### ISSUE TITLE
cross-platform build issue

### ISSUE THREAD

**Issue by f0x52** [superseriousbusiness/gotosocial#101]
My Go gets compiled with (I guess) GLIBC_2.32 on Arch Linux, so that's an issue on the Ubuntu LTS testingtesting123.xyz server: 
`./gotosocial: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./gotosocial-test)`

**Comment by tsmethurst** [comment]
I think this has been solved by https://github.com/superseriousbusiness/gotosocial/commit/03479312f1772f52ffc758b6997317112a6b1d3c which adds some additional parameters to the build script -- in particular, disabled cgo
