### ISSUE TITLE
[bug] Unable to login from Mastodon iOS app

### ISSUE THREAD

**Issue by xplosionmind** [superseriousbusiness/gotosocial#1010]
### Describe the bug with a clear and concise description of what the bug is.

After successfully inserting the credentials in the Mastodon iOS app, the login window disappears and there is no progress.

### What's your GoToSocial Version?

YunoHost 0.5.2~ynh1

### What happened?

![error](https://user-images.githubusercontent.com/42862428/200890420-26d12ab9-1309-46b8-a445-b9ed280f21e3.gif)

### What you expected to happen?

The login should successfully take place

**Comment by tsmethurst** [comment]
Thanks :) We still need someone with an iphone to investigate this, since none of the core devs use iphone :crying_cat_face:

**Comment by june-coloc** [comment]
Hello, not a dev but I have an iPhone and a GTS account!

**Comment by xplosionmind** [comment]
No hurries, I simply switched to Metatext for the moment

**Comment by sargant** [comment]
Had issues myself with GTS 0.5.2 and the Mastodon iOS app. Weirdly, it fails _90%_ of the time - if you try enough times, it does eventually work.

I'm reticent to log out and capture logs now it's working - maybe I'll try later today...
