### ISSUE TITLE
[bug] After losing the media folder avatars from remote instances are not loaded

### ISSUE THREAD

**Issue by imfancat** [superseriousbusiness/gotosocial#1012]
### Describe the bug with a clear and concise description of what the bug is.

After losing the media folder avatars from remote instances are not loaded, 404.

### What's your GoToSocial Version?

GoToSocial 0.5.1-SNAPSHOT git-ad08c6c

### GoToSocial Arch

amd64 Binary

### Browser version

Firefox 107.0

### What happened?

Gotosocial doesn't load avatars after deleting files

### What you expected to happen?

Gotosocial loads avatars after deleting files

### How to reproduce it?

Delete storage folder

**Comment by tsmethurst** [comment]
This will be closed by https://github.com/superseriousbusiness/gotosocial/issues/822 once we get around to doing that
