### ISSUE TITLE
[feature] placeholder for overlarge attachments

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#1013]
### Is your feature request related to a problem ?

I just read a post where I thought they had forgotten to attach a picture.

Turns out they attached a large video, and I didn’t know.

### Describe the solution you'd like.

Put in placeholders for overlong content from external, ideally with a hyperlink to the original file on their homeserver.

Perhaps even do so for overlong posts, truncate them just before the local limit then put in a link.

### Describe alternatives you've considered.

I could raise my limit, but storage space is expensive and I’d like for it to last as long as possible before increasing it.

**Comment by tsmethurst** [comment]
I have a branch open for this :) https://github.com/superseriousbusiness/gotosocial/pull/810

Still testing it out though.

**Comment by mirabilos** [comment]
Ah okay, so that’s also for too large attachments witrh known types? Thanks!

**Comment by tsmethurst** [comment]
> Ah okay, so that’s also for too large attachments witrh known types?

Not yet, but I'll try and fold that in when I start working on that branch again (some other stuff took prio first but I will come back to it)

**Comment by firescry** [comment]
I've just came across this feature proposal I noticed that in part it's similar to solution discussed in #2175 - putting a placeholder for attachments which were not fetched. I'm cross linking them for better traceability :)
