### ISSUE TITLE
[feature] Instance thumbnail from external URL

### ISSUE THREAD

**Issue by xplosionmind** [superseriousbusiness/gotosocial#1019]
### Is your feature request related to a problem ?

No

### Describe the solution you'd like.

The only way to change an instance’s thumbnail is to upload a picture. It would be nice if a custom URL to an external resource could be used.

### Describe alternatives you've considered.

Downloading the desired picture and re-uploading it.

**Comment by tsmethurst** [comment]
I think if we do that we're gonna run into CORS issues and people hot linking and stuff... it seems to me like more trouble than it's worth, since the alternative (downloading + uploading again) is pretty simple :P
