### ISSUE TITLE
[bug] Example systemctl config does not work on Debian

### ISSUE THREAD

**Issue by sargant** [superseriousbusiness/gotosocial#1023]
### Describe the bug with a clear and concise description of what the bug is.

When installing the binary version using the supplied documentation, the service installation steps don't work without further configuration.

### What's your GoToSocial Version?

0.5.2

### GoToSocial Arch

amd64 Binary

### What happened?

Unable to start the systemctl service using the binary installation instructions:

```
root@gotosocial:/opt/gotosocial# systemctl start gotosocial
Job for gotosocial.service failed because the control process exited with error code.
See "systemctl status gotosocial.service" and "journalctl -xe" for details.
```

### What you expected to happen?

Be able to start the service successfully without further configuration

### How to reproduce it?

Follow documented binary service installation instructions on Debian 11

**Comment by owovin** [comment]
Had same results, running `systemctl -u gotosocial.service -b" gave me a constant result of 
```
Nov 11 17:51:48 Sol systemd[1]: Starting GoToSocial Server...
Nov 11 17:51:48 Sol systemd[160355]: gotosocial.service: Failed to set up standard output: No such file or directory
Nov 11 17:51:48 Sol systemd[160355]: gotosocial.service: Failed at step STDOUT spawning /gotosocial/gotosocial: No such file or directory
```
if you can crossreference to the same error, that'll help the developers out 🤝
the service file looks just fine from second/third checking, so i dont know what it would be

**Comment by sargant** [comment]
Alternative PR in #1030 that instead changes the default log path to involve no new subdirectory creation (defaults to a new file in `/var/log`), which should also avoid permissions errors.
