### ISSUE TITLE
[question] Support for ephemeral deployment of server

### ISSUE THREAD

**Issue by joelghill** [superseriousbusiness/gotosocial#1025]
### Is your feature request related to a problem ?

Attempted to deploy the app using the Digital Ocean app platform where each "app" runs as an ephemeral instance.

This doesn't appear to work currently as the GoToSocial server requires local storage for Postgres and Let's Encrypt certificates.

### Describe the solution you'd like.

Perhaps we could configure certificates to be stored in an S3 bucket similar to media?

### Describe alternatives you've considered.

I could simply not deploy the server using the method I described. I would like to easily deploy the server from code though and this would make that easier.

### Additional context.

This work would be a precursor to supporting horizontal scaling of the app. No idea if that's on your roadmap.

**Comment by tsmethurst** [comment]
Heya, if you handle SSL elsewhere, and direct GtS to use an external postgres by setting db-address appropriately, this should eliminate most (if not all?) of the local storage requirements, I think. Did you try this already?

**Comment by theSuess** [comment]
Can verify that by using S3, external postgres and a SSL-Terminating Proxy, GtS does not touch the disk at all.

**Comment by joelghill** [comment]
I may have jumped the gun on requesting a fix here. My database as it is configured to require SSL and it looked like the only way to make a connection to the DB was to have the DB SSL certificate in local storage. I'll play with this more, thank you.

**Comment by joelghill** [comment]
> Heya, if you handle SSL elsewhere, and direct GtS to use an external postgres by setting db-address appropriately, this should eliminate most (if not all?) of the local storage requirements, I think. Did you try this already?

I'm not sure what you mean by "handle SSL elsewhere". I'm considering a solution where I spin up another server as a proxy. It would store the postrges certificate... not sure how to go about that though. Sorry, new to most of this.

**Comment by tsmethurst** [comment]
By handle SSL elsewhere I meant using a reverse proxy for letsencrypt so that GtS doesn't need to store LE certs anywhere :)

But I didn't realize you're also storing postgres certs. Are you running with Docker containers? Because if so, you can just mount your certificate somewhere inside the docker container at runtime, and then GtS still doesn't need to write anywhere.

**Comment by igalic** [comment]
if DigitalOcean's Postgres comes with TLS that can't be turned, there must be a way to import their certificate or their signing CA into the Docker container

**Comment by joelghill** [comment]
> if DigitalOcean's Postgres comes with TLS that can't be turned, there must be a way to import their certificate or their signing CA into the Docker container

A docker deployment through the app platform is also pretty limited. No option to mount a volume or copy files (that I'm aware of).

Honestly, this is likely more trouble that it's worth right now. We can still use Digital Ocean to host through a "Droplet" and it doesn't look like horizontal scaling is on the horizon for GoToSocial any time soon. I'm personally totally fine with closing this issue, there's way more important stuff for ya'll to be spending time on!
