### ISSUE TITLE
[feature] Allow S3 bucket name to be blank to better support CDN with S3 buckets

### ISSUE THREAD

**Issue by joelghill** [superseriousbusiness/gotosocial#1026]
### Is your feature request related to a problem ?

I have configured an S3 storage bucket for server media. I also configured a CDN for said bucket at a subdomain.

When configuring the server, there do not appear to be any settings to allow for the CDN to function correctly. I can set the S3 host to the CDN url, but GTS inserts the bucket name in the media urls and this is inappropriate for the CDN.

### Describe the solution you'd like.

Allow the S3 bucket name to be blank and document this use case in the config file. This should produce correct URLs

### Describe alternatives you've considered.

None

### Additional context.

I can provide my current server config, hostname, S3 bucket, CDN url, etc, if any of that will help.

**Comment by joelghill** [comment]
Did a little bit of research here and it looks like allowing a blank bucket name is probably not going to work, reading and writing to S3 needs a bucket name.

I think the solution here might be to add a new setting for a CDN endpoint. The S3 config would all be the same, however if a CDN is configured creating URLs to read media the CDN endpoint should be used instead of the S3 URL + bucket name.

**Comment by daenney** [comment]
I'm going to close this in favour of #2574 where we've got the generic solution and different use cases documented. If you're still interested in this feature, feel free to subscribe to that issue.
