### ISSUE TITLE
[feature] Open registrations with approval

### ISSUE THREAD

**Issue by xplosionmind** [superseriousbusiness/gotosocial#1027]
### Is your feature request related to a problem ?

So far, admins can either open or close registrations to a GTS server.

Screenshot from my YunoHost configuration panel for GoToSocial app:

![Screenshot 2022-11-12 at 12 02 28 PM](https://user-images.githubusercontent.com/42862428/201471174-cfdbd674-74e7-4dbd-a777-8132fbe6f035.jpg)

### Describe the solution you'd like.

It would be nice to have open registrations but requiring approval, as it happens with Mastodon.

### Describe alternatives you've considered.

Closing registrations and briefly opening them only when I know a friend is going to join, then re-closing them.

**Comment by tsmethurst** [comment]
Right now registration basically just doesn't work at all :P Which is known. Having a proper sign up flow (including open registrations with approval) is something we're gonna do round the end of alpha/beginning of beta when the software is more stable :)

**Comment by tsmethurst** [comment]
I'm gonna close this, since i just realized we already have an issue open for it:

https://github.com/superseriousbusiness/gotosocial/issues/286
