### ISSUE TITLE
[feature] Allow access to public timeline without authorization

### ISSUE THREAD

**Issue by sargant** [superseriousbusiness/gotosocial#1031]
### Is your feature request related to a problem ?

No

### Describe the solution you'd like.

I would like to be able to query `/api/v1/timelines/public` without authorization. Perhaps enabled behind a config flag like `instance-expose-public-timeline` with a default of `false`?

### Describe alternatives you've considered.

NONE

### Additional context.

Suggested PR in #1039

**Comment by tsmethurst** [comment]
closed by https://github.com/superseriousbusiness/gotosocial/pull/1039
