### ISSUE TITLE
Provide docs on how to build GoToSocial

### ISSUE THREAD

**Issue by wioxjk** [superseriousbusiness/gotosocial#1033]
### Is your feature request related to a problem ?

It would be nice with some docs on how to build GoToSocial. I tried look for some but could not find.
I could not find the minimum version of Go that GTS required either.

Background - I tried building GTS on Solaris.

### Describe the solution you'd like.

Short writeup of requirements that is needed to build GTS

### Describe alternatives you've considered.

See above

**Comment by joelghill** [comment]
Seconding this request! I'd like to setup a build and deployment pipeline in my own fork of the project and documentation on the build process would be awesome.

**Comment by tsmethurst** [comment]
The information you're looking for is in the contributing.md document: https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md

But perhaps we should also add a build document somewhere that links to that.

**Comment by tsmethurst** [comment]
I'm gonna close this issue since docs are provided (as linked above) but will bear in mind that we should perhaps add clearer links to building docs in README.md

**Comment by wioxjk** [comment]
Sorry for necroing this thread, but from what I can understand, I should be able to do something like this:

`GOOS=illumos GOARCH=amd64 ./scripts/build.sh`

Right?
However, I am meet with this, not sure what it means.

```
package github.com/superseriousbusiness/gotosocial/cmd/gotosocial
	imports github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/admin/account
	imports github.com/superseriousbusiness/gotosocial/internal/db/bundb
	imports modernc.org/sqlite
	imports modernc.org/libc
	imports modernc.org/libc/errno: build constraints exclude all Go files in /gotosocial/gotosocial/vendor/modernc.org/libc/errno
package github.com/superseriousbusiness/gotosocial/cmd/gotosocial
	imports github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/admin/account
	imports github.com/superseriousbusiness/gotosocial/internal/db/bundb
	imports modernc.org/sqlite
	imports modernc.org/libc
	imports modernc.org/libc/pthread: build constraints exclude all Go files in /gotosocial/gotosocial/vendor/modernc.org/libc/pthread
package github.com/superseriousbusiness/gotosocial/cmd/gotosocial
	imports github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/admin/account
	imports github.com/superseriousbusiness/gotosocial/internal/db/bundb
	imports modernc.org/sqlite
	imports modernc.org/libc
	imports modernc.org/libc/signal: build constraints exclude all Go files in /gotosocial/gotosocial/vendor/modernc.org/libc/signal
package github.com/superseriousbusiness/gotosocial/cmd/gotosocial
	imports github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/admin/account
	imports github.com/superseriousbusiness/gotosocial/internal/db/bundb
	imports modernc.org/sqlite
	imports modernc.org/libc
	imports modernc.org/libc/stdio: build constraints exclude all Go files in /gotosocial/gotosocial/vendor/modernc.org/libc/stdio
package github.com/superseriousbusiness/gotosocial/cmd/gotosocial
	imports github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/admin/account
	imports github.com/superseriousbusiness/gotosocial/internal/db/bundb
	imports modernc.org/sqlite
	imports modernc.org/libc/sys/types: build constraints exclude all Go files in /gotosocial/gotosocial/vendor/modernc.org/libc/sys/types
package github.com/superseriousbusiness/gotosocial/cmd/gotosocial
	imports github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/admin/account
	imports github.com/superseriousbusiness/gotosocial/internal/db/bundb
	imports modernc.org/sqlite
	imports modernc.org/libc
	imports modernc.org/libc/time: build constraints exclude all Go files in /gotosocial/gotosocial/vendor/modernc.org/libc/time
package github.com/superseriousbusiness/gotosocial/cmd/gotosocial
	imports github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/admin/account
	imports github.com/superseriousbusiness/gotosocial/internal/db/bundb
	imports modernc.org/sqlite
	imports modernc.org/libc
	imports modernc.org/libc/unistd: build constraints exclude all Go files in /gotosocial/gotosocial/vendor/modernc.org/libc/unistd
```

**Comment by igalic** [comment]
the prerequisite for bun and SQLite to compile is for libc to be ported to your platform: https://gitlab.com/cznic/libc

**Comment by wioxjk** [comment]
Thank you @igalic for your answer, ofcourse - I should have been able to understand that from the error logs.
But it leads me to the next question - it seems like libc is available on my system at /usr/lib/libc

I assume that I can set some variable in order to point to the location of the library?
I am sorry if this question is in the wrong forum.

**Comment by igalic** [comment]
`/usr/lib/libc` is most likely not modernc.org/libc

that first one is implemented in C, and part of your system. the other one is implemented in go to interact with the C libc

**Comment by wioxjk** [comment]
Thanks,
I reached out, and the author of libc has started builds for OmniOS/Illumos. So builds will hopefully be done in a few hours.

https://modern-c.appspot.com/-/builder/
