### ISSUE TITLE
[feature] API does not expose whether a status is boostable / replyable / local-only

### ISSUE THREAD

**Issue by zxzzxv** [superseriousbusiness/gotosocial#1035]
### Is your feature request related to a problem ?

Right now, there is no API exposed so that a user status may be queried for permissions. This is handy for clients to properly disable those options.

### Describe the solution you'd like.

The underlying data structures store this data, but code that converts between the API and the internal representation still needs to be updated.

### Describe alternatives you've considered.

None considered.

**Comment by tsmethurst** [comment]
Yep good one, we need to add this indeed.

**Comment by tsmethurst** [comment]
For replyable/boostable/likeable, the API has changed thanks to the concept of interaction policies introduced by https://github.com/superseriousbusiness/gotosocial/pull/3108. So that just leaves the "federated" field, which I'll add in a separate PR.
