### ISSUE TITLE
[feature] Import followers/following using csv file

### ISSUE THREAD

**Issue by boerge30** [superseriousbusiness/gotosocial#1048]
The[ Fedifinder](https://fedifinder.glitch.me) from [Luca Hammer](https://vis.social/@luca) creates a .csv file of the Twitter followers/followings, which can then be imported into Mastodon. Could this import function also be built into GoToSocial?

**Comment by simonszu** [comment]
I would not simply +1 this post but also mention that this feature could help users migrate their account to other servers, since they could export their Followinglist from Mastodon instances and import them to GTS

**Comment by tsmethurst** [comment]
Heya, I renamed the issue, hope that's OK!

Currently we plan to implement the Move activity for handling follower/following migrations from Mastodon -> GtS and vice versa, similar to what Mastodon does already, but only once we get to the end of the alpha phase.

At that point we can also consider if we could offer some kind of export/import for lists of followers, but we'll also have to think carefully about the harassment implications of encouraging lists of users to be spread around.

Anyway, until we get to that point, I'm gonna mark this issue as Future Tech so we can come back to it when we get there :)

**Comment by simonszu** [comment]
Sounds good to me. I for myself am currently evaluating GtS as a small
single-user fedi instance which i am mostly using for Mastodon, so:
implicit +1 from me for everything which GtS implements to be on
feature-parity with Mastodon. I'll wait. :)

Am Di., 15. Nov. 2022 um 16:42 Uhr schrieb tobi ***@***.***>:

**Comment by lucahammer** [comment]
While I like the idea, I don't think it's necessary. The API already supports everything that's needed to make it work. Having a web app that does import/export would work just as well. I will try to put something together on the weekend. (Already planned Fedifinder Hardcore with write access to Twitter and GtS to allow people to skip the import step by doing it through the API. I would be open to add that functionality directly to the GtS web frontend as well. Bigger question are the implications of such a feature.). 

Account migration from/to Mastodon on the other hand will be the point where I want to move my main account to GtS. I understand that this is planned at the end of the Alpha and only want to make the point that import/export should not slow down development of core features as layed out in the road map.

**Comment by boerge30** [comment]
Just to be clear: I don't want to stress here ;)

Thanks for your thoughts Luca. I also think mastadon migration is the better way. Then I would favor GoToSocial as my gateway to the Fediverse. I'm excited for what's to come with GoToSocial. Thank you for this exciting project!

**Comment by anantshri** [comment]
For those looking urgently to do this i have a simple option. 

1. use toot cli authenticate to GTS instance 
2. download the csv from fedifinder or old mastodon instance and you can run a loop over `toot follow "@account@domain.name"` and it will do the job for you. 

I know this is not what people want but there is a feature that can do this for you and as others mentioned might not be something to be kept at higher priorities.

**Comment by rsolvang** [comment]
Inspired by @anantshri, I made a tiny bash script to import followers from a CSV export from Mastodon using `toot`:

```
#!/bin/env bash
while read LINE; do
	user=${LINE%%,*}
	toot follow $user
done < following_accounts.csv
```

Beats having to import over 500 followers manually!

**Comment by mkarliner** [comment]
I'd like to implement the solution mentioned by @rsolvang , but I can't find the toot command on
my container version of GTS. Is it extinct?

**Comment by tsmethurst** [comment]
> I can't find the toot command on my container version of GTS. Is it extinct?

toot is not a GoToSocial thing, it's a mastodon-api-compatible command line client application: https://toot.bezdomni.net/

**Comment by almereyda** [comment]
Given a text file `accounts.txt` with one `@username@server.tld` handle per line, this also works:

```sh
xargs -L1 toot follow < accounts.txt
```
