### ISSUE TITLE
unable to follow accounts with appDomain set up

### ISSUE THREAD

**Issue by jk-na** [superseriousbusiness/gotosocial#105]
I've set my GtS instance up using the config.yaml and a different appDomain and host domain and when I attempt to follow anyone (via pinafore or tusky) the instance is logging either `400 Bad Request` or `401 Unauthorized` 

It seems like the request are accompanied with a webfinger request which is using the host domain rather than appDomain.

appDomain: example.org
host: gts.example.org

format of resource=acct:user@gts.example.org rather than user@example.org

If I manually check webfinger for the host formatted account I get an error `"no 'resource' in request query"` whereas if I manually check with the appDomain formatted account (user@example.org), I get the correct account record returned.

nginx redirects work for appDomain to host for .well-known/webfinger and .well-known/nodeinfo

When I try to log in to either pinafore or tusky using the appDomain, I get an error, only logging in via the host url works.

pinafore error: `Error: NetworkError when attempting to fetch resource.. Is this a valid Mastodon instance? Is a browser extension blocking the request? Are you in private browsing mode? If you believe this is a problem with your instance, please send this link to the administrator of your instance.`

tusky error: `Failed authenticating with that instance`

**Comment by jk-na** [comment]
Additionally, when I search for @user@example.org from pleroma I see the webfinger GET with the correct account accompanied by a GET for the profile page which both have 200 codes.  However, the account doesn't appear on the search.

It doesn't appear in a mastodon search either, with the same as above but with an additional webfinger for account@gts.example.org

Pixelfed for some reason sends an incorrectly formatted webfinger request so obviously doesn't get far.

**Comment by tsmethurst** [comment]
I'll have a look into it and get back to you :) thanks for raising this
