### ISSUE TITLE
[feature] Run GTS on a subdomain but use @domain as identifier

### ISSUE THREAD

**Issue by maop** [superseriousbusiness/gotosocial#1055]
### Is your feature request related to a problem ?

Hello, 
I wish to use GTS as a single-user instance with my personal domain, but i already have a site there.

### Describe the solution you'd like.

So, it'd be very useful if one could be able to install GTS on a sub.domain.tld but use user@domain.tld as the identifier for the Federated network.

### Describe alternatives you've considered.

NONE

### Additional context.

i know mastodon do this by adding two variables:

LOCAL_DOMAIN=domain.tld
WEB_DOMAIN=sub.domain.tld

And a redirection on the .well-known/host-meta if i understood correctly this pull https://github.com/mastodon/mastodon/pull/1267

**Comment by PythonLinks** [comment]
I need this too!  I was just about to fire up your GoToSocial on a subdomain. 
Now I am thinking, what magic is this, how is it possible.  You tell the world you are at some domain, but actually you are at a sub domain. 

I would like to say I am very impressed with how fast this software is evolving.  
And I am particularly impressed that it can run on  a small server.

**Comment by anantshri** [comment]
This is already in production. 

https://social.anantshri.info/@anant this is my instance running on a subdomain with id mapped to a specific domain.

https://github.com/superseriousbusiness/gotosocial/blob/main/example/config.yaml#L50 Check this setting option.

**Comment by maop** [comment]
> This is already in production.
> https://github.com/superseriousbusiness/gotosocial/blob/main/example/config.yaml#L50 Check this setting option.

OH WOW!  i swear i search it in the issues and read the entire installation guide and didn't see this. Thank you pointing it out !

Kudos to the team!
