### ISSUE TITLE
[bug] Logging stops after rotation

### ISSUE THREAD

**Issue by erkattak** [superseriousbusiness/gotosocial#1060]
### Describe the bug with a clear and concise description of what the bug is.

After log file rotation, no further logs are written to the specified file.

### What's your GoToSocial Version?

v0.5.2

### GoToSocial Arch

amd64 Binary

### Browser version

Firefox 108.0b1 (64-bit)

### What happened?

Logs stopped appending to the specified file (`/var/log/gotosocial/gotosocial.log`)

### What you expected to happen?

Logs continue to append to the specified file (`/var/log/gotosocial/gotosocial.log`)

### How to reproduce it?

Running on Ubuntu 22.10

Here's the logrotate file, which I'm sure could be modified to rotate much sooner for testing purposes.
`/etc/logrotate.d/gotosocial`
```
/var/log/gotosocial/*.log {
        daily
        missingok
        rotate 14
        compress
        delaycompress
        notifempty
}
```

**Comment by lochiiconnectivity** [comment]
Is the new logfile being created with the same permissions and mode as the old one being rotated had?

**Comment by erkattak** [comment]
It is created with the same permissions. However, after checking again, it looks like the rotated file continues to be written to
```
-rw-r--r--  1 root root         0 Nov 16 15:51 gotosocial.log
-rw-r--r--  1 root root   1104653 Nov 16 15:52 gotosocial.log.1
```
In this case, `gotosocial.log.1` continues to receive new log lines.

**Comment by lochiiconnectivity** [comment]
Hoping you are not running gotosocial as root anywhere (even inside a container).

Based on what you've said regarding the old logfile, you can try using the `copytruncate` option.

Personally I would switch to syslog and create a syslog file to write the logs to this file, then `copytruncate` is not needed, modern syslog daemons handle this properly. 

Example using syslog:

config.yaml:

```
syslog-enabled: true
syslog-protocol: "udp"
syslog-address: "127.0.0.1:514"
```

/etc/rsyslog.d/90-gotosocial.conf:
```
if $programname == 'gotosocial' then /var/log/gotosocial/gotosocial.log
```

/etc/logrotate.d/gotosocial:

```
/var/log/gotosocial/*.log {
        weekly
        missingok
        rotate 52
        compress
        delaycompress
        notifempty
        create 640 syslog adm
        sharedscripts
        endscript
}
```

**Comment by EchedeyLR** [comment]
My current working config:
```
/var/log/gotosocial/gotosocial.log {
        daily
        missingok
        rotate 7
        compress
        copytruncate
        notifempty
        create 640 root root
}
```

**Comment by igalic** [comment]
instead of `copytruncate`, you could also tell logrotate to reload gotosocial

**Comment by tsmethurst** [comment]
@erkattak Shall i close this if you're happy with the proposed config solutions?

**Comment by erkattak** [comment]
@tsmethurst yes, thanks!
