### ISSUE TITLE
[Client Compatibility] Soapbox

### ISSUE THREAD

**Issue by xmgz** [superseriousbusiness/gotosocial#1064]
### Describe the bug with a clear and concise description of what the bug is.

I've **succesfully** logged in https://fe.soapbox.pub/

it's a web front end https://gitlab.com/soapbox-pub/soapbox

I've not tested all available options in config (some are not GTS supported yet). **I can read** my TLs, but apparently posting does **not** work.

I open this issue just to let you know, as I've not found any issue/report here https://github.com/superseriousbusiness/gotosocial/projects

thanks

### What's your GoToSocial Version?

GoToSocial 0.5.2 git-c31f219

### GoToSocial Arch

arm

### Browser version

tested on chromium

### What happened?

I've try to access my gts instance from https://fe.soapbox.pub/ and succeded

### How to reproduce it?

try to access your instance

**Comment by boerge30** [comment]
I just tried it with my GoToSocial instance... Works!

![SCR-20221117-94z](https://user-images.githubusercontent.com/9784885/202365358-05e4a8b9-2e5c-47ef-8e85-5f97ecdc9b8a.png)

GoToSocial 0.5.1-SNAPSHOT git-81c1fe0

**Comment by NyaaaWhatsUpDoc** [comment]
If there's an issue on gotosocial's side you can determine, feel free to create a ticket, but otherwise we will not be doing anything to ensure compatibility with soapbox I am afraid. This is nothing against you as users, this is a case of the author being a known transphobe and bigot, and last time we turned them down for a development request they doxxed some of our devs. They are not people we would like to work with.

**Comment by xmgz** [comment]
Sorry, my intention was **reporting** about this client, as some others in "_Projects_" section, and opened an issue here as I can not open a ticket in projects section (I don't even know how to do it).

**I was not asking GTS support for this client.**

Thank you

Didn't know about its author, but is totally understable your decision (as gts developers).

Please excuse me as didnt mean to bring such topic/issue here. I will close the issue.

**Comment by tsmethurst** [comment]
No worries :)
