### ISSUE TITLE
[Client Compatibility] Sengi

### ISSUE THREAD

**Issue by anantshri** [superseriousbusiness/gotosocial#1069]
Hello Folks,

Just a note from my observations around sengi. (https://github.com/NicolasConstant/sengi)

This particular tool works great with GotoSocial except a few warnings for example it reverts to using v1 api endpoint for search which gives a 404. 

We do have the right api endpoint on v2 and it should work however digging deep in the code it seems the rely on mastodon version reported by the server https://github.com/NicolasConstant/sengi/search?q=instance.major+%3E%3D+3%29 and if version is less them 3 they use API v1. Not sure if we want to address this by switching around our reported version number for better client compatibilities but just wanted to put it out

1. Sengi good for daily use with occasional errors which doesnt hamper the working.
2. errors mostly coz we advertise a version which they interpret as very old version of mastodon.

screenshot of error message 
![image](https://user-images.githubusercontent.com/236843/202462503-a7e0e209-96d7-4808-8db7-a542c6c974a5.png)

**Comment by whtiehack** [comment]
+1

![image](https://user-images.githubusercontent.com/12741016/202654868-1a1583f5-15de-463d-b8a7-88c877317610.png)

**Comment by EchedeyLR** [comment]
@whtiehack I believe you should open a different issue instead of posting here. The client is neither the same nor the error is similar.

**Comment by whtiehack** [comment]
> @whtiehack I believe you should open a different issue instead of posting here. The client is neither the same nor the error is similar.

You're right. I'm sorry.

**Comment by anantshri** [comment]
I think with v0.10 i have not seen these errors. search is also working fantastic. we can close this.

thanks for reminder @tsmethurst
