### ISSUE TITLE
[chore] Remove unused m2m tables `status_to_emojis` and `account_to_emojis`

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#1075]
Since https://github.com/superseriousbusiness/gotosocial/pull/1073 and https://github.com/superseriousbusiness/gotosocial/pull/1074 we don't use those tables for selecting via bun's relations API anymore, so we should be able to just drop the tables.

**Comment by voigt** [comment]
I created a PR to tackle this.

However, looks like it's not only dropping the table. There are still some code paths referencing the tables:

- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/bundb/status.go#L300
- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/bundb/emoji.go#L81
- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/gtsmodel/status.go#L40 (btw. what is m2m?)
- ...
- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/bundb/account.go#L195
- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/bundb/account.go#L228
- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/bundb/emoji.go#L90
- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/gtsmodel/account.go#L45

If you agree, I'd remove them as well.

**Comment by tsmethurst** [comment]
I'm gonna close this one now, since we've decided to keep some of those intermediary tables around, as they're actually useful for things other than just doing m2m relations.
