### ISSUE TITLE
[feature] OStatus Subscribe Flow

### ISSUE THREAD

**Issue by theSuess** [superseriousbusiness/gotosocial#1090]
### Is your feature request related to a problem ?

Mastodon presents the user with a follow button which initiates the OStatus subscribe flow on the users home instance. This allows users to directly follow accounts from other instances without having to search for them in their own client.

### Describe the solution you'd like.

By implementing the ostatus subscribe flow (not sure what it is called exactly - quite hard to find documentation), users can use this functionality with GtS

### Describe alternatives you've considered.

NONE

### Additional context.

Implementing this is quite straight forward, however an important decision has to be made:

* Implement this as a react application (performing the authentication flow on the client side, requiring JS for this functionality)
* Implement this as a server-rendered widget (requiring a middleware to perform the OAuth flow)

**Comment by noerw** [comment]
I'm not well informed on this topic and I'm not involved with gts (yet 🙃), so sorry for the driveby comment:

Afaik the way mastodon implements this is in flux currently:

- Mastodon changed in v4.0 the way this works - if I understand correctly they dropped support for OStatus subscribe flow. https://chaos.social/@rixx/109373534827549588
    - This led to breakage in a browser plugin simplifying this flow https://github.com/rugk/mastodon-simplified-federation/pull/82

- There is a proposal at mastodon to make this work differently via protocol handlers in the web UI (which arguably doesn't apply to GTS much as it doesn't have its own webui): https://github.com/mastodon/mastodon/issues/19679

I'm just posting this here for reference, as this seems like a thing that needs consideration what the ecosystem implements, and might be an opportunity to influence that a bit for gts needs

**Comment by tsmethurst** [comment]
Going to close this because it's unlikely we'll end up supporting it. We can reopen if there's more demand for it.
