### ISSUE TITLE
[performance] replace bun relational queries with separate db calls to better utilitise caching

### ISSUE THREAD

**Issue by NyaaaWhatsUpDoc** [superseriousbusiness/gotosocial#1094]
An example of this can be seen here: https://github.com/superseriousbusiness/gotosocial/blob/9be16852f212f56637fd4a41f3361d30ce7deb5c/internal/db/bundb/account.go#L151

Database areas still requiring this
- [x] Accounts (partially done)
- [x] Emoji
- [x] Media
- [x] Mention
- [x] Relationships (partially done)
- [x] Statuses (partially done)
- [x] User

As part of this work you should also take into account the following issue #1095, so that when filling in related models you are only filling in the bare minimum instead of a full tree of populated models.

**Comment by NyaaaWhatsUpDoc** [comment]
Account blocks (part of relationships) are currently being handled in #1085

**Comment by tsmethurst** [comment]
We've sort of been working on this one again lately. Should we add it to the 0.11.0 milestone?
