### ISSUE TITLE
[chore] create "State" type to better consolidate dependency injection

### ISSUE THREAD

**Issue by NyaaaWhatsUpDoc** [superseriousbusiness/gotosocial#1097]
The initial work is currently being handled in #1078.

Benefits that will come from this move to passing round a singular state:
- easier to manage caches, whether that be start/stop, invalidations of multiple caches (e.g. status gts and AP model caches)
- simplify module initializations, instead of long `New(...)` argument counts
- simplify module access across the codebase

Still remaining to move to this singular state is:
- [ ] API Modules (?)
- [ ] Configuration
- [ ] HTTPClient
- [ ] Federator
- [ ] Federating DB
- [ ] Log (?) (this is one of those areas where globals can be useful)
- [ ] Media Manager
- [ ] Processor
- [ ] Router (?)
- [ ] Storage
- [ ] Timeline
- [ ] Transport Controller
- [ ] Type Converter
- [ ] Visibility Filter
- [ ] Worker queues

**Comment by NyaaaWhatsUpDoc** [comment]
This work (particularly, the contents of #1078) is currently hindering #394. Once the work of that initial PR is completed I will be able to properly refactor the timeline code in a manner that lets me fetch / invalidate required status models.

**Comment by tsmethurst** [comment]
We've done this now, right? I think? Should we close this?
