### ISSUE TITLE
[feature] Windows binary

### ISSUE THREAD

**Issue by hsn10** [superseriousbusiness/gotosocial#1098]
### Is your feature request related to a problem ?

Distribute Windows binary with pgsql or sql lite dB. SQLite would be better.

### Describe the solution you'd like.

Windows zip file

### Describe alternatives you've considered.

Misskey

**Comment by NyaaaWhatsUpDoc** [comment]
This software will not work on Windows, I know of at least one of the libraries we depend on that doesn't support it.

**Comment by tsmethurst** [comment]
Yeah agreed, I think it's going to cause way more headaches than it's worth. If someone else wants to do PRs and checks and do support for Windows then OK, but none of the core devs use Windows.
