### ISSUE TITLE
[bug] Can't edit profile or account settings using Metatext

### ISSUE THREAD

**Issue by daenney** [superseriousbusiness/gotosocial#1100]
### Describe the bug with a clear and concise description of what the bug is.

When logged in on Metatext I can't manage my profile or go to account settings.

### What's your GoToSocial Version?

0.5.2

### GoToSocial Arch

amd64 binary

### Browser version

Firefox 107.0 (64-bit)

### What happened?

Trying to use the "Edit profile" Metatext says "Metatext would like to login using 'https'" and then opens up an embedded browser trying to reach "https". This doesn't work. The same happens with "Account settings".

### What you expected to happen?

Being able to edit my profile. Based on the ROADMAP document I was under the impression this should work.

### How to reproduce it?

* Login to Metatext
* Tap your account icon in the top left
* Try "edit profile"

**Comment by cimm** [comment]
New to the fediverse but I noticed the same issue with `Edit Profile`. The next option, `Account Settings` does open the GoToSocial page and works for me. Not sure what the difference should be between `Edit Profile` and `Account Settings` since the latter already seems to offer the full user settings as far as I can tell. Should both link to the same GoToSocial embedded webpage?

**Comment by daenney** [comment]
Hah. Metatext 1.7.0 was released _today_ which fixes the "Account Settings" case. It's partially fixed the "Edit Profile" action too in that at least it now tries to load a sensible URL, but now gets a 404.

**Comment by daenney** [comment]
Trying "Edit Profile" tries to load `/settings/profile` which 404s. "Account Settings" tries to load "/user" which works. I'm guessing that if GTS would add a route that makes `/settings/profile` the same as `/user` it would solve the issue. But it feels like those are intended to be distinct?

**Comment by daenney** [comment]
Though Metatext is gone, with the 0.10.0-rc and the current testflight of Feditext things work properly. Closing this.
