### ISSUE TITLE
[docs] docker compose with frontend web ui

### ISSUE THREAD

**Issue by KyleTryon** [superseriousbusiness/gotosocial#1104]
I may try this one myself, would love to see if anyone here is already doing this and would like to share what they already have. GoToSocial _should_ theoretically work with several front-ends (maybe), such as [soapbox](https://gitlab.com/soapbox-pub/soapbox). If anyone has tried this already and would like to share, I think this would be a great docs addition and I'd like to see it.

I'll probably be trying this shortly.

**Comment by tsmethurst** [comment]
Hello! Re: soapbox specifically, we have no interest in supporting or promoting it since it's made by an anti-trans bigot :P

Re: including a frontend in general, we'll have some sort of announcement in the works in the nearish future (tm) :)
