### ISSUE TITLE
Is there any open instance for us to try gotosocial?

### ISSUE THREAD

**Issue by MamaShip** [superseriousbusiness/gotosocial#1108]
I am a mastodon instance admin who is looking for fediverse alternatives.

I wanna try gotosocial without deploying one. 

Is there any instance open for registration? Or where to find gotosocial instances?

**Comment by ppetermann** [comment]
I'm new here, so take my answer with some caution, but feature wise gotosocial doesn't seem to support registration other than the admin adding someone on cli yet. 

in the pullrequests you'll find a faq thats being worked on, which has a list of features gotosocial is still missing, i think that gives a good overview on how it will compare to a mastodon instance.

for the end user itself the experience mostly depends on what client you are using - you can use all of those clients with your mastodon instance too - the main difference is that some of the things won't work on gotosocial (yet).

**Comment by tsmethurst** [comment]
Heya, we've got no open instances yet. Once we're out of alpha we might put one together, but we're v. much still testing + coding intensely and don't wanna deal with the moderation burden of having an open instance rn :)

**Comment by EchedeyLR** [comment]
I am hosting an open GTS intance, but it is down by now.

If I get to put the computer up again, you could try to register there or I can register an account for you.

**Comment by MamaShip** [comment]
> I am hosting an open GTS intance, but it is down by now.
> 
> If I get to put the computer up again, you could try to register there or I can register an account for you.

Thanks! It's good to have an open instance that any new user can try out. Maybe one day I'll create an instance like this.

I'm a go programmer too. I'll see if I can help with development.
