### ISSUE TITLE
[bug/investigation] doing `gotosocial admin account confirm` can break an account

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#1110]
See: https://github.com/superseriousbusiness/gotosocial/issues/1106

**Comment by jcn** [comment]
Running 0.6.0-rc1 (docker):

Creating a new user using the command from the documentation works properly:

```
docker exec -it gotosocial /gotosocial/gotosocial admin account create --username some_username --email someone@example.org --password 'some_very_good_password'
```

Running the (unnecessary on 0.6.0-rc1) confirm step seems to wipe out the email address for that user, which then prevents login: 

```
./gotosocial --config-path ./config.yaml admin account confirm --username some_username
```

I tried to update the account again using sqlite to add the email address back in, but had trouble with that so I ended up giving up and just blowing away the install.
