### ISSUE TITLE
[feature] Bookmarks

### ISSUE THREAD

**Issue by matthewp** [superseriousbusiness/gotosocial#1112]
### Is your feature request related to a problem ?

Mastodon supports bookmarks in the form of:

```
/api/v1/statuses/[id]/bookmark
```

### Describe the solution you'd like.

Implement the API

### Describe alternatives you've considered.

NONE

### Additional context.

Currently hitting `/api/v1/statuses/[id]/bookmark` gives a 404.

I'd possibly be willing to take on the work for this, if given a little guidance. Thank you!

**Comment by tsmethurst** [comment]
Yeah I think I just made a typo in the roadmap tbh :')

**Comment by matthewp** [comment]
Typo by marking it out as to not be implemented, you mean?

So you'd accept a contribution for this?

**Comment by tsmethurst** [comment]
Yes exactly :D And for sure!

**Comment by matthewp** [comment]
Little update here, I have bookmarking and unbookmarking locally. I still need to:

* Write tests for the POST handlers
* Implement GET

But good progress, very happy with how easy GoToSocial is to contribute to.

**Comment by dmacvicar** [comment]
>But good progress, very happy with how easy GoToSocial is to contribute to.

Hey @matthewp , may be you can share a bit about your local dev setup. eg how you test locally with a client?

**Comment by matthewp** [comment]
I haven't been testing with a frontend. Just running the test suite. I would think you could run [Pinafore](https://github.com/nolanlawson/pinafore) and point it at a locally running instance if you wanted full end-to-end testing.

**Comment by matthewp** [comment]
PR https://github.com/superseriousbusiness/gotosocial/pull/1168
