### ISSUE TITLE
[bug] Cannot login in to multiple gotosocial instances from a multiple account capable client

### ISSUE THREAD

**Issue by hiredman** [superseriousbusiness/gotosocial#1114]
### Describe the bug with a clear and concise description of what the bug is.

when I run 2 gotosocial instances, I can log into one just fine with a client (pinafore, tusky) but if I try to use the multiple account support in the client to login into a second gotosocial instance, I get errors suggesting I clear session cookies or whatever.

who knows how to clear cookies from tusky (android app), and if I clear cookies from pinafore then I get logged out of the first account.

### What's your GoToSocial Version?

gotosocial version 0.5.2 git-c31f219

**Comment by tsmethurst** [comment]
> instance

do you mean 2 different accounts on the same instance, or do you mean 2 different accounts on different instances?

>  I get errors suggesting I clear session cookies or whatever.

could you copy and paste the errors? it's rather difficult to help debug your issue otherwise

**Comment by hiredman** [comment]
2 separate instances with different accounts

I can't reproduce it now.

Both tusky and pinafore logged right in when I tried to reproduce it today to get the exact message from gotosocial. Could reproduce it all the time yesterday :/

sorry for the noise
