### ISSUE TITLE
[feature] Custom Admin OIDC Groups

### ISSUE THREAD

**Issue by dwmunster** [superseriousbusiness/gotosocial#1121]
### Is your feature request related to a problem ?

Currently, [internal/api/client/auth/callbacks.go](https://github.com/superseriousbusiness/gotosocial/blob/50dc179d332af4a3dc0e69e2c4e39bbbccd3fec5/internal/api/client/auth/callback.go#L225-L230) uses a hardcoded list of groups to determine if the user is an admin (namely `"admin"` and `"admins"`). For some IDPs, groups may be returned as more opaque identifiers, rather than human-friendly names. Therefore, such users are unable to be made admins without manual intervention.

### Describe the solution you'd like.

The list of group names that are made admins should be configurable.

### Describe alternatives you've considered.

None.

### Additional context.

If this feature is of interest, I would be glad to contribute code implementing it.

**Comment by tsmethurst** [comment]
Thanks for opening this :)

We've got a few things open for OIDC at the moment which this fits in to, so I'm gonna link 'em here to help us keep track

#309 #961 https://github.com/superseriousbusiness/gotosocial/issues/763

**Comment by decentral1se** [comment]
I think this was solved in https://github.com/superseriousbusiness/gotosocial/pull/961

https://github.com/superseriousbusiness/gotosocial/blob/282be6f26dd4dfb57c3a21b92b756c40c05b2e6c/internal/api/auth/callback.go#L285-L296

https://github.com/superseriousbusiness/gotosocial/blob/282be6f26dd4dfb57c3a21b92b756c40c05b2e6c/example/config.yaml#L693-L696
