### ISSUE TITLE
[bug] Looking up certain accounts crashes gotosocial

### ISSUE THREAD

**Issue by NoraCodes** [superseriousbusiness/gotosocial#1122]
### Describe the bug with a clear and concise description of what the bug is.

Looking up some accounts (like `@oathboundFamiliar@gender.systems`) causes GoToSocial to crash with no error output. I start seeing 502 errors for a while until systemd can restart it.

### What's your GoToSocial Version?

0.5.2 git-c31f219

### GoToSocial Arch

amd64 Binary

### Browser version

106.0.4 (64-bit)

### What happened?

I entered `@oathboundFamiliar@gender.systems` into the Pinafore search box and got no results and a network error.

### What you expected to happen?

I expected the account to show up in search, as many others do.

### How to reproduce it?

Search for ``@oathboundFamiliar@gender.systems`.

### Anything else we need to know?

Attached HARs and related screenshot.

**Comment by tsmethurst** [comment]
Hey, your access token was in the screenshot :grimacing:

**Comment by NoraCodes** [comment]
lol, lmao, etc.
![Screenshot_20221122_155749](https://user-images.githubusercontent.com/3290365/203431664-1bc1cf71-6204-450b-9a13-f470c621fce9.png)

**Comment by tsmethurst** [comment]
I *think* this might be fixed on current main (soon to be released); at least, i managed to search for the user with no issues :) But I'll keep an eye on this. I'm currently refactoring some of the search code anyways to catch little bugs and makes things smoother.

**Comment by themisir** [comment]
> lol, lmao, etc.
> ![Screenshot_20221122_155749](https://user-images.githubusercontent.com/3290365/203431664-1bc1cf71-6204-450b-9a13-f470c621fce9.png)

it's still visible on github issue edit history (not that I checked)

**Comment by tsmethurst** [comment]
Is this still a thing that happens with the latest release candidate? Just wanna check before 0.6.0
