### ISSUE TITLE
[bug] Previous posts from the federated users are not loading

### ISSUE THREAD

**Issue by themisir** [superseriousbusiness/gotosocial#1138]
### Describe the bug with a clear and concise description of what the bug is.

First of all the main reason I opened this issue is I am wondering if this is the expected behavior or I messed up somewhere. TLDR what's happening is I can follow people but their feed is generally empty compared to my experience on the existing activitypub (mastadon to be exact) servers. However I am not sure if that's really a bug or a feature (it might be working as "expected" because those servers were around for a long time that they got most of the user updates from other federated popular nodes?), I am not fully familiar with activity pub. I've included more details below. I can provide more details if needed.

### What's your GoToSocial Version?

v0.5.1-SNAPSHOT git-3e82196

### GoToSocial Arch

Docker (in kubernetes)

### Browser version

Safari 16.1

### What happened?

When I want to check out one's profile I can see their profile metadata but the feed is mostly empty. In addition to the feed the follow stats are also incorrect (only shows 1 follower if I'm following otherwise 0). I only see posts that's been published after I started following them which seems like GTS doesn't fetches old posts?

### What you expected to happen?

I expected GTS to work as similar to mastodon instances which itself works like a conventional social media: when you visit a profile you see their timeline and their public profile details & stats.

### How to reproduce it?

I am not really sure if this is a feature, bug or a missing implementation. If that shouldn't happen I can try setting up another instance to see if it happens again. I just followed the installation instructions and docker-compose sample to setup it on my k8s cluster.

**Comment by tsmethurst** [comment]
Heya, this is normal: you will only see new posts + boosts + replies from people after you've subscribed to them. We have an issue open for backfilling -- #266 -- but since this isn't really a bug, just a known thing that's not implemented yet, I'm gonna close this if that's ok :)

**Comment by themisir** [comment]
Sure, thanks for the explanation!
