### ISSUE TITLE
[feature] Multiple domains

### ISSUE THREAD

**Issue by erlend-sh** [superseriousbusiness/gotosocial#1141]
### Is your feature request related to a problem ?

[Takahe](https://github.com/jointakahe/takahe) is a new ActivityPub server with support for multiple domains on the same server (“virtual hosting”).

### Describe the solution you'd like.

I wonder if this could be replicated in gts. Virtual hosting of multiple domains on a single ActivityPub server removes the need to run a whole new server for every person or organisation that brings their own domain.

### Describe alternatives you've considered.

none

**Comment by tsmethurst** [comment]
Neat :eyes:

**Comment by LittleFox94** [comment]
I tried having an alias by having a (very naive and static) webfinger document at my website domain, listing `me@website` and my GtS handle. Combining this with a way for GtS to recognize such aliases could be a first minimal version of this? Every user has a `username@gts` handle and can add any `whateverUser@whateverDomain` by first having the webfinger somewhere else, pointing to `username@gts`?

~~Trying to interact with `me@website` from Mastodon works ok-ish, it redirects me to my GtS handle - but trying to interact with `me@website` from my GtS instance crashes GtS ..~~
Oh this apparently works now in GtS as well

**Comment by nileshtrivedi** [comment]
+1 for this feature request.

Many communities want to have their own identity but they don't have the tech know-how to set up and maintain the tech infra. Support for multiple domains will allow a few developers to provide ActivityPub access to many groups.

I'm currently looking at doing this with Takahe and Elk, but it would be great to have this in GoToSocial which is much easier to build and deploy.

**Comment by nileshtrivedi** [comment]
On second thoughts, the same can be achieved by multiple process instances and separate config files.

**Comment by NyaaaWhatsUpDoc** [comment]
given the direction we aim to support with gotosocial (scaling down), supporting multi tenant multi domain setups like this, given the ease of just running multiple gotosocial docker instances (it's ridiculously low resource usage), is really not something i personally want to see in the codebase.

it's really not something i'm interested in supporting.

**Comment by tsmethurst** [comment]
I'm gonna close this since, at this point, it looks unlikely to be something we'll ever implement. But we can always open it again later if we change our minds :)
