### ISSUE TITLE
[feature] Configuration option to disable static pages / public web interface

### ISSUE THREAD

**Issue by afontenot** [superseriousbusiness/gotosocial#1144]
### Is your feature request related to a problem ?

This looks like a wonderful project (congrats!) and very close to something I'd like to try using. I especially like the focus on providing a high quality, performant backend that allows you to use your choice of app through the Mastodon API.

That said, I (and perhaps others) who are looking for an ActivityPub backend don't necessarily need or want our posts to be published on a webpage. Maybe we don't want our instance to be visible on the web at all!

### Describe the solution you'd like.

A true / false config option that allows disabling all HTML pages that would normally be rendered by GoToSocial.

### Describe alternatives you've considered.

Since in most cases GoToSocial is probably behind an nginx proxy, it seems like it would probably be possible to set an nginx configuration that only proxies select requests. (E.g. anything under `/api`, paths mentioned in the ActivityPub spec, the finger URL...)

This seems harder to get right and makes more assumptions than just providing an option within GoToSocial.

### Additional context.

I looked through the docs that seemed relevant to the topic and read through the current example config file in the repository, and didn't see anything related to this. A search didn't turn up anything either. If I missed something, maybe take this as a docs improvement request? Thanks!

**Comment by tsmethurst** [comment]
Hiya, I'm gonna close this in favor of #3249. I don't think adding an option for hiding *all* webpages is something we'd want to do, and as you said, admins can always hide stuff with nginx if they really need to.
