### ISSUE TITLE
[bug] unordered Favorites

### ISSUE THREAD

**Issue by xmgz** [superseriousbusiness/gotosocial#1151]
### Describe the bug with a clear and concise description of what the bug is.

favorite post list elements are not ordered on chronological descent order (as expected)

### What's your GoToSocial Version?

GoToSocial 0.5.2 git-c31f219

### Browser version

any

### What happened?

using pinafore, tusky, ... I went to review my _FAV list_ searching for a recent fav and noticed that it was way down the list.

asked about it in matrix room and I was informed that it was a old issue with low priority (that's fine for me) and invited to **open here an issue** so it can be tracked.

### What you expected to happen?

favorite post correctly time based ordered. Preferebly order by the moment user favorites them (in my opinion), not the original post time stamp.

### How to reproduce it?

go to your favorites and check

**Comment by tsmethurst** [comment]
Thanks for opening :)
