### ISSUE TITLE
[bug] List items on toots published by GTS not read out by screen reader using Pinafore

### ISSUE THREAD

**Issue by bingen13** [superseriousbusiness/gotosocial#1171]
### Describe the bug with a clear and concise description of what the bug is.

Some Markdown elements such as list items and verbatim text are not read when using Pinafore and a screen reader as a client.

### What's your GoToSocial Version?

0.5.2

### GoToSocial Arch

arm64 binary

### Browser version

Firefox 107.0 64 bit.

### What happened?

When using Markdown for GTS (GoToSocial 0.5.2 git-c31f219) posts , some elements are not correct read by the screen reader on Pinafore (Version 2.4.0).

However, using the blockquote feature, or the asterisks for italics, works fine.

### What you expected to happen?

Pinafore should read the entire toot including elements such as list items and verbatim text.

### How to reproduce it?

For example, this toot contains verbatim text and a Markdown list: https://node.isonomia.net/@modulux/statuses/01GK1SGK3ZKPQNRCT7AX7F9PHR

Pinafore only reads out: "Testing for GTS issue. And this is normal text." Skipping the verbatim text and the two list items.

### Anything else we need to know?

As a hypothesis the problem could be on Pinafore doing some html filtering, or GTS preparing the summary object for the toot.

**Comment by tsmethurst** [comment]
Hiya, I'm gonna close this one, since I don't believe it's actually our issue, but probably a combination of a Pinafore issue + whichever screen reader you're using. I'm not really sure what to do about it from GtS's side, since we're just providing pretty basic HTML elements for lists and verbatim text, nothing fancy at all.
