### ISSUE TITLE
[bug/0.6.0-rc1] Error mentioning accounts with uppercase chars in username

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#1172]
```
timestamp="29/11/2022 15:01:44.598" func=status.(*processor).ProcessMentions level=ERROR msg="ProcessMentions: error parsing mention @PeePee@poopoo.org from status: error dereferencing account: database error during dereferencing: GetRemoteAccount: error putting new account: already exists"
```

**Comment by tsmethurst** [comment]
Narrowed this down: https://github.com/superseriousbusiness/gotosocial/blob/8d581deb28eda62f1434ef95f32baf61f885d0ba/internal/db/bundb/account.go#L105

We store usernames in the db as we see them from remote instances (so, can include uppercase), but we're always selecting here assuming username is lowercase, so the select returns db.ErrNoEntries, and then the dereferencer tries to go and fetch the account. Then it can't insert it, because it's already there :D

**Comment by Fastidious** [comment]
Easy fix! (I think, LOL)
