### ISSUE TITLE
[bug/0.6.0-rc1] Profile settings css issues in Safari

### ISSUE THREAD

**Issue by Fastidious** [superseriousbusiness/gotosocial#1175]
### Describe the bug with a clear and concise description of what the bug is.

The profile screen has UX issues. See:

<img width="1012" alt="Screenshot 2022-11-29 at 10 46 14" src="https://user-images.githubusercontent.com/8352292/204575939-19e0ca9c-f9f3-41e0-84ab-edda6d3b9ec2.png">

### What's your GoToSocial Version?

v0.6.0-rc1

### GoToSocial Arch

amd64

### What happened?

Went to profile, saw screen as above

### What you expected to happen?

I expected to see a profile screen that allowed me to upload avatar and banner images.

### How to reproduce it?

Go to https://instance/user.

**Comment by tsmethurst** [comment]
This looks like you only did a partial update of the frontend assets. Are you running with docker, or the tarred binary/assets? If the latter, make sure you untar all the assets/css properly + replace any existing css/js files with the new ones.

**Comment by tsmethurst** [comment]
hmm, which browser are you using?

**Comment by Fastidious** [comment]
Found the bug! It only happens on Safari.

**Comment by tsmethurst** [comment]
> It only happens on Safari.

alright :) will try to get a fix in before the release proper, thanks!

**Comment by kingmath** [comment]
Same issue with Safari in iOS 15.7.1.
Screen was photographed in two parts.

![IMG_0164](https://user-images.githubusercontent.com/16158664/204657453-acff385c-bf04-4282-b62d-cb4ce3a4bb43.jpeg)

![IMG_0165](https://user-images.githubusercontent.com/16158664/204657478-b3677db6-7c1d-4b6a-9d22-22e78e02e974.jpeg)

**Comment by po5** [comment]
I experienced issues on my instance too. The issue is that the css from the previous version is cached.  
Everything is fine for existing users after a hard reload, and for new users by default.  
We should use the software version as a query string to break browser's cache when updating.

**Comment by Fastidious** [comment]
@po5 when it happened to me, I tried it on a different browser (that was never used to access my instance), and even tried on incognito mode. Still same results. I don't think it is what you think it is.

**Comment by f0x52** [comment]
@Fastidious there's some [suspicion it might still be caching](https://stackoverflow.com/questions/48693693/macos-safari-caching-response-while-headers-specify-no-caching), could you check the devtools to see if it's a cached response?

**Comment by f0x52** [comment]
update: I can reproduce the issue in Epiphany, so it's not caching related

**Comment by joepie91** [comment]
This should probably be reported to https://webcompat.com/

**Comment by Fastidious** [comment]
@tsmethurst waiting for this to make it to an RC, because I can’t see the `/admin` settings neither, on Safari (they show fine under Chrome). #1193 might fix it, but no way to test it yet.
