### ISSUE TITLE
[bug] Can't Sign in with Tootle

### ISSUE THREAD

**Issue by zethra** [superseriousbusiness/gotosocial#1187]
### Describe the bug with a clear and concise description of what the bug is.

When trying to sign in with the Tootle, I get "Server returned an Error: I'm a teapot"

### What's your GoToSocial Version?

0.5.2

### GoToSocial Arch

amd64

**Comment by tsmethurst** [comment]
> Server returned an Error: I'm a teapot

That means Tootle isn't submitting a user-agent along with its requests. GtS will (eventually) do filtering based on user-agents--among other things--but right now it's just hardcoded to 418 empty user agents.

**Comment by zethra** [comment]
Ah okay. Just checked Tootles repo was archived a year ago, so I'm guessing this isn't getting fixed on their end. womp. Guess I need to find a better desktop Fedi client.

**Comment by tsmethurst** [comment]
Think we'll make that user-agent thing configurable at some point, so people can turn it off if there's a client they want to use that doesn't submit a user-agent

**Comment by GeopJr** [comment]
(Sorry for bumping this issue)

This has been fixed on [Tooth](https://github.com/GeopJr/Tooth) (fork of Tootle)!
