### ISSUE TITLE
[feature] unauthenticated status context get api

### ISSUE THREAD

**Issue by alok0** [superseriousbusiness/gotosocial#1209]
### Is your feature request related to a problem ?

When I click on a status on Sengi to see the thread/replies,  
posts from mastodon get a more complete result.

### Describe the solution you'd like.

I'm not sure how other apps do it, but Sengi appears to query my own server as well as the original author's server.

- `https://****/api/v2/search?q=https://gts.superseriousbusiness.org/users/gotosocial/statuses/01GKBQX0YPFC0RC548TZEEKEAM&resolve=true`
- `https://****/api/v1/statuses/****/context`
- `https://gts.superseriousbusiness.org/api/v1/statuses/01GKBQX0YPFC0RC548TZEEKEAM/context`

It appears that mastodon will allow this unauthenticated query, but GtS does not (401).

### Describe alternatives you've considered.

none.

### Additional context.

- https://docs.joinmastodon.org/methods/statuses/#context
  - > OAuth: Public for public statuses. User token + `read:statuses` for private statuses.

**Comment by tsmethurst** [comment]
Hmm, we're not going to be doing this. Fetching remote resources from another instance's API like that is really quite a hack on Sengi's part, imo :thinking: Besides, this wouldn't work for secure-mode mastodon anyway.
