### ISSUE TITLE
[QUESTION] Do you want users to file client-specific issues?

### ISSUE THREAD

**Issue by xxxserxxx** [superseriousbusiness/gotosocial#1217]
### Is your feature request related to a problem ?

It's related to several functions in an app, Fedilab, consistently generating client-side errors.

### Describe the solution you'd like.

A simple yes/no answer is sufficient.

### Describe alternatives you've considered.

I considered filing tickets with Fedilab, but Fedilab doesn't claim to be compatible with gotosocial, so they aren't going accept tickets about issues with GTS accounts.

### Additional context.

I did try to ask this in the matrix room, but was denied permission by the room settings.

Several of the things you can do in Fedilab generate errors when connected to a gotosocial server. Fedilab doesn't specifically say it's an AP client, at least not on their front page: it says it's compatible with Mastodon, Pleroma, Peertube, Pixelfed, GNU Social, and Frendica -- which seems to be to be a long-winded way of saying it's an AP client. It does mostly work with gotosocial.

I could file issue here for activities that always generate errors in Fedilab for gotosocial accounts (and not for Friendica, Pixelfed, or Mastodon accounts), but is that helpful for gotosocial?

**Comment by tsmethurst** [comment]
Heya, forgot to reply to this at the same (almost a year ago). Not sure how relevant it is anymore, so I'm just gonna close it :P
