### ISSUE TITLE
[chore/performance] sqlite `pragma` tuning

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#1232]
To squeeze more performance out of the modernc go sqlite implementation, we should investigate which knobs we can tweak and buttons we can press to tune it.

Relevant documents for this:

- shared cached mode: https://www.sqlite.org/sharedcache.html or https://www.sqlite.org/wal.html
- pragma commands to mess about with: https://www.sqlite.org/pragma.html
- thread mode: https://www.sqlite.org/threadsafe.html
 
and likely some others to be found here: https://www.sqlite.org/docs.html

**Comment by NyaaaWhatsUpDoc** [comment]
I think we're already using shared cache mode right? Though WAL (write-ahead-logging) is definitely one worth looking into. I tried quickly enabling it at one point but I think it will be a little more complex than just enabling it, as I was getting some errors with queries after doing so :p

**Comment by igalic** [comment]
might be worth looking into what [TheKounge](https://github.com/thelounge/thelounge) for instance is doing, although their use is very simple

i also think [plume](https://git.joinplu.me/Plume/Plume)'s authors did quite a few optimisation.

**Comment by NyaaaWhatsUpDoc** [comment]
Just a note I have started working on this yesterday evening. Will pick it up again this weekend :)

**Comment by tsmethurst** [comment]
closed by #1349
