### ISSUE TITLE
[bug] language property is empty on statuses

### ISSUE THREAD

**Issue by alok0** [superseriousbusiness/gotosocial#1235]
### Describe the bug with a clear and concise description of what the bug is.

the language field on statuses are blank or null.

- from GtS to Mastodon, Mastodon shows language as `null`
- from Mastodon to GtS, GtS shows language as blank `""`
- from Mastodon to Mastodon, language shows as `""`

as far as I can tell, language only seems to work local and not federated.

### What's your GoToSocial Version?

v0.6.0

**Comment by alok0** [comment]
I do not believe this problem is actually solved. The problem is that the language property is no propagated through ActivityPub. I can neither send nor receive statuses with a language property.

**Comment by tsmethurst** [comment]
Ah OK, thanks for clarifying. I'll open a separate issue for this :+1:
