### ISSUE TITLE
[bug] ASCII hearts get removed from markdown posts </3

### ISSUE THREAD

**Issue by autumnull** [superseriousbusiness/gotosocial#1240]
### Describe the bug with a clear and concise description of what the bug is.

Including either `<3` or `</3` in markdown posts causes strange behavior.

### What's your GoToSocial Version?

v0.6.0

### GoToSocial Arch

armv7 Binary

### What happened?

Input text:
```md
hello <3 old friend <3 i loved u </3 :(( you stole my heart
```

Content HTML:
```html
<p>hello old friend i loved u
```

Note that the closing `</p>` tag is missing, not just the latter half of the sentence.

To summarize:
- `<3` is removed
- `</3` is removed along with everything following it, including the closing `</p>` tag.

### What you expected to happen?

Expected HTML:
```html
<p>hello &lt;3 old friend &lt;3 i loved u &lt;/3 :(( you stole my heart</p>
```

Taken from the [CommonMark dingus](https://spec.commonmark.org/dingus/) :)

### How to reproduce it?

Provide input as above.

**Comment by autumnull** [comment]
Upon inspection, the issue is in blackfriday. It converts the above markdown to
```
<p>hello  old friend  i loved u </3 :(( you stole my heart</p>
```
which is then sanitized (pretty reasonably) by bluemonday to remove the unescaped `<` and everything after it.

The secondary issue is that blackfriday has had no commits since 2020, and has a big pile of unresolved issues, so it is unlikely that the issue in blackfriday will be fixed.

So I tested a few other markdown libraries. The second most popular on github, [gomarkdown](https://github.com/gomarkdown/markdown), does not work. same issue. However, the commonmark implementation in go, [golang-commonmark](https://gitlab.com/golang-commonmark/markdown), does work.

My suggestion is to switch to using golang-commonmark. Unfortunately it does come with a handful of dependencies. But this is the best suggestion i have -- they seem to be more intent on sticking to spec, which i think is desirable.

**Comment by autumnull** [comment]
Scratch that suggestion, actually i just found [goldmark](https://github.com/yuin/goldmark) which has no dependencies, is more popular and well-maintained, and is also commonmark spec compliant. It seems ideal.

**Comment by Fastidious** [comment]
@autumnull does it work on [goldmark](https://github.com/yuin/goldmark)?

**Comment by autumnull** [comment]
yes.

**Comment by tsmethurst** [comment]
Oooh good find 👀 I'm open to switching from blackfriday. Perhaps it's worth making a separate issue for doing the switch so we can write up what's required? Or do you want to do it here?

**Comment by autumnull** [comment]
i'm currently working on switching it over, I don't mind if you wana make a new issue if that's tidier for project managment etc. <3
