### ISSUE TITLE
[bug] Failed build on openSUSE Tumbleweed with go 1.19.4

### ISSUE THREAD

**Issue by darix** [superseriousbusiness/gotosocial#1249]
### Describe the bug with a clear and concise description of what the bug is.

```
CGO_ENABLED=0 \             
go build -trimpath -mod=vendor -buildmode=pie -tags 'netgo osusergo static_build kvformat' '-ldflags=-s -w -extldflags '\''-static'\'' -X '\''main.Version=v0.6.0+git0.f9e5ec9'\''' ./cmd/gotosocial  
# github.com/cornelk/hashmap
vendor/github.com/cornelk/hashmap/list_element.go:17:13: invalid recursive type atomic.Pointer
  vendor/github.com/cornelk/hashmap/list_element.go:17:13: atomic.Pointer refers to
  vendor/github.com/cornelk/hashmap/list_element.go:17:22: ListElement refers to
  vendor/github.com/cornelk/hashmap/list_element.go:17:13: atomic.Pointer
```

same error happens with the build script.

### What's your GoToSocial Version?

v0.6.0+git0.f9e5ec9

### GoToSocial Arch

x86_64

### What happened?

failed build

### What you expected to happen?

working build

### How to reproduce it?

trying to build on openSUSE Tumbleweed

### Anything else we need to know?

-

**Comment by trysdyn** [comment]
That hashmap upstream lib hits a bug in Go 1.19.4 that's been slated for fix in 1.19.5. I hit the same issue on Arch and had to downgrade to 1.19.3

Upstream had it reported here https://github.com/cornelk/hashmap/issues/71
