### ISSUE TITLE
[bug] Confusing error messsage after block of instance

### ISSUE THREAD

**Issue by moan0s** [superseriousbusiness/gotosocial#1253]
### Describe the bug with a clear and concise description of what the bug is.

After adding a block to an instance a red box shows up that informs a user that editing a domain block is not implemented yet. This made me initially feel like the block was not saved successfully and I first had to realize that I am now in the editing workflow for the (successfully saved) block.

This will probably become obolete when #1198 ist implemented but I still wanted to report it as currrent UX issue.

### What's your GoToSocial Version?

GoToSocial 0.6.0 git-f9e5ec9

### GoToSocial Arch

arm 64 docker

### What happened?

# Steps to reproduce
- got to yourinstance.social/settings as admin
- type in a domain to block and click "Add block"
- Type in comments and add the block

It now shows something like the following

![image](https://user-images.githubusercontent.com/25753802/206976622-b4a043c7-d514-41a7-963d-0e828bc3176a.png)

And I was a bit confused

### What you expected to happen?

Something that says "Successfully blocked xy.social. maybe followed by a second field with the current information is on. Maybe something like in the picture
![image](https://user-images.githubusercontent.com/25753802/206981407-365e975e-8ee5-4fe4-853d-a4d4ff2a5aca.png)

### How to reproduce it?

- got to yourinstance.social/settings as admin
- type in a domain to block and click "Add block"
- Type in comments and add the block

**Comment by tsmethurst** [comment]
Mm this makes sense, thanks :)

**Comment by filipesmedeiros** [comment]
I still got this today after adding a new domain block, btw!
