### ISSUE TITLE
[feature] Profile metadata fields

### ISSUE THREAD

**Issue by srcr** [superseriousbusiness/gotosocial#1256]
### Is your feature request related to a problem ?

It annoys me that I can't create these metadata field with my pronouns and URLs like the bigger brands in the Fediverse space. 

### Describe the solution you'd like.

Implement the Profile metadata feature like it is available in Mastodon https://docs.joinmastodon.org/user/profile/#fields

### Describe alternatives you've considered.

None

### Additional context.

This was also reported as a bug earlier https://github.com/superseriousbusiness/gotosocial/issues/979

**Comment by NyaaaWhatsUpDoc** [comment]
This is already in the roadmap document: https://github.com/superseriousbusiness/gotosocial/blob/main/ROADMAP.md
