### ISSUE TITLE
[feature ] Ability to disable ValidateIP (in config?)

### ISSUE THREAD

**Issue by doenietzomoeilijk** [superseriousbusiness/gotosocial#1262]
I'm running a website and GtS on the same server, the latter in a container. I'm horsing around with doing AP-y things on the website, but GtS refuses to follow it. This makes sense, because, as far as GtS-inside-the-container knows, the website lives at 10.0.0.something, which [this validator](https://github.com/superseriousbusiness/gotosocial/blob/746f3fa4e65ac2806955a4be8e969dd8a2636ccf/internal/netutil/validate.go#L88) rejects due to it being in private range.

While I understand where the check is coming from, I'd love to be able to somehow get around it. I don't think I can change the network situation too much. The website isn't running in a container, I'm not at a point in my life where I want to horse around with hairpin NAT on the router and the split horizon DNS is the most sane solution for my needs here.

I would, however, love to be able to follow myself. ;)

Are you open to some thinking about how this could be handled, possibly, or is the validator holy and not something that's ever up for configuration?

**Comment by tsmethurst** [comment]
So in other words yes, I think we'd be open to this, but better check with @NyaaaWhatsUpDoc

**Comment by doenietzomoeilijk** [comment]
Personally, I'd opt for (configurably) disabling just the private prefixes for IPv4, _maybe_ the link-local for IPv6, but my knowledge of IPv6 is somewhat lacking, so I'd leave that particular decision to someone who actually knows what's what.

As for IPv4 private: that's used _widely_ in all kinds of hosting setups, I'm fairly confident in saying that being able to disable that particular check is not much of an issue. If people set up their hosting with reserved or testing ranges, well, that's on them.

**Comment by NyaaaWhatsUpDoc** [comment]
I have some ideas for this :)

Was thinking we could remove the private ranges from being hard-coded in, but instead make them defaults. So you can get rid of them by providing an empty `allow-list` config variable.

**Comment by doenietzomoeilijk** [comment]
Even better, that way you can specify which exact private prefix you want to allow (because who uses all three, right?)

**Comment by igalic** [comment]
explicit `allow-list` is the way to go, given the funky stuff some cloud providers do with private IPv4 and link-local IPv6 addresses

**Comment by rsolvang** [comment]
I have run into the same problem while hosting several instances on the same network. We use the IP ranges `172.17.0.0/16` and `fdd0:172:17::/48`. Currently these instances can't reach each other and we would love to have an allow-list in the config file!

**Comment by rsolvang** [comment]
A short update: we worked around this problem by commenting out `netip.MustParsePrefix("fc00::/7")` and `netip.MustParsePrefix("172.16.0.0/12")` from the `validate.go` file and building from source. Works for now, but an `allow-list` in the config file would be better :smirk:
