### ISSUE TITLE
[Custom Frontends] Focus on API and not on templates could speed the development?

### ISSUE THREAD

**Issue by Loweel** [superseriousbusiness/gotosocial#1269]
### Is your feature request related to a problem ?

Hi All, I am experimenting the snapshot version of gts and I've to say, the idea is great.

But, the fact I cannot really chose to have the frontend I like, without lot of work to make it work towards containers and network. . Apparently, GTS loads templates to answer some basic GET requests, which prevents to me to install existing static frontents.

Besides, by concept, the GTS is API based, so even to develop and care of this go templates is kinda takint time to main goal, which is API compatibility.

### Describe the solution you'd like.

So my proposal is to abandon this templates, and "just" create a folder, say "static", where the http server will just serve static content. Anyone who wants, then, could git glone the frontend: most of frontends are "just" static served, meaning they need nothing by a configuration change (e.g: 127.0.0.1:4000) in some json file, to work.

This would free time to focus on API, allowing in the same time a better experience. Then the current webpage template may be used when the folder is empty, if needed. But jjust this: the user pages and the config pages are written already, there are already some admin FEs around (like the Pleroma one), so why to reinvent the wheel? 

I think this could also free resource to focus on the API. 

### Describe alternatives you've considered.

I considered alternatives like, and they can run with the API:

- soapbox
- pleroma fe
- kenoma fe
- pleroma admin fe

but it's hard to set proper proxypass rules to isolate the fe.

It would be perfect to have 
 some variable like GTS_3RDPARTYFE , pointing to the folder where to install the static frontend, and if not set going with the existing templates.

**Comment by tsmethurst** [comment]
This is not really a helpful issue or a feature request per se. It's actually quite insulting and dismissive to suggest that we're mismanaging our time. The static pages and panels are a core part of what we're making. In future, we have plans to bundle some client front end along with GtS, but it certainly won't be Soapbox. I'm going to close this issue.
