### ISSUE TITLE
[bug] Mentions/hashtags in markdown show up in metadata even in code blocks

### ISSUE THREAD

**Issue by autumnull** [superseriousbusiness/gotosocial#1271]
### Describe the bug with a clear and concise description of what the bug is.

In markdown mode, mentions and hashtags that don't render as clickable tags (e.g. in code blocks), are included in the `tags` and `mentions` metadata of the post.

### What's your GoToSocial Version?

v0.6.0

### GoToSocial Arch

armv7 Binary

### What happened?

Make a post like this:
~~~
How to mention a user
```
@user@floss.dude.io hey bud! nice #ObjectOrientedProgramming software you've been writing lately!
```
hope that helps
~~~
and the user tagged in the code block will be included in the `mentions` field of the status, as well as the hashtag being included in the `tags` field.

### What you expected to happen?

Neither the user nor the hashtag should be associated with the post metadata.

### How to reproduce it?

Make post as above.

### Anything else we need to know?

This is because the hashtags and mentions are scanned from the post before it is rendered as markdown. They should probably be scanned afterward, or during the markdown parsing process somehow.

**Comment by tsmethurst** [comment]
@autumnull is this still a thing? just checking through issues

**Comment by autumnull** [comment]
@tsmethurst probably? unless anyone's significantly overhauled the status text processing part in the meantime, i haven't been paying close attention

**Comment by autumnull** [comment]
the issue was that statuses were scanned with a regex for tags and mentions, rather than taking into account their context in markdown which might make them not actually mentions

**Comment by tsmethurst** [comment]
Aha okay thank you! <3

**Comment by autumnull** [comment]
Update: This also applies to emojis `:face_with_spiral_eyes:`
