### ISSUE TITLE
[feature] Show edited post updates

### ISSUE THREAD

**Issue by bekriebel** [superseriousbusiness/gotosocial#1275]
### Is your feature request related to a problem ?

When a post is edited from an account hosted on Mastodon, the updated post does not appear in the GTS timeline. The post seems to remain the original post and no edit is seen.

### Describe the solution you'd like.

Edited posts should appear as edited on GTS.

### Describe alternatives you've considered.

N/A

**Comment by tsmethurst** [comment]
This has been fixed now :)
