### ISSUE TITLE
[feature] Migrate web code to TypeScript

### ISSUE THREAD

**Issue by imWildCat** [superseriousbusiness/gotosocial#1276]
### Is your feature request related to a problem ?

It could be better if we migrate to Typescript.

this can be it much easier to maintain.

### Describe the solution you'd like.

I can help the migration to typescript if needed

### Describe alternatives you've considered.

Keep JavaScript but it is not easy to scale

**Comment by tsmethurst** [comment]
We're fine with the current setup. While it does have benefits for v. large projects, Typescript comes with its own set of headaches and maintenance issues, and we made a conscious choice not to use it for this project. Perhaps in the distant future but it's not a priority now at all.

**Comment by imWildCat** [comment]
Ok!

I thought about some interesting ideas about generating API interfaces in TypeScript from Golang directly...
