### ISSUE TITLE
[bug] Panic probably related to S3 presigned URL caching

### ISSUE THREAD

**Issue by LittleFox94** [superseriousbusiness/gotosocial#1279]
### Describe the bug with a clear and concise description of what the bug is.

Shortly after updating my GtS from v0.6.0-rc3 to v0.6.0 and then continuing to use it, GoToSocial server died from a panic. The panic output is too long to add here (GitHub refuses to save the issue then), so have a pastebin instead: https://pastebin.com/71J68ZYH

### What's your GoToSocial Version?

v0.6.0

### GoToSocial Arch

amd64 docker

**Comment by NyaaaWhatsUpDoc** [comment]
I know what the issue is here. It's an incorrect calling of the URL cache. Will get this fixed soon.
