### ISSUE TITLE
[bug] 500 ISE when trying to search for or view instance actor internally

### ISSUE THREAD

**Issue by trysdyn** [superseriousbusiness/gotosocial#1289]
### Describe the bug with a clear and concise description of what the bug is.

This is likely cosmetic. Yes, no one should be trying to do this :)

If you try to view the instance actor, GtS throws a 500 Internal Server Error trying to resolve the user attached to the account, which does not exist. This includes trying to view their profile in the web frontend, search for them via the internal/authorized API, but not using an authorized fetch from remote as far as I can tell.

### What's your GoToSocial Version?

v0.6.0 git-b966d3b

### GoToSocial Arch

amd64 source build

### Browser version

Any

### What happened?

I got bored/curious and tried to view the profile for my internal instance actor at `https://<domain>/@<domain>` and got a 500 Internal Server Error instead of the expected 404 Page Not Found boilerplate message or similar. The error in logs:

```
error="Error #01: error converting account: AccountToAPIAccountPublic: error getting user from database for account id 01NXFSPQTRNKGYRDZQH6CY39MA: no entries\n" msg="Internal Server Error: wrote 769B"
```

I then decided to see if the same thing happened while using the API to search for the instance actor and yes, it does. Far as I can tell authorized fetches from a remote instance behave as expected.

### What you expected to happen?

Honestly, I'm not 100% sure...

I think we can copy Mastodon's homework here for `Accept: text/html` and dump the user to the instance about page with an extra slice of copy that explains they tried to look up the instance actor and don't do that.

I'm not sure what's right when using `Accept: application/activity+json` but it's not a 500 ISE.

### How to reproduce it?

Try to do anything that causes GtS to attempt to link the internal instance actor to a user account.

That includes:

- Performing an authenticated API search for the instance actor `@<domain>@domain`
- Attempt to view the instance actor on the web frontend at `https://<domain>/@<domain>`

Then witness the error in the logs.

### Anything else we need to know?

I don't know why I tried to do this and it's *probably* entirely a cosmetic bug. ¯\_(ツ)_/¯

**Comment by tsmethurst** [comment]
Thanks! Silly bug, will try to take a look at it soon (tm)
