### ISSUE TITLE
[feature] Environment variable to toggle TLS for s3 backend

### ISSUE THREAD

**Issue by lsnow99** [superseriousbusiness/gotosocial#1293]
### Is your feature request related to a problem ?

I run Minio within my LAN only, and do not have a TLS certificate configured for it. If I try to use it as the S3 backend, I get an error that a non-HTTPS response was provided. 

### Describe the solution you'd like.

I think it should be possible to toggle TLS for the S3 backend via an environment variable.

### Describe alternatives you've considered.

Using a custom certificate is my best option, but I would prefer to be able to use Minio over HTTP.

**Comment by lsnow99** [comment]
Update: It turns out there already is a variable for this, it just wasn't in the documentation. #1294 adds a note about it.

**Comment by chenzhiwei** [comment]
Seems gotosocial will use the S3 endpoint to expose the media address, the browser will show insure connection.

**Comment by igalic** [comment]
that seems like bad form either way:
the end point could be private, like it is here.
or it could be poorly configured, like (not) suggested here https://github.com/superseriousbusiness/gotosocial/pull/1300

**Comment by lsnow99** [comment]
Yeah my s3 server is not publicly accessible, so I am using this option in conjunction with storage-s3-proxy set to true

**Comment by chenzhiwei** [comment]
I have a VPS and initially use local storage, later I setup a Minio instance, but seems there is no obvious benefits storing media files in to a Minio instance in a single VPS.
