### ISSUE TITLE
[bug] Losing transparency when converting png emoji to a static version

### ISSUE THREAD

**Issue by iochen** [superseriousbusiness/gotosocial#1295]
## Description
When uploading a custom emoji with transparency in png format, the static version of the emoji will lose transparency info (and actually will turn into black).

## Example
Original file at `https://example.ltd/fileserver/XXX/emoji/original/XXX.png` looks like:
![image](https://user-images.githubusercontent.com/28243989/210324300-95e8541f-e9e2-46b5-91f7-f09d3e9ecd6c.png)

Processed static file at `https://example.ltd/fileserver/XXX/emoji/static/XXX.png` looks like:
![image](https://user-images.githubusercontent.com/28243989/210324360-1f1f8729-bedd-4610-9efc-12365a00eecb.png)

## Related code
I have done an experiment that confirms the code in [internal/media/png-stripper.go](https://github.com/superseriousbusiness/gotosocial/blob/main/internal/media/png-stripper.go) will cause this issue.     
However, limited by my ability, I cannot figure out how to fix the bug in that file currently.     
     
And I am curious that, since png file can never be an animated image, why do we need to decode the png file and encode that back like the code below?    
But I haven't deeply dived to the whole project yet, so I am not sure if there is something thoughtless in my idea.
https://github.com/superseriousbusiness/gotosocial/blob/941893a774c83802afdc4cc76e1d30c59b6c5585/internal/media/image.go#L99-L125

## Related issue(s) & PR(s)
https://github.com/superseriousbusiness/gotosocial/issues/425
https://github.com/superseriousbusiness/gotosocial/pull/487

## Version
v0.6.0

**Comment by tsmethurst** [comment]
> png file can never be an animated image

It can be an animated image, there are animated pngs :) But yes indeed, losing transparency is a known issue, will have a look soon(tm) how this can be fixed.

**Comment by iochen** [comment]
> > png file can never be an animated image
> 
> It can be an animated image, there are animated pngs :) But yes indeed, losing transparency is a known issue, will have a look soon(tm) how this can be fixed.

I thought PNG and APNG were two totally separated formats both in MIME type and filename extension.     
Thank you so much for pointing out my mistake!
