### ISSUE TITLE
[feature] Option to disable strict security mode

### ISSUE THREAD

**Issue by anantshri** [superseriousbusiness/gotosocial#1299]
### Is your feature request related to a problem ?

Right now gotosocial cant communicate with likes of pixelfed and bookwyrm instances coz of http signature requirements.

https://github.com/bookwyrm-social/bookwyrm/issues/1179
https://github.com/pixelfed/pixelfed/issues/2935

### Describe the solution you'd like.

I understand its is the best interest that the offending parties should be correcting the error however I was thinking should we also be thinking about a mode where these restrictions are relaxed. may be with admin toggle to allows for interactions with these instances. 

### Describe alternatives you've considered.

We already have open issues in pixelfed and bookwyrm 

https://github.com/bookwyrm-social/bookwyrm/issues/1179
https://github.com/pixelfed/pixelfed/issues/2935

We dont have any more alterantive options.

### Additional context.

Right now from a pixelfed or bookwrym instance i can connect with mastodon instances but not gotosocial instances. the requests are recieved (initial web finger) but next request onwards both softwares cant play well with us.

**Comment by tsmethurst** [comment]
This is a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/872 so I'm gonna close it
