### ISSUE TITLE
[bug] Nodeinfo does not return any users

### ISSUE THREAD

**Issue by jeherve** [superseriousbusiness/gotosocial#1307]
### Describe the bug with a clear and concise description of what the bug is.

When accessing a GoToSocial instance's `Nodeinfo`, I would expect to find a `usage` object filled with information from public users on the instance.

### What's your GoToSocial Version?

0.6.0 git-f9e5ec9

### GoToSocial Arch

arm64 Binary

### What happened?

On GoToSocial 0.6.0 git-f9e5ec9, I only see an empty `users` object:

```json
{
	"version": "2.0",
	"software": {
		"name": "gotosocial",
		"version": "0.6.0 git-f9e5ec9"
	},
	"protocols": [
		"activitypub"
	],
	"services": {
		"inbound": [],
		"outbound": []
	},
	"openRegistrations": false,
	"usage": {
		"users": {}
	},
	"metadata": {}
}
```

### What you expected to happen?

I would expect to see something like this (example taken from a Mastodon instance):

```json
{
	"version": "2.0",
	"software": {
		"name": "mastodon",
		"version": "4.0.2"
	},
	"protocols": [
		"activitypub"
	],
	"services": {
		"outbound": [],
		"inbound": []
	},
	"usage": {
		"users": {
			"total": 20,
			"activeMonth": 21,
			"activeHalfyear": 21
		},
		"localPosts": 415
	},
	"openRegistrations": true,
	"metadata": {}
}
```

### How to reproduce it?

This is currently visible on the [SuperSeriousBusiness GoToSocial](https://gts.superseriousbusiness.org/) instance:

https://gts.superseriousbusiness.org/nodeinfo/2.0

### Anything else we need to know?

Some fediverse tools currently rely on that information to highlight activity on ActivityPub instances. Here is an example:
https://fedidb.org/network/instance?domain=gts.superseriousbusiness.org

It would be nice if GoToSocial supported that. Of course, I may have missed a config option that may allow you to enable this. If so, sorry about that!

**Comment by tsmethurst** [comment]
Thanks! I think this would be a good first issue for someone to fix, so I'm gonna add that label and post about it :)

**Comment by tsmethurst** [comment]
It's this part of the code that needs to be updated:

https://github.com/superseriousbusiness/gotosocial/blob/36aa6854bd7e56603236e4d371db48e4b515e768/internal/processing/federation/getnodeinfo.go#L54-L75

These two db functions can be used to get the relevant stats:

https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/instance.go#L29-L33
