### ISSUE TITLE
[chore] Consider moving away from now-unmaintained Gorilla toolkit

### ISSUE THREAD

**Issue by daenney** [superseriousbusiness/gotosocial#1316]
The current maintainer(s) of the Gorilla libraries have decided to [stop maintenance and will archive the project](https://github.com/gorilla#gorilla-toolkit).

Though this doesn't present an immediate problem as everything will keep working as it is and the code remains retrievable it does mean GTS is now dependent on some libraries that won't see updates or (security) fixes in the future.

For the direct dependencies:
* `gorilla/websocket`:
  * [gobwas/ws](https://github.com/gobwas/ws)
  * [nhooyr/websocket](https://github.com/nhooyr/websocket) (can be compiled to WASM which could be neat)
* `gorilla/feed`: unknown, all other libraries seem to be parsers, not generators
  * the types from [mmcdole/gofeed](https://github.com/mmcdole/gofeed) could conceivable be used to also build a feed

For the indirect dependencies, the dependency tree:
* `gorilla/context`:
   ```
   $ go mod why github.com/gorilla/context
   # github.com/gorilla/context
   github.com/superseriousbusiness/gotosocial/internal/api/client/auth
   github.com/gin-contrib/sessions
   github.com/gorilla/context
* `gorilla/css`
   ```
   $ go mod why github.com/gorilla/css
   # github.com/gorilla/css
   (main module does not need package github.com/gorilla/css)
   ```
* `gorilla/securecookie`
   ```
   $ go mod why github.com/gorilla/securecookie
   # github.com/gorilla/securecookie
   github.com/superseriousbusiness/gotosocial/internal/api/client/auth
   github.com/gin-contrib/sessions
   github.com/gorilla/sessions
   github.com/gorilla/securecookie
   ```
* `gorilla/sessions`
   ```
   $ go mod why github.com/gorilla/sessions
   # github.com/gorilla/sessions
   github.com/superseriousbusiness/gotosocial/internal/api/auth
   github.com/gin-contrib/sessions
   github.com/gorilla/sessions
   ```

The 3 modules that remain reachable in GTS come from [gin-contrib/sessions](https://github.com/gin-contrib/sessions). An issue exists as gin-contrib/sessions#218 reflecting the potential need to remove dependencies on those packages. It appears to be caused by `sessions/cookie.Store` using the Gorilla libraries and doesn't affect other session stores.

**Comment by NyaaaWhatsUpDoc** [comment]
As you say, nothing is going to directly break in the short term, so addressing these slowly could be a good idea. Especially the indrect dependencies, as it gives time for our direct dependencies to hopefully address the situation.

For the websocket library I do like the look of `gobwas/ws`. Looks to be very small, performant and has the most stars of the two. The other library has had more recent commits, but neither have had a release in ~1.5yrs which I'm guessing is due to them not having a changing API or relying on a changing standard.

**Comment by daenney** [comment]
For `gorilla/css`, it comes in through `aymerick/douceur` which is used by `microcosm-cc/bluemonday`. This seems generally harmless.

```
$ go mod why github.com/microcosm-cc/bluemonday
# github.com/microcosm-cc/bluemonday
github.com/superseriousbusiness/gotosocial/internal/text
github.com/microcosm-cc/bluemonday
```

**Comment by daenney** [comment]
Perhaps interesting, the import stats from pkg.go.dev.

* gobwas/ws:
  * imports: 22 (20 of those are stdlib, the other 2 are other packages by the same author)
  * imported by: 360 
* nhooyr.io/websocket
  * imports 28 (23 are stdlib, 2 are from internal, one is for (de)flate support)
  * imported by: 491
 
nhooyr.io/websocket is affected by a 2020 CVE due to allowing Gin < 1.7.0  
> When gin is exposed directly to the internet, a client's IP can be spoofed by setting the X-Forwarded-For header

**Comment by tsmethurst** [comment]
I renamed the issue and added the chore label, hope that's OK :)

**Comment by daenney** [comment]
Looks like we might not have to: https://gorilla.github.io/blog/2023-07-17-project-status-update/

**Comment by tsmethurst** [comment]
Gonna close this since gorilla is back baby!
