### ISSUE TITLE
[bug] Replies to boosts don't always show up in timeline

### ISSUE THREAD

**Issue by eritbh** [superseriousbusiness/gotosocial#1329]
### Describe the bug with a clear and concise description of what the bug is.

If a post from someone I don't follow is boosted onto my timeline, viewing that post won't show me all the replies. If the post is part of a thread, I'll see the rest of the author's posts in the thread, but I won't see any of the replies from other users.

### What's your GoToSocial Version?

v0.6.0

### GoToSocial Arch

amd64 Docker

### What happened?

Someone I follow boosted a post from someone I don't follow. The post had replies, visible on its home instance, from different users on different instances. I viewed the post in my client and saw no replies.

### What you expected to happen?

I expected to see all the replies to the post in my client.

### How to reproduce it?

Have someone you follow boost a post from someone you don't follow which has replies. View the post from your timeline in some client (tested in both Pinafore and Metatext).

**Comment by tsmethurst** [comment]
This is a pretty normal part of how federation works and there's not really a simple fix for it. We do have some logic for fetching replies and parent posts, but it needs a bit more tuning. I think an option in the client API to re-fetch all replies for a given post might not be a bad idea..

**Comment by eritbh** [comment]
Thanks for the info! I've been tinkering with GoToSocial just recently after being active on a larger Mastodon instance for a while, so yeah, I'm not that familiar yet with how the federation experience is expected to differ between those two environments. Does Mastodon handle these situations differently at all, or is it just a function of how much of your social graph is on the same instance as you, or something like that?

**Comment by tsmethurst** [comment]
> Does Mastodon handle these situations differently at all, or is it just a function of how much of your social graph is on the same instance as you, or something like that?

It's a bit of both: I *think* mastodon periodically refreshes replies and stuff on a cooldown when someone views a status, but I can't remember fully. Aside from that, you also will just get a fuller picture being on an instance with more connections.

**Comment by tsmethurst** [comment]
If it's alright with you, I'm gonna close this since it's not really a bug per se. Feel free to reopen it if you have more to add :)
