### ISSUE TITLE
[bug] Unable to use with Elk client

### ISSUE THREAD

**Issue by kvibber** [superseriousbusiness/gotosocial#1331]
### Describe the bug with a clear and concise description of what the bug is.

I'm able to enter my instance URL on [Elk](https://elk.zone/) (a web-based Mastodon front-end client), and get my GTS permissions page, and tell it to allow the application...but when it redirects back to the Elk application, it doesn't retrieve anything from my GTS instance. No posts, no profiles, no posting ability - nothing.

This bug report on Elk may be relevant, or it may not - it's old
https://github.com/elk-zone/elk/issues/133

### What's your GoToSocial Version?

0.6.0 git-f9e5ec9

### GoToSocial Arch

arm64 docker

### Browser version

Arc Version 0.81.2 (36600)

**Comment by joch** [comment]
I’m seeing similar things for other clients. The flow looks like this for the Mammoth iOS app:

```
timestamp=“13/01/2023 08:58:23.091” func=api.OAuthErrorHandler level=DEBUG path=/oauth/token error=invalid_request help=“Bad Request: EOF” msg=“handling OAuth error”
timestamp=“13/01/2023 08:58:23.005” func=router.loggingMiddleware.func1 level=INFO latency=8.18259ms clientIP=xx.xx.xx.xx userAgent=“-” method=POST statusCode=302 path=/oauth/authorize msg=“Found: wrote 23B”
timestamp=“13/01/2023 08:58:21.871” func=router.loggingMiddleware.func1 level=INFO latency=6.234813ms clientIP=xx.xx.xx.xx userAgent=“-” method=GET statusCode=200 path=/oauth/authorize msg=“OK: wrote 848B”
timestamp=“13/01/2023 08:58:21.795” func=router.loggingMiddleware.func1 level=INFO latency=90.034984ms clientIP=xx.xx.xx.xx userAgent=“-” method=POST statusCode=302 path=/auth/sign_in msg=“Found: wrote 23B”
timestamp=“13/01/2023 08:58:18.443” func=router.loggingMiddleware.func1 level=INFO latency=6.519882ms clientIP=xx.xx.xx.xx userAgent=“-” method=GET statusCode=200 path=/auth/sign_in msg=“OK: wrote 803B”
timestamp=“13/01/2023 08:58:18.363” func=router.loggingMiddleware.func1 level=INFO latency=2.866633ms clientIP=xx.xx.xx.xx userAgent=“-” method=GET statusCode=303 path=/oauth/authorize msg=“See Other: wrote 64B”
```

**Comment by tsmethurst** [comment]
I tried it on the version of GtS on current main and it works there, with a few exceptions. So this looks like it might be something we fixed between the soup and the potatoes.

**Comment by tsmethurst** [comment]
Gonna close this now since it seems to work OK :)
