### ISSUE TITLE
[bug] Unable to follow accounts at bird.makeup

### ISSUE THREAD

**Issue by darrinsmart** [superseriousbusiness/gotosocial#1340]
### Describe the bug with a clear and concise description of what the bug is.

bird.makeup is one of those twitter gateways, using a fork of birdsitelive.

When following accounts at bird.makeup (eg: @lapublichealth@bird.makeup), the follow request never completes.

### What's your GoToSocial Version?

0.6.0 git-f9e5ec9

### GoToSocial Arch

x86_64 binary

### What happened?

When trying to follow any account there, the follow request appears to go out but it never completes. My client (Metatext) just shows a "Cancel follow request" button indefinitely.

If I attempt the same on a Mastodon server (mas.to), it works ok.

### What you expected to happen?

I'd expect the follow to complete and have the posts fill my timeline.

### How to reproduce it?

Try following any account on bird.makeup

### Anything else we need to know?

GoToSocial does log:
```
func=transport.(*transport).do level=INFO pubKeyID=.../main-key method=GET url=https://bird.makeup/.well-known/webfinger?resource=acct:lapublichealth@bird.makeup msg="performing request"

func=transport.(*transport).do level=INFO pubKeyID=.../main-key method=POST url=https://bird.makeup/inbox msg="performing request"
```
It's not clear if the issue is with GoToSocial or with bird.makeup. I'm not very familiar with ActivityPub - but happy to do further tests if there is anything I can do.

**Comment by tsmethurst** [comment]
It looks like GtS is sending the Follow but never getting an Accept back, and so never marking the follow request as complete. In my experience cases like this are often due to http signature issues. Does it work if you follow that bird makeup account from a mastodon instance with secure mode enabled?

**Comment by darrinsmart** [comment]
I never did find a Mastodon instance with secure mode enabled. But I thought I'd try GTS again today after installing 0.8.0rc1.

When attempting to follow, bird.makeup does try to connect back and fetch `/users/darrin`. However it gets the 418 teapot response (#1296).

To test further I changed my nginx proxy to add a fake user-agent header. That changed the 418 response to 401, with the log showing:

```
timestamp="08/04/2023 12:31:36.500" func=federation.(*federator).AuthenticateFederatedRequest level=DEBUG requestID=ph3nmrm704001w4kga2g msg="http request wasn't signed or http signature was invalid"
```

@tsmethurst I think you were right on the money. A quick read of the [bird.makeup source](https://git.sr.ht/~cloutier/bird.makeup) suggests that is not signing the request to that endpoint. 

Anyway, IMO this isn't a GTS issue and can be closed.

**Comment by tsmethurst** [comment]
Ah thanks for doing more investigation! I'll close this for now then, we can reopen it again if it seems there's more we can do from GtS's side :)
