### ISSUE TITLE
[feature] RSS Autodiscovery

### ISSUE THREAD

**Issue by kvibber** [superseriousbusiness/gotosocial#1358]
### Is your feature request related to a problem ?

RSS readers (and some browsers, like Vivaldi) can detect when a feed is available based on a link rel=alternate in the html page's header. GTS currently does not include this.

### Describe the solution you'd like.

When a user has RSS enabled, add something like this to their profile page:

```
<link rel="alternate" type="application/rss+xml" href="/path/to/rss/feed" title="Username on GoToSocial" />
```

### Describe alternatives you've considered.

none

### Additional context.

I've taken a look at the template code and I'm willing to implement this myself and submit a PR if it sounds like something you'd want included.

**Comment by tsmethurst** [comment]
This sounds very reasonable! Feel free to work on a PR for this if you like :)

**Comment by kvibber** [comment]
Great! I'll give it a shot!

**Comment by tsmethurst** [comment]
closed by https://github.com/superseriousbusiness/gotosocial/pull/1373
