### ISSUE TITLE
[feature] cors issue with soapbox

### ISSUE THREAD

**Issue by orvice** [superseriousbusiness/gotosocial#1364]
### Is your feature request related to a problem ?

can't post toots with soapbox, error log from console:

```
Access to XMLHttpRequest at 'https://gts.cloud/api/v1/statuses' from origin 'https://fe.soapbox.pub' has been blocked by CORS policy: Request header field idempotency-key is not allowed by Access-Control-Allow-Headers in preflight response.
```
soapbox:
https://gitlab.com/soapbox-pub/soapbox

### Describe the solution you'd like.

add `idempotency-key` header in cors middleware:

https://github.com/superseriousbusiness/gotosocial/blob/main/internal/middleware/cors.go#L49

### Describe alternatives you've considered.

NONE

**Comment by tsmethurst** [comment]
We don't care about soapbox compatibility or support soapbox, so I'm gonna close this.
