### ISSUE TITLE
[feature?] maximum password length 64 chars is too short

### ISSUE THREAD

**Issue by xnuk** [superseriousbusiness/gotosocial#1365]
### Is your feature request related to a problem ?

Related: https://github.com/superseriousbusiness/gotosocial/blob/b375d3b5d68e462a53cd44a0fcee43c1713acedb/internal/validate/formvalidation.go#L35

GoToSocial requires password on first account creation step. So I used our good friend, `bat /dev/urandom | base64 | head -n 1`, for temporary password creation, which makes 77 random chars.

```sh
./gotosocial --config-path ./config.yaml admin account create \
  --email xnuk@example.com --username x_nuk \
  --password abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxy
```

And the result was:
```
2023/01/22 15:46:41 error executing command: password should be no more than 64 chars
```

Problem is, this limit is too short for me. In my password manager, I have lots of passwords over 100 chars, some are over 200 chars, some have non-ASCII chars, some have emojis. Of course this could be extreme case, but for me 64 chars limit is too short.

So why is it 64 chars? Is there a historical reasons or something-doesnt-work problem?

### Describe the solution you'd like.

```diff
-	maximumPasswordLength         = 64
+	maximumPasswordLength         = 256
```

### Describe alternatives you've considered.

`NONE`

**Comment by tsmethurst** [comment]
> So why is it 64 chars? Is there a historical reasons or something-doesnt-work problem?

Nope, just pulled that number out of the air. Feel free to make a PR to change it to 256 if you want :) Or wait and one of us will get around to it eventually.
