### ISSUE TITLE
[bug] 'Halcyon' Timeline doesn't auto update

### ISSUE THREAD

**Issue by memo-567** [superseriousbusiness/gotosocial#1367]
### Describe the bug with a clear and concise description of what the bug is.

First of all, very good job 👍 

Pinafore is nice, but I like Halcyon much better.
Something I noticed is the lack of Halcyon's automatic updating of the timeline.

However, it works fine with all Mastodon instances.

### What's your GoToSocial Version?

GoToSocial 0.6.0 git-f9e5ec9

### GoToSocial Arch

Binary on Debian 11

### Browser version

All

### What happened?

No Timeline Update with Halcyon; Pinafore works fine.

### What you expected to happen?

Timeline should update automatically.

**Comment by tsmethurst** [comment]
I have no idea what Halcyon is! But my first question would be: did you open this issue on Halcyon too? It could be that they use a different streaming API (http streaming as opposed to websockets streaming), which we don't yet support.

**Comment by memo-567** [comment]
Unfortunately, the development of Halcyon is discontinued.

https://notabug.org/halcyon-suite/halcyon

But my thought is that if it works with Mastodon then GoToSocial must be something different in the interface `¯\_(ツ)_/¯`

**Comment by memo-567** [comment]
Updating the timeline doesn't seem to work in Elk either. As far as I know, this is the only web client that is being maintained and further developed.

Mastodon works fine.

https://github.com/elk-zone/elk

**Comment by tsmethurst** [comment]
Hmm, streaming via Elk does work with the latest release, at least. It could be a misconfiguration of your server / reverse proxy causing the issue. Could you try again with 0.7.0 and see if the issue is resolved? If not, best check your server config

**Comment by memo-567** [comment]
Upgraded to 0.7.0, works fine with Pinafore in home timeline, not with federated timeline.
Neither home nor federated timeline in Elk (using elk.zone, developers instance).

So if something is misconfigured with my GTS instance, where to investigate?

**Comment by memo-567** [comment]
Today, and I really don't know why, everything works fine with Pinafore and Elk again. I remember a similar behavior with the following of new user.
That post of this new followings appear several minutes delayed.
How ever — forget my last posts please 😀

**Comment by memo-567** [comment]
Is it possible that the Pinafore home timeline updates always, but the federated timeline only if the browser tab is active?

**Comment by tsmethurst** [comment]
Iirc we only support streaming updates for the Home timeline right now, so it makes sense that federated timeline doesn't update :)

**Comment by tsmethurst** [comment]
I'm going to close this since it wasn't really clear what was causing the issue, and I haven't heard of anyone else having the same issue. Feel free to reopen if you're still having problems with it :)
