### ISSUE TITLE
[bug] Follow button on Elk not working

### ISSUE THREAD

**Issue by ata-star** [superseriousbusiness/gotosocial#1368]
### Describe the bug with a clear and concise description of what the bug is.

Now that Pinafore is [unmaintaind](https://nolanlawson.com/2023/01/09/retiring-pinafore/), i tried Elk
Everything GoToSocial supports works except the Follow button

I get:
 `400 Bad Request` 
and a 
`MastoDeserializeError: Unknown content type text/html returned from the server.`
on the client

And the server says:
```
timestamp="22/01/2023 12:09:02.545" func=middleware.Logger.func1.1 level=INFO latency=1.139244ms clientIP=xxx.xxx.xxx.xxx userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0" method=POST statusCode=400 path=/api/v1/accounts/01M35MW770PNHY8Y2DP26F8GB9/follow msg="Bad Request: wrote 783B"
```

### What's your GoToSocial Version?

0.6.1-SNAPSHOT git-b375d3b

### GoToSocial Arch

arm64

### Browser version

Firefox/109.0

### What happened?

The Follow button switches to Following and then switches back to the previous state

### What you expected to happen?

The Follow button to work after i press it

### How to reproduce it?

Any Docker install (not sure if related) and try to use [Elk](https://github.com/elk-zone/elk) with it

**Comment by tsmethurst** [comment]
`bad request` suggests that Elk is doing something funky, or at least that GoToSocial doesn't recognize what it's trying to do. Did you open an issue for this on Elk, linking here? Might not be a bad idea.

**Comment by ata-star** [comment]
i have not yet created an issue on their github, but linked this on their discord

**Comment by kkoyung** [comment]
I made a little investigation, and found that the follow request sent from Elk to GoToSocial contained an HTTP header `content-type: application/json` while the expected json data was missing in the request body. With the `content-type: application/json`, GoToSocial tried to use parameters as json in the body of request, which did not exist. Then, `internal/api/client/accounts/follow.go` generated a bad request error while calling `c.ShoudBind(form)` to parse the follow request.

![screenshot_2023-01-24_16%3A54%3A58](https://user-images.githubusercontent.com/11942650/214255852-a0db04b2-94b4-49a0-a875-b1e446f19c07.jpg)

GoToSocial version: 0.6.0 git-f9e5ec9S
Elk version: v0.6.1-40-gf1a3c88

**Comment by ata-star** [comment]
Seems to work now with https://main.elk.zone/home will close

Thank you every1 <3
