### ISSUE TITLE
[bug] GtS never recovers from worker exhaustion

### ISSUE THREAD

**Issue by trysdyn** [superseriousbusiness/gotosocial#1376]
### Describe the bug with a clear and concise description of what the bug is.

Title is mood. But anyway.

About four times now since the throttling commit I've run into a situation where (always while I'm asleep, figures) GtS stops processing traffic. All inbound s2s gets Service Unavailable and me authoring a post, while it won't return an error, will not be reflected on the instance. In the logs this starts as a series of "full worker queue" WARNs before a solid wall of ERRORs with blank error fields.

This state seems to be terminal until a restart, at which point any posts/favs/etc I made while this was going on will be lost.

Also as a detail: the restart times out and reports a failure to cleanly shut down.

### What's your GoToSocial Version?

GoToSocial v0.6.0 git-1bda6a2

### GoToSocial Arch

amd64 source build

### Browser version

n/a

### What happened?

I'll find my timeline has stopped moving for longer than is reasonable. If it's a *really* long time I'll know this glitch has occurred but if it's just been a little while I'll try to make a post and find it's not reflected on the web interface or any of my clients.

Log delving, the precursor to this is a series of WARNs that the worker pool is full. A few moments after that, GtS will begin serving 503 Service Unavailable to every s2s communication. It looks like this.

```
Jan 22 17:45:47 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 17:45:47.310" func=concurrency.(*WorkerPool).Queue level=WARN type="worker.Worker[messages.FromFederator]" queue=400 msg="full worker queue"
Jan 22 17:45:50 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 17:45:50.133" func=transport.(*transport).do level=INFO pubKeyID="https://electric.marf.space/users/trysdyn/main-key" method="GET" url="https://gamemaking.social/.well-known/webfinger?resource=acct:[SNIP]@gamemaking.social" msg="performing request"
Jan 22 17:45:50 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 17:45:50.776" func=concurrency.(*WorkerPool).Queue level=WARN type="worker.Worker[messages.FromFederator]" queue=400 msg="full worker queue"
Jan 22 17:46:18 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 17:46:18.802" func=concurrency.(*WorkerPool).Queue level=WARN type="worker.Worker[messages.FromFederator]" queue=400 msg="full worker queue"
Jan 22 17:46:45 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 17:46:45.082" func=middleware.Logger.func1.1 level=INFO latency="4.930334ms" clientIP="[SNIP]" userAgent="http.rb/5.1.1 (Mastodon/4.0.2+glitch+th; +https://social.treehouse.systems/)" method="POST" statusCode=200 path="/users/trysdyn/inbox" msg="OK: wrote 23B"
Jan 22 17:46:53 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 17:46:53.594" func=concurrency.(*WorkerPool).Queue level=WARN type="worker.Worker[messages.FromFederator]" queue=400 msg="full worker queue"
Jan 22 17:47:01 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 17:47:01.576" func=concurrency.(*WorkerPool).Queue level=WARN type="worker.Worker[messages.FromFederator]" queue=400 msg="full worker queue"
```

This continues for about 3 minutes (I've removed that boring window for simplicity), but then this begins:

```
Jan 22 17:50:22 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 17:50:22.730" func=middleware.Logger.func1.1 level=ERROR latency="30.00042516s" clientIP="[SNIP]" userAgent="http.rb/5.1.0 (Mastodon/4.0.2+beachcity1.10.0; +https://beach.city/)" method="POST" statusCode=503 path="/users/trysdyn/inbox" error="" msg="Service Unavailable: wrote 69B"
Jan 22 17:50:27 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 17:50:27.280" func=middleware.Logger.func1.1 level=ERROR latency="30.000205289s" clientIP="[SNIP]" userAgent="http.rb/5.1.0 (Mastodon/4.0.2; +https://conversafiada.net/)" method="POST" statusCode=503 path="/users/trysdyn/inbox" error="" msg="Service Unavailable: wrote 69B"
```

This state persists until a GtS restart however user/browser endpoints still work:

```
Jan 22 17:50:48 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 17:50:48.975" func=middleware.Logger.func1.1 level=INFO latency="3.508962ms" clientIP="[SNIP]" userAgent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/6.3.1 Chrome/94.0.4606.126 Safari/537.36 RSS Guard/4.2.5 RSS Guard/4.2.5" method="GET" statusCode=200 path="/@trysdyn/feed.rss" msg="OK: wrote 25.2kiB"
```

Upon restart, GtS fails to shut down and reports an unclean exit:

```
Jan 22 22:33:04 electric.marf.space systemd[1]: Stopping GoToSocial Server...
Jan 22 22:33:08 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 22:33:08.500" func=middleware.Logger.func1.1 level=ERROR latency="30.000197139s" clientIP="[SNIP]" userAgent="http.rb/5.1.0 (Mastodon/4.0.2; +https://tech.lgbt/)" method="POST" statusCode=503 path="/users/trysdyn/inbox" error="" msg="Service Unavailable: wrote 69B"
Jan 22 22:33:13 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 22:33:13.821" func=middleware.Logger.func1.1 level=ERROR latency="30.001185185s" clientIP="[SNIP]" userAgent="http.rb/5.0.4 (Mastodon/3.5.1+chitter; +https://chitter.xyz/)" method="POST" statusCode=503 path="/users/trysdyn/inbox" error="" msg="Service Unavailable: wrote 69B"
Jan 22 22:33:23 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 22:33:23.579" func=middleware.Logger.func1.1 level=ERROR latency="30.000344043s" clientIP="[SNIP]" userAgent="http.rb/5.1.0 (Mastodon/4.0.2; +https://toot.blue/)" method="POST" statusCode=503 path="/users/trysdyn/inbox" error="" msg="Service Unavailable: wrote 69B"
Jan 22 22:33:28 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 22:33:28.847" func=middleware.Logger.func1.1 level=ERROR latency="30.0004654s" clientIP="[SNIP]" userAgent="http.rb/5.1.1 (Mastodon/4.1.0rc1+glitch; +https://infosec.exchange/)" method="POST" statusCode=503 path="/users/trysdyn/inbox" error="" msg="Service Unavailable: wrote 69B"
Jan 22 22:33:34 electric.marf.space gotosocial[1496955]: 2023/01/22 22:33:34 error executing command: error closing gotosocial service: error shutting down http router: context deadline exceeded
Jan 22 22:33:34 electric.marf.space systemd[1]: gotosocial.service: Main process exited, code=exited, status=1/FAILURE
Jan 22 22:33:34 electric.marf.space systemd[1]: gotosocial.service: Failed with result 'exit-code'.
Jan 22 22:33:34 electric.marf.space systemd[1]: Stopped GoToSocial Server.
Jan 22 22:33:34 electric.marf.space systemd[1]: gotosocial.service: Consumed 13min 30.238s CPU time.
Jan 22 22:33:34 electric.marf.space systemd[1]: Starting GoToSocial Server...
Jan 22 22:33:34 electric.marf.space systemd[1]: Started GoToSocial Server.
```

While in this broken state, my Grafana instance catches Caddy's "HTTP requests in flight" inflates to my concurrency limit and pegs there. Is GtS not closing throttled connections? These aren't "Real" connections. I'm not being DDoSed with organic traffic; they're ghosts or they're re-attempts, but I don't think they're re-attempts as the logs don't indicate remote instances dialing back fast enough to cause the barber shop door to get jammed:

```
Jan 22 18:17:57 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 18:17:57.796" func=middleware.Logger.func1.1 level=ERROR latency="30.00117818s" clientIP="[SNIP]" userAgent="http.rb/5.1.0 (Mastodon/4.0.2; +https://gamemaking.social/)" method="POST" statusCode=503 path="/users/trysdyn/inbox" error="" msg="Service Unavailable: wrote 69B"
Jan 22 18:19:52 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 18:19:52.964" func=middleware.Logger.func1.1 level=ERROR latency="30.000418975s" clientIP="[SNIP]" userAgent="http.rb/5.1.0 (Mastodon/4.0.2; +https://gamemaking.social/)" method="POST" statusCode=503 path="/users/trysdyn/inbox" error="" msg="Service Unavailable: wrote 69B"
Jan 22 18:23:22 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 18:23:22.249" func=middleware.Logger.func1.1 level=ERROR latency="30.001064245s" clientIP="[SNIP]" userAgent="http.rb/5.1.0 (Mastodon/4.0.2; +https://gamemaking.social/)" method="POST" statusCode=503 path="/users/trysdyn/inbox" error="" msg="Service Unavailable: wrote 69B"
Jan 22 18:24:58 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 18:24:58.193" func=middleware.Logger.func1.1 level=ERROR latency="30.003011722s" clientIP="[SNIP]" userAgent="http.rb/5.1.0 (Mastodon/4.0.2; +https://gamemaking.social/)" method="POST" statusCode=503 path="/users/trysdyn/inbox" error="" msg="Service Unavailable: wrote 69B"
Jan 22 18:29:45 electric.marf.space gotosocial[1496955]: timestamp="22/01/2023 18:29:45.855" func=middleware.Logger.func1.1 level=ERROR latency="30.000386627s" clientIP="[SNIP]" userAgent="http.rb/5.1.0 (Mastodon/4.0.2; +https://gamemaking.social/)" method="POST" statusCode=503 path="/users/trysdyn/inbox" error="" msg="Service Unavailable: wrote 69B"
```

For the sake of documentation my `advanced-throttling-multiplier` is 16. This has been extremely clean for fixing my "Hug of death" problem, as an aside.

### What you expected to happen?

N/A

### How to reproduce it?

At present I have no idea. It Just Happens, usually while I'm not actively watching my timeline. I've bumped logging up to DEBUG and will loop back if anything else shows up. By tradition it should be 3-5 days.

You might be able to replicate by artificially hitting the throttling limit with generated traffic and leaving the worker pool saturated for a period of time. If debug logging doesn't show anything useful I might try to cobble that together myself.

### Anything else we need to know?

If I had to guess what's going on: it's possible connections aren't being closed and workers not being freed in some situation. While in the broken state, caddy reports having 20+ requests in flight at all times all of which on the s2s side get slammed shut with a 503 Service Unavailable. This tracks with my 1 CPU throttling multiplier of 16 + a couple of websockets and such for personal use.

If I were being bombed with natural traffic I'd presume at least some requests would get responses, not 100% failure. My gut tells me the pool's crammed with zombie workers.

`Retry-After` seems to not be the cause, I think other fedi software ignores it.

**Comment by tsmethurst** [comment]
I see you're on a commit that's main but from 2 weeks ago: I believe we might have fixed this with the media processing updates we did recently-ish, so it might be worth running on a more recent commit and seeing if the problem still occurs

**Comment by trysdyn** [comment]
You know, that might have been smart of me to do yes.. apologies.

Since I don't know what causes it, let's see if it just stops happening. I can re-open if it happens again.

**Comment by tsmethurst** [comment]
No need to apologize :) hope it's fixed, fingers crossed!
