### ISSUE TITLE
[feature] Implement the /api/v2/instance endpoint

### ISSUE THREAD

**Issue by japareaggae** [superseriousbusiness/gotosocial#1388]
### Is your feature request related to a problem ?

Newer Mastodon clients use the /api/v2/instance endpoint which was introduced in Mastodon 4.0. For example, Ivory for iOS: https://github.com/superseriousbusiness/gotosocial/issues/1339, as verified by Takahē: https://github.com/jointakahe/takahe/issues/473

### Describe the solution you'd like.

The /api/v2/instance endpoint is implemented, increasing compatibility with newer clients.

### Describe alternatives you've considered.

Adding support for the /api/v1/instance endpoint on the clients is an option, however this endpoint was deprecated by Mastodon in version 4.0, so some clients may choose not to support it. 

### Additional context.

Here is a diff between the /api/v1/instance and /api/v2/instance responses for mastodon.social: [instancediff.txt](https://github.com/superseriousbusiness/gotosocial/files/10509254/instancediff.txt)

A summary of changes I've spotted:

- Added `source_url`
- Added `usage`
- `translation` was added into `configuration`
- `uri` renamed to `domain`
- `short_description` renamed to `description`
- `urls` was rolled into `configuration`
- `registrations`, `approval_required` and `invites_enabled` were rolled into a `registrations` dict
- `email` and `contact_account` were rolled into a `contact` dict
- `thumbnail` was changed into a dict
- Removed `stats`

I'm creating this issue since I didn't see the /api/v2/instance endpoint on the ROADMAP.md file.

**Comment by tsmethurst** [comment]
Ah thanks :)
