### ISSUE TITLE
[performance] Implement retry logic for `SQLITE_BUSY` errors generated in WAL mode

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#1407]
We've been playing around in the last few weeks with SQLite tuning and WAL mode without shared cache.

See:

- https://www.sqlite.org/wal.html
- https://activesphere.com/blog/2018/12/24/understanding-sqlite-busy

In WAL mode, when running with more than one DB connection, we sometimes get `SQLITE_BUSY` errors, which can cause all sorts of oddness.

To resolve this, we have to write some logic somewhere in our database package to retry queries when receiving an `SQLITE_BUSY` error -- the official SQLite docs even say:

> there are some obscure cases where a query against a WAL-mode database can return [SQLITE_BUSY](https://www.sqlite.org/rescode.html#busy), so applications should be prepared for that happenstance.

For now, a decent interim solution was to always tune SQLite to use only 1 database connection, regardless of CPU count and CPU multiplier, but in future for better performance we can change this :)

**Comment by NyaaaWhatsUpDoc** [comment]
worth noting it would work quite well handling this while moving away from using bun (our ORM). bun is unfortunately quite inflexible in allowing us to handle these kinds of things.

**Comment by tgulacsi** [comment]
The cleanest case would be to have one goroutine handle all the writes (INSERT/DELETE/UPDATE) on one dedicated db.Conn, and all other queries (SELECT) could use any more connections.

But this assumes we don't use transactions, or the whole transaction must be processed by the writer goroutine.

And all this is only for SQLite, as PostgreSQL has lesser isolation level (READ COMMITED), and the SERIALIZABLE is opt-in.

**Comment by NyaaaWhatsUpDoc** [comment]
After current open PRs have been dealt with, I'm going to take a look at maybe opening some PRs to `uptrace/bun` to expand it more for our usecase here (or at least try to). And hopefully see if there's any other performance improvements I can make to their library as those are obviously wins for us too :)

**Comment by tsmethurst** [comment]
Closed by https://github.com/superseriousbusiness/gotosocial/pull/2025
