### ISSUE TITLE
[bug] webfinger queries don't work for the URLs I get in activities for recipients/actors

### ISSUE THREAD

**Issue by SaulMoonves** [superseriousbusiness/gotosocial#1415]
### Describe the bug with a clear and concise description of what the bug is.

When I get an AP activity, the recipients/actors are by URL, that is the only structured data I have at that point, so I pass those to the URL host's WebFinger to get the full information for the actor. However Gotosocial WebFinger query doesn't work for account URLs even if they're in the WebFinger response aliases or rel="self", that I get if I happen to already know the subject name (handle) to pass to it.

My desired behavior is being able to query these URLs on GotoSocial's WebFinger and get back a successful result. Doing so by URL conforms with the WebFinger RFC as I understand it and all the other major AP servers I've tried handle it. I believe it is desirable because the AP object body is not required to contain anything that would help me get that canonical subject name that GotoSocial WebFinger currently expects, I should be able to use the structured data provided.

### What's your GoToSocial Version?

GoToSocial 0.6.0 git-f9e5ec9

### GoToSocial Arch

dunno

### Browser version

curl

### What happened?

```
curl "https://fedi.jmizzle.com/.well-known/webfinger?resource=https%3A%2F%2Ffedi.jmizzle.com%2Fusers%2Fjawsh"
{"error":"bad webfinger request with resource query https://fedi.jmizzle.com/users/jawsh"}
```

querying by URI doesn't work.

### What you expected to happen?

```
curl "https://fedi.jmizzle.com/.well-known/webfinger?resource=acct:jawsh@fedi.jmizzle.com"
{"subject":"acct:jawsh@fedi.jmizzle.com","aliases":["https://fedi.jmizzle.com/users/jawsh","https://fedi.jmizzle.com/@jawsh"],"links":[{"rel":"http://webfinger.net/rel/profile-page","type":"text/html","href":"https://fedi.jmizzle.com/@jawsh"},{"rel":"self","type":"application/activity+json","href":"https://fedi.jmizzle.com/users/jawsh"}]}
```

I expect to get the same result if I query using acct format

### How to reproduce it?

always happens, see curl statements in above sections.

### Anything else we need to know?

Every other server implementation I've tried does it. I'm cooperating with someone else who is running GotoSocial, I am not running it so my insight is limited, I am just trying to interop with it.

**Comment by daenney** [comment]
I hadn't seen this before and the RFC is a bit ambiguous about it:

> WebFinger requests include a "resource" parameter (see Section 4.1) specifying the query target (URI) for which the client requests information.  WebFinger is neutral regarding the scheme of such a URI: it could be an "acct" URI [18], an "http" or "https" URI, a "mailto" URI [19], or some other scheme.

It's basically "it could be anything, and you should make sense of it somehow" which isn't amazingly helpful. That said, supporting `https` at least seems like something that's probably worth doing.

**Comment by SaulMoonves** [comment]
You're right, the RFC does not specify any kind of mapping and WebFinger isn't an AP-specific or an AP-aware thing so it's pretty wide-open. However I am only proposing gotosocial be able to find actors by exact match to URLs that it's already returning in WebFinger queries (as aliases or "rel":"self","type":"application/activity+json" hrefs) and using in ActivityPub objects as actor/to/cc/bcc.

For context I have a long-running ActivityPub bot on the Fediverse that receives AP notes and replies to them. I do a WebFinger query on everybody tagged in the note I receive so to that I can get the canonical URI and ActivityPub actor profile URL (which I query and check tags for "nobot") for every tagged actor. Then by that canonical URI I store important settings like "this actor has opted out of bot interaction", and respect that and do not tag them in replies or store further information about them beside opt-out flag. There are a wide variety of Fediverse AP implementations and there is no standard or even universally-followed convention for AP actor HTTPS URLs that allows me to parse out the username used for constructing the "acct:username@domain" Mastodon convention that gotosocial right now requires for WebFinger queries. As a result my bot does not work with gotosocial. Your software is great and I see more and more gotosocial servers showing up and a couple of your users asked why my bot wasn't working for them and I tracked this down.

I am perpetually short on time or I would have just sent you a pull request instead of an issue, but I absolutely respect your time as well so I'm not demanding you take action. I can wait or I can just submit you a pull request when I get around to it, or else maybe I could offer a small Paypal bounty for this (I think, fairly small) change if someone else wants to do it and do some minor testing against my bot (post a note at it until it doesn't error out lol.)

Thank you for reading.

**Comment by tsmethurst** [comment]
Can I ask what bot this is?

Also, if you're receiving AP notes then you should already have everything you need in the note to make the queries: make an AP call to dereference the note author and then make a webfinger call using the preferredUsername of the author to get the proper accountDomain. If you have just a mention like `@someone@somewhere.com` then that's also enough.

**Comment by NyaaaWhatsUpDoc** [comment]
We are not interested in taking contributions or working with somone happy to remain civil with transphobes (Alex Gleason). You posted knowing about the lack of support between soapbox and gotosocial so this is something you were at least marginally aware of.

**Comment by alexgleason** [comment]
Lunatic behavior. Ignoring bugs because of _guilt by association_. I wonder if NLnet is aware you act like this.
