### ISSUE TITLE
[bug] [Ice Cubes] Unable to follow accounts

### ISSUE THREAD

**Issue by darrinsmart** [superseriousbusiness/gotosocial#1419]
### Describe the bug with a clear and concise description of what the bug is.

Another client compatibilty issue. Ice Cubes requires the `/api/v1/accounts/:id/featured_tags` endpoint to succeed, or it won't show a follow button for account profile pages.

I see that implementing this is already on the roadmap, I'm making this report just to note that Ice Cubes is affected. Hope thats ok.

Also reported here: https://github.com/Dimillian/IceCubesApp/issues/520

### What's your GoToSocial Version?

v0.6.0 git-3283900

### GoToSocial Arch

x86_64

### Browser version

Ice Cubes

### What happened?

When viewing account profile pages with Ice Cubes, the follow button is missing from the UI.

This only happens with my GoToSocial instance.

It turns out it is because the client is receiving a 404 for the featured_tags request.

### What you expected to happen?

Would expect to see a Follow button.

### How to reproduce it?

Open Ice Cubes, connect to a GTS account. View a profile.

The follow button is normally part of the header.

### Anything else we need to know?

I was about to work around it with a little nginx hack:

```
    # Workaround for missing API + Ice Cubes                                                                                                      
    location ~ ^/api/v1/accounts/[0-9A-Z]+/featured_tags {
        default_type application/json;
        return 200 '[]';
    }
```

This causes Ice Cubes to get an empty list instead of a 404. With that I was able to see the button, follow and un-follow accounts.

GoToSocial is also returning 404 for `api/v1/accounts/familiar_followers`, but Ice Cubes seems to be able to handle that.

**Comment by tsmethurst** [comment]
I'll stub the featured tags endpoint out for now, since we'll be implementing it properly later :)
