### ISSUE TITLE
Hide\blur images when sensitive flag set to true

### ISSUE THREAD

**Issue by jk-na** [superseriousbusiness/gotosocial#142]
This is a known missing feature so far as I understand (as field was missing from go-fed) so just raising the ticket as a placeholder.

When I post a sensitive\content warning status via the API with an image attached, the status is correctly collapsed behind the subject but currently the image is not hidden, even if `sensitive=true`.

**Comment by tsmethurst** [comment]
We've got a PR open against go-fed rn for adding the sensitive property: https://github.com/go-fed/activity/pull/154

If this is accepted, we can add this into GtS as well :crossed_fingers:
