### ISSUE TITLE
Manually approve follow requests

### ISSUE THREAD

**Issue by memo-567** [superseriousbusiness/gotosocial#1431]
### Is your feature request related to a problem ?

This seems not to work yet? Despite switching on, anyone who wants can still follow me 🤔

Is this planned in the near future?

### Describe the solution you'd like.

![go2social hw2k com -  2023 - 02 - 06  07 - 31](https://user-images.githubusercontent.com/58190287/216900555-c01cba39-a40a-4223-b059-ebb195213fa1.jpg)

### Describe alternatives you've considered.

./.

**Comment by tsmethurst** [comment]
Heya, this should already be implemented and working, i'll check it out

**Comment by memo-567** [comment]
The follow-up request already appears as a notification, but I can't find a way to approve it anywhere in Pineafore.

**Comment by tsmethurst** [comment]
Ahhh okay! in pinafore it's in the `community` tab at the top, then there should be a `follow requests` thingy in there (see screenshot)

![Screenshot from 2023-02-06 09-54-23](https://user-images.githubusercontent.com/31960611/216927765-0a3185f8-4b3d-44cf-a461-383b30b1fbe3.png)

Does that work?

**Comment by memo-567** [comment]
So that's where it's hidden 😀
Thank you, it works perfectly now.

**Comment by tsmethurst** [comment]
Glad to hear it! :)
