### ISSUE TITLE
v0.7.0-rc1 /tmp directory 

### ISSUE THREAD

**Issue by memo-567** [superseriousbusiness/gotosocial#1433]
### Describe the bug with a clear and concise description of what the bug is.

`GoToSocial now requires access to your /tmp directory`

Which `/tmp` directory do you mean? I have several on this server but none under the `GoToSocial` directory.

Thanks for help 😀

### What's your GoToSocial Version?

v0.7.0-rc1

### GoToSocial Arch

Binary on Debian 11

### Browser version

All

**Comment by NyaaaWhatsUpDoc** [comment]
tmp as in your machine's global `/tmp` directory. It will fetch it using
`os.TempDir()`, which follows:

"TempDir returns the default directory to use for temporary files.

On Unix systems, it returns $TMPDIR if non-empty, else /tmp. On Windows, it
uses GetTempPath, returning the first non-empty value from %TMP%, %TEMP%,
%USERPROFILE%, or the Windows directory. On Plan 9, it returns /tmp."

**Comment by memo-567** [comment]
It seems to me that I haven't set something quite right there.
Videos are currently not working with my installation.

However, I did not make any additional settings. Should I ?

![20230220-1215](https://user-images.githubusercontent.com/58190287/218079001-9071572b-c49f-482f-b14e-5d967cb8276d.jpg)

**Comment by memo-567** [comment]
Sorry - doesn't work with Pinafore, but with Halcyon. So everything seems to be ok with the config.
