### ISSUE TITLE
[bug/0.7.0-rc1] Error pruning meta: store/storage key not found

### ISSUE THREAD

**Issue by joelghill** [superseriousbusiness/gotosocial#1441]
### Describe the bug with a clear and concise description of what the bug is.

After updating to the release candidate the service fails to start. Error when attempting to prune data.

```
timestamp="06/02/2023 22:49:47.520" func=media.(*manager).PruneUnusedLocalAttachments level=INFO msg="PruneUnusedLocalAttachments: pruning unused local attachments older than 2023-02-03 22:49:47.520686506 +0000 UTC m=-259199.764128210"
timestamp="06/02/2023 22:49:47.524" func=media.(*manager).PruneAllRemote level=INFO msg="PruneAllRemote: finished pruning remote media: pruned 0 entries"
timestamp="06/02/2023 22:49:47.524" func=admin.(*processor).MediaPrune.func1 level=INFO msg="MediaPrune: pruned 0 remote cache entries"
timestamp="06/02/2023 22:49:47.561" func=media.(*manager).PruneUnusedLocalAttachments level=INFO msg="PruneUnusedLocalAttachments: finished pruning: pruned 0 entries"
timestamp="06/02/2023 22:49:47.561" func=admin.(*processor).MediaPrune.func2 level=INFO msg="MediaPrune: pruned 0 unused local cache entries"
timestamp="06/02/2023 22:49:47.591" func=admin.(*processor).MediaPrune.func3 level=ERROR msg="MediaPrune: error pruning meta: store/storage: key not found: The specified key does not exist."
```

I'm using S3 storage and recently changed the access credentials. This version was working fine until then

### What's your GoToSocial Version?

v0.7.0-rc1

### GoToSocial Arch

amd64 binary

### Browser version

N/A

### What happened?

1. Installed an ran v0.7.0-rc1 binary
2. Decided to rotate my S3 credentials
3. Restarted service with new credentials in config file

### How to reproduce it?

Rotate S3 credentials while service is down. Start gotosocial binary after rotating credentials in S3 then start service.

### Anything else we need to know?

v0.7.0-rc1 was working fine until I brought the service down and updated S3 credentials. It's possible I have another error in my config file since I updated with latest example config from main branch.

**Comment by tsmethurst** [comment]
This sounds similar to https://github.com/superseriousbusiness/gotosocial/issues/1434 which has now been fixed on main and will be in a release candidate soon. I'm curious why this is showing up since changing your credentials though, that's very strange. You're positive the new credentials are correct and have proper read permissions on the bucket?

**Comment by joelghill** [comment]
> This sounds similar to #1434 which has now been fixed on main and will be in a release candidate soon. I'm curious why this is showing up since changing your credentials though, that's very strange. You're positive the new credentials are correct and have proper read permissions on the bucket?

I _think_ they are correct and have the proper read permissions, but I'll double check. There was a point where the credentials we not updated in the server config and I had an authentication error in the logs. Since updating the config with the new credentials I no longer see that auth error.
