### ISSUE TITLE
[bug] Likes disappear

### ISSUE THREAD

**Issue by memo-567** [superseriousbusiness/gotosocial#1446]
### Describe the bug with a clear and concise description of what the bug is.

After updating the home timeline (F5 or dragging the page down in Android), the previous likes are no longer displayed.

Tested with Tusky, Pinafore, Halcyon...

### What's your GoToSocial Version?

v0.7.0-rc1

### GoToSocial Arch

Debian 11

### Browser version

All

**Comment by tsmethurst** [comment]
Thanks! This is to do with likes not being propagated through to the home timeline. I'll make another issue describing the problem and link this one :)

**Comment by memo-567** [comment]
Thank you 😀
