### ISSUE TITLE
[chore] Update prepared entries in the home timeline linked list with latest faves/boosts/replies

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#1449]
Currently we implement timelines as a linked list of 'indexed' entries and 'prepared' entries, where 'prepared' items are API models that are ready to be serialized on demand.

This is nice and speedy when fetching timelines. However, it also means that prepared items can get out of date. For example, say a user scrolls through their home timeline and faves a post. The fave is put in the database, updated in the cache, and propagated out to the remote instance as a Like with no problem. However, the prepared entry in the timeline has not been updated to reflect the fave. For the user, this means that faves seem to disappear after the refresh their home timeline (see https://github.com/superseriousbusiness/gotosocial/issues/1446).

One possible solution to this: when a user interacts with a post (replies, faves, boosts), we should then iterate through that user's home timeline, find the post they interacted with, and update the API model representation to include the interaction.

**Comment by NyaaaWhatsUpDoc** [comment]
My plan is to eventually have the timeline cache stored under the main set of state caches, so whenever these types of actions happen across the codebase we can easily invalidate all caches for a status of given ID.

**Comment by decentral1se** [comment]
Coooool, got any pointers for an approach on a fix? Assume nobody is working on this.

I ran into https://github.com/superseriousbusiness/gotosocial/issues/1446 myself and would like to help try to fix this. Will take a run at it next time.

**Comment by NyaaaWhatsUpDoc** [comment]
It will need waiting until a current open PR changing a lot of timeline code is merged I'm afraid. Will also need discussing first in the matrix as there's a number of things to keep in mind :)
