### ISSUE TITLE
[bug/0.7.0-rc1] Long handle in reports form pushes report status

### ISSUE THREAD

**Issue by turtlegarden** [superseriousbusiness/gotosocial#1456]
### Describe the bug with a clear and concise description of what the bug is.

In the *Reports* user interface, a long user handle can push the report status to the side on smaller screen widths as shown below (with the expected behavior beside, for side-to-side comparison):

![The above described graphical glitch, with a long user handle pushing the report status off the page](https://user-images.githubusercontent.com/52264162/217391267-bd1af1c0-5d9c-416b-99fb-e516e1ab7085.png)

### What's your GoToSocial Version?

v0.7.0-rc1

### Browser version

Bromite 108, WebKitGTK 2.38.3, Firefox 109

### What happened?

The user handle does not wrap and pushes the report status out of the container.

### What you expected to happen?

The user handle should wrap on small screens and not push the report status out of the container.

### How to reproduce it?

Report a user from a long domain, or change the HTML to make a fake user from a long domain, and then load it on a small screen.

### Anything else we need to know?

I already have a pull request mostly complete that fixes this issue, and tidies up some CSS bugs with wrapping user handles.

**Comment by turtlegarden** [comment]
about the PR— it fixes the issues but it uses some things like 60% max width when the sidebar wraps to the top, so it's *somewhat* hacky

**Comment by f0x52** [comment]
ah hmm, well you can open it as draft and I'll take a look (have some different ideas too)

**Comment by f0x52** [comment]
![image](https://user-images.githubusercontent.com/23422690/217618794-eda9506e-b6c8-466d-8b7d-defeda368f96.png)
that should do it
