### ISSUE TITLE
New posts made by new followed user does not show in timeline

### ISSUE THREAD

**Issue by memo-567** [superseriousbusiness/gotosocial#1459]
### Describe the bug with a clear and concise description of what the bug is.

New posts made by new followed user does not show in timeline.

### What's your GoToSocial Version?

GoToSocial 0.7.0-rc1 git-02767bf

### GoToSocial Arch

amd64 binary / debian 11

**Comment by tsmethurst** [comment]
We can't really do anything with an issue like this, without logs or a way of reproducing it, so I'm going to close it for now but feel free to reopen it if you can add some logs and whatnot to help us debug.

**Comment by memo-567** [comment]
To reproduce this issue is very simple: 
Follow a user, wait that his posts appear in TL - but they didn't. Checked this with a second account on Mastodon.
