### ISSUE TITLE
[bug/0.7.0-rc1] search api returns "Internal Server Error" when searching for domain blocked accounts

### ISSUE THREAD

**Issue by Pectojin** [superseriousbusiness/gotosocial#1462]
### Describe the bug with a clear and concise description of what the bug is.

I have a small script that reads a blocked_accounts.csv export from a mastodon export (newline separated handles), uses search to get a GTS account id for each, and then calls block on the id.

However, when I call search on specific accounts I get html back:
```
response code: 500
<!DOCTYPE html>
...
    <main>
        <section class="error">
          <span>❌</span> <pre>Internal Server Error</pre>
        </section>
    </main>
...
```

Checking the logs it becomes more obvious why:
```
timestamp="08/02/2023 13:29:54.760" func=transport.(*transport).do level=INFO pubKeyID=https://gts.example.com/users/user/main-key method=GET url=https://blocked.example.com/.well-known/webfinger?resource=acct:username@blocked.example.com msg="performing request"
timestamp="08/02/2023 13:29:54.781" func=router.loggingMiddleware.func1 level=ERROR latency=29.63453ms clientIP=192.168.2.1 userAgent=Ruby method=GET statusCode=500 path=/api/v1/search error="Error #01: error looking up account: transport error: GetRemoteAccount: error dereferencing Accountable: DereferenceAccountable: domain blocked.example.com is blocked\n" msg="Internal Server Error: wrote 600B"
timestamp="08/02/2023 13:29:54.786" func=transport.(*transport).do level=INFO pubKeyID=https://gts.example.com/users/user/main-key method=GET url=https://blocked.example.com/.well-known/webfinger?resource=acct:username@blocked.example.com msg="performing request"
timestamp="08/02/2023 13:29:54.792" func=router.loggingMiddleware.func1 level=ERROR latency=10.81018ms clientIP=192.168.2.1 userAgent=Ruby method=GET statusCode=500 path=/api/v1/search error="Error #01: error looking up account: transport error: GetRemoteAccount: error dereferencing Accountable: DereferenceAccountable: domain blocked.example.com is blocked\n" msg="Internal Server Error: wrote 600B"
timestamp="08/02/2023 13:29:54.796" func=transport.(*transport).do level=INFO pubKeyID=https://gts.example.com/users/user/main-key method=GET url=https://blocked.example.com/.well-known/webfinger?resource=acct:username@blocked.example.com msg="performing request"
timestamp="08/02/2023 13:29:54.803" func=router.loggingMiddleware.func1 level=ERROR latency=10.685723ms clientIP=192.168.2.1 userAgent=Ruby method=GET statusCode=500 path=/api/v1/search error="Error #01: error looking up account: transport error: GetRemoteAccount: error dereferencing Accountable: DereferenceAccountable: domain blocked.example.com is blocked\n" msg="Internal Server Error: wrote 600B"
```

### What's your GoToSocial Version?

v0.6.0

### GoToSocial Arch

x86 binary installed in custom docker image

### Browser version

Ruby 3.0 net/http library 

### What happened?

Using the search api for accounts on a domain blocked instance returns html.

E.g.:
```
https://gts.example.com/api/v1/search?type=accounts&exclude_unreviewed=false&q=user%40example.com&resolve=true&limit=1&following=false
```

### What you expected to happen?

Should probably return `{"accounts":[],"statuses":[],"hashtags":[]}` similarly to what search returns when you search for an already blocked account.

### How to reproduce it?

Use the search api to search for an account on a domain blocked instance

**Comment by f0x52** [comment]
on rc1 this seems to at least give a json response with the error, but still a 500 internal server error instead of an empty result (or actually informative error)

**Comment by tsmethurst** [comment]
Mm, this seems like two separate issues indeed.

For the HTML stuff, make sure you're adding 'accept: application/json' to your request headers in your script.

**Comment by Pectojin** [comment]
Ah, I had `'Content-Type' => 'application/json'` in there, but not `'Accept' => 'application/json'` now I get `{"error":"Internal Server Error"}`

So let me amend the title to be just the error, not the html. The second "bug" is just my mistake.
