### ISSUE TITLE
[bug/federation] Replies to Lemmy posts don't show up on Lemmy instance

### ISSUE THREAD

**Issue by kvibber** [superseriousbusiness/gotosocial#1468]
### Describe the bug with a clear and concise description of what the bug is.

GoToSocial is able to see Lemmy posts, boost them and reply to them, and the replies and boosts will federate to Mastodon followers, but the replies don't seem to federate back to Lemmy. 

### What's your GoToSocial Version?

0.7.0rc1

### GoToSocial Arch

amd64 docker

**Comment by kvibber** [comment]
Apparently Lemmy doesn't do signed fetches yet:
https://socialhub.activitypub.rocks/t/help-improving-federation-between-lemmy-and-other-projects/2308/39

**Comment by daenney** [comment]
That would explain it. It also means Lemmy would already have issue federating with people on certain Mastodon instances if those run in "secure mode", i.e have https://docs.joinmastodon.org/admin/config/#authorized_fetch enabled. Pleroma has a similar setting as do most other implementations, though it's not enabled by default.

I suspect that's likely to change over time though so the longer it goes unimplemented in Lemmy the more federation issues users will experience. There are a couple of Rust crates available that implement HTTP signatures so hopefully the Lemmy devs wouldn't have to do this from scratch.

**Comment by trashhalo** [comment]
linking related issue on lemmy https://github.com/LemmyNet/lemmy/issues/868

**Comment by Nutomic** [comment]
FYI signed fetch will be supported in Lemmy soon (probably in 0.19.0), but will have to be enabled by instance admins.

https://github.com/LemmyNet/lemmy/pull/4125

**Comment by tsmethurst** [comment]
I think this can be closed now (see https://github.com/superseriousbusiness/gotosocial/issues/2697 for more in-depth discussion on federation issues between lemmy + gts).
