### ISSUE TITLE
[chore] Rationalise HTTP return codes for ActivityPub handlers

### ISSUE THREAD

**Issue by Sentynel** [superseriousbusiness/gotosocial#1470]
There are currently some odd behaviours when we process _valid_ but _unhandled_ ActivityPub requests. For example, we return 400 in case of an operation we don't support, e.g. `{"@context":"https://www.w3.org/ns/activitystreams","type":"Remove","actor":"https://mstdn.social/users/Bellingcat","target":"https://mstdn.social/users/Bellingcat/collections/featured","object":"https://mstdn.social/users/Bellingcat/statuses/109761787728067871"}`. (This is a request to unpin a status, which we might want to handle at some point, but is useful as an example.) Tobi also points out that we "return 403 if the incoming post contains a mention of a user that the inbox owner has blocked, which doesn't make much sense either".

We should make these more sensible. From discussion in chat, it seems like the preferred approach is to reserve 400 for unparseable requests, and return 202 in case of unhandled but valid requests. (There's also 501 Not Implemented, but we'd rather not accidentally trigger retries or unreachable server handling on the remote side.) It's non-trivial to tell a request which is _valid ActivityPub_ but which we don't support from a request that's _invalid ActivityPub_ but JSON parses cleanly and otherwise passes basic checks, but it seems like the best option is just to return 202 OK Whatever (sorry, Accepted) in those cases.

**Comment by tsmethurst** [comment]
Aha thank you for writing this down!

**Comment by NyaaaWhatsUpDoc** [comment]
the 403 on on incoming mention by blocked user shouldn't apply anymore

as for other unhandled types, looking at the code it's not quite clear cut. a lot has changed in the last year to the federation code! i shall continue digging

**Comment by tsmethurst** [comment]
Well indeed, we shouldn't do that :P I think it's fine for us to continue to just poll remote profiles every now and then and refetch pinned, and throw those Add / Remove messages away (since we don't own the collections that are being added / removed to/from anyway).

**Comment by NyaaaWhatsUpDoc** [comment]
handled in #2540
