### ISSUE TITLE
[bug] No replies on boosted messages

### ISSUE THREAD

**Issue by andi-makes** [superseriousbusiness/gotosocial#1471]
### Describe the bug with a clear and concise description of what the bug is.

Replies for Toots that are from people you are following seem to get fetched, replies for boosted toots seem to not be fetched.

### What's your GoToSocial Version?

0.7.0-SNAPSHOT git-e5e257c

**Comment by tsmethurst** [comment]
Heya, this is *sort of* known. The logic we have for dereferencing threads needs a bit of tweaking so that we can properly fetch replies, and we also need to periodically refetch them too (like we do now for account media).

**Comment by NyaaaWhatsUpDoc** [comment]
'tis on my list of todos :]

**Comment by tsmethurst** [comment]
This is fixed now! We did the requisite tweaking so threads are much more complete!
