### ISSUE TITLE
[feature] filter / mute words and hashtags

### ISSUE THREAD

**Issue by nikkicoon** [superseriousbusiness/gotosocial#1472]
### Is your feature request related to a problem ?

When I'm trying to add filters on hashtags or words in Tusky, I'm getting an error. I want to block posts about certain topics, this isn't possible so far (unless this problem is tusky exclusive).
I see this as an important feature, and I guess that this isn't implemented so far as I don't see it on the roadmap or in any other closed or open issues for "filter"

### Describe the solution you'd like.

I am able to filter posts.

### Describe alternatives you've considered.

None

**Comment by Sentynel** [comment]
Background: Mastodon provides guidance on the filter API [here](https://docs.joinmastodon.org/api/guidelines/#filters)  and full docs [here](https://docs.joinmastodon.org/methods/filters/) .

Summarising discussion in chat:

* The preferred approach to filtering would be client side. However, many clients don't support this, and an ideal world method for synchronising client side settings between clients would require participation from many clients.
* Mastodon uses a strange hybrid approach where the filter rules run server side, but posts are still supplied to the client with a list of matching rules and it's up to the client to take action. (Although apparently the old API it describes as "client side" would have the server remove posts in some cases!) This means both entirely removing posts and simply adding a content warning are both options, but requires both client and server support.
* Realistically, then, the simplest approach for supporting filtering would be to accept the Mastodon API for setting filters, but only handle "hide" filters and run this server side. Then you only need one client to support filtering to set the rules (this could be added to our settings page as well), and filtering will be applied for all clients. The only disadvantage to this approach is that you have to re-request posts from the client for updated filter rules to apply (the client can't un-hide a post it has but isn't showing after removing a rule). This seems manageable.

I'm happy to look at implementing this, but it's not going to be soon by any means, so anyone else interested in working on it is welcome to chat!

**Comment by f0x52** [comment]
As for leaving more advanced filtering to the client, @NyaaaWhatsUpDoc and me had similar ideas for a generic user configuration storage. Filtering rules would be one use-case but there's definitely more for generic user data shared between their clients. Matrix has something similar [[spec]](https://spec.matrix.org/v1.5/client-server-api/#client-config). We'll probably brainstorm more about this in a separate issue at some point.

There's also room for a separate compatibility layer (outside of GoToSocial) to convert from whatever we come up with to what Mastodon clients expect

**Comment by JJGadgets** [comment]
Has there been any traction on this? 

Truth be told, I'm getting annoyed recently just by _seeing_ some stuff, but unfollowing users entirely would mean losing out on other content that I might be interested in.

**Comment by tsmethurst** [comment]
> Has there been any traction on this?

Not yet, no! Likely one that we'll add to a milestone this year :)
