### ISSUE TITLE
[bug] Avatars are sometimes not loaded, on timeline

### ISSUE THREAD

**Issue by sandboxgangster** [superseriousbusiness/gotosocial#1473]
### Describe the bug with a clear and concise description of what the bug is.

Some Avatars are not loaded since 0.7.0-RC1, if you open the Provile they are partially displayed again, this worked in previous Versions.

### What's your GoToSocial Version?

0.7.0-RC1 git-02767bf

### GoToSocial Arch

arm64

### Browser version

Chrome 105.0.5195.102 (Offizieller Build) (64-Bit)

**Comment by tsmethurst** [comment]
Already fixed this on main, will be in rc2 soon :)
