### ISSUE TITLE
[bug] Can't search for @gotosocial@superseriousbusiness.org

### ISSUE THREAD

**Issue by mxrlkn** [superseriousbusiness/gotosocial#1475]
### Describe the bug with a clear and concise description of what the bug is.

When i search for "@gotosocial@superseriousbusiness.org" on Pinafore I get these logs:

```
timestamp="11/02/2023 14:22:25.562" func=transport.(*transport).do level=INFO pubKeyID=https://fedi.mxrlkn.com/users/mxrlkn/main-key method=GET url=https://gts.superseriousbusiness.org/@gotosocial msg="performing request"


timestamp="11/02/2023 14:22:25.727" func=middleware.Logger.func1.1 level=ERROR latency=170.892331ms clientIP=**** userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0" method=GET statusCode=500 path=/api/v2/search error="Error #01: error looking up status: transport error: GetRemoteStatus: error dereferencing statusable: DereferenceStatusable: error deferencing https://gts.superseriousbusiness.org/@gotosocial: GET request to https://gts.superseriousbusiness.org/@gotosocial failed (401): 401 Unauthorized\n" msg="Internal Server Error: wrote 54B"
```

I can search and follow other gotosocial instances just fine. I think I know what the issue is but I'm not 100% sure.

When I first created my instance I followed gotosocial and that worked, but then I messed up and had to recreate my instance and I used the same url/domain/user and now I can't even search for it. I can refollow/search mastodon users just fine even though i recreated it.

### What's your GoToSocial Version?

v0.7.0-rc2

### GoToSocial Arch

Docker amd64

**Comment by tsmethurst** [comment]
This sounds like the gts.superseriousbusiness.org instance probably cached your previous public key, and now refuses to federate with your new key because it assumes you're an imposter. Could you try creating another account on the same instance, and see if you can follow with that?

**Comment by mxrlkn** [comment]
Yes, I can follow it with a new account on the same instance.

**Comment by tsmethurst** [comment]
Right! That's the issue then: if you start federating with other instances, and then delete + recreate your profile with the same username, it is very likely to break federation with the instances you had already started interacting with. There are two possible workarounds for this:

1. Contact admins of instances you're having trouble federating with and see if they can delete / recreate your public key entry in their database.
2. Just create a new profile and use that instead.

**Comment by mxrlkn** [comment]
Right okay. I'll contact the admin then. I did the same mistake with some mastodon servers and they didn't have issues with it, so I thought it was a bug for gts.  Thanks for the help :)

**Comment by tsmethurst** [comment]
No problem, i'll close the issue if that's alright?
