### ISSUE TITLE
[bug/0.7.0-rc2] No permission to view S3 Media

### ISSUE THREAD

**Issue by joelghill** [superseriousbusiness/gotosocial#1493]
### Describe the bug with a clear and concise description of what the bug is.

Media is failing to load (profile pictures, profile banner). Clicking on images displays a permissions error related to S3 storage.

Example profile: https://alpha.flatlander.social/@joel

### What's your GoToSocial Version?

0.7.0-rc2

### GoToSocial Arch

amd64 binary

### Browser version

firefox - latest

### What happened?

Spun up a fresh install of 0.7.0-rc2 with an S3 bucket for media storage. Uploaded profile photos, etc, all worked well. 24 hours later the images no longer have permissions and are failing to load.

Looks like this might be covered in an upcoming PR but I'm not sure. Likely related to the media pruning changes?

### What you expected to happen?

Media should load

**Comment by joelghill** [comment]
Might be solved with this commit: https://github.com/superseriousbusiness/gotosocial/commit/c223c7598dcd44db9befcce8fb49c6dbbcfac36d

**Comment by tsmethurst** [comment]
Yep indeed it's solved with that commit :) Will be in a release soon, in the meantime you can switch to proxying s3 as a workaround!

**Comment by joelghill** [comment]
> Yep indeed it's solved with that commit :) Will be in a release soon, in the meantime you can switch to proxying s3 as a workaround!

Nice! And thanks, the proxy is working!
