### ISSUE TITLE
[chore] Refactor the `internal/federation/dereferencing` package

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#1497]
Right now it's a lot of spaghetti with functions calling one another all over the place, which is a consequence of the way the package grew.

We should consider spending some time refactoring this package to make it more readable:

- De-interface the dereferencer (#1469)
- Make domain block checks consistent and wrap domain block errors to avoid callers thinking something has really gone wrong.
- Try to come up with a clearer structure in terms of the order in which functions are called: it's not easy now to see the process.

More suggestions welcome below!

**Comment by NyaaaWhatsUpDoc** [comment]
I started some work on the GetStatus function last night :) and in doing so I'll probably try to get to a bunch of the functions in that file.

**Comment by tsmethurst** [comment]
Nice! I think mostly the actual logic is OK -- in the sense that it does what it needs to do. But the structure and the way errors from `internal/federation/dereferencing/errors.go` are used is not very consistent. This is one of the most organic, home-grown packages in the whole of GtS I think :')

**Comment by NyaaaWhatsUpDoc** [comment]
Oh my plan was a combo of refactor to bring it inline with GetAccount(),
and adding the status FetchedAt + refreshing support. The errors I was
planning on addressing at a later time replacing a lot of our wrapped
errors with
https://codeberg.org/gruf/go-errors/src/commit/0fa62be283990b67dae9bc7b13416c1da98bce44/value.go#L3
for passing back information. And in the process encapsulating the errors
all within `gtserrors`

**Comment by tsmethurst** [comment]
With changes since this issue was created, I think it's prettymuch resolved so I'll close it. We're constantly doing little refactors anyways so having a specific refactoring issue for one part of the codebase isn't really necessary.
