### ISSUE TITLE
[feature] Warn when HTTP host header does not match expected.

### ISSUE THREAD

**Issue by minecraftchest1** [superseriousbusiness/gotosocial#1503]
### Is your feature request related to a problem ?

Having the domain requested by clients be different then that expected by GoToSocial (`Host` config option) can lead to a 400 Bad Request during the OAuth login flow. This can be difficult to diagnose.

### Describe the solution you'd like.

Having a warining message in the log output that says something along the lines of `Request for $HTTP_HOST, expected $GTS_HOST?'` when the domains don't match.

### Describe alternatives you've considered.

Suggest in the Error message to check that the domain expected and the domain used match.

### Additional context.

[https://matrix.to/#/!mlPctfMHjyopbOnliM:superseriousbusiness.org/$IhMTK6T9QGGVXf1YWGjcvqRNby5MByE6dUKYO5Bme-g](https://matrix.to/#/!mlPctfMHjyopbOnliM:superseriousbusiness.org/$IhMTK6T9QGGVXf1YWGjcvqRNby5MByE6dUKYO5Bme-g?via=superseriousbusiness.org&via=matrix.org&via=tchncs.de)

**Comment by tsmethurst** [comment]
I'm going to close this because iirc the issue that prompted it was pretty niche and I don't think anyone else has run into it.
