### ISSUE TITLE
Should the application/activity+json Self document require a HTTP signature?

### ISSUE THREAD

**Issue by prologic** [superseriousbusiness/gotosocial#1513]
### Describe the bug with a clear and concise description of what the bug is.

Right now, on a recent instance of a spin up GotoSocial instance, it seems that you require a valid HTTP Signature (RSA-256) to ven make a request for a user's `rel=Self, type=application/activity+json`, which you find from an initial web finger lookup.

Mastodon instances don't require this, moreover, they also don't care about the `Accept` header and just give you the JSON back.

This makes is very hard to interoperate between Mastodon and GotoSocial instances.

### What's your GoToSocial Version?

GoToSocial 0.7.0 git-b599309

### GoToSocial Arch

amd64 Docker

### What happened?

Example request:

```console
$ ./apc GET https://gotosocial.mills.io/users/prologic
GET /users/prologic HTTP/1.1
Host: gotosocial.mills.io
User-Agent: Go-http-client/1.1
Accept: application/activity+json
Date: Fri, 17 Feb 2023 21:26:08 GMT
Signature: keyId="https://prologic.shortcircuit.net.au/1440EBD6.asc.txt",algorithm="hs2019",headers="(request-target) date",signature="tzHKFOebo/ekr0Ch0l6FbyaMsn1/c0EBMtoUOsP5d8kvlq0QFvlfZdTf28l838iVUoC0bx1M8SI0L3SlMlpW7Fq/e60y3FHDWvA1OfMfdkOk095S+ansx6Iqu6HCJhmjDDSepjCDbfSxM7YOfWEIoxaAAs1sfyxxbiDuTree7+U6FaJ0t0JnygA8bHv18xB+Maj2yOzuURqSlLK7ZC54oBn1kwTNCKyDWxoSle/jRANyplbfVG3PLySFEFzVdt3wCbvL3lRKgK6nhJmITLE5zjy3Lj53BfqedH3u2pSIC5vLPFpPHWbysLthgAqgf9MqC8h0C1lrd+CuRfT7mq5Z7w=="
Accept-Encoding: gzip


{"error":"Unauthorized"}
```

### What you expected to happen?

I expect the JSON back regardless of `Accept` header and I expect not to have to provide a HTTP signature as I'm just doing a lookup, I'm really not sure why a GotoSocial instance has to know who I am as an actor at this point?

### How to reproduce it?

Just curl the `rel=Self, type=application/activity+json` response of any user you get from a webfinger lookup.

**Comment by tsmethurst** [comment]
> Should the application/activity+json Self document require a HTTP signature?

Yes, this is one of the core values of GtS: http signatures required by default. It's one component in our approach to protecting users from scraping, and enforcing strict block policies (and it will be necessary in allowlist federation mode, in future).

> This makes is very hard to interoperate between Mastodon and GotoSocial instances.

How do you mean? Mastodon and GtS instances can communicate just fine with one another, since Mastodon implements signed GETs and POSTs. Mastodon itself, when in secure mode, has similar requirements to GtS when it comes to http signatures.

**Comment by prologic** [comment]
What is GtS?

**Comment by prologic** [comment]
So assuming gotosocial instances are opening in stick mode and mastodon.social is not, how do I properly send a request? I can't find good docs on this :/ This is my sample code:

```go
package main

import (
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/httputil"
	"os"
	"time"

	"github.com/go-fed/httpsig"
)

const pubKeyID = "https://prologic.shortcircuit.net.au/1440EBD6.asc.txt"

var (
	privKey *rsa.PrivateKey
	err     error
)

func init() {
	privKey, err = rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		panic(err)
	}
}

func sign(privateKey crypto.PrivateKey, pubKeyId string, r *http.Request) error {
	prefs := []httpsig.Algorithm{httpsig.RSA_SHA256}
	digestAlgorithm := httpsig.DigestSha256
	// The "Date" and "Digest" headers must already be set on r, as well as r.URL.
	headersToSign := []string{httpsig.RequestTarget, "date"}
	signer, _, err := httpsig.NewSigner(prefs, digestAlgorithm, headersToSign, httpsig.Signature, 30)
	if err != nil {
		return err
	}

	return signer.SignRequest(privateKey, pubKeyId, r, nil)
}

func main() {
	flag.Parse()

	method := flag.Arg(0)
	url := flag.Arg(1)

	req, err := http.NewRequest(method, url, nil)
	if err != nil {
		log.Fatalf("error creating request: %s", err)
	}
	req.Header.Add("Date", time.Now().Format(http.TimeFormat))
	req.Header.Add("Accept", "application/activity+json")

	if err := sign(privKey, pubKeyID, req); err != nil {
		log.Fatalf("error signing request: %s", err)
	}

	dump, err := httputil.DumpRequestOut(req, true)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Fprintf(os.Stderr, "%s\n", dump)

	res, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatalf("error making request: %s", err)
	}
	defer res.Body.Close()

	data, err := io.ReadAll(res.Body)
	if err != nil {
		log.Fatalf("error reading response: %s", err)
	}

	fmt.Println(string(data))
}
```

**Comment by tsmethurst** [comment]
Gonna close this now since we discussed it in matrix :)
