### ISSUE TITLE
[bug] oauth with OOB results in 404 on success

### ISSUE THREAD

**Issue by daenney** [superseriousbusiness/gotosocial#1518]
### Describe the bug with a clear and concise description of what the bug is.

I'm filing this on the backend and not frontend since ti's probably a case of "both".

When logging in to GTS, if the out-of-band method/OOB is used and succeeds you're directed to a `/oob?code=<HEX>` page. This code is necessary to then pass on to the client, but unfortunately GTS renders a 404 instead of a nice HTML page with the code. You have to notice that it's in the URL and pick it from there which especially on mobile is easily missed.

### What's your GoToSocial Version?

v0.7.0 git-f86152b

### GoToSocial Arch

amd64 binary

### What happened?

I tried to login using Whalebird.

### What you expected to happen?

A nice HTML page gets displayed with the auth code for you to copy.

### How to reproduce it?

Use any client that uses OOB to authenticate, like Whalebird or a CLI, and try to login.

**Comment by daenney** [comment]
Weirdly enough, we have an `oob.tmpl` and a handler that's supposed to render this:
* https://github.com/superseriousbusiness/gotosocial/blob/d39280ec3389a701604febb221d3e563a9a2c62f/web/template/oob.tmpl#L20-L25
* https://github.com/superseriousbusiness/gotosocial/blob/d39280ec3389a701604febb221d3e563a9a2c62f/internal/api/auth/oob.go#L105-L110

We have all the pieces, but they're not coming together as they should.

**Comment by f0x52** [comment]
the oob template is served at `/oauth/oob` but the oob flow redirects to `/oob`, working on the PR
