### ISSUE TITLE
[bug] React error when logging into user profile page.

### ISSUE THREAD

**Issue by jmscsns** [superseriousbusiness/gotosocial#1552]
### Describe the bug with a clear and concise description of what the bug is.

When I log into the user settings page (/settings/user/profile) I get an error report.

`Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bname%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

The main body is:

`th@https://sub.domain.tld/assets/dist/settings.js:12428:57173
e@https://sub.domain.tld/assets/dist/settings.js:12428:62182
Yi@https://sub.domain.tld/assets/dist/settings.js:12428:73709
Wk@https://sub.domain.tld/assets/dist/settings.js:12428:121922
Vk@https://sub.domain.tld/assets/dist/settings.js:12428:111701
Uk@https://sub.domain.tld/assets/dist/settings.js:12428:111632
Jk@https://sub.domain.tld/assets/dist/settings.js:12428:111501
Ok@https://sub.domain.tld/assets/dist/settings.js:12428:107942
Fk@https://sub.domain.tld/assets/dist/settings.js:12428:108746
Fk@[native code]
jg@https://sub.domain.tld/assets/dist/settings.js:12428:47684
Xk@https://sub.domain.tld/assets/dist/settings.js:12428:113220
Qk@https://sub.domain.tld/assets/dist/settings.js:12428:112198
Hk@https://sub.domain.tld/assets/dist/settings.js:12428:107738
Hk@[native code]
J@https://sub.domain.tld/assets/dist/settings.js:11304:1387
R@https://sub.domain.tld/assets/dist/settings.js:11304:1937
@https://sub.domain.tld/assets/dist/settings.js:11241:1180
@https://sub.domain.tld/assets/dist/settings.js:1761:2016
drainQueue@https://sub.domain.tld/assets/dist/settings.js:1761:1610`

This appears similar to [issue 1478](https://github.com/superseriousbusiness/gotosocial/issues/1478), but in my case it occurs immediately after logging in. No errors are recorded in the syslog.

### What's your GoToSocial Version?

v0.7.1

### GoToSocial Arch

arm64 binary

### What happened?

When I attempt to login to my user profile settings, I am asked for my user name and password, but the page presents an error.

The site settings page loads normally and appears to function.

### What you expected to happen?

I can log into my admin page.

### How to reproduce it?

Logging into my admin page.

**Comment by f0x52** [comment]
can you check the developer console (F12) for the underlying error?

**Comment by jmscsns** [comment]
It has the same error as above and two 404 errors:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (01FPXVN2BN8FY4AP1QM34P96C2.jpeg, line 0) 
![]
(https://sub.domain.tld/fileserver/01XGKM5GNBV0EA2RPHR7CKKZDJ/attachment/original/01FPXVN2BN8FY4AP1QM34P96C2.jpeg)
```
and 
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (01H0DWGGF7XKMD29SZGEQNHNBY.jpeg, line 0)
![](https://sub.domain.tld/fileserver/01XGKM5GNBV0EA2RPHR7CKKZDJ/attachment/original/01H0DWGGF7XKMD29SZGEQNHNBY.jpeg)
```
I don't know javascript (beyond a 'Hello World') or the developer console, but it seems to be triggered by line 35,251 in settings.js (`console.error(n.value)`) but that appears to be part of an error-trapping function, so not sure it's that helpful!

**Comment by dym-sh** [comment]
for me solution was to re-compile script files from `main` branch

> https://github.com/superseriousbusiness/gotosocial/blob/main/web/source/package.json#L10

```sh
git clone https://github.com/superseriousbusiness/gotosocial
cd ./gotosocial/web/source/
yarn install
yarn run build
```

and replace them on the server with new ones

`ls ./gotosocial/web/assets/dist/*.js`

**Comment by jmscsns** [comment]
Didn't do a rebuild, but you found the problem.


It was my error. I misinterpreted the 0.7.0 to 0.7.1 instructions and just replaced the binary, replacing the web folder has fixed all the problems.

**Comment by jmscsns** [comment]
Thanks. I didn't do a rebuild but you found the problem.

> and replace them on the server with new ones
> 
> `ls ./gotosocial/web/assets/dist/*.js`

It was my error. I misinterpreted the 0.7.0 to 0.7.1 instructions and just replaced the binary. Replacing the web folder with the updated version has fixed the issue.
