### ISSUE TITLE
Use the "standard" rss path

### ISSUE THREAD

**Issue by BKLronin** [superseriousbusiness/gotosocial#1578]
### Is your feature request related to a problem ?

It seems that gts uses a different rss feed path than most other activitypubs. In this case tootfinder can't search the requested site.

This might be fixed from the other side but the question could be if that path is used by other services that expect a certain path as well. 

https://tootfinder.ch/wiki/index.php?name=issue:go-social-feeds

### Describe the solution you'd like.

Custom rss path or adheringnto the standard if any

(More of a note this happens)

### Describe alternatives you've considered.

I communicated this issue to the tootfinder.ch author at first.

**Comment by daenney** [comment]
There isn't really a standard for this. It seems a bunch of implementations happened to converge on something but not everyone's copying that.

It would be really helpful to know as part of the bug report what standard path you're referring to. Based on looking at Mastodon it seems you're expecting `/username/user.rss` to exist?

However, there is a standard for discovering the RSS feed. That I think would be more helpful for tootfinder to implement, even if just for a fallback. RSS or Atom feed auto-discovery works by looking for the following `link` element in the HTML head of a page:

```
<link rel="alternate" type="application/rss+xml" 
  title="RSS Feed for petefreitag.com" 
  href="/rss/" />
```

Where it would be `applocation/atom+xml` for Atom. The `href` attributes tells you what to fetch. This would work for any and all RSS feeds and does not rely on implementations aligning on a single path.

**Comment by BKLronin** [comment]
Thank you very much!

It seems its expecting a path like so `https://social.raise-uav.com/@raise_project.rss` 

I´ll talk to the toofinder dev about this implementation, I just on wondered on what side the problem might be and this search function is pretty nice I must admit. Especially in alpha stage of GTS :)

**Comment by tsmethurst** [comment]
I'll close this then, since it's not something we're likely to change on our side, and we already support the autodiscovery thingy for profiles that have rss enabled :)
