### ISSUE TITLE
[bug] DereferenceStatusable: type name Question not supported as Statusable

### ISSUE THREAD

**Issue by Jofkos** [superseriousbusiness/gotosocial#1579]
### Describe the bug with a clear and concise description of what the bug is.

Remote toot doesn't load and can't be searched for. I do not know why this toot is making problems, specifically, yet it might be due to it being a poll (pools have worked before, however).

[The toot in question.](https://social.treehouse.systems/@alyssa/109934257984594393)

The log prints the following error:
```
timestamp="26/02/2023 21:09:12.162" func=concurrency.(*WorkerPool).Queue.func1 level=ERROR type=worker.Worker[messages.FromFederator] error="populateStatusFields: error populating status repliedTo: populateStatusRepliedTo: couldn't get reply to status with uri https://social.treehouse.systems/users/alyssa/statuses/109934257984594393: wrong received type: GetRemoteStatus: error dereferencing statusable: wrong received type: DereferenceStatusable: type name Question not supported as Statusable" msg="message processing error"
```

### What's your GoToSocial Version?

v0.7.0 git-b599309

### GoToSocial Arch

amd64, binary installation

### What happened?

A toot from someone I am following did not show up in my feed, so I tried manually loading it by searching for it.

### What you expected to happen?

The toot to show up, as I am following that person. That not working, the toot loading after I sent an explicit search for it.

### How to reproduce it?

Search for https://social.treehouse.systems/@alyssa/109934257984594393.

**Comment by tsmethurst** [comment]
We didn't implement polls yet, so that's why! It's planned for some time this year :)

**Comment by tsmethurst** [comment]
Yeah agreed, it's a bit silly! But we'll be implementing it soon enough, so there might not be much point making a workaround yet.

**Comment by tsmethurst** [comment]
closed by https://github.com/superseriousbusiness/gotosocial/pull/2330
