### ISSUE TITLE
[bug] internal server error on search with partial input instead of empty result

### ISSUE THREAD

**Issue by mzeiher** [superseriousbusiness/gotosocial#1585]
### Describe the bug with a clear and concise description of what the bug is.

I use metatext to access my gotosocial instance and if I search for a user in metatext it triggers the search while typing, this leads to failing webfinger requests because if I search for exaple for a user the user or hostpath is not yet complete, leading the webfinger to crash because there is no valid host in the search request

example log output with incomplete search and incomplete hostpath:
```
timestamp="03/03/2023 18:29:37.789" func=middleware.Logger.func1.1 level=ERROR latency=125.995105ms clientIP=172.21.0.1 userAgent="Metatext/2 CFNetwork/1404.0.5 Darwin/22.3.0" method=GET statusCode=500 path=/api/v2/search error="Error #01: error looking up account: enrichAccount: error webfingering account: fingerRemoteAccount: error fingering @mathis@social.bi: Get \"https://social.bi/.well-known/webfinger?resource=acct:mathis@social.bi\": dial tcp: lookup nondeter on 127.0.0.11:53: no such host (fast fail)\n" requestID=zycbsa4604001sspsy20 msg="Internal Server Error: wrote 688B"
timestamp="03/03/2023 18:29:38.236" func=middleware.Logger.func1.1 level=ERROR latency=143.548724ms clientIP=172.21.0.1 userAgent="Metatext/2 CFNetwork/1404.0.5 Darwin/22.3.0" method=GET statusCode=500 path=/api/v2/search error="Error #01: error looking up account: enrichAccount: error webfingering account: fingerRemoteAccount: error fingering @mathis@social.bitsc: Get \"https://social.bi/.well-known/webfinger?resource=acct:mathis@social.bitsc\": dial tcp: lookup nondeter on 127.0.0.11:53: no such host (fast fail)\n" requestID=dqbbsa46040013z89rzg msg="Internal Server Error: wrote 688B"
```

I don't know if it is more a client problem or a problem with the search endpoint :)  but maybe other clients also send partial inputs to the search endpoint.

### What's your GoToSocial Version?

v0.7.1

### GoToSocial Arch

amd64 Docker

### What happened?

While typing in the search field of the metatext client the /api/v2/search API is triggered with the partial input leading the search API to return a 500

### What you expected to happen?

I exprected that the API either returns an empty list or maybe a 400 Bad Request error

### How to reproduce it?

just trigger the /api/v2/search endpoint with non-existing users/domains

### Anything else we need to know?

your project is awesome :)

**Comment by tsmethurst** [comment]
Oof... this feels like a case where the client probably shouldn't be doing this, tbh. But it's also a bug in GtS to return a 500 there where an empty result is the more appropriate response. Will fix the latter in GtS.

**Comment by NyaaaWhatsUpDoc** [comment]
https://github.com/superseriousbusiness/gotosocial/pull/1590 handles this

**Comment by tsmethurst** [comment]
closed by https://github.com/superseriousbusiness/gotosocial/pull/1590
