### ISSUE TITLE
[issue] Editing posts doesn't work

### ISSUE THREAD

**Issue by adegans** [superseriousbusiness/gotosocial#1591]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

Not sure if it's a bug or not. But definitely an issue for normal usage.

Trying to edit a toot or reply gives an error in Tusky (bottom of the screen).
Screenshot:  ![tusky-error-gts](https://user-images.githubusercontent.com/9438487/222995401-827695ea-ef15-4646-9c50-8f0bb8aee65a.jpg)

Not sure what to check for logs or anything. I can't find a log at all for GTS.
But if you need something let me know where to find it.

### What's your GoToSocial Version?

0.7.1

### Browser version

Tusky Android

### What happened?

Editing a reply or toot doesn't work.

### What you expected to happen?

To view an edit screen and being able to edit stuff.

### How to reproduce it?

Reply to someone, or post a new toot.
Then edit it from the ... menu on the item you wanna edit.

### Anything else we need to know?

VPS/Centos/cPanel/Apache (vhost + mod_proxy), new setup (installed 2 days ago).

**Comment by tsmethurst** [comment]
Heya! It's normal that this doesn't work, we didn't implement post editing yet :D

**Comment by adegans** [comment]
Aww 🙃
When will it be added?

**Comment by tsmethurst** [comment]
>  When will it be added?

It's not currently planned so not sure. It's kinda a bonus feature at this point. Something for beta perhaps, so end of this year, start of next?

**Comment by adegans** [comment]
With how bad auto correct spellcheck is these days it’s kind of essential though.
Also when auto posting and the format is weird or a tag  needs removing.

there are a few use cases where having an edit option are super useful.

Given that there is a new post option already it should be super easy to add as the UI and ‘post saving’ stuff is already there.

**Comment by tsmethurst** [comment]
@adegans Please read this post on the state of the software: https://gts.superseriousbusiness.org/@gotosocial/statuses/01GJRET55PKNRHZCRC948F13R1 If you want something that works immediately out of the box, Mastodon is right there :P

**Comment by NyaaaWhatsUpDoc** [comment]
> Given that there is a new post option already it should be super easy to add as the UI and ‘post saving’ stuff is already there.

@adegans and you're posting this as a seasoned gotosocial and more generally, ActivityPub, developer are you?

**Comment by adegans** [comment]
> > Given that there is a new post option already it should be super easy to add as the UI and ‘post saving’ stuff is already there.
> 
> @adegans and you're saying this as a seasoned gotosocial and more generally, ActivityPub, developer are you?

*sigh* no, but I know logic and code… just not go. Reusing an existing ui element and pointing it to a different api call thing isn’t hard nor should asking about it get these kinds of ’I don’t wanna’  replies 🤨

**Comment by tsmethurst** [comment]
> Reusing an existing ui element and pointing it to a different api call thing isn’t hard

Correct (well, depending on what you're doing exactly), but this isn't that. Implementing edit support requires backend changes, changes to federation logic, documentation, etc. The API endpoint for that doesn't exist yet in GtS. It's not a simple task. And we have a lot of other important things to do first.

> nor should asking about it get these kinds of ’I don’t wanna’ replies

You started by asking a perfectly reasonable question + follow up question and then you started behaving entitled. You're gonna get some snark for that :shrug:

**Comment by NyaaaWhatsUpDoc** [comment]
> sigh no, but I know logic and code… just not go. Reusing an existing ui element and pointing it to a different api call thing isn’t hard nor should asking about it get these kinds of ’I don’t wanna’ replies raised_eyebrow

as @tsmethurst says, the backend changes for updating statuses are nowhere near as simple as a new route and an update sql statement. we do want to implement it _in time_, but we have a lot to get through and coming across as entitled doesn't really help the situation.

**Comment by adegans** [comment]
Trying to make an argument for what I think is an important feature is not ‘being entitled’ but whatever.
