### ISSUE TITLE
[issue] Mastodon app (official) doesn't authenticate/fails

### ISSUE THREAD

**Issue by adegans** [superseriousbusiness/gotosocial#1592]
### Describe the bug with a clear and concise description of what the bug is.

Not sure if it's a bug proper, I read something about Oauth not working properly - Possibly related.

On my GTS 0.7.1 I can't log in with Mastodon. When I enter the instance address it flashes an error about failing to authenticate. then shows a "404" bubble for a few seconds (see screenshots, the auth error goes to fast to capture).

![mastodon-instance-setup](https://user-images.githubusercontent.com/9438487/222996333-64b1df77-4159-4561-b31d-52b59c7feaed.jpg)

![mastodon-404](https://user-images.githubusercontent.com/9438487/222996330-8190274d-4a03-4cc2-be4d-a8b50da06add.jpg)

When trying the call in something like Curl it shows a GTS generated 404 page about only serving feeds via web.
Not sure what that means as I'm trying to authenticate an app. Tusky Android works fine for the same login procedure.

I tried the account domain, the host domain and with or without https. All fail.
On Tusky with or without https makes no difference. Using the account domain fails, but the actual domain works fine (that's how I logged in now) - I prefer the Mastodon app though.

### What's your GoToSocial Version?

0.7.1

### GoToSocial Arch

amd64

### What happened?

Can't login to Mastodon client on Android (presumably other platforms)

### What you expected to happen?

A login screen to pop up.

### How to reproduce it?

Try logging in on the official mastodon app.

### Anything else we need to know?

VPS/Centos/cPanel/Apache (vhost + mod_proxy), new install.

**Comment by tsmethurst** [comment]
Hmmm yeah I can replicate this when trying to log in to your server (which wouldn't work anyway of course, but I was just seeing if I could get a login screen). I can log in on goblin.technology which is running the latest snapshot on main, behind nginx. Also works on gts.superseriousbusiness.org, which is running behind traefik. Perhaps it's something to do with your reverse proxy setup? :thinking:

**Comment by daenney** [comment]
Works fine for me too with 0.7.1. At least, I can start the login flow. But after it's gone through all of it and succeeded the app just sits there and never seems to really log-in as such.

My last log line seems to be
```
Mar 06 18:28:05 eu1 gotosocial[3636805]: timestamp="06/03/2023 18:28:05.358" func=middleware.Logger.func1.1 level=INFO latency="8.519327ms" clientIP=<REDACTED> userAgent="Mastodon/286 CFNetwork/1404.0.5 Darwin/22.3.0" method=GET statusCode=401 path=/api/v1/accounts/verify_credentials requestID=fcb71ae9887b7aaa125a3801fe65d2ff msg="Unauthorized: wrote 662B"
```

`path=/api/v1/accounts/verify_credentials`

Seems something's going wrong there that causes the app to never complete. But actually logging in works.

**Comment by adegans** [comment]
Hmm, then what could be the problem? Some redirect issue? Or a broken api endpoint or something?

**Comment by tsmethurst** [comment]
> Hmm, then what could be the problem?

I'm not sure! How did you set up your apache? Did you follow the docs we have here (https://docs.gotosocial.org/en/latest/installation_guide/apache-httpd/) or did you go hardcore and set it up some other way?

**Comment by daenney** [comment]
> Hmmm yeah I can replicate this when trying to log in to your server (which wouldn't work anyway of course, but I was just seeing if I could get a login screen). I can log in on goblin.technology which is running the latest snapshot on main, behind nginx. Also works on gts.superseriousbusiness.org, which is running behind traefik. Perhaps it's something to do with your reverse proxy setup? thinking Or it could be a bug that we fixed along the way.

@tsmethurst Are you saying that you managed to properly log in and use the Masto app with your two instances? Because I'm on 0.7.1 and though I get through the login flow I never get to a point where the app itself logs in and I can use it. If you're on main and it works that gives me something to bisect at least which would be very interesting.

**Comment by adegans** [comment]
I don't even get the login prompt on 0.7.1 with the mastodon app. As shown in the screenshots.
So perhaps it works if you were already logged in (on a older version).

If it's something in my server, a redirect or whatever going wrong, then I need to know what to check and where(ish).
I don't know enough about activitypub to investigate or fix this and information/documentation for it is pretty much non-existent.

**Comment by daenney** [comment]
> I don't even get the login prompt on 0.7.1 with the mastodon app. As shown in the screenshots.
> So perhaps it works if you were already logged in (on a older version).

Nope, that's not it. I didn't nor ever had the app installed before and I can trigger the login flow at least.

> If it's something in my server, a redirect or whatever going wrong, then I need to know what to check and where(ish).
I don't know enough about activitypub to investigate or fix this and information/documentation for it is pretty much non-existent.

> > Hmm, then what could be the problem?
> 
> I'm not sure! How did you set up your apache? Did you follow the docs we have here (https://docs.gotosocial.org/en/latest/installation_guide/apache-httpd/) or did you go hardcore and set it up some other way?

We'd need you to answer this question :wink:. Without knowing anything about your configuration we can't do or say much. The app screenshots don't tell us what's going on. Also, GtS and logs from your reverse proxy from the time when you try to trigger the login would be very helpful.

**Comment by adegans** [comment]
> > Hmm, then what could be the problem?
> 
> I'm not sure! How did you set up your apache? Did you follow the docs we have here (https://docs.gotosocial.org/en/latest/installation_guide/apache-httpd/) or did you go hardcore and set it up some other way?

I did follow that page for the most part, but had to piece together centos/cpanel stuff myself - Which I found difficult as I'm not a server guy. I did piece together this doc (.md) with the exact steps (commands) and config stuff I did - (See link).
https://cloud.ajdg.net/s/iZCokdAiD9fNiHS

**Comment by adegans** [comment]
I also tested the oauth header thing mentioned in one of your pages. Unset the header as suggested, but testing with curl the header isn't there. So it made no difference.

**Comment by daenney** [comment]
I traced the app side down all the way to https://github.com/mastodon/mastodon-ios/issues/967, at least for iOS. Basically if account-domain and web-domain differ you'll fail to login if you don't provide it the full instance domain on an otherwise correctly configured GtS instance.

**Comment by tsmethurst** [comment]
Closing this now, since we identified the issue -- workaround for now is to just login using the full host, not just the account domain.
