### ISSUE TITLE
[bug] Timeline just ends, prepareBehind: error preparing item with id 

### ISSUE THREAD

**Issue by Jofkos** [superseriousbusiness/gotosocial#1600]
### Describe the bug with a clear and concise description of what the bug is.

Load my home timeline on a non-caching front-end (like, e.g., elk or pinafore). The timeline just ends, sometimes, and GoToSocial then prints something like
```
timestamp="07/03/2023 11:51:40.134" func=timeline.(*manager).GetTimeline level=ERROR timelineAccountID=<accountId> msg="error getting statuses: prepareBehind: error preparing item with id <itemId>: statusPrepareFunction: error getting status with id <itemId>"
```

Given that it happens on at least two different clients, I think this might be an issue with GoToSocial. I do not know when it happens or how to trigger it, unfortunately.

### What's your GoToSocial Version?

 GoToSocial 0.7.0 git-b599309

### What happened?

The timeline ends, GoToSocial prints an error.

### What you expected to happen?

The timeline to go on.

### How to reproduce it?

Unknown

**Comment by tsmethurst** [comment]
Thanks, indeed this looks like a bug :)

**Comment by Jofkos** [comment]
Is there anything I can do to better document this next time it occurs?

**Comment by tsmethurst** [comment]
Nah it's cool, I think I already might know what the issue is, the info you provided is very helpful :)
