### ISSUE TITLE
is there a reason to have license and copyright in every. single. file. if there is /LICENSE and /README already?

### ISSUE THREAD

**Issue by dym-sh** [superseriousbusiness/gotosocial#1603]
subj.

**Comment by tsmethurst** [comment]
Yes.

**Comment by tsmethurst** [comment]
Yeah sure, check here: https://github.com/superseriousbusiness/gotosocial/blob/main/LICENSE#L621-L648 It's just standard stuff.

**Comment by dym-sh** [comment]
seems like an obsolete «we always done it this way» _suggestion_ from the time before github

neither mastodon nor any other AGPL software thought it was necessary to inconvenience potential contributors by forcing them to first and foremost, scroll past the redundant lines in every single file

its not like this will stop anyone who is willing to breach the license anyways
