### ISSUE TITLE
[bug] Cannot steal emojis of FoundKey instance?

### ISSUE THREAD

**Issue by PrivacyDragon** [superseriousbusiness/gotosocial#1606]
### Describe the bug with a clear and concise description of what the bug is.

Because some emoji packs have more than hundred emojis, it saves a lot of time to import them by having someone send you all of the emojis in a toot.
I tried this with sending dragon emojis from my mastodon account on an instance that already had some of them, then manually adding the missing ones.

I also want the dragon emojis by volpeon, so I sent a DM asking for a reply with all of those emojis.
It appears that I cannot import them, because GTS gives an error...
So either it cannot import from the instance Volpeon uses, an FoundKey instance, or there are too much emojis for the server to handle.
It is incredibly ~infuriating~ annoying either way.

### What's your GoToSocial Version?

0.7.1

### GoToSocial Arch

amd64 Yunohost

**Comment by tsmethurst** [comment]
Can you paste any error messages or logs that you can find?

**Comment by PrivacyDragon** [comment]
```
timestamp="10/03/2023 15:36:17.197" func=middleware.Logger.func1.1 level=INFO latency=36.976972ms clientIP=2a02:a468:550a:1:82fa:5bff:fe5e:968d userAgent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.45 Safari/537.36" method=GET statusCode=200 path=/api/v1/admin/custom_emojis requestID=11n2nk4604001p8zn0h0 msg="OK: wrote 2.35kiB"
timestamp="10/03/2023 15:36:19.939" func=transport.(*transport).do level=INFO pubKeyID=https://social.storydragon.nl/users/storydragon/main-key method=GET url=https://is-a.wyvern.rip/notes/9c53zcg69g requestID=tst2nk46040008ckf2g0 msg="performing request"
timestamp="10/03/2023 15:36:20.230" func=middleware.Logger.func1.1 level=ERROR latency=304.314164ms clientIP=2a02:a468:550a:1:82fa:5bff:fe5e:968d userAgent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.45 Safari/537.36" method=GET statusCode=500 path=/api/v2/search error="Error #01: error looking up status: transport error: GetRemoteStatus: error dereferencing statusable: DereferenceStatusable: error deferencing https://is-a.wyvern.rip/notes/9c53zcg69g: GET request to https://is-a.wyvern.rip/notes/9c53zcg69g failed: 404 Not Found\n" requestID=tst2nk46040008ckf2g0 msg="Internal Server Error: wrote 54B"
```

**Comment by tsmethurst** [comment]
Judging from the logs, either that status doesn't exist on the remote instance, or the remote instance is giving you a 404 because the admin user isn't permitted to see it. It was a dm you said, right? Was it a dm to the user `https://social.storydragon.nl/users/storydragon` or to another user?

**Comment by PrivacyDragon** [comment]
Yes, it was a DM to the user `https://social.storydragon.nl/users/storydragon`

**Comment by tsmethurst** [comment]
I'm not really sure what's going on then, but I don't think this is a bug in GtS, the remote server is just returning a 404 to the request being sent out by the GoToSocial server:

```
GET request to https://is-a.wyvern.rip/notes/9c53zcg69g failed: 404 Not Found
```

Could you try verifying that that's the correct link to the direct message, and/or try getting the remote user to send the message again, and try again with the new message link?

**Comment by PrivacyDragon** [comment]
Okay.
The emoji's have been sent again in a public toot, and that did work.
So I guess that might mean that it would not always work with DMs.
(Though a DM from a Hometown instance with some emojis did work. Maybe depends on the protocol or something then?)
