### ISSUE TITLE
[feature] Supertokens for auth

### ISSUE THREAD

**Issue by a0v0** [superseriousbusiness/gotosocial#1610]
### Is your feature request related to a problem ?

Currently gotosocial supports login by email and password. 

Login with email and mobile via code is currently not possible. Supertokens provide these out of the box.

### Describe the solution you'd like.

Start using supertokens for auth.

### Describe alternatives you've considered.

Supertokens 

### Additional context.

https://supertokens.com/

**Comment by tsmethurst** [comment]
We already support logging in to GtS via external OIDC providers, so if instance admins want functionality for other login types, they can configure it in their OIDC provider. There's no good reason to put something like this in base GtS.
