### ISSUE TITLE
[bug] Spelling

### ISSUE THREAD

**Issue by jsoref** [superseriousbusiness/gotosocial#1613]
### Describe the bug with a clear and concise description of what the bug is.

Spelling errors result in a poor user experience and a harder contribution experience

### What's your GoToSocial Version?

HEAD

### What happened?

https://github.com/jsoref/gotosocial/actions/runs/4398698632#summary-11941497991

### What you expected to happen?

https://github.com/jsoref/gotosocial/actions/runs/4398698723#summary-11941498076

### How to reproduce it?

Add check-spelling workflow: https://github.com/jsoref/gotosocial/commit/5d76d6464b392e71bd145d8beb240cd7c6b0151b

### Anything else we need to know?

I'll file a PR to close this...

**Comment by tsmethurst** [comment]
context: https://github.com/superseriousbusiness/gotosocial/pull/1614#issuecomment-1465289983
