### ISSUE TITLE
Failed Ping/See profile on friends instances

### ISSUE THREAD

**Issue by SuperErnD** [superseriousbusiness/gotosocial#1625]
### Describe the bug with a clear and concise description of what the bug is.

I installed GoToSocial and i give username and host to friends, they cant ping/see profile on their instances

### What's your GoToSocial Version?

Latest

### GoToSocial Arch

amd64 Binary

### What happened?

Just failed, error has occurred 

### What you expected to happen?

Normal ping and see my profile on their instances

### How to reproduce it?

Just install GoToSocial and try ping from pleroma (akkora), misskey

### Anything else we need to know?

Log:
2023-03-15T15:03:43.188 app[f7609367] waw [info] timestamp="15/03/2023 15:03:43.188" func=router.loggingMiddleware.func1 level=INFO latency=263.487353ms clientIP=172.16.70.170 userAgent="Misskey/13.9.2 (https://fedi.debilosempire.org)" method=GET statusCode=401 path=/users/diman msg="Unauthorized: wrote 48B"

**Comment by tsmethurst** [comment]
This is likely a configuration issue with your reverse proxy, causing signature authentication to fail. Make sure you're setting your `host` header properly, check: https://docs.gotosocial.org/en/latest/installation_guide/nginx/#set-up-nginx

**Comment by SuperErnD** [comment]
i cant use that. i use fly io

**Comment by SuperErnD** [comment]
I waited and it work! What?
