### ISSUE TITLE
[bug] Account domain is not checked again after resolving the ActivityPub actor

### ISSUE THREAD

**Issue by handlerug** [superseriousbusiness/gotosocial#1627]
### Describe the bug with a clear and concise description of what the bug is.

When resolving an account from an URL, GoToSocial blindly trusts the URL domain as being canonical for the account. For example, Alice sets up a redirect from `https://fanon.example/@john@truthy.example` to `https://truthy.example/@john`. GoToSocial will GET `https://fanon.example/@john@truthy.example`, then after a redirect GET `https://truthy.example/@john`, and get the correct account info. Afterwards, it'll send a WebFinger request to `https://fanon.example/.well-known/webfinger?resource=acct:john@fanon.example` (the domain is not the right one, but this is not critical) and ignore the 404 error (this is critical), recording `fanon.example` as `@john`'s domain due to a fallthrough in the code.

### What's your GoToSocial Version?

v0.7.1

### GoToSocial Arch

x86_64 Alpine Linux package

### What happened?

The resulting account's domain is `vulpine.club`.

### What you expected to happen?

The resulting account's domain should have been `pixel.kitchen`.

### How to reproduce it?

1. Try searching this URL using a Mastodon client: `https://vulpine.club/@jenn@pixel.kitchen`

### Anything else we need to know?

https://github.com/superseriousbusiness/gotosocial/blob/196cd88b1c7c44a337ca12f6a804f1bb7fa83c4a/internal/federation/dereferencing/account.go#L222-L236

**Comment by tsmethurst** [comment]
Thanks!

**Comment by NyaaaWhatsUpDoc** [comment]
ooh good sleuthing!
