### ISSUE TITLE
[bug] home timeline does not load on Tusker 2023.4

### ISSUE THREAD

**Issue by fuzzysh** [superseriousbusiness/gotosocial#1629]
### Describe the bug with a clear and concise description of what the bug is.

when switching to home timeline i get "Error Loading\n Invalid Model"

### What's your GoToSocial Version?

v0.7.1

### GoToSocial Arch

amd64 binary

### Anything else we need to know?

ios 16.1.2 iphone XR

**Comment by tsmethurst** [comment]
`Invalid Model` suggests that Tusker (hadn't heard of that one before, is it new?) doesn't like one of the models we're serving via the API, but without more information than that we have no way of knowing which one, and why. I would suggest raising this issue on the Tusker repository as well and seeing if they can figure it out from their end too.

**Comment by japareaggae** [comment]
Tusker is this one for iOS: https://apps.apple.com/us/app/tusker/id1498334597

They already had a "Support GoToSocial" issue on their bug tracker, I've added a comment mentioning this error: https://git.shadowfacts.net/shadowfacts/Tusker/issues/129

**Comment by shadowfacts** [comment]
I finally got around to looking at this—the underlying error was  because GtS is returning empty strings for the `url` field in statuses. I've handled this case for the next Tusker update, though it seems a little odd that a status could not have a URL?

**Comment by tsmethurst** [comment]
Huh, that is indeed quite odd... will look into this

**Comment by tsmethurst** [comment]
^^ updated api serialization logic to *always* include a url by falling back to ap uri if necessary
