### ISSUE TITLE
[feature] OTP based login via email

### ISSUE THREAD

**Issue by a0v0** [superseriousbusiness/gotosocial#1631]
### Is your feature request related to a problem ?

It's hard to remember passwords. OTP is common nowadays

### Describe the solution you'd like.

Login via otp instead of password

### Describe alternatives you've considered.

NONE

**Comment by tsmethurst** [comment]
OTP doesn't really fit with our current OAuth flow, and I'm not sure how much utility it really offers anyway. Don't you still need to remember your email password, if you use otp? ;)
