### ISSUE TITLE
Spotty StatusVisibility code requires better tests + fixes

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#164]
The current status visibility code is untested and spotty -- sometimes statuses aren't visible that actually should be visible (thankfully, not the other way around).

We need rigorous tests for the visibility parts of the code, and to patch any bugs we find while testing.

Relevant files:

https://github.com/superseriousbusiness/gotosocial/blob/main/internal/visibility/statusvisible.go
https://github.com/superseriousbusiness/gotosocial/blob/main/internal/visibility/statushometimelineable.go
https://github.com/superseriousbusiness/gotosocial/blob/main/internal/visibility/relevantaccounts.go

**Comment by NyaaaWhatsUpDoc** [comment]
Fix PR in here: #199
