### ISSUE TITLE
[bug] Images not loaded

### ISSUE THREAD

**Issue by Jofkos** [superseriousbusiness/gotosocial#1644]
### Describe the bug with a clear and concise description of what the bug is.

For some toots/posts the image attachments do not show up. 

### What's your GoToSocial Version?

GoToSocial 0.7.1 git-adb5966

### GoToSocial Arch

amd64

### What happened?

A post in my timeline that does have attachments only shows up without those attachments, irrespective of client used.

### What you expected to happen?

The post to have the attachments.

### How to reproduce it?

It is unclear whether it can be reproduced, but one post in question is https://social.noyu.me/@hikari/statuses/01GW7FY26B98YVASNEPW894YHK (running GoToSocial 0.5.2 git-c31f219).

**Comment by tsmethurst** [comment]
Iirc there was a bug in previous versions of GtS where statuses were not being cached properly including their status attachments. I believe 0.5.2 still had that bug

**Comment by tsmethurst** [comment]
I think the solution here is for that user on 0.5.2 to update, then it shouldn't happen again. There will just be exciting new 0.7.1 bugs instead
