### ISSUE TITLE
[feature] Mute User Boosts

### ISSUE THREAD

**Issue by ultramookie** [superseriousbusiness/gotosocial#1671]
### Is your feature request related to a problem ?

There is a nice feature in Mastodon where one can mute a user's boosts. There are some users that have interesting posts that I'd like to follow, but they also boost a lot. This feature is nice since it allows users to only see original posts and not be flooded with boosts.

### Describe the solution you'd like.

A change on the backend to only show posts from a user. Clients like Elk and Semaphore already have the feature on the front-end.

### Describe alternatives you've considered.

NONE

**Comment by tsmethurst** [comment]
Good idea :)
