### ISSUE TITLE
[bug] `failed to set CPU limits from cgroup` on Synology NAS

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#1677]
On some exotic setups that don't have cgroups, the following error can crop up on startup, preventing GtS from running:

`executing command: failed to set CPU limits from cgroup: open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory`

**Comment by yeahwong** [comment]
I've encountered the same issue too.
