### ISSUE TITLE
[bug] Mastodon iOS can’t load threads

### ISSUE THREAD

**Issue by belkadan** [superseriousbusiness/gotosocial#1681]
### Describe the bug with a clear and concise description of what the bug is.

Using the official Mastodon iOS app, whenever I view a post, I don’t see any replies (or the post it’s replying to, if it’s itself a reply). Activity spinners run at the top and bottom, so I think the app is *trying* to load the thread, but failing.

I run a single-user instance, so usually threads cross server boundaries, but even when I reply to myself they’re not showing up as I’d expect.

Another app, Tootoise, does show threads correctly, but has other issues [that maybe I’ll get around to filing at some point]. So the metadata is there, but it’s not quite Mastodon-client-app-compatible.

I doubt the official Mastodon app takes bug reports about using their client with non-Mastodon servers, but I can file one there too if you like.

### What's your GoToSocial Version?

v0.8.0

### GoToSocial Arch

x64 Docker

**Comment by tsmethurst** [comment]
Hey @belkadan , could you confirm if this is still an issue on 0.9.0?

**Comment by belkadan** [comment]
I'm afraid it is. If I tap on a post *on my own profile* that has replies, I see them in Tootoise and Mona, but not in Mastodon.

**Comment by martinr92** [comment]
The issue still exists on version 0.11.1.

Here some logs from the server:
```
timestamp="02/09/2023 22:00:48.237" func=server.glob..func1.Logger.func13.1 level=INFO latency="4.419779ms" userAgent="Mastodon/344 CFNetwork/1410.0.3 Darwin/22.6.0" method=GET statusCode=200 path=/api/v1/timelines/home clientIP=10.2.2.12 requestID=74588f9e5d047bbccb4f110a6565ffa9 msg="OK: wrote 13.3kiB"

timestamp="02/09/2023 22:00:48.360" func=server.glob..func1.Logger.func13.1 level=INFO latency="26.859µs" userAgent="Mastodon/344 CFNetwork/1410.0.3 Darwin/22.6.0" method=GET statusCode=404 path=/api/v1/mutes clientIP=10.2.2.12 requestID=f489bac4d6c87ac6930b86e8bfef861a msg="Not Found: wrote 21B"

timestamp="02/09/2023 22:00:49.316" func=server.glob..func1.Logger.func13.1 level=INFO latency="726.378689ms" userAgent="Mastodon/344 CFNetwork/1410.0.3 Darwin/22.6.0" method=GET statusCode=200 path=/api/v1/statuses/01H9BNZAMG65ABFGWZ7262EA8A/context clientIP=10.2.2.12 requestID=0d9f4c6711a71268637f82263826f691 msg="OK: wrote 6.13kiB"

timestamp="02/09/2023 22:00:49.410" func=server.glob..func1.Logger.func13.1 level=INFO latency="28.456µs" userAgent="Mastodon/344 CFNetwork/1410.0.3 Darwin/22.6.0" method=GET statusCode=404 path=/api/v1/statuses/01H9BNZAMG65ABFGWZ7262EA8A/history clientIP=10.2.2.12 requestID=be3755adff75766b278e46f9d1548904 msg="Not Found: wrote 21B"
```

Maybe the last entry is the problem?

**Comment by tsmethurst** [comment]
Ah thanks, yeah perhaps we need to stub that 'history' endpoint then!

**Comment by NyaaaWhatsUpDoc** [comment]
Relevant API docs for this history endpoint: https://docs.joinmastodon.org/methods/statuses/#history

Will be required as part of https://github.com/superseriousbusiness/gotosocial/issues/1990
