### ISSUE TITLE
Numerical instead of Alphabetical IDs

### ISSUE THREAD

**Issue by Scribilicious** [superseriousbusiness/gotosocial#1696]
### Is your feature request related to a problem ?

From the Ivory App Support:

Unfortunately a lot of these alternate activity pub services will not work with our app for awhile. Our app is built based on Twitter which uses numeric ID’s for posts. Mastodon happens to use numeric ID’s as well which made the transition much easier for us. However a lot of other services like GoToSocial use alphanumeric post ID’s which our app can’t currently handle. It will require us to spend time rewriting a lot of the core code in how our app works. It’s something we want to do at some point, but we  just have too much on our plate at this time to do that. So it’s on our list, but probably won’t get to it for awhile. 

### Describe the solution you'd like.

Numerical instead of Alphabetical IDs.

### Describe alternatives you've considered.

None…

**Comment by NyaaaWhatsUpDoc** [comment]
We don't plan on changing the data format of our IDs, this would be a huge overhaul and require massive database migrations for many users.
