### ISSUE TITLE
[bug] Spaces in CW text can get mangled to %20s

### ISSUE THREAD

**Issue by trysdyn** [superseriousbusiness/gotosocial#1698]
### Describe the bug with a clear and concise description of what the bug is.

Related to #1661 but I believe it's a different bug.

A remote mastodon user can create a thread with CWs that somehow lands on GtS such that escaping code mangles the CW's spaces to `%20`s.

The mangled post was a reply to a previous post that wasn't mangled, so something in reply logic might be the culprit?

### What's your GoToSocial Version?

v0.8.0 tag

### GoToSocial Arch

x86_64 source build

### What happened?

A remote mastodon user posted a [CWed post with a hashtag in the CW](https://social.treehouse.systems/@megmac/110192951356629023). That's fine. The user then [replied to their own post](https://social.treehouse.systems/@megmac/110194468280648558) to add a threaded thought. That second post had the spaces in the CW mangled to `%20`s GtS side. These are public posts but here's what the CW fields look like in my DB:

```
gotosocial=# select content_warning from statuses where id = '01GXYMHY5RAJSEV7WZK7PTNQER' or id = '01GXXYFHP0F4K7QKR50FECNXW5';
         content_warning
---------------------------------
 #Picard s03e09 spoilers
 re: #Picard%20s03e09%20spoilers
(2 rows)
```

I've pulled in this thread from a 3.5 Mastodon instance and it behaved correctly so I believe this is GtS-specific.

### What you expected to happen?

Spaces not getting chomped to human-readable `%20`s

### How to reproduce it?

Dereferencing the linked thread by its root should do it, in theory. So searching for the root post's URL.

### Anything else we need to know?

#1661 mentions Pleroma and its different post formatting; this is Mastodon so I believe a different bug with the same root cause and impact is at play.

**Comment by tsmethurst** [comment]
Ahh thanks, indeed it's likely the same root cause.

**Comment by trysdyn** [comment]
FYI: This can happen in profile bios too. Unfortunately the sample case I have changed their bio today so I can't provide you with a replication means.

Looks to be the same parsing-as-IRI issue though; a colon sets it off.

**Comment by tsmethurst** [comment]
Ack, I saw that too. Will fix soon :)
