### ISSUE TITLE
[bug] Typo in config.yaml

### ISSUE THREAD

**Issue by sandboxgangster** [superseriousbusiness/gotosocial#1704]
### Describe the bug with a clear and concise description of what the bug is.

Hello in the config.yaml there are two minor typos, in line 319 and 321

>    webfinger-max-size": 250
>   webfinger-ttl: "24h"
>   webfinger-sweep-freq": "1m"

lg

### What's your GoToSocial Version?

0.8.0

**Comment by igalic** [comment]
do you think you could provide a patch?
