### ISSUE TITLE
[bug] search: recovered panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#1706]
### Describe the bug with a clear and concise description of what the bug is.

I tried searching for https://social.tchncs.de/@unicorn/104410810083017002 in Pinafore because I could not interact with a boost of that (404, which I *think* tends to happen if the original post is modified after the boost), and got:

> Error during search: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

### What's your GoToSocial Version?

0.8.0

### GoToSocial Arch

amd64 binary

### What happened?

Looking at the logs, I see:

> @40000000643e89611a14cbc4 timestamp="18/04/2023 12:13:11.437" func=middleware.Logger.func1.1 level=ERROR stacktrace="runtime.panicmem()\n\t/usr/local/go/src/runtime/panic.go:260\nruntime.sigpanic()\n\t/usr/local/go/src/runtime/signal_unix.go:837\nprocessing.(*Processor).searchStatusByURI()\n\t/drone/src/internal/processing/search.go:234\nprocessing.(*Processor).SearchGet()\n\t/drone/src/internal/processing/search.go:133\nsearch.(*Module).SearchGETHandler()\n\t/drone/src/internal/api/client/search/searchget.go:163\ngin.(*Context).Next()\n\t/drone/src/vendor/github.com/gin-gonic/gin/context.go:174\ngzip.(*gzipHandler).Handle()\n\t/drone/src/vendor/github.com/gin-contrib/gzip/handler.go:60\ngin.(*Context).Next()\n\t/drone/src/vendor/github.com/gin-gonic/gin/context.go:174\nmiddleware.Throttle.func2()\n\t/drone/src/internal/middleware/throttling.go:124\n" requestID=r9y4h54704000d76g5kg msg="recovered panic: runtime error: invalid memory address or nil pointer dereference"

### What you expected to happen?

Things to work ;-)

### How to reproduce it?

Try searching for the above-mentioned toot, maybe it happens to you as well?

**Comment by tsmethurst** [comment]
Thanks! Will check this out when we're back from holidays :)

**Comment by tsmethurst** [comment]
I believe we've fixed this with the recent updates to the way we perform searches + respond to api search queries. So I'm gonna close this for now but please feel free to open it again if you see the issue again :eyes:

**Comment by mirabilos** [comment]
from a user’s PoV it would be nice to keep things open (so they can still be found more easily) until the code is actually in a published release, but okay

**Comment by tsmethurst** [comment]
Ah okay that's fair, I'll open it again until we know for sure it's fixed.

**Comment by tsmethurst** [comment]
@mirabilos are you running 0.9.0 yet? have you seen this issue again?

**Comment by mirabilos** [comment]
tobi dixit:

>@mirabilos are you running 0.9.0 yet? have you seen this issue again?

Oh, is 0.9.0 released then? Did I miss a release announcement?

**Comment by mirabilos** [comment]
I missed it apparently, I only remember the first two release candidates. Oh well, update went smooth, DB upgrade in milliseconds.

This error has evolved into the next Pokèmon:

```
@400000006477928d059bc88c timestamp="31/05/2023 18:31:31.094" func=middleware.Logger.func1.1 level=ERROR latency="828.423µs" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" method=GET statusCode=500 path=/api/v2/search error="Error #01: error looking up status: GetStatusByURI: error checking database for status https://social.tchncs.de/@unicorn/104410810083017002 by url: \"error populating status parent: no entries\",\"error populating status parent: no entries\"\n" requestID=2n818ww804000qhc9kk0 msg="Internal Server Error: wrote 54B"
```

**Comment by NyaaaWhatsUpDoc** [comment]
This should be fixed in the next hotfix @mirabilos :)

**Comment by NyaaaWhatsUpDoc** [comment]
This is an unrelated error, but is being fixed in the next hotfix. There's currently a PR open that handles it :)

**Comment by mirabilos** [comment]
These seem to both be fixed in 0.10.0-rc3 git-f431974 and can maybe be closed?

**Comment by mirabilos** [comment]
Unfortunately, we will have to reopen this: I managed to reproduce on 0.13.0-rc2 git-d0bb8f0

What I did was to get a post (via “copy link to post”) from an Akkoma instance and Search for it in Semaphore.

Now Pleroma/Akkoma unfortunately don’t copy the `/object/` form to the clipboard (which searching for works) but the `/notice/` form. And if it’s a private post (Direct visibility), I cannot get at the `/object/` form by any other means. (I should have seen the post in my notifications but didn’t, which is why I was searching. I seem to be losing some of them from that instance, but only a small amount.)

Back to the search: searching for a string in the form `https://infosec.place/notice/xxxxxcensoredxxxxx` caused:

```
timestamp="2024-01-01T00:32:39.784Z" func=server.glob..func1.Logger.func13.1 level=ERROR stacktrace="()\n\t/usr/local/go/src/runtime/panic.go:261\nruntime.sigpanic()\n\t/usr/local/go/src/runtime/signal_unix.go:861\ntypeutils.(*Converter).AccountToAPIAccountPublic()\n\t/drone/src/internal/typeutils/internaltofrontend.go:218\nsearch.(*Processor).packageAccounts()\n\t/drone/src/internal/processing/search/util.go:79\nsearch.(*Processor).packageSearchResult()\n\t/drone/src/internal/processing/search/util.go:184\nsearch.(*Processor).Get()\n\t/drone/src/internal/processing/search/get.go:238\nsearch.(*Module).SearchGETHandler()\n\t/drone/src/internal/api/client/search/searchget.go:232\n()\n\t/drone/src/vendor/github.com/gin-gonic/gin/context.go:174\ngzip.(*gzipHandler).Handle()\n\t/drone/src/vendor/github.com/gin-contrib/gzip/handler.go:60\n" requestID=cvdpzgmc0400022snjd0 msg="recovered panic: runtime error: invalid memory address or nil pointer dereference"
timestamp="2024-01-01T00:32:39.784Z" func=server.glob..func1.Logger.func13.1 level=INFO latency="2.122412ms" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0" method=GET statusCode=200 path=/api/v2/search errors="Error #01: recovered panic: runtime error: invalid memory address or nil pointer dereference\n" requestID=cvdpzgmc0400022snjd0 msg="OK: wrote 23B"
```

Do you want a separate bug for the inability to search for `/notice/` from Pleroma/Akkoma? Since their public clients don’t seem to be able to give out the `/objects/` link, this is kinda problematic. Or do you prefer to handle that with the panic?

**Comment by tsmethurst** [comment]
> Do you want a separate bug for the inability to search for /notice/ from Pleroma/Akkoma? Since their public clients don’t seem to be able to give out the /objects/ link, this is kinda problematic. Or do you prefer to handle that with the panic?

We've already got https://github.com/superseriousbusiness/gotosocial/issues/2327

**Comment by mirabilos** [comment]
Ah okay, thanks, subscribed.
