### ISSUE TITLE
ActivityPub data validity checks

### ISSUE THREAD

**Issue by NyaaaWhatsUpDoc** [superseriousbusiness/gotosocial#171]
Posting the conclusion from discussions in the GtS matrix channel yesterday regarding tolerance of invalid ActivityPub data received:

1) we need to define schematically exactly what we are / aren't willing to put in the database, so we know exactly what we'll be getting back from the database -- and don't need to check everything coming out of the database
2) from these definitions we instead place more strict checks on incoming data. we continue to be tolerant of invalid data, e.g. skipping invalid attachments, but we have a cut-off "bare minimum" definition of a status. invalid data will not be allowed in the database

It's probably worth carrying-out at least `1)` *before* starting work on #149

**Comment by NyaaaWhatsUpDoc** [comment]
@tsmethurst could you add this to the feature freeze project please :)

**Comment by tsmethurst** [comment]
What do we think about using something like this on all the structs in the `gtsmodel` package?

https://pkg.go.dev/github.com/go-playground/validator/v10

Or is that overkill given that we already have tags on the structs for bun?

**Comment by tsmethurst** [comment]
Closed by https://github.com/superseriousbusiness/gotosocial/pull/186
