### ISSUE TITLE
[feature] Embedd web templates into binary

### ISSUE THREAD

**Issue by mispp** [superseriousbusiness/gotosocial#1731]
### Is your feature request related to a problem ?

Setting up an gts instance from scratch is not possible only with binary. Also repository with web dir  is needed.

### Describe the solution you'd like.

Embed default templates into the binary using embed package

### Describe alternatives you've considered.

n/a

**Comment by tsmethurst** [comment]
We considered this, but it adds some annoyances and complications and maintenance overhead that we weren't ready to deal with yet. Also, it's not the case that you need the repository with the web dir: the release tars contain all the compiled web assets and templates, so you can just untar :)

We might look into this again in future, but it's not a priority for right now.

**Comment by mispp** [comment]
What maintenance overhead do you mean?

Not that I had too much experience with golang, but embed seemed quiet convenient.

**Comment by tsmethurst** [comment]
OK maintenance isn't quite the right word, but basically just code complication and making the packaging process more complex than it already is. This was the PR where someone proposed it and sent in code: https://github.com/superseriousbusiness/gotosocial/pull/1142

**Comment by tsmethurst** [comment]
I'm going to close this because I don't think it's something we're going to end up doing. Most folks seem to be fine with unpacking the tar.gz (or using the docker container) to keep their templates up to date.
