### ISSUE TITLE
[bug] Follow requests to mastodon show "Follow requested", although account is not locked

### ISSUE THREAD

**Issue by moan0s** [superseriousbusiness/gotosocial#1732]
### Describe the bug with a clear and concise description of what the bug is.

Follow requests to mastodon show don not follow instead show "Follow requested", although account is not locked

### What's your GoToSocial Version?

GoToSocial 0.8.1 git-4dbf9a2

### GoToSocial Arch

docker

### What happened?

I try to follow the non-locked mastodon account @moanos@chaos.social from my GtS instance. It shows me "Follow requested". The response to the follow POST request is

```json
{"id":"01GZESF6XXXXXCW2E19F2XZSCEV","following":false,"showing_reblogs":false,"notifying":false,"followed_by":false,"blocking":false,"blocked_by":false,"muting":false,"muting_notifications":false,"requested":true,"domain_blocking":false,"endorsed":false,"note":""}
```
(note the `"following": false` and the `"requested":true`).

This does not happen when I try to follow @moanos@gay-pirate-assassins.de (GtS account)

### What you expected to happen?

Following that account

### How to reproduce it?

Try to follow a Mastodon account from a GtS account

### Anything else we need to know?

Thanks for all the work <3

**Comment by moan0s** [comment]
Okay just a small update:
It is possible to follow an account on lediver.se which runs Mastodon v4.1.0 but not on chaos.social which runs v4.1.2

Feel free to test this with @moanos@chaos.social and @moanos_foss@lediver.se

**Comment by tsmethurst** [comment]
I managed to follow your chaos.social account OK from goblin.technology, so I don't think the version thing might be a red herring, not sure yet

**Comment by moan0s** [comment]
This gets more puzzeling the more I test: From two GTS instances I tested I get the requested stat back but mastodon shows me I am following

From one new GTS instance i set up I don't get the follow notification.

Maybe it has to do with a state of the mastodon server?

**Comment by moan0s** [comment]
Another possible reason: The two instances where it semi-works have hostname=account domain, the other instance does not.

**Comment by moan0s** [comment]
Well. Found the problem on the server where nothing works: Webfinegrs are not set up correctly. (see https://docs.gotosocial.org/en/latest/installation_guide/advanced/) Therefore closing this now. Sorry for the hassle

**Comment by tsmethurst** [comment]
No hassle! I'm glad it's resolved :) was the issue on your side, or the remote server?

**Comment by moan0s** [comment]
The issue was that in all my excitement of being allowed to set up a GTS server for an organization i completely forgot to redirect `/.well-known/webfinger`, `/.well-known/nodeinfo` and `/.well-known/host-meta`. So the issue was on my site!
