### ISSUE TITLE
[bug] Can't find user on domain with ü in name

### ISSUE THREAD

**Issue by moan0s** [superseriousbusiness/gotosocial#1735]
### Describe the bug with a clear and concise description of what the bug is.

I tried to search an account on bawü.social which returns no result even though the full handle is used. I suspect the ü in the domain is responsible.

### What's your GoToSocial Version?

GoToSocial 0.8.1 git-4dbf9a2

### GoToSocial Arch

docker

### What happened?

Tried to follow @stadtwerketuebingen@bawü.social  by searching for them. Returned no account

### What you expected to happen?

See the account

### How to reproduce it?

Search for @stadtwerketuebingen@bawü.social

**Comment by tsmethurst** [comment]
Ahh thanks, I think we're storing the punycode version of domains with non-ascii characters, and likely searching against that. We should convert the search domain into punycode as well. Will fix :)
