### ISSUE TITLE
[bug] webfinger endpoint should support `application/jrd+json` format

### ISSUE THREAD

**Issue by dotsam** [superseriousbusiness/gotosocial#1736]
### Describe the bug with a clear and concise description of what the bug is.

Per [RFC7033](https://www.rfc-editor.org/rfc/rfc7033#section-4.2), the `.well-known/webfinger` endpoint should accept and return the `application/jrd+json` MIME type.

Currently the server only supports `application/json`
https://github.com/superseriousbusiness/gotosocial/blob/a6ec2a5bc260aa1be0e97c4be674266748fe093d/internal/api/wellknown/webfinger/webfingerget.go#L58-L61

Under the principal of "be conservative in what you send, be liberal in what you accept", I think the server should accept either `application/json` or `application/jrd+json`, and return `application/jrd+json`

### What's your GoToSocial Version?

0.8.1 git-4dbf9a2

### What happened?

Attempting to query a user with the [webfinger-cli](https://github.com/pfefferle/webfinger-cli) tool returns an error

### What you expected to happen?

The tool should return the profile information for the requested user

### How to reproduce it?

1. Install the webfinger-cli tool
2. Run the command `webfinger acct:gotosocial@superseriousbusiness.org`

**Comment by tsmethurst** [comment]
Ah thanks, will fix :)
