### ISSUE TITLE
[bug] Tusky can't refresh notifications

### ISSUE THREAD

**Issue by huggenknubbel** [superseriousbusiness/gotosocial#1737]
### Describe the bug with a clear and concise description of what the bug is.

a manual refresh the Tusky "notifications" tab shows: Nothing there"
but the initial start show there some Messages. Also i got notifications if i got mentionet. 
the logs shows:

``
func=middleware.Logger.func1.1 level=INFO latency=2.287686ms clientIP=87.128.113.191 userAgent="Tusky/22.0 beta 1 Android/13 OkHttp/4.11.0" method=GET statusCode=404 path=/api/v1/notifications/01GJZ8W2M9H9RHFX043N1B6974 requestID=n8qwqsc704001p5bcy20 msg="Not Found: wrote 1.79kiB"
``

if i go in Pinaforce to the Notifications is see:

``
 func=middleware.Logger.func1.1 level=INFO latency=7.231896ms clientIP=10.0.2.1 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0" method=GET statusCode=200 p                                       ath=/api/v1/notifications requestID=tb7x3sc704001qm7fd6g msg="OK: wrote 2.81kiB"
``

### What's your GoToSocial Version?

0.8.1

### GoToSocial Arch

arm64 binary

### Anything else we need to know?

There is a simmilar issue at Tusky: 
[3580](https://github.com/tuskyapp/Tusky/issues/3580)
it seems it's a problem of different implementations of the Notification API
have a look at [this](https://github.com/tuskyapp/Tusky/issues/3580#issuecomment-1527198806)

**Comment by tsmethurst** [comment]
Already got a PR open that fixes this :sunglasses: https://github.com/superseriousbusiness/gotosocial/pull/1734
