### ISSUE TITLE
[bug] Cannot set account `fields_attributes` via JSON

### ISSUE THREAD

**Issue by dotsam** [superseriousbusiness/gotosocial#1759]
### Describe the bug with a clear and concise description of what the bug is.

Support for editing profile fields was added in #1483, and it looks like steps were taken to handle the [slightly strange](https://docs.joinmastodon.org/methods/accounts/#update_credentials) implementation of the `fields_attributes` parameter, but I am having issues with it from Ice Cubes v1.6.15

It appears that the unmarshalling of the JSON response is not working correctly.

When updating a profile, with no profile fields, Ice Cubes sends the following JSON body to `/api/v1/accounts/update_credentials`:
```json
{
    "bot": false,
    "discoverable": false,
    "display_name": "testuser",
    "fields_attributes": {},
    "locked": false,
    "note": "about text",
    "source": {
        "privacy": "public",
        "sensitive": false
    }
}
```

And GTS returns the following error:
```
Bad Request: could not parse form from request: json: cannot unmarshal object into Go struct field UpdateCredentialsRequest.fields_attributes of type []model.UpdateField
```

When attempting to set a profile field, Ice Cubes sends the following body:
```json
{
    "bot": false,
    "discoverable": false,
    "display_name": "testuser",
    "fields_attributes": {
        "0": {
            "name": "Website",
            "value": "https://example.com"
        }
    },
    "locked": false,
    "note": "about text",
    "source": {
        "privacy": "public",
        "sensitive": false
    }
}
```

And GTS again throws the error:

```
Bad Request: could not parse form from request: json: cannot unmarshal object into Go struct field UpdateCredentialsRequest.fields_attributes of type []model.UpdateField
```

### What's your GoToSocial Version?

v0.8.0 git-6392e00

### GoToSocial Arch

amd64 Binary

### What happened?

Attempting to add or edit profile information through the "Edit Info" option in Ice Cubes presents an "Error while saving profile" message, and the information is not updated

### What you expected to happen?

Profile information to update correctly

### How to reproduce it?

Connect a GTS hosted profile to Ice Cubes, and attempt to edit your own profile. Even hitting "Save" while making no changes will produce an error.

**Comment by tsmethurst** [comment]
Bugger, thanks. Looks like we parse it fine when it's submitted as a form, but not when it's submitted as JSON. Will poke around with it.

As for the error handling: yeah we should probably adjust the order of the content-type offers for API endpoints to offer json first, rather than text.
