### ISSUE TITLE
[bug] API searches often return 500 ISE when they oughtn't

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#1761]
Often when searching for a remote account--especially when that account doesn't actually exist on the remote server--the api search endpoint returns a code 500. In most cases, we should just return an empty search response to the user instead of a 500 when nothing is found. We should check through the search logic to ensure that we only return 500 on actual errors.

**Comment by NyaaaWhatsUpDoc** [comment]
Again I think #1690 might actually fix this.
