### ISSUE TITLE
[bug] Pagination always includes next page even if it's the last one

### ISSUE THREAD

**Issue by GeopJr** [superseriousbusiness/gotosocial#1807]
### Describe the bug with a clear and concise description of what the bug is.

On Tuba pagination loops when there's only one page. The header is:

```
<http://localhost:8080/api/v1/timelines/public?limit=20&max_id=01F8MH75CBF9JFX4ZAD54N0W0R>; rel="next", <http://localhost:8080/api/v1/timelines/public?limit=20&min_id=01F8MH75CBF9JFX4ZAD54N0W0R>; rel="prev"
```

notice that both pages have the same id for max/min, causing a loop of the same statuses to appear

[Screencast from 2023-05-22 01-43-19.webm](https://github.com/superseriousbusiness/gotosocial/assets/18014039/9a93a8ae-7a30-4c54-a1b5-c1d74f4d5e73)

### What's your GoToSocial Version?

9c24dee01fc88fc69d581951ef0b6266e301f326

### GoToSocial Arch

x86_64 Binary

### What you expected to happen?

Similar to Mastodon, it should either not include the header or not include the next page:

```
<https://tech.lgbt/api/v1/favourites?limit=20&min_id=2632365>; rel="prev"
```

### How to reproduce it?

1. Start testrig
2. Login with `@the_mighty_zork`'s account on Tuba (port is automatically removed and http gets replaced with https so localhost might not work, I can make a custom build if needed)
3. Select the `Local` sidebar item
4. Scroll to the bottom and notice that the last post gets repeated indefinitely 

### Anything else we need to know?

I can add a check from Tuba's side, but thought I should raise an issue here first in case it occurs in other clients too!

**Comment by tsmethurst** [comment]
Thanks!

**Comment by tsmethurst** [comment]
Could you possibly try building the testrig again from this branch -- https://github.com/superseriousbusiness/gotosocial/tree/account_status_paging_updates -- and seeing if you still run into the same pagination errors?

When I now do the following query against the testrig:

```
curl -i -H 'Authorization: Bearer NZAZOTC0OWITMDU0NC0ZODG4LWE4NJITMWUXM2M4MTRHZDEX' -H 'accept: application/json' 'http://localhost:8080/api/v1/timelines/public?limit=20&max_id=01F8MH75CBF9JFX4ZAD54N0W0R'
```

I get an empty json array in response, and the headers:

```
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Type: application/json; charset=utf-8
Permissions-Policy: browsing-topics=()
Server: gotosocial
Date: Mon, 22 May 2023 12:35:07 GMT
Content-Length: 2
```

Which should be correct, I hope!

**Comment by GeopJr** [comment]
Upon further inspection, it looks like Tuba is messing up the parameters `?limit=20&max_id=01F8MH75CBF9JFX4ZAD54N0W0Rlocal=true` vs `?limit=20&max_id=01F8MH75CBF9JFX4ZAD54N0W0R&local=true`. Sorry for the trouble you went through 🙇

**Comment by tsmethurst** [comment]
Ahh I see! Well that's no problem, those functions needed to be tidied up anyways :)
