### ISSUE TITLE
[bug] refetched threads displaying out of order

### ISSUE THREAD

**Issue by technomancy** [superseriousbusiness/gotosocial#1815]
### Describe the bug with a clear and concise description of what the bug is.

I had a reply to a user I don't follow get boosted to my home timeline. When I navigated to the reply, the entire thread was fetched, as expected with the refetch logic. However, the post which landed on my home timeline (and triggered the refetch) was displayed as the first post in the thread (of 4) when in fact it was the last.

Viewing any other post in the thread showed things correctly; the original post was displayed at the end of the thread instead of at the top. It's only when viewing the original post directly that it was displayed out of order.

Unfortunately this post where I saw this is not public, so I don't think linking to it here would do much good. However, I will keep an eye out to see if I can spot this happening with a public post!

### What's your GoToSocial Version?

0.9.0-rc2

### GoToSocial Arch

linux-amd64

**Comment by tsmethurst** [comment]
Is this still an issue? Or did we fix it with recent thread dereference changes?

**Comment by technomancy** [comment]
I haven't seen this in a long time! I think it's probably fixed. Thanks!
