### ISSUE TITLE
[bug] Re-used and updated hashtags (same spelling, different case) are not rendered as clickable URLs in user profiles or posts

### ISSUE THREAD

**Issue by nachtlied1** [superseriousbusiness/gotosocial#1822]
### Describe the bug with a clear and concise description of what the bug is.

I tried to update my profile and convert all of the lower case hashtags to CamelCase, e.g. updating `#somehashtag` to `#SomeHashtag`.

Saving the updated profile *technically* worked and the change propagated as expected.

However, the 'new' CamelCase hashtags were NOT rendered as clickable URLs (e.g. https://subdomain.tld/tags/SomeHashtag)  as expected when I reloaded the profile in both the web interface and in my phone app. Rather, they were rendered as just another string.

### What's your GoToSocial Version?

0.9.0-rc2

### GoToSocial Arch

arm64 Docker

### What happened?

I looked at my account's `note` content in the DB `accounts` table and noticed that:
* one completely new hashtag that I added had an HTML `a href` tag: `<a href="https://subdomain.tld/tags/NewTag" class="mention hashtag" rel="tag nofollow noreferrer noopener" target="_blank">#<span>NewTag</span></a>`
* the updated CamelCase hashtags (which were previously all lower case) did *not* have `a href` tags. Instead they showed up as plain text: `#UpdatedCamelCaseTag`

In my logs I then saw a number of `duplicate key value violates unique constraint "tags_pkey" (SQLSTATE 23505)` errors. The number of errors aligned with the number of hashtags that I converted to CamelCase and occurred at the same time as the profile update request, so I'm assuming the two things are related:

```
May 23 05:33:33 ba1c28bdc863 gotosocial[1]: timestamp="23/05/2023 05:33:33.930" func=text.(*customRenderer).replaceHashtag level=ERROR requestID=cmshjhw804000qzv3a90 msg="error putting tags in db: ERROR: duplicate key value violates unique constraint \"tags_pkey\" (SQLSTATE 23505)"
May 23 05:33:33 ba1c28bdc863 gotosocial[1]: timestamp="23/05/2023 05:33:33.931" func=text.(*customRenderer).replaceHashtag level=ERROR requestID=cmshjhw804000qzv3a90 msg="error putting tags in db: ERROR: duplicate key value violates unique constraint \"tags_pkey\" (SQLSTATE 23505)"
May 23 05:33:33 ba1c28bdc863 gotosocial[1]: timestamp="23/05/2023 05:33:33.932" func=text.(*customRenderer).replaceHashtag level=ERROR requestID=cmshjhw804000qzv3a90 msg="error putting tags in db: ERROR: duplicate key value violates unique constraint \"tags_pkey\" (SQLSTATE 23505)"
May 23 05:33:33 ba1c28bdc863 gotosocial[1]: timestamp="23/05/2023 05:33:33.937" func=text.(*customRenderer).replaceHashtag level=ERROR requestID=cmshjhw804000qzv3a90 msg="error putting tags in db: ERROR: duplicate key value violates unique constraint \"tags_pkey\" (SQLSTATE 23505)"
```

Looking at the `tags` table, it appears that:
* a new key was inserted for `NewTag` 
* no new key was inserted for `UpdatedCamelCaseTag` (or any of the other updated hashtags)

I'm wondering if there's maybe an issue with case sensitivity somewhere? Although I'm not sure that that makes sense since the `tags_pkey` constraint appears to be set on `id`, not `name`... Anyway, something is off somewhere. :)

Maybe this is also related in some way to https://github.com/superseriousbusiness/gotosocial/issues/1744 ?

### What you expected to happen?

Any updated hashtags (same spelling, different case) in a user profile should still render as clickable URLs when someone views the profile.

### How to reproduce it?

1. Add a lower case hashtag to your user profile in the web admin interface. Save it.
2. Edit the profile and convert the lower case hashtag to CamelCase (or anything where at least one of the original hashtag characters is in a different case).
3. Save the profile
4. Reload the profile and observe that the hashtag no longer renders as a clickable URL
5. Look in the GTS application logs (ERROR level) for errors like `duplicate key value violates unique constraint "tags_pkey"`

**Comment by tsmethurst** [comment]
Thanks! We're gonna work on hashtags soonish to get them implemented properly, so we'll take this along when we do :)

**Comment by daenney** [comment]
I think the problem stems from somewhere here eventually https://github.com/superseriousbusiness/gotosocial/blob/282be6f26dd4dfb57c3a21b92b756c40c05b2e6c/internal/db/bundb/bundb.go#L492

This should work fine and the comparison is done lowercase so the changing of your casing shouldn't matter, it's still the same tag. But somehow it seems like it's then still trying to reinsert the same tag? You shouldn't be able to get 2 tags with the same ID, so the pk violation seems like it should only be possible if we're trying to re-insert the same value?

I'm guessing we have some casing confusion somewhere.
