### ISSUE TITLE
[feature] Support trophies!

### ISSUE THREAD

**Issue by SoniEx2** [superseriousbusiness/gotosocial#1824]
### Is your feature request related to a problem ?

Trophies are a pretty cool mastodon feature.

### Describe the solution you'd like.

We'd like GtS to support trophies just like mastodon does.

### Describe alternatives you've considered.

N/A

### Additional context.

Trophies can do this: https://fedi-to.net/go?h=5&target=web%2Bap://chaos.social/@SoniEx2/110364933701336878

**Comment by tsmethurst** [comment]
Trophies? I've never heard of that or seen it in the Mastodon docs. Can you link to Mastodon docs about that feature?

**Comment by SoniEx2** [comment]
We did.

**Comment by NyaaaWhatsUpDoc** [comment]
Are you talking about Mastodon account verification?

**Comment by SoniEx2** [comment]
Yep! They can be misused as a trophy case of sorts.

**Comment by tsmethurst** [comment]
Gonna close this one in favor of https://github.com/superseriousbusiness/gotosocial/issues/2352 since it's a bit better described there.
