### ISSUE TITLE
[bug] Tracing: error when enabling OpenTelemetry based tracing support.

### ISSUE THREAD

**Issue by jeherve** [superseriousbusiness/gotosocial#1825]
### Describe the bug with a clear and concise description of what the bug is.

This may be related to #1791.

Upon upgrading to v0.9.0, I set `tracing-enabled` to `true` in my config, out of curiosity. This resulted in the following in my logs:

```
error executing command: error initializing tracing: building tracing exporter: failed to build resolver: passthrough: received empty target in Build()
```

I suspect I may have needed to do something before to "just" enable this, and I'd be curious about it.

### What's your GoToSocial Version?

v0.9.0

### GoToSocial Arch

linux_amd64 binary

**Comment by tsmethurst** [comment]
Hmm, did you also try setting `tracing-endpoint`?

**Comment by jeherve** [comment]
I did not! That's probably why I ran into the issue. 🤦 I suppose we can close this then, and I'll wait for #1791 to figure out how to do this properly instead of "just enabling this to see what it does". :)

Sorry!

**Comment by tsmethurst** [comment]
No worries :)
