### ISSUE TITLE
[bug] Gotosocial 0.9 responded with the incorrect reblogged status of posts in the home timeline.

### ISSUE THREAD

**Issue by veer66** [superseriousbusiness/gotosocial#1832]
### Describe the bug with a clear and concise description of what the bug is.

https://github.com/superseriousbusiness/gotosocial/assets/370688/cb98e412-5efa-4c34-9cd3-347e2fcef7eb

### What's your GoToSocial Version?

0.0

### GoToSocial Arch

arm64

### What happened?

The reblogged status of the post in the home timeline was false, although I boosted the post.

### What you expected to happen?

The reblogged status of the post in the home timeline must be true after I boosted the post.

### How to reproduce it?

1. Boost my post
2. Reload the home timeline, which is /api/v1/timelines/home?limit=20
3. Check reblogged status of the post

**Comment by tsmethurst** [comment]
This is related to https://github.com/superseriousbusiness/gotosocial/issues/1449, we'll fix it soon(tm)!

**Comment by veer66** [comment]
@tsmethurst Thank you. I will keep [disabling the timeline cache](https://github.com/superseriousbusiness/gotosocial/commit/522c45ff1355d5dfeb68559a708ee51fd99a089b) until #1449 is fixed.
