### ISSUE TITLE
[bug] Backend does not enforce lowercase shortcode for emoji, frontend does

### ISSUE THREAD

**Issue by moan0s** [superseriousbusiness/gotosocial#1833]
### Describe the bug with a clear and concise description of what the bug is.

It is possible to create an uppercase shortcode by using a filename that contains uppercase letters.

### What's your GoToSocial Version?

0.9.0

### GoToSocial Arch

Docker

### What happened?

I could add a emojy with uppercase shortcode

### What you expected to happen?

Some kind of error

### How to reproduce it?

* Take a png that you like and name it `Test_Case.png`
* Go to the administration area in the GTS admin page -> Add new custom emoji
* Browse and select the file
* leave the automatic shortcode as is
* You should have a emoji with shortcode Test_Case in your Overview of custom emoji

### Anything else we need to know?

Relevant lines in the code:
* Backend comment, saying it should be lowercase: https://github.com/superseriousbusiness/gotosocial/blob/1f069140072be09b67bf0f18b96f575967718ded/internal/gtsmodel/emoji.go#LL27C54-L27C54
* Where it will be validated: https://github.com/superseriousbusiness/gotosocial/blob/1f069140072be09b67bf0f18b96f575967718ded/internal/validate/formvalidation.go#L183
* Here is the regex that does not enforce the lowercase: https://github.com/superseriousbusiness/gotosocial/blob/1f069140072be09b67bf0f18b96f575967718ded/internal/regexes/regexes.go#LL48C30-L48C38

I'll try to fix this myself but wanted to do a proper issue

**Comment by daenney** [comment]
Looking at https://docs.joinmastodon.org/methods/custom_emojis/, it seems capitalised is entirely fine. Unsure about mixed-case but I imagine that doesn't matter either.

Of course internally we can do something different than what we return on the client API, but I'm not sure what problems we would be solving by forcing it to lowercase, and what surprises for people it may create. From the Masto Client API it's clear that `aaaa` and `AAAA` don't represent the same asset, but if we lowercase this internally we wouldn't be able to allow for that.

**Comment by moan0s** [comment]
I'd disagree as the frontend currently does not allow both lower and uppercase. So if you upload an image with Uppercase in the filename, this will automatically be used but you can't change it due to the restriction (as the name will be checked when changed. This leads to user confusion (at least i was confused 😅).
Therefore I'd suggest to lift the restriction in the frontend too. I'd be happy to provide a PR for that

**Comment by tsmethurst** [comment]
Aha yes please do, that would be great :) better check with @f0x52 as well, see if there's any complications
