### ISSUE TITLE
[bug] GTS do not work on an Raspberry with Kernel 6.1.x

### ISSUE THREAD

**Issue by Teufel100** [superseriousbusiness/gotosocial#1838]
### Describe the bug with a clear and concise description of what the bug is.

After i update my Raspberry Pi OS Kernel to version 6.1.x (6.1.29 at the moment), GTS do not work any more. In the logs i can see, that there is some communication between instances, but i can not read or write toots and i can not open the website of my GTS instances. 

Solution for now is, to go back to the old Kernel 5.1.x and hold them.

 

### What's your GoToSocial Version?

0.9.0

### GoToSocial Arch

arm64 Binary

### What happened?

I update the kernel from 5.1.x to 6.1.x on an raspberry Pi 3. After it, GTS do not work anymore with the Client (Tusky, Pinafore, Semaphore) and i can not open the website of my instance. 

`Mai 28 15:31:38 Teufel100sCloud gotosocial[27324]: timestamp="28/05/2023 15:31:38.477" func=middleware.Logger.func1.1 level=ERROR stacktrace="util.genericErrorHandler()\n\t/drone/src/internal/api/util/errorhandling.go:72\nutil.ErrorHandler()\n\t/drone/src/internal/api/util/errorhandling.go:107\nutil.WebErrorHandler()\n\t/drone/src/internal/api/util/errorhandling.go:113\nweb.(*Module).profileGETHandler()\n\t/drone/src/internal/web/profile.go:60\ngin.(*Context).Next()\n\t/drone/src/vendor/github.com/gin-gonic/gin/context.go:174\ngzip.(*gzipHandler).Handle()\n\t/drone/src/vendor/github.com/gin-contrib/gzip/handler.go:60\ngin.(*Context).Next()\n\t/drone/src/vendor/github.com/gin-gonic/gin/context.go:174\nmiddleware.Throttle.func2()\n\t/drone/src/internal/middleware/throttling.go:124\ngin.(*Context).Next()\n\t/drone/src/vendor/github.com/gin-gonic/gin/context.go:174\n" requestID=xxx msg="recovered panic: error converting instance to api representation: InstanceToAPIV1Instance: db error getting instance contact account xxx : \"error populating account header: context canceled\""`

*i changed IDs with xxx

### What you expected to happen?

Work with Client and open the website

### How to reproduce it?

Change the kernel on the raspberry 3 OS (64 bit) from 5.1.x to 6.1.x

**Comment by tsmethurst** [comment]
I'm really not sure how a kernel change could be affecting this... anyone have any ideas?

**Comment by igalic** [comment]
> GoToSocial Arch
> arm64 Binary

i know go abstracts a lot away, but have you tried building yourself?
on the actuary system?

**Comment by Teufel100** [comment]
> > GoToSocial Arch
> > arm64 Binary
> 
> i know go abstracts a lot away, but have you tried building yourself? on the actuary system?

Yeah i tried it, but it was the same. I ask another user of GTS, if he can test it on his system - he use another Distro, and it works for him with the new Kernel. So it is a problem with Raspberry PI OS 64 Bit and the new kernel and maybe the nginx proxy module. I will test it again next week, if i have a little bit more time. 

```
2023/05/31 01:20:57 [error] 898#898: *2456 upstream prematurely closed connection while reading response header from upstream, client: 46.142.104.135, server: social.guckt.info, request: "GET /@teufel100 HTTP/1.1", upstream: "http://127.0.0.1:8083/@teufel100", host: "social.guckt.info", referrer: "https://social.guckt.info/@teufel100"
2023/05/31 01:21:00 [error] 899#899: *2188 upstream prematurely closed connection while reading response header from upstream, client: 46.142.104.135, server: social.guckt.info, request: "GET /api/v1/notifications?limit=20 HTTP/1.1", upstream: "http://127.0.0.1:8083/api/v1/notifications?limit=20", host: "social.guckt.info"
2023/05/31 01:22:14 [error] 899#899: *2188 upstream prematurely closed connection while reading response header from upstream, client: 46.142.104.135, server: social.guckt.info, request: "GET /api/v1/notifications?max_id=01H1P58R5ZMSA28SWYVDHJHKMZ&limit=20 HTTP/1.1", upstream: "http://127.0.0.1:8083/api/v1/notifications?max_id=01H1P58R5ZMSA28SWYVDHJHKMZ&limit=20", host: "social.guckt.info"
2023/05/31 01:29:45 [error] 899#899: *2608 upstream prematurely closed connection while reading response header from upstream, client: 46.142.104.135, server: social.guckt.info, request: "GET /@teufel100 HTTP/1.1", upstream: "http://127.0.0.1:8083/@teufel100", host: "social.guckt.info", referrer: "https://social.guckt.info/@teufel100"
2023/05/31 01:29:46 [error] 899#899: *2709 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 185.244.192.119, server: social.guckt.info, request: "GET /api/v1/instance/peers?filter=suspended HTTP/1.1", upstream: "http://127.0.0.1:8083/api/v1/instance/peers?filter=suspended", host: "social.guckt.info"
2023/05/31 01:29:46 [error] 899#899: *2719 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 170.39.215.215, server: social.guckt.info, request: "GET /nodeinfo/1.0 HTTP/1.1", upstream: "http://127.0.0.1:8083/nodeinfo/1.0", host: "social.guckt.info"
2023/05/31 01:29:46 [error] 899#899: *2721 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 168.119.48.141, server: social.guckt.info, request: "POST /users/teufel100/inbox HTTP/1.1", upstream: "http://127.0.0.1:8083/users/teufel100/inbox", host: "social.guckt.info"
2023/05/31 01:32:05 [error] 894#894: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 168.119.48.141, server: social.guckt.info, request: "POST /users/teufel100/inbox HTTP/1.1", upstream: "http://127.0.0.1:8083/users/teufel100/inbox", host: "social.guckt.info"
2023/05/31 01:32:07 [error] 894#894: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 213.239.212.206, server: social.guckt.info, request: "GET /users/teufel100 HTTP/1.1", upstream: "http://127.0.0.1:8083/users/teufel100", host: "social.guckt.info"
2023/05/31 01:32:13 [error] 894#894: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 141.95.205.46, server: social.guckt.info, request: "POST /users/teufel100/inbox HTTP/1.1", upstream: "http://127.0.0.1:8083/users/teufel100/inbox", host: "social.guckt.info"
2023/05/31 01:32:16 [error] 894#894: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 141.95.205.46, server: social.guckt.info, request: "POST /users/teufel100/inbox HTTP/1.1", upstream: "http://127.0.0.1:8083/users/teufel100/inbox", host: "social.guckt.info"
2023/05/31 01:32:18 [error] 894#894: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 167.235.62.95, server: social.guckt.info, request: "POST /users/teufel100/inbox HTTP/1.1", upstream: "http://127.0.0.1:8083/users/teufel100/inbox", host: "social.guckt.info"
2023/05/31 01:34:35 [error] 895#895: *22 upstream prematurely closed connection while reading response header from upstream, client: 46.142.104.135, server: social.guckt.info, request: "GET /api/v1/timelines/home?since_id=01H1QFASM74J74PFW5AV6FVGGM&limit=20 HTTP/1.1", upstream: "http://127.0.0.1:8083/api/v1/timelines/home?since_id=01H1QFASM74J74PFW5AV6FVGGM&limit=20", host: "social.guckt.info"
2023/05/31 01:36:05 [error] 894#894: *21 upstream prematurely closed connection while reading response header from upstream, client: 46.142.104.135, server: social.guckt.info, request: "GET /api/v1/notifications?since_id=01H1QFN7XQSKZG7CFXB5P71GP0&limit=20 HTTP/1.1", upstream: "http://127.0.0.1:8083/api/v1/notifications?since_id=01H1QFN7XQSKZG7CFXB5P71GP0&limit=20", host: "social.guckt.info"
2023/05/31 01:36:05 [error] 894#894: *49 upstream prematurely closed connection while reading response header from upstream, client: 46.142.104.135, server: social.guckt.info, request: "GET /api/v1/timelines/home?since_id=01H1QFASM74J74PFW5AV6FVGGM&limit=20 HTTP/1.1", upstream: "http://127.0.0.1:8083/api/v1/timelines/home?since_id=01H1QFASM74J74PFW5AV6FVGGM&limit=20", host: "social.guckt.info"
2023/05/31 06:30:43 [error] 894#894: *6824 upstream prematurely closed connection while reading response header from upstream, client: 176.9.158.44, server: social.guckt.info, request: "GET /@teufel100 HTTP/1.1", upstream: "http://127.0.0.1:8083/@teufel100", host: "social.guckt.info", referrer: "https://social.guckt.info/users/teufel100"
2023/05/31 13:30:11 [error] 894#894: *37250 upstream prematurely closed connection while reading response header from upstream, client: 85.214.137.198, server: social.guckt.info, request: "GET /users/teufel100/statuses/01H1RS0PKFJHG5YH3ZX6SMKBQ6 HTTP/1.1", upstream: "http://127.0.0.1:8083/users/teufel100/statuses/01H1RS0PKFJHG5YH3ZX6SMKBQ6", host: "social.guckt.info"
2023/05/31 13:30:43 [error] 894#894: *37723 upstream prematurely closed connection while reading response header from upstream, client: 37.120.168.161, server: social.guckt.info, request: "GET /@teufel100 HTTP/1.1", upstream: "http://127.0.0.1:8083/@teufel100", host: "social.guckt.info", referrer: "https://social.guckt.info/users/teufel100"
2023/05/31 13:30:43 [error] 894#894: *37763 upstream prematurely closed connection while reading response header from upstream, client: 176.9.158.44, server: social.guckt.info, request: "GET /@teufel100 HTTP/1.1", upstream: "http://127.0.0.1:8083/@teufel100", host: "social.guckt.info", referrer: "https://social.guckt.info/users/teufel100"
```

**Comment by daenney** [comment]
I'm not seeing any evidence of a kernel-related issue in this honestly. If we were looking at a kernel issue it would typically manifest as either a crash with a coredump or some form of memory corruption (which should also result in a crash).

The best I can see from the logs is a database related issue. Are you running with SQLite or postgres in this case?

**Comment by Teufel100** [comment]
> I'm not seeing any evidence of a kernel-related issue in this honestly. If we were looking at a kernel issue it would typically manifest as either a crash with a coredump or some form of memory corruption (which should also result in a crash).
> 
> The best I can see from the logs is a database related issue. Are you running with SQLite or postgres in this case?

SQLite. And yes, i aggree with you, that this is not a problem with the kernel itself, but something get broken, if i install the 6.1.x kernel. Maybe i will take it with a new install of the whole system, or i change the Distro.

**Comment by tsmethurst** [comment]
hey @Teufel100 did you ever manage to resolve this?

**Comment by Teufel100** [comment]
> hey @Teufel100 did you ever manage to resolve this?

No, but I know, with another Distribution (not Debian) it works. So it is not a Kernel-Thing by itself. I wait now for the next big upgrade, before I change the Kernel and hope, that this will fix the problem. :)  - So i think, you can close this Topic.
