### ISSUE TITLE
build broke on FreeBSD 13.0-RELEASE amd64 + go 1.17 

### ISSUE THREAD

**Issue by dch** [superseriousbusiness/gotosocial#184]
drive-by bug report on @igalic behalf from mastodon.

env: 

- FreeBSD 13.0-RELEASE amd64
- go 1.17
- commit  #7d193de fails to build

```
$ ./build.sh
package github.com/superseriousbusiness/gotosocial/cmd/gotosocial
	imports github.com/superseriousbusiness/gotosocial/internal/cliactions/admin/account
	imports github.com/superseriousbusiness/gotosocial/internal/db/bundb
	imports modernc.org/sqlite
	imports modernc.org/libc
	imports modernc.org/libc/errno: build constraints exclude all Go files in /repos/gotosocial/vendor/modernc.org/libc/errno
package github.com/superseriousbusiness/gotosocial/cmd/gotosocial
	imports github.com/superseriousbusiness/gotosocial/internal/cliactions/admin/account
	imports github.com/superseriousbusiness/gotosocial/internal/db/bundb
	imports modernc.org/sqlite
	imports modernc.org/libc
	imports modernc.org/libc/signal: build constraints exclude all Go files in /repos/gotosocial/vendor/modernc.org/libc/signal
package github.com/superseriousbusiness/gotosocial/cmd/gotosocial
	imports github.com/superseriousbusiness/gotosocial/internal/cliactions/admin/account
	imports github.com/superseriousbusiness/gotosocial/internal/db/bundb
	imports modernc.org/sqlite
	imports modernc.org/libc/sys/types: build constraints exclude all Go files in /repos/gotosocial/vendor/modernc.org/libc/sys/types
package github.com/superseriousbusiness/gotosocial/cmd/gotosocial
	imports github.com/superseriousbusiness/gotosocial/internal/cliactions/admin/account
	imports github.com/superseriousbusiness/gotosocial/internal/db/bundb
	imports modernc.org/sqlite
	imports modernc.org/libc
	imports modernc.org/libc/time: build constraints exclude all Go files in /repos/gotosocial/vendor/modernc.org/libc/time
package github.com/superseriousbusiness/gotosocial/cmd/gotosocial
	imports github.com/superseriousbusiness/gotosocial/internal/cliactions/admin/account
	imports github.com/superseriousbusiness/gotosocial/internal/db/bundb
	imports modernc.org/sqlite
	imports modernc.org/libc
	imports modernc.org/libc/unistd: build constraints exclude all Go files in /repos/gotosocial/vendor/modernc.org/libc/unistd
```

:disappointed: :crying_cat_face: :sob: 

#87328b6 just worked, with `./build.sh` prior to the vendoring update and modernc stuff.

Hope that's enough for somebody to identify a fix?

**Comment by NyaaaWhatsUpDoc** [comment]
Do you require SQLite? It seems maybe this library doesn't support FreeBSD :( in which case a quick fix for now could be a check for Linux before importing the SQLite library

**Comment by igalic** [comment]
I've created an [issue in modernc](https://gitlab.com/cznic/libc/-/issues/10) about FreeBSD support.

regarding SQLite: I Absolutely want/need SQLite. I already wear enough hats, because I refuse to become a DBA, too.
Alternatively: I don't wanna pay AWS, Azure, GCP to somewhat reliably run a database for me, when that database could be a file.

**Comment by NyaaaWhatsUpDoc** [comment]
I might take a quick look into the requirements for getting FreeBSD support working because it does look interesting 😅. I can't promise I'll get anywhere but just know it also has my interest / attention!

**Comment by igalic** [comment]
updates:  ccgo issue](https://gitlab.com/cznic/ccgo/-/issues/16) is now solved
That one's prerequisite to the [modernc issue](https://gitlab.com/cznic/libc/-/issues/10) which is still being worked on

[SQLite](https://gitlab.com/cznic/sqlite/-/issues/68) might still need work, once that is in place.

meanwhile we've opened https://github.com/golang/go/issues/48148 and https://github.com/golang/go/issues/48160
to cleanup some issue in golang.org/x/sys/unix

**Comment by igalic** [comment]
with all of these packages now having received updates, I've tried to build it
but since they are vendored, I had to update them first, which wasn't successful: https://gitlab.com/cznic/ccgo/-/issues/17

not 100% sure it's a ccgo bug tho, could just be that we're vendoring a waaay too old version?

**Comment by igalic** [comment]
after updating correctly, it compiles and it runs:

```
meena@bsdix ~/s/gotosocial (main)> ./gotosocial --db-type sqlite --host localhost server start
time="2021-09-08T15:21:04Z" level="info" msg="connected to database"
time="2021-09-08T15:21:04Z" level="info" msg="instance entry already exists"
```

**Comment by tsmethurst** [comment]
> it'd feel like cheating my way into the top contributors list ;)

Haha :D 'top contributors list' means nothing around here, don't worry, feel free to submit a patch if you like :) If not, i'll have a crack at it later. Can you list the packages you had to update?

**Comment by NyaaaWhatsUpDoc** [comment]
Just put in a PR for this at #198

**Comment by NyaaaWhatsUpDoc** [comment]
@igalic @dch would you be able to confirm that main can build for you now? please bear in mind there are db changes that need migrating in main so maybe don't switch to it just yet, just attempt a build :')

**Comment by igalic** [comment]
lookin good:

```
meena@bsdix ~/src> rm -rf gotosocial/
meena@bsdix ~/src> git clone https://github.com/superseriousbusiness/gotosocial
Cloning into 'gotosocial'...
remote: Enumerating objects: 9676, done.
remote: Counting objects: 100% (3098/3098), done.
remote: Compressing objects: 100% (1739/1739), done.
remote: Total 9676 (delta 2008), reused 1568 (delta 1331), pack-reused 6578
Receiving objects: 100% (9676/9676), 38.59 MiB | 2.38 MiB/s, done.
Resolving deltas: 100% (4720/4720), done.
Updating files: 100% (4183/4183), done.
meena@bsdix ~/src> cd gotosocial/
meena@bsdix ~/s/gotosocial (main)> ./build.sh
meena@bsdix ~/s/gotosocial (main)> ./gotosocial --db-type sqlite --host localhost server start
time="2021-09-10T09:50:02Z" level="info" msg="connected to database"
time="2021-09-10T09:50:02Z" level="info" msg="created instance instance localhost with id 01JF06H4GPBBJQC6XG4TEM89M0"
```

**Comment by NyaaaWhatsUpDoc** [comment]
woohoo!
