### ISSUE TITLE
[bug] HTTP client connection reuse

### ISSUE THREAD

**Issue by daenney** [superseriousbusiness/gotosocial#1847]
### Describe the bug with a clear and concise description of what the bug is.

Looking around at our code, whenever we're acting as an HTTP client we don't seem to drain the response body.

We correctly follow the Go documentation and seem to `defer` a `*http.Response.Body.Close()` everywhere, but if there's still data on the response and we don't read it the connection can't get reused. This can happen fairly easily when we get an unexpected status code. We often only check the status code, but in many cases there may be a body with an error message too. But without reading the body, the connection can't be reused in those cases. When doing multiple requests against the same server, this incurs the cost of additional TCP and TLS handshakes which would be nice to avoid. This seems to primarily hit us when we're trying to deference an instance or are webfingering them but I imagine there's other places this happens when we're federating.

To fix it, we'd have to do something like the following everywhere instead:

```go
defer func() {
  io.Copy(io.Discard, resp.Body)
  resp.Body.Close()
}()
```

This gets rather tedious to write and is easily forgotten. We could do a helper method, something like `DrainAndClose(*http.Response)` which you could then defer instead.

We can pretty safely do this because our httpclient already wraps the body in an `io.LimitReader` so we're not at risk of accidentally reading a huge response body from a (malicious) server unnecessarily. At that point we just pay the cost of not being able to reuse the connection.

In the HTTP server in Go this draining happens automatically after the handler returns. I've looked at if we can solve this in the httpclient or the transport in a similar fashion but I can't come up with a solution that I like.

### What's your GoToSocial Version?

v0.9.0

### GoToSocial Arch

amd64 binary

### Anything else we need to know?

I might've missed some rather clever piece of code in the code where this is already handled in a transparent manner.

**Comment by NyaaaWhatsUpDoc** [comment]
@daenney I managed to implement a way to ensure the entire body gets drained (with protections for overly large ones) by wrapping the closer itself during the response body wrapping. You can see in the above PR :)

**Comment by daenney** [comment]
> @daenney I managed to implement a way to ensure the entire body gets drained (with protections for overly large ones) by wrapping the closer itself during the response body wrapping. You can see in the above PR :)

Ohhh, that's very cool! I really wish this was a built-in thing for the client.
