### ISSUE TITLE
[feature] Include known remote users when searching by username

### ISSUE THREAD

**Issue by kvibber** [superseriousbusiness/gotosocial#1848]
### Is your feature request related to a problem ?

When I search for a username on my single-user instance, it only brings up local results (i.e. me) unless I specify the entire name including the hostname. On Mastodon, I'll often look for just the username when I can't remember what instance someone is on.

### Describe the solution you'd like.

When I type just `@username`, I want to get a list of users I've interacted with at other instances, or at least users I'm following.

### Describe alternatives you've considered.

The search could look anywhere on this scale:
1. Users I'm following
2. Users I'm following and my followers
3. Users I've had any interaction with
4. Users who've had any interaction with anyone on my instances.

### Additional context.

Partial search would be helpful as well, both for looking up someone whose spelling you can't remember and for clients like Elk that autosuggest as you type write mentions.

**Comment by tsmethurst** [comment]
:+1:
