### ISSUE TITLE
[feature] Implement /api/v1/markers API

### ISSUE THREAD

**Issue by nachtlied1** [superseriousbusiness/gotosocial#1856]
### Is your feature request related to a problem ?

[I'm unclear if this is technically a bug or a feature request? So I'm filing it as a feature request for now since it's for a thing that technically doesn't exist yet. Feel free to move it to another category as appropriate :)]

Client applications are currently unable to make successful `GET` or `POST` calls to the `/api/v1/markers` API because the API is not implemented.  The server currently responds with a HTTP `404` (since the API doesn't exist).

Lack of this API prevents users from being able to save or restore timeline positions (at minimum) on the server side.

Mastodon API reference: https://docs.joinmastodon.org/methods/markers/

### Describe the solution you'd like.

Implementation of the `/api/v1/markers` API so that:

* clients can get saved timeline position when they send `GET /api/v1/markers` requests.  Currently this fails in apps like Tusky and Trunks.
* clients can save timeline position when they send `POST /api/v1/markers` requests.
  * note: this is currently blocking the Trunks app from displaying notifications ('Alerts') because that workflow seems to be blocked on successful completion of `POST /api/v1/markers`. (Might be a Trunks-specific thing, not sure).

Edit: I saw that https://github.com/superseriousbusiness/gotosocial/blob/main/internal/api/model/marker.go already exists, so I'm guessing that means you may already intend to add the markers API at some point

### Describe alternatives you've considered.

Based on some cursory browsing of https://docs.joinmastodon.org/methods/, it doesn't look like there are really any other Mastodon-compatible API methods that would serve this feature's purpose? But someone with more knowledge may know better...

Additionally, it does appear that multiple clients (so far) are expecting the markers API specifically.

### Additional context.

Not sure how much of a blocker this is generally for a good and/or functional user experience.

It would be nice to be able to save and restore timeline position when interacting with my server, but I wouldn't say it's the biggest quality of life issue for me specifically, although other users may have a different perspective of course.
(No lists is more of an issue for me, but I see that those are coming soon. :)

----

Sample logs:

I don't know the full list of clients that are sending `/api/v1/markers` calls, but as a reference, here are a few logged calls for Tusky and Trunks (both Android), showing a `404` response:

`GET` request:
[Tusky]
```
GTS log:

Jun  2 00:11:02 92af1656c292 gotosocial[1]: timestamp="02/06/2023 00:11:02.233" func=middleware.Logger.func1.1 level=INFO latency="91.003µs" userAgent="Tusky/21.0 Android/xx OkHttp/4.10.0" method=GET statusCode=404 path=/api/v1/markers clientIP=xx.xx.xx.xx requestID=v6172yc8040013yqzkm0 msg="Not Found: wrote 21B"

Formatted web server log:

{
  "ts": "2023-06-02T00:11:02.234Z",
  "remote_ip": "xx.xx.xx.xx",
  "proto": "HTTP/2.0",
  "method": "GET",
  "uri": "/api/v1/markers?timeline%5B%5D=notifications",
  "referer": null,
  "user_agent": [
    "Tusky/21.0 Android/xx OkHttp/4.10.0"
  ],
  "size": 21,
  "status": 404
}
```

[Trunks]
```
GTS log:

Jun  2 03:07:57 92af1656c292 gotosocial[1]: timestamp="02/06/2023 03:07:57.772" func=middleware.Logger.func1.1 level=INFO latency="25.083µs" userAgent="Dart/3.1 (dart:io)" method=GET statusCode=404 path=/api/v1/markers clientIP=xx.xx.xx.xx requestID=shyh6ym8040012bxhjng msg="Not Found: wrote 21B"

Formatted web server log:

{
  "ts": "2023-06-02T03:07:57.773Z",
  "remote_ip": "xx.xx.xx.xx",
  "proto": "HTTP/1.1",
  "method": "GET",
  "uri": "/api/v1/markers?timeline%5B%5D=notifications",
  "referer": null,
  "user_agent": [
    "Dart/3.1 (dart:io)"
  ],
  "size": 21,
  "status": 404
}
```

`POST` request:
[Trunks]
```
GTS log:

Jun  2 03:07:58 92af1656c292 gotosocial[1]: timestamp="02/06/2023 03:07:58.204" func=middleware.Logger.func1.1 level=INFO latency="25.141µs" userAgent="Dart/3.1 (dart:io)" method=POST statusCode=404 path=/api/v1/markers clientIP=xx.xx.xx.xx requestID=fhzh6ym804001haan740 msg="Not Found: wrote 21B"

Formatted web server log:

{
  "ts": "2023-06-02T03:07:58.204Z",
  "remote_ip": "xx.xx.xx.xx",
  "proto": "HTTP/1.1",
  "method": "POST",
  "uri": "/api/v1/markers",
  "referer": null,
  "user_agent": [
    "Dart/3.1 (dart:io)"
  ],
  "size": 21,
  "status": 404
}
```

**Comment by tsmethurst** [comment]
Thanks :)

**Comment by VyrCossont** [comment]
Feditext currently disables its use of the markers API when it detects GtS, since it's known not to be implemented yet, but it'd be nice if I could use it in the future.
