### ISSUE TITLE
[bug] Boosting posts report an error from Fedilab app (even though they seem to work).

### ISSUE THREAD

**Issue by punkscience** [superseriousbusiness/gotosocial#1861]
### Describe the bug with a clear and concise description of what the bug is.

When you boost a post from within the Fedilab app, it reports an unspecified error as a toaster message in red and the boost is not displayed. If you check on the posts from a different account and view the users feed, the boost is actually visible. So it appears to have succeeded and not displayed, despite reporting an error.

### What's your GoToSocial Version?

gotosocial version 0.9.0 git-282be6f

### GoToSocial Arch

arm64 Binary

### What happened?

I tried to boost posts from the Fedilab app, it reports an unspecified error as a toaster message in red and the boost is not displayed. If you check on the posts from a different account and view the users feed, the boost is actually visible. So it appears to have succeeded and not displayed, despite reporting an error.

### What you expected to happen?

It should have boosted the post without error and then displayed the boosted post in my local feed. 

### How to reproduce it?

Open your account in Fedilb app on Android and then boost a post of any person you follow.

**Comment by tsmethurst** [comment]
That's very strange... Could you perhaps open this issue on the fedilab repo as well? Did you see any odd logs in your gotosocial instance around the time of the request?

**Comment by tsmethurst** [comment]
@punkscience Should i close this? Or is it still occurring?

**Comment by tsmethurst** [comment]
Hiya, recently fixed this so I'll close the issue :)
