### ISSUE TITLE
[bug] Cannot federate with group topics provided by wxwClub

### ISSUE THREAD

**Issue by KyoSakuyo** [superseriousbusiness/gotosocial#1863]
### Describe the bug with a clear and concise description of what the bug is.

[wxwClub](https://github.com/wxwmoe/wxwClub) is an open-source board/group service serving different Fediverse servers.

Its application named ovo.st has lots of users in Chinese Fediverse ecology.

However, my toots posted via Gotosocial trying connect to ovo.st all cannot be seen in the board. 

I tried to subscribe ovo.st in Gotosocial but it failed as well.

### What's your GoToSocial Version?

0.9.1

### GoToSocial Arch

arm64 Docker

### What happened?

my toots posted via Gotosocial trying connect to ovo.st all cannot be seen in the board. 
I tried to subscribe ovo.st in Gotosocial but it failed as well.(could be found, but always be Pending)

### What you expected to happen?

All my toots has _@board@ovo.st_ mentioned in the end can be found in other accounts federated with ovo.st. 

And I can subcribe/federate with board services powered by wxwClub.

### How to reproduce it?

Just try to send this message:

> It is a test 
>
> @board@ovo.st

And you will see this message does not exist in https://ovo.st/club/board .

**Comment by tsmethurst** [comment]
Can you provide some logs from your GoToSocial instance from when you try to send the message?

**Comment by KyoSakuyo** [comment]
It's the log from sending messages

> timestamp="04/06/2023 15:42:18.328" func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://ovo.st/.well-known/webfinger?resource=acct%3Aboard%40ovo.st requestID=sqa151w80400104f117g pubKeyID=https://fed.sakuyo.net/users/kyo/main-key msg="performing request"
> timestamp="04/06/2023 15:42:18.402" func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://ovo.st/club/board requestID=sqa151w80400104f117g pubKeyID=https://fed.sakuyo.net/users/kyo/main-key msg="performing request"
> timestamp="04/06/2023 15:42:18.430" func=processing.(*Processor).ProcessFromClientAPI level=INFO activityType=Create objectType=Note fromAccount=kyo msg="processing from client"
> timestamp="04/06/2023 15:42:18.435" func=middleware.Logger.func1.1 level=INFO latency=117.912163ms userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0" method=POST statusCode=200 path=/api/v1/statuses clientIP=172.19.0.1 requestID=sqa151w80400104f117g msg="OK: wrote 837B"
> timestamp="04/06/2023 15:42:18.435" func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://ovo.st/club/board/collections/featured pubKeyID=https://fed.sakuyo.net/users/kyo/main-key msg="performing request"
> timestamp="04/06/2023 15:42:18.437" func=federation.(*federatingActor).Send level=INFO msg="send activity Create via outbox https://fed.sakuyo.net/users/kyo/outbox"
> timestamp="04/06/2023 15:42:18.450" func=httpclient.(*Client).DoSigned level=INFO method=POST url=https://ovo.st/inbox pubKeyID=https://fed.sakuyo.net/users/kyo/main-key msg="performing request"
> timestamp="04/06/2023 15:42:18.524" func=middleware.Logger.func1.1 level=INFO latency="527.826µs" userAgent="wxwClub 0.0.5; https://ovo.st" method=GET statusCode=200 path=/users/kyo/main-key clientIP=172.19.0.1 requestID=kfah51w8040005jp3hdg msg="OK: wrote 751B"

It's the log from requesting follow
> timestamp="04/06/2023 15:45:45.330" func=httpclient.(*Client).DoSigned level=INFO method=POST url=https://ovo.st/inbox pubKeyID=https://fed.sakuyo.net/users/kyo/main-key msg="performing request"
> timestamp="04/06/2023 15:45:45.434" func=middleware.Logger.func1.1 level=INFO latency="488.912µs" userAgent="wxwClub 0.0.5; https://ovo.st" method=GET statusCode=200 path=/users/kyo/main-key clientIP=172.19.0.1 requestID=v7yhb1w804001drvaws0 msg="OK: wrote 751B"
> timestamp="04/06/2023 15:45:45.644" func=middleware.Logger.func1.1 level=INFO latency=1.634822ms userAgent="http.rb/5.1.1 (Mastodon/4.1.2+nightly-20230523; +https://mastodon.social/)" method=POST statusCode=401 path=/users/kyo/inbox clientIP=172.19.0.1 requestID=nbz1b1w804001hq3cmg0 msg="Unauthorized: wrote 48B"
> timestamp="04/06/2023 15:45:46.708" func=middleware.Logger.func1.1 level=INFO latency="28.128µs" userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0" method=OPTIONS statusCode=204 path=/api/v1/accounts/01GVDRTMMPFR3J4V9R4176QEFN/follow clientIP=172.19.0.1 requestID=tc11d1w80400125nf540 msg="No Content: wrote 0B"
> timestamp="04/06/2023 15:45:46.926" func=middleware.Logger.func1.1 level=INFO latency=2.263813ms userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0" method=POST statusCode=200 path=/api/v1/accounts/01GVDRTMMPFR3J4V9R4176QEFN/follow clientIP=172.19.0.1 requestID=nc1hd1w8040008pxyy3g msg="OK: wrote 176B"
> timestamp="04/06/2023 15:45:46.926" func=processing.(*Processor).ProcessFromClientAPI level=INFO activityType=Create objectType=Follow fromAccount=kyo msg="processing from client"
> timestamp="04/06/2023 15:45:46.926" func=federation.(*federatingActor).Send level=INFO msg="send activity Follow via outbox https://fed.sakuyo.net/users/kyo/outbox"
> timestamp="04/06/2023 15:45:46.937" func=httpclient.(*Client).DoSigned level=INFO method=POST url=https://ovo.st/inbox pubKeyID=https://fed.sakuyo.net/users/kyo/main-key msg="performing request"
> timestamp="04/06/2023 15:45:46.996" func=middleware.Logger.func1.1 level=INFO latency="286.607µs" userAgent="wxwClub 0.0.5; https://ovo.st" method=GET statusCode=200 path=/users/kyo/main-key clientIP=172.19.0.1 requestID=yc1hd1w804000av3bghg msg="OK: wrote 751B"
> timestamp="04/06/2023 15:46:20.900" func=middleware.Logger.func1.1 level=INFO latency="126.894µs" userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0" method=GET statusCode=404 path=/api/v1/streaming/public/local clientIP=172.19.0.1 requestID=cj41d1w804001mebcf50 msg="Not Found: wrote 21B"

**Comment by tsmethurst** [comment]
Hmm okay, I don't see anything wrong in the logs.... that's a bit weird. Could you raise this with their repo as well, linking this issue? They might have a better idea what's going on.

**Comment by tsmethurst** [comment]
Hiya, I see there was a bit of movement in the linked issue, but I can't translate it. Is this an issue we should keep open on GoToSocial's side?

**Comment by CDN18** [comment]
Hi, seems that it was wxwClub‘s problem verifying GotoSocial's request due to signature algorithm issue, which is more or less similar to #595.
I'm attempting to fix it bug got not clue. Till now I think their is nothing we can do on GotoSocial's side.

Here's a translation of my comment, I'll provide an English version for my later comments on that issue:

> I just tested it:
>
> During interactions, wxwClub fails when performing verification (a `verify_failed` file appears in the `log/inbox` directory), for example, when sending a follow request, the log of wxwClub is as follows:
> (The log is omitted here, for details, please see wxwmoe/wxwClub/issues/5 )
> There is no corresponding `user` record in the user table of the database.

**Comment by CDN18** [comment]
Hello, my PR got merged in wxwClub's side. And it seems that gts and wxwclub can federate happliy now. Now we can close this issue 😊

**Comment by tsmethurst** [comment]
Great stuff! :)
