### ISSUE TITLE
New account created without language being set

### ISSUE THREAD

**Issue by oct2pus** [superseriousbusiness/gotosocial#187]
i created a new account on commit  [ac7c5e8cd28e9a491d7eeb560dd0fe5aed0d94df](https://github.com/superseriousbusiness/gotosocial/commit/ac7c5e8cd28e9a491d7eeb560dd0fe5aed0d94df), when i tried to create a post, i received this error
```time="2021-09-03T00:01:20Z" level="debug" msg="parsing request form: map[]" func="statusCreatePOSTHandler"
time="2021-09-03T00:01:20Z" level="debug" msg="handling status request form: &{StatusCreateRequest:{Status:bepis lol MediaIDs:[] Poll:<nil> InReplyToID: Sensitive:false SpoilerText: Visibility:public ScheduledAt: Language: Format:} AdvancedVisibilityFlagsForm:{Federated:<nil> Boostable:<nil> Replyable:<nil> Likeable:<nil>}}" func="statusCreatePOSTHandler"
time="2021-09-03T00:01:20Z" level="debug" msg="error processing status create: no language given either in status create form or account default" func="statusCreatePOSTHandler"
time="2021-09-03T00:01:20Z" level="info" msg="Bad Request: wrote 23 bytes in 3.390629ms" clientIP="68.235.43.85" latency="3.390629ms" method="POST" path="/api/v1/statuses" statusCode="400" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"
```
i'm not sure if this is related but `chosen_languages` is set to nill, and `locale` is not populated.

**Comment by tsmethurst** [comment]
Hey! That's something we're fixing in the upcoming updates: setting a default language on account creation. In the meantime you can get around it by manually setting a language for your account, either in the database directly or through an API call to `/api/v1/accounts/update_credentials` -- the parameters are documented here: https://docs.gotosocial.org/en/latest/api/swagger/

**Comment by tsmethurst** [comment]
Closing this one because we've fixed it up in our database updates by setting a default :)
