### ISSUE TITLE
[feature] Support remote interaction

### ISSUE THREAD

**Issue by SoniEx2** [superseriousbusiness/gotosocial#1895]
### Is your feature request related to a problem ?

We kinda just wish the interaction icons (reply, boost, fav) were actually interactive.

### Describe the solution you'd like.

Mastodon is currently in the process of re-working remote interactions. We don't know what they're gonna end up doing, but we'd like to encourage GTS to support redirecting the user to `https://remote.instance.example/.well-known/protocol-handler?target=web%2Bap://local.instance.example/@user/statuses/whatever` based on the user typing in `remote.instance.example`.

### Describe alternatives you've considered.

Whatever mastodon ends up doing is gonna look roughly the same as this. The advantage of using `/.well-known/protocol-handler` is that we've been pushing for it for half a year, and while it's not currently supported by any activitypub software, at least to us it seems like the most forward-thinking solution (tho we are biased).

### Additional context.

Long-term planning is considering the potential use-cases of something like `/.well-known/protocol-handler` when compared to not using it. Our intent is that it'll eventually be supported by browsers. Our expectation is that browsers won't support it unless it's widely adopted, and servers won't deploy it unless browsers support it - but do we need to wait for browser support? If servers both deploy it and consume it as an API, we can have something that satisfies the needs of servers today, and browsers can come along and add support for it later. This is win-win.

**Comment by tsmethurst** [comment]
Relates to https://github.com/superseriousbusiness/gotosocial/issues/921

Also related to https://github.com/superseriousbusiness/gotosocial/issues/921

And sort of to https://github.com/superseriousbusiness/gotosocial/issues/1768

We don't really have a horse in this race in terms of different protocols + solutions people have suggested, so we'll probably just see which one picks up steam and (if it's sensible) implement that. Did you already suggest this to Mastodon btw? Did they respond?

**Comment by SoniEx2** [comment]
we did. kinda just now. they haven't responded yet.

**Comment by tsmethurst** [comment]
> unprompted interactions are unsafe, since websites can generate them without the user knowing. having an URL for "following" would still require the remote to ask for confirmation so we feel like there's no advantage to "URLs with action" over "URLs without action"

Yeah agreed, even just a target object URI is enough, just to get you looking at the object in question in your client of choice, then you can interact with it as you wish

**Comment by filipesmedeiros** [comment]
On PeerTube, you can use remote interaction, like below:

<img width="506" alt="Screenshot 2023-11-18 at 13 38 13" src="https://github.com/superseriousbusiness/gotosocial/assets/26208850/71aa913b-6a7c-4abe-84d9-57b72d0bae6d">

But apparently the current implementation of GTS doesn't allow that because of this error: ```logger.ts:46 Error: No subscribe template in webfinger response```.

The Mastodon API docs mention this:
```
{
      "rel": "http://ostatus.org/schema/1.0/subscribe",
      "template": "https://mastodon.social/authorize_interaction?uri={uri}"
}
```
[Here](https://docs.joinmastodon.org/spec/webfinger/#example)

**Comment by SoniEx2** [comment]
you can't go peertube -> gts because gts isn't an activitypub client. this issue is for gts -> mastodon, because mastodon is an activitypub client.

(tho, self-plug: you can use fedi-to.net with tokodon and feditext. e.g. peertube -> fedi-to.net -> tokodon)

**Comment by filipesmedeiros** [comment]
@SoniEx2 sorry, what do you mean GTS is not an ActivityPub client?

**Comment by SoniEx2** [comment]
gts is not a web app. it is a mastodon-compatible API server.

**Comment by filipesmedeiros** [comment]
@SoniEx2 how do we support remote interaction for GTS then? :(

**Comment by tsmethurst** [comment]
It works for other implementations because they ship with a web client. Ie., you log into your peertube instance by going to the instance in your browser and signing in. Same with Mastodon. GoToSocial provides only status web pages (profile pages, status pages, etc) and an API, there's no web client / web app shipped with it, so there's no client to redirect to from a remote instance.

**Comment by SoniEx2** [comment]
> @SoniEx2 how do we support remote interaction for GTS then? :(

as an user? you ask your mastodon client to be like feditext or tokodon and implement the web+ap thingy already, then you can stuff `fedi-to.net` (or roll your own, it's open source) into peertube/mastodon remote interaction dialogs and it'll just work.

**Comment by filipesmedeiros** [comment]
Thank you both for the reply!

> > @SoniEx2 how do we support remote interaction for GTS then? :(
> 
> as an user? you ask your mastodon client to be like feditext or tokodon and implement the web+ap thingy already, then you can stuff `fedi-to.net` (or roll your own, it's open source) into peertube/mastodon remote interaction dialogs and it'll just work.

I will check with my app's dev (CC @cheeaun) about implementing this! Maybe not too hard?

> It works for other implementations because they ship with a web client. Ie., you log into your peertube instance by going to the instance in your browser and signing in. Same with Mastodon. GoToSocial provides only status web pages (profile pages, status pages, etc) and an API, there's no web client / web app shipped with it, so there's no client to redirect to from another instance/ActivityPub implementation.
> 
> To make this work with GoToSocial, we'd need to either ship a client with it (or allow admins to choose a default client to redirect to), or remotes would have to support some other method entirely of making "remote interaction" work.
> 
> I should add that none of this stuff is in the ActivityPub spec, which is one reason why we haven't really worked on it yet. It's mostly a nice-to-have that we'll probably dedicate more time to later on, once we're happy with the core state of GtS.

I like the option of admins having the setting of defining a default client, even more so given GTS is mainly targeted at smaller instances, which means instances of 1 (like mine) will be a more regular use case, maybe?

I will try, just for fun, to hardcode the `subscribe` link on my webfinger file, to see what happens

**Comment by tsmethurst** [comment]
Going to close this as won't implement *for now* but we can open it again later if we have time/interest in doing it.
