### ISSUE TITLE
install on debian without Docker

### ISSUE THREAD

**Issue by sysadminpower2019** [superseriousbusiness/gotosocial#1898]
There seem to be no packages for Debian and i don't see any instructions on how to install this directly without docker. 
Is there a way to do so?

**Comment by igalic** [comment]
our releases contain binaries for several platforms, https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.9.0 which you can use as a first start, until somebody contributes a Debian package build

(i say this as the maintainer of the FreeBSD package)

**Comment by tsmethurst** [comment]
Indeed, GoToSocial just releases code, binaries, and docker containers, everything else is up to the generous work of package maintainers :)
