### ISSUE TITLE
[bug] Profile avatars and headers don't get updated

### ISSUE THREAD

**Issue by handlerug** [superseriousbusiness/gotosocial#1899]
### Describe the bug with a clear and concise description of what the bug is.

Profile avatars and headers don't get updated. Very rarely they do update, but most of the time they get stale and then just disappear as they get purged from the media cache.

### What's your GoToSocial Version?

v0.9.0

### GoToSocial Arch

amd64 Binary (Alpine Linux)

### What happened?

Avatars and headers never get updated and eventually disappear as they get purged from the instance's media cache.

### What you expected to happen?

Avatars and headers to get updated.

### How to reproduce it?

1. Dereference a remote profile (so that it gets stored in the database)
2. Wait for the remote profile to update its avatar or header

### Anything else we need to know?

It feels like these two lines are the problem?

https://github.com/superseriousbusiness/gotosocial/blob/d8e16a226a570a7d262bdeb067273ce35b03cc7c/internal/federation/federatingdb/update.go#L94-L95

If the media attachment IDs were unset, `enrichAccount` would handle the update (because it checks whether the updated account model's attachment IDs are empty or not):

https://github.com/superseriousbusiness/gotosocial/blob/d8e16a226a570a7d262bdeb067273ce35b03cc7c/internal/federation/dereferencing/account.go#L424-L433

The first few lines are a no-op (except for `time.Now()`) when the update is triggered by a remote server because `apubAcc` != nil and `latestAcc` gets set to `account`, so `latestAcc.AvatarRemoteURL != account.AvatarRemoteURL` == false, and the media attachment ID is not empty (as shown earlier), so the avatar update logic gets skipped.

Not sure really because sometimes a week or so after disappearing an avatar can come back. It could happen when a user visits the profile and `GetAccountByURI` is called (which does not pass `apubAcc` and triggers a refresh) but that means an update was never sent to the instance..? Complicated…

**Comment by tsmethurst** [comment]
We've got a PR open right now to address this: https://github.com/superseriousbusiness/gotosocial/pull/1853 

It is a very annoying bug!

**Comment by handlerug** [comment]
Ah, got it! I’ve seen it, but avatars and headers weren’t mentioned so I thought it must be something else :)

**Comment by daenney** [comment]
@handlerug We've got a 0.10.0-rc1 out, would you be up for testing it and see if the issue still happens for you?

**Comment by handlerug** [comment]
Avatars and headers stopped disappearing, but they still don't get updated. I've been running the fix for quite a while now, and a bunch of accounts have changed their profile pictures multiple times since then, yet no change occurred on my instance.

**Comment by handlerug** [comment]
I think it got fixed with https://github.com/superseriousbusiness/gotosocial/pull/1984! Seems like a bunch of accounts got their profile pictures actually updated this time.

**Comment by tsmethurst** [comment]
Great!
