### ISSUE TITLE
[bug] Sometimes fetching the timeline fails

### ISSUE THREAD

**Issue by handlerug** [superseriousbusiness/gotosocial#1901]
### Describe the bug with a clear and concise description of what the bug is.

`func=middleware.Logger.func1.1 level=ERROR latency=9.178766ms method=GET statusCode=500 path=/api/v1/timelines/home error="Error #01: HomeTimelineGet: error getting statuses: func2: db error while trying to prepare 01H368DSP8YY1T9QK7XZ1R2BF3: func1: error getting status with id 01H368DSP8YY1T9QK7XZ1R2BF3: \"error populating status parent: no entries\",\"error populating status parent: no entries\"\n" requestID=r5tmkkm8040015hpvp4g msg="Internal Server Error: wrote 54B"`

The status `01H368DSP8YY1T9QK7XZ1R2BF3` indeed has `in_reply_to_id` set to `01H368AXWRHFVK6DWYJ6Q45RTH` which does not exist in the database. The latter is never mentioned in the logs, the former is only mentioned in errors related to home timeline queries.

### What's your GoToSocial Version?

v0.10.0

### GoToSocial Arch

amd64 Binary (Alpine Linux)

### How to reproduce it?

Run the GoToSocial server for a few days, it's bound to happen.

### Anything else we need to know?

This all probably looks too vague to you, so if you need some more concrete data or more logs, let me know.

**Comment by tsmethurst** [comment]
Ahh I've just been investigating an extremely similar problem, to do with replies sometimes getting lost and threads getting broken. This is almost certainly related...

**Comment by handlerug** [comment]
I've been running main for some time with the fix applied. Haven't had any issues until now. I've seen a post in reply to another post, tried to favorite the reply, got the 404 error. Tried to refresh the home timeline, got the 500 error about the very post I tried to favorite. GtS couldn't fetch the parent status of that post; pretty sure the whole two-status thread was deleted. Maybe some mix of interacting and having the post be deleted is handled incorrectly?

**Comment by handlerug** [comment]
Also happens with list timelines:

`timestamp="16/07/2023 13:39:49.359" func=middleware.Logger.func1.1 level=ERROR latency=932.301754ms method=GET statusCode=500 path=/api/v1/timelines/list/01H4GT5JG34T1P1TSDRGKV91AM error="Error #01: ListTimelineGet: error getting statuses: func2: db error while trying to prepare 01H5DNN9RRWG2VX6ECN394ABG1: func1: error getting status with id 01H5DNN9RRWG2VX6ECN394ABG1: \"error populating status parent: no entries\",\"error populating status parent: no entries\"\n" requestID=9b3etqm904000agndky0 msg="Internal Server Error: wrote 54B"`

**Comment by nachtlied1** [comment]
Just adding that I also see the same errors occasionally in both my home and list timelines. (I'm guessing there's some shared code/logic given the API path `/api/v1/timelines`, so the issue probably stems from the same place in the end).

Sort of related, but might have the same root cause:
The `error populating status parent` issue also makes it impossible to delete e.g. orphaned statuses via a client app - since you need to manually search for a specific status URI before being able to delete it.  (Let me know If it would be helpful to create a new issue for this). Example errors:
```
Jul 17 00:46:40 22fe8b55517e gotosocial[1]: timestamp="17/07/2023 00:46:40.867" func=search.(*Processor).Get level=DEBUG maxID="" minID="" limit=20 offset=0 query=https://mydomain.tld/users/myuser/statuses/XXX queryType=statuses resolve=true following=false requestID=w9850rc904001w81xvz0 msg="beginning search"

Jul 17 00:46:40 22fe8b55517e gotosocial[1]: timestamp="17/07/2023 00:46:40.872" func=dereferencing.(*deref).getStatusByURI level=ERROR requestID=w9850rc904001w81xvz0 msg="error populating existing status: \"error populating status parent: no entries\",\"error populating status parent: no entries\""

Jul 17 00:46:40 22fe8b55517e gotosocial[1]: timestamp="17/07/2023 00:46:40.872" func=middleware.Logger.func1.1 level=ERROR latency=6.442228ms userAgent="Tusky/23.0 Android/XX OkHttp/4.11.0" method=GET statusCode=500 path=/api/v2/search clientIP=XX.XX.XX.XX error="Error #01: packageStatuses: error checking visibility of status XXX for account YYY: isStatusVisible: error populating status XXX: \"error populating status parent: no entries\",\"error populating status parent: no entries\"\n" requestID=w9850rc904001w81xvz0 msg="Internal Server Error: wrote 54B"
```

I suppose it might be possible to delete such statuses directly via the API or to zero out `in_reply_to_*` for the statuses in the DB, but I haven't explored either option yet...and these methods seem like they could cause unintended consequences anyway tbh. :)

**Comment by tsmethurst** [comment]
> Also happens with list timelines:
> 
> `timestamp="16/07/2023 13:39:49.359" func=middleware.Logger.func1.1 level=ERROR latency=932.301754ms method=GET statusCode=500 path=/api/v1/timelines/list/01H4GT5JG34T1P1TSDRGKV91AM error="Error #01: ListTimelineGet: error getting statuses: func2: db error while trying to prepare 01H5DNN9RRWG2VX6ECN394ABG1: func1: error getting status with id 01H5DNN9RRWG2VX6ECN394ABG1: \"error populating status parent: no entries\",\"error populating status parent: no entries\"\n" requestID=9b3etqm904000agndky0 msg="Internal Server Error: wrote 54B"`

@handlerug there was a `continue` statement missing which is likely what was causing this particular problem, see https://github.com/superseriousbusiness/gotosocial/pull/1996

**Comment by handlerug** [comment]
I'm on v0.10.0 and the same error just popped up again:

`timestamp="27/07/2023 15:26:42.892" func=middleware.Logger.func1.1 level=ERROR latency=234.465193ms method=GET statusCode=500 path=/api/v1/timelines/list/01H4GT5JG34T1P1TSDRGKV91AM error="Error #01: ListTimelineGet: error getting statuses: func2: db error while trying to prepare 01H6AB5027SWXYBYK37VY7GWS7: func1: error getting status with id 01H6AB5027SWXYBYK37VY7GWS7: \"error populating status parent: no entries\",\"error populating status parent: no entries\"\n" requestID=w6czb5w9040011smwctg msg="Internal Server Error: wrote 54B"`

🤷

**Comment by tsmethurst** [comment]
Have you seen it again recently? :eyes:

**Comment by handlerug** [comment]
I've been off the fediverse lately. During my active GtS usage, I think I was still seeing it a bunch of times, but not as frequently. I follow many accounts, so maybe that's why. This bug report is not very useful in its current form, so I'll close it for now.
