### ISSUE TITLE
[bug] Missing step in the documentation regarding docker?

### ISSUE THREAD

**Issue by grep-fruit** [superseriousbusiness/gotosocial#1911]
### Describe the bug with a clear and concise description of what the bug is.

I might not know enough about what I'm doing but, there's something I don't understand in the documentation, and I don't know where else to ask : 
I am trying to install GTS on a VPS
I followed the instructions on how to install it with a docker container : 
https://docs.gotosocial.org/en/latest/getting_started/installation/container/
I enabled Let's encrypt, uncommented the ports 443:8080, added my domain name, and replaced the ~ in the path to the volumes for "/home/<myuser>" (this last step was to fix a problem creating the database).

Also I added the dns servers of my hosting to my domain name registrar account a few days ago, and `whois` points them to the right dns servers. 

The logs say everything is fine, and I created a user and got the expected output.

Now what I don't understand is that the instructions say : "GoToSocial should now be running on your machine! To verify this, open your browser and go to http://localhost:443. You should see the GoToSocial landing page. Well done!"

However, of course if I go to localhost on my browser there is nothing, since it is not running on my machine, and I've tried to check for localhost inside the VPS but it seems I'm doing it wrong.
What is the configuration step I'm missing for it to resolve to my domain name, or at least to the IP address of the VPS ?

### What's your GoToSocial Version?

3.3

### GoToSocial Arch

Docker

**Comment by grep-fruit** [comment]
I checked the logs again, and it seems to be an SSL problem
```
timestamp="19/06/2023 21:54:15.777" func=router.(*router).Start.func5 level=INFO msg="listening on 0.0.0.0:8080"
2023/06/19 22:08:55 http: TLS handshake error from 193.118.53.194:59944: acme/autocert: missing server name
2023/06/19 22:09:06 http: TLS handshake error from 172.18.0.1:44106: acme/autocert: server name component count invalid
2023/06/19 22:13:04 http: TLS handshake error from 139.59.58.232:41630: tls: first record does not look like a TLS handshake
2023/06/19 22:13:05 http: TLS handshake error from 139.59.58.232:41646: tls: first record does not look like a TLS handshake
2023/06/19 22:13:05 http: TLS handshake error from 139.59.58.232:41654: tls: first record does not look like a TLS handshake
2023/06/19 22:13:06 http: TLS handshake error from 139.59.58.232:41658: acme/autocert: missing server name
2023/06/19 22:13:06 http: TLS handshake error from 139.59.58.232:41668: acme/autocert: missing server name
2023/06/19 22:13:07 http: TLS handshake error from 139.59.58.232:41680: acme/autocert: host "<IP address of the VPS>" not configured in HostWhitelist

2023/06/19 22:13:08 http: TLS handshake error from 139.59.58.232:53280: tls: client requested unsupported application protocols ([http/0.9 http/1.0 spdy/1 spdy/2 spdy/3 h2c hq])
```
So I guess the problem is regarding the SSL certificates?

**Comment by grep-fruit** [comment]
Ive set GTS_LETSENCRYPT_ENABLED to false and re-commented the "80:80" port, and Ive rerun de docker-compose command. I no longer see SSL errors, but it says the instance already exists, which is true I guess. Since I know you can't reuse an instance name, I hope i didn't break this, I don't want to have to use another domain name!

**Comment by tsmethurst** [comment]
Heya, is there a reason you're using v0.3.3 of GoToSocial, or is that a typo? That's a really old version.

Also, I think the thing about opening localhost in the browser should probably be removed, I'm not sure why it's even in there because it doesn't make sense...

Are you able to reach your instance via the domain name you set for it?

**Comment by tsmethurst** [comment]
Btw, I made https://github.com/superseriousbusiness/gotosocial/pull/1913 to fix some of those docs issues, sorry about those!

**Comment by grep-fruit** [comment]
Thanks! 
No i can't reach it via my domain name (and it doesn't answer with dig, so i might be missing something). I'm not sure if it's relevant but, if I look up the IP address of the VPS, I get the apache default page (since I disabled the automatic SSL generation, before that I got an SSL error). Also, there is nothing else on that VPS yet

Also I got confused, the version I'm using is "latest" and the 3.3 is the version number at the top of the docker-compose.yaml file, which I guess might be the version number of the file, and not the version of GTS

**Comment by tsmethurst** [comment]
Did you manage to get things working in the end? :)

**Comment by grep-fruit** [comment]
Not yet!
I managed to get an A entry set up and that seems to work. I still can't access the domain tho, I'm having SSL errors from the fact that GTS initially tried to generate a cert for a domain it wasnt finding. I need to work on fixing that but I haven't had much time to investigate!

thanks for the follow up :)

**Comment by tsmethurst** [comment]
Heya, I'm gonna close this since the docs ambiguities are fixed now. Hope you managed to get your instance working, but if you find another bug in the deployment process please do open another issue for it!

**Comment by grep-fruit** [comment]
thanks!
