### ISSUE TITLE
[bug] Having issues federating with other instances.

### ISSUE THREAD

**Issue by halphalp** [superseriousbusiness/gotosocial#1912]
### Describe the bug with a clear and concise description of what the bug is.

I was recently able to get GoToSocial up and running via Docker and everything seems to initially be working well using Caddy for a reverse proxy.

I'm able to post and have even had accounts on other instances follow me, but I cannot figure out how to follow or add other instances to my account/timeline (I'm running GTS as a single-user instance for just myself so I don't have to moderate other accounts).

One of the specific issues I'm experiencing is when I search for other accounts or instances on Lemmy/Mastodon, they appear with 0 toots, followers, and following, and following them doesn't seem to have an effect. I've tried this on various web and mobile clients, all with the same result.

I'm using the standard reverse proxy example for Caddy provided in the documentation. My config settings are largely unchanged aside from the few fields towards the top of the file that are specific to my instance (domain, host, etc.).

### What's your GoToSocial Version?

v0.9.0 (Latest Docker tag)

### GoToSocial Arch

Docker

**Comment by sandboxgangster** [comment]
I also have the problem with instances that are not yet federated, for me it helps to unfollow, wait a bit and follow again, it usually works all of a sudden, I don't know where exactly it is, but it's not always like that, at some point you also have a better federated instance and the problem takes care of itself.

**Comment by gw31415** [comment]
I have the same issue. I failed to follow users and still on 'follow requested'.

**Comment by gw31415** [comment]
> I have the same issue. I failed to follow users and still on 'follow requested'.

I've solved the problem.
I configured Nginx to redirect htttp to https and now I can follow federated users.

**Comment by Mushus** [comment]
related? https://github.com/misskey-dev/misskey/issues/9435
signToActivityPubGet

**Comment by gw31415** [comment]
Oh, I've realized that I still haven't been able to successfully follow from Misskey and vice versa.

**Comment by natsukagami** [comment]
For Misskey.io specifically (*not* misskey.design nor misskey.art) I think they don't enable authenticated fetch on the instance.
Trying to ask them about it but never got a response :(

**Comment by tsmethurst** [comment]
@halphalp is this still an issue for you?

**Comment by tsmethurst** [comment]
^^ Closed because I can't really replicate this without more info etc. But feel free to open again if you're still having problems and we can try and figure it out!
