### ISSUE TITLE
[feature] Support for UnifiedPush

### ISSUE THREAD

**Issue by raspbeguy** [superseriousbusiness/gotosocial#1922]
### Is your feature request related to a problem ?

For now I receive no notification using GtS.

### Describe the solution you'd like.

There is a now popular standard called [UnifiedPush](https://unifiedpush.org/) that is already adopted by Mastodon and other stuff like Matrix. Basically the clients subscribes to a topic on a pubsub service like [ntfy](https://ntfy.sh/) and requests the server to publish notifications on that topic.

### Describe alternatives you've considered.

NONE

**Comment by tsmethurst** [comment]
related #1350

**Comment by daenney** [comment]
As far as I'm aware, Mastodon doesn't use UnifiedPush, [it uses WebPush](https://docs.joinmastodon.org/methods/push/). Matrix is a little different in that it has the concept of push gateways, one of which could be a UnifiedPush one. Sygnal, the reference Matrix push gateway implements apns and fcm directly.

Given UnifiedPush won't work on iOS but there is WebPush support now which works on both major mobile platforms, I would suggest we close this in favour of #1350. I think the cost of supporting both isn't worth it.

**Comment by daenney** [comment]
I'm going to close this in favour of the WebPush issue. WebPush is  what Mastodon apps support and has support from the dominant mobile operating systems and browsers.
