### ISSUE TITLE
[bug] Internal Server Error fetching Home

### ISSUE THREAD

**Issue by belkadan** [superseriousbusiness/gotosocial#1925]
### Describe the bug with a clear and concise description of what the bug is.

With multiple apps, I get an Internal Server Error trying to fetch my Home timeline. This only started yesterday evening; GoToSocial has been working fine for me prior to that. Looking at the logs I see

`timestamp="25/06/2023 16:20:50.852" func=middleware.Logger.func1.1 level=ERROR latency=142.735179ms userAgent="Mastodon/520 CFNetwork/1335.0.3.2 Darwin/16.1.0" method=GET statusCode=500 path=/api/v1/timelines/home clientIP=192.184.161.62 error="Error #01: HomeTimelineGet: error getting statuses: getXBetweenIDs: db error while trying to prepare 01H3QJCBP8NX693QFGBHN0Y6N2: StatusPrepareFunction: error getting status with id 01H3QJCBP8NX693QFGBHN0Y6N2: \"error populating status parent: no entries\",\"error populating status parent: no entries\"\n" requestID=jpmnqww804001cy2g550 msg="Internal Server Error: wrote 54B"`

Some other errors that happened within the hour before that, in reverse order (with some redactions):

`timestamp="25/06/2023 16:20:22.801" func=dereferencing.(*deref).GetAccountByURI.func1 level=ERROR msg="error fetching account featured collection: GET request to https://mastodonapp.uk/users/[REDACTED]/collections/featured failed: status=\"403 Forbidden\" body=\"{\"error\":\"Forbidden\"}\""`

`2023/06/25 16:17:40 http: TLS handshake error from 172.104.249.106:49194: acme/autocert: missing server name`
`2023/06/25 16:17:36 http: TLS handshake error from 5.112.169.165:59599: read tcp 172.19.0.2:8080->5.112.169.165:59599: i/o timeout`

`timestamp="25/06/2023 16:10:26.921" func=dereferencing.(*deref).GetAccountByURI.func1 level=ERROR msg="error fetching account featured collection: GET request to https://mstdn.social/users/[REDACTED]/collections/featured failed: status=\"403 Forbidden\" body=\"{\"error\":\"Forbidden\"}\""`
`timestamp="25/06/2023 16:10:26.743" func=dereferencing.(*deref).enrichAccount level=ERROR requestID=74g55ww804001kb0v63g msg="error webfingering[2] remote account [REDACTED]@mstdn.social: fingerRemoteAccount: error fingering @[REDACTED]@mstdn.social: account has been deleted/is gone"`

`timestamp="25/06/2023 15:51:55.586" func=dereferencing.(*deref).GetAccountByURI.func1 level=ERROR msg="error fetching account featured collection: GET request to https://mastodon.social/users/[REDACTED]/collections/featured failed: status=\"410 Gone\" body=\"{\"error\":\"Gone\"}\""`

`timestamp="25/06/2023 15:49:47.053" func=dereferencing.(*deref).GetAccountByURI.func1 level=ERROR msg="error fetching account featured collection: GET request to https://det.social/users/[REDACTED]/collections/featured failed: status=\"403 Forbidden\" body=\"{\"error\":\"Forbidden\"}\""`
`timestamp="25/06/2023 15:49:46.877" func=dereferencing.(*deref).enrichAccount level=ERROR requestID=mmtkzww804000avmtqgg msg="error webfingering[2] remote account[REDACTED]@det.social: fingerRemoteAccount: error fingering @[REDACTED]@det.social: account has been deleted/is gone"`

`timestamp="25/06/2023 15:49:28.326" func=dereferencing.(*deref).populateEmojis level=ERROR msg="couldn't get remote emoji flag_rainbow@tech.lgbt: error reading incoming media: unexpected EOF"`

I would hope that none of these relatively expected events would cause the main problem but just in case…

Let me know if there's any other information I can provide, or test commands I can run on my instance.

### What's your GoToSocial Version?

v0.9.0

### GoToSocial Arch

x86_64 Docker

**Comment by belkadan** [comment]
This has fixed itself today after I posted something; I'm not sure if that was related or not.

**Comment by tsmethurst** [comment]
I believe we've already fixed this on main, so a fix should be in the next release :)

**Comment by belkadan** [comment]
I'm afraid it has, here's a new log:

```
gotosocial  | timestamp="31/07/2023 22:45:08.241" func=middleware.Logger.func1.1 level=ERROR latency=5.027035ms userAgent="Mastodon/555 CFNetwork/1335.0.3.4 Darwin/22.4.0" method=GET statusCode=500 path=/api/v1/timelines/home clientIP=192.184.161.62 error="Error #01: HomeTimelineGet: error getting statuses: func2: db error while trying to prepare 01H6J8VW78CZM6P9DDSY8Q0V5V: func1: error getting status with id 01H6J8VW78CZM6P9DDSY8Q0V5V: \"error populating status parent: no entries\",\"error populating status parent: no entries\"\n" requestID=1hq21bm904001qq85p4g msg="Internal Server Error: wrote 54B"
```

Looks like the function names got lost but otherwise it's equivalent. This happened over the weekend and then fixed itself, and I elicited it now by trying to Load More (earlier) in my timeline, so presumably it's the fault of some particular incoming status.

I'm moderately technical, so if you want to give me something to run in the Docker container or against the SQLite database I'm happy to try it out to see what's weird about "01H6J8VW78CZM6P9DDSY8Q0V5V".

**Comment by daenney** [comment]
That might be interesting. For the database it would be `SELECT * FROM statuses WHERE id = '01H6J8VW78CZM6P9DDSY8Q0V5V'

**Comment by NyaaaWhatsUpDoc** [comment]
I'd also be interested to know when that status first originated. If it's an older one (i.e. 3+ months old), and a load of its URI in the search bar fixes this parent ID issue, then it would indicate this is just remnants of older bugs (and not something to worry about, since new code fixes it when it fetches the latest version).

**Comment by tsmethurst** [comment]
Ahh I think I know why these are cropping up...

When a status parent gets deleted, various parts of PopulateStatus will fail. This is expected and normal. But we return those errors by appending them all to a `gtserror.MultiError`, and then returning the `Combine`d version. The `Combine` function looks like this:

```go
// Combine converts this multiError to a singular error instance, returning nil if empty.
func (e MultiError) Combine() error {
	if len(e) == 0 {
		return nil
	}
	return errors.New(`"` + strings.Join(e, `","`) + `"`)
}
```

Unfortunately, in order to check for `db.ErrNoEntries` we do an `errors.Is()` call on the combined error, which doesn't work because the wrapped errors have been flattened by the combination process into just normal string errors.

So! We probably need to slightly adjust the way we do this error wrapping + combination in order to preserve some information about the contained errors, so that `errors.Is` will still work properly!

**Comment by tsmethurst** [comment]
Started working on this here: https://github.com/superseriousbusiness/gotosocial/tree/multierror_changes

**Comment by belkadan** [comment]
That analysis sounds plausible. Just to add evidence, here's the (redacted) entry in question:

`01H6J8VW78CZM6P9DDSY8Q0V5V|2023-07-30 [REDACTED]+00:00|2023-07-30 [REDACTED]+00:00|https://mastodon.social/users/[REDACTED]/statuses/[REDACTED]|https://mastodon.social/@[REDACTED]/[REDACTED]|<p>[REDACTED]</p>|[]|null|[]|[]|0|01GS1CFNJHPE3A8MWS0KXH3S1K|https://mastodon.social/users/[REDACTED]|01H6J8V1VGHQVDW8JJVWPQ1XSN|https://mastodon.social/users/[REDACTED]/statuses/[REDACTED]|01GS1CFNJHPE3A8MWS0KXH3S1K||||public|0|||Note||1|1|1|1||2023-07-30 [REDACTED]+00:00`

And indeed, would-be `in_reply_to_id` `01H6J8V1VGHQVDW8JJVWPQ1XSN` is not in the database.
