### ISSUE TITLE
[bug] Servers behind NAT64 cannot reach v4 servers due to blocking

### ISSUE THREAD

**Issue by eeeeeta** [superseriousbusiness/gotosocial#1940]
### Describe the bug with a clear and concise description of what the bug is.

The NAT64 range `64:ff9b::/96` cannot be used with GoToSocial, because it is [explicitly blocked](https://github.com/superseriousbusiness/gotosocial/blob/2a40c81f105d592ee474dd28fe8a7fdc31cb73f1/internal/netutil/validate.go#L31) as a 'reserved range'. 

This seems inadvisable, given servers behind a standards-compliant NAT64 (like my testing instance at `gotosocial.i.eta.st`) won't be able to federate at all with v4-only servers due to this.

### What's your GoToSocial Version?

0.9.0 git-282be6f

### GoToSocial Arch

amd64 binary

### What happened?

Interacting with some users fails, e.g.

```
Jul 03 00:17:10 gotosocial gotosocial[3114]: timestamp="03/07/2023 00:17:10.353" func=dereferencing.(*deref).fetchStatusMentions level=ERROR msg="failed to dereference account https://birb.site/users/charlag: item could not be retrieved: enrichAccount: error deferencing https://birb.site/users/charlag: Get \"https://birb.site/users/charlag\": dial tcp [64:ff9b::b01f:d5e7]:443: dial within blocked / reserved IP range"
```

### What you expected to happen?

The server federated as normal

**Comment by tsmethurst** [comment]
We're cooking something up to add exceptions in such cases, so folks can override the reserved ranges :)

**Comment by igalic** [comment]
I think, all the address ranges in this table https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml that are globally reachable should definitely not be on that list to begin with

**Comment by tsmethurst** [comment]
Ack, will review the defaults as well in that case and make sure we're not blocking anything we oughtn't
