### ISSUE TITLE
[bug] Media upload using Tokodon client fails

### ISSUE THREAD

**Issue by Ghabry** [superseriousbusiness/gotosocial#1944]
### Describe the bug with a clear and concise description of what the bug is.

Attaching media files using "Tokodon" fails with invalid request 400.

### What's your GoToSocial Version?

main

### What happened?

Tokodon sends media using ``Content-Disposition: attachment; name="file"; filename="NAME.png"``

What gotosocial expects is ``Content-Disposition: form-data; name="file"; filename="NAME.png"``

Patching Tokodon to use ``form-data`` fixes the media upload (tested pictures and videos) so this is indeed the issue.

Question is if this is a bug in Tokodon or in gotosocial and how hard it is to implement a workaround in gotosocial.

I have no knowledge in go so I cannot figure it out. No idea how to convince ``File *multipart.FileHeader form:"file" binding:"required"`` of ``AttachmentRequest`` to accept ``attachment``.

**Comment by Ghabry** [comment]
Hm and a kinda related issue happens when uploading an avatar or a banner for the profile. Here gotosocial requires this header: ``Content-Disposition: form-data; name="avatar"; filename="XXXXX"`` but Tokodon sends ``Content-Disposition: form-data; name="avatar"`` without the ``filename`` component. This also results in 400.

**Comment by tsmethurst** [comment]
Hmm, looking at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition makes me think this is likely a bug in Tokodon, since it seems according to the reference that `attachment` should be used in response headers, not in request headers. Worth opening an issue with Tokodon to get their input too I think.

**Comment by Ghabry** [comment]
Hm yeah that sounds more like a Tokodon bug.

I will report back when I received any feedback from them.

**Comment by daenney** [comment]
> Hm and a kinda related issue happens when uploading an avatar or a banner for the profile. Here gotosocial requires this header: `Content-Disposition: form-data; name="avatar"; filename="XXXXX"` but Tokodon sends `Content-Disposition: form-data; name="avatar"` without the `filename` component. This also results in 400.

This second one is a bug on our side. `filename` is optional so we should be able to handle the lack of it.

**Comment by tsmethurst** [comment]
Ah thanks @daenney, i missed that part.

**Comment by Ghabry** [comment]
The issue was resolved in tokodon. I will open another issue here for the second bug.
