### ISSUE TITLE
Is there a feature to delete users?

### ISSUE THREAD

**Issue by huabin** [superseriousbusiness/gotosocial#1945]
Hello there,

I want to delete a user and the posts under it, how do I do that?

Thank you.

**Comment by tsmethurst** [comment]
Hiya

Log in to the admin/settings panel as an admin, then under 'moderation -> accounts' you can search for an account using its namestring (`@someone@example.org`) and suspend that account (which is functionally equivalent to deleting it).

Alternatively, if it's your account you want to remove, you can use the `/api/v1/accounts/delete` API endpoint, see here: https://docs.gotosocial.org/en/latest/api/swagger/

**Comment by tsmethurst** [comment]
> its profile still exists and can be accessed

On your instance, or from a remote instance? Suspended users should no longer be visible from your instance, so if they are that sounds like a bug. Suspending should also remove posts from that user :thinking: 

If you want to actually send a Delete message across activitypub, the account owner has to delete the account themselves currently, using the api endpoint I mentioned. Definitely not ideal behavior and something we need to improve.

**Comment by huabin** [comment]
I can visit the Suspended users' page, such as https://domain.com/@suspended_user_name, and I got this

![error](https://github.com/superseriousbusiness/gotosocial/assets/535675/0b888caf-8c5b-481f-8cb2-d469cf26a8d1)

Actually, I would like to get 404 error page instead of this.

I will learn and try the other you gave, thank you so much.

**Comment by huabin** [comment]
Hello @tsmethurst ,

I tried, but it told me this, how can I get the token?

![Screenshot 2023-07-05 at 7 54 30 PM](https://github.com/superseriousbusiness/gotosocial/assets/535675/81971e5b-1271-41e7-aa09-cbef4432af7e)

Thank you.

**Comment by sandboxgangster** [comment]
@huabin z.b. https://web.grautier.com/apikey/ (hosted by Me) or https://takahashim.github.io/mastodon-access-token/ (Hostet by the Projekt)

**Comment by tsmethurst** [comment]
Another alternative for getting a token: press f12 in your browser to view your network requests, log into the settings panel; look in your network requests for a request that has request header `Authorization: Bearer SOME_TOKEN_VALUE` -- that `SOME_TOKEN_VALUE` is the token you need.

**Comment by tsmethurst** [comment]
https://github.com/superseriousbusiness/gotosocial/pull/1954 <- 404 web profiles of suspended users

**Comment by huabin** [comment]
@sandboxgangster @tsmethurst Thank you so much.



> #1954 <- 404 web profiles of suspended users

But it seems doesn't work. @tsmethurst

**Comment by huabin** [comment]
@tsmethurst Sorry to trouble you again, how to restore a suspended user? I logged into the admin cp, and find no way to restore a suspended user. Thank you.

**Comment by tsmethurst** [comment]
iirc at this point it's not possible to restore a suspended user

by the way, for ongoing discussions/help questions like this, as opposed to bug reports / feature requests, it might be better if you join our matrix space

**Comment by huabin** [comment]
Got it, thank you so much.

**Comment by tsmethurst** [comment]
No problem. Can I close this issue now, since the original question has now been answered?

**Comment by huabin** [comment]
Sorry, done.
