### ISSUE TITLE
[bug] Federated with misskey.io

### ISSUE THREAD

**Issue by Mushus** [superseriousbusiness/gotosocial#1949]
### Describe the bug with a clear and concise description of what the bug is.

Hello, I would like to discuss a problem I am having with federation with misskey.io.
I am aware that this may not be a bug.
I am running a server using gotosocial.
I want to federate with misskey.io, but the connection is not established because gotosocial returns unauthorized.

### What's your GoToSocial Version?

revision: https://github.com/superseriousbusiness/gotosocial/commit/d9c69f6ce05daddf2f6d5d8c6c03b4c3d55df93a

### GoToSocial Arch

amd64 go1.20.5

### What happened?

When I send a follow request to a user on misskey.io they will not see it because the notification never reaches them. Also, searching for my own user on misskey.io will not show the remote user's page on gotosocial because the misskey.io user page returns an internal server error response.

misskey.io user page: https://misskey.io/@[username]@[hostname]

According to my review of misskey's source code,
When misskey responds to a remote user's page, it appears that misskey sends an http request to gotosocial equivalent to the following curl command

```
curl https://[host]/@[username] -H "Accept: application/activity+json, application/ld+json"
```

When you request that command, gotosocial returns the following response
As a result, the remote user's page on misskey returns an internal server error.

```
{"error": "Unauthorized: http request wasn't signed or http signature was invalid"}
```

Similarly, sending a request to misskey.io returns the following response.
```
curl https://misskey.io/@[username] -H "Accept: application/activity+json, application/ld+json"
```

```
{
    "@context": [
        "https://www.w3.org/ns/activitystreams",
        "https://w3id.org/security/v1",
        {
            "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
            "sensitive": "as:sensitive",
            "Hashtag": "as:Hashtag",
            "quoteUrl": "as:quoteUrl",
            "toot": "http://joinmastodon.org/ns#",
            "Emoji": "toot:Emoji",
            "featured": "toot:featured",
            "discoverable": "toot:discoverable",
            "schema": "http://schema.org#",
            "PropertyValue": "schema:PropertyValue",
            "value": "schema:value",
            "misskey": "https://misskey-hub.net/ns#",
            "_misskey_content": "misskey:_misskey_content",
            "_misskey_quote": "misskey:_misskey_quote",
            "_misskey_reaction": "misskey:_misskey_reaction",
            "_misskey_votes": "misskey:_misskey_votes",
            "isCat": "misskey:isCat",
            "vcard": "http://www.w3.org/2006/vcard/ns#"
        }
    ],
    "type": "Person",
    "id": "http://.../users/...",
    "inbox": "http://.../users/.../inbox",
    "outbox": "http://.../users/.../outbox",
    "followers": "http://.../users/.../followers",
    "following": "http://.../users/.../following",
    "featured": "http://.../users/.../collections/featured",
    "sharedInbox": "http://.../inbox",
    "endpoints": {
        "sharedInbox": "http://.../inbox"
    },
    "url": "http://.../@[username]",
    "preferredUsername": "[mushus]",
    "name": null,
    "summary": null,
    "icon": null,
    "image": null,
    "tag": [],
    "manuallyApprovesFollowers": false,
    "discoverable": true,
    "publicKey": {
        "id": "https://.../users/...#main-key",
        "type": "Key",
        "owner": "http://.../users/...",
        "publicKeyPem": "-----BEGIN PUBLIC KEY-----\n...==\n-----END PUBLIC KEY-----\n"
    },
    "isCat": false
}
```

### What you expected to happen?

gotosocial can establish a federation with misskey.io.
To do so, gotosocial needs to return a response similar to that of misskey with the status code 200.

### How to reproduce it?

execute `curl https://[host]/@[username] -H "Accept: application/activity+json, application/ld+json"`

### Anything else we need to know?

I am not familiar with ActivityPub, so I don't know if this behavior of gotosocial is right or wrong as a standard specification.
It may be possible that misskey.io is behaving improperly as an ActivityPub.

**Comment by tsmethurst** [comment]
Heya, this is an issue with misskey.io: they don't have authorized fetch enabled, so their GET requests to GtS are not signed. I believe this has already been changed in the misskey code so that GETs will be signed by default. This should be resolved either by misskey.io enabling the setting in their config to turn on signed GETs, or by them eventually upgrading to a version where this is the default. In the meantime, there's not much to do from GoToSocial's side so I'm gonna close this issue.

**Comment by laozhoubuluo** [comment]
For Misskey or its simple modified version, `signToActivityPubGet` configuration should manually set `true` to interact some instances normally. The latest recommended configuration is `true` but default is `false`, which will cause this problem. 
For site administrators, you should check whether the Misskey configuration is correct. For site users, please refer this issue to the administrator, who will confirm whether Misskey is configured correctly.

Details: https://github.com/misskey-dev/misskey/issues/8093
