### ISSUE TITLE
[bug] Error 500 for RSS feed without posts

### ISSUE THREAD

**Issue by LukeLambert** [superseriousbusiness/gotosocial#1951]
### Describe the bug with a clear and concise description of what the bug is.

If a profile doesn't have any posts, the RSS feed will return a 500: Internal Server Error instead of a valid rss+xml document with no entries. This will cause issues with feed readers if someone tries to subscribe before there are any posts, or if a user deletes all their posts.

Log:
```
method=GET
statusCode=500
path=/@luke/feed.rss
error="Error #01: GetRSSFeedForUsername: db error: no entries\n"
```

### What's your GoToSocial Version?

0.9.0

### GoToSocial Arch

arm64 Docker

**Comment by tsmethurst** [comment]
Whoops, thanks

**Comment by daenney** [comment]
This comes from https://github.com/superseriousbusiness/gotosocial/blob/672386a1b9a194cfe7493fe33a9b8d2742cdcb53/internal/processing/account/rss.go#L35-L57

Unfortunately, we emit that same error message 3 times, but my guess is that it came from `GetAccountLastPosted` and that's where we perhaps need an additional error value to signal that there hasn't been a status yet.

**Comment by tsmethurst** [comment]
I've got a fix on a branch already, which also refactors some of the messy RSS logic a bit. Will include it in 0.10.0 proper!
