### ISSUE TITLE
[bug] Codeblocks break responsivness of the page

### ISSUE THREAD

**Issue by web110010** [superseriousbusiness/gotosocial#1952]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

Inside a codeblock if the text is too long on one specific line the length of **all** the posts increase with it.
![chromium](https://github.com/superseriousbusiness/gotosocial/assets/137025268/ade82951-f95d-4ef3-b1fb-db86de66c9c5)

### What's your GoToSocial Version?

GoToSocial 0.9.0 git-282be6f

### Browser version

Mozilla Firefox(fedora) 115.0, Chromium(flatpak) 114.0.5735.198, Firefox for android, Chrome for android

### What happened?

I was trying out what works for markdown, support for extended syntax elements(which isn't completely there yet), when I noticed that that due to the codeblock the recent posts were pulled bellow the About section. So I opened it on my phone to check it and the page wasn't readable on the phone.

A little investigation into it and the culprit was a line of code which was pretty long inside the codeblock.
This seems to happen with both the basic(4 spaces or 1 tab indentation) and extended(code between (```)) markdown syntax.

### What you expected to happen?

One of two things:

- line wrapping (not at all desirable)
- a scroll bar specific to codeblock to appear allowing for scrolling the codeblock (this is what I hoped for)

### How to reproduce it?

A long line of code inside a codeblock.

**Comment by tsmethurst** [comment]
Ah right this bug! Thanks! Forgot to open an issue for it earlier.
