### ISSUE TITLE
[feature] SemVer version in /api/vX/instance and /nodeinfo/2.0

### ISSUE THREAD

**Issue by VyrCossont** [superseriousbusiness/gotosocial#1953]
### Is your feature request related to a problem ?

As a client dev, I would like to know approximately which version of GotoSocial I'm talking to, so that I can enable or disable my client's features as necessary (search, lists, etc.). Right now, if I run my GtS instance off `main`, the version fields in `/api/v1/instance`, `/api/v2/instance`, and `/nodeinfo/2.0` are a build identifier like `git-2a40c81`. This doesn't tell my client much.

### Describe the solution you'd like.

I suggest changing this so that builds off `main` or other Git branches (as opposed to version tags) are marked as [SemVer pre-release versions](https://semver.org/#spec-item-9) of whatever version's next on the roadmap, with the Git revision attached as [SemVer build metadata](https://semver.org/#spec-item-10). This would make my example version into `0.10.0-git+2a40c81`.

I can parse that with any SemVer library and then compare it to a known version like `0.9` to decide whether to enable (for example) profile field editing, subscriptions, and extra trans rights.

### Describe alternatives you've considered.

One way to do feature detection is to just call an API and see if it works, but not all APIs can be called safely just to test them, and being able to `HEAD` or `GET` an HTTP API doesn't necessarily tell you what methods, options, inputs, etc. can be used.

Another way is to have feature detection flags with names and add those to `instance` or `nodeinfo` APIs, which is what Pleroma and Akkoma do, and to some extent what the Mastodon-compatible `instance` API's cross-platform `configuration` object is for, but then someone has to name all of the features explicitly.

**Comment by tsmethurst** [comment]
Mm yes, good one. If you build with `goreleaser` it does present something closer to what you're looking for -- `0.9.1-SNAPSHOT git-df39a13` in the case of the current deployment of goblin.technology -- but indeed if you build using `go build` or `./scripts/build.sh` it doesn't work that way. Will try to find some time to address this once 0.10.0 is out.

**Comment by tsmethurst** [comment]
Oh actually if you do `./scripts/build.sh` it should be injecting the version into the build via the following line:

`GO_LDFLAGS="${GO_LDFLAGS-} -s -w -extldflags '-static' -X 'main.Version=${VERSION:-$(git describe --tags --abbrev=0)}'"`

But that only uses the most recent git tag, it doesn't assume snapshot of the next version.

**Comment by VyrCossont** [comment]
Thanks for looking into this. Sounds like using goreleaser is the way to go meanwhile.

**Comment by VyrCossont** [comment]
Followup: goreleaser needs a fair bit of infra so what I actually ended up doing for now is setting the numeric version manually with `VERSION=0.10.0rc1 ./scripts/build.sh`.

**Comment by tsmethurst** [comment]
> goreleaser needs a fair bit of infra

Hah yes that's fair, it really does the whole build start to finish. V convenient for CI, less so for humans

**Comment by nikclayton** [comment]
+1

I need this for Pachli, where features (like support for filters) will be enabled/disabled based on what the server reports, falling back to versions comparisons.

Right now the reported version info is not semver compatible; e.g., https://gts.superseriousbusiness.org/api/v2/instance reports `0.13.1 git-ccecf5a` as the version number, which does not follow https://semver.org/ (`0.13.1+git-ccecf5a` would).

**Comment by VyrCossont** [comment]
I've special-cased GtS version parsing in Feditext for the same reasons as Pachli (feature gating), but I think a one-character change would fix this in the important cases:

`0.13.1-SNAPSHOT git-b6fe8e7` (today's `goreleaser`-built `goblin.technology` version) would become `0.13.1-SNAPSHOT+git-b6fe8e7`: version `0.13.1`, pre-release identifier `SNAPSHOT`, build tag `git-b6fe8e7`.

`0.13.2 git-2c95cfb` (today's `./scripts/build.sh`-built `princess.industries` version) would become `0.13.2+git-2c95cfb`: version `0.13.2`, no pre-release identifier, build tag `git-b6fe8e7`.

`0.13.2` with no metadata would remain `0.13.2`.

Builds doing a bare `go build ./cmd/gotosocial` or `go run ./cmd/gotosocial` would end up with something like `git-ca53e9e`, which is not valid SemVer. However, `CONTRIBUTING.md` says to use `build.sh` except for the `nodemon` automatic re-compiling example, so you're only ever going to hit that problem in development workflows. (Or if you forget to fetch tags from upstream and `build.sh` ends up with no tags for `git describe` to use.)
