### ISSUE TITLE
[feature] Use Hugo for documentation

### ISSUE THREAD

**Issue by web110010** [superseriousbusiness/gotosocial#1957]
### Is your feature request related to a problem ?

I was looking into contributing to the documentation, then I read the `CONTRIBUTING.md` , cloned the repo, then installed conda (fedora rpm), tried running, failed, then removed conda, installed the miniconda linked in `CONTRIBUTING.md` installed it and run, ok it works now. Added a file, it doesn't show in the navbar, took 10 minutes to figure out mkdoc.yml which is outside the docs folder is where I should link the webpage.

Problems with how docs are done currently
- Slow
- Pain to add files
- Python (Nothing against python, but if main project is in go, why not use something from go for documentation)

### Describe the solution you'd like.

Just a simple documentation which is simple to modify, fast and doesn't involve installing miniconda.

Why Hugo?
- Fast (blazingly fast!!)
- golang
- simple

### Describe alternatives you've considered.

NONE

### Additional context.

If you do consider it, I converted most(almost all, it was pretty simple) of the documentation into a hugo site for you to try. The api page with swagger is a bit broken(was on dark mode, ok on light mode), I tried fixing the css and its passable on both dark and light mode.

the code is hosted here https://github.com/web110010/gtsdocs
and the demo site: https://c20e1cec.gtsdocs.pages.dev/

If you do decide on it, the theme [hugo-book](https://github.com/alex-shpak/hugo-book) has a lot of features and you should look into it. Also, I choose hugo-book cause it didn't have any other dependencies, whereas docsy (which seems to be the most popular theme for docs) and others had other requirements, such as needing some npm packages.

I you want to use the above site as a base just clone the repo and add it your project. I will kill the website ~1 week.

**Comment by tsmethurst** [comment]
We're pretty happy with how the docs work right now, don't think we'll be switching to Hugo any time soon, but thanks!
