### ISSUE TITLE
[bug] Avatar and Banner upload fails when using Tokodon

### ISSUE THREAD

**Issue by Ghabry** [superseriousbusiness/gotosocial#1958]
### Describe the bug with a clear and concise description of what the bug is.

Tokodon sends `` Content-Disposition: form-data; name="avatar" `` when uploading an Avatar.

gotosocial expects ``Content-Disposition: form-data; name="avatar"; filename="XXXXX"``

As concluded in #1944 ``filename`` is optional so this is a bug.

Same applies to the profile banner upload.

--------

This sounds simple to fix but I cannot figure out what to change in the struct definition as there is a huge lack of documentation in gin-gonic.

### What's your GoToSocial Version?

latest

**Comment by NyaaaWhatsUpDoc** [comment]
Unfortunately this comes down to a rather brittle binding API in `gin-gonic` and bad `mime/multipart` standard library behaviour on Go's part (see: https://github.com/golang/go/issues/19183). So unfortunately without getting _really_ hacky, (I started working on this and will require a lot of extra request data juggling without...), it's not going to be possible.

I did take a look at alternative 3rd-party libraries but they all seem to be not-battle-tested and unmaintained (see: https://github.com/albrow/forms, https://github.com/neox5/go-formdata).

Is Tokodon able to include the filename in the request? I understand this isn't an ideal situation, so if not I can continue digging to create some sort of workaround / `mime/multipart` patch, but I just wanted to check.

**Comment by f0x52** [comment]
just adding this probably also applies to custom emoji uploads and domain block imports, iirc that's all our file upload routes

**Comment by Ghabry** [comment]
Yes, I can submit a patch to Tokodon. Sounds easier than working around go limitations.

Last time they were very happy about fixes for servers other than Mastodon. :)

**Comment by tsmethurst** [comment]
Hey @Ghabry , do you know if this has been updated in Tokodon?

**Comment by tsmethurst** [comment]
Going to close this since we decided it was not something that we could fix on our side without big hacky workarounds. It doesn't look like it's been fixed in Tokodon either yet unfortunately, but that's life!

**Comment by Ghabry** [comment]
A fix was merged today into Tokodon. (Sorry for the delay :))
