### ISSUE TITLE
TestFingerWithHostMetaCacheStrategy is flaky

### ISSUE THREAD

**Issue by MaeIsBad** [superseriousbusiness/gotosocial#1980]
### Describe the bug with a clear and concise description of what the bug is.
TestFingerWithHostMetaCacheStrategy randomly fails

With no code changes: 
- fail: https://drone.superseriousbusiness.org/superseriousbusiness/gotosocial/6608/1/3
- fail: https://drone.superseriousbusiness.org/superseriousbusiness/gotosocial/6607/1/3
- pass: https://drone.superseriousbusiness.org/superseriousbusiness/gotosocial/6609/1/3

### What's your GoToSocial Version?

ca5492b65f45c7db8a9cfb767b0b48aa6cf6fe24

**Comment by tsmethurst** [comment]
I'm gonna close this for now since the test is now disabled!
