### ISSUE TITLE
[bug] Passwords > 72 chars cause havoc that needs DB access to recover

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2003]
### Describe the bug with a clear and concise description of what the bug is.

I’ve attempted to `admin account create` a user account for a bot, with a loooong (autogenerated, random) password. I got:

    2023/07/19 19:01:24 error executing command: error hashing password: bcrypt: password length exceeds 72 bytes

Unfortunately, neither a subsequent `admin account create` with a shorter password…

    2023/07/19 19:02:05 error executing command: username «censored» is already in use

… nor `admin account password` to set/change it…

    2023/07/19 19:02:41 error executing command: no entries

… could succeed.

----

To allow a subsequent `admin account create` to proceed, I had to hack around this on the DB level:

    gotosocial=# SELECT * FROM accounts WHERE username='«censored»';
    gotosocial=# DELETE FROM accounts WHERE id='…';

Inspection had shown that the newly created user already had a row in the `accounts` table but not in the `user` table. I hope I did not miss any others to clean up.

### What's your GoToSocial Version?

0.9.0 git-282be6f

### GoToSocial Arch

amd64 binary

### What happened?

see above

### What you expected to happen?

password hashing can take arbitrarily long inputs

### How to reproduce it?

I *was* going to say…

    $ setuidgid _gts /opt/GtS/gotosocial --config-path /opt/GtS/config.yaml admin account create --username foo --email bar@example.com --password xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

… but that yielded a different error…

    2023/07/19 19:34:46 error executing command: password is only 15% strength, try including more special characters, using uppercase letters, using numbers or using a longer password

… so I guess choose a random long pw…

    $ setuidgid _gts /opt/GtS/gotosocial --config-path /opt/GtS/config.yaml admin account create --username foo --email bar@example.com --password 70F85RjI3DPWcteNF9ACV5UO2PhCguaXZiQDVhXfhRazUWXmpYrTVfvGJfFtUW0JUv8v3JoUXxpV8hgyMhm9CYXsEAoM6trY605

**Comment by tsmethurst** [comment]
> password hashing can take arbitrarily long inputs

Unfortunately the bcrypt algorithm that we use for hashing passwords, for better or worse, supports only a maximum length of 72 bytes as a limitation of the algorithm itself. This is something Mastodon has also had discussion about: https://github.com/mastodon/mastodon/issues/25390

So we could pre-hash passwords before feeding them into bcrypt ([not recommended](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pre-hashing-passwords)), we could switch to a different hashing algorithm that allows more than 72 bytes, or we could truncate bytes after 72 (extremely bad idea).

I think at least workable things that we can do right now are: 1) limiting max password bytes to 72 and checking it earlier + returning a more helpful error when creating users and 2) fixing the bug whereby an account gets created but not a user.

**Comment by tsmethurst** [comment]
Gonna close this one now, since we've changed the max password length to 72 bytes!
