### ISSUE TITLE
[bug] Lists view doesn't show list members

### ISSUE THREAD

**Issue by decentral1se** [superseriousbusiness/gotosocial#2006]
### Describe the bug with a clear and concise description of what the bug is.

Loving the lists feature, thanks! 

On Tusky, when I edit a list, I don't get a listing of who is in the list. I think I only see the last person I added to the list. When I search for handles that I already have added to the list, I can add them again - there is no indication that they're already in the list.

### What's your GoToSocial Version?

v0.10.0-rc3

### GoToSocial Arch

am64 binary

### What happened?

I only see the last person I added to the list (I think).

### What you expected to happen?

See list membership with markers to "in" (x)" and "not in" (tick to add). That's mostly Tusky specific UI but I assume other apps will use markers to render who is in / out in similar ways.

### How to reproduce it?

- Create a list on Tusky
- Add a bunch of people
- Edit the list

### Anything else we need to know?

Otherwise, it seems to be working pretty good :heart:

**Comment by tsmethurst** [comment]
Ahh yes we've seen the same thing, it's weird isn't it? Will investigate, thank you!

**Comment by tsmethurst** [comment]
This seems particular to Tusky, right? I haven't seen it on other clients

**Comment by decentral1se** [comment]
@tsmethurst potentially! i can't actually see any way to view the list membership on semaphore which is the other client I use... opened https://github.com/NickColley/semaphore/discussions/70 to track that. Sorry can't be of more help rn

**Comment by tsmethurst** [comment]
It's cool, no worries! I found the issue, PR incoming this afternoon :)
