### ISSUE TITLE
[bug] 400 when posting with long Content Wrapper

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2010]
### Describe the bug with a clear and concise description of what the bug is.

When posting with a long Content Wrapper, I get a 400 Bad Request.

### What's your GoToSocial Version?

0.10.0-rc3 git-f431974

### GoToSocial Arch

amd64 binary

### What happened?

    timestamp="21/07/2023 00:15:26.682" func=middleware.Logger.func1.1 level=INFO latency=7.679414ms userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" method=POST statusCode=400 path=/api/v1/statuses requestID=t8kwtxc9040006g7emrg msg="Bad Request: wrote 115B"

### What you expected to happen?

This to post. Otherwise, give a sensible error message and document CW upper limit.

### How to reproduce it?

Create a new toot (e.g. in Semaphore) with body `test`, enable Content Wrapper, fill it with `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`

**Comment by trysdyn** [comment]
The CW upper limit is configurable via the config directive `status-cw-max-chars` but when I hit this I was confused at first too (actually my confusion was over media description size, but same concept).

I wonder if we can bubble a plaintext error through to the client to display somehow.

**Comment by mirabilos** [comment]
Trysdyn Black dixit:

>The CW upper limit is configurable via the config directive
>`status-cw-max-chars`

It is?

There’s no status-cw-max-chars in config.yaml though.

bye,
//mirabilos
-- 
22:20⎜<asarch> The crazy that persists in his craziness becomes a master
22:21⎜<asarch> And the distance between the craziness and geniality is
only measured by the success 18:35⎜<asarch> "Psychotics are consistently
inconsistent. The essence of sanity is to be inconsistently inconsistent

**Comment by tsmethurst** [comment]
> I wonder if we can bubble a plaintext error through to the client to display somehow.

We already do, if I remember rightly, it's just that most clients don't actually show the errors we return unfortunately.

> There’s no status-cw-max-chars in config.yaml though.

https://github.com/superseriousbusiness/gotosocial/blob/95e2024c2a86833d043470ec7c0a87424a93e2d9/example/config.yaml#L577-L581

**Comment by mirabilos** [comment]
Ah, status*es*. Thanks!

**Comment by tsmethurst** [comment]
Should I close this one now then? I suppose there's still an argument to be made for changing the default `statuses-cw-max-chars` value to whatever the default for Mastodon is, since most clients probably have it hard coded :thinking: But that would belong in a separate issue I think.

**Comment by mirabilos** [comment]
tobi dixit:

>Should I close this one now then?

Or keep it open until we know it’s possible to pass a better error
message to the client or we know it’s not possible. Maybe?

>I suppose there's still an argument to be made for changing the default
>`statuses-cw-max-chars` value to whatever the default for Mastodon is,

Hm, no idea what their value is.

>since most clients probably have it hard coded :thinking:

In Semaphore it seems to work differently: it considers the length
of the content wrapper / “title” to be part of the length of the
entire post. If I add a couple hundred chars there, it removes them
from the number shown for the post body.

This shows that Semaphore has a completely different concept of CWs,
and I wonder if $someone should not look into which is actually
better / intended / whatever.

I guess for m*st*d*n it doesn’t matter much because their maximum
post length is ridiculously small anyway…

>But that would belong in a separate issue I think.

Indeed… except if GtS were to be “wrong” in CW length interpretation
(see above). If what I interpolate from Semaphore’s observable
behaviour is right, we wouldn’t even need a separate error message
any more other than the one sent when the post is too long.

bye,
//mirabilos, who, thankfully, has only very basic understanding of AP
-- 
  "Using Lynx is like wearing a really good pair of shades: cuts out
   the glare and harmful UV (ultra-vanity), and you feel so-o-o COOL."
                                         -- Henry Nelson, March 1999

**Comment by tsmethurst** [comment]
This should be resolved by https://github.com/superseriousbusiness/gotosocial/pull/2682; we made the CW length there identical to Mastodon: cw is now just included in total post length.
