### ISSUE TITLE
[bug] All HTTP HEAD requests get 404

### ISSUE THREAD

**Issue by trysdyn** [superseriousbusiness/gotosocial#2016]
### Describe the bug with a clear and concise description of what the bug is.

GtS seems to respond with a 404 to all HEAD requests, including requests for resources that do exist. This is *technically* incorrect behavior and in theory (but not in practice in any way I am aware of) could break some monitoring systems, caching proxies, CDNs, etc.

The technically correct behavior if we're not handling HEADs is to respond with 405 to them.

### What's your GoToSocial Version?

v0.10.0

### GoToSocial Arch

amd64 source build

### What happened?

Someone joined the GtS help chat reporting their webfinger address was 404ing. While investigating I found their testing method was `curl -I` which uses a head request. The same URL returns a 200 OK if you use a GET request.

### What you expected to happen?

The HEAD request should return either a 200 OK with the response headers only, or a 405 Invalid Method to note clearly GtS does not service HEAD requests.

### How to reproduce it?

Hit GtS with any HEAD request, at either the SSL terminator or the service itself.

`curl -I https://gts.superseriousbusiness.org` will return a 404; dropping the `-I` will return a 200.

### Anything else we need to know?

In my usual style this is a compliance/technicality nitpick, but it could become a problem one day, or is one in a way we're not yet aware of.

**Comment by kensanata** [comment]
My suspicion is that we need something in a `gin.Engine` with `HandleMethodNotAllowed` set, but I'm unsure what exactly.

```go
	// HandleMethodNotAllowed if enabled, the router checks if another method is allowed for the
	// current route, if the current request can not be routed.
	// If this is the case, the request is answered with 'Method Not Allowed'
	// and HTTP status code 405.
	// If no other Method is allowed, the request is delegated to the NotFound
	// handler.
	HandleMethodNotAllowed bool
```

My uninformed and untested guess:

```diff
diff --git a/internal/router/router.go b/internal/router/router.go
index 47835e5b..33e38a72 100644
--- a/internal/router/router.go
+++ b/internal/router/router.go
@@ -180,6 +180,7 @@ func New(ctx context.Context) (Router, error) {
 
 	// create the actual engine here -- this is the core request routing handler for gts
 	engine := gin.New()
+        engine.HandleMethodNotAllowed = true;
 	engine.MaxMultipartMemory = maxMultipartMemory
 
 	// set up IP forwarding via x-forward-* headers.
```

**Comment by trysdyn** [comment]
A correction I was provided via the Matrix chat: GtS does not 404 **all** HEAD requests. HEAD requests to the fileserver route will be served for compliance purposes with some third party services (it wasn't recalled clearly which ones but possibly Libreapay's account linkage stuff?).

If the comments on the `HandleMethodNotAllowed` block above are accurate, I think that could work. Just wanted to make sure this was known before a solution is pondered too deeply.
