### ISSUE TITLE
[bug] Published toots have non-clickable hashtags

### ISSUE THREAD

**Issue by ezaquarii** [superseriousbusiness/gotosocial#2019]
### Describe the bug with a clear and concise description of what the bug is.

Published toots have non-clicable hashtags, like in this one:
https://social.etacassiopeiae.net/@ezaquarii/statuses/01H62AEBWRP45XCMN77R3X09J4

It has 2 hashtags: #email and #fediverse. First is clickable, second is not.

### What's your GoToSocial Version?

0.9.0
0.10.0

### GoToSocial Arch

amd64

### What happened?

I published a toot with 2 hashtags. First hashtag is clickable. Second hashtag is not.

Generally hashtags are not working randomly. Sometimes all work. Sometimes few, sometimes none.

### What you expected to happen?

All hashtags should be clickable.

### How to reproduce it?

One reliable method I found:

1. publish a toot using officialy supporteclient
2. delete and redraft
3. publish again

Second method: just publish a toot with multiple hashtags. Or URL and hashtags.

**Comment by tsmethurst** [comment]
Heya, this is normal: hashtags are not implemented yet. They will be in the next release though :)

**Comment by ezaquarii** [comment]
Thanks, that makes sense.

Out of curiosity, why some are clickable and the effect is random-ish?

**Comment by tsmethurst** [comment]
> why some are clickable and the effect is random-ish

Just some weird parsing logic on our part, also fixing it on a branch rn.
