### ISSUE TITLE
[Question] SQLite federation performance

### ISSUE THREAD

**Issue by Jasdemi** [superseriousbusiness/gotosocial#2026]
I'm planning to install GTS as my single user instance. 
The doc says that SQLite is more than enough for single user instances. 

But what about the amount of instances I federate with? Could it become a bottleneck if I add a relay (once released) with hundreds of instances?

**Comment by tsmethurst** [comment]
For some context, the instance I run (https://goblin.technology) runs on SQlite and federates with > 2000 instances. Instance is a 1-cpu 1024mb ram VPS. Performance is good, occasionally some slow queries (>1s) but not during federation operations. We're still measuring + improving performance on SQLite but you should have enough headroom for a while.
