### ISSUE TITLE
[feature] config for disabling webclient recommendation on homepage?

### ISSUE THREAD

**Issue by decentral1se** [superseriousbusiness/gotosocial#2030]
### Is your feature request related to a problem ?

The homepage of GtS is allows for customisation but includes a mandatory "GoToSocial does not provide its own webclient, but implements the Mastodon client API. You can use this server through a variety of other clients:" section which can be confusing for newcomers. What is a webclient? Sometimes less information is better as people get onboarded with various concepts.

### Describe the solution you'd like.

Ability to hide the webclient recommendation section:

![image](https://github.com/superseriousbusiness/gotosocial/assets/1991377/995aefbf-c01e-4c7f-9f23-01c5cd5d9a71)

I can handle this introduction myself via the "Short description"? Altho this maybe then means the "Short description" is becoming the "Full description" which for the time being, I don't see updating on the home page?

### Describe alternatives you've considered.

Making the customisable section on the top longer and including text to help people understand what the instance is about, also federated social media etc. However, then I typically introduce my own client in the text. So then the client recommendations are there twice.

### Additional context.

This is mostly relevant for onboarding "not technical" people.

**Comment by daenney** [comment]
I don't think we want to do that honestly. If you want to, you can achieve this by overriding the [`index.tmpl`](https://github.com/superseriousbusiness/gotosocial/blob/main/web/template/index.tmpl) in your `web-template-base-dir`.

**Comment by decentral1se** [comment]
OK, thanks for the tip!
