### ISSUE TITLE
[bug] activity+json: `attachment` should always be an array

### ISSUE THREAD

**Issue by Cynosphere** [superseriousbusiness/gotosocial#2034]
### Describe the bug with a clear and concise description of what the bug is.

When getting a post via `Accept: application/activity+json` and the post has one attachment, it is an object opposed to an array of object.

### What's your GoToSocial Version?

v0.10.0

### Anything else we need to know?

I have not checked if this is mandatory by the spec but every other server seems to implement it this way.

**Comment by tsmethurst** [comment]
> I have not checked if this is mandatory by the spec

It's not! The only thing we've run into so far where it's mandatory is the `items` or `orderedItems` property on a `collection` or `orderedCollection`: https://www.w3.org/TR/activitystreams-vocabulary/#dfn-items

There's nothing special about the 'attachments' property of an object that says it must be an array (https://www.w3.org/TR/activitystreams-vocabulary/#dfn-attachment), it's just like any other property with domain object and range object, link, so if there's only one entry it's valid to serialize it as either an object or an array.

Is there a specific case where this is causing problems?

**Comment by tsmethurst** [comment]
More context on this can be found here: https://github.com/superseriousbusiness/gotosocial/pull/1673 and here: https://github.com/w3c/activitystreams/issues/535

**Comment by Cynosphere** [comment]
> Is there a specific case where this is causing problems?

I found it when working on my Discord bot that has the option to re-embed fediverse posts, which I just made a simple workaround of wrapping in an array if it isn't one. I figured I'd report it just in case it was causing issues elsewhere because of:
> every other server [software] seems to implement it this way
