### ISSUE TITLE
[bug] Suspended cyrillic domains can't be edited/removed

### ISSUE THREAD

**Issue by Jasdemi** [superseriousbusiness/gotosocial#2035]
### Describe the bug with a clear and concise description of what the bug is.

I have added the domain "срёт.онлайн" to my suspended instances, but it can no longer be removed or edited. 

### What's your GoToSocial Version?

0.10.0 git-89ee9d5

### GoToSocial Arch

Docker

### How to reproduce it?

1. Add a domain with cyrillic characters on https://<your-domain>/settings/admin/federation
2. Open the entry of the suspended domain
3. The domain field will display something like "%D1%81%D1%80%D1%91%D1%82.%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD" instead of the real domain.

**Comment by tsmethurst** [comment]
Hmmm thanks, will check it out.
