### ISSUE TITLE
[feature] Separate the uploaded and federated media into different folders

### ISSUE THREAD

**Issue by chenzhiwei** [superseriousbusiness/gotosocial#2036]
### Is your feature request related to a problem ?

I don't want to backup the media that downloaded from federated sites.

### Describe the solution you'd like.

There are two types of media, user uploaded and downloaded from federated sites.

It is better to separate them into different folders, so when creating backup, I can only backup the media I uploaded.

### Describe alternatives you've considered.

NONE

**Comment by daenney** [comment]
Hiya! We're already tracking this in #1776 so I'm going to go ahead and close this one. You can subscribe to that issue instead if you want to keep track of the progress on this.
