### ISSUE TITLE
[bug] Pleroma instances tend to massively overload my GtS instance for some reason

### ISSUE THREAD

**Issue by eeeeeta** [superseriousbusiness/gotosocial#2039]
### Describe the bug with a clear and concise description of what the bug is.

Due to some sort of incompatibility (perhaps #107), Pleroma instances tend to get stuck in a loop requesting the same things over and over from my instance. When making a particularly popular post, the effect of lots of Pleromas doing this causes CPU load to spike to ~200%, the journal to get overwhelmed, ... -- basically a small Denial of Service attack.

### What's your GoToSocial Version?

v0.10.0 git-2470e21 (patched)

### GoToSocial Arch

amd64 binary

### What happened?

- Make a post that gets boosted by a bunch of people
- Notice GtS getting slower to respond
- Have my Prometheus alerts tell me that the server is overheating and has its resources stretched
- Check the logs to find lots of Pleroma spam

A random sample of 100 lines of it looks like [this](https://eta.st/lx/v04za7r4.txt).

### What you expected to happen?

Although this probably needs to be fixed pleroma-side, it'd be nice to have some mitigation for this on the GtS end -- I currently just [block the pleroma User-Agent entirely](https://git.eta.st/forks/gotosocial/-/commit/2470e21629b052a14f12f7266deecfc96dddd8f4), but some rate-limiting to detect this case might be useful

**Comment by tsmethurst** [comment]
Huh, that's odd! Thanks, will investigate soon (tm).

**Comment by NyaaaWhatsUpDoc** [comment]
@tsmethurst  I just had a thought, what if we are _also_ doing the same thing we found that some Mastodon instances were doing and serving self-referential status collection pages?

**Comment by eeeeeta** [comment]
I'm pretty sure this one is actually PEBKAC -- I had hacked up my GtS database to move some of my old posts over from another instance, but this resulted in the pinned toot being broken, and I think *that's* why the Pleromas carried on crashing and retrying in a big loop. Whoops! Apologies for the false alarm >.<

**Comment by eeeeeta** [comment]
I lied! I pinned a non-cursed toot, left it a while, and came back to another sea of constantly retrying Pleromas in the logs :c

**Comment by tsmethurst** [comment]
Hmmm.... could it be because you've got your domain (eta.st) serving webfinger responses directly rather than forwarding them to your GtS server? It does look like you're serving the correct data, but it might be confusing Pleroma specifically for whatever reason.

**Comment by eeeeeta** [comment]
It seems very linked to the pinned toot -- unpinning the toot will make the Pleromas stop looping, for example -- so I doubt that's it

**Comment by tsmethurst** [comment]
Hey @eeeeeta , are you still seeing this with 0.12.1?

**Comment by eeeeeta** [comment]
I just updated my own patchset to HEAD actually, so I'll pin a toot and see if I can get some pleromas stuck in it again...

**Comment by eeeeeta** [comment]
Update: It's 2 days later and I just opened my gts logs to find about 10 Pleroma requests per second, so this is still an issue! Please let me know if there's anything more I can do to debug this :)

**Comment by tsmethurst** [comment]
Alright, thanks for checking it out! I'll see if I can figure out just what it is about GtS pinned posts that pleroma doesn't like...

**Comment by bjo81** [comment]
If it also affects Akkoma, I could try to follow and take a look into the logs.

**Comment by eeeeeta** [comment]
It only affects sufficiently old Akkoma; modern Akkoma versions don't seem to have an issue.

**Comment by tsmethurst** [comment]
Ah really? So it's something that Akkoma identified as a bug recently and fixed?

**Comment by tsmethurst** [comment]
Just a thought, btw, are you pinning toots that you 'imported' and then fiddled with in the database?

**Comment by eeeeeta** [comment]
That was originally the case, but the problem exists even with non-'imported' toots.

**Comment by tsmethurst** [comment]
I'm still not sure what to do with this one. Is it still happening or have the 'omas fixed it on their side?

**Comment by eeeeeta** [comment]
Very much so -- pinned a post today and came back an hour later to find GtS using all the CPU on the machine :(

**Comment by tsmethurst** [comment]
How about now?

**Comment by eeeeeta** [comment]
(whoops, didn't actually mean to instantly close, but I guess that's fine?)
