### ISSUE TITLE
[bug] Error when searching for an account with a dot in the username

### ISSUE THREAD

**Issue by jeherve** [superseriousbusiness/gotosocial#2044]
### Describe the bug with a clear and concise description of what the bug is.

When searching for an account with a dot in the username, no username is returned in the search results.

### What's your GoToSocial Version?

0.10.0

### GoToSocial Arch

amd64 binary

### What happened?

When querying the `api/v2/search` endpoint for an account with a dot in the username, no results are returned:

```
yourdomain.com/api/v2/search?q=%40mattwiebe.blog%40mattwiebe.blog&resolve=true&limit=5&exclude_unreviewed=false
```

Response:

```
{"accounts":[],"statuses":[],"hashtags":[]}
```

Here is what appears in the logs:

```
timestamp="31/07/2023 17:16:37.765" func=middleware.Logger.func1.1 level=INFO latency="45.741µs" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" method=OPTIONS statusCode=204 path=/api/v2/search clientIP=2a01:e0a:a5c:b460:c48a:1130:4cbc:1d91 requestID=0ppf7b4904001hh9skfg msg="No Content: wrote 0B
```

### What you expected to happen?

I would expect the account to appear as a result, like it does in Mastodon for example.

The account does exist and seems to return the expected information:

https://mattwiebe.blog/.well-known/webfinger?resource=acct:mattwiebe.blog@mattwiebe.blog

```
$ curl -H 'accept: application/activity+json' https://mattwiebe.blog/@mattwiebe.blog
{
	"@context": [
		"https:\/\/www.w3.org\/ns\/activitystreams",
		"https:\/\/w3id.org\/security\/v1",
		{
			"manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
			"PropertyValue": "schema:PropertyValue",
			"schema": "http:\/\/schema.org#",
			"pt": "https:\/\/joinpeertube.org\/ns#",
			"toot": "http:\/\/joinmastodon.org\/ns#",
			"value": "schema:value",
			"Hashtag": "as:Hashtag",
			"featured": {
				"@id": "toot:featured",
				"@type": "@id"
			},
			"featuredTags": {
				"@id": "toot:featuredTags",
				"@type": "@id"
			}
		}
	],
	"type": "Group",
	"inbox": "https:\/\/public-api.wordpress.com\/wpcom\/activitypub-1.0\/sites\/219408313\/users\/0\/inbox",
	"outbox": "https:\/\/public-api.wordpress.com\/wpcom\/activitypub-1.0\/sites\/219408313\/users\/0\/outbox",
	"following": "https:\/\/public-api.wordpress.com\/wpcom\/activitypub-1.0\/sites\/219408313\/users\/0\/following",
	"followers": "https:\/\/public-api.wordpress.com\/wpcom\/activitypub-1.0\/sites\/219408313\/users\/0\/followers",
	"streams": [],
	"preferredUsername": "mattwiebe.blog",
	"publicKey": {
		"id": "https:\/\/mattwiebe.blog\/@mattwiebe.blog#main-key",
		"owner": "https:\/\/mattwiebe.blog\/@mattwiebe.blog",
		"publicKeyPem": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqOZVi+KixVpRREqqoltz\nJvBQXYEw8eqCqROme\/JpFkB2XqAFcPZlnKE\/ucMpotrbC5c2M\/R\/gJG3lPYvO6eb\n3mPpfkTjN\/\/i+2KZ7RJ3OowMfeHDIaQEFITwgXjlR+kFaZMytZBwFM8xfPe2VOHt\nPon9yfR2KxnUT9NAZGT\/PhgJ6YQnJOq2kapCNGf\/dyU6XY6OAcGJrK+S6a73hLqT\noOSsChbpJhlIgJBRZsVvtYn6RFkSkMRx5NvqxOZ\/qyh1Ycv8owUTDK2d29IhepGA\ng\/eXRlOiONxti6emUXF5GBBK3ShLPn80R+zpJIF1D5IK3Nyc+QnrbOi22iz1Pe2F\niQIDAQAB\n-----END PUBLIC KEY-----\n"
	},
	"manuallyApprovesFollowers": false,
	"id": "https:\/\/mattwiebe.blog\/@mattwiebe.blog",
	"attachment": [],
	"name": "mattwiebe.blog",
	"published": "2023-05-25T14:58:47Z",
	"summary": "",
	"url": "https:\/\/mattwiebe.blog\/@mattwiebe.blog"
}
```

### How to reproduce it?

1. Go to https://semaphore.social/
2. Log in to to a GtS account.
3. Go to Search
4. Search for `@mattwiebe.blog@mattwiebe.blog`
5. See no result being returned

### Anything else we need to know?

- I'm posting here following my comment on this issue: https://github.com/superseriousbusiness/gotosocial/issues/595#issuecomment-1658090650
- The account listed above is a group type account, on a site using the ActivityPub plugin for WordPress: https://github.com/Automattic/wordpress-activitypub/

**Comment by jeherve** [comment]
Of note, this seems to be limited to usernames with a dot. When searching for another username for a Group account on another site using the ActivityPub plugin for WordPress, I get results. You can test with `@blog@jeremy.hu` for example.

**Comment by tsmethurst** [comment]
I think the issue here is not the dot, but the fact that our heuristics are catching this as an instance service account, because the username is the same as the domain. See:

- https://github.com/superseriousbusiness/gotosocial/blob/9bd03e122e9c0e9c4dc3c4683b834c4a3bd673ea/internal/processing/search/util.go#L55
- https://github.com/superseriousbusiness/gotosocial/blob/9bd03e122e9c0e9c4dc3c4683b834c4a3bd673ea/internal/gtsmodel/account.go#L97

I think the solution here would be to allow returning instance accounts in search when they've been searched for specifically by namestring or URL, but exclude them still from search results returned by text search.

**Comment by jeherve** [comment]
Thanks for the details. Your proposed solution makes sense I think, it would solve the problem nicely.
