### ISSUE TITLE
[feature] Account notes

### ISSUE THREAD

**Issue by WesleyAC** [superseriousbusiness/gotosocial#2063]
### Is your feature request related to a problem ?

Many clients (Tusky is the one I generally use) support adding notes to accounts. This field shows up on my GTS server, but the notes don't seem to be saved.

### Describe the solution you'd like.

A implementation of notes!

Or, if that will take a while and there is a standardized way in nodeinfo or something to indicate that it's unsupported, that.

### Describe alternatives you've considered.

Not implementing notes. But they're useful so I'd like them.

### Additional context.

It's possible that these are supposed to work and it's a bug that they don't, if so I can investigate.

**Comment by tsmethurst** [comment]
This is already included in main, so will be in the next release :) https://github.com/superseriousbusiness/gotosocial/pull/1982

**Comment by WesleyAC** [comment]
Oh excellent! That's great :)
