### ISSUE TITLE
[bug] 411 error from remote server when trying to interact

### ISSUE THREAD

**Issue by rdelaage** [superseriousbusiness/gotosocial#2079]
### Describe the bug with a clear and concise description of what the bug is.

When trying to interact with some remote servers there is no interaction possible (follow or redirect) and I get a 411 response from the remote server in the logs.

### What's your GoToSocial Version?

517829ae

### GoToSocial Arch

arm64

### What happened?

Remote server refused to receive a message in the inbox with a 411 response from the remote server
```
timestamp="07/08/2023 17:18:46.480" func=httpclient.(*Client).DoSigned level=INFO method=POST url=https://podcast.picasoft.net/@la_voix_est_libre/inbox pubKeyID=https://gotosocial.pi4.delaage.fr/users/rdelaage/main-key msg="performing request"
timestamp="07/08/2023 17:18:46.500" func=processing.(*Processor).EnqueueClientAPI.func1 level=ERROR msg="error processing client API message: func1: error delivering to https://podcast.picasoft.net/@la_voix_est_libre/inbox: deliver: POST request to https://podcast.picasoft.net/@la_voix_est_libre/inbox failed: status=\"411 Length Required\" body=\"<!DOCTYPE html><title>Error 411</title><p>Error 411.\r\n\""
```

### What you expected to happen?

An accept-follow response

### How to reproduce it?

Create a gotosocial account. Try to follow @la_voix_est_libre@podcast.picasoft.net and see the gotosocial logs

**Comment by NyaaaWhatsUpDoc** [comment]
Very much appreciate this digging, thank you!

In case you're interested I'll link to the appropriate code for the fix when it happens. It will probably end up being in our custom httpclient with backoff functionality (so under `./internal/httpclient`)
