### ISSUE TITLE
[bug] Issue  Feed Rss description  garbled chars 

### ISSUE THREAD

**Issue by kkbt0** [superseriousbusiness/gotosocial#2083]
### Describe the bug with a clear and concise description of what the bug is.

Rss feed description garbled characters

### What's your GoToSocial Version?

GoToSocial 0.10.0 git-89ee9d5

### GoToSocial Arch

amd64 docker

### What happened?

https://example.com/@tom/feed.rss have 
```
��...</description>
```

Maybe it can work correctly with ASCII .But not for Utf-8 . 

### What you expected to happen?

Published longer than a certain length, characters beyond the ASCII range.Such as Chinese.

**Comment by tsmethurst** [comment]
Oh weird, thank you, will investigate!
