### ISSUE TITLE
[feature] Add toggle in settings frontend for `discoverable` account flag

### ISSUE THREAD

**Issue by VyrCossont** [superseriousbusiness/gotosocial#2088]
### Is your feature request related to a problem ?

I want to be able to set the `discoverable` federated account flag so that an account can show up in Mastodon account and (soon) post searches. I'm not sure if it interacts with GtS search yet, or with other instance types.

### Describe the solution you'd like.

I'd like `/settings/user/profile` in the settings frontend to have a checkbox for setting the `discoverable` flag, called something like "Account and posts should be made discoverable in searches", next to "Manually approve follow requests" and "Enable RSS feed of Public posts".

### Describe alternatives you've considered.

Any Mastodon-compatible client can potentially set this flag through the `PATCH /api/v1/accounts/update_credentials` API method.

### Additional context.

The flag defaults to off, so *not* implementing this isn't going to cause any new privacy issues.

**Comment by NyaaaWhatsUpDoc** [comment]
I think we should emphasize in the front-end text that this will include searches by remote servers.

**Comment by tsmethurst** [comment]
Yes, agreed, we've needed this setting for a while! It should probably come with a warning and a link to the documentation next to it, like we have in the post settings (see screenshot)

![User post settings panel, showing little links next to settings for post privacy and format, which link to the GtS docs](https://github.com/superseriousbusiness/gotosocial/assets/31960611/121ae56d-c957-4517-a893-e046d54b536e)

**Comment by f0x52** [comment]
We already have the API implemented, so if someone could write a nice docs page with pros/cons to link to I can add it to the settings :)

**Comment by VyrCossont** [comment]
As of today, Mastodon uses a *different* actor-level federated attribute for post search opt-in (`indexable`, which is new), but this is still used for profile search and other profile discovery mechanisms.

**Comment by NyaaaWhatsUpDoc** [comment]
> As of today, Mastodon uses a _different_ actor-level federated attribute for post search opt-in (`indexable`, which is new), but this is still used for profile search and other profile discovery mechanisms.

oh mastodon sure do love their confusing API decisions
