### ISSUE TITLE
[bug] Content Security Policy Error on S3 Image Load

### ISSUE THREAD

**Issue by mlapida** [superseriousbusiness/gotosocial#2110]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

After updating to 0.11.0-rc2, I'm receiving content-security-policy errors and am unable to load images on the site. Enabling the image proxy seems to address the issue. Looking at the [release notes for RC2](https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.11.0-rc2), it seems this should have been addressed in RC2.

I'm using Cloudflare R2 for this setup, and prefer to turn the image proxy off. 

### What's your GoToSocial Version?

0.11.0-rc2

### Browser version

115.0.2 

### What happened?

Images do not load when accessing the site directly. A Content-Security-Policy error is displayed from the browser's console. 

### What you expected to happen?

The images to load normally. 

### How to reproduce it?

Load any page on a GTS install running 0.11.0-rc2. [My site](https://gts.lapidak.is) can be used as an example.

### Anything else we need to know?

This is occurring across Safari and Brave as well.

**Comment by tsmethurst** [comment]
We're on it!

**Comment by mlapida** [comment]
Seems to be working perfectly.
