### ISSUE TITLE
[bug] Uploading images results in a 422

### ISSUE THREAD

**Issue by DysphoricUnicorn** [superseriousbusiness/gotosocial#2116]
### Describe the bug with a clear and concise description of what the bug is.

Trying to upload any image results in a 422: "Unprocessable Entity" error.

This happens in Toot! and Semaphore, I haven't tried other clients yet.

Server logs only show this:
```
timestamp="14/08/2023 19:31:10.453" func=middleware.Logger.func1.1 level=INFO latency="9.160967ms" userAgent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" method=POST statusCode=422 path=/api/v2/media clientIP=172.16.1.12 requestID=c3d8bb732b62e781003fee14df86e142 msg="Unprocessable Entity: wrote 56B"
````

This happened for me in v0.10.0 and after updating to v0.11.0-rc3 in hopes it might be fixed, it still occurs

### What's your GoToSocial Version?

v0.11.0-rc3

### GoToSocial Arch

x86 container on kubernetes

**Comment by tsmethurst** [comment]
That's strange... Could you check in the network logs of your browser when doing the upload via semaphore, and see if anything helpful is being returned along with the 422 response?

**Comment by NyaaaWhatsUpDoc** [comment]
also information on the image file types used :)

**Comment by DysphoricUnicorn** [comment]
I'll add that info as soon as I can. Sorry for leaving it out in my initial report. I've been quite busy packing for camp but didn't want to forget opening this issue

**Comment by tsmethurst** [comment]
No worries! Have fun at camp!

**Comment by DysphoricUnicorn** [comment]
Wow, I just tried reproducing it again and it no longer happened 🙃

Sorry for wasting your time

**Comment by tsmethurst** [comment]
Glad it's working :)
