### ISSUE TITLE
[feature] Add an option to export path of replicated remote media

### ISSUE THREAD

**Issue by rdelaage** [superseriousbusiness/gotosocial#2117]
### Is your feature request related to a problem ?

I would like to backup my GoToSocial instance using autorestic. I need to backup the `storage` directory, but I want to avoid backuping of replicated remote media to preserve my backup device.

I tried to use the `gotosocial admin media list-remote` command to create an exclude list, but this command export the URL of the remote media on their original instance. I would like to export the local path on filesystem for replicated remote media.

### Describe the solution you'd like.

A flag to export local path of replicated remote media.

Something like `gotosocial admin media list-remote --local-path`

### Describe alternatives you've considered.

Using a script reading the database, too much complex and hard to maintain. This should be something handled by the CLI.

**Comment by tsmethurst** [comment]
ties in with #1998 I believe

**Comment by tsmethurst** [comment]
closed by https://github.com/superseriousbusiness/gotosocial/pull/2121
