### ISSUE TITLE
[feature] emojis are not included in admin media commands

### ISSUE THREAD

**Issue by rdelaage** [superseriousbusiness/gotosocial#2118]
### Describe the bug with a clear and concise description of what the bug is.

When I run `gotosocial admin media list-local` my custom emojis are not listed at all. The same seems to happen with `gotosocial admin media list-remote`. This can be a problem for people performing backups using these commands.

### What's your GoToSocial Version?

v0.11.0-rc3

### GoToSocial Arch

arm64

**Comment by daenney** [comment]
I've changed this to an enhancement. We should add a way to include emoji too, either as its own command or by default and then with some filter on the command if you want one or the other.
