### ISSUE TITLE
Consider replacing blob.Storage interface

### ISSUE THREAD

**Issue by NyaaaWhatsUpDoc** [superseriousbusiness/gotosocial#212]
Our current implementation is not concurrency safe for multiple changes to same key, and passes bytes instead of streams which will be an issue for larger files. An alternative could be: https://git.iim.gay/grufwub/go-store

This is concurrency safe, supports either bytes or streams and has a swappable internal storage interface so the plain disk storage can eventually have other implementations, e.g. S3

My suggested use here would be `kv.KVStore{}` with `storage.DiskStorage{}`

It also supports a lot of configuration of buffer sizes and uses pooled allocation of buffers wherever possible

**Comment by NyaaaWhatsUpDoc** [comment]
For anyone taking a look at it, the object store type is currently not passing tests, but that's not needed here.

**Comment by tsmethurst** [comment]
Good idea -- as long as it can use the current file structure and doesn't require dropping all media then i'm totally for it, the blob.Storage was just a naive implementation of something to get us moving

**Comment by NyaaaWhatsUpDoc** [comment]
Implemented in #214
