### ISSUE TITLE
[bug] Recurring Content Security Policy Error with AWS S3

### ISSUE THREAD

**Issue by RShirohara** [superseriousbusiness/gotosocial#2123]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

The image loading issue due to Content Security Policy Error in S3 fixed in #2110 continues to occur in the AWS S3 environment, so images cannot be displayed.

I use AWS S3 in my environment and do not use image proxy.

I checked the HTTP request for the image and found that the domain set in the `location` header does not match the domain set in the `content-security-policy` header.

![image](https://github.com/superseriousbusiness/gotosocial/assets/47940764/5fe6bd6e-34af-4fd8-b255-f3316c35d762)

### What's your GoToSocial Version?

v0.11.0 (`815b529`)

### Browser version

Firefox 112.0.1 (64-bit)

### What happened?

When I access the site with a web browser, the images do not load.
The browser console displays a Content-Security-Policy error.

### What you expected to happen?

Images are loaded normally.

### How to reproduce it?

Open the user page of the instance running GoToSocial v0.11.0.
~~[My page](https://ap.third-branches.net/@rshirohara) can be used as an example.~~

### Anything else we need to know?

- This problem occurring across Chromium 116.0.5845.96 (64-bit) as well. 
- I'm a non-native English speaker, so I use DeepL Translator and Google Translate.

**Comment by tsmethurst** [comment]
Thank you for the detailed report! It seems we probably need to add another setting to our config to let people override those content security policy entries if their s3 api domain differs from the domain that media actually ends up being served from.

As a workaround in the meantime, can you try setting s3 proxy to true in your config file? That should at least allow media to be shown while we work on a hotfix for this issue.
