### ISSUE TITLE
[bug] reblogs shown on timeline

### ISSUE THREAD

**Issue by alok0** [superseriousbusiness/gotosocial#2131]
### Describe the bug with a clear and concise description of what the bug is.

It appears that if I have `reblog`s turned off for an account I follow, then the websocket for streaming updates correctly filters out boosts. But if I load my home timeline (`/api/v1/timelines/home`) it shows the boosted posts there.

### What's your GoToSocial Version?

v0.11.0

### GoToSocial Arch

amd64 Docker

### How to reproduce it?

1. Account A follow account B
2. Account A sets `reblog` to false for B
3. Account B boosts a post
4. Account A does not receive a streaming websocket update for said boost
5. Account A reloads timeline from `/api/v1/timelines/home`
    - Expected result: boosted post is not included
    - Actual result: boosted post is included

**Comment by tsmethurst** [comment]
Currently it doesn't apply retroactively by removing previous reblogs, it just applies going forward.

**Comment by alok0** [comment]
Does that count as retroactive? At the time the boost was published/received reblogs was not intended to be shown, and at the time the timeline was loaded reblogs was also not intended to be shown.

**Comment by tsmethurst** [comment]
Oh, I misunderstood your issue, sorry. That sounds like a bug indeed!
