### ISSUE TITLE
[bug]How to set Time Zone

### ISSUE THREAD

**Issue by jkjoy** [superseriousbusiness/gotosocial#2132]
### Describe the bug with a clear and concise description of what the bug is.

The time displayed is incorrect. How to set it

### What's your GoToSocial Version?

latest

### GoToSocial Arch

amd64

**Comment by tsmethurst** [comment]
For docker: https://docs.gotosocial.org/en/latest/getting_started/installation/container/#server-timezone-optional-but-recommended

For bare metal / binary installation: GoToSocial uses your server's timezone.

**Comment by jkjoy** [comment]
Thanks a lot.
