### ISSUE TITLE
[bug] GoToSocial cannot connect to Neon PostgreSQL database

### ISSUE THREAD

**Issue by aaro-n** [superseriousbusiness/gotosocial#2133]
### Describe the bug with a clear and concise description of what the bug is.

Neon PostgreSQL provides free 3GB database storage, GoToSocial cannot establish a link with Neon.
# Environment variables:
```
  GTS_DB_PORT = "5432"
  GTS_DB_ADDRESS = "ep-raspy-pond-xxxxx.ap-southeast-1.aws.neon.tech"
  GTS_DB_USER = "gotosocial"
  GTS_DB_PASSWORD = "TEuSAtYR26Wx"
  GTS_DB_DATABASE = "gotosocial"
  GTS_DB_TLS_MODE = "enable"
```
# log:
```
2023/08/19 15:02:24 error executing command: error creating dbservice: postgres ping: failed to connect to `host=ep-raspy-pond-xxxxx.ap-southeast-1.aws.neon.tech user=gotosocial database=gotosocial`: server error (ERROR: Endpoint ID is not specified. Either please upgrade the postgres client library (libpq) for SNI support or pass the endpoint ID (first part of the domain name) as a parameter: '?options=endpoint%3D<endpoint-id>'. See more at https://neon.tech/sni (SQLSTATE XX000))
```

### What's your GoToSocial Version?

v0.11.0

### GoToSocial Arch

amd64 Docker

### What happened?

none

### What you expected to happen?

Normal connection with Neon PostgreSQL

### How to reproduce it?

none

### Anything else we need to know?

Does gotosocial have a database connection method in the form of `DATABASE_URL="postgres://user:password@host:port/database?sslmode=disable"`.

**Comment by tsmethurst** [comment]
> Does gotosocial have a database connection method in the form of DATABASE_URL="postgres://user:password@host:port/database?sslmode=disable".

Currently not, no.

https://neon.tech/docs/connect/connection-errors#c-set-verify-full-for-golang-based-clients

^^ Can you try doing that and see if it works?

**Comment by aaro-n** [comment]
@tsmethurst Thanks for the guidance. After modifying the variables according to the document, you can connect to the database normally, and this problem will be closed.
# Environment variables:
```
  GTS_DB_PORT = "5432"
  GTS_DB_ADDRESS = "ep-raspy-pond-xxxxx.ap-southeast-1.aws.neon.tech"
  GTS_DB_USER = "gotosocial"
#  GTS_DB_PASSWORD = "TEuSAtYR26Wx"
  GTS_DB_PASSWORD = "endpoint=ep-raspy-pond-xxxxx;TEuSAtYR26Wx"
  GTS_DB_DATABASE = "gotosocial"
  GTS_DB_TLS_MODE = "enable"
```
