### ISSUE TITLE
[feature] Federation with theverge.space

### ISSUE THREAD

**Issue by alok0** [superseriousbusiness/gotosocial#2135]
### Is your feature request related to a problem ?

I do not know what software runs on `theverge.space`. I assume it is a one off. I've not been able to contact the maintainer.

When I try to follow any of the accounts (eg `@quickposts@theverge.space`) I get an error I don't understand:

```
 timestamp="19/08/2023 13:23:47.378" func=workers.(*Processor).ProcessFromClientAPI level=INFO activityType=Create objectType=Follow fromAccount=******** msg="processing from client API"
 timestamp="19/08/2023 13:23:47.379" func=middleware.Logger.func1.1 level=INFO latency="5.312266ms" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0" method=POST statusCode=200 path=/api/v1/accounts/********/follow clientIP=108.26.156.28 requestID=5nafe3ca0400149cdm2g msg="OK: wrote 177B"
 timestamp="19/08/2023 13:23:47.379" func=federation.(*federatingActor).Send level=INFO msg="send activity Follow via outbox https://********/users/********/outbox"
 timestamp="19/08/2023 13:23:47.393" func=httpclient.(*Client).DoSigned level=INFO method=POST url=https://theverge.space/actor/quickposts/inbox pubKeyID=https://********/users/********/main-key msg="performing request"
 timestamp="19/08/2023 13:23:47.491" func=workers.(*Processor).EnqueueClientAPI.func1 level=ERROR msg="error processing client API message: CreateFollowReq: error federating follow: Follow: error sending activity *typefollow.ActivityStreamsFollow via outbox https://********/users/********/outbox: func1: error delivering to https://theverge.space/actor/quickposts/inbox: deliver: POST request to https://theverge.space/actor/quickposts/inbox failed: status=\"415 Unsupported Media Type\" body=\"{\"statusCode\":415,\"code\":\"FST_ERR_CTP_INVALID_MEDIA_TYPE\",\"error\":\"Unsupported Media Type\",\"message\":\"Unsupported Media Type: application/ld+json; profile=\\\"https://www.w3.org/ns/activitystreams\\\"\"}\""

```

```json
{
  "statusCode": 415,
  "code": "FST_ERR_CTP_INVALID_MEDIA_TYPE",
  "error": "Unsupported Media Type",
  "message": "Unsupported Media Type: application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\""
}

```

### Describe the solution you'd like.

I am uncertain if this should even work, but I thought I'd ask since I can't figure out where it is failing in from the logs.

### Describe alternatives you've considered.

NONE

### Additional context.

Search for the accounts generally seem to work.

If I boost the posts from that server from a mastodon server, gotosocial can see the boosted post.

**Comment by tsmethurst** [comment]
Some CURLing later: it looks like they support `Content-Type: application/activity+json` on POST requests, but not `Content-Type: application/ld+json; profile="https://www.w3.org/ns/activitystreams"`. Since the latter is the the standard AP content-type for server-to-server interactions, this is likely just an oversight on their part (see https://www.w3.org/TR/activitypub/#server-to-server-interactions).

I'll link the software author to this issue :)

**Comment by tsmethurst** [comment]
I got a reply from the dev that he'll take a look at it soon :)

**Comment by zemlanin** [comment]
theverge.space’s maintainer here. Yeah, its server is a one-off

I’ve added handling for `application/ld+json`, but not 100% sure if I’ve done it everywhere it’s needed. Could you check if it works?

**Comment by tsmethurst** [comment]
It seems to work! That was quick!

**Comment by zemlanin** [comment]
Yay! Sorry for causing an issue in your project 😅

**Comment by alok0** [comment]
ok, so now i'm getting:

`timestamp="19/08/2023 16:15:05.372" func=workers.(*Processor).EnqueueClientAPI.func1 level=ERROR msg="error processing client API message: CreateFollowReq: error federating follow: Follow: error sending activity *typefollow.ActivityStreamsFollow via outbox https://********/users/********/outbox: func1: error delivering to https://theverge.space/actor/adi_robertson/inbox: deliver: POST request to https://theverge.space/actor/adi_robertson/inbox failed: status=\"401 Unauthorized\" body=\"{\"detail\":\"invalid signature\"}\""`

is this a secure mode/authorized fetch problem?

**Comment by zemlanin** [comment]
It's HTTP Signatures problem

Do you, by any chance, know an instance I could join to test federation with less back and forth?

**Comment by zemlanin** [comment]
Okay, `http-signature` doesn't support `hs2019` algorithm… https://github.com/TritonDataCenter/node-http-signature/issues/106

**Comment by zemlanin** [comment]
Do _all_ server-to-server requests to GtS need to be signed?

```
> curl -H "accept: application/activity+json" "https://goblin.technology/users/tobi"
{"error":"Unauthorized: http request wasn't signed or http signature was invalid: (verifier)"}
```

**Comment by alok0** [comment]
yes https://github.com/superseriousbusiness/gotosocial/blob/main/docs/federation/federating_with_gotosocial.md

**Comment by zemlanin** [comment]
@alok0 I think I've fixed follow/unfollow. Could you check it on your server?

---

Auto-replies from bots (as a DM) still don't work — the message is sent and accepted, but doesn't show up in Semaphore

Am I missing something in the reply `Note`? Do DMs need to be available via URL (right now I'm sending them without storing in the database)?

```js
{
  type: 'Note',
  id: 'https://theverge.space/actor/sean_hollister/note/fdb38f82-8f25-4cd7-a610-efb0aa9cc697/reply-1692532446289-000001',
  published: '2023-08-20T11:54:06.289Z',
  updated: null,
  attributedTo: 'https://theverge.space/actor/sean_hollister',
  inReplyTo: 'https://goblin.technology/users/zemlanin/statuses/01H89CQ4S3G9Z9VDZY3VNE6Q6T',
  to: [ 'https://goblin.technology/users/zemlanin' ],
  url: 'https://theverge.space/actor/sean_hollister/note/fdb38f82-8f25-4cd7-a610-efb0aa9cc697/reply-1692532446289-000001',
  content: '<p>Hi. Accounts on @theverge.space are unofficial bots. You can comment <a href="https://www.theverge.com/2023/7/14/23795423/guess-what-i-found-in-the-oculus-vr-lobby-a-decade-ago">the article</a> on The Verge</p><p>Sorry for confusion<br>- the <a href="https://theverge.space">theverge.space</a> developer</p>',
  contentMap: {
    en: '<p>Hi. Accounts on @theverge.space are unofficial bots. You can comment <a href="https://www.theverge.com/2023/7/14/23795423/guess-what-i-found-in-the-oculus-vr-lobby-a-decade-ago">the article</a> on The Verge</p><p>Sorry for confusion<br>- the <a href="https://theverge.space">theverge.space</a> developer</p>'
  },
  attachment: [],
  conversation: undefined,
  tag: [ { type: 'Mention', href: 'https://goblin.technology/@zemlanin' } ]
}
```

**Comment by zemlanin** [comment]
`Announce`/boost messages trigger `Internal Server Error` on GtS's side

**Comment by alok0** [comment]
`timestamp="20/08/2023 12:08:01.095" func=middleware.Logger.func1.1 level=ERROR latency="4.41176ms" userAgent="fetch (https://theverge.space)" method=POST statusCode=500 path=/users/********/inbox clientIP=3.239.85.123 error="Error #01: PostInboxScheme: error calling sideEffectActor.PostInbox: Announce: error converting announce to boost: ASAnnounceToStatus: error extracting published: ExtractPublished: published prop was not date time\n" requestID=8d8xg4ma04001z1aegx0 msg="Internal Server Error: wrote 54B"`

**Comment by alok0** [comment]
I'm also having trouble seeing both `stories@theverge.space` and `quickposts@theverge.space` i'm guessing it might have something to do with GtS wanting `url` to be unique but they are both set to `"https://www.theverge.com/"`

Does `url` need to be unique?

**Comment by zemlanin** [comment]
I've added `#stories`/`#quickposts` to those actor's URLs

**Comment by alok0** [comment]
🎉 ?

**Comment by zemlanin** [comment]
🎉

**Comment by tsmethurst** [comment]
> Does url need to be unique?

It doesn't *need* to be, so actually we should probably fix this: https://github.com/superseriousbusiness/gotosocial/issues/2082

**Comment by tsmethurst** [comment]
> error extracting published: ExtractPublished: published prop was not date time

Now that's kind of interesting.... I'll go look at the spec.

**Comment by tsmethurst** [comment]
Apparently `published` (https://www.w3.org/TR/activitystreams-vocabulary/#dfn-published) should be one of these bad boys: https://www.w3.org/TR/xmlschema-2/#dateTime.

`2023-08-20T11:54:06.289Z` looks OK to me following that spec, so this is likely a GtS bug to be fixed.

**Comment by zemlanin** [comment]
> `2023-08-20T11:54:06.289Z` looks OK to me following that spec, so this is likely a GtS bug to be fixed.

It was `null` when @alok0 posted [this comment](https://github.com/superseriousbusiness/gotosocial/issues/2135#issuecomment-1685267880)

**Comment by tsmethurst** [comment]
Ahh ok!

So stuff is working? Are you having fun @zemlanin? :') what a sunday

**Comment by zemlanin** [comment]
> So stuff is working?

Primary stuff works, but I still can't manage to send DMs to those who might mistake a bot for a human https://github.com/superseriousbusiness/gotosocial/issues/2135#issuecomment-1685265894

> Are you having fun? :') what a sunday

🥲

**Comment by alok0** [comment]
`timestamp="20/08/2023 13:28:07.478" func=typeutils.(*converter).ASStatusToStatus level=WARN statusURI=https://theverge.space/actor/wes_davis/note/7c76816f-f019-4256-ad62-ed6d60792ed7/reply-1692538087398-000008 requestID=5ym224wa04001jezjppg msg="error extracting mentions: ExtractMention: name prop empty"
`

**Comment by tsmethurst** [comment]
`tag: [ { type: 'Mention', href: 'https://goblin.technology/@zemlanin' } ]`

GtS expects mentions to look like this:

```json
{
	"type": "Mention",
	"href": "https://gts.superseriousbusiness.org/users/gotosocial",
	"name": "@gotosocial@superseriousbusiness.org"
}
```

So, `href` is the AP URI/ID of the mentioned account, not the web URL, and `name` is in the `@[username]@[domain]` format, similar to this example: https://www.w3.org/TR/activitystreams-vocabulary/#ex197-jsonld

**Comment by zemlanin** [comment]
Why's `name` required? Isn't `href` be enough to find DM's recipient?

**Comment by tsmethurst** [comment]
True true, we probably don't need it. Originally we just cribbed from the way Mastodon formats mention to ensure compatibility with other softwares, but we could for sure update our parsing logic to not require `name` anymore, or only require one of name or href, something along those lines.

**Comment by tsmethurst** [comment]
Shall I close this issue now, since things seem to be working? :)

**Comment by zemlanin** [comment]
It's the question for @alok0 to answer, but I guess?..

But-but, `name`less Mentions and 4XX (with some description?) instead of a server error on activity without `published` (and, i assume, other required fields) as separate issues?

**Comment by alok0** [comment]
Sure this seems to be solved. I suppose the Mentions can be a separate issue.
