### ISSUE TITLE
[bug] backend filesystem lock prevents deployment restart

### ISSUE THREAD

**Issue by sschnabe** [superseriousbusiness/gotosocial#2137]
### Describe the bug with a clear and concise description of what the bug is.

I'm using gotosocial with postgres in k3s on my homeserver. gotosocial has a persistent volume with hostPath.

If the deployment restarts the new pod does not start with this log (the old pod is already running):

```
timestamp="19/08/2023 19:05:33.904" func=cache.(*VisibilityCache).Init level=INFO msg="Visibility cache size = 5618"
timestamp="19/08/2023 19:05:33.904" func=cache.(*Caches).Start level=INFO msg="start: 0xc000896fc0"
timestamp="19/08/2023 19:05:33.913" func=bundb.pgConn level=INFO msg="connected to POSTGRES database"
timestamp="19/08/2023 19:05:33.922" func=bundb.doMigration level=INFO msg="there are no new migrations to run"
timestamp="19/08/2023 19:05:33.931" func=bundb.(*adminDB).CreateInstanceAccount level=INFO msg="instance account *** already exists"
timestamp="19/08/2023 19:05:33.933" func=bundb.(*adminDB).CreateInstanceInstance level=INFO msg="instance entry already exists"
timestamp="19/08/2023 19:05:33.933" func=cache.(*Caches).Stop level=INFO msg="stop: 0xc000896fc0"
2023/08/19 19:05:33 error executing command: error creating storage backend: error opening disk storage: store/storage: storage lock already open
```

From my point of view there should be no lock to enable restarting the instance. I've searched, but did not find a related issue. Any idea? 

Thanks for developing gotosocial!

### What's your GoToSocial Version?

0.11.0

### GoToSocial Arch

docker amd64

**Comment by tsmethurst** [comment]
Currently (for the sake of consistency) GtS doesn't support running multiple copies of the same instance, which precludes a rolling update strategy.

Can you try setting your strategy to recreate rather than the default? https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment Then it should only ever run one pod at a time (ie., wait for the old pod to be destroyed before launching a new one).

**Comment by sschnabe** [comment]
With this workaround it works (i've deployed gts this way currently).

I was aware of #1749, but didn't noticed that this includes rolling deployments of a single instance. Maybe add a hint to #1749?

**Comment by tsmethurst** [comment]
Aha! Glad it works :)

Since you mentioned that issue, this issue is now linked from there, so folks should be able to find it. Shall I close this issue now, since you've got things running?

**Comment by sschnabe** [comment]
Works, closing this issue.
