### ISSUE TITLE
[docs] When to tweak advanced-throttling-retry-after

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2139]
### Describe the bug with a clear and concise description of what the bug is.

With the 0.11.0 upgrade I had reset my `advanced-throttling-retry-after` from `45s` to the default of `30s`.

Over the weekend I noticed I was barely getting any new posts; sometimes I could load some by going to a user’s profile but that’s it.

Back home I saw lots of 429 in the log and bumped that value up to `60s` (and reduced the cache target because I saw GtS using 1.2 GiB virtual size in top), and now, a short while after restarting it, posts are trickling in again as usual.

### What's your GoToSocial Version?

v0.11.0

### GoToSocial Arch

amd64 binary

### Anything else we need to know?

If there is, just ask!

**Comment by tsmethurst** [comment]
I'm not really sure what the bug is here, or what you want to be fixed/changed, please can you explain?

**Comment by tsmethurst** [comment]
This issue prompted me to do a bit of digging.

It's not the throttler that serves `429` codes, the throttler serves `503` codes. It's the rate-limiter returning those `429` codes. So I think changing the throttling settings was a placebo in this case: the real 'fix' was just restarting the instance and thereby clearing the in-memory cache of the rate-limiter.

If you were getting 429's for everything, and you have your reverse proxy configured correctly, and trusted-proxies set correctly in your config, then this suggests there might be a bug in the rate limiter where it's not getting reset properly or something. So I'll do a bit more digging :)

**Comment by mirabilos** [comment]
Agreed.

I got some 429s from @benjaminbhollon’s instance when reading some threads, but not enough to notice in normal operation.
