### ISSUE TITLE
[bug] `500 Internal Server Error` on malformed Activity

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2145]
Spotted by @alok0 here: https://github.com/superseriousbusiness/gotosocial/issues/2135#issuecomment-1685267880

`timestamp="20/08/2023 12:08:01.095" func=middleware.Logger.func1.1 level=ERROR latency="4.41176ms" userAgent="fetch (https://theverge.space)" method=POST statusCode=500 path=/users/********/inbox clientIP=3.239.85.123 error="Error #01: PostInboxScheme: error calling sideEffectActor.PostInbox: Announce: error converting announce to boost: ASAnnounceToStatus: error extracting published: ExtractPublished: published prop was not date time\n" requestID=8d8xg4ma04001z1aegx0 msg="Internal Server Error: wrote 54B"`

We ought to return 400 in such cases, rather than 500-ing. The end!

**Comment by zemlanin** [comment]
Might be the same or similar bug: I'm getting 500 when sending this `Update` activity for an actor to a server running `0.11.1-SNAPSHOT git-13f1c85`:

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "ostatus": "http://ostatus.org#",
      "conversation": "ostatus:conversation"
    }
  ],
  "id": "https://theverge.space/actor/wes_davis#message-Update-1693034968039-000001",
  "to": ["https://www.w3.org/ns/activitystreams#Public"],

  "type": "Update",
  "object": "https://theverge.space/actor/wes_davis",
  "published": "2023-08-26T07:29:28.039Z",
  "actor": "https://theverge.space/actor/wes_davis"
}
```
