### ISSUE TITLE
Replies do not trigger notifications

### ISSUE THREAD

**Issue by NyaaaWhatsUpDoc** [superseriousbusiness/gotosocial#215]

**Comment by tsmethurst** [comment]
I also saw this behavior -- I think it's something to do with mentions on incoming messages still not being parsed correctly; i noticed for a status in which I was mentioned (as i saw in the timeline) that there was no corresponding mention in the database for it.

**Comment by tsmethurst** [comment]
Places to look:

https://github.com/superseriousbusiness/gotosocial/blob/main/internal/typeutils/astointernal.go#L221-L226

https://github.com/superseriousbusiness/gotosocial/blob/8a18017389bec393239ababc939a93d31ad49b13/internal/ap/extract.go#L527-L584

https://github.com/superseriousbusiness/gotosocial/blob/main/internal/federation/dereferencing/status.go#L296-L384
