### ISSUE TITLE
[bug] Posts CSS: <h2> is bigger than <h1>

### ISSUE THREAD

**Issue by raphaelmartin** [superseriousbusiness/gotosocial#2150]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

Posts (/statuses/XXX) pages composed with Markdown heading tags (`#, ##, ###`...) render `<h1>` as 1em (16px) and `<h2>` as 1.5em (24px).

# h1

<img width="853" alt="Capture d’écran 2023-08-22 à 17 38 45" src="https://github.com/superseriousbusiness/gotosocial/assets/6185710/af3bfc92-d899-466a-99fc-29ace047117c">

# h2

<img width="809" alt="Capture d’écran 2023-08-22 à 17 39 20" src="https://github.com/superseriousbusiness/gotosocial/assets/6185710/21618880-8260-4453-b037-1f75009d0b52">

### What's your GoToSocial Version?

v0.11.0 Sloppy Sloth

### Browser version

Chrome 116.0.5845.96 (arm64)

### What you expected to happen?

`<h1>` should be bigger than `<h2>`, `<h3>`, etc.

### How to reproduce it?

Visible on any profile page /@username

**Comment by tsmethurst** [comment]
Thanks! Will check this out.
