### ISSUE TITLE
[bug] Admin settings are not shown

### ISSUE THREAD

**Issue by Tsuribori** [superseriousbusiness/gotosocial#2154]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

When logging in as an admin user the admin settings are still not shown.

User is admin:
```shell
user account                    approved admin moderator suspended confirmed
<redacted> <redacted>    yes      yes   yes       no        yes

```

Going to `/settings` and logging in results in a following:

![Screenshot_2023-08-23_20-18-23](https://github.com/superseriousbusiness/gotosocial/assets/30933799/c7aa44d8-0fbd-4dac-b3fe-16099c92c4c3)

After which the settings page contains no admin options:

![Screenshot_2023-08-23_20-24-54](https://github.com/superseriousbusiness/gotosocial/assets/30933799/9f2c8bb8-be4f-4ced-a34f-ec0a4497f3f2)

### What's your GoToSocial Version?

0.11.1

### Browser version

Firefox 102.13.0esr (64-bit)

### What happened?

No admin settings are shown for an admin user

### What you expected to happen?

That admin settings are shown for an admin user

### How to reproduce it?

* Set up a gotosocial container using the [container docs](https://docs.gotosocial.org/en/latest/getting_started/installation/container/)
* Create admin user through the [container instructions](https://docs.gotosocial.org/en/latest/getting_started/user_creation/#containers)
* Log in using `/settings` path to the settings view

### Anything else we need to know?

I logged in through a Tusky app before attempting to log in using the web UI if it can have any significance.

**Comment by tsmethurst** [comment]
Could you first try restarting the container and see if that helps? It may be a caching issue, not sure.

**Comment by tsmethurst** [comment]
Aha, yes it's known behavior. Gotosocial has an in memory cache which the admin cli doesn't update. Eventually we'll need to fix this behavior but for now I'll add some extra lines to the docs about it.
