### ISSUE TITLE
[bug]use Dockerfile building

### ISSUE THREAD

**Issue by jkjoy** [superseriousbusiness/gotosocial#2156]
### Describe the bug with a clear and concise description of what the bug is.

```
error: failed to solve: failed to compute cache key: failed to calculate checksum of ref 540ok3uijgphc4wh46czb7lfn::foq1nw1dl1bcpwf31l2d3rzye: "/gotosocial": not found
```

### What's your GoToSocial Version?

latest

### GoToSocial Arch

amd64

### What happened?

```
error: failed to solve: failed to compute cache key: failed to calculate checksum of ref 540ok3uijgphc4wh46czb7lfn::foq1nw1dl1bcpwf31l2d3rzye: "/gotosocial": not found
```

### How to reproduce it?

docker cannot be created properly

**Comment by tsmethurst** [comment]
We have a whole section in the docs for building: https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md#building-gotosocial
