### ISSUE TITLE
Promote instance creation through companies like DigitalOcean

### ISSUE THREAD

**Issue by hypervalley** [superseriousbusiness/gotosocial#2160]
As a contributor, I hope that a cloud service for creating instances (including docker-based ones) will be made available. This way, your code can be effectively tested by non-programmers. E.g. DigitalOcean's 1-Click App.

**Comment by tsmethurst** [comment]
There's no way we're gonna do free advertising for corpo cloud providers. For self-hosters there's already yunohost packaging and various other methods of installing the software which don't require someone to be a programmer. In future we might look into some kind of provided hosting solution like masto.host but that's probably way off.
