### ISSUE TITLE
[bug] GoToSocial gets the correct user IP

### ISSUE THREAD

**Issue by aaro-n** [superseriousbusiness/gotosocial#2161]
### Describe the bug with a clear and concise description of what the bug is.

I use Docker to run GoToSocial, the `clientIP` IP in the Docker log is the LAN IP, set the environment variable to `GTS_REQUEST_ID_HEADER = "x-forwarded-for"`, the `clientIP` IP is still the LAN IP, and there is `requestID="39.171.xxx.xxx, xx:xxx:1::1c:5515"`, I want clientIP to be the real IP of the user.

### What's your GoToSocial Version?

0.11.1

### GoToSocial Arch

and64,Docker

### What happened?

Enable `GTS_REQUEST_ID_HEADER = "x-forwarded-for"`, log`clientIP=172.16.139.58 requestID="39.xx.xx.173, xxx:8280:1::1c:xx"`

### What you expected to happen?

Enable `GTS_REQUEST_ID_HEADER = "x-forwarded-for"`, log`clientIP=39.xx.xx.173 requestID="39.xx.xx.173, xxx:8280:1::1c:xx"`,Should be changed from `clientIP=172.16.139.58` to `clientIP=39.xx.xx.173`

### How to reproduce it?

can always be reproduced。

### Anything else we need to know?

I don't understand whether `clientIP` in the GoToSocial log is the user IP. If the question raised is wrong or does not affect the function of GoToSocial, please close this question.

**Comment by tsmethurst** [comment]
You need to set `GTS_TRUSTED_PROXIES` by adding the IP address of your proxy to the list.

For example:

```env
GTS_TRUSTED_PROXIES="172.16.139.58"
```

**Comment by aaro-n** [comment]
Thanks for the reply, the method you said is useful, but there is still a problem.

Enable `GTS_REQUEST_ID_HEADER = "x-forwarded-for"`,Docker log： 
`clientIP=172.16.139.58 requestID="49.xx.xx.93, 2a09:zz:z::cc:5515" `

`172.16.139.58`:The local IP should be removed.  

`49.xx.xx.93`:The user accesses the IP, which is required, and the IP will change when different users access it.

`2a09:zz:z::cc:5515`:This is the server IP, but pay attention to my network structure,` user--Cloudflre (CDN)--Nginx (image static file cache)--Fly.io load balancing--GoToSocial (Docker)`

Modify the configuration file to:
```
  GTS_REQUEST_ID_HEADER = "x-forwarded-for"
  GTS_TRUSTED_PROXIES = "172.16.139.58"
```
The log after reboot is: `clientIP= 2a09:zz:z::cc:5515 requestID="49.xx.xx.93, 2a09:zz:z::cc:5515" `,The IP obtained by `clientIP` is the IP of Fly.io load balancing, which is not what I need. Continue to modify the configuration file as follows:
```
  GTS_REQUEST_ID_HEADER = "x-forwarded-for"
  GTS_TRUSTED_PROXIES = "172.16.139.58,2a09:zz:z::cc:5515"
```
Re-run the container and get the running log:`clientIP=49.xx.xx.93 requestID="49.xx.xx.93, 2a09:zz:z::cc:5515"`,This running log is correct, but there are doubts. There are two IPs obtained by `requestID`, one is the user IP, and the other is the last public network IP. Will `requestID` obtain 3 or more IPs?
Now this issue is solved, please close this issue if there are no other issues.

**Comment by tsmethurst** [comment]
`GTS_REQUEST_ID_HEADER = "x-forwarded-for"` is an incorrect setting, you should just remove that entirely.

**Comment by aaro-n** [comment]
Understand I will delete this variable.
# Now GoToSocial obtains the user IP as follows:
* `clientIP=172.16.139.58`,It is the intranet IP, not the user IP, set `GTS_TRUSTED_PROXIES = "172.16.139.58`
* `clientIP=2a09:zz:z::cc:5515`,This IP is the public IP of the server, not the required user IP. Therefore set`GTS_TRUSTED_PROXIES = "172.16.139.58,2a09:zz:z::cc:5515"`
* `clientIP=49.xx.xx.93`,This IP is the correct user IP.

Problem solved, close issue.
