### ISSUE TITLE
[bug] SSL Verification error on subdomain

### ISSUE THREAD

**Issue by AndreasThinks** [superseriousbusiness/gotosocial#2162]
### Describe the bug with a clear and concise description of what the bug is.

I'm running GoToSocial through a container on a subdomain, and having issues with the remote SSL certificate being verified by other instances when I try and follow accounts... so I'm getting an error 503, SSL Certificate Could Not be Verified error.

Does anybody have any ideas? My primary domain.com forwards to a github pages, while socia.domain.com forwards to my GoToSocial. It *might* be a conflict between existing SSL on my primary domain?

### What's your GoToSocial Version?

GoToSocial 0.11.1

**Comment by tsmethurst** [comment]
Or your SSL isn't working? Have you tried arresting it? Get outta here copper.
