### ISSUE TITLE
[bug] Empty federated timeline

### ISSUE THREAD

**Issue by lamons** [superseriousbusiness/gotosocial#2163]
### Describe the bug with a clear and concise description of what the bug is.

I built an GtS instance and have been using it for months, all features seems fine, but the federated timeline has been always empty.

I and other users of this instance have followed some people on other instances and are able to see their post on our personal timelines with no problem.

> home to 5 users who posted 3 statuses, federating with 38 other instances.

### What's your GoToSocial Version?

0.11.1 git-c7a46e0

### GoToSocial Arch

Docker

### What happened?

The instance is built on a CentOS 7 server at June, using the docker installation with :latest tag. I just pulled the 0.11.1 update yesterday but the issue persists. 

### What you expected to happen?

Federated timeline works as it should be.

**Comment by tsmethurst** [comment]
Heya! Empty like mostly empty, or empty like completely empty with no posts at all?

**Comment by lamons** [comment]
@tsmethurst Hi! There is no posts at all on federated timeline. Personal timelines and local timeline seems working fine. I tested on Semaphore and some iOS clients and all got the same issue so doesn't seems like an issue on client side.

**Comment by tsmethurst** [comment]
Hmm okay, that's a bit strange. Do you follow accounts that post/boost Public statuses? The public/federated timeline only contains non-reply Public visibility posts that your server becomes aware of, through accounts you follow posting, boosting, or replying to things. 

Could you maybe try searching for the following status from your instance, then checking the federated timeline to see if it shows up there?

https://gts.superseriousbusiness.org/@gotosocial/statuses/01H8CDEXZDDTK3EYQ4VKN217EA

If it doesn't, do you see any logs on your GtS server process when loading the federated timeline, which might indicate an error?

**Comment by tsmethurst** [comment]
Stranger and stranger! Thanks for checking.

The log lines you sent suggest that when GtS does the SELECT from the database to get Public posts, it's just not getting anything, and then it returns an empty JSON array (`[]`) without any errors.

Do the log lines for ` /api/v1/timelines/public` look the same when you use Semaphore or Pinafore to check the public timeline? I just wanna eliminate the possibility that Tusker is doing something odd with its query parameters which is leading to 0 being returned.

---

By the way, this is unrelated to the issue but it looks like you've not got your `trusted-proxies` / `GTS_TRUSTED_PROXIES` configured correctly. This is why all your client IPs show as `172.18.0.1`, which I guess is your Docker network gateway? You should probably consider adding `172.18.0.1` to trusted proxies to ensure that GtS can differentiate between clients, otherwise they'll all fall under the same rate limiter bucket and end up rate limiting each other.

**Comment by lamons** [comment]
This is the server response when loading federated timeline with Semaphore, doesn't look very different though:

```
gotosocial  | timestamp="27/08/2023 09:09:25.938" func=streaming.(*Module).handleWSConn level=INFO username=bbp streamID=016A4GDBRG8CB7CQ80NPPXMGK7 msg="closed websocket connection"
gotosocial  | timestamp="27/08/2023 09:09:25.941" func=streaming.(*Module).handleWSConn level=INFO username=bbp streamID=01F4Q8V8VJ18TCMWDDXK4SDF74 msg="closed websocket connection"
gotosocial  | timestamp="27/08/2023 09:09:27.300" func=server.glob..func1.Logger.func13.1 level=INFO latency="2.470389ms" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" method=GET statusCode=200 path=/api/v1/instance clientIP=172.68.234.134 requestID=g5d42dma040003e7mp9g msg="OK: wrote 582B"
gotosocial  | timestamp="27/08/2023 09:09:27.324" func=server.glob..func1.Logger.func13.1 level=INFO latency="1.562247ms" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" method=GET statusCode=200 path=/api/v1/timelines/public clientIP=172.68.234.134 requestID=k9d42dma04000jevd50g msg="OK: wrote 26B"
gotosocial  | timestamp="27/08/2023 09:09:27.377" func=server.glob..func1.Logger.func13.1 level=INFO latency="1.356566ms" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" method=GET statusCode=200 path=/api/v1/accounts/verify_credentials clientIP=172.68.234.228 requestID=t1d42dma04000ttsnpm0 msg="OK: wrote 655B"
gotosocial  | timestamp="27/08/2023 09:09:27.393" func=streaming.(*Module).StreamGETHandler level=INFO username=bbp streamID=01HMDQCBGS154DTQ4PEPA5BK16 requestID=w1d42dma0400083ggq60 msg="opened websocket connection"
gotosocial  | timestamp="27/08/2023 09:09:27.393" func=server.glob..func1.Logger.func13.1 level=INFO latency="1.181635ms" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" method=GET statusCode=200 path=/api/v1/streaming clientIP=172.68.234.154 requestID=w1d42dma0400083ggq60 msg="OK: wrote 0B"
gotosocial  | 2023/08/27 09:09:27 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:83)
gotosocial  | timestamp="27/08/2023 09:09:28.288" func=server.glob..func1.Logger.func13.1 level=INFO latency="1.726647ms" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" method=GET statusCode=200 path=/api/v1/instance clientIP=172.68.234.229 requestID=bsf42dma04000a9btyrg msg="OK: wrote 582B"
gotosocial  | timestamp="27/08/2023 09:09:28.416" func=streaming.(*Module).StreamGETHandler level=INFO username=bbp streamID=01A39SC2X8Q13MYYNMGGTG0WDV requestID=w1f42dma04001cttqt60 msg="opened websocket connection"
gotosocial  | timestamp="27/08/2023 09:09:28.417" func=server.glob..func1.Logger.func13.1 level=INFO latency="977.112µs" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" method=GET statusCode=200 path=/api/v1/streaming clientIP=172.68.234.232 requestID=w1f42dma04001cttqt60 msg="OK: wrote 0B"
gotosocial  | 2023/08/27 09:09:28 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:83)
gotosocial  | timestamp="27/08/2023 09:09:36.084" func=server.glob..func1.Logger.func13.1 level=INFO latency="1.336154ms" userAgent="Poduptime/Production from https://fediverse.observer" method=GET statusCode=200 path=/.well-known/nodeinfo clientIP=172.71.151.9 requestID=tdy42dma04000sp4g840 msg="OK: wrote 115B"
gotosocial  | timestamp="27/08/2023 09:09:36.215" func=server.glob..func1.Logger.func13.1 level=INFO latency="1.907818ms" userAgent="Poduptime/Production from https://fediverse.observer" method=GET statusCode=200 path=/nodeinfo/2.0 clientIP=172.71.147.90 requestID=anym2dma04000v8fgn9g msg="OK: wrote 194B"
```
Also thanks for the tip about trusted proxies!

**Comment by tsmethurst** [comment]
> Also thanks for the tip about trusted proxies!

No problem. Since it looks like you're behind Cloudflare, you probably also want to add the Cloudflare IP range for your region (`172.64.0.0/13` I think) to trusted proxies too (comma-separate entries if you're using env vars). See https://www.cloudflare.com/ips/.

Anyway, will look into this public timeline issue before we do the next release, very odd that no statuses are being selected.

**Comment by lamons** [comment]
Cool, let me know if there's anything need me to test!

**Comment by lamons** [comment]
> Heya, could you confirm if this issue is still showing up?

Looks like it's working now, thanks!
