### ISSUE TITLE
[feature/bugfix] Admin action for remote public key rotation

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2170]
Right now, GoToSocial isn't able to support cases where remote instances have to rotate their private + public keys (using `tootctl accounts rotate`, for Mastodon) due to data leakage, bugs, data loss, other issues.

This manifests as GoToSocial returning 401s to requests from remote instances in cases where the remote instance admin has had to rotate their keys. GtS keeps the old key cached, and tries to verify the incoming signature against the old key. Since the signature has been created with the new key, GtS rejects the request because it looks like a forgery.

It would probably be a good idea to support key rotation in a basic way for now to alleviate cases like this. Perhaps we could allow an admin, via the API, to wipe all keys for accounts from a specific instance, and code some logic to refetch them again when each account is next seen. At least then, admins could try to fix federation with specific instances by wiping their keys.

Whatever logic we end up using for this could be the basis for configurable automated key rotation, but that's way out of scope for this issue.

See this thread for context: https://queer.af/@erincandescent/110983340023366569

**Comment by NyaaaWhatsUpDoc** [comment]
How does Mastodon handle key rotation with secure fetch enabled? Is there an AP activity sent out indicating signature invalidation?

**Comment by erincandescent** [comment]
> How does Mastodon handle key rotation with secure fetch enabled? Is there an AP activity sent out indicating signature invalidation?

Mastodon sends out an update activity for the actor containing the new key, signed with the old key

**Comment by erincandescent** [comment]
The key rotation logic was [implemented here](https://github.com/mastodon/mastodon/pull/8466/files). It may have changed since

**Comment by tsmethurst** [comment]
> Mastodon sends out an update activity for the actor containing the new key, signed with the old key

Interesting! OK, we should try to handle that as well then :)

**Comment by hikari-no-yume** [comment]
Hi everyone. I just YOLO-upgraded my server to 4b594516ec5fe6d849663d877db5a0614de03089 and used the new UI added in #2183 to expire all the keys for @erincandescent's instance, and I am happy to confirm that this seems to have fixed the federation between my instance and theirs; users on their instance now receive new posts from me again. Thanks!
