### ISSUE TITLE
[bug] List rename not reflected in Tusky

### ISSUE THREAD

**Issue by decentral1se** [superseriousbusiness/gotosocial#2188]
### Describe the bug with a clear and concise description of what the bug is.

Renaming a list from "foo" to "bar" does not update the name of the list in the timeline view.

### What's your GoToSocial Version?

v0.11.x

### GoToSocial Arch

x86_64

### What happened?

I renamed the list in the lists management interface in Tusky. Then I viewed the list in the main timeline view where I have it configured as a tab. The name did not change.

### What you expected to happen?

The new name of the list will be shown.

### How to reproduce it?

1. Create a new list
2. Configure the list to show in a tab on the timeline view (`Account preferences > Tabs`)
3. Rename the list
4. View the list in the timeline view as a tab

### Anything else we need to know?

I checked Tusky and there doesn't seem to anything open there for it:

> https://github.com/tuskyapp/Tusky/issues?q=is%3Aissue+rename

**Comment by tsmethurst** [comment]
I just checked and this exhibits the same behavior on mastodon too, so I think this may be a Tusky issue rather than a GtS issue!

**Comment by decentral1se** [comment]
Thanks! Moved over to https://github.com/tuskyapp/Tusky/issues/4011 then :running_woman:

**Comment by decentral1se** [comment]
Looping back for anyone else, it is indeed a Tusky issue: https://github.com/tuskyapp/Tusky/issues/4011#issuecomment-1713442093
