### ISSUE TITLE
[bug] Errors while generating client from swagger definition

### ISSUE THREAD

**Issue by decentral1se** [superseriousbusiness/gotosocial#2196]
### Describe the bug with a clear and concise description of what the bug is.

Firstly with validation:

> swagger generate client -f ./docs/api/swagger.yaml -A go-gts
> 2023/09/11 23:47:34 validating spec .../docs/api/swagger.yaml
> The swagger spec at ".../docs/api/swagger.yaml" is invalid against swagger specification 2.0. see errors :
> - "paths./api/v1/reports.post.parameters" must validate one and only one schema (oneOf). Found none valid
> - paths./api/v1/reports.post.parameters.example in body is a forbidden property
> - paths./api/v1/reports.post.parameters.in in body should be one of [header]
> - "paths./api/v1/list.post.parameters" must validate one and only one schema (oneOf). Found none valid
> - paths./api/v1/list.post.parameters.example in body is a forbidden property
> - paths./api/v1/list.post.parameters.in in body should be one of [header]
> - "paths./api/v1/list.put.parameters" must validate one and only one schema (oneOf). Found none valid
> - paths./api/v1/list.put.parameters.example in body is a forbidden property
> - paths./api/v1/list.put.parameters.in in body should be one of [header]
> - "paths./api/v1/accounts/update_credentials.patch.parameters" must validate one and only one schema (oneOf). Found none valid
> - paths./api/v1/accounts/update_credentials.patch.parameters.items.type in body should be one of [string number integer boolean array]
> - paths./api/v1/accounts/update_credentials.patch.parameters.in in body should be one of [header]
> - "paths./api/v1/admin/reports/{id}/resolve.post.parameters" must validate one and only one schema (oneOf). Found none valid
> - paths./api/v1/admin/reports/{id}/resolve.post.parameters.example in body is a forbidden property
> - paths./api/v1/admin/reports/{id}/resolve.post.parameters.in in body should be one of [header]

Then without validation, running into this showstopper:

> $ swagger generate client --skip-validation -f docs/api/swagger.yaml -A go-gts
> 2023/09/11 23:49:55 preprocessing spec with option:  minimal flattening
> 2023/09/11 23:49:56 building a plan for generation
> 2023/09/11 23:49:56 generation target ./
> 2023/09/11 23:49:56 planning definitions (found: 69)
> 2023/09/11 23:49:57 planning operations (found: 89)
> object has no key "adminEmojiCategory"

I can try fix up stuff if someone shares some pointers!

### What's your GoToSocial Version?

v0.11.x

### GoToSocial Arch

x86_64

### What happened?

Client was not generated.

### What you expected to happen?

Client is generated.

### How to reproduce it?

`swagger generate client -f ./docs/api/swagger.yaml -A go-gts`

**Comment by tsmethurst** [comment]
Darn, looks like we'd have to fix a lot of stuff! V. low priority, but thank you for posting the errors!
