### ISSUE TITLE
[bug] Hashtags can't contain underscores?

### ISSUE THREAD

**Issue by hikari-no-yume** [superseriousbusiness/gotosocial#2199]
### Describe the bug with a clear and concise description of what the bug is.

Apparently, GTS considers a hashtag to be terminated when it encounters an underscore, which is a bit of a surprise coming from Twitter, and doesn't seem to match (some versions of?) Mastodon.

Example post where the GTS behaviour can be seen and compared against Mastodon: https://social.noyu.me/@hikari/statuses/01HA5B4KBHEQAG8GBCBZTRB3F8.

I'm not _certain_ this is a GTS issue, but it happens both in Pinafore's UI and on the web page, and I notice GTS has a function called `IsPermittedInHashtag` that doesn't permit underscores, so it probably is?

I have no idea if there's a spec around what characters a hashtag should be able to contain. If it were up to me, I might let the server admin specify a regex in `config.yaml`.

### What's your GoToSocial Version?

GoToSocial 0.11.1-SNAPSHOT git-4b59451

### GoToSocial Arch

amd64 binary

### What happened?

I wrote `#hikari_no_yumeposting` in a post using Pinafore and posted it on my GoToSocial instance. GTS seems to regard `#hikari` as the hashtag.

### What you expected to happen?

GTS would regard `#hikari_no_yumeposting` as the hashtag.

### Anything else we need to know?

Would a behaviour change apply retroactively? Could that be problematic?

**Comment by tsmethurst** [comment]
Oh! That's quite surprising indeed. We probably just missed something in the logic we use to derive hashtags. Will add this to the 0.12.0 milestone, thanks for opening!
