### ISSUE TITLE
[bug] I got an error migrating from one server to another

### ISSUE THREAD

**Issue by Salomens** [superseriousbusiness/gotosocial#2203]
### Describe the bug with a clear and concise description of what the bug is.

After I migrated the sqlite files and media files to a new machine, I opened the settings page and an error occurred. The error message was 500: Internal Server Error.
[gotosocial-20230916213645.log](https://github.com/superseriousbusiness/gotosocial/files/12640812/gotosocial-20230916213645.log)

### What's your GoToSocial Version?

GoToSocial 0.11.1 git-c7a46e0

### GoToSocial Arch

amd64 docker

**Comment by daenney** [comment]
Your logs state "attempt to write a readonly database" multiple times. It seems your new GtS process doesn't have the necessary permissions to write to the directory the SQLite database is stored in, or the database files itself. They might be owned by the wrong user/group combination, or it's the actual file permissions itself.

**Comment by Salomens** [comment]
> Your logs state "attempt to write a readonly database" multiple times. It seems your new GtS process doesn't have the necessary permissions to write to the directory the SQLite database is stored in, or the database files itself. They might be owned by the wrong user/group combination, or it's the actual file permissions itself.

Thank you very much, pass the command sudo chown -R 1000:1000 /root/gotosocial/data
problem has been solved
