### ISSUE TITLE
[bug] sql: no rows in result set

### ISSUE THREAD

**Issue by 593kdk32idk32** [superseriousbusiness/gotosocial#2211]
### Describe the bug with a clear and concise description of what the bug is.

Several testing instances stopped working all of a sudden. No changes in code, or operation. They all have the same type of SQL errors. 

Here are two examples. 

```
1. AuthenticatePostInbox: could not fetch receiving account UserName: PopulateAccount: error populating account header: sql: no rows in result set\n" 
```

```
2. msg="recovered panic: error converting instance to api representation: InstanceToAPIV1Instance: db error getting instance account: PopulateAccount: error populating account avatar: sql: no rows in result set"
```
Note: UserName is a replacement for the actual account name. 

### What's your GoToSocial Version?

0.11.1 git-c7a46e0

### GoToSocial Arch

FreeBSD amd64 binary install

### What happened?

GoToSocial worked and then stopped working with SQL errors. No trigger that I can determine. 

### What you expected to happen?

GoToSocial to keep working as it had been.

### How to reproduce it?

Unfortunately I don't know. It seems to have happened suddenly without any discernible cause. 

### Anything else we need to know?

Is there any way to determine the exact SQL query that seems to be failing? I've manually checked the database and everything seems normal. The data is present and can be queried so far as I can tell. 

I'd appreciate any pointers as to where to look.

**Comment by tsmethurst** [comment]
Wow, that's a pretty wacky bug!

Couple questions to maybe help narrow things down:

- Which database type are you using, postgres or sqlite?
- Are these test instances running on the same machine, or different machines?
- Does the issue persist after restarting?

**Comment by 593kdk32idk32** [comment]
- The database is PostgreSQL 15.4
- Different machines, different Postgres instances.
- The issue persists after restarting GoToSocial, and Postgres. 

One instance was an upgrade from a previous version of GtS. The other was a clean installation only a few weeks old.

**Comment by 593kdk32idk32** [comment]
For reference, the account is seen in the database. 

Running this returns an account. 
```
./gotosocial --config-path config.yaml admin account list
```

**Comment by 593kdk32idk32** [comment]
Adding to this. I enabled trace logging with sql queries. I can copy out the sql queries and run them by hand. They work fine that way and return results. I'm not sure I'm correlating the errors with the right query though. 

Here's a snippet from the log. 

```
timestamp="18/09/2023 21:08:38.050" func=bundb.queryHook.AfterQuery level=TRACE duration=24.809747ms query=SELECT "token"."id", "token"."created_at", "token"."updated_at", "token"."client_id", "token"."user_id", "token"."redirect_uri", "token"."scope", "token"."code", "token"."code_challenge", "token"."code_challenge_method", "token"."code_create_at", "token"."code_expires_at", "token"."access", "token"."access_create_at", "token"."access_expires_at", "token"."refresh", "token"."refresh_create_at", "token"."refresh_expires_at" FROM "tokens" AS "token"
timestamp="18/09/2023 21:09:27.874" func=bundb.queryHook.AfterQuery level=TRACE duration=4.192736ms query=SELECT "instance"."id", "instance"."created_at", "instance"."updated_at", "instance"."domain", "instance"."title", "instance"."uri", "instance"."suspended_at", "instance"."domain_block_id", "instance"."short_description", "instance"."description", "instance"."terms", "instance"."contact_email", "instance"."contact_account_username", "instance"."contact_account_id", "instance"."reputation", "instance"."version" FROM "instances" AS "instance" WHERE ("instance"."domain" = 'example.com')
timestamp="18/09/2023 21:09:27.887" func=bundb.queryHook.AfterQuery level=TRACE duration=12.467313ms query=SELECT count(*) FROM "accounts" AS "account" WHERE ("account"."username" != 'example.com') AND ("account"."suspended_at" IS NULL) AND ("account"."domain" IS NULL)
timestamp="18/09/2023 21:09:27.899" func=bundb.queryHook.AfterQuery level=TRACE duration=12.12574ms query=SELECT count(*) FROM "statuses" AS "status" WHERE ("status"."local" = TRUE)
timestamp="18/09/2023 21:09:27.900" func=bundb.queryHook.AfterQuery level=TRACE duration=362.969µs query=SELECT count(*) FROM "instances" AS "instance" WHERE ("instance"."domain" != 'example.com') AND ("instance"."suspended_at" IS NULL)
timestamp="18/09/2023 21:09:27.903" func=bundb.queryHook.AfterQuery level=TRACE duration=2.986527ms query=SELECT "account"."id", "account"."created_at", "account"."updated_at", "account"."fetched_at", "account"."username", "account"."domain", "account"."avatar_media_attachment_id", "account"."avatar_remote_url", "account"."header_media_attachment_id", "account"."header_remote_url", "account"."display_name", "account"."emojis", "account"."fields", "account"."fields_raw", "account"."note", "account"."note_raw", "account"."memorial", "account"."also_known_as", "account"."moved_to_account_id", "account"."bot", "account"."reason", "account"."locked", "account"."discoverable", "account"."privacy", "account"."sensitive", "account"."language", "account"."status_content_type", "account"."custom_css", "account"."uri", "account"."url", "account"."inbox_uri", "account"."shared_inbox_uri", "account"."outbox_uri", "account"."following_uri", "account"."followers_uri", "account"."featured_collection_uri", "account"."actor_type", "account"."private_key", "account"."public_key", "account"."public_key_uri", "account"."sensitized_at", "account"."silenced_at", "account"."suspended_at", "account"."hide_collections", "account"."suspension_origin", "account"."enable_rss" FROM "accounts" AS "account" WHERE ("account"."username" = 'example.com') AND ("account"."domain" IS NULL)
timestamp="18/09/2023 21:09:27.909" func=bundb.queryHook.AfterQuery level=TRACE duration=6.417566ms query=SELECT "media_attachment"."id", "media_attachment"."created_at", "media_attachment"."updated_at", "media_attachment"."status_id", "media_attachment"."url", "media_attachment"."remote_url", "media_attachment"."type", "media_attachment"."original_width", "media_attachment"."original_height", "media_attachment"."original_size", "media_attachment"."original_aspect", "media_attachment"."original_duration", "media_attachment"."original_framerate", "media_attachment"."original_bitrate", "media_attachment"."small_width", "media_attachment"."small_height", "media_attachment"."small_size", "media_attachment"."small_aspect", "media_attachment"."focus_x", "media_attachment"."focus_y", "media_attachment"."account_id", "media_attachment"."description", "media_attachment"."scheduled_status_id", "media_attachment"."blurhash", "media_attachment"."processing", "media_attachment"."file_path", "media_attachment"."file_content_type", "media_attachment"."file_file_size", "media_attachment"."file_updated_at", "media_attachment"."thumbnail_path", "media_attachment"."thumbnail_content_type", "media_attachment"."thumbnail_file_size", "media_attachment"."thumbnail_updated_at", "media_attachment"."thumbnail_url", "media_attachment"."thumbnail_remote_url", "media_attachment"."avatar", "media_attachment"."header", "media_attachment"."cached" FROM "media_attachments" AS "media_attachment" WHERE ("media_attachment"."id" = '01FZCEJGZ2SFX0SS9CRC5AS9CD')
timestamp="18/09/2023 21:09:27.910" func=bundb.queryHook.AfterQuery level=TRACE duration=158.975µs query=SELECT count(*) FROM "accounts" AS "account" WHERE ("account"."username" != 'example.com') AND ("account"."suspended_at" IS NULL) AND ("account"."domain" IS NULL)
timestamp="18/09/2023 21:09:27.910" func=bundb.queryHook.AfterQuery level=TRACE duration=189.135µs query=SELECT count(*) FROM "statuses" AS "status" WHERE ("status"."local" = TRUE)
timestamp="18/09/2023 21:09:27.910" func=bundb.queryHook.AfterQuery level=TRACE duration=121.034µs query=SELECT count(*) FROM "instances" AS "instance" WHERE ("instance"."domain" != 'example.com') AND ("instance"."suspended_at" IS NULL)
timestamp="18/09/2023 21:09:27.910" func=server.glob..func1.Logger.func13.1 level=ERROR stacktrace="util.genericErrorHandler()\n\t/drone/src/internal/api/util/errorhandling.go:72\nutil.ErrorHandler()\n\t/drone/src/internal/api/util/errorhandling.go:127\nutil.WebErrorHandler()\n\t/drone/src/internal/api/util/errorhandling.go:133\nweb.(*Module).baseHandler()\n\t/drone/src/internal/web/base.go:39\ngin.(*Context).Next()\n\t/drone/src/vendor/github.com/gin-gonic/gin/context.go:174\nserver.glob..func1.Logger.func13()\n\t/drone/src/internal/middleware/logger.go:115\ngin.(*Context).Next()\n\t/drone/src/vendor/github.com/gin-gonic/gin/context.go:174\ngin.(*Engine).handleHTTPRequest()\n\t/drone/src/vendor/github.com/gin-gonic/gin/gin.go:620\ngin.(*Engine).ServeHTTP()\n\t/drone/src/vendor/github.com/gin-gonic/gin/gin.go:576\n" requestID=qns21ama0400044ktgc0 msg="recovered panic: error converting instance to api representation: InstanceToAPIV1Instance: db error getting instance account: PopulateAccount: error populating account avatar: sql: no rows in result set"
timestamp="18/09/2023 21:09:27.910" func=server.glob..func1.Logger.func13.1 level=INFO latency="40.562005ms" userAgent="Mozilla/5.0 (Windows NT 10.0; rv:114.0) Gecko/20100101 Firefox/114.0" method=GET statusCode=200 path=/ clientIP=IP-REMOVED requestID=qns21ama0400044ktgc0 msg="OK: wrote 16.0EiB"
timestamp="18/09/2023 21:09:28.086" func=server.glob..func1.Logger.func13.1 level=INFO latency="62.493µs" userAgent="Mozilla/5.0 (Windows NT 10.0; rv:114.0) Gecko/20100101 Firefox/114.0" method=GET statusCode=404 path=/favicon.ico clientIP=IP-REMOVED requestID=jssj1ama04001cgavv10 msg="Not Found: wrote 21B"

```

**Comment by tsmethurst** [comment]
Hmmm. The important one in the latest logs you posted, to my eye, seems to be:

`SELECT * FROM "media_attachments" WHERE ("media_attachment"."id" = '01FZCEJGZ2SFX0SS9CRC5AS9CD')`

(translated the query a bit to use * instead of all those named columns)

That query seems to be one that's performed in order to fetch the instance thumbnail, which we store as the avatar of the instance account. That also lines up with the second error you posted in the original issue. Did you by any chance recently set/unset the instance thumbnail in the settings panel? Recently like, just before the issue appeared?

The first error you posted in the original issue is a bit different since it's not related to the instance account, but to another account.

The only link I can see between these two issues is that in both of them a media attachment is now missing in the database, but the media attachment ID is still set on the account, leading GtS to try to fetch the media attachment with the given ID from the database, and failing. You didn't happen to manually remove media from the storage folder did you? Just to maybe try to narrow down the cause.

Anyway, I *think* the following query would temporarily get things working again, by unsetting all headers + avatars for local accounts:

`UPDATE accounts SET (avatar_media_attachment_id, header_media_attachment_id) = (NULL, NULL) WHERE domain IS NULL;`

However that doesn't really help to identify what went wrong in the first place. The fact that it happened with two instances at the same time is kinda concerning :thinking:

**Comment by 593kdk32idk32** [comment]
Hello, 

Running this code did fix it. 

```
UPDATE accounts SET (avatar_media_attachment_id, header_media_attachment_id) = (NULL, NULL) WHERE domain IS NULL;
```

I had also done a recent restart of GoToSocial on both instances to work around https://github.com/superseriousbusiness/gotosocial/issues/2154 . 

On the instance I just fixed, I had updated the images though the web admin interface. 

I've reached out to the tester on the other instance, but I'm pretty sure they also updated images though the web interface.

**Comment by tsmethurst** [comment]
Alright, I'm glad the DB query sorted things out for now! That's something, at least. We'll try and find time soon to poke around and see if we can figure out what *caused* it. Thanks for raising the issue!

**Comment by 593kdk32idk32** [comment]
Is it safe to run multiple instances of GoToSocial concurrently, talking to a single PostgreSQL instance? Would having multiple instances cause issues in the database? 

I ask because I just tested the image upload with a single instance and the problem does not happen. But the cases where it did were running multiple instances.

**Comment by tsmethurst** [comment]
Oh... err... hmm... well as long as they're using different databases within that PostgreSQL instance it *should* be OK since they're logically separated (though we haven't tested this). But if they're using the same database then yes absolutely that will cause issues!

**Comment by 593kdk32idk32** [comment]
Sorry, I was not clear. 

It is one GoToSocial instance at one domain being run independently on three different servers. It has shared storage underneath so each instance sees the same files and runs off the same configuration. All three copies talk to the same database. The point is to load balance and provide fail over if a server running one of the instances goes down. 

But now I wonder if SQL inserts could end up being out of order and cause corruption.

**Comment by tsmethurst** [comment]
What, oh no! Multiple nodes/clustering is absolutely not supported yet. That will definitely cause major issues, since each instance also has an internal state held in an in-memory cache, so they're going to start diverging from each other almost immediately.

**Comment by 593kdk32idk32** [comment]
Ahhh, 

Then this issue is likely my fault and not a bug in GoToSocial. I'll run it single instance only from now on.

**Comment by tsmethurst** [comment]
Heh, okay, alright to close the issue then? You can follow multinode/cluster support here: https://github.com/superseriousbusiness/gotosocial/issues/1749 But as it says in the issue, it won't be a priority for quite a while since we're focusing on other stuff first.

**Comment by 593kdk32idk32** [comment]
Closing out as user error. Thank you for your help.

**Comment by tsmethurst** [comment]
No problemo!
