### ISSUE TITLE
[feature] Make maintenance task time configurable

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2212]
### Is your feature request related to a problem ?

I think at midnight server time (UTC in my case), some maintenance tasks run, making the system otherwise sluggish.

### Describe the solution you'd like.

I’d like to be able to configure the time this runs, to not coincide with either personal usage or backup times.

### Describe alternatives you've considered.

NONE

### Additional context.

Also, how do I figure out which tasks are run and when they end(ed), to have a rough idea of how long a timeslot I need to reserve for them? That is, for what do I need to grep in the logs?

**Comment by tsmethurst** [comment]
Good idea yeah; I think someone else recently requested the same thing in chat but we forgot to make an issue for it.

> Also, how do I figure out which tasks are run and when they end(ed), to have a rough idea of how long a timeslot I need to reserve for them? That is, for what do I need to grep in the logs?

I think if you grep 'prune' you should see entries in the logs for the tasks.
