### ISSUE TITLE
[bug] Inconsistent paging through local timeline; local timeline appears to end prematurely

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2213]
Sometimes while scrolling through the local timeline, a response will be returned from `api/v1/timelines/public?local=true` that contains an empty JSON array and no `Link` header, which causes clients to assume the end of the timeline has been reached, and stop trying to page through it (and indeed they *can't* page through it, because there's no link header to use).

To users, this gives the appearance that the local timeline just ends, or that it's being cleared beyond a certain time, but this is not the case.

I think the problem lies somewhere between the public timeline function in `internal/db/bundb/timeline.go` and the code for paging + filtering that timeline in `internal/processing/timeline/public.go`.

Interesting to note that this issue has probably been around a while, but we didn't notice it yet because nobody was really using the local timeline much, since almost all GtS instances have been single-user or very-few-users until now!

**Comment by benjaminbhollon** [comment]
Yeah, I figure me trying to start a relatively large server with GtS (currently alpha.polymaths.social, will move to the main domain once alpha ends) will probably uncover myriad bugs. ;)

Happy to look through any logs or do any diagnosing on this, by the way.

**Comment by NyaaaWhatsUpDoc** [comment]
this bug might be a good chance to update to the latest paging code :)

**Comment by benjaminbhollon** [comment]
Timeline "cleared" again. This time I can confirm there were zero posts, not just a limit to how many we could scroll through. There's one now, but for a good bit there were zero.

**Comment by benjaminbhollon** [comment]
The timeline is currently empty. `https://alpha.polymaths.social/api/v1/timelines/public?limit=20&local=true` returns `[]`

**Comment by tsmethurst** [comment]
^^ Found a fix :)

Turned out to be rather a simple bug -- classic oversight on my part.

**Comment by benjaminbhollon** [comment]
@tsmethurst We're still getting the timeline clearing after upgrading to rc1. :(

Any diagnostic I should look into?

**Comment by benjaminbhollon** [comment]
I can also open a new issue if you'd prefer that.

**Comment by benjaminbhollon** [comment]
It looks like even though the `link` header is being provided correctly, clients are ignoring it and just re-requesting the same link, setting the `maxid` parameter based on the last loaded status. Semaphore, for example, is just requesting the same URL over and over, even though the `next` value is present and points to a page with content. :P

**Comment by benjaminbhollon** [comment]
Checking with some of my users, it seems like whether it works or not now is client-dependent; some clients just can't handle empty timeline pages, whether or not there is a next link.

I'll open a new issue, since it's related but not the same.
