### ISSUE TITLE
[bug] some toots don’t load, even when specified by ID

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2215]
### Describe the bug with a clear and concise description of what the bug is.

A few days ago, I had the following issue, which I’m reporting by request of Tobi and it’s still reproducible.

Background: some days ago (before that), another user account on my instance (CVS commit mail to Fediverse conversion bot) had posted a status with Visibility=Unlisted, as usual, which I then replied to.

Now I wanted to pull up that reply to reply to it again, to provide updated information (also to those who interacted with the original post, if any). I could not find it in my home timeline or my own “posts and replies” for some reason, though I *could* find older posts.

So I went to the PostgreSQL to search, as usual. I eventually found that post, and doing an otherwise unconstrained `SELECT id,content FROM statuses WHERE content LIKE '%`*some text from the post*`%' ORDER BY id;` showed that exactly one ID matches it, so I’m positive the ID is not of a boost.

I then proceeded to plug that ID into Semaphore as usual: `https://semaphore.social/statuses/01HA644YWD5M4F8RS3W9XSGRDD`

This, however, caused merely an “Internet request failed. Showing offline content.” popup and a spinning animation, and this is reproducible. This normally works, I’ve been using that method multiple times a month.

The F12-Network tab reports a `GET /api/v1/statuses/01HA644YWD5M4F8RS3W9XSGRDD` that 404s with the response `{"error":"Not Found"}`.

The “interesting” log lines are probably:

```
timestamp="20/09/2023 17:19:43.306" func=server.glob..func1.Logger.func13.1 level=INFO latency="13.807µs" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" method=OPTIONS statusCode=204 path=/api/v1/statuses/01HA644YWD5M4F8RS3W9XSGRDD requestID=sba9ncwa04001pz7zpbg msg="No Content: wrote 0B"
timestamp="20/09/2023 17:19:43.307" func=server.glob..func1.Logger.func13.1 level=INFO latency="10.995µs" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" method=OPTIONS statusCode=204 path=/api/v1/statuses/01HA644YWD5M4F8RS3W9XSGRDD/context requestID=sfa9ncwa040005mnjcq0 msg="No Content: wrote 0B"
timestamp="20/09/2023 17:19:43.671" func=server.glob..func1.Logger.func13.1 level=INFO latency="41.557779ms" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" method=GET statusCode=404 path=/api/v1/statuses/01HA644YWD5M4F8RS3W9XSGRDD requestID=1qb9ncwa04001e6htt10 msg="Not Found: wrote 45B"
timestamp="20/09/2023 17:19:43.675" func=server.glob..func1.Logger.func13.1 level=INFO latency="48.682005ms" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" method=GET statusCode=404 path=/api/v1/statuses/01HA644YWD5M4F8RS3W9XSGRDD/context requestID=1bb9ncwa04001zc4kf20 msg="Not Found: wrote 45B"
```

I can try to enable debug logging for this, but it’s pretty hard to filter out anything not belonging to that one request… (might temporarily block tcp/443 for all other IPs for that, or something…)

### What's your GoToSocial Version?

0.11.1 git-c7a46e0

### GoToSocial Arch

amd64 binary

**Comment by tsmethurst** [comment]
Could you check if the parent status is still there in the database too? In other words, the status pointed to by your status's `in_reply_to_id` field?

**Comment by mirabilos** [comment]
Uhm…

(`SELECT * EXCEPT (content, text) FROM …`)

```
gotosocial=# SELECT s.sensitive,s.created_at,s.updated_at,s.local,s.federated,s.boostable,s.replyable,s.likeable,s.pinned_at,s.fetched_at,s.in_reply_to_uri,s.id,s.boost_of_id,s.boost_of_account_id,s.content_warning,s.visibility,s.language,s.created_with_application_id,s.activity_streams_type,s.in_reply_to_account_id,s.uri,s.url,s.attachments,s.tags,s.mentions,s.emojis,s.account_id,s.account_uri,s.in_reply_to_id FROM statuses s WHERE id='01HA644YWD5M4F8RS3W9XSGRDD';
 sensitive |          created_at           |          updated_at           | local | federated | boostable | replyable | likeable | pinned_at | fetched_at | in_reply_to_uri |             id             | boost_of_id | boost_of_account_id | content_warning | visibility | language | created_with_application_id | activity_streams_type | in_reply_to_account_id |                                     uri                                     |                                  url                                   | attachments |                                                     tags                                                      | mentions | emojis |         account_id         |               account_uri               | in_reply_to_id
-----------+-------------------------------+-------------------------------+-------+-----------+-----------+-----------+----------+-----------+------------+-----------------+----------------------------+-------------+---------------------+-----------------+------------+----------+-----------------------------+-----------------------+------------------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------+-------------+---------------------------------------------------------------------------------------------------------------+----------+--------+----------------------------+-----------------------------------------+----------------
 f         | 2023-09-13 01:58:01.869275+00 | 2023-09-13 01:58:01.869276+00 | t     | t         | t         | t         | t        |           |            |                 | 01HA644YWD5M4F8RS3W9XSGRDD |             |                     |                 | unlocked   | DE       | 01Y4AC0AH6KBQG5D8S5N46VRWX  | Note                  |                        | https://toot.mirbsd.org/users/mirabilos/statuses/01HA644YWD5M4F8RS3W9XSGRDD | https://toot.mirbsd.org/@mirabilos/statuses/01HA644YWD5M4F8RS3W9XSGRDD |             | {01FD8KK0DKKEVEPFDWT0EY48CJ,01H7ZG1BNM65AEETFMXRZQK607,01HA63S66HQX28T0MJ0NF2NJRS,01HA63S68WG57MS48G1VTJBD0Y} | {}       | {}     | 01GS55SW7VWYN3BFRYCX5NW526 | https://toot.mirbsd.org/users/mirabilos |
(1 row)
```

In other words: `in_reply_to_account_id`, `in_reply_to_uri` and `in_reply_to_id` are empty.

.oO(**what?**)

Excluding severe DB corruption, it seems like this _wasn’t_ a reply. OK, I can live with that (the chances are higher I misremembered than for DB corruption like that to have not yet been found elsewhere). But… if it’s not a reply… then… we can…

I tested something just now: I did…

```
gotosocial=# UPDATE statuses SET visibility='public' WHERE id='01HA644YWD5M4F8RS3W9XSGRDD';
```

… and restarted GtS, then tried to go to `/@mirabilos/statuses/01HA644YWD5M4F8RS3W9XSGRDD` in the webbrowser to drop the need for a client, and it visibly (and in the logs) 404s there as well.

**Comment by mirabilos** [comment]
Oh noes… I did trace-level debugging and found it.

I had cleaned up the `applications` table’s multiple dozen dead entries, but the `statuses` table has an `created_with_application_id` field that is not a foreign key (otherwise, referential integrity would have prevented me from removing the corresponding rows in the `applications` table, which I kinda relied on…) but still needed:

```
[…]
timestamp="20/09/2023 20:39:10.766" func=bundb.queryHook.AfterQuery level=TRACE duration=939.464µs query=SELECT "application"."id", "application"."created_at", "application"."updated_at", "application"."name", "application"."website", "application"."redirect_uri", "application"."client_id", "application"."client_secret", "application"."scopes" FROM "applications" AS "application" WHERE ("id" = '01Y4AC0AH6KBQG5D8S5N46VRWX')
timestamp="20/09/2023 20:39:10.771" func=server.glob..func1.Logger.func13.1 level=INFO latency="241.744404ms" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" method=GET statusCode=404 path=/@mirabilos/statuses/01HA644YWD5M4F8RS3W9XSGRDD requestID=r5qn3d4a04000rch8v5g msg="Not Found: wrote 1.12kiB"
```

And indeed…

```
gotosocial=*# UPDATE statuses SET created_with_application_id='016G7Y300X8EXHVHQDNA3MPVZP' WHERE created_with_application_id NOT IN (SELECT id FROM applications);
```

(where `016G7Y300X8EXHVHQDNA3MPVZP` is a valid ID) fixes this, also for Semaphore.

So I guess this is not a bug. Other than that `created_with_application_id` should be an FK, I suppose, but feel free to close this.

**Comment by tsmethurst** [comment]
Aha! OK, will close then. In future it's better not to poke around deleting things in the db like this; we'll at some point implement logic for cleaning up those peripheral tables as well.
