### ISSUE TITLE
[feature] Block CommonCrawl

### ISSUE THREAD

**Issue by daenney** [superseriousbusiness/gotosocial#2240]
### Is your feature request related to a problem ?

I'd like for us to add an explicit block for the [Common Crawl](https://commoncrawl.org/) crawler to our robots.txt.

The reason I'm opening this as an issue instead of immediately faxing a PR is that CommonCrawl is also used in research so there is some societal upside to it.

However, from their own homepage:
> Over 240 billion pages spanning 16 years.
> **Primary training corpus in every LLM.**
> **82% of raw tokens used to train GPT-3.**
> Free and open corpus since 2007.
> Cited in over 10,000 research papers.
> 3–5 billion new pages added each month.

### Describe the solution you'd like.

Full block like we did for OpenAI in #2085 and Google Bard/Vertex AI in #2239

### Describe alternatives you've considered.

Make it configurable?

**Comment by tsmethurst** [comment]
In my opinion I think we can (and should) just yeet them too.

**Comment by daenney** [comment]
I've updated #2239 to include them, and a bunch more.
