### ISSUE TITLE
[bug] Unable to activate user custom CSS

### ISSUE THREAD

**Issue by 77nnit** [superseriousbusiness/gotosocial#2241]
### Describe the bug with a clear and concise description of what the bug is.

I am not able to see the custom CSS field (not even disabled) on the user settings page.

### What's your GoToSocial Version?

0.11.1 git-c7a46e0

### GoToSocial Arch

x64 Docker

### What happened?

Following the guide I added those two global variables to the docker-compose.yaml in order to enable user custom CSS:
```
GTS_ACCOUNTS_ALLOW_CUSTOM_CSS: "true"
GTS_ACCOUNTS_CUSTOM_CSS_LENGTH: 10000
```
I modified the variable names as per rules given here: [Environment Variables](https://docs.gotosocial.org/en/latest/configuration/#environment-variables)

### What you expected to happen?

I expected to see and be able to edit the custom CSS field on the user profile, as I should have as per here: [Custom CSS](https://docs.gotosocial.org/en/latest/user_guide/settings/#custom-css)

![Screenshot_2023-10-01_18-14-28](https://github.com/superseriousbusiness/gotosocial/assets/123692361/469c0bf2-0aaf-42a0-a4ec-c16f1298bb39)

**Comment by tsmethurst** [comment]
Heya, don't forget to restart your GtS instance after modifying the environment variables.

**Comment by tsmethurst** [comment]
Heya, I'm gonna assume you got this working and close the issue. Feel free to reopen if you're still running into problem :)
