### ISSUE TITLE
[bug] Link header missing some params

### ISSUE THREAD

**Issue by cheeaun** [superseriousbusiness/gotosocial#2253]
### Describe the bug with a clear and concise description of what the bug is.

Fetching the timeline for a local public timeline: `/api/v1/timelines/public?limit=20&local=true` returns `Link` header that looks like this:

```
<https://[DOMAIN]/api/v1/timelines/public?limit=20&max_id=[ID]>; rel="next", <https://[DOMAIN]/api/v1/timelines/public?limit=20&min_id=[ID]>; rel="prev"
```

Notice that the `local` param is gone in the next and prev links.

### What's your GoToSocial Version?

v3.5.3+0.11.1-git-c7a46e0

### What happened?

First page returns local timeline, subsequent pages, read from `Link` header, return non-local federated public timeline.

### What you expected to happen?

The params (`local`, in this case) persist in `Link` header.

### How to reproduce it?

- Fetch `/api/v1/timelines/public?limit=20&local=true`
- Observe the response's `Link` header and see if `local` is there in the `next` and `prev` links.

### Anything else we need to know?

For context, I'm the dev of [Phanpy](https://github.com/cheeaun/phanpy) (3rd-party Mastodon web app) and one user found a bug with the Local public timeline showing non-local posts.

Phanpy uses `masto.js` library which reads the `Link` header for pagination. I debugged this and found that some params (`local`) did not persist in the `Link` header.

Notes:
- The instance tested is not my server.
- This is probably not the only param that is not persisted. I didn't check any other params or other timelines.
- I've read the code (I'm not a Go dev), seems relevant to `/internal/util/paging.go` and looks like `ExtraQueryParams` need to be populated?

**Comment by daenney** [comment]
Nice catch, thank you for raising this. We definitely need to fix that.
