### ISSUE TITLE
[bug] Bad request when trying to use very small avatars/banners 

### ISSUE THREAD

**Issue by Craftplacer** [superseriousbusiness/gotosocial#2263]
### Describe the bug with a clear and concise description of what the bug is.

When trying to upload an image that's too small (1x1 image for example) as the avatar or banner the backend just returns Bad Request.

### What's your GoToSocial Version?

v0.11.1 git-c7a46e0

### GoToSocial Arch

arm64 binary

**Comment by igalic** [comment]
how big in bytes are these files?
what, exactly does the backend say, other than bad request?
what do the logs say?

**Comment by tsmethurst** [comment]
It's probably giving bad request because the image is too small for us to derive the type from the magic bytes. Not 100% sure though, logs would be helpful.

**Comment by tsmethurst** [comment]
Could you check the response via the network tab (or equivalent for your browser) when doing an upload via the settings panel? That should give more information, i hope.

**Comment by tsmethurst** [comment]
Alright, annoying that it gives no errors, but that's OK. I'm fairly sure it's here where it's going wrong: https://github.com/superseriousbusiness/gotosocial/blob/39e22a9703470b74fa1bdbed8fd6200818667276/internal/media/processingmedia.go#L159-L162

We use those first 261 bytes as the 'magic' bytes for working out what format a file is. So a 35b 1-pixel gif isn't gonna work there. An 8x8 pixel gif or something, on the other hand, would probably work.

**Comment by tsmethurst** [comment]
Yes probably something like that. We'll take a better look at it when time allows.

**Comment by igalic** [comment]
> Alright, annoying that it gives no errors, but that's OK. I'm fairly sure it's here where it's going wrong:
> 
> https://github.com/superseriousbusiness/gotosocial/blob/39e22a9703470b74fa1bdbed8fd6200818667276/internal/media/processingmedia.go#L159-L162
> 
> We use those first 261 bytes as the 'magic' bytes for working out what format a file is. So a 35b 1-pixel gif isn't gonna work there. An 8x8 pixel gif or something, on the other hand, would probably work.

it's there a way to make this read graceful?
take what's there, even if it's less than 261 bytes?

**Comment by KEINOS** [comment]
> it's there a way to make this read graceful?

I think `io.ReadFull` is causing the error of `unexpected EOF`.

https://github.com/superseriousbusiness/gotosocial/blob/39e22a9703470b74fa1bdbed8fd6200818667276/internal/media/processingmedia.go#L159-L167

How about using `copy` instead?

```go
func Example() {
	// 1x1 px transparent GIF image
	imgBase64 := "R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="

	imgBin, err := base64.StdEncoding.DecodeString(imgBase64)
	PanicOnErr(err)

	hdrBuf := make([]byte, 261)

	// rc := bytes.NewReader(imgBin)
	// _, err = io.ReadFull(rc, hdrBuf)
	// PanicOnErr(err)

	_ = copy(hdrBuf, imgBin)

	info, err := filetype.Match(hdrBuf)
	PanicOnErr(err)

	fmt.Printf("%s\n", info.MIME.Value)
	// Output:
	// image/gif
}

func PanicOnErr(err error) {
	if err != nil {
		log.Panic(err)
	}
}
```
- [GoPlayground](https://go.dev/play/p/o51hGjVFSnh)

**Comment by tsmethurst** [comment]
PR would be great! :)

**Comment by KEINOS** [comment]
> @tsmethurst 
> PR would be great! :)

Done 👍 Hope it helps!

- #2298
