### ISSUE TITLE
[bug] 500 in /api/v1/blocks

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2268]
### Describe the bug with a clear and concise description of what the bug is.

    timestamp="16/10/2023 19:22:22.215" func=server.glob..func1.Logger.func13.1 level=ERROR latency="38.585742ms" userAgent="Feditext/76 CFNetwork/1335.0.3.4 Darwin/21.6.0" method=GET statusCode=500 path=/api/v1/blocks error="Error #01: ERROR: column \"?\" does not exist (SQLSTATE 42703)\n" requestID=c1vf0ecb04000h81y1s0 msg="Internal Server Error: wrote 54B"

### What's your GoToSocial Version?

0.11.1 git-c7a46e0

### GoToSocial Arch

amd64 binary

### How to reproduce it?

FediText: click on the upper-left corner icon, then Preferences in the menu, then Blocked Users.

### Anything else we need to know?

via https://github.com/feditext/feditext/issues/267#issuecomment-1765127318

My guess is bogus SQL (bad bind parameter syntax or forgot to pass a bind parameter).

**Comment by tsmethurst** [comment]
Thanks! Could you see if this persists in the new release candidate (0.12.0-rc1)?

**Comment by mirabilos** [comment]
Thanks, it’s fixed there!
