### ISSUE TITLE
[bug] more DB constraint violations; this time in enrichStatus

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2271]
### Describe the bug with a clear and concise description of what the bug is.

    timestamp="2023-10-17T20:56:46.903Z" func=dereferencing.(*deref).dereferenceThread level=ERROR msg="DereferenceStatusAncestors: error dereferencing parent https://tech.lgbt/users/lnr/statuses/111252223850848130: enrichStatus: error putting in database: ERROR: duplicate key value violates unique constraint \"statuses_uri_key\" (SQLSTATE 23505)"

### What's your GoToSocial Version?

0.12.0-rc1 git-637f188

### GoToSocial Arch

amd64 binary

### What happened?

I just saw that flit by in the logs while retesting a different bug. I recall we had some of these constraint violations elsewhere, but this is now; possibly related to the threading thing.

### Anything else we need to know?

PostgreSQL, of course.

**Comment by tsmethurst** [comment]
Thanks, I'll see if there's a cheeky quick fix here.

**Comment by tsmethurst** [comment]
Hmm, the strange thing here is that we do actually have code to handle these errors: https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/bundb/errors.go

Apparently it's not working though, so I'll poke at it.

**Comment by tsmethurst** [comment]
Aha, reproduced it with a test :)

**Comment by tsmethurst** [comment]
^^ Got it.
