### ISSUE TITLE
[bug] Cannot bulk import/export domain anymore

### ISSUE THREAD

**Issue by JacksonChen666** [superseriousbusiness/gotosocial#2274]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

Trying to click the link "Or use the bulk import/export interface" in either domain allows/blocks will bring the user to a new domain allow/block instead of the import/export interface.

![gotosocial new domain block page, setting the domain as "import-export"](https://github.com/superseriousbusiness/gotosocial/assets/50755746/a92d3c2e-2803-4d5e-90d0-0b6188c1d5ae)

### What's your GoToSocial Version?

v0.12.0-rc1

### Browser version

LibreWolf 118.0.1-1

### What you expected to happen?

The bulk import/export interface shows up.

### How to reproduce it?

Click the "Or use the bulk import/export interface" link.

### Anything else we need to know?

`/settings/admin/domain-permissions/import-export` still exists but the links don't seem to be correct.

**Comment by tsmethurst** [comment]
Got it, thanks. I'll make a fix for it, just set the link wrong. In the meantime you should still be able to navigate to the bulk import/export page using the link on the sidebar!
