### ISSUE TITLE
[bug] Following a WordPress Blog fails

### ISSUE THREAD

**Issue by pfefferle** [superseriousbusiness/gotosocial#2280]
### Describe the bug with a clear and concise description of what the bug is.

It seems that GoToSocial is not validating the signature correctly when having a fragment in the URL.

The signature fails with the fragment in the `keyId`:

```
[Signature] => keyId="https://notiz.blog/wp-api/activitypub/1.0/application#main-key",algorithm="rsa-sha256",headers="(request-target) host date",signature="[...]"
```

This signature works without it:

```
[Signature] => keyId="https://notiz.blog/wp-api/activitypub/1.0/application",algorithm="rsa-sha256",headers="(request-target) host date",signature="[...]"
```

You can check the JSON profile here:

```
curl "https://notiz.blog/wp-api/activitypub/1.0/application" \
     -H 'Accept: application/activity+json'
```

### What's your GoToSocial Version?

0.11.1 git-c7a46e0

**Comment by jeherve** [comment]
> What's your GoToSocial Version?
> 0.11.1 git-c7a46e0

This also happens with 0.12.0-rc2 git-805c67b

**Comment by tsmethurst** [comment]
Hmm, that's a bit weird. I believe Mastodon also puts fragments in their keyId and GtS works fine with Mastodon. Can you give more context on what wordpress thingy is being used here? And what GtS says in its logs?

**Comment by tsmethurst** [comment]
Are you by any chance using the same public key for multiple users?

**Comment by tsmethurst** [comment]
Hmm, I was able to follow https://notiz.blog/author/matthias-pfefferle/ from my GoToSocial account just now, no signature errors there. Or do you currently have that service using the key without the fragment?

**Comment by pfefferle** [comment]
No, the public key will be auto generated for every user.

**Comment by pfefferle** [comment]
> Hmm, I was able to follow https://notiz.blog/author/matthias-pfefferle/ from my GoToSocial account just now, no signature errors there. Or do you currently have that service using the key without the fragment?

No, it is using the Fragment at the moment. This is weird, we tested it on https://fedi.jeremy.hu/

**Comment by jeherve** [comment]
> Could you please try going to actions -> keys in your GtS settings panel and invalidating the keys for notiz.blog, and see if that changes anything?

Looks like it helped indeed!

**Comment by tsmethurst** [comment]
Great, gonna close this as resolved then if that's OK, I believe the fragment was a red herring.

**Comment by tsmethurst** [comment]
Yup yup, you're welcome :) Good luck with the plugin, it's a great idea!
