### ISSUE TITLE
[feature] Cli: Indicate that an account already is admin on `admin account promote`

### ISSUE THREAD

**Issue by CherryKitten** [superseriousbusiness/gotosocial#2289]
### Is your feature request related to a problem ?

Running `admin account promote` for a user who already is an admin returns a return code of zero without any output indicating that the user already has admin rights.
That makes it hard to determine if the command changed anything, which is impractical for automations that try to be idempotent.

### Describe the solution you'd like.

Either return a non-zero exit code, output a simple message to stderr, or both.

### Describe alternatives you've considered.

none (making this all uppercase feels bad, I couldn't get myself to do it)

### Additional context.

meow

**Comment by tsmethurst** [comment]
Hmm, not sure about this one because the action of promoting a user is itself idempotent, but I know what you mean. This is for ansible right?

What you might do to check whether a user is an admin already is run `./gotosocial --log-level=warn admin account list` and then pipe that through the following regular expression, where the username you're looking for is `username_of_the_maybe_admin`:

```regex
^username_of_the_maybe_admin\s+[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}\s+(?:yes|no)\s+(yes|no)(?:no|yes|\s)+$
```

In capture group 1, that will output `yes` if the user is an admin, or `no` if not.

You can play around with the regular expression here: https://regex101.com/r/5fCLFs/1

**Comment by CherryKitten** [comment]
> Hmm, not sure about this one because the action of promoting a user is itself idempotent, but I know what you mean. This is for ansible right?

yep, eventhough the action itself is idempotent, there is no feeeback indicating if something was done or not, so I can't easily show the correct status in the ansible output

> What you might do to check whether a user is an admin already is run `./gotosocial --log-level=warn admin account list` and then pipe that through the following regular expression, where the username you're looking for is `username_of_the_maybe_admin`:
> 
> ```regexp
> ^username_of_the_maybe_admin\s+[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}\s+(?:yes|no)\s+(yes|no)(?:no|yes|\s)+$
> ```
> 
> In capture group 1, that will output `yes` if the user is an admin, or `no` if not.
> 
> You can play around with the regular expression here: https://regex101.com/r/5fCLFs/1

Thanks, this *would* work, but it'd need more steps and executing more commands, so I would prefer any kind of feedback from the promote command that shows if something was changed or not, if possible

**Comment by tsmethurst** [comment]
Totally forgot we had this open. I don't think we're going to do it as nobody else has asked for it and there is an available workaround. If there's more requests for it we can look at reopening the issue.
