### ISSUE TITLE
[bug] Can't update profile 0.12.0

### ISSUE THREAD

**Issue by kuspoes** [superseriousbusiness/gotosocial#2297]
### Describe the bug with a clear and concise description of what the bug is.

I can't update my profile.

### What's your GoToSocial Version?

0.12.0

### GoToSocial Arch

amd64 binary

### What happened?

1. Trying to update my profile but everytime click on Save Profile Info, nothing happened.
2.  Custom CSS box non editable.

log

`timestamp="25/10/2023 03:27:53.417" func=server.glob..func1.Logger.func13.1 level=INFO latency="2.277977ms" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0" method=PATCH statusCode=400 path=/api/v1/accounts/update_credentials clientIP=192.168.0.2 requestID=8vcdys4b040013vsnzj0 msg="Bad Request: wrote 100B"`

### What you expected to happen?

1. Can edit profile
2. Can insert custom css

**Comment by linksu** [comment]
Exactly the same problem here after upgrading. Using arm64 with Docker.

**Comment by tsmethurst** [comment]
Heya! Thanks for opening. We have a fix for this issue on a branch :) Currently preparing 0.12.1 bugfix release
