### ISSUE TITLE
[bug] honk (benjojo) images shown with wrong image description

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2302]
### Describe the bug with a clear and concise description of what the bug is.

I complained about an image having a mere image description of…

> z64KTcw2h2bZ8s67k2.jpg

… but the sender indicates this is supposed to be a GtS bug as he [says](https://benjojo.co.uk/u/benjojo/h/711R2M5Ct2CfjY2825) he’s following spec “as far as [he] can see” in his own Fedi implementation. He attached the following document to support:

```
   {
      "actor": "https://benjojo.co.uk/u/benjojo",
      "id": "https://benjojo.co.uk/u/benjojo/honk/QZp4JrCv78N95hCgd1JQ",
      "object": {
        "attachment": [
          {
            "mediaType": "image/jpeg",
            "name": "z64KTcw2h2bZ8s67k2.jpg",
            "summary": "A very large panel that is entirely twist switches",
            "type": "Document",
            "url": "https://benjojo.co.uk/d/XzKw4M2Sc1pBxj3hY4.jpg"
          }
        ],
        "attributedTo": "https://benjojo.co.uk/u/benjojo",
        "content": "Finally a interface perfect for the gentoo users out there",
        "context": "data:,electrichonkytonk-8W1z23Q474f7b4N2JT",
        "conversation": "data:,electrichonkytonk-8W1z23Q474f7b4N2JT",
        "id": "https://benjojo.co.uk/u/benjojo/h/tk2Mfwj4m7vVS1Fm8L",
        "published": "2023-10-19T23:58:07Z",
        "summary": "",
        "to": "https://www.w3.org/ns/activitystreams#Public",
        "type": "Note",
        "url": "https://benjojo.co.uk/u/benjojo/h/tk2Mfwj4m7vVS1Fm8L"
      },
      "published": "2023-10-19T23:58:07Z",
      "to": "https://www.w3.org/ns/activitystreams#Public",
      "type": "Create"
    },
```

I’ve got no idea about AP JSON, but I’d appreciate if you could check whether this is indeed a GtS bug or a frontend bug or a bug on the sender’s side or something.

### What's your GoToSocial Version?

0.11.1 git-c7a46e0

### GoToSocial Arch

amd64 binary

**Comment by tsmethurst** [comment]
Seen that as well yeah, think I know what's causing it. Thanks for raising it (I keep forgetting to do it)
