### ISSUE TITLE
[bug] 401: Unauthorized: token not supplied

### ISSUE THREAD

**Issue by xxwhirlpool** [superseriousbusiness/gotosocial#2311]
### Describe the bug with a clear and concise description of what the bug is.

Hi, I previously deployed a GTS instance with no issue the other day, but the IP on my server accidentally dynamically changed for reasons, and the instance stopped working. This was fine with me, because I planned to make a new instance with a new domain anyway, and the first instance was for testing. However, upon trying to deploy a new instance, either bare metal or docker, I get the following error when navigating to /settings in the browser:

> 401: Unauthorized: token not supplied
> 
> You can attempt logging in again below:
> [instance url]

I'm not sure what's causing this, maybe my reverse proxy? I have GTS secured with Caddy, and I'm not sure if that's causing the issue. I didn't have any issues with Caddy and GTS or this problem in general when running my previous instance for the first time.

Apologies if this is not the right place to ask. Any help is appreciated. Thank you.

### What's your GoToSocial Version?

v0.1.12.1

### GoToSocial Arch

amd64

### What happened?

401: Unauthorized: token not supplied error upon navigating to /settings

### Anything else we need to know?

Bare metal installation (faced same issue with Docker)

**Comment by tsmethurst** [comment]
Marking this one as resolved because it was addressed out of band. Browser issue (waterfish) was causing problems, trying with firefox works.
