### ISSUE TITLE
[bug] Unable to comment on other mastodon instance

### ISSUE THREAD

**Issue by ItsNayabSD** [superseriousbusiness/gotosocial#2312]
### Describe the bug with a clear and concise description of what the bug is.

I wasn't able to comment on the one of the posts of fosstodon.org instance with my GoToSocial account. When I try to authenticate, the instance responded with 404 not found.

### What's your GoToSocial Version?

v0.12.0

### GoToSocial Arch

amd64 binary

### What happened?

I visited the following buildroot hashtag url from fosstodon.org

https://fosstodon.org/tags/buildroot

I found an interesting post there and I want to comment using my GoToSocial account. I clicked on the reply to the following post
https://fosstodon.org/@troglobit/111241007886591470

A nice pop up showed up asking me to enter my instance address to `Take me home`.

![Take me home](https://i.imgur.com/ceHmvCj.png)

I've entered my instance address: social.nayab.dev. The instance responded with `404: Page Not Found`

![404 not found](https://i.imgur.com/JIRX3vu.png)

### What you expected to happen?

I expect the authentication to be succeeded so that I could comment on other mastodon instances posts without following them.

### How to reproduce it?

Visit the url https://fosstodon.org/@troglobit/111241007886591470.

Log out from fosstodon.org if you already have account with them and logged in.

Try to comment on the post mentioned above. Follow the on-screen instructions to authenticate. The authentication will fail and the GoToSocial instance respond with 404 not found page.

### Anything else we need to know?

None

**Comment by tsmethurst** [comment]
Hi, we haven't implemented the "interact with remote post" flow, see: https://github.com/superseriousbusiness/gotosocial/issues/921

It's more complex to do in GoToSocial's case because we don't have a built-in client application. For now the best way of interacting with a remote post is to copy the link to the post and paste it into the search of whatever client you're using.

**Comment by ItsNayabSD** [comment]
Thanks. I think I am ok with pasting the url in semaphore.social search and replying from there.

**Comment by ItsNayabSD** [comment]
Thanks. I think I am ok with pasting the url in semaphore.social search and replying from there.
