### ISSUE TITLE
[bug] Uploading videos in weird unplayable formats does not cause any errors

### ISSUE THREAD

**Issue by eeeeeta** [superseriousbusiness/gotosocial#2314]
### Describe the bug with a clear and concise description of what the bug is.

In [this thread](https://gotosocial.i.eta.st/@eta/statuses/01HDYP57FNVVS66JXMWPRJMR2E), I uploaded a cursed `.mp4` that had 10-bit HDR video inside, which (turns out) is unplayable by most people's hardware (except for iPhones). GtS happily accepted such a file, and since the file appeared fine to me on the iPhone it was recorded on, I had no idea that other people might have encountered playback issues.

If GtS isn't willing to re-encode video itself (absolutely understandable), I think it should at least warn on or deny media that's unlikely to be played on a majority of devices to avoid pitfalls like this. I've no idea what "compatible" videos look like, but for example re-encoding with `ffmpeg -pix_fmt yuv420p` made my video work, so perhaps that's a useful starting point?

### What's your GoToSocial Version?

v0.12.0 git-17ad215 (custom branch)

**Comment by eeeeeta** [comment]
Hmm, maybe this issue isn't as big as I thought -- it appears mastodon might do some re-encoding of incoming videos? (This is still an issue for the web UI, though, but a far less significant one.)

**Comment by tsmethurst** [comment]
Yes, afaik mastodon (and most other implementations) will call ffmpeg to do reencoding. I can see where you're coming from but tbh I'm not sure if it's GtS's place to say 'this format looks weird, are you sure you want to upload it?' -- unless that weird format contains something actually malicious, of course.

**Comment by eeeeeta** [comment]
Yeah, that's fair -- I'll close this, since mastodon re-encoding makes this basically a non-issue!
