### ISSUE TITLE
Support for MySQL or other Database connectors

### ISSUE THREAD

**Issue by sdenike** [superseriousbusiness/gotosocial#2324]
### Is your feature request related to a problem ?

While I know there is already SQLite and Postgres support, will there be other data connectors for MySQL, etc?

### Describe the solution you'd like.

Would like to have the option of using MySQL as the database service. This could open up the hosting of the instances on hosts that for some reason or another do not allow for SQLite/Postgres.

### Describe alternatives you've considered.

SQLite/Postgres as included, but would like to see this as an option if possible.

**Comment by tsmethurst** [comment]
Probably not no! See: https://github.com/superseriousbusiness/gotosocial/issues/728

**Comment by T1anjiu** [comment]
Haha, despite this, I still hope to join MySQL support someday in the future.
