### ISSUE TITLE
[bug] Changing User Password Doesn't Work

### ISSUE THREAD

**Issue by benjaminbhollon** [superseriousbusiness/gotosocial#2325]
### Describe the bug with a clear and concise description of what the bug is.

A user on my instance reached out to me saying he'd lost his password, so I tried to reset it using the admin CLI. However, the new password I'm trying to change to isn't working to log into their account.

No errors are being thrown by the CLI. I know this has worked in the past, on v0.11.0, so I wonder if this somehow got introduced in a recent release? Or if I'm somehow having a brain fart?

### What's your GoToSocial Version?

3.5.3+0.12.1-git-5fdc005

### GoToSocial Arch

amd64 Binary

### What happened?

The account cannot be logged into. I do not know if the previous password still works, since this user forgot it.

### What you expected to happen?

I expected to be able to log in with the new password.

### How to reproduce it?

Assuming it's reproducible…

- Try to change a password from the admin CLI (I'll include the exact command I used in a moment)
- Try to log in with the new password

### Anything else we need to know?

The command I'm running:

```bash
./gotosocial admin account password --config-path config.yaml --username thedoctor --password this.is.a.test
```

Is there something I'm doing wrong? No errors are being thrown.

**Comment by tsmethurst** [comment]
Could you try restarting your instance after changing the password?

**Comment by benjaminbhollon** [comment]
Okay that worked. 😅

Any idea what's up?

**Comment by tsmethurst** [comment]
Yes :') Unfortunately it's a caching issue. When you use the CLI to update something in the database directly, it doesn't have a way of invalidating the in-memory cache of the running instance. So as far as the running instance is concerned, the password hasn't changed. Restarting the instance flushes the cache.

Most of the admin CLI commands will probably be replaced at some point by functions in the admin panel, which *does* connect directly to the running instance and can therefore invalidate the cache properly.

**Comment by benjaminbhollon** [comment]
Okay, that makes sense. Good to know for the future, too. I guess the times I last used this I was doing a lot of tweaking of the instance so I coincidentally reloaded the instance and cleared the cache.

Should we close this issue, then?

**Comment by tsmethurst** [comment]
> Should we close this issue, then?

Might as well yeah! I'll close it. Someone will probably run into the same issue at some point so perhaps this will help them until we can get a proper fix.

**Comment by benjaminbhollon** [comment]
Thanks for the quick turnaround, by the way! I appreciate y'all!
