### ISSUE TITLE
[bug] Akkoma and Pleroma URLs and URIs causing issues when searching

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2327]
Pleroma and Akkoma both seem to do a bit of an odd thing, where they'll serve a status on the web as (say) `https://akkoma.example.org/notice/AbFvHsSx5mhPlyqABk`, but when you dereference that status, they redirect to the ActivityPub ID of the object, (say) `https:///akkoma.example.org/objects/18d277b3-06fb-40d4-ae70-30b4bca1f7d8`.

Dereferencing that URI will give you ActivityPub, as expected, but the returned Note won't have any reference on it to the web URL.

This causes issues inside the dereferencer, because as far as GtS is concerned this is a "new" status (ie., one the instance hasn't seen before), because it can't find it in the database using the given URL. The GtS instance will dutifully try to store the "new" status, only to run against the unique URI constraint and fail.

This leads to situations where you can keep searching, from your GoToSocial instance, for an Akkoma or Pleroma status using its web URL, but get nothing back, because your instance can't find it in the DB at the URL you're providing, and it can't store a "new" status because it already exists.

When you use the ActivityPub URI of the Note, on the other hand, that all works fine.

Probably the solution here would be to check first if we have the status using the web URL, then when that check returns false dereference it as normal, then check *again* if we have the status using the ActivityPub URI/ID returned by doing the dereference.

**Comment by NyaaaWhatsUpDoc** [comment]
just confirmed this as working by searching for: https://pleroma.envs.net/notice/AWanqm7L8SzpPIpsMi

which works, and the resulting status clicked on returns the url: https://pleroma.envs.net/objects/d357a8a8-a10f-4ea4-aa54-3bf9974d542f
