### ISSUE TITLE
[bug] Profile photos not loading for external accounts after swapping to S3

### ISSUE THREAD

**Issue by novakeith** [superseriousbusiness/gotosocial#2328]
### Describe the bug with a clear and concise description of what the bug is.

Remote profile pictures for certain accounts are not loading after I migrated my storage from local to an S3 bucket. This does not affect all accounts. It appears to only affect accounts that I federated with while I was using local storage.

### What's your GoToSocial Version?

v0.12.1

### GoToSocial Arch

Docker - Debian  x86_64

### What happened?

I reconfigured my GtS instance to use an S3 bucket about 24 hours after I started my GtS instance. On bringing the server back up, I noticed users were missing profile pictures.

### What you expected to happen?

I expected that when I visited their profile the data would refresh and grab the profile picture. However, that was not the case. I also tried unfollowing and re-following a few users to see if that would fix the issue, but it did not. 

### How to reproduce it?

Start a GtS instance with local storage, federate with a few accounts by following them, and then swap to an S3 storage provider.

### Anything else we need to know?

It is possible this has something to do with the database - at the same time I migrated from local -> S3, I also changed my database from sqlite -> Postgres. But I was able to re-import the data during the database migration so I did not think this was the primary cause of this issue.

**Comment by novakeith** [comment]
It's still a problem I encounter every day unfortunately :( 

Now I'm in a weird circumstance since I manually moved myself from local storage to s3 and that's when this issue cropped up, so I'm not expecting some kind of magical fix for my meddling. But it would be nice if there was a way to force all profile photos to be redownloaded from the source instance. IIRC, gotosocial is looking for them in their old storage location and probably doesn't update until the remote user changes their profile picture.

**Comment by tsmethurst** [comment]
You can try working around this with the following database query:

```sql
UPDATE accounts SET (avatar_media_attachment_id, avatar_remote_url, header_media_attachment_id, header_remote_url, fetched_at) = (null, null, null, null, null) WHERE domain IS NOT null;
```

After running it, restart your instance (or run it while your instance is down and then bring your instance up).

That will force GtS to refetch avatars + headers the next time it sees each remote account.

**Comment by novakeith** [comment]
Thanks! Looks like that did the trick. 

I should have written down how I did the migration, this would be useful knowledge for people in my situation (admittedly - probably rare)

**Comment by tsmethurst** [comment]
I'm glad it works at least! I'm going to close this issue, but will open it again and use it to track the (possible?) bug if someone else recreates it.
