### ISSUE TITLE
Order statuses (and more?) by ID, not date

### ISSUE THREAD

**Issue by NyaaaWhatsUpDoc** [superseriousbusiness/gotosocial#233]
the example here being goat's future posts now being stuck at the top of my federated timeline

**Comment by tsmethurst** [comment]
We already do order statuses by ID -- the problem in this case is that the ID of certain items that need to be sortable is tied to the date. For statuses (and some other things) we generate their ids by calling NewULIDFromTime:

https://github.com/superseriousbusiness/gotosocial/blob/main/internal/id/ulid.go#L25-L32

The greater the time, the higher the ID generated, see https://github.com/oklog/ulid for implementation.

This produces database-friendly sortable IDs, that also play nice with things like Tusky and Pinafore, where they use IDs to sort (early in development I tried using random IDs and it worked *terribly* in Pinafore, and very buggily in tusky).

So in this case, sorting by ID versus sorting by date is essentially the same thing :P

**Comment by NyaaaWhatsUpDoc** [comment]
Ahhh I see the issue...Yes I think you're right. I'd say anything > 24hrs in the future is a good round number to go for, and takes into account any timezone weirdness

**Comment by tsmethurst** [comment]
Yep, I was thinking somewhere in the range of 12 - 24 :) Let's take 24 and tweak it later if needs be. I'll close this issue for now.
