### ISSUE TITLE
[bug] Problem with Documentation

### ISSUE THREAD

**Issue by HelgeKrueger** [superseriousbusiness/gotosocial#2332]
When  clicking on "swagger.yaml" on https://docs.gotosocial.org/en/latest/api/swagger/ I'm redirected to https://docs.gotosocial.org/api/swagger/swagger.yaml

This is not a yaml file, but some broken looking html file. Looks like some problem with the documentation generation.

**Comment by tsmethurst** [comment]
Thanks, well spotted!
