### ISSUE TITLE
[bug] Login fails with error "field response_type was not set on OAuthAuthorize form"

### ISSUE THREAD

**Issue by urmaul** [superseriousbusiness/gotosocial#2342]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

Login fails with an error.

### What's your GoToSocial Version?

0.12.1 git-5fdc005

### Browser version

Firefox 119.0 (64-bit)

### What happened?

I try to set up a local instance of GoToSocial and I cannot login as my test user.

### What you expected to happen?

Either login works or actionable error is shown.

### How to reproduce it?

1. Run GoToSocial locally in a docker container. Database is sqlite, letsencrypt disabled, opening http://localhost:8080 in the browser opens home page.
2. Create a test user
3. Try to log in to "http://localhost:8080" either via https://semaphore.social/ or via http://localhost:8080/settings.
4. Enter email and valid password.
5. Page http://localhost:8080/oauth/authorize returns next error:

> Bad Request: field response_type was not set on OAuthAuthorize form: If you arrived at this error during a login/oauth flow, please try clearing your session cookies and logging in again; if problems persist, make sure you're using the correct credentials

**Comment by tsmethurst** [comment]
Hiya

>  If you arrived at this error during a login/oauth flow, please try clearing your session cookies and logging in again

Did you try this? Also, did you configure your instance host as `localhost:8080`?

**Comment by urmaul** [comment]
I tried changing the port, and cleaning all the cookies for `localhost`.
Instance host was `localhost` without the port. Will try it with the port number later today.

**Comment by tsmethurst** [comment]
Alrighty. For purely local testing and development you may want to use the testrig, btw. It's a little easier than running an actual instance on localhost, and will also guarantee that you don't accidentally make network requests: https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md#standalone-testrig-with-semaphore

**Comment by urmaul** [comment]
Turned out I was configuring the instance host value wrongly. Both `localhost` and `localhost:8080` options work fine. No bugs here.
