### ISSUE TITLE
[feature] Email change mechanism

### ISSUE THREAD

**Issue by benjaminbhollon** [superseriousbusiness/gotosocial#2373]
### Is your feature request related to a problem ?

I've had multiple requests from members of my instance to change the email addresses attached to their accounts, but I don't see any way of doing so.

### Describe the solution you'd like.

Ideally, they could change it themselves through the settings portal, perhaps with an email verification mechanism.

### Describe alternatives you've considered.

I'd be fine if it requires the admin CLI to change emails; I don't anticipate it being a frequent request and doing it manually likely wouldn't take too much time/effort.

**Comment by tsmethurst** [comment]
Good feature request! I actually completely forgot we hadn't implemented this yet. We'll try to do it for 0.14.0 probably (we're just polishing things off for 0.13.0 now).

In the meantime I believe you can safely do it manually in the database by doing something like this:

```sql
UPDATE users SET email='new_email_address' WHERE email='old_email_address';
```

And then restarting your instance.

A bit of a hack, but it's there if you need it!

**Comment by benjaminbhollon** [comment]
I'll consider doing that, thanks. Glad to hear a polished version will come soon! And that the new release is upcoming. ;)

**Comment by tsmethurst** [comment]
Hmm. Gonna push this back again to 0.16.0; I'm doing a lot of work on the sign-up flow for that version, and email confirmation / change can be part of that bundle of work.

**Comment by benjaminbhollon** [comment]
Makes sense. ;)
