### ISSUE TITLE
[question] How to actually `/api/v1/admin/email/test`?

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2376]
I’ve always wondered how and when GtS sends out eMails and have been pointed to <https://docs.gotosocial.org/en/latest/configuration/smtp/#can-i-test-if-my-smtp-configuration-is-correct> by a friendly GtS admin, and from there I went to https://docs.gotosocial.org/en/latest/api/swagger/ and got stuck.

It begins with that there is the unchanged `REPLACE_ME` near the beginning *and* the reader cannot change the base URL (from what I remember when I was in a project that used Swagger years ago, you can have a fixed base URL, a set of fixed ones, or let the user enter their own; this seems to be using a fixed base URL of `example.com` which is not entirely helpful).

I guess I could use <https://takahashim.github.io/mastodon-access-token/> or <https://tinysubversions.com/notes/mastodon-bot/> to get a token, or reuse the one I use for the Feediverse RSS2Fedi thing, but anything further than that…? Depends on the base URL again so I’m SOL?

Has anyone ever used the Swagger thing for anything in practice?

Would it perhaps be possible to integrate that with `/settings/admin` so I can use the latter to send arbitrary requests against my own instance and not have to bother with extra authentication (and setting the base URL, because *then* it could just use the one it’d be served from)?

AIUI some requests are signed; does the Swagger thing do that as well?

**Comment by tsmethurst** [comment]
We really just intended the swagger docs to be read-only reference documentation, and not have folks using it to try to send requests. In fact, I don't think it's set up properly (even aside from REPLACE_ME etc.) to make requests by authenticating correctly.

> Has anyone ever used the Swagger thing for anything in practice?

As a reference doc, yes. As a means of sending requests, no, I doubt it.

> Would it perhaps be possible to integrate that with /settings/admin so I can use the latter to send arbitrary requests against my own instance

That's a massive chunk of work which would probably be better spent on just adding an 'email' section to let admins enter an email address to send a test email to, which would then use the API anyway.

> AIUI some requests are signed; does the Swagger thing do that as well?

No, that's for server-to-server requests via the federation API. The swagger doc is intended to document the client API. We do have a section on 's2s/federation' but we'll likely remove that in favor of the much more comprehensive [federating with gotosocial](https://docs.gotosocial.org/en/latest/federation/federating_with_gotosocial/) document.

**Comment by mirabilos** [comment]
tobi dixit:

>> Has anyone ever used the Swagger thing for anything in practice?
>
>As a reference doc, yes. As a means of sending requests, no, I doubt it.
[…]

Hmm, okay, fair. Perhaps add a note near the beginning of the
Swagger page stating that?

And, if someone who knows finds the time, perhaps create a small
documentation page somewhere that explains to someone who knows
in general how to use cURL etc. and has the Swagger page at hand
how to go from there to sending a request. Then link to that as
well. I think the “normal” GtS admin has not ever made either an
AP request or a mstdn-compatible-c2s-API request ever ☻ but this
might be useful. And it could even use the test eMail request as
example ☺

Thanks,
//mirabilos
