### ISSUE TITLE
[bug] boosted posts sometimes appear to be authored by the booster

### ISSUE THREAD

**Issue by illfygli** [superseriousbusiness/gotosocial#2394]
### Describe the bug with a clear and concise description of what the bug is.

A boosted toot may change so that the booster appears as the author, the date of the toot becomes the boost date, and so on.

I've seen it change before my eyes, so it starts out correct, and then the booster usurps the original author. :)

Unfortunately, I found nothing even remotely interesting in the logs.

### What's your GoToSocial Version?

0.12.2

### GoToSocial Arch

x86_64 binary

### What happened?

A boost appeared on the timeline.

Then the boost metadata replaced that of the original post, making it look like an original post by the booster.

### What you expected to happen?

Post should keep the original author.

### How to reproduce it?

Stare at the timeline for extended periods of time. Sorry, I don't know. :(

### Anything else we need to know?

You're the best, keep up the good work.

**Comment by tsmethurst** [comment]
Oh, I didn't mean to mark this as completed. I'll open it again until we can validate it's actually fixed.

**Comment by illfygli** [comment]
Upgraded to 0.13.0-rc1 and will keep an eye out!

**Comment by tsmethurst** [comment]
I haven't seen this again yet :eyes:

**Comment by illfygli** [comment]
Me neither!

Seems like it was actually quite common, once I started looking for it, but now I haven't seen it on 0.13.0 or any of its RCs.

**Comment by tsmethurst** [comment]
Great :) I'll close it for now and let's see if it pops up again in future.
