### ISSUE TITLE
[feature] Schedule database vacuuming every x days

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2397]
With lots of inserts / deletes / updates etc going on, it's possible for a database to become fragmented, and larger than it needs to be. It would probably pay off to enable vacuuming on a schedule.

For SQLite, we could enable `auto_vacuum=incremental` on the database, and then call the `incremental_vacuum` pragma every now and then (once a week? less? more?). See https://sqlite.org/pragma.html#pragma_auto_vacuum and https://sqlite.org/pragma.html#pragma_incremental_vacuum.

Note that you can only set auto_vacuum on **new** SQLite database files; this includes new **copies** of database files as created by calling `VACUUM`, so we'd have to provide manual migration steps. The steps are basically: stop gotosocial, call `VACUUM` once using the sqlite CLI tool, start gotosocial again. If folks prefer not to `VACUUM` their database once manually, then subsequent `incremental_vacuum` calls just won't do anything, which is not the end of the world.

For Postgres, we can also use the `VACUUM` command, though in PG's case the DB will keep the same overall size, but free up capacity within that size. That's probably good enough. See: https://www.postgresql.org/docs/current/sql-vacuum.html

**Comment by daenney** [comment]
You don't need to manually vacuum PG, let autovacuum handle it. If autovacuum is not able to keep up with pruning dead tuples, people can tweak it for their database. Personally, even on a relatively busy GtS instance I doubt this'll be an issue for anyone. Autovacuum has much better heuristics as to when it should run, and has similar heuristics to back the hell off if it's causing problems. This works out much better than us calling vacuum on a schedule.

**Comment by NyaaaWhatsUpDoc** [comment]
Setting auto_vacuum and scheduling incremental vacuums on new databases definitely sounds like a good idea. Alternatively, instead of scheduling incremental_vacuum ourselves, we could just run incremental vacuuming on gotosocial start? Then we can just say to users that are having a problem to maybe restart their instance once a month, or once a week, both of which are perfectly fine imo. Otherwise then we'll start building further divergence between SQLite and Postgres users in one set having extra background scheduled tasks. This also minimizes risk of vacuuming causing resource exhaustion, queues to back up (which we still have a bug we need to fix re: that), etc.

**Comment by daenney** [comment]
I don't think we should manually call vacuum on PG. Not even at startup. The divergence is unfortunate, but we shouldn't be applying maintenance patterns or recommendations of SQLite to PG. If calling VACUUM on a schedule is something an administrator _wants_ to do, they can already do so using something like cron.

SQLite is a single-tenant database, Postgres isn't guaranteed to be. Vacuum can cause a lot of I/O even if you limit it to a specific DB and table. This can have knock-on effects on other users. It's very unlikely we can do a better job than the autovacuum daemon when it comes to regularly scheduling these things with minimal impact and taking into account other users of the database instance.

**Comment by tsmethurst** [comment]
Mm, I'd be OK with scheduling autovacuum once per week or something for SQLite (or at least allowing users to set that behavior if they so wish), and leaving Postgres alone. The divergence is unfortunate but it seems there's not too much we can do about that. I'm wary of performing cleanup tasks on start because we used to do that with media, and it caused a big burst of activity on startup which folks weren't expecting (and which could sometimes cause the instance to take ages to start).

**Comment by daenney** [comment]
I think that's probably the best approach. I'm honestly not sure how often the vacuum calls should be done when using SQLite in incremental vacuum mode.

Given that in full mode it happens after every commit, it seems we could call `increment_vacuum` multiple times a day. Whether multiple times a day is necessary is another matter entirely.

We should add a note to our docs that informs admins that if they want to shrink the physical size of the DB on disk, they do need to call VACUUM at some point. But that should be done sparingly, at a time of their choosing and really only when running out of disk space. Having free space in the DB itself doesn't slow queries down so it's not harmful.

**Comment by NyaaaWhatsUpDoc** [comment]
I might take a look and see what other sqlite applications tend to handle these situations 🤔

**Comment by mirabilos** [comment]
PostgreSQL does have autovacuum, and/or people schedule manual vacuum anyway, e.g.:

```
tg@bove:~ $ cat /etc/cron.d/zzzlocal                                                                            
2 7 * * * postgres /usr/bin/env LANG=C LC_CTYPE=C LC_ALL=C psql -c 'VACUUM FULL FREEZE ANALYZE;' gotosocial 2>&1 | logger -t gtscron-vacuum
```

So please make that optional if you do.

(It does shrink the on-disc size of the DB, once the WALs created by the VACUUMing expire. But the more important parts are freezing old unchanged rows and especially updating planner statistics.)

**Comment by tsmethurst** [comment]
I'm gonna just close this since I don't think it's necessary for Postgres (as stated above it does autovacuum people can enable), and for SQLite we now have documentation for doing manual DB maintenance.
