### ISSUE TITLE
[question] S3 upload performance

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#2400]
I am using Cloudflare R2 as the storage for my Gotosocial instance. Since I started using it, I have noticed that the upload time for images is much longer compared to Mastodon.

## Profiling
If we measure the time taken by the `/api/v2/media` request as the duration of image uploads, uploading the same image takes approximately 6-7 seconds in Gotosocial, while in Mastodon that takes less than 3 seconds.

## Question
I wonder if this is a normal upload speed or if there might be an issue with my configuration. Is there any way to reduce the upload time?

---

Attached: My storage configuration

```
GTS_MEDIA_VIDEO_MAX_SIZE: 104857600
GTS_STORAGE_BACKEND: s3
GTS_STORAGE_S3_ENDPOINT: <account_id>.r2.cloudflarestorage.com
GTS_STORAGE_S3_PROXY: true
GTS_STORAGE_S3_ACCESS_KEY: <access_key>
GTS_STORAGE_S3_SECRET_KEY: <secret_key>
GTS_STORAGE_S3_BUCKET: <bucket_name>
GTS_STATUSES_MEDIA_MAX_FILES: 9
```

**Comment by tsmethurst** [comment]
Some things to consider: Are your GtS VPS and your S3 in the same AZ/Region? Is your GtS instance in a different location from your Mastodon instance?
