### ISSUE TITLE
[bug] No federation options in admin panel

### ISSUE THREAD

**Issue by itsdoublearon** [superseriousbusiness/gotosocial#2406]
### Describe the bug with a clear and concise description of what the bug is.

I can not get my instances on runTipi to federate with other servers. Don't see any federation options in the admin settings UI either. This is happening both on a VPS and a RPi server, so it seems like something with runTipi.

### What's your GoToSocial Version?

GoToSocial 0.12.2 git-096c517

### GoToSocial Arch

arm64 Docker

### What happened?

My instance is not being seen by other servers.

### What you expected to happen?

To be able to interact with other servers

**Comment by tsmethurst** [comment]
Federation just means that you (or accounts on your instance) follow/interact with accounts on other instances, and vice versa. Unless you're using allowlist federation mode, you don't need to do anything special in the admin settings panel to make that happen; just search for and follow an account from a client. If you are using allowlist federation mode, you should be able to add/remove domain allows via the admin settings panel, provided you're logged in to the panel as an admin user.

**Comment by itsdoublearon** [comment]
Ok thanks. New to this, and was hoping for a little more connection easily with other servers. Thanks again.
