### ISSUE TITLE
[bug] `@` not handled in autocompletion queries

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2411]
### Describe the bug with a clear and concise description of what the bug is.

When beginning to type `@meow` for autocompletion in Semaphore, I get this in the log:

```
func=bundb.queryHook.AfterQuery level=WARN duration="1m19.636948962s" query="SELECT \"account\".\"id\" FROM \"accounts\" AS \"account\" WHERE ((\"account\".\"domain\" IS NULL) OR (\"account\".\"domain\" != \"account\".\"username\")) AND (\"account\".\"id\" < 'ZZZZZZZZZZZZZZZZZZZZZZZZZZ') AND ((SELECT LOWER(CONCAT(\"account\".\"username\", COALESCE(\"account\".\"display_name\", ''))) AS \"account_text\") LIKE '%@meow%' ESCAPE '\\') ORDER BY \"account\".\"id\" DESC LIMIT 4" requestID=8gmewcmc0400166f0vg0 msg="SLOW DATABASE QUERY"
```

However, the string searched for (the `LOWER(…)`) does not even begin with a `@`.

Furthermore, this makes it good as impossible to search for “common” names as the domain is not contained in the string *and* the `LIMIT` is very low.

May I at least suggest doing:
- strip the leading `@` (but _only_ __one__ leading one!) from the search text
  - so we get `LIKE '%meow%'` but people can still search for `@` explicitly by doubling it or putting one later
- change the `LOWER(…)` sub-clause to something like `LOWER(CONCAT("account"."username", '@', COALESCE("account"."domain", 'gts.superseriousbusiness.example.org'), COALESCE("account"."display_name", '')))`
  - where `gts.superseriousbusiness.example.org` is the __account-domain__ from the configuration, of course (since GtS knows that *and* it will never change, it can put this as hardcoded string into the query, no extra hardparse penalty)
  - so we get 'lowerusername@lowerdomainlowerdisplayname' as text compared with

Additionally, perhaps raise the `LIMIT` a bit?

Thanks in advance!

### What's your GoToSocial Version?

0.13.0-rc1 git-0e2c342

### GoToSocial Arch

amd64 binary

**Comment by tsmethurst** [comment]
GtS not stripping the leading '@' looks indeed like a regression, I believe we used to do that. I'll check it out.

Coalescing the host / account domain into the query won't work; `domain` is NULL for local accounts. I could have another crack at optimizing the query in other ways though (not including the leading wildcard when doing that kind of search, for example).

The LIMIT part is provided by the client, there's not much we can (or should) do about that in GtS itself.

**Comment by mirabilos** [comment]
tobi dixit:

>GtS not stripping the leading '@' looks indeed like a regression, I
>believe we used to do that. I'll check it out.

Thanks!

>Coalescing the host / account domain into the query won't work;
>`domain` is NULL for local accounts.

Yes, that’s why I added this part to the suggested query:

COALESCE("account"."domain", 'gts.superseriousbusiness.example.org')

This expands to accounts.domain if it’s not NULL, the hardcoded
local string (which GtS would provide from the account-domain value
from the config) for local accounts.

>The LIMIT part is provided by the client, there's not much we can (or
>should) do about that in GtS itself.

Ah okay, right. Thanks for the info.

bye,
//mirabilos

**Comment by mirabilos** [comment]
Hmmhmmhmm.

Related to this (because this is where I found the slow queries, and they may be slow because it takes them a while to scan through the entire table because they find no match (any more?)):

Since “shortly”, whenever I begin to type `@foo` in Semaphore, a number of those minutes-long autocompletion queries are started.

So either Semaphore also changed something (with its last public commit on 2ⁿᵈ Feb, this is not very likely) or this is indeed a regression in the RC.

But I **do** still get autocompletion, so there must (also?) be queries that _do_ work. It’s almost instant in Semaphore and as-usual-slow-as-hell in FediText.

I tried to look a bit at that but those searches are POST queries (probably better this way, so the strings searched for don’t show up in Apache `access_log` for the admin to see) so digging into this might need more intrusive techniques.

But if I should try to check some things, compare queries, run another RC to test a proposed fix, … I’m available.

**Comment by mirabilos** [comment]
I see queries for both `'%meow%'` and `'%@meow%'` in the logs btw, maybe just filter out the second kind then?

**Comment by tsmethurst** [comment]
Pinafore/Semaphore store a bunch of things in local browser storage iirc, including autocomplete suggestions from accounts you've mentioned before. So those will show up first, quickly, and while those are showing, search requests will be passed back to the backend, iirc.
