### ISSUE TITLE
[feature] Push status edit messages to streams

### ISSUE THREAD

**Issue by Sentynel** [superseriousbusiness/gotosocial#2417]
### Is your feature request related to a problem ?

If you have a client using the streaming API connected, and a status in your timeline is edited, you don't currently get a streamed message telling you this, so the status doesn't get updated.

### Describe the solution you'd like.

Add support for the "status.update" message type on the streaming API.

### Describe alternatives you've considered.

n/a

**Comment by mirabilos** [comment]
huh… this is closed now? So if I don’t get any edit notifications, it’s a client issue?

**Comment by tsmethurst** [comment]
This issue is not related to notifications. This is about sending a websocket message with the updated representation of a status so that the client can update its view. Currently we don't have notifs for status edits. Something we'll probably cover when we add proper outgoing edit support.

**Comment by mirabilos** [comment]
tobi dixit:

>This issue is not related to notifications. This is about sending a
>websocket message with the updated representation of a status so that
>the client can update its view.

Aaaaah, okay.

>Something we'll probably cover when we add proper
>outgoing edit support.

Makes sense. Thanks for the info!
