### ISSUE TITLE
[question] Clarification - automatic remote emoji federation

### ISSUE THREAD

**Issue by filipesmedeiros** [superseriousbusiness/gotosocial#2431]
### Describe the bug with a clear and concise description of what the bug is.

When reading a post from a remote instance, that contains a custom emoji, should this emoji be automatically fetched/federated and displayed? If so, it appears that it sometimes doesn't, as shown in the screenshot below.

<img width="284" alt="Screenshot 2023-12-09 at 12 03 40" src="https://github.com/superseriousbusiness/gotosocial/assets/26208850/db50dc49-841e-42d9-a9de-d0d669fcd051">

The post seen in the original instance:
<img width="97" alt="Screenshot 2023-12-09 at 12 03 52" src="https://github.com/superseriousbusiness/gotosocial/assets/26208850/0e66aeb9-44dc-4aeb-bf03-59bc3ad660d3">

[This part of the docs](https://docs.gotosocial.org/en/latest/admin/settings/#custom-emoji) implies that they should be displayed but not fetched to the local media storage, is this correct?

### What's your GoToSocial Version?

v0.13.0-rc1

### GoToSocial Arch

amd64

### What happened?

The emoji is not displayed as an image, only as a shortcode

### What you expected to happen?

The emoji image to be fetched so I can see it in the post.

### How to reproduce it?

Hopefully just seeing any remote custom emoji that is not imported would reproduce this.

### Anything else we need to know?

I don't think so :)

**Comment by tsmethurst** [comment]
They should be downloaded from remote, cached locally, and displayed normally, but for some emojis (webp and jpeg file types, too-large emojis) they won't be. It's normal to see a few emojis missing occasionally. If you don't see any emojis ever, that's a bug.

**Comment by tsmethurst** [comment]
Related: https://github.com/superseriousbusiness/gotosocial/issues/2398

**Comment by filipesmedeiros** [comment]
I'll check the original file. I suppose the size limit can be configured?

**Comment by tsmethurst** [comment]
It can be configured yes :)
