### ISSUE TITLE
[bug] Some env vars are ignored

### ISSUE THREAD

**Issue by etkecc** [superseriousbusiness/gotosocial#2451]
### Describe the bug with a clear and concise description of what the bug is.

```
GTS_OIDC_CLIENT_SCOPES="openid,email,profile" 
```
is ignored, request is sent with `groups` included. Tried different formats (`GTS_OIDC_CLIENT_SCOPES=openid,email,profie`, and `GTS_OIDC_CLIENT_SCOPES=openid email profile` dont work either)

```
GTS_OIDC_LINK_EXISTING=true
```
(it's ignored, plus **there is no `--oidc-link-existing` cli arg** as well)

```
GTS_OIDC_ADMIN_GROUPS=admin
```

is ignored

### What's your GoToSocial Version?

v0.12.2

### GoToSocial Arch

amd64 Docker

### What happened?

Env vars are ignored

### What you expected to happen?

Env vars are respected

### How to reproduce it?

Set the mentioned env vars and observe that GTS ignores them, and uses default values instead

**Comment by tsmethurst** [comment]
Oh okay that's weird, probably just some missing config files. To work around this in the meantime, try setting those variables into a config.yaml file and mount it into your container.

**Comment by NyaaaWhatsUpDoc** [comment]
@etkecc was `GTS_OIDC_CLIENT_SCOPES` the exact variable name you were using? because the environment variable it reads from is `GTS_OIDC_SCOPES` (note no `_CLIENT`) and i can confirm the variable is being set correctly in the environment parsing test script.

**Comment by NyaaaWhatsUpDoc** [comment]
setting the other environment variables also shows them being correctly parsed in the `test/envparsing.sh` script:

```
diff --git a/test/envparsing.sh b/test/envparsing.sh
index c67d855f5..599df9508 100755
--- a/test/envparsing.sh
+++ b/test/envparsing.sh
@@ -249,8 +249,8 @@ GTS_OIDC_ISSUER='whoknows' \
 GTS_OIDC_CLIENT_ID='1234' \
 GTS_OIDC_CLIENT_SECRET='shhhh its a secret' \
 GTS_OIDC_SCOPES='read,write' \
-GTS_OIDC_LINK_EXISTING=true \
-GTS_OIDC_ADMIN_GROUPS='steamy' \
+GTS_OIDC_LINK_EXISTING=false \
+GTS_OIDC_ADMIN_GROUPS='steamy,helicopter' \
 GTS_SMTP_HOST='example.com' \
 GTS_SMTP_PORT=4269 \
 GTS_SMTP_USERNAME='sex-haver' \
OUTPUT not equal EXPECTED
114,115c114
<         "steamy",
<         "helicopter"
---
>         "steamy"
122c121
<     "oidc-link-existing": false,
---
>     "oidc-link-existing": true,

```

**Comment by tsmethurst** [comment]
Ah, the link existing thing reminds me of something someone was saying in the help channel a while ago. I think that's a separate issue. We need to clarify how that thing actually works and what it's meant to do.
