### ISSUE TITLE
[question] Ambiguos log-timestamp-format in config.yml

### ISSUE THREAD

**Issue by Ryuno-Ki** [superseriousbusiness/gotosocial#2455]
### Describe the bug with a clear and concise description of what the bug is.

Since there is ambiguity between the US-American way of describing dates and basically the rest of the world, the example has to be sensible enough to not confuse day with month.

### What's your GoToSocial Version?

v0.13.0-rc2

### GoToSocial Arch

AMD64

### What happened?

I installed GtS on my VPS bare metal as per the documentation.

When editing the config.yml I was unsure how the example and default are meant to be interpreted:

https://github.com/superseriousbusiness/gotosocial/blob/v0.13.0-rc2/example/config.yaml#L38-L47

The example says `[true, false]` which doesn't look like a string.
The default says `"02/01/2006 15:04:05.000"` which is a string but the [Go documentation on time](https://pkg.go.dev/time#pkg-constants) gives `01/02 03:04:05PM '06 -0700` as layout example.

Personally I would prefer an RFC3339 format: 2006-01-02T15:04:05Z.

As European I'm not sure, whether `02/01` is referring to 1st of February or 2nd of January.

### What you expected to happen?

I would either expect another format or use 13 etc. as day part of the example.
The example confused me.

### How to reproduce it?

Copy the `example/config.yml` and open it in a text editor.

### Anything else we need to know?

Go To Social is awesome!

**Comment by mirabilos** [comment]
I ran into the same problem and it took an absolutely **insane** amount of time until I figured out the correct magic to produce ISO 8601 timestamps for logging.

```
log-timestamp-format: "2006-01-02T15:04:05.000Z07:00"
```

(maybe this could be added to the docs?)

I think the GtS developers are utterly blameless here though, as this seems to be the NIH syntax of a golang timestamp formatting library. (I can even understand why they would use single-digit figures for day and month: so you can distinguish between zero-padded, space-padded(to some amount) and unpaded.)

But yeah, a proper ISO 8601 example will help many Europeans who haven’t had any exposure to this kind of timestamp formatting configuration (strftime is usual and translates well to Java, PHP’s is… well I thought it was bad before I saw this) understand what’s what. And maybe give them a value to start off with.
