### ISSUE TITLE
[bug] Character count don't follow Mastodon API

### ISSUE THREAD

**Issue by c-cesar** [superseriousbusiness/gotosocial#2457]
### Describe the bug with a clear and concise description of what the bug is.

Mastodon does some weird maths when calculating their post character limits: 

- a link always counts as 23 chars, and the domain of a webfinger handle doesn't count. https://docs.joinmastodon.org/user/posting/
- but the CW counts. https://github.com/mastodon/mastodon/issues/9792
Some frontends, like Semaphore, do this calculation, creating a discrepancy between characters reported by the frontend and accepted by GoToSocial, creating situations when the frontend says the post is below the character limit, but the server refuses.

### What's your GoToSocial Version?

0.13.0-rc2 git-d0bb8f0

### What happened?

GTS refuses posts that exced their char limit, but that are reported by a recomended frontend as bellow character limit if they contain links or full webfinger handles.

GTS publishes posts above character limit reported by the frontend if they contain CW.

### What you expected to happen?

The server character count to match the character count reported by recomended frontends.

### How to reproduce it?

Create a post with links or full webfinger mentions where their total character count is above GTS character limit, but bellow Mastodon limit.

Ceate posts where the sum of CW and text is above character limit. (Only some clients, like Subway Tooter, allows to try to publish the post, even reporting its above the character limit.)

### Anything else we need to know?

This is mostly a papercut, as we can simply increase the character limit as a workaround.

**Comment by tsmethurst** [comment]
Ah thanks for highlighting this. We'll take a look :eyes:

**Comment by NyaaaWhatsUpDoc** [comment]
#2682 should handle this for now. whether we want to *exactly* follow mastodon's URL counting behaviour in the future i'm not totally certain, but going to remove this from the v0.14.0 milestone at least.

**Comment by tsmethurst** [comment]
I'm gonna close this for now, I think the behavior we landed on after https://github.com/superseriousbusiness/gotosocial/pull/2682 is probably good enough / close enough to Mastodon, especially given our much higher default character limit, which makes it less important to prune links to 23 chars.
