### ISSUE TITLE
[bug] Parent status / replied-to status not dereferenced sometimes

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2460]
This is sorta related to a bug I thought we'd fixed already. Sometimes when a status from someone I follow gets inserted into the timeline, after being federated in via a Create activity, the parent status (`in_reply_to_uri`) doesn't get dereferenced, so the reply appears to be orphaned, since it's serialized via the API as having `in_reply_to = null`.

Checking in the db, I see that the status does have an `in_reply_to_uri` set, and it's the URI of a public / unlisted status on an instance I don't block, by a user I don't block, so it should have been derefed before the child status was timelined.

We should check again through our dereferencing logic to ensure that this situation doesn't happen, since it's rather jarring and may also lead to statuses being put in the timeline when they oughtn't.

**Comment by daenney** [comment]
I got this chain recently too. Initially:

```
sqlite> select in_reply_to_id, in_reply_to_uri, in_reply_to_account_id  from statuses where statuses.url = 'https://goblin.technology/@tobi/statuses/XXXX';
in_reply_to_id  in_reply_to_uri                                               in_reply_to_account_id
--------------  ------------------------------------------------------------  ----------------------
NULL            https://k.iim.gay/users/kim/statuses/YYYY  NULL                                                                                           
```

I tried to refresh that status a few times, but the thread kept being stuck in detached head state.

This morning, after refreshing it:

```
sqlite> select in_reply_to_id, in_reply_to_uri, in_reply_to_account_id  from statuses where statuses.url = 'https://goblin.technology/@tobi/statuses/XXXX';
in_reply_to_id              in_reply_to_uri                                               in_reply_to_account_id    
--------------------------  ------------------------------------------------------------  --------------------------
ZZZZ  https://k.iim.gay/users/kim/statuses/YYYY  AAAA
```

**Comment by benjaminbhollon** [comment]
I've been seeing this a number of times on my instance but hadn't had time to investigate yet. At least once, my replies to the chain weren't being federated to the other instance—though that may be a completely unrelated issue or a one-time error.

**Comment by mirabilos** [comment]
This does not seem to be fixed in 0.13.1-SNAPSHOT git-d59cba4 🦥

I have a fresh thread from today, from which I see https://alpha.polymaths.social/@rl_dane/statuses/01HNZAQ7YK1HTFZ1T49T1TV0TB because I follow `rl_dane` and that status is public, but I see neither parent nor children in https://semaphore.social/statuses/01HNZAQ7N8V5J1SQZZ8S6YD27P (which is the equivalent on my instance).

```
gotosocial=> \pset null nil
Null display is "nil".
gotosocial=> select in_reply_to_id, in_reply_to_uri, in_reply_to_account_id  from statuses where id='01HNZAQ7N8V5J1SQZZ8S6YD27P';
 in_reply_to_id |                                 in_reply_to_uri                                 | in_reply_to_account_id 
----------------+---------------------------------------------------------------------------------+------------------------
 nil            | https://alpha.polymaths.social/users/sotolf/statuses/01HNZAG6Y3TY64XZCNVATQ6Y25 | nil
(1 row)
```

**Comment by mirabilos** [comment]
Even after doing a Semaphore search for the `sotolf` post, which does show it, I get:

```
gotosocial=> select in_reply_to_id, in_reply_to_uri, in_reply_to_account_id  from statuses where uri='https://alpha.polymaths.social/users/sotolf/statuses/01HNZAG6Y3TY64XZCNVATQ6Y25';
       in_reply_to_id       |                                 in_reply_to_uri                                  |   in_reply_to_account_id   
----------------------------+----------------------------------------------------------------------------------+----------------------------
 01HNZ9YYA8DJMYB5FRV1XPHQQM | https://alpha.polymaths.social/users/rl_dane/statuses/01HNZ9YYP59EMRQQX7CF6ZMB5A | 01HA0YDV7MWW55DV492GYYN1JA
(1 row)

gotosocial=> select in_reply_to_id, in_reply_to_uri, in_reply_to_account_id  from statuses where id='01HNZAQ7N8V5J1SQZZ8S6YD27P';
 in_reply_to_id |                                 in_reply_to_uri                                 | in_reply_to_account_id 
----------------+---------------------------------------------------------------------------------+------------------------
 nil            | https://alpha.polymaths.social/users/sotolf/statuses/01HNZAG6Y3TY64XZCNVATQ6Y25 | nil
(1 row)
```

I can also not see the `rl_dane` post as child of the `sotolf` post.

**Comment by mirabilos** [comment]
Right.

It’s now about an hour later, still no change, but I’ll try again later.

I’ve not enabled debug logging, but all I see are the usual API requests from clients and the usual `msg="performing request"` ones from `httpclient.(*Client).DoSigned`, nothing suspicious.

I do indeed follow a subset of the people in the thread, but not everyone.

If I should enable debug logging, upgrade to a later snapshot, etc. just ping me.

**Comment by tsmethurst** [comment]
> It’s now about an hour later, still no change, but I’ll try again later.

We have re-dereferencing of statuses on a cooldown of 2 hours, so it may still be considered "fresh" by your instance and not get re-dereferenced yet.

> If I should enable debug logging, upgrade to a later snapshot, etc. just ping me.

Righty ho. Should be fine for now, I'll just go through the code again step by step later this week, for a start, and see if I can spot anything funny.

By the way, we did a security update earlier today so you'll want to update to that anyway: https://gts.superseriousbusiness.org/@gotosocial/statuses/01HNZ5GF2EM5M899B7RKXYNMH9

**Comment by mirabilos** [comment]
Ah, missed that, I was in a meeting until a few minutes ago, will upgrade, thanks!

**Comment by mirabilos** [comment]
Interesting. I got the direct parent and one child, but no more than that, but not upon merely visiting the toot’s page on Semaphore, but only after pasting the link into its search form and submitting that I got the reply, then I pressed F5 on the toot’s page and also got the parent.

**Comment by mirabilos** [comment]
… ah hm, that may be because it’s now 429ing my instance õÕ

**Comment by mirabilos** [comment]
got another one: <https://gts.superseriousbusiness.org/@gotosocial/statuses/01HPQHNA9YS9QK2W61GEEF6J9J> which is 01HPQHN9R0ENT8MPM12SK7Q4S8 on my instance.

```
gotosocial=> \pset null nil
Null display is "nil".
gotosocial=> select in_reply_to_id, in_reply_to_uri, in_reply_to_account_id  from statuses where id='01HPQHN9R0ENT8MPM12SK7Q4S8';
 in_reply_to_id |                                     in_reply_to_uri                                     | in_reply_to_account_id 
----------------+-----------------------------------------------------------------------------------------+------------------------
 nil            | https://alpha.polymaths.social/users/orbitalmartian/statuses/01HPQHKNNMVJPPK8VPM61KT6SK | nil
(1 row)
```

I can see the context on the superseriousbusiness instance’s webview but not on my instance (now running 0.13.1-SNAPSHOT+git-8b82119 🦥)…

**Comment by mirabilos** [comment]
Dixi quod…

>got another one

And also here, waiting for some hours made the thread resolve,
so there’s something wrong with the initial setup, but later it
gets fixed.

The part about it getting fixed only later is, of course, the
frustrating one for the user experience ;-)

**Comment by tsmethurst** [comment]
I'm investigating this one again now, since I can semi-reliably reproduce it. I have enough information now, it's just a matter of going through the code with my favourite debugger (fmt.Printf statements) and catching it.

**Comment by tsmethurst** [comment]
Think I've found the issue, and it's a one-liner (see above).

**Comment by NyaaaWhatsUpDoc** [comment]
@tsmethurst do you think we can mark this as closed now?

**Comment by tsmethurst** [comment]
Yes! Kapow!
