### ISSUE TITLE
[chore] Change `<aside>` in unknown media API representations to `<small>` for better presentation

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2461]
See https://github.com/cheeaun/phanpy/issues/365

Currently we use `<aside>` which, on further inspection, is not really semantically correct, since asides are meant to be able to stand as independent pieces of content outside of the context of the element that contains them. If we change this to `<small>` then we avoid semantic confusion while also hopefully providing a visual differentiation for the injected unknown media message.

**Comment by firescry** [comment]
Also [Elk](/elk-zone/elk) client has a problem with the new notice about unavailable media and completely ignores it:
![elk](https://github.com/superseriousbusiness/gotosocial/assets/49809580/82bb8cc4-9588-411f-9062-717fab08e0a8)

While the same post in Tusky shows the notice as expected:
![tusky](https://github.com/superseriousbusiness/gotosocial/assets/49809580/887ee284-5ca9-40e6-b570-f954293378cf)

**Comment by tsmethurst** [comment]
If it completely ignores it, that seems more like a bug or an oversight in Elk. `<aside>` is completely valid HTML. But we'll change it to something else anyway.

**Comment by firescry** [comment]
Got it :) I'll wait for a change in GTS then and if problem persist, I'll report it to Elk :)

**Comment by cheeaun** [comment]
List of allowed elements (and classnames, attrs) on Elk here: https://github.com/elk-zone/elk/blob/3ae2d50bff5a8c03a6af6ed45876bda82f1b6967/composables/content-parse.ts#L23-L69

**Comment by filipesmedeiros** [comment]
I remember @cheeaun also suggested that we add a custom `class` to this element. It's kind of "ugly" in the sense that we're using a styling feature for markup that should be styling agnostic, but it can really help frontends style it, right? Something like `class="gts-unloadable-media"` or whatever.

**Comment by filipesmedeiros** [comment]
Also, this comment I think is related (although not the same): https://github.com/superseriousbusiness/gotosocial/pull/2331#issuecomment-1859646378
