### ISSUE TITLE
[bug] Authorisation of streaming endpoint

### ISSUE THREAD

**Issue by filipesmedeiros** [superseriousbusiness/gotosocial#2462]
### Describe the bug with a clear and concise description of what the bug is.

The authorisation of the streaming endpoint seems to be done in a different way from the Mastodon API, causing some confusion within clients.

### What's your GoToSocial Version?

v0.13.0

### GoToSocial Arch

amd64

### What happened?

On Phanpy, trying to connect to the websocket streaming endpoint failed.

<img width="699" alt="Browser logs showing errors trying to connect to the streaming endpoint of GtS" src="https://github.com/superseriousbusiness/gotosocial/assets/26208850/92fdb1b2-0817-4211-9279-a3c32ddf9b66">

Same happened for Elk.

### What you expected to happen?

The connection to be established successfully.

### How to reproduce it?

Login with an account on Phanpy or Elk, and go to the console (hopefully).

### Anything else we need to know?

[Mastodon does it with a header](https://docs.joinmastodon.org/methods/streaming/#headers), while [GtS does it with a query parameter](https://docs.gotosocial.org/en/latest/api/swagger/). Don't know if this is on purpose and/or for historical reasons.

A tried to open a connection using [websocat](https://github.com/vi/websocat) with the correct authentication (by manually copying the authentication token) and it works as intended!

**Comment by filipesmedeiros** [comment]
Nevermind, this is wrong! I was looking at the REST endpoint on the Mastodon docs :(

**Comment by tsmethurst** [comment]
Aha OK :') I was just about to write a reply.
