### ISSUE TITLE
[feature] Better conversation thread sorting

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2479]
Currently when we return thread context (aka conversation) from the API or on the web frontend, our sorting is a little strange because it interleaves replies from other accounts into the "main" thread of the conversation, interrupting the flow:

- Post by account A (start of thread) 1/4
- Self reply by account A 2/4
- Reply from account B to 2/4
- Self reply by account A 3/4
- Reply from account C to 3/4
- etc etc
- Self reply by account A (end of thread) 4/4

We should try to sort conversation threads a little nicer so that posts are more readably arranged / divided into main and comments sections:

- Post by account A (start of thread) 1/4
- Self reply by account A 2/4
- Self reply by account A 3/4
- Self reply by account A (end of thread) 4/4
- **Comments section**
- Reply from account B to 2/4
- Reply from account C to 3/4
- etc etc

**Comment by mirabilos** [comment]
Oh, is it GtS that does the sorting of replies, not the client?

I have this problem in FediText, when I zoom into a post to read the replies, it loads the first couple of them, then I scroll down, and the newly-loaded ones are somehow “up” of where I already was and the ones I was just reading have jumped down to the bottom, so I have to scroll either to the top to restart reading, or to the bottom to continue where I was then go to the top anyway.

Is this a GtS issue? Do you want it in here or separate? Or should I continue to poke at FediText for that?

**Comment by tsmethurst** [comment]
> Oh, is it GtS that does the sorting of replies, not the client?

GtS does initial sorting and tries to serve things in a reasonable order (hopefully more reasonable after we work on this feature). But clients can (and do) still jiggle replies around. The latter thing sounds like it might be a Feditext issue, but I'm not sure.

**Comment by VyrCossont** [comment]
Feditext isn't doing anything special; I think this is simply a GtS difference from Mastodon, and the proposed sorting into self-replies/other replies is the correct fix.
