### ISSUE TITLE
[bug] Pending follow request show as rejected when using Elk

### ISSUE THREAD

**Issue by coxde** [superseriousbusiness/gotosocial#2487]
### Describe the bug with a clear and concise description of what the bug is.

Like this [issue](https://github.com/elk-zone/elk/issues/2531) said, when I use Elk as the client of GtS, if other accounts try to follow a locked account, the follow request would show as "You have rejected the request" in notifications. But actually the request is still pending, you can confirm that is a pending request by using other client like [Semaphore](https://github.com/NickColley/semaphore). And if the "other accounts" are from the same instance, there will be no notification at all.

According to [their contributor](https://github.com/elk-zone/elk/issues/2531#issuecomment-1871847252), this issue may be caused by GtS' relationship API lack of a attribute `requested_by`.

### What's your GoToSocial Version?

0.13.0 git-f4fcffc

### GoToSocial Arch

amd64 Docker

### What you expected to happen?

The notification card should show the handle buttons to let user approve it or reject it.

### How to reproduce it?

1. Use Elk as the client.
2. Make A account as locked.
3. Using any other accounts to follow A.

### Anything else we need to know?

I would like to thank you for this fantastic ActivityPub software. It's been a pleasure to see GtS grow from the very beginning to the point where it's about to go into beta.

**Comment by tsmethurst** [comment]
Man, I don't understand how Mastodon keeps making these API changes and not also breaking compatibility for older Mastodon versions as well (for people who don't want to use the >4.2.x versions).

Anyway. We'll check it out, thanks.

**Comment by tsmethurst** [comment]
Related to https://github.com/superseriousbusiness/gotosocial/issues/871

**Comment by coxde** [comment]
If it helps, [this](https://github.com/mastodon/mastodon/pull/20785) might be where they added `requested_by`.

**Comment by tsmethurst** [comment]
Thanks :)
