### ISSUE TITLE
[question] Will GoToSocial work with PostgresQL 16.x?

### ISSUE THREAD

**Issue by nachtlied1** [superseriousbusiness/gotosocial#2488]
### Describe the bug with a clear and concise description of what the bug is.

(This is more of a question than a bug report, but I'm not on Matrix, and I didn't see a template for just questions here either...)

Question:
I currently use PostgresQL 15.5.  However, if I wanted to upgrade to 16.x in the future, I'd like to know if GTS would still work fine with that version?

I think so? But there could be GTS nuances that I'm unaware of. And I'd prefer to confirm any potential issues in advance so that I don't upgrade and then learn the hard way that upgrading was a bad idea. :)

### What's your GoToSocial Version?

v0.13.0

### GoToSocial Arch

arm64 Docker

### What happened?

N/A

### What you expected to happen?

N/A

### How to reproduce it?

N/A

### Anything else we need to know?

Release notes for PostgresQL 16.0: https://www.postgresql.org/docs/release/16.0/

**Comment by tsmethurst** [comment]
It should yeah, I don't believe we rely on anything particularly spicy in Postgres, but we haven't tested it. So take that as a firm "probably".
