### ISSUE TITLE
[feature] mute words and/or hashtags

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2498]
### Is your feature request related to a problem ?

Next to #717, the ability to mute posts is something I’m looking for. My Fediverse experience is mature enough I wish for this, so I can e.g. not see dog pictures of people I like to see cat pictures from, or to avoid high-rate political discussions while getting otherwise posts and boosts, by muting, say, politician names.

### Describe the solution you'd like.

I’d like to have a list of hashtags to mute, and a list of “words” to mute, where “words” should have the ability to do both exact and substring matches as well as match multi-word strings (such as a first and last name); I think matching should always be case-insensitive, but some people might have use for case-sensitive matching?

I’ve no idea about the implementation. Some clients might support it, but doing it in /settings would suffice for me.

### Describe alternatives you've considered.

NONE

### Additional context.

I’d really love if both #717 and this will make it to an upcoming milestone `<3`

**Comment by tsmethurst** [comment]
Oh yes, this is basically "filters" I think. That's this one: https://github.com/superseriousbusiness/gotosocial/issues/1472

**Comment by mirabilos** [comment]
Oh okay. A search for “mute” didn’t find that one.

Could you perhaps edit its title to add “mute words and hashtags”, then we can close this one?

(Though that one mostly wants a specific existing API adapted, whereas I’d be fine with having to use /settings for this.)

**Comment by tsmethurst** [comment]
Done!
