### ISSUE TITLE
[question] status not yet deref'd

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2511]
I see a couple lines along the theme of…

    timestamp="2024-01-08T23:59:50.749Z" func=visibility.(*Filter).isStatusHomeTimelineable level=WARN msg="status not yet deref'd: https://sunny.garden/users/georgepenney/statuses/11[…]

… in the log. Do I need to worry, as it’s a warning?

**Comment by tsmethurst** [comment]
Nah, it's not much to worry about. The warning is mostly to say that the derived visibility of the given status may not be entirely accurate due to a parent not being dereferenced yet. It's not an operational issue.
