### ISSUE TITLE
[bug] Profile bio fields overflow with long text such as links instead of word breaking and wrapping. + CSS fix

### ISSUE THREAD

**Issue by jwbjnwolf** [superseriousbusiness/gotosocial#2528]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

When you have long text in your bio or in the meta data fields such as a long link, it doesn't wrap correctly staying in the container. If you have a dash for example in the link in the right place, then it will wrap correct because a dash is the same as a word break in this regard, but without a word break/dash, the word that'd need wrapping to not overflow overflowss outside of the container.

Here's for example the GotToSocial account's links, focusing on the Matrix link which has a dash where it needs to wrap, so it wraps, unlike the opencollective and github links.
<img width="411" alt="GoToSocial account's profile links" src="https://github.com/superseriousbusiness/gotosocial/assets/59905825/bbe889cf-8be7-45bc-bbee-f13c3631a32e">

When you remove that dash from the matrix link where it needs to wrap, it no longer wraps correct and overflows outside of the container like so:
<img width="496" alt="GoToSocial account's profile links" src="https://github.com/superseriousbusiness/gotosocial/assets/59905825/ac226de0-867c-40c8-ac5c-7e153e8f2819">

The Profile field titles behave the same as well, that say you have a long word in there such as Supercalifragilisticexpialidocious, which may need to be wrapped depending on the viewport, here for example on a narrower viewport width, it overflows.
<img width="278" alt="One of GoToSocial's account profile field titles but it's Mary Poppins and she's popping out of the bio container" src="https://github.com/superseriousbusiness/gotosocial/assets/59905825/d88c7dde-805f-4185-b072-793ad77053fd">

If I split up as two words like Supercalifragilistic expialidocious, then it doesn't overflow as it wraps correctly.
<img width="259" alt="One of GoToSocial's account profile field titles but it's Mary Poppins and she's not popping out of the bio container" src="https://github.com/superseriousbusiness/gotosocial/assets/59905825/8b99297c-efb8-4d27-a74c-6fed828d098c">

I initally thought this was just happening with Chromium/Safari browsers, because with their behaviour, they don't treat slashes like how dashes behave like word breaks, whereas Firefox does treat slashes the same, so it's not so noticable. However as shown here, with again a smaller viewport, if a link is extra long without dashes/slashes like the Matrix link, then it overflows like so.
<img width="313" alt="GoToSocial's account profile fields as viewed in firefox" src="https://github.com/superseriousbusiness/gotosocial/assets/59905825/e439ab99-db37-4d2b-9c51-76a18013d09a">

This also happens in the bio to. I happens with the whole about column with any text that doesn't have a break at the point it needs to wrap to the next line. The same doesn't happen though with the posts column, whcih I'm sure would of been picked up had it been doing so lol.
<img width="665" alt="GoToSocial's account showing the top pinped post with a link to github where the gotosocial in the link breaks to wrap to the next line even though it's one word without any breaks that'd be overflowing in the profile bio fields" src="https://github.com/superseriousbusiness/gotosocial/assets/59905825/1d99aa56-2fd9-43a1-8bfc-9aff51951e71">

### What's your GoToSocial Version?

0.13.1

### Browser version

Safar/Chromium browsers are more noticable, but also does happen on Firefox 

### What you expected to happen?

For text to wrap to the next line regardless of whether it has a word break or not where it's supposed to wrap.

### How to reproduce it?

On Chromium/Safari browsers, put a long link or text in your bio that needs to you expect to wrap. See how it overflows if there's no word break (such as a dash or space) at the point where it should wrap to the next line.

On Firefox browsers that may not be so noticable with links because Firefox treats slashes like dashes, put long text in without any slashes, and see it again overflowing where it's supposed to be wrapping.

### Anything else we need to know?

# CSS Fix

The posts don't have the issue because `.toot .text .content` has a `word-break: break-word;` rule in the CSS.

Adding said CSS to the `.profile .about-user .fields .field` too will fix the issue.
<img width="735" alt="Screenshot of adding the break-word css rule to the profile fields which no in turn correctly break words to be able to wrap instead of overflowing the container" src="https://github.com/superseriousbusiness/gotosocial/assets/59905825/d2579b6e-d667-4d07-9eb4-7873a0dfb169">

**Comment by tsmethurst** [comment]
Thank you for the detailed report!
