### ISSUE TITLE
[bug] allowlist/blocklist (partially) applies depending on which was added later

### ISSUE THREAD

**Issue by itsjustduc** [superseriousbusiness/gotosocial#2541]
### Describe the bug with a clear and concise description of what the bug is.

if i add example.org to blocklist and then to allowlist, federation works fine. if i do it the other way around, it's broken. 

### What's your GoToSocial Version?

v0.13.1-SNAPSHOT git-dfc7656

### GoToSocial Arch

arm64 Binary

### What happened?

if i add example.org to blocklist and then to allowlist, federation works fine. an account from there returns a list of toots. but then if i unblock and reblock it (without removing it from allowlist), federation breaks. 
http responses on some endpoints from what i can tell based on masto-fe and semaphore:
**blocklist and then allowlist:**  (works as expected ✅) 
`/lookup`: status 200, returns account details
`/statuses`:  status 200, returns list of toots
`/follow`: status 200, follow goes through
**allowlist and then blocklist:** (does not work as expected ❌)
`/lookup`: status 200, returns account details
`/statuses`:  status 200, returns empty `[]`
`/follow`: status 404, returns `{"error":"Not Found: target account not found"}`
**blocklist only** (works as expected ✅) 
`/lookup`: status 404, returns `{"error":"Not Found: @user@example.tld not found"}`
`/statuses`:  status 200, returns empty `[]`
`/follow`: status 404, returns `{"error":"Not Found: target account not found"}`

### What you expected to happen?

[see documentation](https://docs.gotosocial.org/en/latest/admin/federation_modes/#combining-blocks-and-allows)

### How to reproduce it?

add a domain to the allowlist, then add the same domain to the blocklist. look up an arbitrary user of that instance, and it should return the user, but not their toots (and following probably also shouldn't work).

**Comment by tsmethurst** [comment]
Just to verify, are you running in allowlist mode or blocklist mode (the default)?

**Comment by itsjustduc** [comment]
blocklist mode

**Comment by tsmethurst** [comment]
I edited the question after I posted it, sorry about that. Could you answer the second part too?

**Comment by itsjustduc** [comment]
same for every user
