### ISSUE TITLE
[bug] 500 error when setting alias to mastodon

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#2552]
### Describe the bug with a clear and concise description of what the bug is.

I encountered this while testing #2519 and trying to set my gts account as an alias of my mastodon account. 

### What's your GoToSocial Version?

v0.13.1-SNAPSHOT git-b2cacd6

### GoToSocial Arch

arm64 Docker

### What happened?

I entered `https://mastodon.social/@<my_username>` and clicked save, then got an 500 error.

### What you expected to happen?

The alias was set successfully.

### How to reproduce it?

1. Enter mastodon user url (e.g.  `https://mastodon.social/@<my_username>` ) in migration panel
2. See error

## Logs

```
gotosocial | timestamp="21/01/2024 14:43:43.728" func=server.glob..func1.Logger.func13.1 level=ERROR latency="4.70556ms" userAgent="***" method=POST statusCode=500 path=/api/v1/accounts/alias clientIP=223.97.49.77 errors="Error #01: Alias: db error updating also_known_as_uri: ERROR: malformed array literal: \"[\"https://mastodon.social/users/icarus22\"]\" (SQLSTATE 22P02)\n" requestID=xcvqmb4d04001g4zrrzg msg="Internal Server Error: wrote 54B"
```

**Comment by tsmethurst** [comment]
Thanks, looks like something specific to Postgres, hmm.

**Comment by CDN18** [comment]
Thanks for the quick fix! Can confirm it's working now on postgres.

**Comment by tsmethurst** [comment]
Great. Just be aware that the setting doesn't actually *do* anything yet; it's not plumbed in to anything, so don't expect it to work yet :P
