### ISSUE TITLE
[question] should GtS support tables in Markdown (and incoming HTML)?

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2554]
Some of my RSS feeds have tables in them, which the Markdownify-patched Feediverse helpfully translates into the pipes-and-dashes thing used for Markdown tables.

I suspect GtS does not enable the Goldenmark tables extension, and/or its HTML filter doesn’t let the table tags through.

Question is, should it, or is it a good thing it doesn’t and should I try to get Markdownify (or bs4 or something) to flatten the tables?

At least [honk](https://humungus.tedunangst.com/r/honk/m/activitypub.7) actively documents HTML table support.

**Comment by tsmethurst** [comment]
We actually tried allowing tables through for a while! But in my testing most clients displayed them terribly, and Mastodon handled them terribly too, so we decided not to bother (see https://github.com/superseriousbusiness/gotosocial/pull/116). So indeed they are currently turned off, and will likely remain that way unless someone makes a PR that patches them in and runs some tests showing that they work OK now.

**Comment by mirabilos** [comment]
hmmh… though Mastodon renders (rendered?) _everything_ awfully, e.g. lists had not even a space, let alone newline plus list bullet, between the items… I think things got a bit better now? Dunno, I don’t use Mastodon…

But, okay, then I’ll look into flattening those tables for now.
