### ISSUE TITLE
[feature] Additional Prometheus metrics

### ISSUE THREAD

**Issue by Tsuribori** [superseriousbusiness/gotosocial#2569]
### Is your feature request related to a problem ?

Metrics are currently collected on Go, HTTP and DB performance. Additional instance specific metrics that could be added are the ones shown in the frontend frontpage UI:

- Number of instance users
- Number of instance statuses
- Number of instances federated with

### Describe the solution you'd like.

Adding OTEL meters for these so they are exported as Prometheus metrics

### Describe alternatives you've considered.

NONE

### Additional context.

A question about implementation, should the meters live in `internal/metrics` or `internal/api/metrics`?

**Comment by daenney** [comment]
`api/internal/metrics` is only the URL handler that serves `/metrics` for Prometheus clients to scrape.
