### ISSUE TITLE
[bug] Instance about page text is incomplete when there are no posts or no federating instances

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#2588]
#2480 refactors the `home to x users who wrote x posts, federating with x instances` into `web/template/page_header.tmpl`.

I'm setting up a new gts instance. While the newly set up instance doesn't have any post and any federating instance, the statistics section seems a little bit weird, which, in other words, does not read as smoothly.

When there's no post, it says `home to x users who wrote, federating with ... `
When there's no federating instance, it says `home to x users who wrote, federating with`

Not sure if this is a front end bug, I came here to ask this question. Screenshot attached:

![image](https://github.com/superseriousbusiness/gotosocial/assets/46210502/7a67afb8-9243-4e8c-bc21-369e6ba7e0db)

![image](https://github.com/superseriousbusiness/gotosocial/assets/46210502/5cbbb241-62ae-42d9-ad44-9a699c079d45)

**Comment by tsmethurst** [comment]
Oh I think that's a bug, thanks! I'll take a look before we put this in a release.
