### ISSUE TITLE
[bug] follow_requests endpoint seems to return null under certain circumstances

### ISSUE THREAD

**Issue by Follpvosten** [superseriousbusiness/gotosocial#2595]
### Describe the bug with a clear and concise description of what the bug is.

I got two follow requests from a suspicious pixelfed server. Fediblocked that server without doing anything to the FRs, and now I cannot look at my follow requests in any client, because the endpoint returns null.

```
Feb 01 06:52:17 kcloud-nix gotosocial[1221272]: timestamp="01/02/2024 06:52:17.459" func=server.glob..func1.Logger.func13.1 level=INFO latency="781.048µs" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0" method=GET statusCode=200 path=/api/v1/follow_requests clientIP=83.64.142.10 requestID=6ag3jrwd04001742yebg msg="OK: wrote 28B"
```
![grafik](https://github.com/superseriousbusiness/gotosocial/assets/22855787/20b42932-94bf-46af-ba44-d15253146c9d)

I have not done any further investigaton, let me know if I can help somehow.

### What's your GoToSocial Version?

v0.13.0

### GoToSocial Arch

aarch64 from nixos-unstable

**Comment by tsmethurst** [comment]
Thank you! Probably something silly and small, will add this to the 0.14.0 milestone.
