### ISSUE TITLE
[bug] instance logo squished

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2607]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

The new frontend (on `/`) squishes the instance logo to 100×100 px whereas the old one would allow nōn-square logos.

### What's your GoToSocial Version?

0.13.1-SNAPSHOT git-d59cba4 🦥

### Browser version

Firefox 115.7.0esr (Debian/amd64)

**Comment by tsmethurst** [comment]
Ah right, a mistake from the template/html/css rework. I'll fix it for 0.14.0. Thanks!

**Comment by mirabilos** [comment]
Cheers! (It’s only cosmetic, but I was going through the pages to see where all my custom CSS needed changes.)

I also reinstated that it’s much smaller height for the other pages, maybe you want that as well?

```
--- page_header.tmpl.orig
+++ page_header.tmpl
@@ -61,12 +61,15 @@ Instance Logo
         src="{{- .instance.Thumbnail -}}"
         alt="{{- template "thumbnailDescription" . -}}"
         title="{{- template "thumbnailDescription" . -}}"
-        width="100"
+{{- if .showStrap }}
         height="100"
+{{- else -}}
+        height="50"
+{{- end }}
     />
     <h1>{{- .instance.Title -}}</h1>
 </a>
 {{- if .showStrap }}
-<aside>home to {{ template "strapUsers" . }} who wrote {{ template "strapPosts" . }}, federating with {{ template "strapInstances" . }}</aside>
+<aside class="gentium x18pt">home to {{ template "strapUsers" . }} who wrote {{ template "strapPosts" . }}, federating with {{ template "strapInstances" . }}</aside>
 {{- end }}
 {{- end }}
\ No newline at end of file
```

**Comment by mirabilos** [comment]
I was just looking at putting this into a PR, but the old height was `6rem` for the `/` page and `3rem` for the other pages, which we cannot put into the `img[@height]` attribute, so this needs a bit more hands-on than I can do at the moment.

Would you perhaps, when you touch this anyway, add the following, which is only slightly related but having yet another issue would be overkill:

```
--- opt/GtS/web/template.orig/frontend.tmpl
+++ frontend.tmpl
@@ -18,7 +18,7 @@
 */ -}}

 {{- with . }}
-<main class="lightgray">
+<main class="lightgray gts-frontend">
     <div id="root"></div>
 </main>
 {{- end }}
```

This allows user CSS to determine when it’s on the `/settings` page, e.g. I have changed the `ul li::before (content)` for the normal pages but have to reset that for the settings page obviously, but in contrast to GtS-provided CSS I cannot rely on inclusion of an extra CSS file for these, so I go by that.

Though tbh `id="gts-frontend"` would probably be even better.

**Comment by tsmethurst** [comment]
Fixed the regression with https://github.com/superseriousbusiness/gotosocial/pull/2669, which just goes back to basically the previous behavior with a few small changes.

Other thing covered here: https://github.com/superseriousbusiness/gotosocial/pull/2674
