### ISSUE TITLE
[bug] snapshot docker image build got overwritten by release

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#2609]
### Describe the bug with a clear and concise description of what the bug is.

After upgrading to aa396c78d30c129bb2145765d3990571dbc025bb snapshot, the whole instance stopped working. The log was filling with error `error populating instance contact account: ERROR: column account.also_known_as does not exist`

### What's your GoToSocial Version?

v0.13.2-SNAPSHOT git-f5314c0

### GoToSocial Arch

arm64 Docker

**Comment by CDN18** [comment]
I'm afraid we need to build the main branch again and push it to `snapshot`. The snapshot build got overwritten by the v0.13.2 release.

**Comment by tsmethurst** [comment]
Ah thanks, will fix that immediately.

**Comment by tsmethurst** [comment]
Yup, running our CI/CD again, it will be fixed in a few minutes :) Thanks for reporting!

**Comment by CDN18** [comment]
@tsmethurst It seems that the docker snapshot build still gets overwritten every time a new release comes out, which could result in similar db migration bugs like this issue in the future. Should we change the pushing logic a bit to separate snapshot from release?

**Comment by tsmethurst** [comment]
Ah yes that's probably a good idea... I'll make a separate issue for that.

**Comment by CDN18** [comment]
Update: the v0.14.1 release-overwrittened snapshot image did cause another bug, though not as critical as this issue.

The container log was filling with `error populating move: sql: no rows in result set`
```
gts | timestamp="09/03/2024 09:25:18.791" func=typeutils.(*Converter).AccountToAPIAccountPublic level=ERROR msg="error(s) populating account, will continue: PopulateAccount: error populating move: sql: no rows in result set"
gts | timestamp="09/03/2024 09:25:18.799" func=typeutils.(*Converter).AccountToAPIAccountPublic level=ERROR msg="error(s) populating account, will continue: PopulateAccount: error populating move: sql: no rows in result set"
```

For anyone facing the same or a similar issue, I recommend retaining the old images to facilitate a quick rollback until #2737 is addressed.
