### ISSUE TITLE
[bug] Images being dropped from small Mastodon server located far away

### ISSUE THREAD

**Issue by belkadan** [superseriousbusiness/gotosocial#2615]
### Describe the bug with a clear and concise description of what the bug is.

Images specifically from `@vampiress@eigenmagic.net`, whose Mastodon server is in Australia, fail to make it to my server in the US (something I wouldn't have known if not for the "attachment could not be downloaded" notices added in 0.13, so thank you for those!). Checking the logs, I see

```
gotosocial  | timestamp="07/02/2024 22:08:53.248" func=server.glob..func1.Logger
.func13.1 level=INFO latency="3.538956ms" userAgent="http.rb/5.1.1 (Mastodon/4.2
.5; +https://eigenmagic.net/)" method=POST statusCode=202 path=/users/jrose/inbo
x clientIP=180.150.56.173 requestID=zkgsv1cd040015zqfkdg msg="Accepted: wrote 45
B"
gotosocial  | timestamp="07/02/2024 22:08:53.248" func=workers.(*Processor).Proc
essFromFediAPI level=INFO activityType=Create objectType=Note toAccount=jrose re
questID=zkgsv1cd040015zqfkdg msg="processing from fedi API"
gotosocial  | timestamp="07/02/2024 22:08:53.260" func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://eigenmagic.net/system/media_attachments/files/111/892/478/126/668/546/original/bcb227c5344b1962.jpeg requestID=zkgsv1cd040015zqfkdg pubKeyID=https://social.belkadan.com/users/jrose/main-key msg="performing request"
gotosocial  | timestamp="07/02/2024 22:09:03.263" func=dereferencing.(*Dereferencer).fetchStatusAttachments level=WARN requestID=zkgsv1cd040015zqfkdg msg="partially loaded attachment: store: error writing media to storage: context deadline exceeded (Client.Timeout or context cancellation while reading body)"
gotosocial  | timestamp="07/02/2024 22:09:03.401" func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://eigenmagic.net/users/vampiress/statuses/111892478338944285/replies?only_other_accounts=true&page=true pubKeyID=https://social.belkadan.com/users/jrose/main-key msg="performing request"
gotosocial  | timestamp="07/02/2024 22:09:05.315" func=server.glob..func1.Logger.func13.1 level=INFO latency="552.854µs" userAgent="http.rb/5.1.1 (Mastodon/4.2.5; +https://eigenmagic.net/)" method=GET statusCode=200 path=/users/jrose/main-key clientIP=180.150.56.173 requestID=4c8sx1cd04000esk9k30 msg="OK: wrote 559B"
gotosocial  | timestamp="07/02/2024 22:09:08.801" func=server.glob..func1.Logger.func13.1 level=INFO latency="1.139902ms" userAgent="http.rb/5.1.1 (Mastodon/4.2.5; +https://eigenmagic.net/)" method=GET statusCode=200 path=/users/jrose clientIP=180.150.56.173 requestID=r0f9x1cd04001jctp66g msg="OK: wrote 1.00kiB"
```

so it timed out after a 10s delay. I asked her about it and she noted

> It is an Australian server, and a small one. I have noticed it takes time for images to filter through? Videos WAY more so (so I rarely post them except when it's the only way to show something.)
>
> (Like, even if I post them, it can take a bit before they appear properly in my timeline. I presume there's internal processing on the server?)

So maybe her instance is sending out posts before the attachment is available? And if Mastodon-using followers aren't having problems, maybe there's an attachment fetch retry job that GoToSocial doesn't have.

### What's your GoToSocial Version?

v0.13.1

### GoToSocial Arch

x86_64 Docker

**Comment by tsmethurst** [comment]
The default http client behavior we use is to try for 10s to fetch an attachment, and if we can't do it in that amount of time then we'll try again after a 2hr cooldown next time you look at the status in your client. We do that mainly to avoid keeping lots of outgoing HTTP connections busy.

If the 10s timeout isn't working because you federate with slower/more distant instances, you can tune it here :) https://github.com/superseriousbusiness/gotosocial/blob/6738fd5bb0193daf3e2b524105ff690e8bfc32f4/example/config.yaml#L820-L834 You might try setting it to 20s or 30s and see how that goes!

**Comment by belkadan** [comment]
Thanks! I'll try that soon [when I put in the 0.13.2 update, probably] and see if I can verify…I was thinking "the two-hour retry doesn't seem to be working", but if the *second* request *also* took a full 10 seconds then that'd be what I'd see.

**Comment by charlie2alpha** [comment]
Would that translate to GTS_HTTPCLIENT_TIMEOUT as an environment variable for use on a docker container?

**Comment by tsmethurst** [comment]
Mm, because it's nested I think to set that one you may need to mount a config.yaml file into the container and set it on the mounted file. We're due to refactor how we handle environment variable stuff, but I think currently nested variables don't work as expected, but don't quote me on that.

**Comment by charlie2alpha** [comment]
I can mount a config file, but where exactly inside the container? How can I pass it to the executable?

**Comment by tsmethurst** [comment]
You can mount it in the container wherever you like, as long as it's readable by gotosocial. I usually use `/gotosocial/config.yaml`, since that's the same dir the gts binary runs from inside the docker container. Then you can set the env var GTS_CONFIG_PATH to `/gotosocial/config.yaml`, and it'll read it from there. You can use a mix of config.yaml settings and env variables, then, with env vars taking precedence.

**Comment by daenney** [comment]
Beyond tweaking the timeout, we can't really do anything about a server not being able to transfer the asset to us within that time. As noted, we'll attempt to fetch the assets every now and then, until hopefully at some point it succeeds.

It's probably worthwhile trying to fetch the assets yourself using something like `curl` once or twice from your server and note how long the transfer takes. That should give you an idea for what to set the timeout to. Be careful not to set the timeout to high or disable it, as that can result in your server holding open connections indefinitely which will eventually cause other problems.

I'm going to close this issue for now as this isn't a bug in GoToSocial itself, but more of a consequence of how the fediverse works and what people are using to power their instances.

**Comment by belkadan** [comment]
Hm. I haven't had the chance to update the timeout yet, but a quick curl check is coming back with 3s, not anything too unreasonable. So if this is instead the server sending out references to media that isn't available yet, then maybe there's a problem with the retry? Even after two hours, or *opening in a new client,* I'm not seeing the media.

(If I explicitly use "Load from Remote Server" in my client, the image shows up, and then is correctly available in my timeline after that. But that's different from just "my client requested the status again".)

**Comment by tsmethurst** [comment]
Tbf, if the server is sending out references to media that doesn't exist yet, that's a bug on the server sending the messages :P In which case GoToSocial just serving the link so you can open the media yourself seems fine. Could you try -- when you have time -- updating the timeout, and then see if problems persist with that server? If it keeps happening then feel free to reopen the issue and we can investigate properly, but I think step 1 is just doing some tuning first.

**Comment by belkadan** [comment]
Good news: setting the timeout as `GTS_HTTP_CLIENT.TIMEOUT` worked, even if that's probably not what you want to use long-term.

Also good news: the two-hour refresh now worked, though I had to quit and reopen my primary client to actually get it to refresh.

Thanks for putting me on the right track!

**Comment by tsmethurst** [comment]
Ah that's great, thanks for updating :)
