### ISSUE TITLE
[feature] Exclusive lists

### ISSUE THREAD

**Issue by nishtahir** [superseriousbusiness/gotosocial#2616]
### Is your feature request related to a problem ?

It's difficult to manage a bunch of news feeds/posts from bot accounts in my timeline. It would be cool to have a feature to help with that.

### Describe the solution you'd like.

Hometown/Mastodon have a feature that excludes posts that appear in the list from the user's timeline
> Hometown introduces a new kind of exclusive list. It's a toggle available for each of your lists that says "any post that appears in this list should not appear in my home timeline".

Mastodon implementation [issue](https://github.com/mastodon/mastodon/issues/16556) 

### Describe alternatives you've considered.

None

### Additional context.

It should be noted that a couple of clients support the feature as implemented in Mastodon.

**Comment by tsmethurst** [comment]
We're gonna work on this after 0.14.0 is out :) It's not too tricky to implement, by the looks of it.

**Comment by NyaaaWhatsUpDoc** [comment]
^ exactly. i have already started working on this, just it's quite low priority with the v0.14.0 release coming up :)

**Comment by VyrCossont** [comment]
For future reference, the Hometown docs are here: https://github.com/hometown-fork/hometown/wiki/Exclusive-lists

**Comment by charlie2alpha** [comment]
Looks like it's broken for me on the latest snapshot version 0.16.1-SNAPSHOT+git-307d98e 
I have a test list with just one account, until a few hours ago I wasn't seeing those post in my home timeline. After I updated to the latest snapshot the list's post started appearing again in my home timeline.

**Comment by tsmethurst** [comment]
When the home timeline is first generated I think we don't filter for exclusivity. But from the moment you launch onwards, *new* entries that belong in an exclusive list shouldn't be put into the home timeline. We might need to do some tweaks still on this though.

**Comment by charlie2alpha** [comment]
Bugfix looks good so far! Thanks!

**Comment by tsmethurst** [comment]
Grand, enjoy!

**Comment by nishtahir** [comment]
This doesn't appear to work on my instance, running ` 🦥 Source - GoToSocial 0.17.0-rc4+git-77d755e 🦥 `. 
I have a few lists I created and checked exclusive option. I tested on Mastodon (Android v2.7.3 - 123) and Moshidon 2.3.0.

I'm not sure what additional debugging information to provide but I'm happy to pull whatever is needed to investigate.

**Comment by VyrCossont** [comment]
@nishtahir please open a new bug with the info in your comment here, and also, whether any of the posts showing up in your timeline are tagged with hashtags that you follow.

**Comment by nishtahir** [comment]
Oh, that might have been it. Do hashtags override the exclusivity filtering?

**Comment by VyrCossont** [comment]
@nishtahir they do, yes. The intent is that you'd be able to add accounts to an exclusive list to avoid seeing the majority of their posts in your home timeline, but that you would still see their posts that are relevant to hashtags you follow.
