### ISSUE TITLE
[feature] instance logo per url configuration

### ISSUE THREAD

**Issue by wrenix** [superseriousbusiness/gotosocial#2618]
### Is your feature request related to a problem ?

I would like to set the url in automation deployment.

### Describe the solution you'd like.

so a config-value would be nice to an external url where the image for the logo is stored. 

### Describe alternatives you've considered.

value to an file here or an cli to set it.

**Comment by tsmethurst** [comment]
This is a pretty niche feature request and not something I think we'd implement (I can't imagine anyone else using it, really). What you might consider instead is just replacing the default instance logo in the assets folder for your installation. That should prettymuch achieve what you're trying to achieve, I think.

**Comment by NyaaaWhatsUpDoc** [comment]
you could also just automate setting the instance logo and banner via an admin account over curl

**Comment by daenney** [comment]
External URL would also bring the need to adapt our CSP policy to then allow loading that in the web UI. Or we'd have to pull it down ourselves at startup, which I'd rather not do.

Given that the asset needs to be publicly accessible already for this to work, it would not be hard to retrieve the logo and put it in the right place on the filesystem instead as part of deployment automation. Many configuration management systems have support for this, like [Ansible's built-in `get_url`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#id6), [Puppet's `file` resource supports this directly](https://www.puppet.com/docs/puppet/7/types/file.html#file-attribute-source), etc. Or put the logo into the assets of your configuration management source which then deploys it, avoiding the availability requirement on a third-party system during provisioning.

Given the alternatives available, I'm going to go ahead and close this.
