### ISSUE TITLE
[bug] Federation with relay.fedi.buzz

### ISSUE THREAD

**Issue by Jasdemi** [superseriousbusiness/gotosocial#2626]
### Describe the bug with a clear and concise description of what the bug is.

relay.fedi.buzz is a service that creates followable accounts based on tags or even entire instances. Other users can follow them and they boost posts. 

I'm able to follow accounts created by relay.fedi.buzz, but no posts arrive on my instance. 

Since we have no relay support, this would be a fantastic way to bring some life to single-user instances. 

### What's your GoToSocial Version?

0.13.1

### GoToSocial Arch

Docker

### What happened?

No posts are coming through.
```
timestamp="10/02/2024 14:36:43.837" func=
server.glob..func1.Logger.func13.1 level=INFO latency="1.944829ms" userAgent="buzzrelay/0.1.0 (+https://relay.fedi.buzz)" method=POST statusCode=202 path=/users/jasdemi/inbox clientIP=2a00:8180:2c00:282:50c8:56ff:fe25:a04d pubKeyID=https://relay.fedi.buzz/instance/relay.fedi.buzz#key requestID=7g8ks4wd04000cc5cfrg msg="Accepted: wrote 45B"

timestamp="10/02/2024 14:36:43.838" func=dereferencing.(*Dereferencer).getStatusByURI level=ERROR requestID=7g8ks4wd04000cc5cfrg msg="error populating existing status: PopulateStatus: error populating status author: sql: no rows in result set"

timestamp="10/02/2024 14:36:43.838" func=workers.(*Processor).ProcessFromFediAPI level=INFO activityType=Create objectType=Announce toAccount=jasdemi requestID=7g8ks4wd04000cc5cfrg msg="processing from fedi API"

timestamp="10/02/2024 14:36:43.838" func=workers.(*Processor).EnqueueFediAPI.func1 level=ERROR requestID=7g8ks4wd04000cc5cfrg msg="error processing fedi API message: CreateAnnounce: error dereferencing announce: EnrichAnnounce: db error inserting status: constraint failed: NOT NULL constraint failed: statuses.visibility (1299)"
```
### What you expected to happen?

The followed fedibuzz account boosting posts to my instance.

### How to reproduce it?

Follow an account from relay.fedi.buzz such as @tag-fediverse@relay.fedi.buzz 

### Anything else we need to know?

With 0.13.2 following relay.fedi.buzz accounts doesn't work so I had to downgrade to 0.13.1. 

Error log with 0.13.2:
`errors="Error #01: PostInboxScheme: error calling sideEffectActor.PostInbox: ACCEPT: follow target account and requesting account were not the same\n" requestID=ahnff4md04001kqq1p4g msg="Internal Server Error: wrote 54B"`

**Comment by tsmethurst** [comment]
That looks like they're sending an Accept for a Follow but sending it not from the Actor that was being targeted by the Follow. That's exactly the kind of behavior that 013.2 is meant to counteract :P Typically we expect the Accept of the Follow to be signed by the Actor doing the Accepting.

**Comment by tsmethurst** [comment]
We definitely shouldn't be returning 500 there though, even if we don't process the activity, we should return something else in cases where we decide to ignore it because the origin doesn't look valid. But that's for later. For 0.13.2 the immediate priority was closing gaps.

**Comment by tsmethurst** [comment]
The error logs reveal a few other issues as well, like trying to set visibility to null. Probably a couple things we can fix there that are unrelated to this issue itself :P

**Comment by tsmethurst** [comment]
I've opened a FR on buzzrelay now to ask them to use the signing key of the Actor of the Activity when doing deliveries: https://github.com/astro/buzzrelay/issues/15

Also, relatedly, it's not just GoToSocial who now checks origins strictly enough for this to cause issues for buzzrelay: https://github.com/astro/buzzrelay/issues/2

**Comment by tsmethurst** [comment]
Hmmm I think I jumped to the wrong conclusion and there's something else causing the issue. I updated my comment: https://github.com/astro/buzzrelay/issues/15#issuecomment-1937878026

It does look like they're using keyId correctly afaict (but I'm not a Rust coder so I'm not 100% sure).

So there may be some other issue that's causing problems. I'll check this out again when time permits.

**Comment by Jasdemi** [comment]
Astro, the maintainer of buzzrelay fixed it. 
Can now follow relay.fedi.buzz accounts and posts arrive on my instance just fine. I no longer need real relay support as this method is much better. 😃

Thanks to @tsmethurst for taking care of it!

**Comment by tsmethurst** [comment]
Just to be clear, I didn't do this because I think fedi.buzz is a good solution to the relay issue. It's basically a hack built on top of the mastodon streaming API that uses "donated" client tokens to scrape instances, regardless of the intentions of admins of those instances, and without the knowledge of those whose posts are being scraped in this way (and yes I'm aware it only takes "Public" posts, let's not get into that whole mess). I'm not saying it's not a useful hack, now, but it's only going to be useful as long as a) there isn't better relay support that people actually opt in to using in order to distribute their posts more widely, and b) implementations can't be arsed blocking requests coming from fedi.buzz. I basically only helped in this case because it was fairly clear that fedi.buzz was doing something a bit funky with their AP implementation, and I got nerd sniped into looking through their code.

But in any case, I will close this issue now since it is more or less resolved, right?
