### ISSUE TITLE
[feature] Configuration Variable to disable domain check for OAuth

### ISSUE THREAD

**Issue by HelgeKrueger** [superseriousbusiness/gotosocial#2627]
### Is your feature request related to a problem ?

I want to do the following:
- Run gotosocial inside a docker container with hostname gotosocial (I will talk to it from other containers)
- Port forward the port 80 to outside, so I can access the web interface

Currently this fails with

> Bad Request: field response_type was not set on OAuthAuthorize form: If you arrived at this error during a login/oauth flow, please try clearing your session cookies and logging in again; if problems persist, make sure you're using the correct credentials

when the environment is configured with

```dockerfile
ENV GTS_HOST=gotosocial
ENV GTS_ACCOUNT_DOMAIN=gotosocial
```

By setting the environment variables to 

```dockerfile
ENV GTS_HOST=localhost:2974
ENV GTS_ACCOUNT_DOMAIN=localhost:2974
```

I can access the webinterface from outside, including logging in from https://semaphore.social/

### Describe the solution you'd like.

The simplest approach for me would be to be able to set a configuration variable such as

GTS_OAUTH_NO_DOMAIN_CHECK

to disable the check. This is similar behavior to setting

```yml
http-client:
  allow-ips: ["172.0.0.0/8"]
```

in order to allow activity inside the docker network.

### Describe alternatives you've considered.

I've checked if there is already such a variable in the documentation, and didn't find any.

**Comment by tsmethurst** [comment]
This is confusing. Can you explain what you're trying to do? What domain check are you referring to?

**Comment by HelgeKrueger** [comment]
Thanks for getting me  and sorry for taking a few days to reply.

I'm trying to run gotosocial in a docker container, so that I can run automated tests against it. I've attached the Dockerfile with the dependencies:

[example.zip](https://github.com/superseriousbusiness/gotosocial/files/14294043/example.zip)

The problem now is that:

- If I want the docker container accessible from inside a docker network, I need the environment variable `GTS_HOST` to be "gotosocial", i.e. the network alias of the container.
- If I want the docker container to be accessible through port forwarding, I need `GTS_HOST` to be `localhost:port`.

Does this explain my problem?

**Comment by tsmethurst** [comment]
Mmmm I think so. For cases like this, would it not be sufficient to add an entry in your /etc/hosts file, or to mess around with docker dns for intra-container domain resolution? It feels like there's probably a simple way of making this work without introducing changes in GoToSocial for this very specific use case :P

**Comment by daenney** [comment]
There should be no need to change `GTS_HOST` for port forwarding, you can forward any port on the host to whichever port in the container GtS is bound to.

The problem then indeed arises, with `GTS_HOST` being called `gotosocial`, there is no way to resolve that name _outside_ of containers on the same Docker network.

For `curl`, this can be solved quite handily by using its `--resolve` argument, which lets you skip the DNS lookup and point to an IP directly will still using the name. This should be enough for things to work:

```
curl https://gotosocial --resolve 'gotosocial:443:192.168.72.1'
```

The myriad of tricks you can do with resolve are explained quite nicely over here: https://everything.curl.dev/usingcurl/connections/name

For most HTTP clients, I suspect you can do the same. For example, doing a http GET to `http://192.168.72.1` but setting an explicit `Host: gotosocial`

**Comment by daenney** [comment]
I'm going to go ahead and close this, since there's been no follow-ups for a while. If there's still an issue with local testing feel free to reopen it.
