### ISSUE TITLE
[bug] Search for account URL doesn't always work when redirected

### ISSUE THREAD

**Issue by tux93** [superseriousbusiness/gotosocial#2643]
### Describe the bug with a clear and concise description of what the bug is.

Pixelfed seems to generate three different URLs for a post:

1. The URL a logged in user sees when opening a post from the Local feed (i.e. https://pixelfed.de/i/web/post/${ID})
2. When clicking the timestamp from the above point, the Post opens in a different interface and the URL becomes https://pixelfed.de/p/${USER}/${ID}?fs=1
3. The canonical URL for a Post https://pixelfed.de/p/${USER}/${ID}

Note especially the `?fs=1` parameter being the only difference between 2 and 3.

### What's your GoToSocial Version?

0.13.3

### GoToSocial Arch

arm64 Binary

### What happened?

When pasting URLs 1. and 2. into the Search on a GTS account, the post cannot be found and errors are logged:
```
# URL type 1 fails
Feb 16 10:44:00 hal9000 gotosocial[32056]: func=search.(*Processor).Get level=DEBUG maxID="" minID="" limit='5' offset='0' query=https://pixelfed.de/i/web/post/663854260074423729 queryType="" resolve=true following=false requestID=54mmvccd04001bqdt2vg msg="beginning search"
Feb 16 10:44:00 hal9000 gotosocial[32056]: func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://pixelfed.de/i/web/post/663854260074423729 requestID=54mmvccd04001bqdt2vg pubKeyID=https://boosts.squirrel.pictures/users/fl4nn/main-key msg="performing request"
Feb 16 10:44:00 hal9000 gotosocial[32056]: func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://pixelfed.de/i/web/post/663854260074423729 requestID=54mmvccd04001bqdt2vg pubKeyID=https://boosts.squirrel.pictures/users/fl4nn/main-key msg="performing request"
Feb 16 10:44:00 hal9000 gotosocial[32056]: func=server.glob..func1.Logger.func13.1 level=ERROR latency=141.587573ms userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0" method=GET statusCode=500 path=/api/v2/search clientIP=192.168.1.222 errors="Error #01: Get: error searching by URI: byURI: error looking up https://pixelfed.de/i/web/post/663854260074423729 as status: enrichStatus: dereferenced status uri https://pixelfed.de/p/defernite/663854260074423729 does not match https://pixelfed.de/i/web/post/663854260074423729\n" requestID=54mmvccd04001bqdt2vg msg="Internal Server Error: wrote 54B"


# URL type 2 fails
Feb 16 10:45:10 hal9000 gotosocial[32056]: func=search.(*Processor).Get level=DEBUG maxID="" minID="" limit='5' offset='0' query=https://pixelfed.de/p/defernite/663855289106142950?fs=1 queryType="" resolve=true following=false requestID=a0wmxccd040000ry7700 msg="beginning search"
Feb 16 10:45:10 hal9000 gotosocial[32056]: func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://pixelfed.de/p/defernite/663855289106142950?fs=1 requestID=a0wmxccd040000ry7700 pubKeyID=https://boosts.squirrel.pictures/users/fl4nn/main-key msg="performing request"
Feb 16 10:45:10 hal9000 gotosocial[32056]: func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://pixelfed.de/p/defernite/663855289106142950?fs=1 requestID=a0wmxccd040000ry7700 pubKeyID=https://boosts.squirrel.pictures/users/fl4nn/main-key msg="performing request"
Feb 16 10:45:10 hal9000 gotosocial[32056]: func=server.glob..func1.Logger.func13.1 level=ERROR latency=97.662604ms userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0" method=GET statusCode=500 path=/api/v2/search clientIP=192.168.1.222 errors="Error #01: Get: error searching by URI: byURI: error looking up https://pixelfed.de/p/defernite/663855289106142950?fs=1 as status: enrichStatus: dereferenced status uri https://pixelfed.de/p/defernite/663855289106142950 does not match https://pixelfed.de/p/defernite/663855289106142950?fs=1\n" requestID=a0wmxccd040000ry7700 msg="Internal Server Error: wrote 54B"


# URL type 3 (canonical) succeeds
Feb 16 10:45:55 hal9000 gotosocial[32056]: func=search.(*Processor).Get level=DEBUG maxID="" minID="" limit='5' offset='0' query=https://pixelfed.de/p/defernite/663855289106142950 queryType="" resolve=true following=false requestID=vfn4xccd04001gb43s80 msg="beginning search"
Feb 16 10:45:55 hal9000 gotosocial[32056]: func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://pixelfed.de/p/defernite/663855289106142950 requestID=vfn4xccd04001gb43s80 pubKeyID=https://boosts.squirrel.pictures/users/fl4nn/main-key msg="performing request"
Feb 16 10:45:55 hal9000 gotosocial[32056]: func=server.glob..func1.Logger.func13.1 level=INFO latency=44.18858ms userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0" method=GET statusCode=200 path=/api/v2/search clientIP=192.168.1.222 requestID=vfn4xccd04001gb43s80 msg="OK: wrote 1.33kiB"
```
Only the canonical URL is accepted to look up the post.

### What you expected to happen?

The post can be looked up by any of the URLs.

### How to reproduce it?

1. Be logged in on a Pixelfed instance, open any post from the Local feed -> the URL bar shows a URL type 1
2. Click on the Timestamp of the Post, it will show the Post in a different interface, possibly the one non-logged in users would get, the URL bar shows a URL type 2
3. Right clicking the Timestamp and selecting "Copy link" will give you the canonical URL (Type 3) at any point

**Comment by tsmethurst** [comment]
Hmm. Well, when GtS looks up an object, it checks that at least one of the `id` and `url` properties of the object (see [here](https://www.w3.org/TR/activitystreams-core/#object)) match the url that was entered to perform the search. It looks in this case like pixelfed sets the following values on their Note objects:

```json
"id": "https://pixelfed.de/p/defernite/663855289106142950",
"url": "https://pixelfed.de/p/defernite/663855289106142950"
```

If there's a different url format that they use for web views of posts, it ought to be set in the `url` property, but i'm not sure a client-app internal url counts there since it's not accessible to the outside world. And when I open `https://pixelfed.de/p/defernite/663855289106142950` in my browser, I do see a web representation of the post, which is what one would expect at the `url` property. So I don't think pixelfed is doing anything wrong here.

I think the only thing GtS is doing wrong is returning a 500 error when a lookup stops in this manner; we should return something else to the user instead, since it's not actually an internal server error.

**Comment by daenney** [comment]
I'm curious about something; when retrieving that `i/web` URL, they return a redirect with a location pointing towards the object:

```
$ curl -H "Accept: application/activity+json" -vv https://pixelfed.de/i/web/post/663855289106142950
[..]
< location: https://pixelfed.de/p/defernite/663855289106142950
```

That `location` then matches the `id` of the object, so it feels like this should work?

**Comment by tsmethurst** [comment]
I was just about to say something similar about the redirect. You could probably say that if the lookup results in a redirect (on the same host), we could check that the last redirect value used matches the `id` or `url` property of the Object, instead of just the initial search query value.

**Comment by daenney** [comment]
I don't think we need to know the redirect chain. We have the original URL as it came in to the search endpoint. We can query for that and then check the URL using the `http.Response.Request.URL` which will be the actual URL from where the current response body was retrieved. In the case of the redirect chain, it's the last one.

If the hosts match, then we're good and whether it was through a redirect or not doesn't matter at that point (I think).

**Comment by tsmethurst** [comment]
Changed the title to make this a more general issue for tracking this, since someone reported a similar thing in https://github.com/superseriousbusiness/gotosocial/issues/2648

**Comment by tsmethurst** [comment]
Sorta related: https://github.com/superseriousbusiness/gotosocial/issues/2327

**Comment by NyaaaWhatsUpDoc** [comment]
Work on this is currently happening here: https://github.com/superseriousbusiness/gotosocial/compare/main...NyaaaWhatsUpDoc:2643-bug-search-for-account-url-doesnt-always-work-when-redirected?expand=1

currently slowed by needing to fix up the gomock generated tests in the activity/pub package :p

**Comment by mirabilos** [comment]
I spotted another occurrence of this despite the fix.

In https://semaphore.social/search searching for `https://infosec.place/users/AlXRUAEjZWsAzH4Zm4` will get me nothing. Following the redirect to `https://bird.makeup/users/evilsocket` and searching for that gives me the account.

0.16.0-rc3+git-db80361 🦥

**Comment by NyaaaWhatsUpDoc** [comment]
oh that's an interesting one, i'll take a look.

**Comment by tsmethurst** [comment]
@mirabilos I had a quick look and both of the following calls return response 404:

- `curl -H 'accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' https://infosec.place/users/AlXRUAEjZWsAzH4Zm4`
- `curl -H 'accept: application/activity+json' https://infosec.place/users/AlXRUAEjZWsAzH4Zm4`

So I think in this case they just haven't set up redirects properly, but I'm not 100% sure.

**Comment by NyaaaWhatsUpDoc** [comment]
that's how the gotosocial logs are seeing it too. they definitely haven't setup redirectlys properly for ActivityPub. it redirects for standard web requests, but just returns as not-found if it's an ActivityPub protocol (well, specified by the Accept header) request

**Comment by mirabilos** [comment]
Thanks for having a look! This is not something I would have expected or guessed.

Reported as https://akkoma.dev/AkkomaGang/akkoma/issues/835
