### ISSUE TITLE
[bug] Import/Export UI flow can cause a 404

### ISSUE THREAD

**Issue by Pectojin** [superseriousbusiness/gotosocial#2644]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

This is a minor issue where a missing frontend check will cause the Import/Export UI to return a 404.
![image](https://github.com/superseriousbusiness/gotosocial/assets/1561484/7cb92187-d6de-4e00-a4b8-9ad4773b59cb)
![image](https://github.com/superseriousbusiness/gotosocial/assets/1561484/f7f6208d-5e96-4e73-a63a-09984d6416a0)

### What's your GoToSocial Version?

0.13.3

### Browser version

Chromium 112, Firefox 122

### What happened?

I accidentally brought the Import/Export UI in a state where the "Import" button returns a 404 error with no clear explanation of what I did wrong.

### What you expected to happen?

I expected to import a list of domain blocks

### How to reproduce it?

When you open the Import/Export page neither "domain blocks" nor "domain allows" is selected, but you can still click "import" which brings you to the next page.

Here is the first clue of what is wrong as it says "Confirm import of domain s", which I never noticed until filing this issue. On this page clicking "Import" will cause a "404: Not Found" as pictured.

Inspecting the network traffic reveals the problem. When selecting neither option on the first page a request is made for `/api/v1/admin/domain_s?import=true`, but if you select e.g. "domain blocks" you correctly request `/api/v1/admin/domain_blocks?import=true`.

i.e. the code interpolates an empty string because I forgot to select an option.

### Anything else we need to know?

I have a slight preference for the solution to this being to have the first page select "domain blocks" by default, but a check in the frontend prompting the user to select an option is equally valid.

I don't think the second page needs any changes to address this.

**Comment by tsmethurst** [comment]
Ah thanks, I actually noticed that during development and thought "I'll fix this later". Hello, consequences of my actions.

**Comment by tsmethurst** [comment]
I fixed this recently, I can't remember in what PR but it is fixed on main at least :')
