### ISSUE TITLE
[bug] Searching with URL redirects does not function

### ISSUE THREAD

**Issue by 9p4** [superseriousbusiness/gotosocial#2648]
### Describe the bug with a clear and concise description of what the bug is.

When searching for a post `https://labyrinth.zone/notice/AexYaAWPVNKv6rZscy`, it does not appear. In the logs, we see:

`timestamp="2024-02-17T02:55:16.147Z" func=server.glob..func1.Logger.func13.1 level=ERROR latency=188.024882ms userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0" method=GET statusCode=500 path=/api/v2/search clientIP=173.230.7.46 errors="Error #01: Get: error searching by URI: byURI: error looking up https://labyrinth.zone/notice/AexYaAWPVNKv6rZscy as status: enrichStatus: dereferenced status uri https://labyrinth.zone/objects/cdcf8ccf-5382-4678-9dee-f65efd22257e does not match https://labyrinth.zone/notice/AexYaAWPVNKv6rZscy\n" requestID=yx6zvd4d040016rdghgg msg="Internal Server Error: wrote 54B"`

Searching for the dereferenced status URL brings up the correct post (`https://labyrinth.zone/objects/cdcf8ccf-5382-4678-9dee-f65efd22257e`).

### What's your GoToSocial Version?

https://github.com/superseriousbusiness/gotosocial/pull/2642

### GoToSocial Arch

Podman amd64

### How to reproduce it?

Search for `https://labyrinth.zone/notice/AexYaAWPVNKv6rZscy`

**Comment by tsmethurst** [comment]
Heya, this is basically the issue as https://github.com/superseriousbusiness/gotosocial/issues/2643 so I'll close this one and amend that one to make it more general.
