### ISSUE TITLE
[bug] `POST /api/v1/admin/custom_emojis` does not validate shortcode content, only length

### ISSUE THREAD

**Issue by gaykitty** [superseriousbusiness/gotosocial#2649]
### Describe the bug with a clear and concise description of what the bug is.

Shortcodes are supposed to "be between 2 and 30 characters, letters, numbers, and underscores only". However, the API endpoint only checks that they are between 2 and 30 characters, and not what characters are used. I'm not familiar with the GtS codebase but I suspect this regex is the culprit.

https://github.com/superseriousbusiness/gotosocial/blob/8b8211986e222109880a2bb03aaee99958ea67fb/internal/regexes/regexes.go#L48

### What's your GoToSocial Version?

v0.13.3

### GoToSocial Arch

amd64

**Comment by tsmethurst** [comment]
Thanks! I'll make a fix :)

**Comment by tsmethurst** [comment]
Just for clarity the regex you pointed out does do what it ought to do. `\w` is shorthand for `[a-zA-Z0-9_]`. See https://regex101.com/r/wFuJZ6/1.

So the issue likely lies somewhere else, I'll poke at it a bit.
