### ISSUE TITLE
[bug] notifications from DMs between local users shown as from yourself

### ISSUE THREAD

**Issue by benjaminbhollon** [superseriousbusiness/gotosocial#2653]
### Describe the bug with a clear and concise description of what the bug is.

When I receive a DM from another user on my own instance, the notification shows as being from myself (but the post itself has the correct author).

Ends up being like this:

```
Amin the Admin 🇺🇸 🇲🇾 🇮🇳 🇦🇫  (amin) mentioned you 

(direct) Rogue 
roguefoam

[[message text]]
```

I've been seeing this since the first v0.13 update, I think, I just haven't gotten around to reporting it until now (I also was doing some testing to see if it was showing up for anyone else and to what extent—it doesn't happen for messages between remote users, but does for local users, it seems).

### What's your GoToSocial Version?

v0.13.3

### GoToSocial Arch

amd64 Binary

### What happened?

On receiving a DM from a local user, the notification shows as being from myself.

### What you expected to happen?

I expect the notification to be shown as from the user who sent the message.

### How to reproduce it?

1. Send a direct message from one local user to another
2. Notification metadata seems to show up wrong (this is more or less visible depending on your client; I see it most often in tut and IceCubes, but it's not noticeable in, say, Semaphore because it doesn't show the "__ mentioned you" header

**Comment by tsmethurst** [comment]
Oh silly, thanks, will take a look

**Comment by tsmethurst** [comment]
Ah, managed to replicate it, I'll investigate :)
