### ISSUE TITLE
[bug] GoToSocial with S3 backend on the same webserver using SNI and different certificates over HTTP/2 causes media to not load for some clients due to HTTP 421

### ISSUE THREAD

**Issue by 9p4** [superseriousbusiness/gotosocial#2654]
### Describe the bug with a clear and concise description of what the bug is.

Oh boy this one is weird.

My GoToSocial setup looks something like this: GtS is running behind an Apache reverse proxy, and so is Minio for S3 storage. Minio has the domain `o.example.com`, and the certificate for `o.example.com, *.o.example.com`. GtS has the domain `social.example.com` and the certificate for `example.com, *.example.com`. Both endpoints are HTTP/2 enabled. GtS is not proxying S3 media.

When using *some* clients (_i.e._ those on iOS/macOS, incl. [tooot](https://github.com/tooot-app/app) and Metatext), media does not load. The Apache logs always have something like this:

```
o.example.com:443 000.000.000 - - [17/Feb/2024:16:39:42 -0500] "GET /gotosocial/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/emoji/original/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.png?X-Amz-Algorithm=... HTTP/2.0" 421 587 "-" "tooot/4.10.3 (iPhone; iOS 17.3.1; Scale/3.00)"
```

Enabling proxying the S3 media causes the error to disappear. Weirder still, disabling HTTP/2 also fixes the error.

Here's what I think is happening:

1. GtS redirects the client via an HTTP 302 redirect
2. The client uses HTTP/2's connection reuse functionality because it matches the prerequisites
3. The connection reuse is messed up on iOS?
4. ??? SNI error?
5. Media does not load

It's not a CSP issue because it works just fine on other clients that are not iOS/macOS. It's not a tooot issue because it is also seen on Metatext and Safari. It is definitely related to a weird interference with SSL/SNI/HTTP2/Redirecting because once I put an interception proxy in place on my phone to see the network requests, the issue went away (due to the proxy not doing HTTP/2), and changing the certificate on my S3 endpoint to match the same one as my main endpoint (`o.example.com` now has the certificate for `example.com, *.example.com`) also fixed the issue.

This may be a bug with Webkit/Apple's networking stack when handling H/2 redirects.

Potential fixes:

1. Patch GtS to not redirect media (and instead just returns the S3 endpoint URL)
2. Disable HTTP/2
3. Proxy S3 media in GtS
4. Move S3 and GtS services to different hosts so no SNI issues arise
5. Use the same certificates for GtS and S3 (may cause issues with domain-addressed S3 endpoints)
6. Use different domains for S3 and GtS (so no connection reuse happens, untested)
7. Yell at Tim Cook

### What's your GoToSocial Version?

https://github.com/superseriousbusiness/gotosocial/pull/2642

### GoToSocial Arch

Podman amd64

**Comment by 99kaits** [comment]
This seems to be iOS specific because I had no issues viewing media on the same instance on Android.

**Comment by tsmethurst** [comment]
Wow! Thanks for filing, but I'm not sure what to do with this one, tbh. Option number one is something we'll probably be sort of implementing at some point because a few people have requested it, but yeah, maybe just proxy instead for now then? Sounds more like an apple bug than a GtS bug but it's good to have it written down here in case someone runs into the same problem.

**Comment by 9p4** [comment]
I ended up just moving away from bucket-style addressing of my Minio instance.

**Comment by tsmethurst** [comment]
Okay :D Well, I'm going to close this as "wontfix" because I don't believe it's really a GtS problem *but* thank you for opening it and writing it up, because now it's searchable in our issues :)

**Comment by 9p4** [comment]
I think a separate issue is warranted for the "return the S3 URL directly instead of a redirect"?

**Comment by daenney** [comment]
That already exists, it's #2574
