### ISSUE TITLE
[feature/admin] Allow enabling very basic anti-spam heuristics to drop messages coming in via the fedi API

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2678]
It would be good if there was a toggle somewhere on the settings panel (or in the config.yaml) to enable an extremely basic spam filter that would drop messages from remotes if several of the following conditions are met:

1. The message is from someone that nobody on the instance follows.
2. The message is from a brand-new account that the instance hasn't seen before.
3. The message mentions more than one person.
4. The message contains a link and/or the message contains an image.

Messages meeting those conditions could be dropped. This might result in legit messages getting caught in the crossfire, so this setting should probably be off by default, or maybe admins could customize how many conditions should be met before the message is dropped.

**Comment by NyaaaWhatsUpDoc** [comment]
it would be useful if we had a frontend for the built-in header-filtering we currently have to go alongside this

**Comment by benjaminbhollon** [comment]
This would be really handy, if only to turn on temporarily during a spam wave.
