### ISSUE TITLE
add ability to log to syslog

### ISSUE THREAD

**Issue by igalic** [superseriousbusiness/gotosocial#268]
currently, gotosocial logs to stdout/stderr.

It would be nice if we could add `--syslog` flag, which causes it to log to syslog.
That way, admins don't need to pipe logs into a specific location and ensure they are rotated, which might need a restart! they an just have syslog handle all of that!

**Comment by tsmethurst** [comment]
We can do this with this logrus hook relatively easily: https://github.com/Sirupsen/logrus/blob/master/hooks/syslog/syslog.go
