### ISSUE TITLE
[bug] Federation with Activity-Relay

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#2681]
### Describe the bug with a clear and concise description of what the bug is.

Activity-Relay is an ActivityPub relay server. Users can subscribe the relay by following `https://<your-relay-server-address>/actor` (`@relay@relay-server.address`). https://github.com/yukimochi/Activity-Relay

While trying to subscribing, Gotosocial managed to fetch the actor account @relay@relay.domain, but the follow requests seem to never get approved and are left in a pending state.

The logs from my instance indicate that the follow request cannot be delivered to the Activity Relay's inbox:

```
gotosocial  | timestamp="23/02/2024 13:21:47.468" func=workers.(*clientAPI).CreateFollowReq level=ERROR requestID=tg723nmd04000b2nb1rg msg="error federating follow request: Follow: error sending activity *typefollow.ActivityStreamsFollow via outbox https://gotosocial.domain/users/gts_user/outbox: func1: error delivering to https://activityrelay.domain/inbox: deliver: POST request to https://activityrelay.domain/inbox failed: status=\"400 Bad Request\" body=\"<empty>\""
```

I've opened an issue in Activity-Relay's side, see yukimochi/Activity-Relay/issues/93

### What's your GoToSocial Version?

v0.13.1-SNAPSHOT+git-5aca09b (it's indeed 0.13.3+)

### GoToSocial Arch

arm64 Docker

### What happened?

The follow requests can't be delivered to Activity-Relay's side.

### What you expected to happen?

Successfully follow the relay account.

### How to reproduce it?

1. Find a Activity-Relay instance. e.g. https://relay.infosec.exchange/
2. Attempt to follow the actor account: https://relay.infosec.exchange/actor `@relay@relay.infosec.exchange`
3. See 400 error

**Comment by VyrCossont** [comment]
GtS doesn't support relays yet: see #1123.

**Comment by CDN18** [comment]
Ahh, I overlooked this previously. I had initially thought the process of following a relay actor is identical to following an account. I'll close the issue on both sides for now.

**Comment by VyrCossont** [comment]
Surprisingly, following a relay as an individual account does work in Mastodon. But Fedi servers that support relays normally have an admin panel or command line tool to join the entire server to the relay.
