### ISSUE TITLE
[feature] Amazonbot to robots.txt

### ISSUE THREAD

**Issue by gaykitty** [superseriousbusiness/gotosocial#2686]
### Is your feature request related to a problem ?

Add [Amazonbot](https://developer.amazon.com/amazonbot) to robots.txt

### Describe the solution you'd like.

Add [Amazonbot](https://developer.amazon.com/amazonbot) to robots.txt

### Describe alternatives you've considered.

None?

**Comment by NyaaaWhatsUpDoc** [comment]
get fucked Amazon
