### ISSUE TITLE
add ability to daemonize

### ISSUE THREAD

**Issue by igalic** [superseriousbusiness/gotosocial#269]
currently, gotosocial remains in the foreground

some inits don't handle that well, and assume that software hasn't finished starting.

it would be useful to have a `--daemonize` or similar flag, for such purposes.

note that this can probably be emulated for now:

```sh
gotosocial >/dev/null 2>&1 &
disown
```

note that it's important to give up `stdout` and `stderr`; we can either pipe them to a file, or `/dev/null` or we can add #268

**Comment by tsmethurst** [comment]
I don't see a good standard Go way of doing this (just some gross hacks). I think what we'll probably do here is suggest people run it with `nohup [...] &` or however they want to do it, and/or provide a systemd service file example for people to use or adapt.

**Comment by tsmethurst** [comment]
We should also make sure we respond properly to `SIGHUP` but i'll make a separate issue for that

**Comment by igalic** [comment]
FreeBSD has a utility for doing much of this already: [`daemon(8)`](https://man.freebsd.org/daemon(8))
However, then you're in Pidfile handling hell, and I'd rather not go there

**Comment by NyaaaWhatsUpDoc** [comment]
doing it with an external utility that's tried, tested and designed for this is better than overcomplicating the gotosocial binary imo

**Comment by igalic** [comment]
I made it work without a Pidfile: https://codeberg.org/meena/freebsd-ports/src/branch/add/gotosocial/net-im/gotosocial/files/gotosocial.in

This is without supervision, because I dunno, i assume it's stable enough for now to not need babysitting??

**Comment by tsmethurst** [comment]
@zoe-bat added an example systemd config file in this PR: https://github.com/superseriousbusiness/gotosocial/pull/341

@igalic is there anything else you think we should include, or should i close this issue?

**Comment by igalic** [comment]
👍🏻
