### ISSUE TITLE
Be a bit more forgiving with accept headers?

### ISSUE THREAD

**Issue by edent** [superseriousbusiness/gotosocial#2720]
I'm trying to request a WebFinger. I got this error:

> Not Acceptable: no format can be offered for requested Accept header(s) [application/activity+json]; this endpoint offers [application/jrd+json application/json] 

Which appears to come from:

https://github.com/superseriousbusiness/gotosocial/blob/ea0efb809475bc84f24ad4959d86259222d2ace2/internal/api/util/negotiate.go#L130

If I make the request without *any* Accept header, it completes.  GoToSocial is the only server I've found which is so strict. Would you consider loosening the requirements for machine-readable endpoints like webfinger?

**Comment by tsmethurst** [comment]
Hmm, I'm not sure. We're not doing anything wrong here afaik. Is there a reason to relax it?

**Comment by edent** [comment]
Only that the code I'm using sends `application/activity+json` for all its other requests and I'm too lazy to change :-)

I can't see your logs, but I wonder how many other people were mistaken (like me) that all the endpoints would speak activity+json?

**Comment by tsmethurst** [comment]
> Only that the code I'm using sends application/activity+json for all its other requests and I'm too lazy to change :-)

I'll close this then. I don't see any reason to serve application/json or some other type when activity+json has been explicitly requested.
