### ISSUE TITLE
[bug] DB queries on SQLite-backed instance return error `interrupted (9)` for every query (modernc.org/sqlite > v1.29.2)

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2728]
Since updating our sqlite version in https://github.com/superseriousbusiness/gotosocial/pull/2718, occasionally an instance will become unresponsive since all SQLite DB queries return `interrupted (9)`. A restart fixes this (temporarily at least).

Not yet sure what's causing the issue, we're investigating.

**Comment by tsmethurst** [comment]
Workaround in https://github.com/superseriousbusiness/gotosocial/pull/2731

**Comment by tsmethurst** [comment]
Steps to recreate the issue:

- Check out v0.14.0 of GtS.
- `DEBUG=1 ./scripts/build.sh`
- `DEBUG=1 GTS_DB_ADDRESS=./sqlite.db ./gotosocial testrig start`
- Open https://localhost:8080/@admin in the browser.
- Hold down ctrl+f5 in the browser for ~10 seconds to force spammy refresh of GtS.
- Watch the testrig logs.

**Comment by NyaaaWhatsUpDoc** [comment]
a bug-fix upstream has now been opened: https://gitlab.com/cznic/sqlite/-/merge_requests/67
