### ISSUE TITLE
[bug] gotosocial user doesn't have sufficient privileges to run gotosocial.service

### ISSUE THREAD

**Issue by JacksonBates** [superseriousbusiness/gotosocial#2734]
### Describe the bug with a clear and concise description of what the bug is.

Running the `sudo systemctl enable --now gotosocial.service` command keeps consistently failing.

`letsEncryptTLS.func2 level=FATAL msg="letsencrypt: listen: listen tcp 0.0.0.0:80: bind: permission denied"`

### What's your GoToSocial Version?

0.14.0+git-7bc536d

### GoToSocial Arch

Binary

### What happened?

Following the installation guide, I reached the point where I create a gotosocial user and group to run the gotosocial.service.

Running the `sudo systemctl enable --now gotosocial.service` command kept consistently failing.

I was able to catch the failure in the act with multiple restarts, and found this log line `letsEncryptTLS.func2 level=FATAL msg="letsencrypt: listen: listen tcp 0.0.0.0:80: bind: permission denied".

### What you expected to happen?

`systemctl status gotosocial.service` should report that the service is healthy.

### How to reproduce it?

Attempt to run the gotosocial.service as documented, on a bare metal installation, no proxy.

### Anything else we need to know?

Some digging revealed that the `gotosocial` user doesn't have permission to bind to ports below 1024.

I have modified the service file to run as `root` instead, and this works perfectly, but presumably you went to the trouble to create the gotosocial user for a reason!

Did I miss something in the set up process? Is this something that affects only the letsencrypt service usage, when no proxy is used? Is there a better approach than just letting root run this?

**Comment by tsmethurst** [comment]
Hiya, you need to uncomment this line: https://github.com/superseriousbusiness/gotosocial/blob/016923b4dc0575c92eb0507a5c527f3183ec52f1/example/gotosocial.service#L48

We should add a note about that to the docs.

**Comment by tsmethurst** [comment]
I've updated the docs now so I'll close this issue. Please feel free to reopen if uncommenting that line in your service file doesn't resolve the problem :)

**Comment by JacksonBates** [comment]
Oh excellent, thanks!
