### ISSUE TITLE
[bug/sqlite] Instance can get in a state where every db query returns `database is locked (517)`

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2774]
Difficult to reproduce this one. I noticed last week that my instance (running on https://github.com/superseriousbusiness/gotosocial/commit/0362d49da0d09784f9b974718839f5e69df3bae1 or so) had started responding to most requests with 500 errors. On checking I see lots of stuff like the following:

```
timestamp="17/03/2024 13:54:07.347" func=server.glob..func1.Logger.func13.1 level=ERROR latency="5.039544ms" userAgent="xxx" method=GET statusCode=500 path=/api/v1/accounts/verify_credentials clientIP=xxx.xxx.xxx.xxx errors="Error #01: error converting account: AccountToAPIAccountPublic: error counting statuses: database is locked (517)\n" requestID=xvz7jk4e04001z3j88p0 msg="Internal Server Error: wrote 54B"
```

This state of affairs persisted for about 30 minutes until I restarted the instance, which caused it to start behaving normally again after the restart.

517 corresponds to [sqlite busy](https://www.sqlite.org/rescode.html#busy_snapshot), which we should be handling already, so I'm really not sure what was happening there. One to investigate.

**Comment by NyaaaWhatsUpDoc** [comment]
have you recently started using filtering ? i'm wondering if the new upsert type perhaps is not going the usual retryBusy route 🤔

**Comment by NyaaaWhatsUpDoc** [comment]
worst case, at this point I'm getting fairly comfortable with the SQLite driver internals for easier debugging :p

**Comment by tsmethurst** [comment]
> have you recently started using filtering

I didn't make any filters yet no, so I don't think that's the issue. Could it be another regression in sqlite from https://github.com/superseriousbusiness/gotosocial/commit/c27049ad15c3f4dad068bc528cab34c06653cd32 ?

**Comment by NyaaaWhatsUpDoc** [comment]
it's hard to say off the top of my head. might take a look into it a bit later, for now i need to do some IRL cleaning (have people over for dinner later!) and then get to your PR :)

**Comment by NyaaaWhatsUpDoc** [comment]
leaving this issue open after the above bugfix, as i'm still not 100% sure why the instance got *stuck* in this state

**Comment by marmulak** [comment]
Hello, running 0.15.0-rc1+git-65b5366 (binary release) on freebsd-amd64. My instance became unresponsive after this:

`Apr  4 16:10:14 hostname gotosocial[68822]: timestamp="04/04/2024 16:10:14.880" func=server.glob..func1.Logger.func13.1 level=ERROR stacktrace="util.NotFoundHandler()\n\t/drone/src/internal/api/util/errorhandling.go:50\nutil.ErrorHandler()\n\t/drone/src/internal/api/util/errorhandling.go:149\nserver.glob..func1.2()\n\t/drone/src/cmd/gotosocial/action/server/server.go:286\ngin.(*Context).Next()\n\t/drone/src/vendor/github.com/gin-gonic/gin/context.go:174\nserver.glob..func1.Logger.func13()\n\t/drone/src/internal/middleware/logger.go:134\n()\n\t/drone/src/vendor/github.com/gin-gonic/gin/context.go:174\ngin.serveError()\n\t/drone/src/vendor/github.com/gin-gonic/gin/gin.go:656\ngin.(*Engine).handleHTTPRequest()\n\t/drone/src/vendor/github.com/gin-gonic/gin/gin.go:649\ngin.(*Engine).ServeHTTP()\n\t/drone/src/vendor/github.com/gin-gonic/gin/gin.go:576\n" requestID=g00wva4e04001d60k6f0 msg="recovered panic: db error fetching instance: context canceled"`

This happened before with an SQLite related issue in 0.14.0 if I remember correctly. GoToSocial could not be terminated after that except by force. The instance resumes working after reloading GtS, but hard to say when the error may occur again. It was thought to have been fixed last time when downgrading one of the included libraries I think.

**Comment by tsmethurst** [comment]
Hiya, I'm gonna make a new issue for this ^^ since it's a bit different from the issue at the top of the thread.

**Comment by tsmethurst** [comment]
Closed by https://github.com/superseriousbusiness/gotosocial/pull/2811 (for now)

**Comment by blakesmith** [comment]
We've been seeing `database is locked` errors happening sporadically while running the test suite during packaging, but not sure if that's related. See: https://github.com/NixOS/nixpkgs/pull/303321.

**Comment by tsmethurst** [comment]
Yeah I've seen that in the test suite too. Something to do with the in-memory implementation specifically I think.

**Comment by blakesmith** [comment]
@tsmethurst That's really useful information! I only know a little bit about sqlite internals, but since sqlite in-memory doesn't support WAL mode, I wonder if there's some exclusive locking happening in the test suite that normally wouldn't happen in a live instance when `PRAGMA journal_mode=WAL` can more gracefully handle multiple concurrent readers? Now I'm getting curious here. :grin:

**Comment by tsmethurst** [comment]
Probably something along those lines yeah!
