### ISSUE TITLE
[bug] Custom emoji missing on Android client Megalodon

### ISSUE THREAD

**Issue by kouya** [superseriousbusiness/gotosocial#2794]
### Describe the bug with a clear and concise description of what the bug is.

The custom emojis I added to my instances display empty in Megalodon. The app brings up the selector but for some reason they don't show at all.

I could swear this once worked but can't confirm it 100%. I vaguely remember them displaying on 0.11 releases and then came up empty with 0.12 one day. There aren't really any special emojis on it, only blobfoxes with flat names. I don't recall changing anything on the emoji list that made them broken.

The software is afaik a fork of the official masto client for Android, https://sk22.github.io/megalodon/ but don't know if it happens with the official as well.

If you need any further information, let me know. It's hard to pinpoint where an issue could be here or how I can help more. Reproducing is simple though (see description below), at least for me.

GTS works fine with other clients I use, mainly my own Phanpy fork. And Megalodon also show them correctly when connecting to Mastodon.

### What's your GoToSocial Version?

0.14.2

### GoToSocial Arch

amd64 binary

### How to reproduce it?

Install https://sk22.github.io/megalodon/
Log in on an instance where you added custom emoji
Create new post and open emoji selector -> they are empty

**Comment by tsmethurst** [comment]
I wonder if maybe it's because GtS requires authorization on the emojis endpoint, and afaik Mastodon doesn't... We require auth there because you can learn a lot about an instance by just looking at what emojis they have installed, which is a privacy issue. Not 100% sure that's what's causing it though. Perhaps it's worth you opening an issue on Megalodon as well and linking back to this one?

**Comment by kouya** [comment]
Hm, maybe I'll see what the official client does from which Megalodon was forked from and syncs to first. Probably the more correct place to put an issue, although they might only care for Mastodon. :p I can still ask the Megalodon people afterwards if needed.

But don't really have a way to confirm if it's the issue with auth for the list. Which seems to be a really good idea to have though.

**Comment by tsmethurst** [comment]
You could try looking at your GtS logs when opening the custom emoji selecter, and see what it returns maybe? I think the api endpoint is `/api/v1/custom_emojis` so just look for that and see if GtS is returning a code 200 or something else.

**Comment by kouya** [comment]
I was just trying to see something in the logs with other clients I think you are right. Just didn't know what request to look for. :3 
Phanpy and Tusky indeed get 200 while Megalodon and also the official client get a 401 from it.

Sorry for the report, I will close it again and try their bugtracker and link to here. <3

**Comment by tsmethurst** [comment]
Ahh okay, glad my intuition is right, but it's a pity it probably won't be changed! I suppose you could ask upstream on the Mastodon Android repo, but the dev doesn't seem v. receptive to changes that don't directly pertain to Mastodon itself, so it might not get changed there either.
