### ISSUE TITLE
[bug] Outgoing HTTP client not re-signing for new URL when redirected

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2795]
I gotta double check this one, but I believe when we follow an ActivityPub URI through a redirect, we don't sign again for the new URI.

For example, if I search for `https://hellsite.site/@dumpsterqueer@ondergrond.org/111856964841873312`, which redirects to `https://ondergrond.org/@dumpsterqueer/111856964630233504`, I get the following error:

`timestamp="01/04/2024 12:26:49.391" func=search.(*Processor).byURI level=DEBUG requestID=ht3356ce04000wy2pr60 msg="semi-expected error type looking up https://hellsite.site/@dumpsterqueer@ondergrond.org/111856964841873312 as status: enrichStatus: error dereferencing https://hellsite.site/@dumpsterqueer@ondergrond.org/111856964841873312: Dereference: GET request to https://ondergrond.org/@dumpsterqueer/111856964630233504 failed: status=\"401 Unauthorized\" body=\"{\"error\":\"Unauthorized: authentication NOT PASSED for public key https://goblin.technology/users/tobi/main-key; tried algorithms [rsa-sha256 rsa-sha512 ed25519]; signature value was 'keyId=\\\"https://goblin.technology/users/tobi/main-key\\\",algorithm=\\\"hs201\""`

Searching directly for `https://ondergrond.org/@dumpsterqueer/111856964630233504` works fine though.

We should try and figure out if I'm correct in my diagnosis that we're not signing for the redirected URI, and also investigate if it's possible to do that without completely refactoring the http client stuff.

**Comment by NyaaaWhatsUpDoc** [comment]
i think this will require some rethinking, I'll see if I can throw it in with the http queue stuff as I'm doing some breakdown of it there. it's going to need changing where the signing performed and having it placed in the transport

**Comment by tsmethurst** [comment]
Alright! Maybe I'll take this one out of 0.15.0 then, if it has to involve some refactoring? Would like to avoid big-ish refactors before the release (let's save them for after).

**Comment by daenney** [comment]
I think we can solve it in the mean time by (also) doing the signing in `http.Client.CheckRedirect`?

The [default for check redirect](https://cs.opensource.google/go/go/+/refs/tags/go1.22.1:src/net/http/client.go;l=810) is:

```go
func defaultCheckRedirect(req *Request, via []*Request) error {
	if len(via) >= 10 {
		return errors.New("stopped after 10 redirects")
	}
	return nil
}
```

But we could set our own function there that keeps the `len(via)` check and updates `req` (the upcoming request) after with the new signing header.

**Comment by daenney** [comment]
I think you can also do this by putting the signing in an `http.RoundTripper`, instead of the `Do` method we have now. That *should* get called for each request in the chain.

**Comment by NyaaaWhatsUpDoc** [comment]
yeah that's i meant with the http library transport :)

**Comment by NyaaaWhatsUpDoc** [comment]
i think i found a way to manage this without any refactoring. currently running our tests against it now to see if it works!
