### ISSUE TITLE
[feature] List themes as dropdown menu

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#2806]
### Is your feature request related to a problem ?

As of now, the user theme options are presented in the form of radio buttons. As instances begin to introduce a plethora of custom themes, the list of radio buttons grows longer, potentially cluttering the interface and making it less user-friendly.

### Describe the solution you'd like.

Would it be possible to consider modifying the theme selection from a list of radio buttons to a dropdown menu?

### Describe alternatives you've considered.

None

**Comment by tsmethurst** [comment]
Mm yeah could probably do this :+1:
