### ISSUE TITLE
[bug/0.15.0-rc1] No notification was created when a user follows another user on the same instance.

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#2813]
### Describe the bug with a clear and concise description of what the bug is.

There is no "user1 followed you" notification created when user1 choose to hide their followings in gts settings.

### What's your GoToSocial Version?

0.15.0-SNAPSHOT+git-85bc140

### GoToSocial Arch

arm64 docker

### What happened?

No notification was created when a following-hiddened user follows another user

### What you expected to happen?

A notification was created

### How to reproduce it?

1. Set the hiding followings option to true
2. Follow another account on the same instance. (If on two different instances, things will go normal)
3. Switch to "another account" and check notification

If the "no notification" criteria was triggered. No further "followed you" notification will be made, even changing the option back to false and re-do the follow does so.

**Comment by tsmethurst** [comment]
Oh that's curious... Thanks, I'll take a look at it.

**Comment by CDN18** [comment]
It seems that follows created by local accounts will still not produce a notification.

**Comment by tsmethurst** [comment]
Ah really? I haven't been able to recreate this on my instance. I'll take another look at it.

**Comment by CDN18** [comment]
Thanks! will try my best to help out if I can :)
