### ISSUE TITLE
[feature] Investigate using Matrix protocol for DMs

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#284]
Right now DMs are just ActivityStreams Notes with only the recipient in the To field -- the same way Mastodon does it. This is OK, but it's nowhere near as smooth as actual instant messaging is, and it also has no kind of end-to-end encryption.

We should investigate to what extent it would be possible to integrate GoToSocial with a running Matrix server (probably Synapse) in order to allow users to send messages to each other.

**Comment by tsmethurst** [comment]
Linking this because it might be useful: https://github.com/matrix-org/gomatrix

**Comment by loid345** [comment]
Dendrire server written on golang, and it goes better

**Comment by jugendhacker** [comment]
I'm not totally sure if Matrix would be a great choice here, as Matrix is quite complex, as every participating server in a room (also private chats are rooms, but only with two people) has to keep a directed graph of all events (or at least the important ones) that happened in such a room. This will definitely add a lot of complexity to GtS. Maybe [Application Services](https://matrix.org/docs/guides/application-services) could take away some of the complexity, but IMHO a more "fire and forget"-ish Protocol would make more sense here, as it minimizes the effort GtS has to do.
