### ISSUE TITLE
[feature] Domain names as usernames

### ISSUE THREAD

**Issue by erlend-sh** [superseriousbusiness/gotosocial#2840]
### Is your feature request related to a problem ?

I'd like to set my root domain as my handle, [like in Bluesky](https://bsky.social/about/blog/4-28-2023-domain-handle-tutorial).

This greatly improves account portability. Related to #1141 

### Describe the solution you'd like.

Apparently this is quite doable in ActivityPub as well:

https://mymath.rocks/objects/ee4b8487-1ba2-4041-b7fd-744d5eface64

https://codeberg.org/fediverse/fep/src/branch/main/feps/fep-4adb.md

https://codeberg.org/fediverse/fep/src/branch/main/feps/fep-612d.md

![B5F29E29-1150-4773-932F-0CA4990DA06A](https://github.com/kitsune-soc/kitsune/assets/583842/1cdaefdb-9699-43ec-8ff8-978ce5f36ccc)

### Describe alternatives you've considered.

Also under consideration in the Kitsune project: https://github.com/kitsune-soc/kitsune/issues/217

### Additional context.

- https://datatracker.ietf.org/wg/dance/about/
- https://datatracker.ietf.org/doc/draft-ietf-dance-architecture/

**Comment by tsmethurst** [comment]
I don't really understand what's being requested here, or why. Could you explain this in more detail please?

**Comment by NyaaaWhatsUpDoc** [comment]
i'm not really sure i see the benefit of it other than vanity? if you can implement this without spaghettifying out dereferencer then by all means go for it, but otherwise i can't really see this being a high priority (if at all) over useful safety features, performance enhancements, etc.

**Comment by daenney** [comment]
The SocialHub FEPs are generally ignored by many ActivityPub "microblogging" implementers and many of us don't engage with that process for various reasons. Unless someone puts in the effort to drive at a consensus between some major implementations (like Masto, Pleroma/Akkoma, Misskey etc.) that this is a thing they'll implement, it makes little sense for much smaller projects like ours to spend the time on it.

I also don't see much of a benefit to having 2 username schemes. It's a whole additional thing to implement, which also brings DNS in scope, for the 1% case of wanting to use the domain as the handle directly. It seems this would only complicate the interoperability story.

If anyone wants to use the GtS codebase for their own experimentation though, to figure out what an implementation of this would look like in practice, please do. But it's not likely we'd accept a PR for it, unless some of the big implementations decide to go for it.

**Comment by tsmethurst** [comment]
Hiya, I'm gonna close this as not planned, since it looks unlikely we'll be doing this. If we change our minds later we can always open it again :)
