### ISSUE TITLE
[bug] Delivery goroutines experienced a panic with "not yet initialized" while executing CLI commands

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#2843]
### Describe the bug with a clear and concise description of what the bug is.

CLI commands are terminating with error messages indicating that a panic occurred due to not being initialized:

For example, this error appears when executing the command 'gotosocial admin account create':

```
goroutine 25 [running]:
github.com/superseriousbusiness/gotosocial/internal/transport/delivery.(*Worker).run(0x0?, {0x27eb968?, 0x400010c660?})
        /drone/src/internal/transport/delivery/delivery.go:159 +0x134
codeberg.org/gruf/go-runners.(*Service).GoRun.func1()
        /drone/src/vendor/codeberg.org/gruf/go-runners/service.go:59 +0x64
created by codeberg.org/gruf/go-runners.(*Service).GoRun in goroutine 1
        /drone/src/vendor/codeberg.org/gruf/go-runners/service.go:49 +0x8c
panic: not yet initialized

goroutine 30 [running]:
github.com/superseriousbusiness/gotosocial/internal/transport/delivery.(*Worker).run(0x0?, {0x27eb968?, 0x400010c840?})
        /drone/src/internal/transport/delivery/delivery.go:159 +0x134
codeberg.org/gruf/go-runners.(*Service).GoRun.func1()
        /drone/src/vendor/codeberg.org/gruf/go-runners/service.go:59 +0x64
created by codeberg.org/gruf/go-runners.(*Service).GoRun in goroutine 1
        /drone/src/vendor/codeberg.org/gruf/go-runners/service.go:49 +0x8c
```

### What's your GoToSocial Version?

v0.15.1-SNAPSHOT+git-6de5717

### GoToSocial Arch

arm64 Docker

### What happened?

CLI commands terminated with error

### What you expected to happen?

CLI ammnads are executed successfully

### How to reproduce it?

Run any cli command.
In my case the errored commands are `admin account create/list/confirm`

**Comment by tsmethurst** [comment]
Thanks! I think we just need to initialize the delivery queues when running commands via the CLI (even if we don't end up using them). @NyaaaWhatsUpDoc do you feel like doing this one or should I?
