### ISSUE TITLE
[bug] twblue and possibly software based around mastodon.pi doesn't work

### ISSUE THREAD

**Issue by albertotirla** [superseriousbusiness/gotosocial#2845]
### Describe the bug with a clear and concise description of what the bug is.

I am not on windows, but I know afew people who want to use those clients, because they are more accessible for blind users.

There's one which is open source, it's called twblue, but another which is mostly used by windows users is called tweesecake, both of them use mastodon.py, but fixing one is probably fixing the other. None of them work, no posts are shown in one, and the other is actually crashing

### What's your GoToSocial Version?

latest

### GoToSocial Arch

x86_64 docker

### What happened?

twblue, for example, just crashes, with this exception printed in its logs:

```
16/04/2024 17:28:08 root ERROR: Uncaught exception
Traceback (most recent call last):
  File "__startup__.py", line 124, in run
  File "console.py", line 16, in run
  File "main.py", line 128, in <module>
  File "main.py", line 87, in setup
  File "controller\mainController.py", line 242, in do_work
  File "controller\mastodon\handler.py", line 59, in create_buffers
  File "sessions\mastodon\session.py", line 108, in get_user_info
  File "sessions\mastodon\session.py", line 124, in get_muted_users
  File "decorator.py", line 232, in fun
  File "mastodon\utility.py", line 49, in wrapper
  File "mastodon\relationships.py", line 30, in mutes
  File "mastodon\internals.py", line 297, in __api_request
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Not Found')
```

### What you expected to happen?

the functionality of the client, as much as it is, should work

### How to reproduce it?

* download one of the programs, twblue is recommended because it's open source
* use the interface to log in
* restart the app

### Anything else we need to know?

when that request is performed, I get the following related log line in the server, which corelates with the exception backtrace in the log:

```
gotosocial_1  | timestamp="16/04/2024 21:28:09.159" func=server.glob..func1.Logger.func13.1 level=INFO latency="32.899µs
" userAgent=TWBlue/2024.01.05 method=GET statusCode=404 path=/api/v1/mutes clientIP=x.x.x.x errors="Error #01: Not Found\n" requestID=yyyyyyy msg="Not Found: wrote 21B"
```

**Comment by CDN18** [comment]
This may relate to #717 . Mutes API is not implemented yet so clients that require this API will not function properly until it is implemented.

**Comment by CDN18** [comment]
This may relate to #717 . Mutes API is not implemented yet so clients that require this API will not function properly until it is implemented.

**Comment by tsmethurst** [comment]
We can probably just stub out this endpoint for now to return an empty array. This should alleviate the issue until we actually implement that endpoint properly.

**Comment by albertotirla** [comment]
similar errors happen with tweesecake, the only difference is that it's trying to access other endpoints, such as conversations, which also return that error, causing the statuses in the timeline to be just blank strings, even though their number is indeed displayed correctly, as in, there is an equal amount of blank spots as there should be toots. This possibly affects anything which uses mastodon.py, but the person I'm talking to only tryed to use those two clients.

**Comment by tsmethurst** [comment]
Alright, got it. Tbh if a client errors getting something, it should probably try to handle the error gracefully. But we'll do what we can from this side.

**Comment by tsmethurst** [comment]
I've now stubbed out the mutes and conversations endpoints. When I'm on my windows partition i'll install twblue and check whether it works now.

**Comment by tsmethurst** [comment]
Confirmed fixed on latest snapshot/main now :)

**Comment by albertotirla** [comment]
alright, this can be closed now, not your issue anymore
