### ISSUE TITLE
[feature] Sign up page for new accounts

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#286]
We should have a sign up page for people who want to apply for an account on an instance.

Right now the flow of creating a new account is either:

1. Ask the admin directly out of band.
2. Do the sign-up flow through the API as scripted here: https://github.com/superseriousbusiness/gotosocial/blob/main/scripts/auth_flow.sh

In addition to these methods, we should have a webpage with a form that prospective users can fill out. This would show the terms and conditions of the instance, the instance description etc, and require a prospective user to give their desired username, email address, password, locale etc. The form should be POSTed to `/api/v1/accounts`.

**Comment by ForestJohnson** [comment]
I was planning on adding this as a new route here: https://github.com/superseriousbusiness/gotosocial/blob/main/internal/api/client/auth/auth.go#L74

I haven't looked into it very far yet, my initial plan was to start by copy and pasting the SignInGETHandler / SignInPOSTHandler  into a RegisterGETHandler and RegisterPOSTHandler and work from there.

**Comment by mindmeshlink** [comment]
I see this was listed as the already open version of #1027 - to be clear then, is the API signup flow one which creates users that still need manually approved by an admin to post on the instance, as a default?
