### ISSUE TITLE
[bug/frontend] Custom emoji shortcode is not changed after addition/changed input file

### ISSUE THREAD

**Issue by jessienab** [superseriousbusiness/gotosocial#2868]
### Describe the bug with a clear and concise description of what the bug is.

When adding a custom emoji through the settings panel, the shortcode is automatically populated by the filename.

The existing shortcode in the input box is not removed: 
* If the emoji is accepted and added to the system, and
* if a different file is put into the Browse selection

Not sure if this is a bug or a feature request, but given the shortcode populates from the filename the first time, it should *always* populate from the filename then, and should clear itself after a successful addition.

### What's your GoToSocial Version?

0.15.0+git-15733cd

### GoToSocial Arch

amd64 Docker Image (podman rootless)

### What happened?

1. Emoji is selected to be added. Shortcode is populated from filename.
2. The emoji is added to the system assuming there is not shortcode conflict
3. Another emoji image file is selected to be added.
4. The shortcode input box retains the same text as the first file

### What you expected to happen?

1. Emoji is selected to be added. Shortcode is populated from filename.
2. The emoji is added to the system assuming there is not shortcode conflict
OR
2. Another emoji image file is selected to be added.

3. The shortcode input box should either change to the new filename, or should be cleared following a successful addition.

### How to reproduce it?

1. Go to $host/settings/admin/custom-emoji/local
2. Select a custom emoji file
3. Let it populate the shortcode. Change it as needed
4. Add the emoji, or select a different image to use as an emoji source

### Anything else we need to know?

Please see these images as visual examples:

First, file Untitled.png is selected, then added to the emoji roster.
Then a different file is selected, but the shortcode of the first file remains.
![Screenshot from 2024-04-25 22-06-28](https://github.com/superseriousbusiness/gotosocial/assets/99688442/406ecdd6-9b23-4c27-ab29-3fa04a2ab15b)
![Screenshot from 2024-04-25 22-06-37](https://github.com/superseriousbusiness/gotosocial/assets/99688442/91ab3c2b-86d5-4533-8baa-e2948fa69f06)

https:// gts-test.nabein.me is the instance I'm testing on.

Thank you!

**Comment by tsmethurst** [comment]
Just a bug I think, I'll take a look (I'm in the settings panel code the last few days anyway).
