### ISSUE TITLE
[bug] External Users can still see followings/followers of a follow-hiddened account

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#2895]
### Describe the bug with a clear and concise description of what the bug is.

After enabling `Hide who you follow / are followed by` option, other local user won't see the following and follow list. However, remote accounts can still see the exact following/follower list of the follow-hiddened account. 

### What's your GoToSocial Version?

0.15.1-SNAPSHOT+git-35b1c54

### GoToSocial Arch

arm64 Docker

### What happened?

The following/follower list is not properly hiddened.

### What you expected to happen?

After enabling the hidden option, users of external instances will also be unable to see the following and followers list.

### How to reproduce it?

1. Enable the hide option
2. Login a remote account
3. Load the following/follower list of the follow-hiddened account. (Should be loaded with `load from remote instance` enabled or option alike)

**Comment by tsmethurst** [comment]
Could you give some more details? There's nothing we can do to stop external instances showing followers/following on their instance that they know about (which should not be a complete list). Or, if the external instance loaded the whole list by iterating through followers/following *before* the gts account set hide collections, there's not much we can do about that either. Though I'm not aware of any fedi server that iterates through followers/following in that way.

**Comment by CDN18** [comment]
Sure :) I'm meaning that external users can retrieve the entire following/follower list in realtime even after the hide option are enabled, not just following/followers on their instance, which seems not so normal.

The hiddened gts account has about 60 followers and more than 300 followings, with the discovery option enabled and manually approve option disabled.

**Comment by CDN18** [comment]
Update: After additional testing, I've determined that the issue likely stems from a caching problem in the client I'm using. The complete list is accessible when any account is logged in, but disappears the moment I log out of my hidden GTS account. I was mistaken in my initial assessment. Apologies for the inconvenience🙏

**Comment by tsmethurst** [comment]
Aha no problem, I'm glad there's no issue :)
