### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by iamxvbaba** [superseriousbusiness/gotosocial#294]
1. Request /oauth/authorize?force_login=true&response_type=code&client_id=xxx&redirect_uri=xxx&scope=read%20write%20follow%20push
2. Redirect to /auth/sign_in page.
3. Login success And redirect to /oauth/authorize.

return error: missing one of: response_type, client_id or redirect_uri.
Why the session has nothing?

**Comment by iamxvbaba** [comment]
![image](https://user-images.githubusercontent.com/28732408/140273922-085f35cd-6f5d-490b-bcfd-c52b3d92f568.png)

**Comment by iamxvbaba** [comment]
> 1. Request /oauth/authorize?force_login=true&response_type=code&client_id=xxx&redirect_uri=xxx&scope=read%20write%20follow%20push
> 2. Redirect to /auth/sign_in page.
> 3. Login success And redirect to /oauth/authorize.
> 
> return error: missing one of: response_type, client_id or redirect_uri. Why the session has nothing?

cookie is empty.

**Comment by iamxvbaba** [comment]
oo, Host is error.

**Comment by PrivacyDragon** [comment]
What was exactly the problem here?
I am now experiencing it too.
