### ISSUE TITLE
[bug] Refused to load the stylesheet ... because it violates the following Content Security Policy directive: "default-src 'self'".

### ISSUE THREAD

**Issue by 3waffel** [superseriousbusiness/gotosocial#2947]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

When importing elements from a remote url in the custom css, the page will not load it due to CSP.

```css
@import "https://another-origin.com/style.css";
```

With the following error message showing in the console:

```
Refused to load the stylesheet 'https://another-origin.com/style.css' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.
```

The provided "advanced-csp-extra-uris" option only makes difference on "img-src" and "media-src", but the "style-src-elem" still uses "default-src".
It might be helpful to provide another option to explicitly change "default-src".

### What's your GoToSocial Version?

v0.15.0+git-15733cd

### Browser version

Chrome 125.0.6422.113

### How to reproduce it?

Importing a remote element in the custom css results in the error.

**Comment by tsmethurst** [comment]
Heya, this isn't a bug, it's just the CSP working as intended. If you need to load a separate CSS file for your custom CSS, you can just put it in your `web/assets/dist` directory and import it with `@import "/assets/dist/whatever.css"`.
