### ISSUE TITLE
[bug] Followed Owncast Stream but GTS seems to randomly not get updates

### ISSUE THREAD

**Issue by ozonedGH** [superseriousbusiness/gotosocial#2948]
### Describe the bug with a clear and concise description of what the bug is.

Honestly not sure how to define this.  I followed https://cast.samsai.eu/ months ago.  I randomly get updates from the stream.  I just looked at the logs and I unfollowed and refollowed and saw the following in the log:

```
timestamp="31/05/2024 17:02:26.543" func=server.glob..func1.Logger.func13.1 level=INFO latency="2.286341ms" userAgent=Go-http-client/2.0 method=GET statusCode=401 path=/users/ozoned clientIP=172.19.0.1 pubKeyID=https://cast.samsai.eu/federation/user/stream#main-key errors="Error #01: authentication NOT PASSED for public key https://cast.samsai.eu/federation/user/stream#main-key; tried algorithms [rsa-sha256 rsa-sha512 ed25519]; signature value was 'keyId=\"https://cast.samsai.eu/federation/user/stream#main-key\",algorithm=\"hs2019\",headers=\"(request-target) host date\",signature=\"X35nb8i/Os07mn3HfgKpcu8wlaKDtjune4SGGYHEOn0ZsBiK2k2topS66eOfc0xtlJI+OhjB9inozIHS3EmjE+/T8smOhKLvftNzh6rG4qgzRO/qTcvOFbLogsaLJfo/Lccng7TwikqPv8PCmQvy8X07fMwwTGs2xyxbLDCAuFDgmUP2HDIQkPVkmwoEqOpY++hyLmHc6BR385ZwdGh39YIyEUsovX5XIojwPAbNHN7qHgQooEuSzX6VPMt6GtkG8dyoZ9anpP3TxhOEqsZRfJioXGccXuy6264WuVsX/26NVZ93YyDcZvrWx3JHsL8dtGOLsSz/g8/8njZOk5cS5Q==\"'\n" requestID=xh59nkwf0400012bssm0 msg="Unauthorized: wrote 533B"
```

So it looks like I'm expecting a specific public key, but I got something else.  I unfollowed and followed again, maybe the Owncast server switched sites or something, but still getting the same.

I'm honestly not sure if this is a GTS issue or an Owncast issue.  Hoping for any kind of thoughts or help with this.

Thank you all for you help, the tech is amazing and you're helping free the internet with the work you do.

### What's your GoToSocial Version?

0.15.0

### GoToSocial Arch

Docker x64

### What happened?

I can find and follow the streamer, but I don't get updates.

### What you expected to happen?

When the streamer updates their Owncast title, makes a post, goes live, that i get an update.

### How to reproduce it?

I just followed stream@cast.samsai.eu and I see it.

### Anything else we need to know?

I don't honestly know.  I'm going to open up a bug with Owncast as well and I'll post the Inc# here.

https://github.com/owncast/owncast/issues/3757

**Comment by tsmethurst** [comment]
It looks like GtS isn't happy with the signature coming from that server. You could try invalidating the keys for `cast.samsai.eu` in the settings panel under "admin -> actions -> keys", and see if that resolves the issue.

**Comment by ozonedGH** [comment]
I didn't even know you could expire the keys.  I did this and I'll update as soon as I have more information!  Thank you so much!  :)

**Comment by tsmethurst** [comment]
No worries. I recommend unfollowing and refollowing and seeing if it goes through this time.

**Comment by ozonedGH** [comment]
That looks to have worked and following and unfollowing is the smart move, but I'm not the smartest.  :-D  lol I had thought of it, but just slipped my mind I guess, so thank you very much for your help!  I'll close this and the Owncast bug I opened.  Appreciate it.

**Comment by tsmethurst** [comment]
Glad it's working :)
