### ISSUE TITLE
[feature] Emoji grabber

### ISSUE THREAD

**Issue by jk-na** [superseriousbusiness/gotosocial#295]
Very low priority, but is it possible for GtS to pull the emoji icon from the remote server if it isn't locally stored\referenced and store it?

Possibly toggleable, as I guess some people may prefer :lotsof: :colon: :enclosed: :text:

**Comment by tsmethurst** [comment]
Yep, handling emojis properly is definitely something we're going to look into :)

**Comment by tsmethurst** [comment]
Putting this one in the next milestone since we're likely putting emoji support in there
