### ISSUE TITLE
[bug] Can't find @demo@seppo.social to follow

### ISSUE THREAD

**Issue by mro** [superseriousbusiness/gotosocial#2961]
### Describe the bug with a clear and concise description of what the bug is.

@gerben@nlnet.nl reported to me that he can't find and follow @demo@seppo.social on their gotosocial.

To investigate, I installed https://www.freshports.org/net-im/gotosocial/, configured https://gotosocial.dev.seppo.social/ and checked https://seppo.social/demo/apchk.cgi/webfinger?redirect=self&resource=@demo@gotosocial.dev.seppo.social

The gotosocial server log say
```
$ tail -f /var/log/messages
Jun  4 10:50:20 vmd32118 gotosocial[53222]: timestamp="2024-06-04T10:50:20.267+02:00" func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://seppo.social/demo/apchk.cgi/actor.jsa#main-key requestID=0dc7d70f-753d-44ec-9c5c-1c8e97048399 pubKeyID=https://gotosocial.dev.seppo.social/users/demo/main-key msg="performing request"
Jun  4 10:50:25 vmd32118 gotosocial[53222]: timestamp="2024-06-04T10:50:25.278+02:00" func=server.glob..func1.Logger.func13.1 level=ERROR latency="5.023752519s" userAgent=Seppo.Social method=GET statusCode=500 path=/users/demo clientIP=81.28.232.73 pubKeyID=https://seppo.social/demo/apchk.cgi/actor.jsa#main-key errors="Error #01: callForPubKey: error dereferencing public key https://seppo.social/demo/apchk.cgi/actor.jsa#main-key: Get \"https://seppo.social/demo/apchk.cgi/actor.jsa#main-key\": context deadline exceeded (Client.Timeout exceeded while awaiting headers) (fast fail)\n" requestID=0dc7d70f-753d-44ec-9c5c-1c8e97048399 msg="Internal Server Error: wrote 33B"
```

while https://seppo.social/demo/apchk.cgi/actor.jsa#main-key returns the actor profile json.

### What's your GoToSocial Version?

0.14.1_2

### GoToSocial Arch

FreeBSD binary

### What happened?

```
$ tail -f /var/log/messages
Jun  4 10:50:20 vmd32118 gotosocial[53222]: timestamp="2024-06-04T10:50:20.267+02:00" func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://seppo.social/demo/apchk.cgi/actor.jsa#main-key requestID=0dc7d70f-753d-44ec-9c5c-1c8e97048399 pubKeyID=https://gotosocial.dev.seppo.social/users/demo/main-key msg="performing request"
Jun  4 10:50:25 vmd32118 gotosocial[53222]: timestamp="2024-06-04T10:50:25.278+02:00" func=server.glob..func1.Logger.func13.1 level=ERROR latency="5.023752519s" userAgent=Seppo.Social method=GET statusCode=500 path=/users/demo clientIP=81.28.232.73 pubKeyID=https://seppo.social/demo/apchk.cgi/actor.jsa#main-key errors="Error #01: callForPubKey: error dereferencing public key https://seppo.social/demo/apchk.cgi/actor.jsa#main-key: Get \"https://seppo.social/demo/apchk.cgi/actor.jsa#main-key\": context deadline exceeded (Client.Timeout exceeded while awaiting headers) (fast fail)\n" requestID=0dc7d70f-753d-44ec-9c5c-1c8e97048399 msg="Internal Server Error: wrote 33B"
```

### What you expected to happen?

a found actor to follow.

### How to reproduce it?

enter @demo@gotosocial.dev.seppo.social into the search input field or use the checker https://seppo.social/demo/apchk.cgi/webfinger?redirect=self&resource=@demo@gotosocial.dev.seppo.social

### Anything else we need to know?

Greetings from @mro@digitalcourage.social, I track it also at https://seppo.social/issues/13

**Comment by tsmethurst** [comment]
The errors there look like your server isn't responding with headers in time, so GtS is hanging up the request. However I'm not sure if that's the actual issue or just something up with the test setup (something NAT-related maybe?), because when I search for that actor from my own GtS account I do get a response back, albeit not one that GtS can recognize as a valid ActivityPub response.

This is what I'm getting back:

```json
{
    "type": "Person",
    "id": "https://seppo.social/demo/apchk.cgi/actor.jsa",
    "inbox": "https://seppo.social/demo/apchk.cgi/",
    "outbox": "https://seppo.social/demo/apchk.cgi/",
    "name": "ApChk.cgi",
    "publicKey": {
      "@context": [
        {
          "@language": null
        }
      ],
      "id": "https://seppo.social/demo/apchk.cgi/actor.jsa#main-key",
      "owner": "https://seppo.social/demo/apchk.cgi/actor.jsa",
      "publicKeyPem": "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCFENGw33yGihy92pDjZQhl0C3\n6rPJj+CvfSC8+q28hxA161QFNUd13wuCTUcq0Qd2qsBe/2hFyc2DCJJg0h1L78+6\nZ4UMR7EOcpfdUE9Hf3m/hs+FUR45uBJeDK1HSFHD8bHKD6kv8FPGfJTotc+2xjJw\noYi+1hqp1fIekaxsyQIDAQAB\n-----END PUBLIC KEY-----",
      "signatureAlgorithm": "https://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
    },
    "manuallyApprovesFollowers": true,
    "discoverable": false,
    "generator": {
      "type": "Link",
      "href": "https://seppo.social",
      "name": "ApChk.cgi"
    },
    "attachment": []
  }
```

I'd assume the issue there is that you have a `@context` embedded inside your public key model, but no `@context` for the Actor model you're serving.

**Comment by tsmethurst** [comment]
Some more context (ha!) about this: https://www.w3.org/TR/activitystreams-core/#jsonld

Just to clarify, we're not sticklers ourselves about items having a `@context`, because we don't really compact/uncompact following json-ld, so it doesn't matter to us either way. The only reason we require one is because the library we're using does, iirc, despite the lines given here:

> When a JSON-LD enabled Activity Streams 2.0 implementation encounters a JSON document identified using the " application/activity+json" MIME media type, and that document does not contain a @context property whose value includes a reference to the normative [Activity Streams 2.0 JSON-LD @context definition](https://www.w3.org/ns/activitystreams), the implementation MUST assume that the normative @context definition still applies.

**Comment by mro** [comment]
> but no `@context` for the Actor model

uh, excellent catch, thank you, let me fix and check back…

**Comment by mro** [comment]
hm, adding the `@context`, deploying to dev.seppo.social and trying https://dev.seppo.social/demo/apchk.cgi/webfinger?redirect=self&resource=@demo@gotosocial.dev.seppo.social yields in the server log:
```
Jun  4 14:01:16 vmd32118 gotosocial[53222]: timestamp="2024-06-04T14:01:16.792+02:00" func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://dev.seppo.social/2024-03-19/apchk.cgi/actor.jsa#main-key requestID=8cac0709-59cb-4c6e-8b19-8e5b194b6999 pubKeyID=https://gotosocial.dev.seppo.social/users/demo/main-key msg="performing request"
Jun  4 14:01:16 vmd32118 gotosocial[53222]: timestamp="2024-06-04T14:01:16.860+02:00" func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://dev.seppo.social/2024-03-19/apchk.cgi/actor.jsa requestID=8cac0709-59cb-4c6e-8b19-8e5b194b6999 pubKeyID=https://gotosocial.dev.seppo.social/users/demo/main-key msg="performing request"
Jun  4 14:01:16 vmd32118 gotosocial[53222]: timestamp="2024-06-04T14:01:16.889+02:00" func=server.glob..func1.Logger.func13.1 level=ERROR latency="112.124727ms" userAgent=Seppo.Social method=GET statusCode=500 path=/users/demo clientIP=167.86.120.117 pubKeyID=https://dev.seppo.social/2024-03-19/apchk.cgi/actor.jsa#main-key errors="Error #01: AuthenticateFederatedRequest: error dereferencing account https://dev.seppo.social/2024-03-19/apchk.cgi/actor.jsa: enrichAccount: error converting accountable to gts model for account https://dev.seppo.social/2024-03-19/apchk.cgi/actor.jsa: ASRepresentationToAccount: unusable username for https://dev.seppo.social/2024-03-19/apchk.cgi/actor.jsa\n" requestID=8cac0709-59cb-4c6e-8b19-8e5b194b6999 msg="Internal Server Error: wrote 33B"
```

why can't GotoSocial use the username?

**Comment by mro** [comment]
ic, it has no preferredusername…

**Comment by tsmethurst** [comment]
The webfinger case is a bit odd. If I curl `https://dev.seppo.social/.well-known/webfinger?resource=acct:Chk.cgi@dev.seppo.social`, I get redirected to `https://dev.seppo.social/2024-03-19/.well-known/webfinger/index.jrd?resource=acct:Chk.cgi@dev.seppo.social`, which is fine in itself, and GtS will follow that redirect. But then the result is:

```json
{
  "subject": "acct:demo@dev.seppo.social",
  "links": [
    {
      "href": "https://dev.seppo.social/2024-03-19/activitypub/actor.jsa",
      "rel": "self",
      "type": "application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\""
    },
    {
      "href": "https://dev.seppo.social/2024-03-19/",
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html"
    },
    {
      "href": "https://dev.seppo.social/2024-03-19/o/p/",
      "rel": "alternate",
      "type": "application/atom+xml"
    },
    {
      "rel": "http://ostatus.org/schema/1.0/subscribe",
      "template": "https://dev.seppo.social/2024-03-19/seppo.cgi/actor?id={uri}"
    }
  ]
```

So in response to a request for user `Chk.cgi`, it's giving back info for user `demo`, which is why GtS is not accepting it.

GtS requires (what it considers to be) a valid and well-formed webfinger response as a security measure. Ie., it uses the server as the authority on whether a given user really exists on the server, to prevent cases where someone does something weird like upload a json-ld file claiming to be an ActivityPub actor in order to create "ghost" actors that don't really exist.

Just to check, do you have issues federating with other fedi server softwares, or is it just GtS that's presenting issues?

**Comment by tsmethurst** [comment]
Talked about this with other devs and we're thinking about relaxing the `preferredUsername` requirement GtS currently has, and falling back to discovering a username via webfinger instead when `preferredUsername` isn't present.

**Comment by mro** [comment]
> webfinger case is a bit odd

when leaving the `apchk.cgi` aside and focusing on serious accounts, for @demo@dev.seppo.social, I would have expected `$ curl -L 'https://dev.seppo.social/.well-known/webfinger?resource=acct:demo@dev.seppo.social'`.

The endpoint `/.well-known/webfinger` acts as a (de)multiplex funnel and does not check names but happily (cascadingly) redirect and may well lead to a 404 downstream.

In essence interesting are the accounts @demo@dev.seppo.social (for development and tests, e.g. here) and  @demo@seppo.social (for anybody to try except @mentions once I set up nightly rollback).

I'd love to see gotosocial following both.

**Comment by mro** [comment]
P.S.: let's wait with that until after your release.

**Comment by mro** [comment]
congratulations @tsmethurst to the release. Now as the dust may have settled, can you have another look?

**Comment by mro** [comment]
Hi @tsmethurst,

the situation has worsened. The signed http `get` gets a 500 response from social.nlnet.nl: https://seppo.social/aseppototry/seppo.cgi/http?get=https%3A%2F%2Fsocial.nlnet.nl%2Fusers%2Fgerben (uid: aSeppoToTry pwd: demodemodemo) while the same binary on a different server gets a 200.

**Comment by tsmethurst** [comment]
I'll see if time allows to do this soon: https://github.com/superseriousbusiness/gotosocial/issues/2961#issuecomment-2149409802

But I'm working on a big feature right now that I wanna get finished ASAP, so it will have to wait til afterwards, unless someone else has time to take a look at it.
