### ISSUE TITLE
[bug] WASM SQLite build + default config is slow on not-Linux

### ISSUE THREAD

**Issue by daenney** [superseriousbusiness/gotosocial#2962]
### Describe the bug with a clear and concise description of what the bug is.

When running with the WASM SQLite build on anything other than Linux, `db-sqlite-journal-mode` must not be set to `WAL` ~~as that can currently lead to database corruption~~ as otherwise performance will be atrocious.

Instead, we should use `TRUNCATE` in those cases. This has a slight performance impact, but should be fine in practice for small instances especially while this is still in the experimental stages.

### What's your GoToSocial Version?

main

### Anything else we need to know?

We should do two things:

* [ ] Add some documentation about this
* [ ] Update the config parser to check for `runtime.GOOS` and if that's not Linux on the WASM build throw an error if the journal mode is set to WAL

**Comment by NyaaaWhatsUpDoc** [comment]
i think we should be careful what we claim to support. not to say we don't add checks, but we should be careful with what we claim to officially support.

i know for certain that our storage library will only work on Unix like filesystems, and may possibly cause issues on systems outside of Linux / BSDs

**Comment by daenney** [comment]
Aye, we don't have to support everything under the sun.

The WAL mode issue affects the BSDs however. Given we already publish a FreeBSD binary ourselves and we're packaged in pkgsrc etc. I think we should fix that case because that's a bit of a footgun now. That's what I meant with not-Linux since Windows isn't something we support in the first place (and folks can use WSL).

**Comment by ncruces** [comment]
Do you have a reference on database corruption? I'm guessing this may be a misunderstanding.

You should never get corrupted databases with a default build of `github.com/ncruces/go-sqlite3`.

Without a fix for ncruces/go-sqlite3#85 WAL mode should perform awfully, to the point that you can't open a database, but it should not corrupt data.

**Comment by daenney** [comment]
Ah sorry. Then yes, that's a misunderstanding on my part. Let me update that.

**Comment by ncruces** [comment]
No problem! I understand the subtly of the topic, but that's why I tried hard to default to safe, will never corrupt your data, settings.

Also… macOS is fine, it just works.

And I don't think you are using `EXCLUSIVE` locking mode, nor should you. You'd need to use `SetMaxOpenConns(1)`, and that's not realistic, really.

Finally, I think ncruces/go-sqlite3#90 is almost done.

**Comment by daenney** [comment]
That's awesome, thank you for doing these things for us. There's no rush on our side, I think with the warning PR I've raised it's fine and we can ship with that for a while until the BSD WAL shakes out and you're happy and confident in the implementation.

We don't intend to switch to it yet by default for 0.16, but we might go for it for 0.17 if there's no known issues then. We release every 2-3 months and I'm guessing 0.16 might be an end-of-June type of affair.

**Comment by ncruces** [comment]
> That's awesome, thank you for doing these things for us.

No problem, you're an great nerd sniper.
It was in my TODO list, if someone wants to try it, all the better.
I'm now pretty confident in this solution; just missing docs, clean up.

**Comment by daenney** [comment]
Issue has been resolved on the go-sqlite3 side so we'll upgrade when a new release comes out instead.
