### ISSUE TITLE
[bug] Headers markdown not shown in Sharkey

### ISSUE THREAD

**Issue by AtiusAmy** [superseriousbusiness/gotosocial#2974]
### Describe the bug with a clear and concise description of what the bug is.

Headers just looks like normal texts when they should be bold

https://social.atiusamy.com/notes/9u7s0jqg599o07od

https://fedi.winscloud.net/@winsdominoes/statuses/01HZRGRJY17Q0RST67R8GFA2D7

Headers from IceShrimp does render properly in Sharkey though: 

https://social.atiusamy.com/notes/9u7iay1l599o059f

Not sure if this is a *key being goofy issue or GoTo not federating issue, but unfortunately I'm not smart enough to determine that 😅

### What's your GoToSocial Version?

v0.15.0

### GoToSocial Arch

amd64 Docker

### What happened?

The headers shown in Sharkey looks like a normal text

### What you expected to happen?

Looks big and bold like a header

### How to reproduce it?

Make a GoTo post that has "# words"

View that post in Sharkey

**Comment by tsmethurst** [comment]
I believe this is a *key thing, we don't remove headers or anything from the markdown before sending stuff out, so I'll close this. Perhaps you can raise it with them?

**Comment by AtiusAmy** [comment]
> I believe this is a *key thing, we don't remove headers or anything from the markdown before sending stuff out, so I'll close this. Perhaps you can raise it with them?

Ah yeah, I will!

**Comment by AtiusAmy** [comment]
To give an update on this I created an [issue](https://social.atiusamy.com/files/cf165ef0-7d95-4699-9787-b1679aacb497) on their Gitlab, and it is not being fixed with this [PR](https://activitypub.software/TransFem-org/Sharkey/-/merge_requests/540) :D

Seems to be an issue with mfm
