### ISSUE TITLE
[bug] Incorrect path to vote in a poll in the API documentation

### ISSUE THREAD

**Issue by dananglin** [superseriousbusiness/gotosocial#2994]
### Describe the bug with a clear and concise description of what the bug is.

In the API documentation the path to cast a vote in a poll is set to `/api/v1/polls/{id}/vote` [here](https://github.com/superseriousbusiness/gotosocial/blob/611f9de39b7a29e89616c9ffe76d2aca1194877b/docs/api/swagger.yaml#L7525), but I get a `404` from my instance when using this path. This is the log message I get from my instance:

```
timestamp="11/06/2024 17:28:19.986" func=server.glob..func1.Logger.func13.1 level=INFO latency="45.047µs" userAgent=Enbas/0.0.0 method=POST statusCode=404 path=/api/v1/polls/01J020RN185KYW7T0MAVZFRFND/vote clientIP=172.18.1.1 errors="Error
#01: Not Found\n" requestID=j422224g04000v2r7zg0 msg="Not Found: wrote 21B"
```

I believe the correct path for voting is `/api/v1/polls/{id}/votes` (after looking [here](https://github.com/superseriousbusiness/gotosocial/blob/611f9de39b7a29e89616c9ffe76d2aca1194877b/internal/api/client/polls/polls.go#L32)) and I was able to cast my votes after updating the path to this.

### What's your GoToSocial Version?

v0.15.0

### GoToSocial Arch

amd64 Docker

### What happened?

I was testing the path to cast a vote to a poll using the path in the API documentation and got a `404` from my instance.

### What you expected to happen?

A `200` response.

### How to reproduce it?

Visit the path in the specified in the API documentation to cast a vote in a poll.

### Anything else we need to know?

N/A

**Comment by VyrCossont** [comment]
Yep, that checks out: the path in the docs is wrong. Thanks for the report.
