### ISSUE TITLE
[feature] Implement "api/v1/notifications?limit=20&types[]=mention"

### ISSUE THREAD

**Issue by Fastidious** [superseriousbusiness/gotosocial#3003]
### Is your feature request related to a problem ?

Yes, and no. Yes, because it doesn't work and renders an error on Phanpy (or any client that uses the same API filter), no, because it isn't a show stopper.

Phanpy, a favourite of many Mastodon client, allows for the filtering of mentions using `api/v1/notifications?limit=20&types[]=mention`, using the `notifications` API. When connected to GoToSocial such feature doesn't work (see https://github.com/cheeaun/phanpy/issues/567).

### Describe the solution you'd like.

Based on the above, could it be possible to implement the API to allow filtering on notifications?

### Describe alternatives you've considered.

NONE

**Comment by Fastidious** [comment]
Just got the snapshot (b08c1bd) to test this one, and I am getting the same error on Phanpy. Is there something I need to set on config?

**Comment by tsmethurst** [comment]
https://github.com/superseriousbusiness/gotosocial/pull/3023 will resolve remaining bug
