### ISSUE TITLE
[feature] Stop rendering OpenGraph metadata unless the request Accept's an application/opengraph+html

### ISSUE THREAD

**Issue by SoniEx2** [superseriousbusiness/gotosocial#3008]
### Is your feature request related to a problem ?

Fedi link previews are openly recognized as a DDoS tool. By using content negotiation to render *only* OG metadata, we can save CPU cycles and render *more* OG metadata in the same amount of time, and also generate shorter responses, all in all lowering the effectiveness of fedi link previews as a DDoS tool. Plus, with content negotiation, a sysadmin can also straight-up reject OG requests instead of having to implement User-Agent rejection code for Mastodon, Akkoma, and whatever fedi implementations come out next week or next month or whatever. 

### Describe the solution you'd like.

Restricting link previews to the magic header value would encourage Mastodon and other link preview tools to use content negotiation for OpenGraph metadata. This would be a good first step towards solving the fedi DDoS problem.

### Describe alternatives you've considered.

We originally suggested using a new HTTP request header but the IETF was pretty adamant about how we should be using content negotiation for this issue. However, it is up to us to actually implement it.

**Comment by VyrCossont** [comment]
Nothing on earth uses this MIME type. I get literally zero Google results for `application/opengraph+html` and have never heard of such a scheme. This would break Open Graph previews for anything served from GtS, with no benefits.

**Comment by tsmethurst** [comment]
I've never heard of a gts instance being ddos'd in this way. If it's possible, and becomes an issue, we can look more closely at mitigating it, but it would be better to do that with more efficient throttling / caching of html, rather than baroque content types.

**Comment by SoniEx2** [comment]
you gotta push other software to care about it, make it so if they wanna show previews of GtS links, they should do the thing: https://socialhub.activitypub.rocks/t/using-content-negotiation-for-opengraph-metadata-mitigating-the-fedi-ddos-problem/4317

GtS itself doesn't show previews, so it isn't contributing to the problem.
