### ISSUE TITLE
[feature] Allow users to set `federated=false` on new statuses using an emoji shortcode

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#301]
In Glitchsoc you can make a post local-only by appending the `:eye:` emoji shortcode to the *end* of a post: https://glitch-soc.github.io/docs/features/local-only-toots/

In Hometown this is similar, but it uses the `:local_only:` emoji shortcode *anywhere* in the post: https://github.com/hometown-fork/hometown/wiki/Local-only-posting#the-local_only-emoji

We should, imo, use the `:local_only:` approach in GoToSocial, because it's more explicit.

**Comment by tsmethurst** [comment]
I added 'help wanted' to this because it's a fairly easy one to implement and maybe a nice intro feature for someone new to the codebase to work on :)

**Comment by mal0ki** [comment]
:eye: sounds more like sensitive/CW short code to me.

**Comment by daenney** [comment]
Given we closed the PR that implemented this in #1880, I'm going to close this feature request for now. Though it would seem useful to have a feature like this, doing it with an emoji isn't how we want to go about it in the end.

Vyr provided some thoughts on how we could have extensions to functionality that clients could discover in #1985. Once that shakes out into something, then we could implement the functionality in those terms.

As a general observation, many GtS instances are single-person or very small community. Though local-only could be useful for small community, for single-person instances it seems to not have a lot of utility, which may result in this not being used much in the first place.
