### ISSUE TITLE
[bug] Websocket-streamed statuses end up in the wrong timeline in pinafore.social

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#303]
If you have your local or federated timeline open in pinafore.social and you get a new status streamed in via websocket connection, the message ends up in whatever timeline you're currently looking at, regardless of whether it belongs on the home timeline, the local timeline, or the federated timeline. This behavior is fixed by a refresh, because then the app pulls statuses from the API again.

We should check here: https://github.com/superseriousbusiness/gotosocial/blob/main/internal/api/client/streaming/stream.go

And here: https://github.com/superseriousbusiness/gotosocial/tree/main/internal/processing/streaming

to make sure we're categorizing streamed messages correctly

**Comment by burakakca** [comment]
Isn't that the problem you're talking about?
![gtosocial-steaming-error](https://user-images.githubusercontent.com/56919004/154476433-b0383110-4c69-4b98-bb48-6c780f8ec6c5.png)

If it is how can i fix it
