### ISSUE TITLE
How to restore a suspended account on my server?

### ISSUE THREAD

**Issue by huabin** [superseriousbusiness/gotosocial#3039]
Hello guys,

I meet an issue, there're two accounts on my server(instance), and I suspended one, it looks like the following.

<img width="706" alt="SS" src="https://github.com/superseriousbusiness/gotosocial/assets/535675/b8a92eb4-9f9e-4c6a-89be-1565fb94cfd8">

How can I restore it? Thank you.

**Comment by daenney** [comment]
I think that's fixable with the CLI, `gotosocial admin account enabled --username <user>`.

**Comment by tsmethurst** [comment]
> I think that's fixable with the CLI, `gotosocial admin account enable --username <user>`.

That would only work on an account that was disabled with the cli, but in this case it's been suspended, which cannot be reversed (see screenshot).

![Screenshot_20240625-201421_Firefox](https://github.com/superseriousbusiness/gotosocial/assets/31960611/14b4819c-2bff-4bd6-88ca-2dbabac53149)

**Comment by huabin** [comment]
@tsmethurst

It's so weird that I can't restore, but I can search it from the client side.

<img width="1040" alt="SS" src="https://github.com/superseriousbusiness/gotosocial/assets/535675/071bcf41-0f68-42bf-b2b7-56d73309c7b9">
