### ISSUE TITLE
[bug] Subway Tooter issues

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#304]
Subway Tooter (https://github.com/tateisu/SubwayTooter) gets a 500 error when logging in.

Relevant logs:

```
time=2021-11-16T15:10:11Z level=info msg=[1.458397ms] Internal Server Error: wrote 154 bytes clientIP=REDACTED latency=1.458397ms method=POST path=/oauth/token statusCode=500 userAgent=SubwayTooter/4.7.3 Android/10
```

**Comment by tsmethurst** [comment]
test

**Comment by blackle** [comment]
should be fixed by https://github.com/tateisu/SubwayTooter/pull/195

**Comment by tsmethurst** [comment]
oh nice :) Can anyone test it? I can't remember who raised this in the first place :') Was it you?

**Comment by blackle** [comment]
I tested the fix I sent to the SubwayTooter project and it works.
