### ISSUE TITLE
[bug] avatars are not displayed in the correct format in phanpy

### ISSUE THREAD

**Issue by coxde** [superseriousbusiness/gotosocial#3040]
### Describe the bug with a clear and concise description of what the bug is.

Hello again,

I've opened a issue in Phanpy repo, but since it's possible related to GoToSocial, so I'd like to open a issue here again.

> I found out that avatars are not displayed in the correct format in the timeline (.jpg) while the original one are .png or .gif. BTW, they are displayed correctly in profile page.

### What's your GoToSocial Version?

0.16.0+git-f1cbf6f

### GoToSocial Arch

amd64 Docker

### What happened?

I found out that avatars are not displayed in the correct format in Phanpy (.jpg) while the original one are .png or .gif. They are displayed correctly in user's profile page.

### What you expected to happen?

They should be displayed as the original format, or at least without the weird background.

### How to reproduce it?

1. Go to the timeline in Phanpy
2. Find out that some users' avatars are with black background
3. Use browser dev tool to check avatars' format, they're .jpg instead of .png or .gif as in the original format

### Anything else we need to know?

The issue in Phanpy: https://github.com/cheeaun/phanpy/issues/579
I can't reproduce it on a Mastodon server, so maybe it's related to GoToSocial.

**Comment by tsmethurst** [comment]
For reference btw, the reason you don't see a similar issue on mastodon is because they use imagemagick (iirc) to reencode things into just a smaller/static version of their original format. We don't have that option in GtS -- and it's also a bit more expensive in terms of processing -- which is why we do things the way we do :P

**Comment by coxde** [comment]
Thanks for your detailed explanation! I hope they can introduce similar options like in pinafore.

**Comment by tsmethurst** [comment]
No worries :) Would it be alright if I closed this issue then? Or possibly convert it into a feature request for encoding thumbnails with transparency layers? Then we can keep track of it.

**Comment by coxde** [comment]
Well it'd be neat if you have the intention to consider such a feature request, feel free to do so!

**Comment by tsmethurst** [comment]
For tidyness I'll close this issue and link to it in a new one.
