### ISSUE TITLE
[bug] HTTP request header filtering doesn't work?

### ISSUE THREAD

**Issue by coxde** [superseriousbusiness/gotosocial#3047]
### Describe the bug with a clear and concise description of what the bug is.

Hiya today I set up the HTTP Request Header Filtering but it didn't work, maybe it's my configuration or it's a bug?

### What's your GoToSocial Version?

0.16.0+git-f1cbf6f

### GoToSocial Arch

amd64 Docker

### What happened?

I set `GTS_ADVANCED_HEADER_FILTER_MODE=block` in Docker environment and add some header blocks in the setting panel For example, I set `^.*Amazon.*$` as the Header Value Regex. Then I used [User Agent Switcher](https://github.com/ray-lothian/UserAgent-Switcher/) to test it and I faked my user agent as `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML\, like Gecko) Version/8.0.2 Safari/600.2.5 (Amazonbot/0.1; +https://developer.amazon.com/support/amazonbot)`. I tried to access my GoToSocial instance homepage but nothing happened.

### What you expected to happen?

I should be blocked with a 403 or so.

### How to reproduce it?

1. set `GTS_ADVANCED_HEADER_FILTER_MODE=block` in Docker environment
2. add some header blocks in the setting panel
3. faked user agent to match the blocked user agent

### Anything else we need to know?

My docker compose config:

```
environment:
      - TZ=UTC
      - GTS_HOST=gts.example.org
      - GTS_ACCOUNT_DOMAIN=example.org
      - GTS_TRUSTED_PROXIES=127.0.0.1/32,10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,::1,fc00::/7
      - GTS_DB_TYPE=sqlite
      - GTS_DB_ADDRESS=/gotosocial/storage/sqlite.db
      - GTS_ADVANCED_HEADER_FILTER_MODE=block
```

Example log:

`gotosocial  | timestamp="" func=server.init.func1.Logger.14.1 level=INFO latency="320.239µs" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML\, like Gecko) Version/8.0.2 Safari/600.2.5 (Amazonbot/0.1; +https://developer.amazon.com/support/amazonbot)" method=GET statusCode=200 path=/fileserver/*********/attachment/original/*********.jpg clientIP=172.19.0.3 requestID=********* msg="OK: wrote 11.5kiB"`

**Comment by tsmethurst** [comment]
It definitely does work. It might just be the env var not being picked up correctly though. I see we don't have a test for that particular variable. I'll check it out. In the meantime you can try setting it in a config.yaml file instead :)

**Comment by tsmethurst** [comment]
Hiya, I can't replicate the env var issue. Just checking, did you make sure to restart GoToSocial after setting the environment variable?

**Comment by coxde** [comment]
Hi, this is strange, I've restarted few times, and I also tested `config.yaml` instead of env, but still didn't work. Just to be sure, this is the right regex? And I can test the same regex if you can share yours.

![image](https://github.com/superseriousbusiness/gotosocial/assets/63153334/209556f2-9ee8-4091-ac3d-ed763692cdda)

**Comment by tsmethurst** [comment]
Oh, you've made a mistake. Header name has to be the name/key of the header, it's not a name for the rule. In your case the header name should be "User-Agent". Gonna close this since I believe this is just an understandable error :)

**Comment by coxde** [comment]
Oh silly me...
