### ISSUE TITLE
[bug] Answer to authorization of new application always 'scope "read"'?

### ISSUE THREAD

**Issue by chri2** [superseriousbusiness/gotosocial#3049]
### Describe the bug with a clear and concise description of what the bug is.

I tried to register an application like described in the documentation https://docs.gotosocial.org/en/latest/api/authentication/ . I tried the request for "Create a new application" with `"scopes": "read write"` and with `"scopes": "write"` and both time got the answer `Here's your out-of-band token with scope "read"`.

I couldn't check, yet, which rights I really have, but at least the message seems to be wrong.

### What's your GoToSocial Version?

0.16.0

### GoToSocial Arch

arm64 yunohost

### What happened?

see above

### What you expected to happen?

expected the answer to contain the scope I had requested.

### How to reproduce it?

see above

**Comment by tsmethurst** [comment]
Adding documentation for this. There's just a bit missing in the docs. I'll make a PR later today.
