### ISSUE TITLE
[bug] SignupURL does not redirect admin to account page

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#3054]
### Describe the bug with a clear and concise description of what the bug is.

It seems that the SignupURL in the current email template is formatted as: `https://<instanceURL>/settings/admin/accounts/<accountID>`, which did not change following the settings panel refactor. The correct URL should be: `https://<instanceURL>/settings/moderation/accounts/<accountID>`

### What's your GoToSocial Version?

main

### What happened?

The SignupURL in the email template is outdated and points to `https://<instanceURL>/settings/admin/accounts/<accountID>` instead of the updated `https://<instanceURL>/settings/moderation/accounts/<accountID>`.

### What you expected to happen?

The SignupURL in the email template should be updated to `https://<instanceURL>/settings/moderation/accounts/<accountID>`.

### How to reproduce it?

1. Setup a instance with SMTP enabled.
2. Register an account via the web form
3. Click the link inside the admin notification email and got redirected to a blank settings panel page

**Comment by tsmethurst** [comment]
Whoops, thanks :)
