### ISSUE TITLE
Compiled gts  issue "error creating dbservice: db migration error: sqlite3: disk I/O error"

### ISSUE THREAD

**Issue by suoko** [superseriousbusiness/gotosocial#3067]
### Describe the bug with a clear and concise description of what the bug is.

timestamp="03/07/2024 19:48:11.886" func=bundb.sqliteConn level=INFO msg="connected to SQLITE database with address file:sqlite.db?_pragma=busy_timeout%281800000%29&_pragma=journal_mode%28WAL%29&_pragma=synchronous%28NORMAL%29&_pragma=cache_size%28-8192%29&_txlock=immediate"
timestamp="03/07/2024 19:48:11.889" func=cache.(*Caches).Stop level=INFO msg="stop: 0xc000700008"
timestamp="03/07/2024 19:48:11.889" func=workers.(*Workers).Stop level=INFO msg="stopped delivery workers"
timestamp="03/07/2024 19:48:11.889" func=workers.(*Workers).Stop level=INFO msg="stopped client workers"
timestamp="03/07/2024 19:48:11.889" func=workers.(*Workers).Stop level=INFO msg="stopped federator workers"
timestamp="03/07/2024 19:48:11.889" func=workers.(*Workers).Stop level=INFO msg="stopped dereference workers"
timestamp="03/07/2024 19:48:11.889" func=server.init.func1.1 level=INFO msg="done! exiting..."
2024/07/03 19:48:11 error executing command: error creating dbservice: db migration error: sqlite3: disk I/O error (code=10 extended=4874)

### What's your GoToSocial Version?

latest

### GoToSocial Arch

amd64

### How to reproduce it?

Install ubuntu 14.04
git clone https://github.com/superseriousbusiness/gotosocial.git
scripts/build.sh
./gotosocial --config-path config.yaml  server start

**Comment by Fastidious** [comment]
Is Ubuntu 14.04 **not** a typo?

**Comment by tsmethurst** [comment]
This is the documentation about the code that's being returned: https://www.sqlite.org/rescode.html#ioerr_shmsize. Not sure what to make of this but it may point at some other issue: disk/space, io error, something like that.

**Comment by tsmethurst** [comment]
It could also be something peculiar to Ubuntu 24.04, though that would be quite surprising.

**Comment by tsmethurst** [comment]
Hi, does this issue continue to occur? If it was just some temporary thing and it's resolved now then I'll close it.

**Comment by tsmethurst** [comment]
Gonna close this for now unless someone else can reproduce it.
