### ISSUE TITLE
[bug] object of type person missing inbox

### ISSUE THREAD

**Issue by mro** [superseriousbusiness/gotosocial#3069]
### Describe the bug with a clear and concise description of what the bug is.

when dereferencing the key-id of signed http responses, gotosocial returns a sparse activitypub object declared of type `person`. But it has no `inbox` property and so can't be parsed.

somewhat related to #2961 

### What's your GoToSocial Version?

0.16.0

### What happened?

the returned object of type `person` lacks the `inbox` property.

### What you expected to happen?

a valid activitypub object

### How to reproduce it?

a signed get to https://social.nlnet.nl/users/gerben and then to the key id mentioned in there https://social.nlnet.nl/users/gerben/main-key namely.

**Comment by tsmethurst** [comment]
This is documented here: https://docs.gotosocial.org/en/latest/federation/http_signatures/#quirks Not a bug but a known quirk we'll fix at some point.

**Comment by mro** [comment]
@tsmethurst when do you plan to comply to AP in this regard?

**Comment by tsmethurst** [comment]
It's tracked here: https://github.com/superseriousbusiness/gotosocial/issues/1186

Not currently on the planning but hopefully some time within a year. It's not trivial to change this behavior without potentially breaking a bunch of other stuff.
