### ISSUE TITLE
[bug] turnoff autocapitalize and spellcheck for some input tags

### ISSUE THREAD

**Issue by coxde** [superseriousbusiness/gotosocial#3073]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

Hiya! Maybe this is more of a suggestion than a bug? Anyway, because some input tags don't set `autocapitalize=none` and `spellcheck=false`, when I use a virtual keyboard (on a phone for example), the auto capitalization and spell checking is really annoying. And those inputs don't really need capitalize and spell check (also a potential privacy issue). For example: username, domain, IP don't need those (and maybe more!).

![image](https://github.com/superseriousbusiness/gotosocial/assets/63153334/fc78550d-5282-4a4f-9c1a-5c23a55df699)

### What's your GoToSocial Version?

v0.16.0+git-f1cbf6f

### Browser version

Firefox 127.0.2

### Anything else we need to know?

MDN:

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

**Comment by tsmethurst** [comment]
Good idea
