### ISSUE TITLE
[feature] Options to control sections in Default Index Page

### ISSUE THREAD

**Issue by mohan43u** [superseriousbusiness/gotosocial#3076]
### Is your feature request related to a problem ?

The current Default Index page have Four sections

- About
- What Is This
- Register
- Client Apps

But there is no way to selectively display these sections, I think it will be good of we have control over which one of these sections should be displayed

### Describe the solution you'd like.

Introduce following Environment variables to selectively display sections in default index.

- GTS_DEFAULT_INDEX_SHOW_ABOUT_SECTION
- GTS_DEFAULT_INDEX_SHOW_WHAT_IS_THIS
- GTS_DEFAULT_INDEX_SHOW_REGISTER
- GTS_DEFAULT_INDEX_SHOW_CLIENT_APPS

### Describe alternatives you've considered.

Already there is a way to show single user's profile page `GTS_LANDING_PAGE_USER` but I think It serves a different purpose, I believe the current default index page helps to quickly launch `semaphore` and also helpful to introduce `Tusky` to anyone who visit the gotosocial page. These new options I proposed will help to fine tune the default index page.

### Additional context.

I already worked on my idea and have a code here

https://github.com/mohan43u/gotosocial/tree/default-index-options

I read `CONTRIBUTING.md` which said I should first open an Issue to discuss before opening pull request, so here I am.

**Comment by NyaaaWhatsUpDoc** [comment]
you can already make these changes you want by modifying the index template under web/template/index.tpl :)

**Comment by mohan43u** [comment]
> index template under web/template/index.tpl

How can I do it when I run under podman? isn't this file part of source code? I don't see any config option or command line option to do it easily, thats why I would like to see these options so that I can do

1. pull the docker image
2. set some environment variables to control the default index
3. run

**Comment by tsmethurst** [comment]
Mmm indeed... I don't think these options are something most people would ever touch tbh, so I'm gonna close this as "won't implement". I looked at your branch and it looks like you've got it solved for yourself already :)

If you want to do it by editing the template file, you can mount an edited file into the container at `/gotosocial/web/template/index.tmpl` using the same bind mount method described here for the config.yaml file: https://docs.gotosocial.org/en/latest/configuration/#mounting-in-container

**Comment by mohan43u** [comment]
got it. thanks for developing gotosocial.

**Comment by tsmethurst** [comment]
You're welcome! ^_^
