### ISSUE TITLE
[feature] S3 storage for media

### ISSUE THREAD

**Issue by LittleFox94** [superseriousbusiness/gotosocial#308]
I found some comments about planned S3 support but nothing seems to be here yet, so I thought creating an issue might be a good idea :)

Also, I'm working on it and just had my first image uploaded and successfully served again - but more discussion for that is probably better in the PR to follow :)

**Comment by NyaaaWhatsUpDoc** [comment]
I'd initially thought of doing this as an implementation of the `storage.Storage` interface passed to `kv.KVStore`, i'm interested to see how you implemented it :)

**Comment by LittleFox94** [comment]
Currently added a new package `internal/storage` with sub-packages `local` and `s3`, `local` using `KVStore` and `s3` building on top of minio client SDK (for now, but that's easy enough ^^).

This new package has an interface `Storage` which looks very much like the `kv.storage.Storage` one, but only has the methods actually used by GTS and also has a `URL(name string) (*url.URL, error)` so we can directly use S3 links instead of proxying the data through the server.

**Comment by tsmethurst** [comment]
Nice! Yes indeed, s3 support is something that seemed necessary right from the beginning, but none of us got around to working on it yet. Glad you're taking a look at it :)

**Comment by theSuess** [comment]
Hey there, I'm currently setting up my own instance and would love object storage support. Is this still being worked on?

If not, I'd go ahead and implement it based on the structure outlined in previous comments

**Comment by LittleFox94** [comment]
I don't currently have a working branch for this. Started again some days ago, but didn't really make progress so far.

One thing came up in a chat discussion: we cannot embed short-lived signed S3 URLs directly into posts but have to embed links pointing to GoToSocial and then forward to a short-lived signed S3 URL - keep this in mind :)
