### ISSUE TITLE
[bug] update configuration.media_attachments.supported_mime_types on the instance api endpoint

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#3098]
### Describe the bug with a clear and concise description of what the bug is.

With #3090 brings more media types into gts. Should we update the `configuration.media_attachments.supported_mime_types` part of `/api/v[12]/instance`'s response?

Currently the response is:
```json
"supported_mime_types": [
        "image/jpeg",
        "image/gif",
        "image/png",
        "image/webp",
        "video/mp4"
      ],
```
However it seems does not affect actual media processing though.

**Comment by tsmethurst** [comment]
I'll defer to @NyaaaWhatsUpDoc about what media types we can actually support now (and therefore what should be in that list).

**Comment by NyaaaWhatsUpDoc** [comment]
ah good idea! I'll update it when I'm back at a computer Sunday / Monday :)

**Comment by tsmethurst** [comment]
Closed by https://github.com/superseriousbusiness/gotosocial/pull/3107
