### ISSUE TITLE
[feature] Label automated accounts as “bot”, or similar

### ISSUE THREAD

**Issue by Fastidious** [superseriousbusiness/gotosocial#3132]
### Is your feature request related to a problem ?

No. It is not a problem per se, but bot accounts are not labeled as such while looking at their profiles with clients. 

### Describe the solution you'd like.

Bot, or automated accounts should be noted in their profiles as such. This is how Phanpy shows them:

![IMG_3459](https://github.com/user-attachments/assets/eb30e7ee-406f-414a-b737-1907332d0712)

### Describe alternatives you've considered.

NONE

**Comment by VyrCossont** [comment]
We have the internals and API for this already (`bot` param to `PATCH /api/v1/accounts/update_credentials`). Remaining work:

- Public web frontend: `profile.tmpl` should display a bot badge somewhere inside `.namerole`
- Settings web frontend: add a "Mark account as automated" checkbox in the "Visibility and privacy" section of the profile settings

**Comment by Fastidious** [comment]
I asked @cheeaun what Phanpy used to label this, and he write `bot: true`, and linked this: https://docs.joinmastodon.org/entities/Account/#bot

**Comment by VyrCossont** [comment]
Yes, as I said, we have the internals and API for this already. Phanpy logged into a GtS instance will already show remote bot accounts correctly. However, Phanpy can't *set* the bot flag on an account; it doesn't have a checkbox for that.
