### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by evandibona** [superseriousbusiness/gotosocial#315]
First off, I don't usually submit issues, so apologies in advances for any breaches in etiquette. 

My knowledge of Go is very limited, however, there seems to be some problem with the autocert part of the SSL initialization. I tried to get the certs myself and adjust the code accordingly, but there is something that I'm missing in the install/setup. 

So is there a good way to troubleshoot the process that autocert goes through? Or any recommendations for inserting the certs manually?

**Comment by ForestJohnson** [comment]
SSL_ERROR_RX_RECORD_TOO_LONG  sounds like protocol wires crossed.  Like the client thinks its speaking HTTPS but the server is speaking HTTP ? or something ??

We will need more information about how/where you set up GTS and how you are trying to access it.  It might also help if you could explain in excruciating detail the process you went through leading up to seeing this error.

**Comment by evandibona** [comment]
Damn that was a quick response! I'll wipe the VPS and document it this time.

**Comment by evandibona** [comment]
* Fresh VPS running Debian 10.
* Adjusted the hostname to match my domain name
* `mkdir -p /root/gotosocial/storage/certs`
* `cd gotosocial/`
* `wget https://github.com/superseriousbusiness/gotosocial/releases/download/v0.1.0/gotosocial_0.1.0_linux_amd64.tar.gz`
* `tar xzf gotosocial_0.1.0_linux_amd64.tar.gz`
* `rm *gz`
* `cp example/config.yaml .`
* `vim config.yaml`
* Changed *exactly* as described in [the docs](https://docs.gotosocial.org/en/latest/installation_guide/binary/)
* `./gotosocial --config-path ./config.yaml server start`
```
time=2021-11-19T22:02:59-05:00 level=info msg=connected to database
time=2021-11-19T22:03:00-05:00 level=info msg=MIGRATED DATABASE TO group #1 (20211113114307) func=doMigration
time=2021-11-19T22:03:00-05:00 level=info msg=created instance instance piedmontnonst.top with id 0196D9KQ2XKD84H4HJP3EY5YRV
time=2021-11-19T22:03:00-05:00 level=fatal msg=listen: listen tcp :80: bind: address already in use
```
* `netstat -ltnp`
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      760/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      734/exim4
tcp6       0      0 :::80                   :::*                    LISTEN      371/apache2
```
* `systemctl disable apache2; systemctl stop apache2`
```
Synchronizing state of apache2.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable apache2
insserv: warning: current start runlevel(s) (empty) of script `apache2' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `apache2' overrides LSB defaults (0 1 6).
Removed /etc/systemd/system/multi-user.target.wants/apache2.service.
```
* `./gotosocial --config-path ./config.yaml server start`
```
time=2021-11-19T22:09:05-05:00 level=info msg=connected to database
time=2021-11-19T22:09:05-05:00 level=info msg=there are no new migrations to run func=doMigration
time=2021-11-19T22:09:05-05:00 level=info msg=instance entry already exists
```
* Pull up firefox and try to access from my laptop:
```
Secure Connection Failed

An error occurred during a connection to www.piedmontnonst.top. Peer reports it experienced an internal error.

Error code: SSL_ERROR_INTERNAL_ERROR_ALERT

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…
```
* Tried a `reboot` this time to see if anything changes.
* `cd gotosocial/`
* `./gotosocial --config-path ./config.yaml server start`
```
time=2021-11-19T22:14:24-05:00 level=info msg=connected to database
time=2021-11-19T22:14:24-05:00 level=info msg=there are no new migrations to run func=doMigration
time=2021-11-19T22:14:24-05:00 level=info msg=instance entry already exists

```
* Same error as before.
```
Secure Connection Failed

An error occurred during a connection to www.piedmontnonst.top. Peer reports it experienced an internal error.

Error code: SSL_ERROR_INTERNAL_ERROR_ALERT

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…
```

At least it's consistent, but as I said before, I'm not really sure how to figure out what's going wrong.

**Comment by evandibona** [comment]
Forgot to put this server response in, after trying to load the page: 
```
2021/11/19 22:14:45 http: TLS handshake error from 71.76.209.85:54905: acme/autocert: host "www.piedmontnonst.top" not configured in HostWhitelist

```

**Comment by ForestJohnson** [comment]
This is interesting stuff. Thanks for posting the details.  I'm new to this project so I'd have to take some time to dig into it further. 

The first time I tried to connect to your server on port 80 I  got the normal HTTPS redirect : 

```
forest@thingpad:~$ curl http://www.piedmontnonst.top/
<a href="https://www.piedmontnonst.top/">Temporary Redirect</a>.


```

However the subsequent attempts I got connection refused: 

```
forest@thingpad:~$ curl -v http://www.piedmontnonst.top/
*   Trying 45.15.167.165:80...
* TCP_NODELAY set
* connect to 45.15.167.165 port 80 failed: Connection refused
* Failed to connect to www.piedmontnonst.top port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to www.piedmontnonst.top port 80: Connection refused

```

So I'm assuming you are mucking around with it right now? 

Based on what you are doing it really looks like it should work. It might be an issue that gotosocial has, I'm not sure what, though.  I would say the next steps would be to attempt to enable / increase the amount of logging that happens with regards to the Lets Encrypt ACME transaction and the TLS certificate setup in general

**Comment by evandibona** [comment]
Oh yeah, haha that explains a couple of connection attempts that threw me off. So I blew through my 5 weekly LetsEncrypt issuances this afternoon, but I had made a typo in that domain anyways. Just bought the spelling I wanted, "piedmontnons.top" and and fiddling trying to get it to work. 

One discovery I did make, is that autocert does try to connect to LetsEncrypt and do it's thing, but only after about 30 minutes of idling.

**Comment by ForestJohnson** [comment]
weird. Sorry it didn't seem to work.  I will say that what you are doing helps, trying to use the GTS project and hitting snags, its like a stone tumbling on the bottom of a river -- after some time, it will become smooth and round.   And when that happens it should work on the 1st try. But takes some banging around to get there.

**Comment by tsmethurst** [comment]
`time=2021-11-19T22:03:00-05:00 level=fatal msg=listen: listen tcp :80: bind: address already in use`

-- Where does that one come from? :thinking: 

Also, you're trying to access the `www` subdomain, so `www.piedmontnonst.top` which you've presumably set up to forward to `piedmontnonst.top`. The built-in letsencrypt sees a request coming in, but with a hostname it's not been configured for, so it rejects the request. If you try going to *just* `piedmontnonst.top`, without the `www.` then it should work. This is essentially because the built-in letsencrypt doesn't request wildcard certificates.

**Comment by evandibona** [comment]
tsmethurst , I think I get what you're saying. When I switched domains last night there was a typo in an A record, so I fixed that and now I'm getting the error below. 

```
time=2021-11-20T00:39:25-05:00 level=info msg=connected to database
time=2021-11-20T00:39:25-05:00 level=info msg=MIGRATED DATABASE TO group #1 (20211113114307) func=doMigration
time=2021-11-20T00:39:25-05:00 level=info msg=created instance instance piedmontnons.top with id 01P57KN6Q0QM6Z54H83RKQD79P
2021/11/20 04:27:07 http: TLS handshake error from 13.80.134.157:60840: tls: first record does not look like a TLS handshake
2021/11/20 05:36:33 http: URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed; see golang.org/issue/25192
2021/11/20 06:47:48 http: TLS handshake error from 109.234.153.134:19505: tls: first record does not look like a TLS handshake
2021/11/20 06:47:48 http: TLS handshake error from 109.234.153.132:49749: tls: first record does not look like a TLS handshake
2021/11/20 06:47:53 http: TLS handshake error from 109.234.153.130:6363: tls: first record does not look like a TLS handshake
2021/11/20 06:47:53 http: TLS handshake error from 109.234.153.134:6535: tls: first record does not look like a TLS handshake
2021/11/20 06:48:07 http: TLS handshake error from 109.234.153.134:46649: unexpected EOF
2021/11/20 06:48:07 http: TLS handshake error from 109.234.153.133:51243: unexpected EOF
```

**Comment by evandibona** [comment]
Thank you both for the help! After tweaking things back and forth, I set a port back to its default value and everything worked. 

It seems like what went wrong was my initial misunderstanding that I needed to manually set up the certs. Then from there I had to set everything to a new domain. Plus it took me awhile to realize that it takes about 20-30 minutes of waiting before I would get any debugging info from autocert, still not sure why that is. But the landing page is running with no https errors so thanks again!

**Comment by ForestJohnson** [comment]
This boils down to:  (at least IMO)

1.  Human users will always expect the www subdomain to automatically work.  My brother is a prime example of this, he always types  www before typing URLs I send to him,  and so if I don't handle www, he will tell me my website doesn't work.   So GTS should probably at very least attempt to set up the www as well, and warn the user if the DNS was not set up for the www.

2. The certificate issuance process should probably have more logging around it.

3. The documentation should explain exactly how the automatic  HTTPS process works from start to finish, probably with diagram(s)

**Comment by tsmethurst** [comment]
>  So GTS should probably at very least attempt to set up the www as well, and warn the user if the DNS was not set up for the www.

I disagree with this: imo it's not GoToSocial's responsibility to handle traffic to a domain it hasn't been configured for, and it doesn't make sense for it to try to request a certificate for `www.` if the admin hasn't explicitly set their domain as that.

If a user wants to configure their dns records to forward `www.example.org` to `example.org` that's fair enough, and very understandable, but then they should use some kind of routing solution for that (traefik, nginx, whatever), because it's not GtS' job.

> The documentation should explain exactly how the automatic HTTPS process works from start to finish, probably with diagram(s)

True! We could just link to letsencrypt's explanation and diagrams :) https://letsencrypt.org/how-it-works/

> we can do some research and try to figure out why these TLS errors are being logged even though its working

A lot of TLS errors get logged just because some random bot or scraper or whatever tries to access the server by IP address rather than by hostname, then you get errors like 'this doesn't look like a tls handshake' or `hostname not in whitelist` etc.

For customizing the logging, we can make an issue to pass a custom logger to the http server here: https://github.com/superseriousbusiness/gotosocial/blob/main/internal/router/router.go#L141

Anyway @evandibona  I'm going to close this issue now since you got things working :)
