### ISSUE TITLE
[bug - 0.16.0] POSTs to remote inboxes are being made with the generic "Go-http-client/2.0" user agent and not GoToSocial's

### ISSUE THREAD

**Issue by VirtualWolf** [superseriousbusiness/gotosocial#3156]
### Describe the bug with a clear and concise description of what the bug is.

HTTP POST requests made to a remote user's inbox URL from GoToSocial have their user agent string as the generic `Go-http-client/2.0` instead of `gotosocial/<VERSION> (<DOMAIN>)`.

### What's your GoToSocial Version?

0.16.0

### GoToSocial Arch

amd64 Docker

### What happened?

I've been playing around with GoToSocial to host my own instance and was going through and following various users from my main account. It's been working fine, but there is a user on one specific server who reported that she wasn't getting my follow request showing at all (on the GtS side it just showed as pending acceptance).

I did a bunch of poking around and contacted the server admin and he looked through his server logs, and it turns out that the request that GtS was making to his server to follow users has its user agent sent to the generic `Go-http-client/2.0` and thus was triggering his anti-scraper mechanisms so the request never actually made it to his Mastodon instance.

I've since played around more with the extremely minimal [activitypub-single-php-file](https://gitlab.com/edent/activitypub-single-php-file) as a remote server to test with, and I can confirm that _all_ POST requests that are made specifically to  `https://<REMOTE_URL>/inbox` don't have the user set correctly:

```
apache-1  | 172.19.0.1 - - [31/Jul/2024:10:59:58 +0000] "POST /inbox HTTP/1.0" 200 354 "-" "Go-http-client/2.0"
```

Favouriting, following, @-mentioning, they all show up in the Apache logs like the above.

### What you expected to happen?

GoToSocial should be using its own user agent for _all_ HTTP requests it makes.

### How to reproduce it?

Watch the Apache/Nginx access logs of a remote instance as you follow/favourite/@-mention a user from that remote instance from GoToSocial and you'll see the user agent appear as the generic Go one:

```
apache-1  | 172.19.0.1 - - [31/Jul/2024:10:59:58 +0000] "POST /inbox HTTP/1.0" 200 354 "-" "Go-http-client/2.0"
```

### Anything else we need to know?

I'd be happy to try to fix this myself, but I don't know Go at all... 😅 I poked through the codebase but wasn't able to follow the actual flow of code to figure out how the user agent _wasn't_ being set.

**Comment by tsmethurst** [comment]
We noticed this already yeah, it's already fixed on main :)

**Comment by tsmethurst** [comment]
That's always fun :D Since it's resolved on main, I'll close this issue, but thank you for opening it, as it's now trackable by other people having the same issue on 0.16.0 :)
