### ISSUE TITLE
[bug] Sensitive filter toggle button showing the <details> drop down arrow on Safari/Webkit browsers (CSS fix)

### ISSUE THREAD

**Issue by jwbjnwolf** [superseriousbusiness/gotosocial#3170]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

Another little bug time lol. So Safari browsers, still are showing the arrow drop down button that you have with `<details>` elements, which is what's being used for the sensitive filter/media spoiler toggle.

<img width="1105" alt="Screenshots on Safari of a image with the sensitive filter toggled on & off, showing the drop down arrow that is supposed to be hidden which is the case on other browsers but not Safari" src="https://github.com/user-attachments/assets/811f9965-42dc-4ed8-a375-90ff6fc79f8b">

### What's your GoToSocial Version?

v0.16.0

### Browser version

Safari browsers, both on iOS & macOS, maybe other webkit browsers such as Gnome Web too

### What happened?

When the sensitive filter is toggled hiding the media, the `<details>` toggle arrow is seen pushed to the right displaying over the media element. When it is toggled showing the media, aka the `<details>` element is toggled to be expanded, the toggle arrow is on the left above the image partly hidden by the hide/show eye toggle button.

### What you expected to happen?

Like on Firefox/Chromium browsers, that the `<details>` element's arrow is hidden, however it displays on Safari/Webkit based browsers.

### How to reproduce it?

Using Safari on macOS or iOS, go to a post in the web interface that contains media such as [one of the posts from the official GtS account containing media](https://gts.superseriousbusiness.org/@gotosocial/statuses/01J3ZM6N4VQ1NS60RHGAVVWMFC)), and you'll see the bug. Gnome Web may also be the same since it uses Webkit also).

## CSS Fix

Here's CSS to add to hide the arrow for Safari browsers:
```
.status .media .media-wrapper details summary::-webkit-details-marker {
  visibility: hidden;
}
```
Can on Safari see the fix in action on [my arootastic wolf gif post](https://wolfi.ee/@jase/statuses/01HM01QSHJ1NCJ3F8SM4C3NDEG) after adding the CSS to my custom CSS.

Did originally go with `display: none` though whether that'd cause anything in regards to accessibility I'm not sure, so I've opted for `visibility: hidden`. Visually does exact same effect.

**Comment by tsmethurst** [comment]
Ah thanks for this, will include it in next release.
