### ISSUE TITLE
[feature] Allow passing connection string directly in database configuration

### ISSUE THREAD

**Issue by winston0410** [superseriousbusiness/gotosocial#3172]
### Is your feature request related to a problem ?

At the moment, it is impossible to connect gotosocial to a specific schema in Postgres. This problem could be resolved, if the configuration accept a connection string or schema in the definition.

### Describe the solution you'd like.

I would like to be able to pass `db-dsn` in the configuration. If `db-dsn` is defined, other db connect related configuration fields should be ignored.

### Describe alternatives you've considered.

Offer a field `db-schema`, and allow user to define the schema there. This will be a easy fix, but `db-dsn` will be more flexible, as it allows user to define more fields.

**Comment by tsmethurst** [comment]
Hmm, is it possible to pass schema in a Postgres connection string? I don't see anything about it in [the docs](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS) unless I'm missing something (quite possible). Could you possibly link to some docs showing how a schema parameter would work?

**Comment by winston0410** [comment]
Sure, an example of passing schema through connection string would look like this, assuming you use `database/sql`

```
postgres://user:pass@localhost/prod_pg?search_path=gotosocial
```

Similar format for pgx:

https://github.com/jackc/pgx/issues/1013

And I have read the source, seems like we just need to change the logic here a bit? If you are happy with the `dsn` field, I can implement that in a PR.

https://github.com/superseriousbusiness/gotosocial/blob/b78be9fd4a0af55dfb38d15dd1bf253460244c2e/internal/db/bundb/bundb.go#L457-L474

**Comment by tsmethurst** [comment]
Closed by https://github.com/superseriousbusiness/gotosocial/pull/3178
