### ISSUE TITLE
[feature] *Steal this look* updating emojis 

### ISSUE THREAD

**Issue by LittleFox94** [superseriousbusiness/gotosocial#3179]
### Is your feature request related to a problem ?

many emoji packs are updated sometimes and in case of changed ones, the original artist might appreciate only the most recent version being used

### Describe the solution you'd like.

Building on the *Steal this look* feature, GoToSocial could (optionally) watch those posts for edits, automatically updating the emojis - this way we could define "emoji pack posts" to be a good way to distribute and keep emoji packs update.

Any settings done on the initial stealing would also be applied to those updates (e.g. the category, which is the only setting rn) and it should be configurable if the post should be watched for updates (default off) and probably also what should happen if emojis are deleted (ignore or actually delete), since that would modify existing posts.

### Describe alternatives you've considered.

Just not doing that, working with the API instead or just not update them - dunno, this is not an important feature for me, just a silly idea that might actually be nice

**Comment by tsmethurst** [comment]
Hrmn I don't think this is a very good way to keep emojis up to date. I'm not sure yet what would be "better", but the idea of someone being able to change a bunch of emojis on your instance just by changing a post doesn't sit right. I think it would be better to just support some (semi-)standard format for uploading emoji packs in zips or tars or whatever. So I'm gonna close this, but thanks for putting the idea on the radar.
