### ISSUE TITLE
Password Change API

### ISSUE THREAD

**Issue by evandibona** [superseriousbusiness/gotosocial#318]
I hate to be a bother again, but this one has me stumped. After bumbling around with the API for awhile, I got through the authentication with a code and then a token. The site ( https://piedmontnons.top/assets/account/ ) consistently makes the call for the account object, with the username and other things. But I'm stuck at trying to change the password. 

It seems that no matter how the request is framed it still returns a 404. There doesn't seem to be any good reason why that address would fail when the other one seems to work just fine. 

user: strawman@gmx.com
pass: ifIonlyhadabrain

Thanks in advance, this project is fantastic!

**Comment by tsmethurst** [comment]
Heya! Totally my fault :') I missed something when I was doing that user module code for changing passwords etc. I'll make a fix for it :)

**Comment by tsmethurst** [comment]
@evandibona the above pr should fix the issue ^^ It'll be included in 0.1.1, or you can try building from main and deploying again if you're up for it

**Comment by evandibona** [comment]
Haha no worries, I appreciate the fix. Works beautifully now!
