### ISSUE TITLE
[bug] Login in a new Instance "Code 400 Waiting for callback, but no ?code= provided in url."

### ISSUE THREAD

**Issue by sandboxgangster** [superseriousbusiness/gotosocial#3180]
### Describe the bug with a clear and concise description of what the bug is.

Im Setup a new Instance, the Login not Work on a Old Instance is that not a Problem same Config as the Old Instance (Domain chage).

"Code 400 Waiting for callback, but no ?code= provided in url."

Test whit the Git and Release its same.

### What's your GoToSocial Version?

GoToSocial v0.16.0+git-4697271

### GoToSocial Arch

arm64

### What happened?

Login page https://.../settings/user give me "Code 400 Waiting for callback, but no ?code= provided in url." 

Login not Work over the Web side

### How to reproduce it?

Go to Login Side on a new Instance

**Comment by tsmethurst** [comment]
Hiya, you need to just clear your cookies and try again :) There's likely something still in your browser cache.

**Comment by sandboxgangster** [comment]
Oh Thanks
