### ISSUE TITLE
[feature] Update old keys if checking signature fails

### ISSUE THREAD

**Issue by gabboman** [superseriousbusiness/gotosocial#3197]
### Is your feature request related to a problem ?

Imagine someone leaks on accident the users private keys. The only solution is to rotate them of course.
The problem is that there is no way to rotate keys without the old keys (wich, by the way, are already compromised). I am getting 401s in all endpoints

### Describe the solution you'd like.

If checking the http signature fails and the key is older than lets say 48 hours, force an update of the user to get the newer version of the keys

### Describe alternatives you've considered.

Since the incident happened more than a year ago, dming to every gts instance that I've interacted with is not viable

### Additional context.

I am an ok programmer I swear

**Comment by NyaaaWhatsUpDoc** [comment]
this would then mean that if the domain is compromised we would end up fetching and replacing the keys, and since there's no user input they'd have no way to know that it's compromised? i'm not really sure there's a way of doing this *automatically* without causing issues in the case of compromised keys :thinking:

**Comment by gabboman** [comment]
> this would then mean that if the domain is compromised we would end up fetching and replacing the keys, and since there's no user input they'd have no way to know that it's compromised? i'm not really sure there's a way of doing this _automatically_ without causing issues in the case of compromised keys 🤔

If a domain is compromised and someone deploys a fake instance I just need to wait another 48 hours and all is back to normal



> have you considered moving the domain you're on?

not a trivial thing to do.

As explained on matrix, my issue is that one of my endpoints leaked the field privateKey  of my users looong ago and the only obvious solution was to do a rotation of all keys

**Comment by NyaaaWhatsUpDoc** [comment]
> If a domain is compromised and someone deploys a fake instance I just need to wait another 48 hours and all is back to normal

exactly, that's a problem. after 48hrs our gotosocial instance would then begin federating with them again as normal, and our gotosocial user / admin would have no idea that they're actually federating with a compromised instance

**Comment by gabboman** [comment]
what in the case of reinstalling the software from scratch, its something dirty too but unfortunately it can also happen. make it a week let's say, a period long enough that the rightful owner can recover the domain. or a month.

**Comment by tsmethurst** [comment]
Just gonna add my thoughts to the above discussion:

I think this is a reasonable feature request to make, but to have such a rotation feature turned on by default would essentially make the http signature verification pointless; if your instance is just going to trust new keys unconditionally, then there's no point bothering with those keys in the first place.

The risk is that if someone from an instance running on example.org shuts down their instance, and lets the dns lease lapse, someone else can then buy example.org, run an instance there, and trivially imitate users from the previous instance, and have those users be trusted by any instances that example.org was previously federating with.

So I think if we were to introduce a setting like this, we'd have to a) put auto rotation on a very long cooldown, to disincentivize people imitating lapsed domains, and b) have this definitely turned off by default.

**Comment by tsmethurst** [comment]
Personally I don't mind reopening this and keeping it as a feature request to think about when we have time, but only with the above provisos taken into consideration. Even then I don't think this would necessarily solve your issue of "I had catastrophic data loss", because if we did implement this feature, I imagine most people would leave it on the default "off" setting, so you'd have to be manually asking people to refresh keys for your domain anyway.

**Comment by daenney** [comment]
It's not enough for GtS to implement this. You need to convince all other instances you're federating with to rotate your key. At least any instance that enforces HTTP signatures, like Mastodon in secure mode. We can maybe come up with a mechanism to make that work between GtS instances, but we can't exactly force that implementation on Masto, the Oma's, the Forkeys and the like.

Any kind of key rotation scheme, and the mechanisms behind it, would have to be agreed upon by the major implementers before we do anything. And it would take a lot of work to think through all the possibilities for misuse and design a threat model around this that everyone is comfortable with.

**Comment by gabboman** [comment]
> Any kind of key rotation scheme, and the mechanisms behind it, would have to be agreed upon by the major implementers before we do anything. And it would take a lot of work to think through all the possibilities for misuse and design a threat model around this that everyone is comfortable with.

The thing is that i did rotate the keys more than a year ago. And  mastodon accepted the new keys after not that long, less than a day. Same for akkoma. Misskey forks took a bit more but thats it.

**Comment by tsmethurst** [comment]
Anyway I think there's not much left to say in this conversation, and I defer to my fellow devs that this is not on the table for now.

In any case thanks for opening this request, now we have a record of it on the repo which is important + useful!

**Comment by gabboman** [comment]
> Hmm, it seems like a mischaracterization to call it harassment if you're just politely asking people to rotate keys because you made a mistake.
> 
> 
> 
> Re: other software types, I'd be curious to know more about how they handle rotation. If we were to implement something like this at some point (again, big "if"), then we'd have to have a look at how they do that, because it's quite surprising and a bit troubling that they so swiftly and automatically accept signatures from different keys 🤔

a bit over the top a bit but the point is that it should not be needed. I get that it was a "skill issue" on my side and that I am asking for a fix on yours, butt:

mastodon uses DNS as the source of truth.  wich makes sense: hacking a domain is not an easy feat compared to stealing ltt youtube or twitter.

maybe add a warning "hello the private key of this user has changed all posts will be cwd with this until you go to settings and do x y z" and even maybe link to this discussion
