### ISSUE TITLE
[feature] Landing page at /

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#32]
There should be a nice landing page at the root of the instance that shows:

* Some explanation about the instance (description) with instance header and profile images.
* Basic server configuration/software version.
* Number of users/number of statuses.
* Links to apps for using the instance (Tusky, Pinafore.social, etc)
* Instructions for registering.
* Link to GoToSocial source code.
* Etc.

This should be created as a template in the /web/template directory of the repository, which allows instance owners to overwrite it as they wish.

**Comment by tsmethurst** [comment]
Handled by @f0x52 in https://github.com/superseriousbusiness/gotosocial/pull/46

**Comment by 9cat** [comment]
where is the most  IMPORTANT  session :    registering ?
