### ISSUE TITLE
[feature] Customizable version string

### ISSUE THREAD

**Issue by clarjon1** [superseriousbusiness/gotosocial#3201]
### Is your feature request related to a problem ?

So as it turns out, certain libraries (looks over at Mastodon.py) throw a fit if unexpected characters show up in the version string or dont follow Masto's versioning exactly, as they attempt to parse the version string out.

### Describe the solution you'd like.

A configuration line that would, when populated, override the version string output by the server. When left blank or unconfigured, it would use the current output style when the version in api is enabled

### Describe alternatives you've considered.

There is a flag in Mastodon.py which can disable this check, but as the services I'm running into don't expose a way to disable this check from a user-level, I have to use other server software. I've also considering compiling the server with a manually changed version number but having to do that for each update seems tedious and annoying

**Comment by tsmethurst** [comment]
Hiya, did you check the config option here? https://github.com/superseriousbusiness/gotosocial/blob/6fe96a56112bb537e1d03ef73670c0388b4756a0/example/config.yaml#L401-L408 The idea of that option is to provide clients with a Mastodon-compatible version string. Did you try the mastodon.py libraries with that option enabled? If it doesn't work properly for all clients + libraries, I'd rather fix that than add another feature that manipulates the version string.

**Comment by clarjon1** [comment]
as mentioned in the first post, yes, that option is enabled -- the version string doesn't show up in the API triggering this particular issue otherwise!

And, the issue does not seem to be limited to just that one library, and I'd personally like to be able to bodge fix the issue myself rather than have to wait weeks/months for solutions that may or may not come from talking to those projects

If I have to recompile the gotosoc source code myself to fix it so i can post from automations designed for masto and dont see having to modify their code for non-masto services, i'll do it

**Comment by tsmethurst** [comment]
> as mentioned in the first post, yes, that option is enabled -- the version string doesn't show up in the API triggering this particular issue otherwise!

I reread your initial post a few times, but I don't see where you say that you've enabled the config option I mentioned. Can you confirm that you've got instance-inject-mastodon-version set to "true" in your GoToSocial config.yaml file? Could you please paste in here what version string is being returned from /api/v1/instance when that flag is set?

> And, the issue does not seem to be limited to just that one library, and I'd personally like to be able to bodge fix the issue myself rather than have to wait weeks/months for solutions that may or may not come from talking to those projects
> 
> If I have to recompile the gotosoc source code myself to fix it so i can post from automations designed for masto and dont see having to modify their code for non-masto services as worth their dev time, i'll do it
> 
> I've been getting the same type of initial response from those i've been reaching out to about this, not wanting to modify things for what everyone sees as an edge case -_-
> 
> other projects telling me to tell my server software dev to fix their version string formatting, you telling me to tell other projects to fix their string detection.
> 
> 🙃
> 
> (apologies for the bit of a rant i am just excessively frustrated at the moment at how things seem to be being responded to when i report this)

You've misread my response, I think. I'm not telling you to tell other projects anything. What I meant was that if our instance-inject-mastodon-version flag doesn't result in a version string output that's compatible with libraries and tools that are strict about versions, then we should fix the version string we output when that flag is set. I'd rather do that instead of adding another config option to GtS that lets you manipulate the version string in a different way.

**Comment by mirabilos** [comment]
In bullseye, you need the patch from <https://debr.mirbsd.org/repos/wtf/dists/bullseye/wtf/Pkgs/python-mastodon/python-mastodon_1.5.1-1.1.debdiff.xz>, but in bookworm, `python3-mastodon` should work with GtS as-is.

Example code, from Feediverse:

```
masto = Mastodon(
    version_check_mode="none",
    api_base_url=config['url'],
    client_id=config['client_id'],
    client_secret=config['client_secret'],
    access_token=config['access_token']
)

masto.status_post(postbody) # or: , visibility='public')
```

**Comment by tsmethurst** [comment]
Gonna close this now as I think it's just a duplicate of a feature we already have, and haven't heard anything in a month. @clarjon1 feel free to reopen if you have more to add :)
