### ISSUE TITLE
[docs] Update README.md from alpha -> beta when beta is out

### ISSUE THREAD

**Issue by neuhaus** [superseriousbusiness/gotosocial#3213]
The software seems to be under active development, yet the main README file contains this outdated sentence [ed by tobi: "We foresee entering beta around the beginning of 2024."] that makes it appear as if the project hasn't been updated in a while.

Someone who is in the know about the roadmap should update it. Thanks 🙇🏼‍♂️

**Comment by NyaaaWhatsUpDoc** [comment]
exciting!! (not that it is anything but a version tag name change, but still :p)
