### ISSUE TITLE
[bug] Metrics endpoint does not return correct Content-Encoding

### ISSUE THREAD

**Issue by gmemstr** [superseriousbusiness/gotosocial#3216]
### Describe the bug with a clear and concise description of what the bug is.

When looking at the `/metrics` endpoint, it appears that the browser attempts to render the gzip compressed data, rather than decompressing it. From digging into the response headers, the browser doesn't actually know that it's getting gzip data back, with a `content-encoding: identity` header rather than `content-encoding: gzip` which is what would be expected.

This can be confirmed by using `curl` without an `Accept-Encoding: gzip` header - this returns the metrics data as expected. Adding an `Accept-Encoding: gzip` header manually and piping into `gzip -dc` also returns the metrics data.

### What's your GoToSocial Version?

0.16.1-SNAPSHOT+git-c78c3d5

### GoToSocial Arch

arm64 Docker

### What happened?

Browser is unable to decompress gzip stream and instead renders it as is.

### What you expected to happen?

Metrics endpoint returns correct headers to identify response as gzip data.

### How to reproduce it?

Load `/metrics` endpoint.

**Comment by tsmethurst** [comment]
Thanks, this looks like a regression from 0.16.0, very strange :thinking: I'll go through and see what's changed.

**Comment by tsmethurst** [comment]
Ah it's because of a dependency update, prometheus is trying to do its own gzip now, and overwriting values from our gzip middleware: https://github.com/superseriousbusiness/gotosocial/pull/3210/files#diff-9b0fbb4e734fd51a74793baf89de863a2d1b56f02a713dd6e145a9a0b9eb79ce

**Comment by gmemstr** [comment]
Theoretically that *should* be disabled https://github.com/superseriousbusiness/gotosocial/blob/bef0dfc66cd7fd11d17fa1cb900d582071a8d5ba/internal/api/metrics/metrics.go#L35

**Comment by tsmethurst** [comment]
Yeah I saw that, unfortunately they also are now overwriting any "content-encoding" header you set with "internal" (ie., no compression) if you've not negotiated any compressions. Which is a bit annoying. I'll make a fix.

**Comment by gmemstr** [comment]
Huh, well that's unexpected and annoying - but thanks for taking a look! Looking forward to the fix :D

**Comment by tsmethurst** [comment]
> Looking forward to the fix :D

Same here :')

**Comment by tsmethurst** [comment]
Just after I fixed this on our side, Prometheus pushed a fix from their side :')
