### ISSUE TITLE
[feature] shared OIDC session storage

### ISSUE THREAD

**Issue by gmemstr** [superseriousbusiness/gotosocial#3217]
### Is your feature request related to a problem ?

I want to run multiple instances of the gotosocial binary for redundancy, but because the OIDC provider state/keys (or something similar?) is per-binary, it leads to invalid authentication flows.

### Describe the solution you'd like.

Ideally I would like to be able to store the OIDC state in an external, shared service like Redis/Redict/Valkey.

### Describe alternatives you've considered.

NONE

**Comment by NyaaaWhatsUpDoc** [comment]
this is currently impossible

please see: https://github.com/superseriousbusiness/gotosocial/issues/1749

**Comment by gmemstr** [comment]
@NyaaaWhatsUpDoc Totally understandable - I missed this issue which searching for something that existed. I'll close this up :)
