### ISSUE TITLE
[bug] - [Admin interface] Error upon pressing [enter] after typing a domain in the domain-block input field

### ISSUE THREAD

**Issue by PrivacyDragon** [superseriousbusiness/gotosocial#3220]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

Whenever I type a domain into the input field on the domain blocks page, and then press [enter], I get an error.
This error only occurs when using the [enter] key, so I am still able to add new domain blocks, but only by pressing the 'block {domain}' button with my mouse.

Whenever the error occurs, I have to refresh the page a bit and go to another settings tab first. 

I already had this error in the previous version of GTS, if I remember correctly.

### What's your GoToSocial Version?

0.16.0+git-f1cbf6f

### Browser version

LibreWolf 127.0.2-2

### What happened?

See Above

### What you expected to happen?

Upon submitting a domain using the [enter] key, the same as what happens when clicking the button to add a domain to the blocklist.

### How to reproduce it?

* Make sure to have admin access
* Go to the settings thing.
* Go to `Domain Permissions` > `Blocks`
* Enter a domain to block into the input field
* Press the enter key on your keyboard.
* Enjoy the error-message.

**Comment by tsmethurst** [comment]
Hiya, I just fixed this one on main yesterday, funnily enough: https://github.com/superseriousbusiness/gotosocial/pull/3218

So the fix will be in the next release. Workaround in the meantime is to just click on the button instead of pressing enter to submit the form.
