### ISSUE TITLE
[bug] Reply status to a deleted status return 404 for REST API methods

### ISSUE THREAD

**Issue by Rengyr** [superseriousbusiness/gotosocial#3226]
### Describe the bug with a clear and concise description of what the bug is.

When trying to delete a reply to a status that was already deleted, the REST API call fails with status 404 and JSON reply body: {"error":"Not Found"}.
Same thing happens when trying to favorite or do other REST API call with the reply status.

### What's your GoToSocial Version?

0.16.0+git-f1cbf6f

### GoToSocial Arch

amd64 binary

### What happened?

Getting 404 response from the REST API. For DELETE method the status is still in the GTS database.

### What you expected to happen?

Correct processing of the REST API call. Removing the status from the GTS database in case of DELETE method.

### How to reproduce it?

1. Post status
2. Post reply to the status
3. Delete the main status
4. Try to delete/favorite the reply status

### Anything else we need to know?

The reply status is fetched via `GET /api/v1/timelines/home?limit=20` when calling the REST API on the instance of the account and is stored in the GTS database. However, any direct REST API call with the reply status id fails with 404 (e.g. `POST api/v1/statuses/{status_id}/favourite`).

**Comment by tsmethurst** [comment]
Think there's a fix for this on main already :) So will be included in 0.17.0 iirc.

**Comment by Rengyr** [comment]
Okay, thanks !
Can close the issue then (or do what is your process for "bugs" with fix not yet being part of the release).

**Comment by tsmethurst** [comment]
I'll close it :)
