### ISSUE TITLE
[Federation/Smithereen] Reload actor object

### ISSUE THREAD

**Issue by SadmL** [superseriousbusiness/gotosocial#3229]
I'm not sure which presented categories it must be for this issue so I used custom one.

There is exists [Smithereen](https://github.com/grishka/Smithereen) ActivityPub software.
Before I can't subscribe to Smithereen accounts, see https://github.com/grishka/Smithereen/issues/77
Smithereen dev says https://github.com/grishka/Smithereen/issues/77#issuecomment-2308375661:
> GoToSocial probably expects `"manuallyApprovesFollowers": false` and assumes true if it's not present. I'll add that field to my actors.
> 
> You should still be able to follow Smithereen accounts, it'll just look like you sent a follow request that was instantly accepted (which is how following works in ActivityPub anyway).

and it didn't work for me.
Then https://github.com/grishka/Smithereen/issues/77#issuecomment-2308383064:
> I don't know how it works for GoToSocial, but you need to make it reload the actor object somehow. On Mastodon this can be done by pasting the origin URL (https://friends.grishka.me/danilax86) into the search.

I've reloaded my GoToSocial instance systemd service, nginx, used admin panel for accounts search (settings/moderation/accounts/search), also searching in [GoToSocial Docs](https://docs.gotosocial.org/) and various search engines, but no luck.

**Comment by NyaaaWhatsUpDoc** [comment]
if you wait 6hrs since you last fetched the account, on next fetch gotosocial will refresh the account. we put it on a cool down to limit unnecessary traffic most of the time. though most of the time accounts on servers will be kept up-to-date by sending each other Update Actor activities.

**Comment by SadmL** [comment]
It is possible to do manual reload via cli?
