### ISSUE TITLE
[feature/docs] Document `GTS_WAZERO_COMPILATION_CACHE` for caching pre-compiled WASM to disk

### ISSUE THREAD

**Issue by gmemstr** [superseriousbusiness/gotosocial#3233]
### Is your feature request related to a problem ?

When starting up the server binary, especially on lower power machines, the `precompiling WebAssembly` step can take a while, even if the version of the binary remains unchanged.

### Describe the solution you'd like.

It may be worthwhile to look at caching the compiled WASM to disk rather than just in memory, which can then be loaded into memory on subsequent starts. This could be to a directory in `/tmp` to that reboots clear out old versions automatically. A hash/commit/revision tag could be added to the cache file to ensure when upgrading the new version is compiled and placed on disk.

### Describe alternatives you've considered.

NONE

**Comment by tsmethurst** [comment]
You can do this by setting `GTS_WAZERO_COMPILATION_CACHE` to some directory :) (eg., `GTS_WAZERO_COMPILATION_CACHE=~/.cache/wazero`. We still need to document that env var.
