### ISSUE TITLE
[feature] Change the version of dependency "go-swagger/go-swagger"

### ISSUE THREAD

**Issue by HappyHacker123** [superseriousbusiness/gotosocial#3246]
### Is your feature request related to a problem ?

Currently `gotosocial` depends on `go-swagger/go-swagger@v0.31.0`. But project `go-swagger` may have retagged version v0.31.0, so the checksum from the code in github does not match the checksum saved in sum.golang.org as shown in this [issue](https://github.com/go-swagger/go-swagger/issues/3118). 
Consequently, when trying to download go-swagger directly, the following error will occur.
```
go: downloading github.com/go-swagger/go-swagger v0.31.0
go: github.com/go-swagger/go-swagger/cmd/swagger@v0.31.0: github.com/go-swagger/go-swagger@v0.31.0: verifying module: checksum mismatch
downloaded: h1:s/T8gKzyNAUMFMyTWew6Vz3+rpT2MYKQD6ez1FlkRrs=
sum.golang.org: h1:H8eOYQnY2u7vNKWDNykv2xJP3pBhRG/R+SOCAmKrLlc=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

### Describe the solution you'd like.

Bumping or downgrading the version of go-swagger/go-swagger .

### Describe alternatives you've considered.

NONE

**Comment by tsmethurst** [comment]
Oh that's annoying, thanks, I'll take a look.

**Comment by HappyHacker123** [comment]
Thanks for your quick reply! When trying to use gts, i try to add gts's dependencies in my go.mod and download them.
When trying to download go-swagger, the problem arise. And the following command can trigger the message.
```
GOPROXY=direct go get github.com/go-swagger/go-swagger@v0.31.0
```

**Comment by tsmethurst** [comment]
> When trying to use gts, i try to add gts's dependencies in my go.mod and download them.

I'm unclear on this part, can you go step-by-step? I just did the following in a `golang` Docker container to test building from fresh and it worked with no error message by just using the vendored dependencies:

1. `git clone https://github.com/superseriousbusiness/gotosocial`
2. `cd gotosocial`
3. `./scripts/build.sh`

**Comment by HappyHacker123** [comment]
Thank you for your response! I apologize for any confusion earlier. I fully understand your explanation, and I hadn't realized that GoToSocial uses the vendor directory. Following your suggestion to use the build.sh script, everything works as expected.

This issue is more of a reminder about the potential risks with github.com/go-swagger/go-swagger@v0.31.0, as go-swagger has retagged the v0.31.0 release. It would be advisable to upgrade go-swagger if possible :).

The risk would happen if you do the following steps.  
1. `git clone https://github.com/superseriousbusiness/gotosocial`
2. `cd gotosocial`
3.  `GOPROXY=direct go mod tidy`

**Comment by tsmethurst** [comment]
Ah fair enough, I'll just close it now then. We'll upstep go swagger whenever they release a new version.
