### ISSUE TITLE
[feature] failed login message should explain why in  certain circumstances. And in web browser it should be HTML instead of JSON

### ISSUE THREAD

**Issue by ForestJohnson** [superseriousbusiness/gotosocial#329]
When you try to log in to GTS,  if your email hasn't  been confirmed yet, or if your account has not been approved by an admin yet, it will say incorrect username and password, which is wrong. 

If you are trying to log in in the web browser (`/auth/sign_in`) it should display the login failed error message as HTML, not as JSON.

**Comment by ForestJohnson** [comment]
> for that one i'd say: check the email + password first, make sure it's correct, then show the 'your email address isn't confirmed yet' message
> otherwise just show a standard 'email address or password incorrect' error to prevent people inferring email addresses etc 

-t

**Comment by tsmethurst** [comment]
Closing this one now since it was implemented a while ago :)
