### ISSUE TITLE
[bug] SQL migrations not running

### ISSUE THREAD

**Issue by turtlegarden** [superseriousbusiness/gotosocial#3340]
### Describe the bug with a clear and concise description of what the bug is.

The SQL migrations do not seem to have run for one or another reason upon upgrading to 0.17.0 — all new columns and tables are missing and all old “dropped” columns are still existing.

### What's your GoToSocial Version?

v0.17.0-rc1

### GoToSocial Arch

x86_64 Binary

### What happened?

The new columns and tables were not correctly set up under the migrations. The server, upon starting after the migrations, bumped into errors and shut down.

### What you expected to happen?

The new SQL columns and tables would be correctly setup

### How to reproduce it?

Make a server on a 0.16.x version, post a few statuses, then upgrade to 0.17.0 rc.

### Anything else we need to know?

If it's not too much of a pain, could you please list the added/removed tables & columns & data types & defaults? I want to make sure my server works fully again :>

**Comment by tsmethurst** [comment]
I summarized the run migrations here, so you can try this and see if it helps:

https://gist.github.com/tsmethurst/f243cf59884cf893dfc138b600a54115
