### ISSUE TITLE
[bug/v0.17.0-rc1] Replies to unlisted post by local users return blank page in browser

### ISSUE THREAD

**Issue by xwyqi** [superseriousbusiness/gotosocial#3341]
### Describe the bug with a clear and concise description of what the bug is.

Replies to unlisted post by local users return a blank page in browser.

### What's your GoToSocial Version?

v0.17.0-rc1

### GoToSocial Arch

x86_64 docker

### What happened?

Unlisted replies by local user return a blank page when setting visibility level to Show Public and Unlisted posts.

### What you expected to happen?

Unlisted replies by local user should return content correctly.

### How to reproduce it?

Go to profile settings, set the visibility level of posts to show public and unlisted posts, and open the post link using web client.

**Comment by tsmethurst** [comment]
Thanks, I'll take a look. I tested this so not sure what happened there!

**Comment by tsmethurst** [comment]
Ah thank you, that's very helpful!
