### ISSUE TITLE
[feature] Add custom CSS for Instance Frontpage

### ISSUE THREAD

**Issue by S0yKaf** [superseriousbusiness/gotosocial#3348]
### Is your feature request related to a problem ?

You're able to add custom CSS for individual profiles but not for the instance front page itself.

### Describe the solution you'd like.

Implement a custom CSS field in the instance settings that works the same way as the custom CSS for profiles but that affects the front page.

This would also change the CSS for the `/about` and `/signup` page or any other instance related pages. Excluding the dashboard

### Describe alternatives you've considered.

Instance admins could potentially do this by manually editing the provided CSS files. However, it's not everyone who's comfortable doing  this. and a built-in setting would be more fun and accessible.

**Comment by tsmethurst** [comment]
Oh weird I could have sworn we had an issue open for this already. Thanks!
