### ISSUE TITLE
[bug/v0.17.0-rc1] Remote user pins disappearing after opening them (posts still exist though)

### ISSUE THREAD

**Issue by jwbjnwolf** [superseriousbusiness/gotosocial#3351]
### Describe the bug with a clear and concise description of what the bug is.

So was just speaking about [pins and bugs lol..](https://wolfi.ee/@jase/statuses/01J8JZTHN1VXQETRXPV5T0YRNB)

Bug I've just noticed, pinned posts of remote accounts are disappearing from the profile's pinned post list after opening said pinned post and looking back at the profile.

### What's your GoToSocial Version?

v0.17.0-rc1

### GoToSocial Arch

amd64

### What happened?

I was looking at (Goblin) Tobi's pinned posts and was getting confused of why are they suddenly disappearing after opening them, like as if Tobi was suddenly unpinning them as I was looking at them.. But I look at Tobi's web profile and they're still there. Meanwhile looking from my instance, Tobi's pinned posts are all gone now.

Then looking on other accounts from other instances I noticed the same was happening, that they were disappearing as soon as I open them (any remote instance software).

I couldn't though reproduce this between my secondary GtS instance (which runs on sub of same domain on same server), that my own couple pinned posts didn't disappear upon opening them from on my secondary instance.

I had before noticing this bug done a `VACUUM;` on the sqlite database, so I quickly tested my backup from before putting the vacuum over if the issue was still present. Yes, it happened on the backup too so that's not at fault.

### What you expected to happen?

Pinned posts to not vanish from the remote profile's pinned list after having viewed them.

### How to reproduce it?

If you're on v0.17.0-rc1 and this isn't just a my instance only doing this for some peculiar reason when no one elses is, then open a remote account's profile on your instance (so in Tusky or so), look at their pinned posts, then open one of them. Go back to their profile, look at their pinned posts again.. is the pinned post you looked at still there (after a refresh)?.

### Anything else we need to know?

Do not know if this log is useful as such, but is around the point of me opening a pinned post and it getting hidden.

```
Sep 25 02:33:52 web.howl.ee gotosocial[54025]: timestamp="25/09/2024 02:33:52.664" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://instance.tld/users/username/statuses/XXXXXXXXXXXXXXXX attempt=1 requestID=1111111111111111 pubKeyID=https://wolfi.ee/users/jase/main-key msg="200 OK"
Sep 25 02:33:52 web.howl.ee gotosocial[54025]: timestamp="25/09/2024 02:33:52.668" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://instance.tld/users/username/statuses/XXXXXXXXXXXXXXXX/replies?only_other_accounts=true&page=true attempt=1 pubKeyID=https://wolfi.ee/users/jase/main-key msg="200 OK"
Sep 25 02:33:52 web.howl.ee gotosocial[54025]: timestamp="25/09/2024 02:33:52.668" func=server.init.func1.Logger.13.1 level=INFO latency="248.458642ms" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0" method=GET statusCode=200 path=/api/v1/statuses/1X1X1X1X1X1X1X1X/context requestID=1111111111111111 msg="OK: wrote 54B"
Sep 25 02:33:52 web.howl.ee gotosocial[54025]: timestamp="25/09/2024 02:33:52.720" func=server.init.func1.Logger.13.1 level=INFO latency="396.696µs" userAgent="Mastodon/4.3.0-beta.1+glitch (http.rb/5.2.0; +https://instance.tld/)" method=GET statusCode=200 path=/users/jase/main-key pubKeyID=https://instance.tld/actor#main-key requestID=2222222222222222 msg="OK: wrote 548B"
Sep 25 02:33:52 web.howl.ee gotosocial[54025]: timestamp="25/09/2024 02:33:52.761" func=server.init.func1.Logger.13.1 level=INFO latency="941.57µs" userAgent="Mastodon/4.3.0-beta.1+glitch (http.rb/5.2.0; +https://instance.tld/)" method=GET statusCode=200 path=/users/jase pubKeyID=https://instance.tld/actor#main-key requestID=3333333333333333 msg="OK: wrote 1.57kiB"
Sep 25 02:33:52 web.howl.ee gotosocial[54025]: timestamp="25/09/2024 02:33:52.790" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://instance.tld/users/username/statuses/XXXXXXXXXXXXXXXX/replies?only_other_accounts=true&page=true attempt=1 pubKeyID=https://wolfi.ee/users/jase/main-key msg="200 OK"
Sep 25 02:33:53 web.howl.ee gotosocial[54025]: timestamp="25/09/2024 02:33:53.231" func=streaming.(*Module).readFromWSConn level=DEBUG streamID=918273645 username=jase requestID=4444444444444444 msg="finished websocket read"
Sep 25 02:33:53 web.howl.ee gotosocial[54025]: timestamp="25/09/2024 02:33:53.232" func=streaming.(*Module).writeToWSConn level=DEBUG streamID=918273645 username=jase requestID=4444444444444444 msg="error writing websocket ping: websocket: close sent"
Sep 25 02:33:53 web.howl.ee gotosocial[54025]: timestamp="25/09/2024 02:33:53.232" func=streaming.(*Module).writeToWSConn level=DEBUG streamID=918273645 username=jase requestID=4444444444444444 msg="error writing websocket message: websocket: close sent"
Sep 25 02:33:53 web.howl.ee gotosocial[54025]: timestamp="25/09/2024 02:33:53.232" func=streaming.(*Module).writeToWSConn level=DEBUG streamID=918273645 username=jase requestID=4444444444444444 msg="finished websocket write"
Sep 25 02:33:53 web.howl.ee gotosocial[54025]: timestamp="25/09/2024 02:33:53.232" func=streaming.(*Module).handleWSConn level=INFO streamID=918273645 username=jase requestID=4444444444444444 msg="closed websocket connection"
```

No idea if this is related as such but is only thing can pin point in logs with debug and db query logs enabled.

**Comment by tsmethurst** [comment]
Aha, you're absolutely right, well spotted! I can reproduce this. Will make a fix for 0.17.0 :) Thanks for reporting.
