### ISSUE TITLE
[bug/v0.17.0-rc1] example AppArmor policy causes errors with embedded ffmpeg and prevents loading remote avatars

### ISSUE THREAD

**Issue by remorae** [superseriousbusiness/gotosocial#3359]
### Describe the bug with a clear and concise description of what the bug is.

With the example AppArmor policy enabled, remote avatars fail to load for a newly federated user.

### What's your GoToSocial Version?

v0.17.0-rc1

### GoToSocial Arch

amd64 Binary

### What happened?

I recently set up a GoToSocial instance in v0.16.0 in allowlist mode. I enabled the [example AppArmor policy](https://github.com/superseriousbusiness/gotosocial/raw/main/example/apparmor/gotosocial) (after modifying it to look for the sqlite database in `/gotosocial`). The instance was not federated with any other instance until after upgrading to v0.17.0-rc1.

Today, after adding a few domains to the allowlist and federating with those instances, I signed in to https://semaphore.social and searched for a user I knew existed on each instance in order to follow them. Their avatars did not load.
After disabling the AppArmor policy and restarting GoToSocial, I was able to load avatars for new users, but not the ones I already searched for and tried to follow.

Relevant log output (hostname/domains/usernames changed for privacy):
```
Sep 26 17:04:25 hostname gotosocial[66287]: timestamp="26/09/2024 17:04:25.465" func=federation.(*Federator).AuthenticateFederatedRequest level=WARN requestID=wa04mbwj04000343jkhg msg="network race during https://example.com/users/foo handshake"
Sep 26 17:04:26 hostname gotosocial[66287]: timestamp="26/09/2024 17:04:26.685" func=federation.(*Federator).AuthenticateFederatedRequest level=WARN requestID=k63mmbwj04000kztrmd0 msg="network race during https://example.com/users/foo handshake"
Sep 26 17:04:27 hostname gotosocial[66287]: timestamp="26/09/2024 17:04:27.059" func=federation.(*Federator).AuthenticateFederatedRequest level=WARN requestID=yp44mbwj04000gzv3jeg msg="network race during https://example.com/users/foo handshake"
Sep 26 17:04:27 hostname gotosocial[66287]: timestamp="26/09/2024 17:04:27.102" func=media.(*ProcessingMedia).store.func1 level=ERROR requestID=pnx4mbwj0400080xs1wg msg="error(s) cleaning up files: error removing /tmp/gotosocial-2506606360_thumb.webp: remove /tmp/gotosocial-2506606360_thumb.webp: no such file or directory"
Sep 26 17:04:27 hostname gotosocial[66287]: timestamp="26/09/2024 17:04:27.103" func=dereferencing.(*Dereferencer).fetchAccountAvatar level=WARN requestID=pnx4mbwj0400080xs1wg msg="partially loaded attachment: processMediaSafeley: error loading media https://example.com/fileserver/01HMQNV2KPJXJ50EJ654EMBGE6/attachment/original/01J8JA385TH62SNC10TJ27J1TA.png: store: error generating image thumb: ffmpeg:  error running: module[] function[_start] failed: permission denied (recovered by wazero)\nwasm stack trace:..."
Sep 26 17:04:27 hostname gotosocial[66287]: timestamp="26/09/2024 17:04:27.331" func=media.(*ProcessingMedia).store.func1 level=ERROR requestID=pnx4mbwj0400080xs1wg msg="error(s) cleaning up files: error removing /tmp/gotosocial-1332422521_thumb.webp: remove /tmp/gotosocial-1332422521_thumb.webp: no such file or directory"
Sep 26 17:04:27 hostname gotosocial[66287]: timestamp="26/09/2024 17:04:27.331" func=dereferencing.(*Dereferencer).fetchAccountHeader level=WARN requestID=pnx4mbwj0400080xs1wg msg="partially loaded attachment: processMediaSafeley: error loading media https://example.com/fileserver/01HMQNV2KPJXJ50EJ654EMBGE6/attachment/original/01J8QEKHYYSN0KBWF02G46MY54.png: store: error generating image thumb: ffmpeg: error running: module[] function[_start] failed: permission denied (recovered by wazero)\nwasm stack trace:..."
```
Similar output occurred for the other user I tried to follow before disabling AppArmor.

### What you expected to happen?

I expected remote user avatars to load successfully.

### How to reproduce it?

1. Configure GoToSocial to run in allowlist mode.
2. Follow the steps to enable the example AppArmor policy listed at https://docs.gotosocial.org/en/latest/advanced/security/sandboxing/ under "AppArmor".
3. Sign in to the instance settings page in a browser as an admin account and add a new instance's domain to the allowlist.
4. In a front-end client, search for a user on said instance that has an avatar set. Their avatar will not load.

### Anything else we need to know?

Running on Debian 12, using SQLite for the database, via the systemd service as the 'gotosocial' system user.

I did not notice any issues with local user avatars, but my instance only has two accounts and I had already followed the non-admin account from the admin account.

**Comment by tsmethurst** [comment]
Ah thank you, we need to add `/tmp` and possibly `/dev/urandom` to apparmor
