### ISSUE TITLE
[bug/v0.17.0-rc1] ffmpeg/upload bug, error 422 unprocessable entity

### ISSUE THREAD

**Issue by cadusilva** [superseriousbusiness/gotosocial#3362]
### Describe the bug with a clear and concise description of what the bug is.

I was hoping someone would report this, but I guess it's a pretty particular case. When trying to upload a media file like an `opus` audio or `mp4` video, there's this error:

OPUS file (5 MB):
``` bash
statusCode=422 path=/api/v2/media errors="Error #01: StoreLocalMedia: error processing media: store: error cleaning metadata: ffmpeg: non-zero return code 1 ([ogv @ 0xae8a70] Unsupported codec id in stream 0\nCould not write header for output file #0 (incorrect codec parameters ?): Invalid argument\nError initializing output stream 0:1 -- \n\n)\n" msg="Unprocessable Entity: wrote 72B"
```

[MP4 video](https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4) (61 MB):
``` bash
statusCode=422 path=/api/v2/media errors="Error #01: StoreLocalMedia: error processing media: store: error draining data to tmp: reached read limit 128MiB\n" msg="Unprocessable Entity: wrote 72B"
```

There's enough disk space and reducing the max media size in the config file didn't help. The `/tmp` directory is not a partition or in-memory and there's 13 GB of free space.

Is this expected? Uploading a `mp3` file went fine.

Running Debian 12 `amd64`, GoToSocial `0.17.0-rc1+git-de72855`, binary version (but happened with Docker version too).

Thank you!

### What's your GoToSocial Version?

0.17.0-rc1+git-de72855

### GoToSocial Arch

amd64 binary

### What happened?

Uploading media files like `opus` audio or `mp4` video results in `ffmpeg` failing to process the file or a weird `error draining data to tmp` message.

### What you expected to happen?

Files converted as necessary and able to be successfully published.

### How to reproduce it?

Try to upload an `opus` or  `mp4` file and after sending the file, there's an `422` error.

### Anything else we need to know?

``` yaml
media-local-max-size: 128MiB
media-remote-max-size: 128MiB
```

**Comment by tsmethurst** [comment]
Thanks for reporting ^_^

**Comment by NyaaaWhatsUpDoc** [comment]
ah the big buck bunny :D

also yes thank you for reporting! will get right on this

**Comment by cadusilva** [comment]
Thank *you*, people!

So, I [downloaded this file](https://ia800203.us.archive.org/5/items/MusopenCollectionAsFlac/Bach_GoldbergVariations/JohannSebastianBach-01-GoldbergVariationsBwv.988-Aria.flac) ([via](https://archive.org/details/MusopenCollectionAsFlac)), converted it to `opus` using the [same software](https://github.com/kassoulet/soundconverter) and with the same settings as the file with the reported error, and then, this time... It worked.

I tried another file, this time the "Study and Relax" from [here](https://freepd.com/music/Study%20and%20Relax.mp3). Same software, same settings and the error 422 was back with the output'd `opus` file.

**Comment by cadusilva** [comment]
About the converter settings:

![Screen capture showing Opus selected as codec with 'insanely high' bitrate settings and 48 kHz resample](https://github.com/user-attachments/assets/caabd330-6334-42e7-8614-47d0a0c7d7bc)

**Comment by NyaaaWhatsUpDoc** [comment]
found and fixed :)

**Comment by NyaaaWhatsUpDoc** [comment]
thank you again for the detailed report @cadusilva !

**Comment by cadusilva** [comment]
Hooray! Thanks for the fix 😄
