### ISSUE TITLE
[bug] Interaction Policies Review Bug: User sees their own post instead of the reply

### ISSUE THREAD

**Issue by sgrigson** [superseriousbusiness/gotosocial#3366]
### Describe the bug with a clear and concise description of what the bug is.

I created a 'lockdown' user with reply control enabled.

I then commented with a user and was pretty happy with how it was working, however when you go to review the comments, this happens:

![Reply shows as from 'Daddy Lockdown' instead of the actual commenter](https://github.com/user-attachments/assets/c85ce4de-b69a-49ad-8a86-7039624d36b1)

It appears there's a small bug here where the OP is being quoted as the reply.

### What's your GoToSocial Version?

0.17.0-rc

### What happened?

I created a locked down user on one island server with reply control (approval required) for public posts, then made a public post.

With my other user (Oliphant) I replied to "Daddy Lockdown" saying "Didn't I just reply to this?" but what was shown was the screen above, not the comment.

![image](https://github.com/user-attachments/assets/c3fb3f6d-d487-4a34-b360-3e19e2da2025)

### What you expected to happen?

What should happen is that you'd see the pending comment itself, from the correct user.

### How to reproduce it?

Hopefully reproducing it should be trivial, based on the info above.

**Comment by tsmethurst** [comment]
Thanks for reporting! Already fixed this one on main so it'll be included in rc2 :)
