### ISSUE TITLE
[bug] images are rejected prematurely if descriptions are required

### ISSUE THREAD

**Issue by 68kmentat** [superseriousbusiness/gotosocial#338]
Pinafore and Tusky both upload the image to the server first, and then allow the user to write an image description. If the server is configured to require image descriptions, it rejects the image before the user is able to write one in these clients.

**Comment by tsmethurst** [comment]
Jotting this down here for when someone picks it up: it's related to the way that tusky and pinafore upload images. Normally when you upload an image in one of those apps, you upload the image *first*, which is a POST to `/api/v1/media` then you see a preview thumbnail, and you can edit it with a PUT to `/api/v1/media/:id`, which is where the description and focus are usually set. Then the status is finally submitted, with the media attachment as a parameter. For the description length stuff, we should probably check max characters on the initial media PUT and POST, and then check *minimum* characters on the submission of the status, *after* the user has been given the chance to edit their description.
