### ISSUE TITLE
[bug] last_status_at returns a date, not a datetime

### ISSUE THREAD

**Issue by untitaker** [superseriousbusiness/gotosocial#3418]
### Describe the bug with a clear and concise description of what the bug is.

https://docs.joinmastodon.org/entities/Account/#last_status_at

Mastodon returns a date here, not a datetime. In some programming languages (rust..) this makes a difference and leads to compatibility issues. I am not sure if you accept "compat" bugs with Mastodon API, but I thought I'd try my luck.

### What's your GoToSocial Version?

0.17-rc4

### GoToSocial Arch

amd64 docker

### What happened?

example output from gts:

```
        "last_status_at": "2024-10-11T10:56:48.000Z",
```

### What you expected to happen?

i'd have expected:

```
        "last_status_at": "2024-10-11",
```

### How to reproduce it?

I used the "/following" API in GTS, and parsed the result into a `chrono::NaiveDate` in Rust. That one will fail validation if the input is actually a datetime.

**Comment by tsmethurst** [comment]
Oh thanks, will change that.
