### ISSUE TITLE
[bug] Creating v2 filters fails if a filter with the same title already exists on a different account

### ISSUE THREAD

**Issue by fl4nn** [superseriousbusiness/gotosocial#3445]
### Describe the bug with a clear and concise description of what the bug is.

It seems that filter titles collide globally.

### What's your GoToSocial Version?

0.17.0

### GoToSocial Arch

amd64 binary

### What happened?

Scenario: a GTS instance with multiple users, User A creates a filter titled `AI`. Some time later User B tries to create a new filter and also wants to title it `AI`, the creation of the filter then fails.

In the GTS logs this error appears:
`Oct 15 21:52:31 gotosocial[698730]: func=server.init.func1.Logger.13.1 level=INFO latency="2.944949ms" userAgent="Tusky/26.2 Android/14 OkHttp/4.12.0" method=POST statusCode=409 path=/api/v2/filters clientIP=192.168.1.243 errors="Error #01: duplicate title, keyword, or status\n" requestID=2cyvv4cj04000kj416jg msg="Conflict: wrote 81B"`

### What you expected to happen?

The second user is able to create the filter even if another user already happens to have created a filter with the same title.

### How to reproduce it?

Set up two accounts on a GTS instance, create a filter as one user, then try to create a filter with the same title as the other user.

**Comment by tsmethurst** [comment]
Thanks! We've just gotta shuffle that filters table a bit I think. We can do this in a bug fix release :)
