### ISSUE TITLE
[feature] Support for Mastodon "trending" API style requests

### ISSUE THREAD

**Issue by jessienab** [superseriousbusiness/gotosocial#3446]
### Is your feature request related to a problem ?

No, this is a new feature request that does not currently exist in GTS as far as I can tell.

It could in theory be implemented client side, however it would appear most clients send this request to the server, given API availability.

### Describe the solution you'd like.

Support for the Trending API mechanism as described in Mastodon documentation. This mechanism provides a list of currently trending statuses, tags, and URLs, as found in the general/federated Fediverse of a server.

https://docs.joinmastodon.org/methods/trends/

Two in particular are the most common called by Mastodon apps:

1. Trending tags, https://docs.joinmastodon.org/methods/trends/#tags

2. Trending statuses, https://docs.joinmastodon.org/methods/trends/#statuses

At present, when apps request trending statuses or tags, a 404 is returned server side, and often a generic error is returned client (app) side.

Ex. Using Tusky for Android

```
timestamp="12/10/2024 18:14:11.042" func=server.init.func1.Logger.14.1 level=INFO l
atency="35.049µs" userAgent="Tusky/26.2 Android/14 OkHttp/4.12.0" method=GET status
Code=404 path=/api/v1/trends/statuses clientIP= errors="Error #01: Not
 Found\n" requestID=cbdwq0mj040012kg0c10 msg="Not Found: wrote 21B"
```
![376398990-d4db7711-8e73-4e2c-93dd-ab24844e8509](https://github.com/user-attachments/assets/f3f2cd4b-663d-4833-b71b-e5894141b571)

The only thing I as the end user do not understand, is where the trending posts are pulled from; if an instance is single user, would it poll federated servers for their most popular posts? Would it look at recently used tags to determine what's trending? I can't tell...

### Describe alternatives you've considered.

The alternatives would be to use another Mastodon based/API supported server, such as Mastodon, Chuckya, glitch-soc, etc. The other alternative is using a different instance that is running on aforementioned software (which I do anyway, I simply think it would be nice to have included in GTS).

### Additional context.

As this could in theory be a feature creep, I am simply opening this to generate a discussion, as I felt this was the best place given existing API documentation.

Thank you!

**Comment by tsmethurst** [comment]
Hiya! We're not really interested in implementing these trending features + endpoints any time soon (if at all), so I'll close issue as "not planned" but we can reopen it later if we change our minds.
