### ISSUE TITLE
[feature] Auto-embed links in posts

### ISSUE THREAD

**Issue by Hujgo** [superseriousbusiness/gotosocial#3451]
### Is your feature request related to a problem ?

It would be beneficial to have auto-embed for links to know the content at a glance.

### Describe the solution you'd like.

From another instance:
![image](https://github.com/user-attachments/assets/4b24ae8a-a703-4914-81a6-6d311fa70f3b)

From GoToSocial:
![image](https://github.com/user-attachments/assets/670481e7-b1b7-4b80-b60c-b7e6eec5ef89)

### Describe alternatives you've considered.

`NONE`

**Comment by tsmethurst** [comment]
Hiya! We already have an issue for this here -- https://github.com/superseriousbusiness/gotosocial/issues/1345 -- so I'm gonna close this as a duplicate. We'll get to it at some point (tm).
