### ISSUE TITLE
[bug] `/api/v*/instance` `domain` and `uri` properties conflict with Mastodon’s usage of those property names

### ISSUE THREAD

**Issue by daprice** [superseriousbusiness/gotosocial#3467]
### Describe the bug with a clear and concise description of what the bug is.

Mastodon uses the `uri` (in v1) and `domain` (in v2) properties for the domain name that gets added to account handles.

GoToSocial uses `uri` (in v1) for a link to the home page, and `domain` (in v2) for the domain where the API is hosted, with a separate `account_domain` property that serves the same purpose as Mastodon’s `domain`.

Mastodon API clients (in my case using the open source [TootSDK](https://github.com/TootSDK/TootSDK) library) that expect `uri` or `domain` to contain the account handle domain will have issues connecting to GoToSocial and/or displaying full account handles if a server is using separate domains for these.

### What's your GoToSocial Version?

0.17.0 (tested on various instances running this version listed on FediDB)

### What happened?

GoToSocial’s `uri` property in `/api/v1/instance` and `domain` in `/api/v2/instance` conflict with Mastodon’s properties of the same name.

### What you expected to happen?

Mastodon API compatibility as described in the [docs](https://docs.gotosocial.org/en/latest/#mastodon-api-compatibility)

### How to reproduce it?

call `/api/v2/instance` on a GoToSocial server

### Anything else we need to know?

I’m wondering if this is intended behavior so I can handle it appropriately in a client app I’m developing.

**Comment by tsmethurst** [comment]
Oh interesting, thanks, sounds like it might be a bug indeed.
