### ISSUE TITLE
[bug] Can't follow gotosocial

### ISSUE THREAD

**Issue by Hujgo** [superseriousbusiness/gotosocial#3475]
### Describe the bug with a clear and concise description of what the bug is.

When I look up your account @gotosocial@superseriousbusiness.org it's not able to find it.

### What's your GoToSocial Version?

v0.17.1

### GoToSocial Arch

Docker

### What happened?

Output:
```
{
  "timestamp": "22/10/2024 14:21:41.379",
  "func": "httpclient.(*Client).DoOnce",
  "level": "INFO",
  "method": "GET",
  "url": "https://gts.superseriousbusiness.org/users/gotosocial",
  "attempt": "1",
  "requestID": "1yv6scwj04000tnr6420",
  "pubKeyID": "https://fedi.ziqfm.com/users/hujgo/main-key",
  "msg": "401 Unauthorized"
}
```
```
{
  "timestamp": "22/10/2024 14:21:41.379",
  "func": "httpclient.(*Client).DoOnce",
  "level": "INFO",
  "method": "GET",
  "url": "https://gts.superseriousbusiness.org/users/gotosocial",
  "attempt": "1",
  "requestID": "1yv6scwj04000tnr6420",
  "pubKeyID": "https://fedi.ziqfm.com/users/hujgo/main-key",
  "msg": "401 Unauthorized"
}
```
```
{
  "timestamp": "22/10/2024 14:21:41.556",
  "func": "httpclient.(*Client).DoOnce",
  "level": "INFO",
  "method": "GET",
  "url": "https://gts.superseriousbusiness.org/users/gotosocial",
  "attempt": "1",
  "requestID": "1yv6scwj04000tnr6420",
  "pubKeyID": "https://fedi.ziqfm.com/users/hujgo/main-key",
  "msg": "401 Unauthorized"
}
```

### What you expected to happen?

Other instances are working fine.

### Anything else we need to know?

Location: India
I am able to access the profile from browser directly at https://gts.superseriousbusiness.org/@gotosocial
I'm using Cloudflare

Docker configuration
      GTS_LETSENCRYPT_ENABLED: "false"
      GTS_LETSENCRYPT_EMAIL_ADDRESS: ""
      GTS_ADVANCED_RATE_LIMIT_REQUESTS: 0
      GTS_WAZERO_COMPILATION_CACHE: /gotosocial/.cache

**Comment by tsmethurst** [comment]
Hiya, did you create your instance, look up the gts account, then wipe your db and start again, by any chance?

**Comment by Hujgo** [comment]
Ah, I'm guilty of that 😬 That was around 6 months ago though. I've followed accounts from mastadon.social, misskey.io, etc. before the db wipe, and I can still follow accounts on there. But I did have this issue the first time as well, gotosocial was one of the first accounts I wanted to follow.

**Comment by tsmethurst** [comment]
Got ya. I'll roll the keys for your domain on gts.superseriousbusiness.org :)

**Comment by tsmethurst** [comment]
There, you should be able to follow now!

**Comment by Hujgo** [comment]
Thank you!
