### ISSUE TITLE
[Wiki] GoToSocial Federation Status

### ISSUE THREAD

**Issue by SadmL** [superseriousbusiness/gotosocial#3476]
It is not is a issue actually, just an announcement. 🙃
I've created a Codeberg repo that contanis info about GtS federation capabilities with other Fediverse software.
https://codeberg.org/SadmL/gotosocial-federation-status

Can't promise that I'll maintain regularly it for long period, life is life, you know. I hope in worst case scenario I'll check it at least once per month.

Feel free to close it when you read it.

**Comment by tsmethurst** [comment]
Oh that's very neat, thank you ^_^
