### ISSUE TITLE
[bug] error getting status parent XYZ: sql: no rows in result set"

### ISSUE THREAD

**Issue by jessienab** [superseriousbusiness/gotosocial#3478]
### Describe the bug with a clear and concise description of what the bug is.

A user on my server is attempting to refresh their Home feed. They follow my GTS account, and my Wetdry.world account.

Following the upgrade to v0.17.x, they can't seem to refresh the home feed anymore.
Their client, IceCubes (iOS) reports a generic UI error:
![gts](https://github.com/user-attachments/assets/9ad856ba-5480-476c-9757-5de80238b623)

and on the server backend, I can see the following: 

```
timestamp="22/10/2024 14:38:51.743" func=timeline.(*Processor).PublicTimelineGet level=ERROR requestID=vh88ddcj04001te4fsm0 msg="error checking status visibility: isStatusPublicTimelineable: error getting status parent 01JA1R2ZSRYMKXWHF9R9XQ6MVB: sql: no rows in result set"

timestamp="22/10/2024 14:38:51.745" func=timeline.(*Processor).PublicTimelineGet level=ERROR requestID=vh88ddcj04001te4fsm0 msg="error checking status visibility: isStatusPublicTimelineable: error getting status parent 01JA1QWRJRNSDA4BSFWG4QQ6T6: sql: no rows in result set"

timestamp="22/10/2024 14:38:51.755" func=server.init.func1.Logger.13.1 level=INFO latency="143.499183ms" userAgent="Ice%20Cubes/2877 CFNetwork/1498.700.2 Darwin/23.6.0" method=GET statusCode=200 path=/api/v1/timelines/public clientIP=x requestID=vh88ddcj04001te4fsm0 msg="OK: wrote 4.62kiB"
```

However in checking the DB, I can see the above statuses exist, example:
![Screenshot from 2024-10-22 21-38-31](https://github.com/user-attachments/assets/ccc0f597-bbb9-4b35-bd17-739932b018c1)

More logs:
[2024-10-22-gts.txt](https://github.com/user-attachments/files/17483931/2024-10-22-gts.txt)

Not sure if this is related to: https://github.com/superseriousbusiness/gotosocial/issues/2460
or
https://github.com/superseriousbusiness/gotosocial/issues/1901

----

I have no issues with my GTS account on the server, using the Tusky client (Android).
I am not super active on Matrix, so just reporting here if this is an actual bug...

Just not sure how to resolve this outside of perhaps deleting and recreating the user's account that's having issues?

Or alternatively if this needs to be reported to IceCubes and not GTS?

Thank you!
Jessie

### What's your GoToSocial Version?

GoToSocial 3.5.3+0.17.1+git-8a93300

### GoToSocial Arch

amd64 Docker (Podman rootless)

**Comment by tsmethurst** [comment]
Hiya, could you ask the user to log out of Ice Cubes and log back in again? It could be a bug that was in 0.17.0 which is persisting. I believe the error logs you're seeing are a red herring, it's just GtS reporting that those statuses are omitted from the timeline response, since you still get 200 OK and some data back from the timeline query.

**Comment by CDN18** [comment]
I'm experiencing the same issue on one of my GTS instances (others are okay). I tried logging out and back into the account, but the timeline still doesn't load properly.

**Comment by tsmethurst** [comment]
With Ice Cubes specifically or with other clients as well? GtS v0.17.1?

**Comment by CDN18** [comment]
> With Ice Cubes specifically or with other clients as well? GtS v0.17.1?

Seems specific to ice cubes. My accounts don't have problems with FediText and moshidon.

For Gts version, I'm running GoToSocial 0.17.2-SNAPSHOT+git-d8a8386

**Comment by tsmethurst** [comment]
Given the above discussion I'm gonna close this for now, but I'll open it again if other users report the same issues so we can investigate properly.
