### ISSUE TITLE
[feature] method to trigger clean up of old media

### ISSUE THREAD

**Issue by f0x52** [superseriousbusiness/gotosocial#348]
as admin api call?
clean up media from disk, and remove references so it doesn't error

**Comment by tsmethurst** [comment]
Right now media is cleaned up at midnight every night (or not, if the admin has turned it off), but let's leave this issue open for the ability to trigger clean up media manually (via CLI probably) rather than waiting for the cron job to do it.

**Comment by tsmethurst** [comment]
We now have a function in the processor to trigger the cleanup: https://github.com/superseriousbusiness/gotosocial/blob/main/internal/processing/admin/mediaremoteprune.go

However we still need to expose an endpoint at something like `/api/v1/admin/media_cleanup` that can take a parameter for the number of days to keep media cached. This should then return the number of media entries that were pruned.

**Comment by tsmethurst** [comment]
So this task involves:

1. Creating an endpoint in [this package](https://github.com/superseriousbusiness/gotosocial/tree/main/internal/api/client/admin) to handle a POST to `/api/v1/admin/media_cleanup`. The request body should contain a field called `remoteCacheDays` to mirror the config.yaml variable `media-remote-cache-days`.
2. Having the new endpoint check for admin privileges (check one of the other admin functions for how to do this).
3. Having the new endpoint call the corresponding function in the processor, and return the number of pruned media entries.
4. Documenting the endpoint with Swagger annotations (can be copied + edited from one of the existing endpoints).
5. (Optional) Documenting the endpoint somewhere in the `admin` section of the docs (https://github.com/superseriousbusiness/gotosocial/tree/main/docs/admin).

**Comment by rscmbbng** [comment]
A function to remove remote accounts (+ their associated avatars & headers) that the software knows about but hasn't seen in a long time would be very helpful. This is separate from remote media and tends to accumulate quite rapidly over time.
