### ISSUE TITLE
v0.17.1 release notes: link to v0.17.0 directly

### ISSUE THREAD

**Issue by almereyda** [superseriousbusiness/gotosocial#3501]
The release notes for v0.17.1 contain a n important link to the v0.17.0 release notes. Unfortunately it only points to the list of all releases, with v0.17.0 scrolling down and to the next page over time.

- https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.17.1

The wrong link was probably copied due to the identical display of the top of the list of releases and of a single release above the fold.

For people who run into this upgrade now or later, it might be easier to discover the respective release notes, if they were linked directly.

- https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.17.0

Is it still possible to update the link?

**Comment by tsmethurst** [comment]
Oh thanks, fixed!
