### ISSUE TITLE
[bug] post counters should not include direct messages

### ISSUE THREAD

**Issue by codl** [superseriousbusiness/gotosocial#3504]
### Describe the bug with a clear and concise description of what the bug is.

Post counters on profiles and on the instance landing page count all posts, including direct messages. This seems questionable privacy-wise, you could infer how many direct messages someone is sending by monitoring how fast their post count is increasing vs how many posts you can actually see.

### What's your GoToSocial Version?

v0.17.1

### GoToSocial Arch

amd64 binary

### What happened?

I posted a direct message and my post count went up by 1 on my public profile, so did the global count on the landing page.

### What you expected to happen?

Post count does not go up.

### How to reproduce it?

Post a direct message to no-one.

### Anything else we need to know?

One could argue that private posts should also not be counted, or even unlisted posts. Idk about that but I am certain that direct messages should not be counted.

**Comment by tsmethurst** [comment]
Ah yes we should change this indeed, thanks :)

**Comment by Booklordofthedings** [comment]
Hi, id be willing to work on a fix for that if thats fine

The fix would likely be to edit the query in internal\db\bundb\instance.go: CountInstanceStatuses, to exclude everything thats also in internal\gtsmodel\conversation.go: ConversationToStatus

Potentially there should be version of that function that does a full count, but everything that currently calls it seems to be public facing in a way where we would rather like to hide it

**Comment by Booklordofthedings** [comment]
Didnt see that there actually is a post visibility field which can be used easier and should be faster than my initial idea
