### ISSUE TITLE
[bug] Upgrade from 0.17.1 to 0.17.2 leads to error on some clients

### ISSUE THREAD

**Issue by SadmL** [superseriousbusiness/gotosocial#3516]
### Describe the bug with a clear and concise description of what the bug is.

After upgrade from v0.17.1 to v0.17.2 GtS no more counts as "Mastodon" server for some mobile clients (tested on Moshidon, Mastodon official app, Pachli), so you can't login anymore with error

```
java.lang.NumberFormatFormalException: Expected an int but was 9223372036854775807 at line 1 column 
2534 path $.configuration.media_attachments.image_matrix_limit
```
Reverting back from v0.17.2 to v0.17.1 fixes issue

### What's your GoToSocial Version?

v0.17.1, v0.17.2

### GoToSocial Arch

amd64 Binary

### What happened?

image_matrix_limit in v0.17.1 - 16777216 changing into 9223372036854775807 in v0.17.2 that causes error

### What you expected to happen?

Normal login to client

### How to reproduce it?

Do upgrade from v0.17.1 to v0.17.2

### Anything else we need to know?

from /api/v1/instance
image_matrix_limit in v0.17.1 - 16777216 (no problems)
image_matrix_limit in v0.17.2 - 9223372036854775807 (can't login)

**Comment by tsmethurst** [comment]
We'll make another bugfix, seems some clients don't like such a large number so we'll use the maximum int32 size instead of the maximum int64 one :)
