### ISSUE TITLE
[bug] CORS / CORB issues with storage CDN

### ISSUE THREAD

**Issue by skpy** [superseriousbusiness/gotosocial#3526]
### Describe the bug with a clear and concise description of what the bug is.

Ever since migrating my media to DigitalOcean Spaces S3-compatible storage, I've been getting intermittent failures loading images. Different client apps exhibit different problems, but all clients have some kind of problem.

https://phanpy.social has the most success with media in posts, but has some problems with avatars:
![image](https://github.com/user-attachments/assets/9482c503-4725-4f26-a679-e7d569dbeaea)

phanpy.social shows CORS errors:
<img width="404" alt="Screenshot 2024-11-07 at 5 38 41 PM" src="https://github.com/user-attachments/assets/651678a2-79b8-4a7f-a60e-c1717f294428">

https://elk.zone is unable to properly display images and some avatars:
![image](https://github.com/user-attachments/assets/d23217d5-aa07-449a-b3c2-68ce493f4a7c)
![image](https://github.com/user-attachments/assets/458a8489-a721-4999-8fdc-2d6640dad04b)

elk.zone shows CORB problems:
<img width="393" alt="Screenshot 2024-11-07 at 5 37 48 PM" src="https://github.com/user-attachments/assets/874986ca-e87f-4549-97b0-5c469add4bb6">

iOS IceCubes app struggles, too:
![IMG_92C9105B8FAA-1](https://github.com/user-attachments/assets/27556758-8e1c-4b21-bde7-03f098c8fb34)

I don't know how to debug/triage an iOS app, but I'll guess it's CORS-related, too.

I see also that avatars are getting CORB problems on my site's direct view, too
![image](https://github.com/user-attachments/assets/ebed5435-d077-459c-b6a9-14d98cc3d12b)
<img width="404" alt="Screenshot 2024-11-07 at 5 41 59 PM" src="https://github.com/user-attachments/assets/e90d743c-2b23-487e-a77e-1f72fc1a8d6d">

### What's your GoToSocial Version?

0.17.2+git-e953d80

### GoToSocial Arch

Linux x64

### What happened?

CORS / CORB issues after I moved storage to S3-compatible.

### What you expected to happen?

I expected my images to display correctly.

**Comment by skpy** [comment]
When I opened this issue, I was using these values in my docker-compose.yml file:
```
      GTS_STORAGE_BACKEND: "s3"
      GTS_STORAGE_S3_ENDPOINT: "nyc3.digitaloceanspaces.com"
      GTS_STORAGE_S3_ACCESS_KEY: "<REDACTED>"
      GTS_STORAGE_S3_SECRET_KEY: "<REDACTED>"
      GTS_STORAGE_S3_BUCKET: "skippy-fedi"
      GTS_STORAGE_S3_REDIRECT_URL: "https://fedi.skippy.tech"
```

This morning, I commented out that last one -- `GTS_STORAGE_S3_REDIRECT_URL` -- and restarted the container. Images worked as expected.  My guess is that the redirect URL isn't being set for CORS in the way that the storage endpoint is?

**Comment by tsmethurst** [comment]
`No Access-Control-Allow-Origin header is present on the requested resource` suggests to me that the CDN fedi.skippy.tech requires a bit more configuration. You might try setting origin `*` and allowed methods GET here: https://docs.digitalocean.com/products/spaces/how-to/configure-cors/#control-panel

**Comment by skpy** [comment]
Just added. elk.zone and iOS IceCubes are showing broken images again.

elk shows CORB still:
<img width="394" alt="Screenshot 2024-11-08 at 7 57 50 AM" src="https://github.com/user-attachments/assets/7ac81eac-ef81-44c2-bbf9-384157d1debd">

This isn't important enough for me to spend much more time on. I'll forego the CDN config and talk directly to the bucket for now. For my small personal instance, it ought not be much of a problem.

Thanks!
