### ISSUE TITLE
[bug] Single character emoji shortcodes are not allowed

### ISSUE THREAD

**Issue by NoraCodes** [superseriousbusiness/gotosocial#3532]
### Describe the bug with a clear and concise description of what the bug is.

Shortcodes must be between 2 and 30 characters; 1 character codes should be supported.

### What's your GoToSocial Version?

1.16.0

### GoToSocial Arch

amd64 built from source via Nix

### Anything else we need to know?

I brought this up in the GTS Help matrix channel, to a positive response.

**Comment by tsmethurst** [comment]
Thanks for opening!
