### ISSUE TITLE
[query] Unable to see anyone's posts apart from 2

### ISSUE THREAD

**Issue by mannp** [superseriousbusiness/gotosocial#3553]
Hi there

I have recently (not sure when, likely 0.17.0) lost other people posts that I follow.

When I say lost, I mean their posts do not appear at all for me on tusky or web gui.

I am still following them, but their posts do not appear for me.

Two people/companies I follow I get their posts and reposts fine.

Not sure what I have set or unset, or changes that might cause this sort of behaviour?

Any pointers as to what I might look at to check further would be appreciated.

Thanks

**Comment by tsmethurst** [comment]
Couple questions to help narrow this down:

Was this after a migration (ie., updating to 0.17.0 from 0.16.x or lower)? Did the migration run successfully? Does your instance show any relevant logs when attempting to view posts? Is it just the home timeline that's affected, ie., can you still see posts on the profile of other accounts?

**Comment by mannp** [comment]
> Couple questions to help narrow this down:
> 
> Was this after a migration (ie., updating to 0.17.0 from 0.16.x or lower)? Did the migration run successfully? Does your instance show any relevant logs when attempting to view posts? Is it just the home timeline that's affected, ie., can you still see posts on the profile of other accounts?

Thanks for coming back to me.

I noted the large migration from 0.16.x to 0.17.0 and watched it. I did not see any errors and things appeared to be working normally.

There are no obvious errors unfortunately no.

I am getting a lot of these types of messages, with whom the users I do not know.

`Nov 21 11:56:01 server gotosocial[2787]: timestamp="21/11/2024 11:56:01.528" func=dereferencing.(*Dereferencer).dereferenceAccountStats level=WARN msg="couldn't count followers for @Wendy@mastodon.nl: dereferenceCollection: error dereferencing https://mastodon.nl/users/WendySchuchmann/followers: Dereference: GET request to https://mastodon.nl/users/WendySchuchmann/followers failed: status=\"403 Forbidden\" body=\"{\"error\":\"Forbidden\"}\""`


The instance has two accounts, 1 personal, 1 admin, and it is federating with 1366 other instances, with 144 blocked domains from a mastodon blocking list, but that has been used from the start and I previously had no issues.

I am following approx 50 others, a mixture of companies and people and only tailscale and matrix posts appear normally on my timeline. None of the other 48 appear at all.

**Comment by tsmethurst** [comment]
If you're getting `403 Forbidden` when your instance tries to fetch from other instances that means you've been blocked or forbidden for some other reason, or the account has been deleted or the instance is running in allowlist now, or whatever else. For example I notice that `https://mastodon.nl/@WendySchuchmann`, when opened in the browser, doesn't show the user's profile. Have the other accounts posted recently? Bear in mind you won't see old posts from those accounts from *before you started following them* because they were never delivered to your instance.

**Comment by mannp** [comment]
Going to close this as using different android clients I managed to see all the missing posts.

Not sure if its the official mastodon client for android that I was using.

Swapped and now made progress.

Thanks for your inputs.
