### ISSUE TITLE
[feature] Add endpoint `PUT /api/v1/statuses/{id}`

### ISSUE THREAD

**Issue by fnando** [superseriousbusiness/gotosocial#3555]
### Is your feature request related to a problem ?

Looks like `PUT /api/v1/statuses/{id}` is not implemented, which prevents posts from being edited.

### Describe the solution you'd like.

It'd be great if `PUT /api/v1/statuses/{id}` was added, so we could edit posts.

### Describe alternatives you've considered.

NONE

### Additional context.

Mastodon endpoint: https://docs.joinmastodon.org/methods/statuses/#edit

**Comment by tsmethurst** [comment]
Gonna close this as a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/1990, which is being worked on at the moment.
