### ISSUE TITLE
[feature] add stub for /api/v1/accounts/{id}/featured_tags

### ISSUE THREAD

**Issue by ptrcnull** [superseriousbusiness/gotosocial#3562]
### Is your feature request related to a problem ?

it's been already requested in #1419, but it looks like the wrong endpoint was implemented, and the issue got closed. marking this as a feature request, because while it doesn't break anything for me, masto-fe shows a toast of "404 Not Found" every time i open someone's profile, so it would be nice to at least stub it out

### Describe the solution you'd like.

#1420 but for `/api/v1/accounts/{id}/featured_tags`

### Describe alternatives you've considered.

NONE

**Comment by tsmethurst** [comment]
Sure, this is an easy fix :)
