### ISSUE TITLE
[bug] Not federating? 

### ISSUE THREAD

**Issue by yetzt** [superseriousbusiness/gotosocial#3585]
### Describe the bug with a clear and concise description of what the bug is.

I've set up an instance on my own server, following the documentation (bare metal, nginx reverse proxy, split-domain deployment) on a domain that was never before used for anything activitypub. There are no filters or firewalls in front and DNS is working.

After setting up gotosocial i followed another account of mine on another server (mastodon) and also imported the accounts i follow with that other account via csv import. 

Nothing is happening: I can't see posts or replies and i can't follow people. Curiously, i can see replies to a post from the other account and see the account following other accounts as well. I have the impression gotosocial is sending but not receiving. I have carefully read the documentation, scoured recent github issues and examined logs, but i can't figure out what the cause might be.

### What's your GoToSocial Version?

v0.17.3

### GoToSocial Arch

Linux x86-64/AMD64 Binary

### What happened?

As described, federation appears not to be working: I can't see other posts (except for one year-old message from a wordpress blog) or follow people (except for four accounts that use i believe wordpress). I can't see anything suspicious in the logs or in the webserver logs, but my understanding of activitypub is limited.

### What you expected to happen?

The opposite.

### How to reproduce it?

nginx:
```
server {

        listen [::]:443 ssl http2;
        listen 443 ssl http2;

        server_name social.yetzt.me;

        ssl_certificate /etc/letsencrypt/live/social.yetzt.me/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/social.yetzt.me/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/social.yetzt.me/fullchain.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/nginx/dhparam.pem;
        ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
        ssl_ecdh_curve secp384r1;
        ssl_session_timeout  10m;
        ssl_session_cache shared:SSL:10m;
        ssl_session_tickets off;
        ssl_stapling on;
        ssl_stapling_verify on;
        resolver 9.9.9.9 1.1.1.1;
        resolver_timeout 5s;
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header Content-Security-Policy "default-src 'self'; img-src 'self' blob: data: https:; script-src 'self'; style-src 'self';";

        keepalive_timeout 70;
        client_max_body_size 40M;

        charset utf-8;
        gzip_static on;
        brotli_static on;

        access_log /home/gotosocial/access.log main;
        error_log /home/gotosocial/error.log warn;

        location /.well-known/acme-challenge {
                root /var/www;
        }

        location / {
                proxy_pass http://127.0.0.1:21808;
                proxy_set_header Host $host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

        location ~ /\.git/ {
                deny all;
        }

        location ~ /\.ht {
                deny all;
        }

}
```

non-default config:
```
log-level: "debug"
landing-page-user: "yetzt"
host: "social.yetzt.me"
account-domain: "yetzt.me"
bind-address: "127.0.0.1"
port: 21808
db-type: "sqlite"
db-address: "/home/gotosocial/gotosocial.sqlite"
instance-languages: ["de", "en"]
instance-inject-mastodon-version: true
media-description-min-chars: 1
media-remote-cache-days: 30
media-cleanup-from: "04:00"
storage-local-base-path: "/home/gotosocial/storage"
statuses-max-chars: 4096
statuses-poll-max-options: 8
statuses-poll-option-max-chars: 128
letsencrypt-cert-dir: "/home/gotosocial/storage/certs"
letsencrypt-email-address: "<redacted>"
smtp-host: "<redacted>"
smtp-port: 587
smtp-username: "<redacted>"
smtp-password: "<redacted>"
smtp-from: "<redacted>"
smtp-disclose-recipients: true
```

redirects for `./well-known/{webfinger|nodeinfo|host-meta}` are set up.

### Anything else we need to know?

The instance in question is `social.yetzt.me` for the domain `yetzt.me`

(I don't know if this is a bug or if i've overlooked something that is obvious to anyone else, but i would appreciate any help)

**Comment by yetzt** [comment]
Never mind: i figured out i somehow managed to create the account with `http` urls instead of `https`. I guess i can take it from here.

**Comment by tsmethurst** [comment]
Was just about to say that yeah. Did you set `protocol` to `http`, create the user, and then change it to `https` or something?

**Comment by yetzt** [comment]
i think i had set it to http at first since i expected it to be the correct setting with the reverse proxy, but then set it back after noticing the web frontent trying to load resources via http. i must have created the account when the setting was wrong. 

i've replaced the http links in the accounts table, which appears to have fixed the symptoms so far. i don't understand activitypub well enough to know what other consequences this might have caused, but i will observe.
