### ISSUE TITLE
[bug] invalid config: host must be set when generating local storage paths

### ISSUE THREAD

**Issue by thestfndev** [superseriousbusiness/gotosocial#3603]
### Describe the bug with a clear and concise description of what the bug is.

When running the command to generate storage paths, exactly as [described in the documentation](https://docs.gotosocial.org/en/latest/admin/backup_and_restore/) under Borgmatic, I got an error, and the storage paths were not generated correctly.

The command that I run:

```
./gotosocial admin media list-attachments --local-only | /gotosocial/media-to-borg-patterns.py /gotosocial/storage
```

The output:
```
R /gotosocial/storage
2024/12/07 07:40:37 error executing command: invalid config: host must be set
- /gotosocial/storage/*
- 
``` 

### What's your GoToSocial Version?

0.17.3

### GoToSocial Arch

amd64 binary

### What happened?

As in the bug description, I tried to generate paths for Borgmatic exactly as in the documentation. 
The storage path in my config.yml file is absolute.
The host variable is set in my config.yml file.

### What you expected to happen?

I expected the storage path patterns for Borgmatic to be generated successfully.

### How to reproduce it?

Try generating the storage patterns as described in the documentation.

**Comment by tsmethurst** [comment]
Oh right, this is just a documentation issue I think. You'll have to point GoToSocial to your config yaml file.

Can you try:

```bash
./gotosocial --config-path ./config.yaml admin media list-attachments --local-only | /gotosocial/media-to-borg-patterns.py /gotosocial/storage
```

**Comment by thestfndev** [comment]
It works now, thank you! I'll make a PR with an update to the documentation if that's ok.

**Comment by tsmethurst** [comment]
That would be great, thank you! :)
