### ISSUE TITLE
Use a Pleroma-compliant instance version

### ISSUE THREAD

**Issue by alexgleason** [superseriousbusiness/gotosocial#382]
Under GET `/api/v1/instance`, Pleroma returns a version like this:

```
"version": "2.7.2 (compatible; Pleroma 2.4.51-1156-gb718f477-gleasonator)"
```

I suggest GoToSocial's look like this:

```
"version": "2.7.2 (compatible; GoToSocial 0.1.1-ab316d2)"
```

This has several advantages:

1. You supply the **Mastodon** version GoToSocial is compliant with first. This allows us to understand the featureset we're working with.
2. It identifies itself as GoToSocial specifically, so we can provide special support for GoToSocial.
3. It keeps the GoToSocial version separate from the Mastodon API compatibility version.

I've gotten basic support for GoToSocial implemented in Soapbox FE here: https://gitlab.com/soapbox-pub/soapbox-fe/-/merge_requests/1029

For now I had to fall back on a limited featureset with GoToSocial, but with this extra information I can fine-tune the features we expose.

Take a look here: https://gitlab.com/soapbox-pub/soapbox-fe/-/blob/develop/app/soapbox/utils/features.js

We parse the `version` string and use if for feature detection, toggling on or off certain parts of the UI depending on whether the backend supports it.

**Comment by tsmethurst** [comment]
Responded via email.
