### ISSUE TITLE
[feature] GtS CLI: dump and restore the instance key

### ISSUE THREAD

**Issue by igalic** [superseriousbusiness/gotosocial#387]
## problem:

Currently `gotosocial` has no tooling to administrate some key-components of an instance.
The federation key of an instance, once exchanged, is usually cached locally at remote instances.
If that key gets "lost" and admin would need to contact other instance admins to re-initiate federation, because ActivityPub doesn't provide a way to re-negotiate such a key.

## work around:

fiddle around in the database.?

## proposed solution:

```
gotosocial admin instance dump [component|name|like|key|users|etc…|or: all] --path
```

This could then be important with the already existing:

```
gotosocial admin import /path/to/key.dump
```

**Comment by norayr** [comment]
i just opened similar issue in socialhome issue tracker: https://gitlab.com/jaywink/socialhome/-/issues/616

socialhome also has troubles federating and even searching for gotosocial users.

logs at the link above.

it is likely to be a gotosocial issue.

**Comment by tsmethurst** [comment]
I believe this has been closed now by the `admin export` and `admin import` functions, which allow you to export a JSON of all local accounts etc, including their private + public keys.

Just for clarity's sake, it's a bit of a misconception that there's one instance key that handles HTTP signatures for federation. GoToSocial has an instance account that does some tasks, which has a private/public key pair, but each user (non-machine, non-instance) account also has its own keypair, which is used for signing outgoing messages sent on behalf of that account. In other words there's no such thing as "The federation key of an instance". When doing a backup, the instance account keypair *AND* the individual account keypairs should all be backed up.

Anyway! I will mark this as resolved :)
