### ISSUE TITLE
[feature] GtS CLI: list local users

### ISSUE THREAD

**Issue by igalic** [superseriousbusiness/gotosocial#388]
## problem

gotosocial cli currently has no way to list local users:

```
# gotosocial admin account --help
admin commands related to accounts

Usage:
  gotosocial admin account [command]

Available Commands:
  confirm     confirm an existing account manually, thereby skipping email confirmation
  create      create a new account
  demote      demote an account from admin to normal user
  disable     prevent an account from signing in or posting etc, but don't delete anything
  password    set a new password for the given account
  promote     promote an account to admin
  suspend     completely remove an account and all of its posts, media, etc

Flags:
  -h, --help              help for account
      --username string   the username to create/delete/etc
```

This might be fine for tiny instances, but anything can get pretty unwieldly pretty quickly

## Workaround

fiddle around in the database??

## Proposed solution:

add a sub-command that fiddles around in the database and lists local users:

```
gotosocial admin account list
```

A tabular display of username and capabilities and whether the account is disabled or suspended would be good, but having flags to select users based on these stati would be also very good!

```
gotosocial admin account list [--suspended|--unconfirmed|--disabled|--etc…]
```

**Comment by tsmethurst** [comment]
Aha, this has been possible for a while now (see above commits) so I'll close this :)
