### ISSUE TITLE
[feature] GtS CLI: list remote users and instances

### ISSUE THREAD

**Issue by igalic** [superseriousbusiness/gotosocial#389]
## problem

currently, gotosocial has no way to display remote users and instances we federate with, or actively block/mute/suspend.
After some activity on the open Fediverse that could become quite unwieldy.

## workaround

fiddle around in the database

## proposed solution

provide a gotosocial subcommand that fiddles around in the database for me:

```
gotosocial admin remote-users list
gotosocial admin remote-instances list
```

analogous to https://github.com/superseriousbusiness/gotosocial/issues/388 we should be able to make sub-selections based on different stati:

```
gotosocial admin remote-users list --muted
gotosocial admin remote-instances list --allowed
```

**Comment by tsmethurst** [comment]
It's now possible to list users via the CLI, and to filter on suspended status in the settings panel, so I'll close this :)
