### ISSUE TITLE
[question] gotosocial version is missing — or: How the heck do you build this project??!

### ISSUE THREAD

**Issue by igalic** [superseriousbusiness/gotosocial#391]
while [packaging gotosocial for FreeBSD](https://bugs.freebsd.org/show_bug.cgi?id=261733), it was pointed out to me that the version is set thru the build script in [`scripts/build.sh`](https://github.com/superseriousbusiness/gotosocial/blob/main/scripts/build.sh).

It appears that gotosocial itself is using goreleaser, but I'm not sure that thing even works without a cloud?
Which we don't have access to when building ports…
and even then i still suspect that the `.Version` in that file is somehow magically filled in from the tag version…

but even so, it looks like i'm missing other, crucial steps:

```
  - yarn install --cwd web/gotosocial-styling
  - node web/gotosocial-styling/index.js --build-dir="web/assets"
```

does this mean that "web/assets" is a product of that build process?
and that gotosocial-styling directory shouldn't be packaged at all?

do i really have to install yarn and node ☹ ?

**Comment by tsmethurst** [comment]
For the build.sh script, you can set the environment variables VERSION and COMMIT based on latest git tag/current commit, and these will then be inserted into the built binary.

Alternatively, you can use GoReleaser locally, which will do it for you: https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md#with-goreleaser

The yarn and node steps: those steps are only needed if something changes in GoToSocial styling between releases, so you don't *have* to do them per se.

I think for packaging GtS for freebsd, probably the easiest way to is to just take the freebsd build from the releases and untar it somewhere, then you don't actually need to build anything. Or are you wanting to build a system to keep up with latest on main?

**Comment by igalic** [comment]
I want to — i am *trying to* contribute a "port" to FreeBSD. That's a recipe for how to build gotosocial
so that people can just `pkg install gotosocial` on their machines!

(which follows FreeBSD conventions for where to place files)

(or checkout the ports tree, and build the very latest version themselves to install on their machines)

________

as for the changing assets: I think it would be good form for the project to have a "rebuilding web/assets" commit whenever something changes that would lead to them needing to be rebuilt.
That way people who really wish to build gotosocial only need go, and not also nodejs, because, I just hit another bug in NodeJS today: https://github.com/nodejs/node/issues/40467 / https://twitter.com/spoofyroot/status/1379911789903716352 and i'm ready to become a goat shepherd
