### ISSUE TITLE
[feature] Prune timelines after x entries to avoid eating up memory

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#394]
Statuses in timelines are now cached in linked lists, but these lists are never pruned, meaning that after weeks/months of continuous running, they start to use up more and more memory. We should implement a mechanism for pruning these lists beyond x entries, and schedule the cleanup to run every hour or so.

**Comment by carbontwelve** [comment]
I wonder if using something like this https://github.com/arp242/zcache to cache the linked lists would speed up implementation?
