### ISSUE TITLE
[feature] LDAP support

### ISSUE THREAD

**Issue by OniriCorpe** [superseriousbusiness/gotosocial#435]
Hi!

It would be nice to support LDAP for creating user accounts at the time of the connection attempt
And syncing the password of the corresponding user account, by checking each time in the LDAP directory which password is the current

I don't think this is a priority feature but I think it would be a good thing to implement one day

**Comment by tsmethurst** [comment]
Good idea :+1:

**Comment by ericomeehan** [comment]
This is a feature I would like as well.
