### ISSUE TITLE
migration from mastodon

### ISSUE THREAD

**Issue by norayr** [superseriousbusiness/gotosocial#447]
hello!

i wish i could migrate my mastodon instance to gotosocial.

would you please create a script to migrate the existing mastodon db with users and posts to gotosocial db?

also i guess each instance has its own private key by which it is identified? then also that?

thank you!

**Comment by tsmethurst** [comment]
Heya, this is a duplicate of #128 so I'm gonna close it :)

This is something we probably won't work on until GoToSocial is out of alpha and is more feature complete. But it's definitely something we will include when the time comes :)

**Comment by norayr** [comment]
yay yay, thank you!
