### ISSUE TITLE
ACME errors in log for 'www.' subdomain

### ISSUE THREAD

**Issue by cathalgarvey** [superseriousbusiness/gotosocial#451]
Probably benign? But I set up a server recently on a bare domain name, and I'm seeing logging like the following:

`2022/04/12 20:14:07 http: TLS handshake error from 45.87.43.55:50660: acme/autocert: host "www.xn--seafid-exa.ie" not configured in HostWhitelist`

And indeed, the 'www.' subdomain is not covered by TLS. I'm not seeing requests to this subdomain occurring though, so it might just be some internal gripe from the ACME library.

**Comment by tsmethurst** [comment]
Heya! I've seen similar logs when bots and whatnot are trying to scrape endpoints. So not exactly benign, but not an issue we can do much about from our end i'm afraid (apart from just suppressing the logs), so I'm gonna close this issue.

**Comment by cathalgarvey** [comment]
FWIW, I was checking the logs to see whether it was a bot, and saw no evidence there of a bot. But perhaps the logs don't show pre-handshake connections when the TLS fails?

I assumed from the `acme/autocert` bit that this was a library griping at me. It's no problem to me either way though. :)
