### ISSUE TITLE
[bug] federated posts don't show the CW

### ISSUE THREAD

**Issue by igalic** [superseriousbusiness/gotosocial#456]
both, pinafore and tusky, display federated posts with CW without them.

original:
![two posts from @meena@scholar.social with CW reading: Punishment and Reward in the Corporate University](https://user-images.githubusercontent.com/497249/163667005-49916356-38c9-4e21-8a26-b286af4f574e.jpg)

viewed from gotosocial:
![wo posts from @meena@scholar.social without CW just showing text](https://user-images.githubusercontent.com/497249/163667143-64d4ac0b-7e9b-44d0-a3b5-01dafd721421.jpg)

**Comment by tsmethurst** [comment]
Aha, good catch, thanks!

**Comment by tsmethurst** [comment]
Having trouble reproducing this; i tried posting from my mastodon account and from my goblin.technology account the content-warnings show up in both federated and home timelines.

![Screenshot from 2022-04-25 14-58-37](https://user-images.githubusercontent.com/31960611/165094042-e2c6d20f-34ff-4dbf-b901-859c64b7edeb.png)

Could you give me the URIs of the two posts in your screenshot so I can try dereferencing them from GtS and see if I can replicate it that way?

**Comment by tsmethurst** [comment]
Ah wait, I found the posts! And indeed I see the same bug for those posts; I'll investigate why :)

**Comment by igalic** [comment]
this: https://scholar.social/@meena/108138729399508469

from a week ago, is still displayed wrong

this: https://scholar.social/@meena/108187671571909188

from the same account from yesterday is displayed correctly.
i upgraded yesterday to the latest HEAD
