### ISSUE TITLE
[bug] GtS sometimes doesn't shut down cleanly

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#461]
Sometimes when I do `systemctl restart gotosocial` to restart GoToSocial and load new configuration, it hangs on 'shutting down' and I have to manually kill it with `kill -9 [pid]`.

So *something* is getting stuck *somewhere* and we have to figure out where.

Could be related to #460 in that that also feels like it's probably a lockup situation or race condition

**Comment by tsmethurst** [comment]
Update: I added some logging and it looks like this might be an issue with the router not shutting down cleanly, rather than something from media processing as I'd suspected.

**Comment by igalic** [comment]
that does make sense.
what library does the router use for handling connections?

**Comment by tsmethurst** [comment]
This seems to have been closed by #466 :fireworks:
