### ISSUE TITLE
[bug] can't upload images

### ISSUE THREAD

**Issue by igalic** [superseriousbusiness/gotosocial#462]
when trying to upload a 1 MB image to my instance, it fails after about 600 bytes:

```
Apr 16 16:24:52 social gotosocial[36272]: time=2022-04-16T16:24:52Z level=info msg=[5.80325ms] Not Found: wrote 632 bytes func=github.com/superseriousbusiness/gotosocial/internal/router.loggingMiddleware.func1 file=github.com/superseriousbusiness/gotosocial/internal/router/logger.go:65 clientIP=192.168.17.10 latency=5.80325ms method=POST path=/api/v2/media statusCode=404 userAgent=Tusky/17.0 Android/10 OkHttp/4.9.3
Apr 16 16:24:53 webserver httpd[37201]: [proxy:error] [pid 37201:tid 35124299520] (32)Broken pipe: [client 95.223.76.65:46035] AH01084: pass request body failed to 192.168.17.40:8080 (social)
Apr 16 16:24:53 webserver httpd[37201]: [proxy_http:error] [pid 37201:tid 35124299520] [client 95.223.76.65:46035] AH01097: pass request body failed to 192.168.17.40:8080 (social) from 95.223.76.65 ()
```

i don't think it's the proxy, all values here https://httpd.apache.org/docs/2.4/mod/mod_proxy.html like it should fit (time and space)

the image in question:
![steveklabnik-FQaWvpKXsAEGdr--01](https://user-images.githubusercontent.com/497249/163684189-1939efc5-f34f-4b0b-9d34-d546d15f3a5f.jpeg)

i've had similar trouble with other jpegs before, tho they might have been a lot bigger

**Comment by igalic** [comment]
it there a trace logging mode where i can easily filler out the SQL stuff?

**Comment by igalic** [comment]
meanwhile, here's the fetch error (attempt?) from pinafore.social, as captured by Firefox:
```javascript
await fetch("https://soc.eena.me/api/v2/media", {
    "credentials": "include",
    "headers": {
        "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
        "Accept": "application/json",
        "Accept-Language": "en-US,en;q=0.5",
        "Content-Type": "multipart/form-data; boundary=---------------------------261650408553611804259382910",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "cross-site",
        "Sec-GPC": "1",
        "Authorization": "Bearer YJG3ZMM4Y2ETNTHHNC0ZNZG5LTHKNDCTY2ZJZMJMYMQZZMVL"
    },
    "method": "POST",
    "mode": "cors"
});
```

**Comment by igalic** [comment]
the biggest image i can upload is around 200k, despite 

```yaml
media-image-max-size: 10485760
```

**Comment by tsmethurst** [comment]
Did you try it without your proxy yet? Ie., just sshing into the instance it's running on and connecting directly with the GtS api? I have a feeling this could be proxy related.

**Comment by igalic** [comment]
no.
how, exactly, do i do that?

**Comment by dokuja** [comment]
I saw a post from another instance that couldn't upload images and confirmed I couldn't as well.  Media uploads using Tusky 17 fails, but works on Pinafore.  I believe it is related to this issue:

[https://github.com/tuskyapp/Tusky/issues/2409](https://github.com/tuskyapp/Tusky/issues/2409)

Using /api/v2/media returns a 404:

`Apr 23 18:58:40 gotosocial[36457]: time=2022-04-23T18:58:40Z level=info msg=[6.795272ms] Not Found: wrote 652 bytes clientIP=1.2.3.4 latency=6.795272ms method=POST path=/api/v2/media statusCode=404 userAgent=Tusky/17.0 Android/11 OkHttp/4.9.3`

And /api/v1/media (using Pinafore) returns 200:

`Apr 23 19:00:46 gotosocial[36457]: time=2022-04-23T19:00:46Z level=info msg=[70.054549ms] OK: wrote 307 bytes clientIP=1.2.3.4 latency=70.054549ms method=POST path=/api/v1/media statusCode=200 userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.133 Safari/537.36`

**Comment by tsmethurst** [comment]
Right! I talked to the Tusky folks and they switched media endpoints from v1 to v2 in Tusky 17. GtS doesn't implement the v2 endpoint yet, so we've gotta do that :P I'll make a fix. Thanks for the info!

**Comment by tsmethurst** [comment]
Aha!! Thank you! So we just need to implement both the v1 and v2 endpoints to stay in line with the mastodon api... I'll make a fix tomorrow :)

Sent from ProtonMail mobile

-------- Original Message --------
