### ISSUE TITLE
[bug] [docker] Unable to open database file

### ISSUE THREAD

**Issue by EchedeyLR** [superseriousbusiness/gotosocial#476]
I just followed the documentation of https://docs.gotosocial.org/en/latest/installation_guide/docker/ until the step in which the container must be started.

Then, I checked the state with `docker ps` and saw it restarting every time.

After checking the logs with `docker logs -f gotosocial` I saw this:

```
time=2022-04-23T23:39:58Z level=fatal msg=error executing command: error creating dbservice: sqlite ping: Unable to open the database file (SQLITE_CANTOPEN)
time=2022-04-23T23:39:58Z level=fatal msg=error executing command: error creating dbservice: sqlite ping: Unable to open the database file (SQLITE_CANTOPEN)
time=2022-04-23T23:39:59Z level=fatal msg=error executing command: error creating dbservice: sqlite ping: Unable to open the database file (SQLITE_CANTOPEN)
time=2022-04-23T23:40:00Z level=fatal msg=error executing command: error creating dbservice: sqlite ping: Unable to open the database file (SQLITE_CANTOPEN)
time=2022-04-23T23:40:02Z level=fatal msg=error executing command: error creating dbservice: sqlite ping: Unable to open the database file (SQLITE_CANTOPEN)
```

I only changed `GTS_HOST` to my domain and the exposed host port to other one instead of `443` in the default enabled one.

I am sure this has nothing to do and is more *other issue*.

Thank you in advance for any help provided.

**Comment by EchedeyLR** [comment]
I forgot to mention that I followed these steps from an user in the `docker` group without `root` privileges which are not necessary when you are in that group to manage Docker itself.

Since the container must mount a local volume, the service inside the container is being run under user `1000:1000` and the user holding the directory is not in that group, maybe is that the origin of the issue itself?

It should not be because even running a Docker container in an unprivileged user under `docker` group should run these containers with the default user of docker and not this user. Docker containers being run by unprivileged users itself require remapping the Docker main service.

**Comment by tsmethurst** [comment]
Heya! Indeed this looks like a bug or missing step in our documentation... Can you try `sudo chown -R 1000:1000` on the data directory you created for GoToSocial?

**Comment by EchedeyLR** [comment]
I can try without problem, but that doesn't make it reliable for running in a production environment, since it will expose that private server information to a main user already created in the server.

Could I just change the `user` parameters in the `docker-compose.yml` or that would involve you to change some additional configuration inside your Docker image?

**Comment by EchedeyLR** [comment]
Okay, I tried to change the `user` parameter in the configuration to the one I used and it worked perfectly.

**Comment by tsmethurst** [comment]
> Okay, I tried to change the `user` parameter in the configuration to the one I used and it worked perfectly.

Alright, sounds like we just need to change the documentation a little then :)

**Comment by mat-l** [comment]
I have the same problem in the current version of gotosocial.
I have followed the guide over here https://docs.gotosocial.org/en/latest/installation_guide/docker/ and have check the permissons of the data folder as well regarding user 1000:1000 and everything is fine.
Anyways the container ist not starting with the following error logs: "2022/11/21 15:42:32 error executing command: error creating dbservice: sqlite ping: Unable to open the database file (SQLITE_CANTOPEN)" the data folder is also completely empty. :-(
Any quick fix ideas?

**Comment by 9cat** [comment]
for NOT SAFE way to test it . change it to root:root  , it works

**Comment by mat-l** [comment]
Thanks for the hint testing it with root @9cat . It helped me to identify a small mistake in the path of the volumes.
It now works 👍 thank you for the quick answer and your great project. Looking forward building up my new fediverse home with gotosocial. @tsmethurst

**Comment by chao7150** [comment]
If you `sudo docker compose` you must change volumes from `~/gotosocial...` to `/home/foo/gotosocial...`

**Comment by mirenbz** [comment]
I'm having the same problem... `user` in `docker-compose.yml` is set to the same user:group set as owner of `/gotosocial/storage`, `~/gotosocial/data` and `sqlite.db` (which is in `/gotosocial/storage/sqlite.db`, and set so in the compose file). `docker-compose up -d` goes green, but `docker ps` shows gotosocial always restarting a few seconds ago, and the logs say that

```
error executing command: error creating dbservice: sqlite ping: Unable to open the database file (SQLITE_CANTOPEN)
```

Any clues? Thanks!

**Comment by hughrun** [comment]
@mirenbz I just ran into this and the problem was that I am not using the default directory location so the `data` directory wasn't where GTS expected it. If this is the case for you, you need update the directory path under `volumes` in `docker-compose.yaml`

**Comment by hiklah** [comment]
Hi all,

I also have encountered this issue with running docker as current user instead of the root with `sudo`. The reason is that the `user` in the docker is not `1000:1000` although we set it on the `docker-compose.yaml`, and in my case is `100999:100999`. Thus the user cannot write sqlite data to the `data` directory.

All we need to do is just changing the ownership of `data` directory to the real user, ex: `sudo chown 100999:100999 gotosocial/data`

But in some case, maybe it's not `100999:100999`. We could firstly set `write` permission of `data` to all users with command line `sudo chmod 777 gotosocial/data` or `sudo chmod a+w gotosocial/data`. After that, run `docker compose up`. If it works, run `Ctrl+C` to stop it and run `ls -l gotosocial/data` to get the real uid and gid of the user with the sqlite data files. Then run `chown` as I mentioned before to change the ownership.

I would prefer to remove the `data` and create it again and then change the ownership as it's the first run and nothing would be lost :)

**Comment by OscarAlmgren** [comment]
I'm still having trouble with this issue. Is there any work done to update the docs with a correct way to do this?

**Comment by tsmethurst** [comment]
It's not really clear to me based on the comments in this thread what would need to be changed in the documentation. Would a note about chowning the data directory for whatever user you're running the gts container as do the trick?
