### ISSUE TITLE
[bug] Reverse proxy server support seems to be incorrect

### ISSUE THREAD

**Issue by EchedeyLR** [superseriousbusiness/gotosocial#482]
It is supposed that Apache Http Server sends the correct headers for maintaining the client IP in the backend web server running GTS but, for some reason, GTS doesn't seem to support the header or ignores it completely.

I get this from the logs:
```
time=2022-04-24T13:19:04Z level=info msg=[1.002331ms] Forbidden: wrote 64 bytes clientIP=192.168.3.1 latency=1.002331ms method=POST path=/auth/sign_in statusCode=403 userAgent=Mozilla/5.0 (X11; Linux x86_64; rv:4.8) Goanna/20220329 PaleMoon/29.4.5.1

```

Where `192.168.3.1` is the IP address of the reverse proxy server.

**Comment by tsmethurst** [comment]
Hmm, did you try adding `192.168.3.1` to the `trusted-proxies` section of your GtS configuration?

**Comment by EchedeyLR** [comment]
Ok, that is the common config but where should I modify the configuration since I am using Docker?

Uploading the `config.yml` was skipped in the Docker documentation and I don't see more information about that.

**Comment by tsmethurst** [comment]
You can set it with an env var on the Docker container. So I think your case setting `GTS_TRUSTED_PROXIES` to `192.168.3.1` should do the trick

**Comment by EchedeyLR** [comment]
Perfect, it works.

I want to ask you since in the `config.yml` this is some kind of array: what happens if I want to add more than just a trusted proxy?

**Comment by tsmethurst** [comment]
Good question. As an env var you space separate it, so say `GTS_TRUSTED_PROXIES=address_1 address_2`. If it's in the config.yaml you add it as an array. If it's being passed on the command line I think it's comma separated, so `--gts-trusted-proxies address_1,address_2`. I should document this :P

**Comment by EchedeyLR** [comment]
Okay, thank you.

Closing this.
