### ISSUE TITLE
[bug] Registered and promoted user cannot login in Admin panel

### ISSUE THREAD

**Issue by EchedeyLR** [superseriousbusiness/gotosocial#483]
I followed the documentation for the Docker option, but this issue seems to not be specific of it.

After I registered and promoted the new user correctly and the instance is running correctly, I cannot login using this user in the Admin panel, receiving `password/email combination was incorrect` as result.

**Comment by tsmethurst** [comment]
Just checking: currently the email is case sensitive and doesn't strip spaces (we have to fix this). Can you make sure the email address you put into the login form is exactly the same as the one you created your user with?

**Comment by EchedeyLR** [comment]
The email was correct.

To be exact, the `type="email"` doesn't allow extra spaces.

**Comment by EchedeyLR** [comment]
My configuration line was exactly `docker exec -it gotosocial /gotosocial/gotosocial admin account create --username echedeylr --email elr@disroot.org --password ****` (skipping the password).

**Comment by tsmethurst** [comment]
Hmm okay, were there any special characters in your password like ampersands or whatever? In other words, things that the bash command line might have interpreted/escaped?

**Comment by EchedeyLR** [comment]
Okay, this was my fault at all.

I forgot to confirm the account. :^).

Closing the issue as result of it.

**Comment by tsmethurst** [comment]
Haha, happens to the best of us! Glad you figured it out :)
