### ISSUE TITLE
[question] How to set the email of the instance?

### ISSUE THREAD

**Issue by EchedeyLR** [superseriousbusiness/gotosocial#484]
I didn't see it in the documentation itself.

![image](https://user-images.githubusercontent.com/56733813/164992543-44b4f213-7a99-410b-b188-97c3fe7a8839.png)

**Comment by tsmethurst** [comment]
Hey! This should be possible through the admin ui, but I see that it's currently not :thinking: Not sure why, but it's something we can fix pretty easily. I'll let you know when it's done.

**Comment by tsmethurst** [comment]
https://github.com/superseriousbusiness/gotosocial-admin/pull/8 Made a PR to our gotosocial-admin repo. Once it's merged and deployed I'll ping you again.

**Comment by tsmethurst** [comment]
Heya, it's been merged into main now, and there's already a version deployed here, so you can use that updated version to add an email address to your instance :) https://gts.superseriousbusiness.org/admin

**Comment by tsmethurst** [comment]
> what would someone use who doesn't have the admin tool web thing deployed?

You don't even have to deploy it yourself, you can just use the one i linked above :muscle: it's just a webapp.

Aside from that, you can be hardcore and just do an API call

**Comment by igalic** [comment]
i was hoping there's a configuration setting, or a CLI command.

but, i guess, i could just run the app on my laptop!

**Comment by tsmethurst** [comment]
I'm going to close this issue now since the question is answered :) Feel free to open it again if you have more to ask.
