### ISSUE TITLE
[question] How to set more than one account to contact?

### ISSUE THREAD

**Issue by EchedeyLR** [superseriousbusiness/gotosocial#485]

**Comment by tsmethurst** [comment]
Heya! Right now it's not possible to do this, but it's something we should consider adding in future :) Some kind of 'mod team' thing instead of just 'contact account' perhaps?

**Comment by tsmethurst** [comment]
I'm going to close this issue now since the question is answered :) Feel free to open it again if you have more to ask.

I also opened a feature issue to work on this when we have the bandwidth
