### ISSUE TITLE
[chore] Tidy up Bun annotations to allow upstep to bun v1.1.4

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#486]
Stepping from Bun v1.1.3 => v1.1.4 produces lots of failing tests, because of the nullzero change in bun: https://github.com/uptrace/bun/blob/master/CHANGELOG.md#114-2022-04-20

To make GtS work properly with the new version of bun we need to carefully go through our structs in the `gtsmodel` package and make sure we're using the combination of `default`, `nullzero` and `notnull` tags correctly on our fields. See: https://github.com/uptrace/bun/issues/523#issuecomment-1107833377

**Comment by igalic** [comment]
> In v1.1.4 we made change to automatically apply `nullzero` when you have `default:something` option, because otherwise the default is just ignored.

unless i completely misunderstanding what `nullzero` does, that sounds like a really weird change.
it also sounds like a total butt move to do that on a patch upgrade

**Comment by tsmethurst** [comment]
Eh, it's ok :) we'll make it work
