### ISSUE TITLE
[bug] Confusing error message when `host` is unset

### ISSUE THREAD

**Issue by iMartyn** [superseriousbusiness/gotosocial#495]
When running `0.3.0` of the docker image without a `host` variable set but sqlite configured, the app crashes with the following output :

```
time=2022-04-26T16:20:43Z level=info msg=connected to SQLITE database
time=2022-04-26T16:20:43Z level=info msg=there are no new migrations to run func=doMigration
time=2022-04-26T16:20:43Z level=fatal msg=error executing command: error creating instance account: constraint failed: NOT NULL constraint failed: accounts.username (1299)
```

This is a confusing error message as it is a clean database and looks to be creating a record with an empty username.

Either the username should have a default value if the host is unset, or the app should bail with a nicer error message leading people to set the host env/config.

**Comment by igalic** [comment]
or it should just ignore everything but name when SQLite is set as DB.
worst case, i would expect a warning that you're supplying info that SQLite can't deal with, but not a crash.
