### ISSUE TITLE
[feature] Follower vs friend distinction

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#5]
There should be a way of distinguishing between a 'follower' -- someone who gets your public and unlisted posts delivered to them -- and a 'friend' -- someone who sees your 'friends only' posts.

**Comment by cadadr** [comment]
I was about to open an issue for something similar: mutuals-only posts. If a post of mine is set to "mutuals only, it should only be visible to those accounts who follow me and whom I follow back, and aren't muted.

The idea is not mine originally, I encountered it on fedi but I don't have a link to the original, nor do I recall who came up with it.

**Comment by tsmethurst** [comment]
Ohoho, believe it or not we actually have mutuals-only posts already :) Just not sure yet of the proper way to federate them...

**Comment by cadadr** [comment]
Oh, I should've checked first. Thank you so much, so nice and refreshing to see a project this thoughtful finally! :heart:

**Comment by igalic** [comment]
which pr/commit fixed this?

**Comment by Fastidious** [comment]
@igalic none that I can see. But if the OR changed their mind, then 🤷🏻‍♂️.
