### ISSUE TITLE
[bug] Editing a profile bio shows the existing bio text as html

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#502]
This is confusing and messy for users; we should show it as plaintext not html when it's being edited.

**Comment by igalic** [comment]
or, *\*cough\** markdown

**Comment by tsmethurst** [comment]
> or, _*cough*_ markdown

We don't support markdown for editing profiles yet... but when we do, we should allow that as well yep yep

**Comment by tsmethurst** [comment]
Closed by https://github.com/superseriousbusiness/gotosocial/pull/531
