### ISSUE TITLE
[bug] followers-only statuses are not self-boostable

### ISSUE THREAD

**Issue by i-am-a-paull** [superseriousbusiness/gotosocial#504]
When using the dot menu on your own followers-only post on Tusky, the "boost to original audience" option is visible, but selecting it causes a 403 Error and produces the following log output on the server:

`time=2022-04-28T18:00:45Z level=info msg=[7.017318ms] Forbidden: wrote 45 bytes clientIP=[redacted ip address] latency=7.017318ms method=POST path=/api/v1/statuses/01G1PKC7V47T8XMG8YKDJEF51E/reblog statusCode=403 userAgent=Tusky/17.0 Android/11 OkHttp/4.9.3`

**Comment by i-am-a-paull** [comment]
I added a condition to an if statement that may fix this, but I wanted to be sure that there wasn't some larger overarching issue at hand that my limited knowledge of how it all works may be missing. I noticed that followers-only posts are stored with the boostable flag set to false, and that makes sense. But are there any conditions where the original author should *not* be able to boost their own post?

**Comment by tsmethurst** [comment]
I would say that the author shouldn't be able to boost their own direct messages, but that's about it. If you have a fix for this, you're very welcome to open a PR and I'll review :) First time contribs for open issues--especially ones in a current milestone--are very very welcome :muscle:

**Comment by tsmethurst** [comment]
Closed by https://github.com/superseriousbusiness/gotosocial/pull/510
