### ISSUE TITLE
[bug] Errors using Toot!.app

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#513]
From Leah in the matrix chat

> I've tested the app "Toot!" today and there are a few things that need to get fixed in gotosocial, otherwise the app (sadly) won't talk with it:
> 
> GET /api/v1/instance:
>  -> missing or empty fields in response:
>   - thumbnail (needs to be a valid url with an image)
>   - contact_account.header (needs to be a valid url with an image)
>   - contact_account.header_static (needs to be a valid url with an image)
> 
> POST /oauth/token:
>  -> missing field in response: created_at (unix timestamp in seconds) 
> 
> POST /api/v1/statuses:
>  -> wrong format in response: created_at (needs to be something like `2022-04-30T14:19:05.000Z`)
>  -> empty fields in response:
>   - account.header (needs to be a valid url with an image)
>   - account.header_static (needs to be a valid url with an image)
> 
> -> user posts in general:
>  - wrong format in response: created_at (append `.000` before the Z)
>
> What does work with the above fixes:
> -> instance lookup
> -> auth
> -> home timeline
> -> federated timeline
> -> (un)faving posts
> -> (un)boosting posts
> -> deleting posts
> -> creating posts (tested with cw's, images attached, post visibility on public/unlisted/followers-only/direct)
> 
> What doesn't work: (no ideas on that yet)
> -> notifications timeline
> -> local timeline
> -> user profiles (shows the profile picture and bio but doesn't show any posts nor users in followers/following)

We should try to resolve these issues so that [Toot!](https://mastodon.social/@tootapp) will work with GoToSocial.

**Comment by carbontwelve** [comment]
I think you're right @kseistrup, this seems linked to #559, I am seeing the same two log entries when I try with either Toot! or the official Mastodon App.

```
2022-05-19T22:36:33.336084509Z app[web.1]: time=2022-05-19T22:36:33Z level=info msg=[2.654023ms] OK: wrote 379 bytes clientIP=172.17.0.1 latency=2.654023ms method=GET path=/api/v1/instance statusCode=200 userAgent=Toot!/132 CFNetwork/1331.0.7 Darwin/21.4.0
2022-05-19T22:36:33.386805554Z app[web.1]: time=2022-05-19T22:36:33Z level=info msg=[2.260561ms] Not Found: wrote 641 bytes clientIP=172.17.0.1 latency=2.260561ms method=GET path=/.well-known/host-meta statusCode=404 userAgent=Toot!/132 CFNetwork/1331.0.7 Darwin/21.4.0
```

**Comment by tsmethurst** [comment]
Thanks! Looks like it's related to this one then: https://github.com/superseriousbusiness/gotosocial/issues/345

**Comment by tsmethurst** [comment]
The problems with Toot in this issue have been fixed with recent updates, so I'm going to close this issue. There are still some problems with Toot, but they should be opened as separate bug reports.
