### ISSUE TITLE
[performance] Perform viper.Get__() functions only at init

### ISSUE THREAD

**Issue by NyaaaWhatsUpDoc** [superseriousbusiness/gotosocial#517]
Parse config values into struct at init and from there we should just access the values through the initialized struct. Running `viper.Get___()` in HTTP handlers for example, or other (relatively) hot codepaths is unnecessary given it's not a super simple implementation.

It should be a very easy to change to make, just possibly quite a bit of code to change :'). I'm happy to do it myself assuming this is something we agree on here!

**Comment by igalic** [comment]
(how) will this affect our plans re https://github.com/superseriousbusiness/gotosocial/issues/270 ?

**Comment by tsmethurst** [comment]
Indeed, that would be my concern too: one of the reasons we switched to viper was to allow config to be reloaded from file or (eventually) from other config storage systems like etcd. If it's only a small performance hit to call `viper.Get()` then I think I'd rather we kept it so we can allow hot reload later on

**Comment by NyaaaWhatsUpDoc** [comment]
> Indeed, that would be my concern too: one of the reasons we switched to viper was to allow config to be reloaded from file or (eventually) from other config storage systems like etcd. If it's only a small performance hit to call `viper.Get()` then I think I'd rather we kept it so we can allow hot reload later on

Ah I was not aware of this. It definitely would be possible to manage this still implementing the initial viper calls at init, but maybe reduces the priority of this by a little.
