### ISSUE TITLE
Can't login with any client

### ISSUE THREAD

**Issue by ffuentese** [superseriousbusiness/gotosocial#518]
I just installed the software. I used postgres and the website works, accounts are saved through the gts cli but I can't login using toot or tusky. It always throughs the error that the password/email combination is wrong. I checked the password but it seems like the issue is somewhere else.

I'm using Ubuntu 20.04.3 LTS with the latest version.

**Comment by igalic** [comment]
did you use `gotosocial admin account confirm --username <name>` ?

**Comment by ffuentese** [comment]
Apparently I got what it was but some symbols don't work well because I made another account with a simpler password and it worked. If I just knew which characters those were or what's the max length....

I add passwords using a password generator like the one from keepassxc

**Comment by igalic** [comment]
the problem might be that the shell is interpreting the symbols, so it's important to correctly escape them:

```
meena@76ix ~> pwgen -1ys 28
S<DRQD-fZ!XknX[k"dvA-*5rS#@:
```

in this example, `<`, `!`, `[`, `"`, `*`, `#`, and `:` would be interpreted by a sh compatible shell.

to correctly escape it, in this case, you'd have to use single-quotes:

```
gotosocial admin account create --email you@your.domain --username you --password 'S<DRQD-fZ!XknX[k"dvA-*5rS#@:'
```

**Comment by tsmethurst** [comment]
Heya, if it's alright with you i'll close this issue now since @igalic explained what's going on :) I'll make an update to the documentation to put single quotes around the password so other people don't run into this issue.

If you have any more questions or problems, feel free to reopen the issue!
