### ISSUE TITLE
[bug] followers-only statuses can be boosted by other accounts in miscoded clients

### ISSUE THREAD

**Issue by i-am-a-paull** [superseriousbusiness/gotosocial#524]
followers boosting followers-only statuses with boostable set to true doesn't error out. I don't entirely know what the reach would be, but it definitely should not be allowed. I tested this by modifying pinafore code to always allow boosts. PR #510 should fix this bug as well as #504 , but I wanted to make sure you were aware of this.

**Comment by tsmethurst** [comment]
Good catch, thank you!

**Comment by tsmethurst** [comment]
Closed by https://github.com/superseriousbusiness/gotosocial/pull/510
