### ISSUE TITLE
[bug] Link to post returns error

### ISSUE THREAD

**Issue by zethra** [superseriousbusiness/gotosocial#532]
When I get the link to a post through Tusky or another front end, that link returns `{"error":"status not found"}`. The post still shows up in my client and to other users in their clients.

**Comment by zethra** [comment]
The log shows the following error
```
time=2022-05-03T04:37:32Z level=info msg=[2.814933ms] Bad Request: wrote 52 bytes clientIP=172.24.0.3 latency=2.814933ms method=GET path=/@sasha/statuses/01G242FDYHCGEASCJT3RT11TMT statusCode=400 userAgent=Mozilla/5.0 (Android 11; Mobile; rv:98.0) Gecko/98.0 Firefox/98.0
```

**Comment by igalic** [comment]
this is the case for all posts that aren't public.
so, beginning from from "unlisted" you can't link to posts.

this decision has been made as a measure to protect Users privacy.

**Comment by zethra** [comment]
Makes sense. I hadn't realized I made the post unlisted. My mistake.
