### ISSUE TITLE
[investigation] error dereferencing single status in thread

### ISSUE THREAD

**Issue by NyaaaWhatsUpDoc** [superseriousbusiness/gotosocial#539]
i *think* currently if we run into an error dereferencing a status in a thread, the whole stack of dereferenced statuses gets dropped, when ideally we should dereference and store what we can.

i'm not 100% sure though hence the investigate tag

**Comment by tsmethurst** [comment]
Gonna take a look at this one today :)

**Comment by tsmethurst** [comment]
Had a look, and we weren't missing anything when erroring during a dereference (just the status that was being dereferenced); it doesn't abort the whole thread dereferencing process. Did find another bug though, opened with mastodon: https://github.com/mastodon/mastodon/issues/18638
