### ISSUE TITLE
[bug] Misskey federation is flaky

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#540]
Currently it's possible to see posts from Misskey when they're boosted by someone else, but it's not possible to follow or be followed by a misskey instance. We should investigate why. Most likely: something to do with http signatures.

**Comment by jugendhacker** [comment]
Maybe some more details. If I try to follow a Misskey user I get the following log:
```
May 05 09:55:49 gotosocial gotosocial[386]: time=2022-05-05T09:55:49Z level=error msg=BatchDeliver: at least one failure: POST request to https://example.com/users/someusersid/inbox failed (401): 401 Unauthorized
```

(I redacted the original Domain and User ID from the log)


So your guess about a problem with HTTP Signatures seems to be correct.

**Comment by jugendhacker** [comment]
The Misskey inbox processing seems to be [here](https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/queue/processors/inbox.ts) but I don't understand enough of it's codebase to be able to figure out why GoToSocial signature might not get accepted.

**Comment by kescherCode** [comment]
Perhaps an issue should be opened at https://github.com/misskey-dev/misskey, because if this only happens with Misskey and not with other ActivityPub software, this may very well be a Misskey issue.

**Comment by carbontwelve** [comment]
My instance (0.3.4 1cdc163 2022-05-26T11:38:41Z [go1.18]) doesn't seem to be showing avatars of Misskey instances (just noticed with [nuhn@ping.the-planet.space](https://ping.the-planet.space/@nuhn)) avatar and avatar_static both come back as empty strings from GtS:

```js
acct: "nuhn@ping.the-planet.space"
avatar: ""
avatar_static: ""
bot: false
created_at: "2022-05-30T07:01:48Z"
display_name: "🌱 Nuhnimon-kenobi 🖋 "
emojis: []
fields: []
followers_count: 0
following_count: 0
header: ""
header_static: ""
id: "01QRQHQHMK3V8GVJMWFXP63DP7"
last_status_at: "2022-05-30T09:42:04Z"
locked: false
note: "<p><span>Mom, writer, game dev. I love notebooks, knitting, crochet, movies, coffee, dragons and sleeping.<br>She/Her.<br></span></p>"
statuses_count: 2
url: "https://ping.the-planet.space/@nuhn"
username: "nuhn"
```

**Comment by kescherCode** [comment]
As I had suspected earlier: Misskey probably had some faults there.
Latest dev builds merged [fix: add id for activitypub follows](https://github.com/misskey-dev/misskey/pull/8689) and [fix(federation): accept HTTP signatures with hs2019](https://github.com/misskey-dev/misskey/pull/8635). These sound precisely like the issues described here.

**Comment by tsmethurst** [comment]
Oh brilliant! :)

**Comment by tastytea** [comment]
After upgrading Misskey to 12.111.0, i can follow `@gotosocial@gts.superseriousbusiness.org`! :tada:

**Comment by tsmethurst** [comment]
Gonna close this one now since federation with the latest version of misskey (following, being followed back, message delivery) works OK.

We can open more misskey federation issues later if more things pop up, of course :)
