### ISSUE TITLE
[bug] Pinafore websocket connection issue

### ISSUE THREAD

**Issue by Lastorder-DC** [superseriousbusiness/gotosocial#545]
![image](https://user-images.githubusercontent.com/18280396/167068765-0d3a3914-0b25-4fd4-856d-65081b23c19f.png)

Version : `0.3.1 9cf66bf 2022-04-26T16:10:11Z [go1.18]`
I'm running gotosocial with command `./gotosocial --config-path ./config.yaml server start`

Manual connection to wss works(tested using chrome extension)

**Comment by tsmethurst** [comment]
Heya, couple questions to help narrow this down: 

1. Do the logs in your browser give any more info under the dropdown?
2. Do you see any interesting logs on GoToSocial when you try to make the websocket connection?
3. Are you using a reverse proxy like nginx, or something else?

**Comment by Lastorder-DC** [comment]
1. Nope. only this.
![image](https://user-images.githubusercontent.com/18280396/167100175-c206ad88-2859-45d8-ad46-cca6c7a0573e.png)
2. Log shows patten below
```
time=2022-05-06T08:59:43Z level=debug msg=received open stream request func=github.com/superseriousbusiness/gotosocial/internal/processing/streaming.(*processor).OpenStreamForAccount file=/drone/src/internal/processing/streaming/openstream.go:39 account=01CH48QFT415V6EFM8HH8072J3 fields.func=OpenStreamForAccount func=github.com/superseriousbusiness/gotosocial/internal/processing/streaming.(*processor).OpenStreamForAccount streamType=user
time=2022-05-06T08:59:43Z level=trace msg=received TICK from ticker func=github.com/superseriousbusiness/gotosocial/internal/api/client/streaming.(*Module).StreamGETHandler file=/drone/src/internal/api/client/streaming/stream.go:175 fields.func=StreamGETHandler func=github.com/superseriousbusiness/gotosocial/internal/api/client/streaming.(*Module).StreamGETHandler
```
Received stream open request

```
time=2022-05-06T08:59:56Z level=trace msg=received TICK from ticker func=github.com/superseriousbusiness/gotosocial/internal/api/client/streaming.(*Module).StreamGETHandler file=/drone/src/internal/api/client/streaming/stream.go:175 fields.func=StreamGETHandler func=github.com/superseriousbusiness/gotosocial/internal/api/client/streaming.(*Module).StreamGETHandler
time=2022-05-06T08:59:56Z level=trace msg=wrote ping message into websocket connection func=github.com/superseriousbusiness/gotosocial/internal/api/client/streaming.(*Module).StreamGETHandler file=/drone/src/internal/api/client/streaming/stream.go:181 fields.func=StreamGETHandler func=github.com/superseriousbusiness/gotosocial/internal/api/client/streaming.(*Module).StreamGETHandler
```
Log about ping and tick

```
time=2022-05-06T09:00:13Z level=debug msg=error writing ping to websocket connection: write tcp 10.0.0.9:443->my.browser.ip.addr:62543: write: broken pipe func=github.com/superseriousbusiness/gotosocial/internal/api/client/streaming.(*Module).StreamGETHandler file=/drone/src/internal/api/client/streaming/stream.go:177 fields.func=StreamGETHandler func=github.com/superseriousbusiness/gotosocial/internal/api/client/streaming.(*Module).StreamGETHandler
time=2022-05-06T09:00:13Z level=trace msg=leaving StreamGETHandler func=github.com/superseriousbusiness/gotosocial/internal/api/client/streaming.(*Module).StreamGETHandler file=/drone/src/internal/api/client/streaming/stream.go:185 fields.func=StreamGETHandler func=github.com/superseriousbusiness/gotosocial/internal/api/client/streaming.(*Module).StreamGETHandler
```
BrokenPipe error

![chrome_2022-05-06_18-01-22](https://user-images.githubusercontent.com/18280396/167101292-1450c0aa-c317-4c54-b459-8f791000e352.png)
What is interesting is, althouth ping is sent to client, nothing was received.

3. No. I'm using gotosocial as webserver(port 80/443 listen) also I'm using root account.

**Comment by tsmethurst** [comment]
Ah I figured it out! It's a chrome-specific issue, which explains why I didn't see it yet. Now I can replicate it :) I'll work on a fix.

**Comment by tsmethurst** [comment]
I opened a PR to pinafore here: https://github.com/nolanlawson/pinafore/pull/2140

**Comment by tsmethurst** [comment]
Heya, since this has been merged into pinafore now, i'm going to close the issue. Once the new version of Pinafore has been deployed on pinafore.social, this should all work as expected :)
