### ISSUE TITLE
user discovery

### ISSUE THREAD

**Issue by Akronae** [superseriousbusiness/gotosocial#547]
Hi,

Is it possible for the users of my instance to be discovered from another instance ?
I have this kind of error:
```
time=2022-05-07T18:44:01Z level=info msg=[311.23µs] Bad Request: wrote 93 bytes clientIP=10.0.1.3 latency=311.23µs method=GET path=/.well-known/webfinger?resource=acct:lalala@www.wewheek.com statusCode=400 userAgent=http.rb/4.4.1 (Mastodon/3.4.6; +https://mastodon.world/)
```

**Comment by Akronae** [comment]
I had to change the routing to GtS from `www.domain.com` to `domain.com`

**Comment by tsmethurst** [comment]
Oh I'm glad you got it working! Was about to start investigating this one :')
