### ISSUE TITLE
[bug] Link account handle inside bio doesn't always work

### ISSUE THREAD

**Issue by jugendhacker** [superseriousbusiness/gotosocial#554]
When I'm trying to put the handle of an account into the bio of a GoToSocial account other people will not be able to click on it. In contrast mastodon seems to make a clickable link out of it. Would be cool if GoToSocial could also do this.

**Comment by tsmethurst** [comment]
Heya! You should be able to do this if you format it like so: `@user@example.org`.

**Comment by jugendhacker** [comment]
Seems not to work. My friend over at https://social.jugendhacker.de/@krea does exactly this and it does not seem to work.

**Comment by tsmethurst** [comment]
AH weird! Okay, thanks for raising this, we'll take a look :)

**Comment by tsmethurst** [comment]
Changed the title to reflect that it's something we've gotta fix, hope that's OK with you

**Comment by jugendhacker** [comment]
Yeah it's okay for me, just thought it's not implemented yet and therefore I wanted to request.

**Comment by igalic** [comment]
I did say i need to take a look at all our regrets, i mean Regexes
