### ISSUE TITLE
Column account.note_raw doesnt exist

### ISSUE THREAD

**Issue by mcrosson** [superseriousbusiness/gotosocial#555]
When updating to 0.3.2 from 0.3.1 I'm getting the following error. When reviewing the docs I dont see a note on if i need to run migrations or similar. This could also be a bug.

```
time=2022-05-11T14:04:22Z level=info msg=connected to POSTGRES database
time=2022-05-11T14:04:22Z level=info msg=there are no new migrations to run func=doMigration
time=2022-05-11T14:04:22Z level=fatal msg=error executing command: error creating instance account: ERROR: column account.note_raw does not exist (SQLSTATE 42703)
```

**Comment by tsmethurst** [comment]
Heya, normally you don't need to run any migrations. We actually messed something up in 0.3.2 ;) Can you step back down to 0.3.1 in the meantime? We'll release a fix asap.

**Comment by mcrosson** [comment]
i already have downgraded to 0.3.1 and will keep an eye out for any updates re this ticket/item.

**Comment by tsmethurst** [comment]
Hiya! We've patched the release and it should work now: could you download it / pull the docker container again and try once more?

**Comment by mcrosson** [comment]
looks like its good to go now

i see the below in the log and pinafore seems connected and showing new statuses

`time=2022-05-11T20:32:47Z level=info msg=MIGRATED DATABASE TO group #4 (20220511165212) func=doMigration`
