### ISSUE TITLE
[bug] `error extracting status content: no content found`

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#565]
This occurs sometimes on posts that are just an image and no text:

```
time=2022-05-13T22:16:51+02:00 level=info msg=ASStatusToStatus: error extracting status content: no content found statusURI=https://mastodon.social/users/yogthos/statuses/108296425480940485
```

I thought I'd fixed this but apparently not quite!

**Comment by NyaaaWhatsUpDoc** [comment]
I just realised if you look at the log entry, it's at info level so it's part of that code block that logs the error but doesn't actually stop parsing because of it. I think we might want to update those log messages to be warnings and not look like errors :')
