### ISSUE TITLE
database error on user creation

### ISSUE THREAD

**Issue by OniriCorpe** [superseriousbusiness/gotosocial#567]
I would like to know if this behaviour is normal
an user of my yunohost package reported this to me and I have the problem too
the GTS server is running, I run the user creation command, and it returns an error asking me to authenticate to the database

```
./gotosocial admin account create --username test_user --email test@example.com --password "someextracomplicatedpassword"
time=2022-05-14T18:42:43+02:00 level=fatal msg=error executing command: error creating dbservice: postgres ping: failed to connect to `host=/var/run/postgresql user=root database=gotosocial`: server error (FATAL: authentification par mot de passe échouée pour l'utilisateur  « root » (SQLSTATE 28P01))
```

the user in question has bypassed using `--db-user gotosocial --db-password thatlongpassword` however from my point of view as a packager, I don't want users to have to go digging for that password

**Comment by tsmethurst** [comment]
Since we talked about this one in the Matrix, do you wanna keep it open or are you OK with the interim solution we reached?

**Comment by OniriCorpe** [comment]
yeah, using --config-path argument is okay
but as mentioned by @f0x52 maybe the cli should communicate with the running server to make those db changes?

**Comment by igalic** [comment]
related: https://github.com/superseriousbusiness/gotosocial/issues/379

**Comment by tsmethurst** [comment]
> yeah, using `--config-path` argument is okay but as mentioned by @f0x52 maybe the cli should communicate with the running server to make those db changes?

I'll open an issue for investigating how to do this neatly :)
