### ISSUE TITLE
[investigation] Is it possible to connect the CLI directly to a running instance?

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#573]
Right now the CLI admin commands make changes by making inserts/deletes/updates directly in the database, for things like creating new users etc. This works fine for the most part, but it doesn't allow us to use the CLI to do things that require federation, and it also means you always need to pass the config into the commands (see #567).

We should investigate whether it's possible to hook the CLI directly into a running server process to do things like inject new configuration, trigger cleanups, deletes, etc. We can use this issue to collect suggestions + document our findings, and perhaps come up with a plan for implementing this in code.

Note that since eventually we will expose admin APIs for managing all of these things, this is really a sort of bonus / QoL feature for admins who prefer to manage things via a CLI rather than an API. If it's not practical to add this functionality, or it requires a lot of redesign and refactoring, then imo it would be best to just prioritize implementing admin endpoints and exposing them through the admin panel, rather than putting too much time into this. But opinions will no doubt vary on this!

**Comment by igalic** [comment]
using one API is always better than using two APIs.

**Comment by f0x52** [comment]
I think it would be best to re-use the same admin api's, but maybe add a pre-shared token authentication method in the config, so the CLI doesn't have to go through an OAUTH flow

**Comment by tsmethurst** [comment]
I'm going to close this one now, since it's unlikely we'll be adding it, but will be focusing instead on adding more useful actions to the admin settings panel.
