### ISSUE TITLE
[frontend] Admin panel: 'Moderation' section for admin actions on accounts

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#582]
We need a 'Moderation' section on the admin panel that contains the existing instance blocks implementation, as well as a way of letting admins trigger the `/api/v1/admin/accounts/{id}/action` endpoint.

Currently only the Suspend action is allowed through this endpoint, but this is already useful for cleaning up old accounts or suspending specific remote accounts that are causing problems.

This is blocked by https://github.com/superseriousbusiness/gotosocial/issues/581 since we need to the implement the endpoint described there first in order to make `/api/v1/admin/accounts/{id}/action` useable.

**Comment by f0x52** [comment]
Working on the reports section now, so we have *some* way to get to user accounts by id, and perform actions, but would definitely be useful to have a general listing route soon(tm) as well, to make the section more useable
