### ISSUE TITLE
[feature] Allow paging through a user's public statuses on their profile

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#583]
Right now on a user's profile page we serve the latest 10 public statuses from that user under the heading 'Recent posts by x'.

We should add some url parameters to the profile page to allow for paging through statuses. For this, we should mirror some of the parameters used by the `/api/v1/accounts/{id}/statuses` endpoint. For now just `max_id` will do the job here.

Related to #570

**Comment by carbontwelve** [comment]
Does this include all accounts, or only users of the instance?

**Comment by tsmethurst** [comment]
Just users of the instance :) This is specifically for the web view. We won't ever allow paging through statuses of off-instance users via the web ui. You can do it via the api already, as part of the standard mastodon API functionality, but you have to be logged in to do that, so we can apply access controls.
