### ISSUE TITLE
[performance] Cache recently allowed/denied domains to cut down on db calls

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#591]
We check for domain blocks here: https://github.com/superseriousbusiness/gotosocial/blob/caa0cde0e025708a762659758d9de7851745cbfe/internal/api/security/signaturecheck.go#L32-L43

We should put a cache somewhere that stores which domains have been allowed recently and blocked recently, to cut down on database calls for block checking. If a domain was blocked recently, it'll be blocked again. If it was allowed recently, it'll be allowed again. We should invalidate this cache when the domain block list is updated (entry added or removed).

**Comment by NyaaaWhatsUpDoc** [comment]
Want me to get this with my matrix mentioned cache plans?

**Comment by tsmethurst** [comment]
Sure! <3 I also don't mind implementing it though, just see how much time + energy you have :)

**Comment by tsmethurst** [comment]
I put this one in 0.4.0 instead, since we ended up having plenty of stuff in 0.3.5 already :)

**Comment by tsmethurst** [comment]
closed by #794
