### ISSUE TITLE
[feature] Add task for cleaning up duplicated media

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#599]
Since https://github.com/superseriousbusiness/gotosocial/pull/589 we shouldn't be pulling any duplicated media attachments in, however we still need to create a task or something (via API, cli, migration, whatever) to clean up media that was already duplicated.

**Comment by NyaaaWhatsUpDoc** [comment]
I think we should make this one a migration imo . unless you think it might come in handy in the future?

**Comment by tsmethurst** [comment]
Tbh it's gonna be tricky to do in a migration because we only have access to the db connection there, and not the storage interface etc. So that will take some code changes to our standard migration stuff I think. I'm considering pushing this one back to the next release because it's a bit of a headache :thinking:
