### ISSUE TITLE
[bug] Gotosocial doesn't use rotation photo data

### ISSUE THREAD

**Issue by tootbrute** [superseriousbusiness/gotosocial#618]
I posted a photo from my Gotosocial self-hosted instance and it is sideways.
Using another account on Tusky and posting the same photo the photo is correctly oriented.

Maybe Gotosocial doesn't read image meatadata/EXIF tags? Maybe this is a known issue?

https://go.arkadi.one/@elias/statuses/01G49JY37DA2G0VRNAECW2QBAD

Phone: LineageOS 18.1
App: Tusky from F-droid

**Comment by NyaaaWhatsUpDoc** [comment]
This has been mentioned before and I think the issue was we're clearing too many of the exif tags :')

Fortunately shouldn't be too difficult to fix. Thank you for submitting an issue!
