### ISSUE TITLE
[bug] Federated accounts show no posts or stats

### ISSUE THREAD

**Issue by autumnull** [superseriousbusiness/gotosocial#631]
### Describe the bug with a clear and concise description of what the bug is.

Federated accounts show no posts or stats

### What's your GoToSocial Version?

v0.3.4

### GoToSocial Arch

armv7 Binary

### What happened?

Viewing accounts on other servers shows no posts, and 0 for all the follower/following/posts stats. Happens on both tusky and pinafore.

Additionally when attempting to follow these accounts, it shows "follow requested", even when the account is not private.

Pinafore:
![screenshot of account @Gargron@mastodon.social with pinafore on mobile browser showing the described behavior](https://user-images.githubusercontent.com/86073772/172032707-315b6d98-a2ca-4ee1-8067-e15df79cfca8.jpg)
Tusky:
![screenshot of account @Gargron@mastodon.social with Tusky app showing the described behavior](https://user-images.githubusercontent.com/86073772/172032719-c0010ece-82e1-40f9-833b-09843571b788.jpg)

### What you expected to happen?

It should show the posts and stats from federated accounts, like it does for local accounts:

![IMG_20220605_035234](https://user-images.githubusercontent.com/86073772/172032973-e7ce04ea-82cf-4abf-93d0-6c37df362ac1.jpg)

### How to reproduce it?

I followed the "binary release" install instructions in the docs. Only thing I had to improvise was the proxy, for which i am using lighttpd, but that part seems to work fine i think.

### Anything else we need to know?

If you want to know the server url to poke around my specific instance you can message me, i just won't post it publicly.

**Comment by zethra** [comment]
I believe GtS will not show information for accounts you're not following. On larger instances you sometimes will see such info because another account on that instance is following that person. I believe this is a limitation of large the activity pub protocol. There may be some other way to fix this though.

As for the "Follow Requested" thing. I've noticed that too. I believe that is a bug.

**Comment by tsmethurst** [comment]
> I believe this is a limitation of large the activity pub protocol. There may be some other way to fix this though.

Indeed! What we will do in future is try to fetch an account's featured/pinned posts so that at least something shows up in the ui when you look at an account your instance hasn't learned much about yet :) There are probably other fixes we could do as well to present something more reasonable to the user, but this will take a bit of investigation.

> As for the "Follow Requested" thing. I've noticed that too. I believe that is a bug.

Yep, that's a bug!

**Comment by autumnull** [comment]
Okay so it turns out in my case at least that it was less of a bug and more of *"me not reading the `config.yaml` annotations properly"* but @tsmethurst kindly looked at the api setup and found the issue :slightly_smiling_face: 

In particular:

https://github.com/superseriousbusiness/gotosocial/blob/7c6c0cd547f356d5309bda2478a69ea9346c74b6/example/config.yaml#L48-L51

My webserver runs on lighttpd, so my `/etc/lighttpd/lighttpd.conf` file now contains these lines:
```
$HTTP["host"] == "example.org" {
        # thanks, tobi!
        $HTTP["scheme"] == "https" {
                url.redirect = (
                        "^/\.well-known/webfinger(\?.+)?$" => "https://gts.example.org/.well-known/webfinger${qsa}",
                        "^/\.well-known/nodeinfo(\?.+)?$" => "https://gts.example.org/.well-known/nodeinfo${qsa}"
                )
                url.redirect-code = 308
        }
}
```

**Comment by tsmethurst** [comment]
Should I close this one now, since it was mostly resolved? The feature of fetching a user's public outbox is something we should make a separate issue for i think

**Comment by autumnull** [comment]
Yeah the only reason i left it open is because of the public outbox side of things, so it seems sensible to close it if there's one already :)
