### ISSUE TITLE
[bug] Can't Clear Notifications in Tusky

### ISSUE THREAD

**Issue by zethra** [superseriousbusiness/gotosocial#632]
### Describe the bug with a clear and concise description of what the bug is.

In Tusky, the clear button under the notifications tab doesn't do anything. On Mastodon it works. 

### What's your GoToSocial Version?

v0. 3.4

### GoToSocial Arch

amd64 Docker

### What happened?

I click the clear button in the notifications tab in Tusky and nothing happens. 

### What you expected to happen?

The notifications are cleared. 

### How to reproduce it?

Click the clear button in Tusky when notifications are present.

**Comment by tsmethurst** [comment]
Heya! This is normal: we haven't implemented that endpoint yet. I'll try to get it in soon because it's a pretty easy fix :)

**Comment by tsmethurst** [comment]
@Arteneko has volunteered to take a look at this one :)

Here's a quick little summary of the work that needs to be done:

1. create a 'delete notifications' function in the interface here: https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/notification.go and implement it here: https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/bundb/notification.go
2. add a test for the function here: https://github.com/superseriousbusiness/gotosocial/blob/main/internal/db/bundb/notification_test.go
3. Add a function to the processor here: https://github.com/superseriousbusiness/gotosocial/blob/main/internal/processing/notification.go
4. Add an api endpoint for deleting notifications here: https://github.com/superseriousbusiness/gotosocial/tree/main/internal/api/client/notification. This should follow the mastodon api for `/api/v1/notifications/clear` as described here: https://docs.joinmastodon.org/methods/notifications/

Any questions or issues or anything, please feel free to ask! :sloth:

**Comment by tsmethurst** [comment]
Closed by https://github.com/superseriousbusiness/gotosocial/issues/632
