### ISSUE TITLE
Publishing a container image

### ISSUE THREAD

**Issue by decentral1se** [superseriousbusiness/gotosocial#65]
Forgot to mention that in https://github.com/superseriousbusiness/gotosocial/issues/62 but an "upstream" (e.g. published from here) container image would be lovely. For now, I can build my own image for now but yeah, would be cool to have a `superseriousbusiness/gotosocial:latest` thing from hub.docker.com or whatever. No rush on this!

**Comment by decentral1se** [comment]
For now, I made a friendly mirror and pushed https://git.autonomic.zone/autonomic-cooperative/gotosocial/commit/f16ba8821d4da01894122d218ae9046a2bb71cc1 which runs https://drone.autonomic.zone/autonomic-cooperative/gotosocial/1/1/2 and results in https://hub.docker.com/r/decentral1se/gotosocial :partying_face: 

(if you want to use Autonomic infra for this, hmu, we could see what is possible :))

**Comment by tsmethurst** [comment]
Yup! That's one of the things I have in mind before doing a proper release, getting a CI/CD system set up in some capacity. Thanks for the offer, I'll have a think about it :)

**Comment by decentral1se** [comment]
Since the PRs are flowing in (yay!), I will politely nag you again that this would be excellent to have :) 

Then my upgrades are not such a back & forth with pulling in changes, building a container and rolling it out...

:pray:

**Comment by tsmethurst** [comment]
Docker hub repo for `superseriousbusiness/gotosocial` is now a thing, and there are docker build and push scripts inside the repo. It's not integrated into CI/CD yet, but we should probably make another issue for that one specifically.

For now, you can assume that the `0.1.0-SNAPSHOT` docker container will be kept up to date.

I'm gonna close this issue now :)
