### ISSUE TITLE
[feature] `/api/v1/instance/peers` with filter parameters

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#650]
Mastodon exposes an endpoint at `/api/v1/instance/peers` which returns a json array of domains that an instance federates with (see eg https://mastodon.social/api/v1/instance/peers):

```json
[
  "instance1.com",
  "instance2.com"
]
```

However, Mastodon does not show any json for instances that have been suspended/silenced, etc. In order to implement https://github.com/superseriousbusiness/gotosocial/issues/378, we should consider implementing this 'peers' endpoint but also allowing callers to submit query parameters to also show instances that have been suspended/silenced.

From the `gotosocial-code` Matrix chat:

---

`GET /api/v1/instance/peers` that also takes a query param `filter`

Possible values for `filter` are `friends,silenced,suspended` and you can provide any combination of these to filter the list of instances. When the value is empty, whether through no query or through `filter=` (empty), a default `filter` of `friends` is assumed.

Usage examples:

```text
GET /api/v1/instance/peers
- no filter value, default of `filter=friends` is assumed, returns only federated instances

GET /api/v1/instance/peers?filter=
- no filter value, default of `filter=friends` is assumed, returns only federated instances

GET /api/v1/instance/peers?filter=friends
- returns only federated instances

GET /api/v1/instance/peers?filter=suspended
- only returns suspended instances

GET /api/v1/instance/peers?filter=silenced
- only returns silenced instancces

GET /api/v1/instance/peers?filter=silenced,suspended,friends
- returns all known instances
```

---

We should also allow admins to limit permissions on this endpoint to authorized users only if they so desire; not everyone wants to share their blocklist/peer list since it has obvious safety implications.

When we implement https://github.com/superseriousbusiness/gotosocial/issues/3, we can consider allowing admins to also supply another instance's `/api/v1/instance/peers?filter=suspended` endpoint as a blocklist to subscribe to. This is convenient in cases where a known instance has a great block list, and a new instance wants to use the same block list without manually having to import the entries.

**Comment by dariusk** [comment]
I like this API extension. My first issue is really minor: why `friends`? Something like `unrestricted` might be more appropriate, mostly because federation does not necessarily equal a friendship relationship.

Also: are there other levels that make sense to include beside the three listed? I'm thinking about the options to _Reject media files_ and _Reject reports_ in the Mastodon domain blocking interface. These can be combined with any of the three states you list (for example, a server can be fully unrestricted and yet have all its media files rejected).

This also leads me to think the object returned should be either an array of domain strings or an array of objects in the form `{ "domain": "example.social" }`. Each object MUST have a `domain` property but servers can add arbitrary metadata (media rejected, admin notes, etc) to their exports all they want, and other servers can simply ignore the metadata.

**Comment by dariusk** [comment]
You can see that in the [PR for the domain block CSV export/import on Mastodon](https://github.com/mastodon/mastodon/pull/15664), they do [specify the additional metadata](https://github.com/mastodon/mastodon/blob/943cfa01320dabe24250749c37d3ecbbddee6332/spec/fixtures/files/domain_blocks.csv).

**Comment by tsmethurst** [comment]
Aha thank you!

> Something like unrestricted might be more appropriate, mostly because federation does not necessarily equal a friendship relationship.

This makes sense ^^ @NyaaaWhatsUpDoc what do you think?

> Also: are there other levels that make sense to include beside the three listed? I'm thinking about the options to Reject media files and Reject reports in the Mastodon domain blocking interface. These can be combined with any of the three states you list (for example, a server can be fully unrestricted and yet have all its media files rejected).

Right now GtS only supports suspending completely. We will probably add more nuanced defed/safety options for this further down the line, but I suppose we can then add those extra parameters to the endpoint as necessary.

> This also leads me to think the object returned should be either an array of domain strings or an array of objects in the form { "domain": "example.social" }. Each object MUST have a domain property but servers can add arbitrary metadata (media rejected, admin notes, etc) to their exports all they want, and other servers can simply ignore the metadata.

This is also more in line with how we serve the admin view of domain blocks at `/api/v1/admin/domain_blocks`. From our swagger docs:

```json
[
  {
    "created_at": "2021-07-30T09:20:25+00:00",
    "created_by": "01FBW2758ZB6PBR200YPDDJK4C",
    "domain": "example.org",
    "id": "01FBW21XJA09XYX51KV5JVBW0F",
    "obfuscate": false,
    "private_comment": "they are poopoo",
    "public_comment": "they smell",
    "subscription_id": "01FBW25TF5J67JW3HFHZCSD23K"
  }
]
```

So perhaps instead of an array of strings at /api/v1/instance/peers we can use a similar object...

**Comment by dariusk** [comment]
> So perhaps instead of an array of strings at /api/v1/instance/peers we can use a similar object...

Sounds good. I don't really think the extra API surface is needed, really just defining the basic object to return and allowing for extensions should be enough.

**Comment by NyaaaWhatsUpDoc** [comment]
My only concern with the term "unrestricted" is that it's quite long, very nitpicky I know but I obsess over these things :'). It can make reading debug logs, code and that kind of thing a little more tiresome.

How about "open"? 

(though I'm not hugely tied to this, if there isn't another suitable word then "unrestricted" is fine)

**Comment by tsmethurst** [comment]
'open' sounds fine to me :) I'll start coding the endpoint soon so we can play around with it and discuss this more on a PR
