### ISSUE TITLE
[bug] JSON.parse error in admin panel when saving without email

### ISSUE THREAD

**Issue by autumnull** [superseriousbusiness/gotosocial#652]
### Describe the bug with a clear and concise description of what the bug is.

The built-in admin panel shows the error `JSON.parse: unexpected character at line 1 column 1 of the JSON data` if i click the save button without filling out the `Email` field.

### What's your GoToSocial Version?

v0.3.5

### GoToSocial Arch

armv7 Binary

### What happened?

Clicking the save button on the admin panel without the `Email` field filled in displays
```
JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
at the top of the form, and doesn't save the settings.

### What you expected to happen?

The settings should save and show `Config saved` at the top, or if it's intended to require an email then error page should display properly.

### How to reproduce it?

Go to admin panel, hit save without the `Email` field filled.

### Anything else we need to know?

Looking at the network tab in the browser debugger, I found that it's returning a `400: Bad Request` error, where the response contains some HTML:
```html
<!DOCTYPE html>


<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="og:title" content="[REDACTED HOST DOMAIN] - GoToSocial">
	<meta name="og:description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="/assets/dist/_colors.css">
	<link rel="stylesheet" href="/assets/dist/base.css">
	
	<link rel="shortcut icon" href="/assets/logo.png" type="image/png">
	<title>[REDACTED HOST DOMAIN] - GoToSocial</title>
</head>
<body>
	<div class="page">
		<a href="/" class="nounderline">
			<header>
				<img src="/assets/logo.png" alt="Instance Logo"/>
				<div>
					<h1>
						[REDACTED HOST DOMAIN]
					</h1>
				</div>
				<div></div>
			</header>
		</a>

    <main>
        <section class="error">
          <span>❌</span> <pre>Bad Request: no email provided</pre>
        </section>
    </main>
		
		<footer>
			<div id="version">
				GoToSocial: <span class="accent">0.3.5 git-13e4bbd</span><br>
				<a href="https://github.com/superseriousbusiness/gotosocial">Source Code</a>
			</div>
			<div id="contact">
				
			</div>
			<div id="email">
				
			</div>
		</footer>
	</div>
	
</body>
</html>
```

This HTML is not displayed, however (i'm on latest stable firefox).

**Comment by tsmethurst** [comment]
Thanks for opening this!

I think one thing we need to do now with the admin panel is have it add 'Accept: application/json' to its request headers.

And I also need to update the instance patch endpoint to allow submitting an empty email address

**Comment by xmgz** [comment]
this might be related to this

![bug-gts](https://user-images.githubusercontent.com/704948/175291863-36be27a0-73df-462f-b115-349ed803714c.png)

It is GtS 0.3.6 admin panel, this json error happens after trying to save changes on

**Comment by tsmethurst** [comment]
Yes probably! I'll fix it up for the next release :) In the meantime, can you try filling in an email address in the email field? It doesn't have to be a real address, just something... Then we can see if it's the same issue

**Comment by xmgz** [comment]
Yes! it works fine IF I fill email field. Both description and short description are saved and no JSON error is reported.
