### ISSUE TITLE
[bug] Disallow following/blocking yourself

### ISSUE THREAD

**Issue by autumnull** [superseriousbusiness/gotosocial#664]
### Describe the bug with a clear and concise description of what the bug is.

It's currently possible for an authenticated user to follow/block themself. I feel like this is weird behavior and shouldn't be possible.

### What's your GoToSocial Version?

v0.3.6

### GoToSocial Arch

armv7 Binary

### What happened?

submitting an api request to `/api/v1/accounts/{id}/follow` (or `.../block`) with the currently authenticated user's id returns a `relationship` saying that you have followed/blocked yourself.

### What you expected to happen?

should probably return a `Error 406 (not acceptable)` ?

### How to reproduce it?

get an oauth token for an account, submit an api request as described above to the same account you auth'd with.

**Comment by tsmethurst** [comment]
Haha, yes, this is definitely a bug :') Thank you!
