### ISSUE TITLE
[bug] frontend assets don't get proper Last-Modified headers

### ISSUE THREAD

**Issue by f0x52** [superseriousbusiness/gotosocial#669]
especially as the frontend starts to change more it's quite annoying to have (partly) cached versions used by clients, that can only bring pain in the future

**Comment by tsmethurst** [comment]
i'm looking into this and *apparently* the `Static` functionality on the gin router should provide these headers for us, since under the hood it just uses `http.ServeFile`. However it doesn't seem to be doing that, so i'll do more digging

**Comment by tsmethurst** [comment]
Hmm wait, no, it does set proper last-modified headers

![Screenshot from 2022-06-29 16-53-24](https://user-images.githubusercontent.com/31960611/176467864-289be75a-cb86-4b79-ada6-8183ed1a61f6.png)

Perhaps the issue is that we don't set cache-control headers anywhere in GtS...

**Comment by tsmethurst** [comment]
dropping this link here for future self

https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#etagif-none-match
