### ISSUE TITLE
[bug] No documented way to change the thumbnail in the `/v1/instance` API response

### ISSUE THREAD

**Issue by tsal** [superseriousbusiness/gotosocial#671]
### Describe the bug with a clear and concise description of what the bug is.

Since some clients require the thumbnail value to exist for the instance model, it would be nice if there were an easy-to-find, documented method to change that thumbnail. As it stands, I have tried a dozen searches on two different engines, with no luck. Either SEO is hiding the information, or it simply does not exist.

### What's your GoToSocial Version?

v0.3.6

### GoToSocial Arch

amd64 docker

### What happened?

Fresh, configured installation that appears to be federated, but some clients simply will not work because the server is returning a bad / loose model that doesn't conform to the client expectations.  Since I can see it being returned as an empty value, my assumption is, there is an _intention_ to be able to configure this value, but no interface can be found for doing so -- the closest found is value is listed as an empty, uneditable string in the admin panel.

### What you expected to happen?

I expect to be able to update the instance thumbnail or for it to default to a sane, non-empty value.

### How to reproduce it?

Fresh docker instance.

**Comment by tsal** [comment]
It seems like this is mostly on my end, but I am thinking the host account should be included in the initial setup documentation, maybe?

**Comment by tsmethurst** [comment]
Thanks for opening this! I'll take a look at fixing it up, for now, by just putting a link in there to the sloth icon, and in future we can make it properly customizable when we do our admin panel rework :) That should at least fix the problem for clients who are looking for a value there.

> It seems like this is mostly on my end, but I am thinking the host account should be included in the initial setup documentation, maybe?

Can you explain this? Not sure what you mean
