### ISSUE TITLE
[bug] Code spans aren't HTML escaped in markdown posts

### ISSUE THREAD

**Issue by autumnull** [superseriousbusiness/gotosocial#679]
### Describe the bug with a clear and concise description of what the bug is.

When using the markdown format, code spans (`like this`) containing HTML aren't HTML-escaped during processing.

### What's your GoToSocial Version?

v0.3.6

### GoToSocial Arch

armv7 Binary

### What happened?

making a post with the markdown format with the following contents
```markdown
`Nobody tells you about the </code><del>SECRET CODE</del><code>, do they?`
```
results in a post with this content:
```html
<p><code>Nobody tells you about the </code><del>SECRET CODE</del><code>, do they?</code></p>
```
which is rendered as this:
<p><code>Nobody tells you about the </code><del>SECRET CODE</del><code>, do they?</code></p>

### What you expected to happen?

should result in the following HTML (or similar):
```html
<p><code>Nobody tells you about the &lt;/code&gt;&lt;del&gt;SECRET CODE&lt;/del&gt;&lt;code&gt;, do they?</code></p>
```
which is rendered as this:

<p><code>Nobody tells you about the &lt;/code&gt;&lt;del&gt;SECRET CODE&lt;/del&gt;&lt;code&gt;, do they?</code></p>

### How to reproduce it?

Get an oauth token, send a request to make a new post in markdown format with the content above.

**Comment by tsmethurst** [comment]
Thanks! I'll check it out soon :)
