### ISSUE TITLE
[bug] Tusky: searching for @user@instance goes into a UI discovery loop

### ISSUE THREAD

**Issue by decentral1se** [superseriousbusiness/gotosocial#68]
I don't have a nice way to take a  screencast from my phone right now but when I search for @user@instance in the tusky interface, when the account is found, the interface starts to endlessly list them in a loop. You can still choose the first user found and the follow works out, so this is not blocking me in any way. Hope that is clear :+1:

**Comment by videogame-hacker** [comment]
Just discovered this myself -- I think we need to handle some pagination thing?

**Comment by charlag** [comment]
Here's the source for search:
https://github.com/tuskyapp/Tusky/blob/4159826f266d7c6b69738d0668c43b33b68b51c8/app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchPagingSource.kt#L38

I think we will keep requesting with new `offset` until we get empty result

**Comment by tsmethurst** [comment]
AH thank you! This is helpful :)
