### ISSUE TITLE
[bug] Some characters in tags are not correctly parsed

### ISSUE THREAD

**Issue by xmgz** [superseriousbusiness/gotosocial#681]
### Describe the bug with a clear and concise description of what the bug is.

 tags in user's profile are no correctly treated as tags, it breaks at different non english characters. Same happens in posts.

### What's your GoToSocial Version?

0.3.6 YNH

### GoToSocial Arch

arm YNH version

### What happened?

look at this example

![image](https://user-images.githubusercontent.com/704948/176826358-07674d9e-9acc-45c6-b982-8932f56a74bf.png)

**same happens in posts** when using "é", "ó", ... characters. I've not tested other non english letters.

### What you expected to happen?

correctly read words and set it as tags

### How to reproduce it?

just post any comment using this characters, not tested with different 

### Anything else we need to know?

I don't know if this is controlled by any key in config.file, but I have not found any.

My system (debian based) is correctly using/displaying my language preferences.

thank you

**Comment by tsmethurst** [comment]
Thanks for opening this! This is because of the regular expressions we use, I'll fix them up soon :)

**Comment by illfygli** [comment]
Maybe `… [\p{L}\p{N}] …`? I think that would be the unicode-aware equivalent.

**Comment by tsmethurst** [comment]
> Maybe `… [\p{L}\p{N}] …`? I think that would be the unicode-aware equivalent.

Yes!! Thank you :)
