### ISSUE TITLE
[bug] Page overflows to the right on mobile

### ISSUE THREAD

**Issue by zethra** [superseriousbusiness/gotosocial#691]
### Describe the bug with a clear and concise description of what the bug is.

On mobile, various page overflow to the right of the view port and introduce a right scroll.

![image](https://user-images.githubusercontent.com/6034238/177204271-876c613b-273e-43ec-bf6a-f872a5ddca7c.png)

### What's your GoToSocial Version?

0.3.7

### GoToSocial Arch

amd64

### What happened?

See above

### What you expected to happen?

No horizontal scroll

### How to reproduce it?

Load a GtS page on mobile, possible with enough content. Testrig triggers it.

**Comment by tsmethurst** [comment]
Fixed with recent changes :)
