### ISSUE TITLE
[feature] Account self-registration

### ISSUE THREAD

**Issue by innogrey** [superseriousbusiness/gotosocial#703]
### Is your feature request related to a problem ?

If the question is absurdly stupid, please ignore it. I definitely lack experience with fediverse. The configuration file contains the "accounts-registration-open:" option. I assume that when it is set to 'true', users can self-register accounts. And now the question arises: how? where? The suggested front-ends do not provide the option 'register an account'. Can someone clarify whether the option is unimplemented, or maybe some custom api access is needed here, or have I gone very much astray. Thanks in advance.

### Describe the solution you'd like.

A way to self-register an account

### Describe alternatives you've considered.

No alternatives really

**Comment by tsmethurst** [comment]
Heya! Thanks for opening this :)

The `accounts-registration-open` option is implemented! But unfortunately right now we don't have a sign-up page for new accounts. It's planned but not there yet.

In the meantime, indeed it's something you have to do via the API; check the first option under the 'accounts' section here: https://docs.gotosocial.org/en/latest/api/swagger/. There's also a script here demonstrating the account registration flow: https://github.com/superseriousbusiness/gotosocial/blob/main/scripts/auth_flow.sh

In future we'll make a nice page for this for people who want to join an instance :)

**Comment by tolstoevsky** [comment]
Hi!
Any news around this feature? May we hope it's coming soon? :)
