### ISSUE TITLE
[feature] Footer links for imprint and privacy policy

### ISSUE THREAD

**Issue by boerge30** [superseriousbusiness/gotosocial#707]
### Is your feature request related to a problem ?

No footer links for the imprint and privacy policy (DSGVO / GDPR Stuff).

### Describe the solution you'd like.

I am looking for a simple way to use footer links for the imprint and the privacy policy (DSGVO / GDPR). Best via the admin interface, as it already works with the e-mail and the username.

### Describe alternatives you've considered.

None

**Comment by tsmethurst** [comment]
Thanks for raising this! In future we'll have a 'terms of service' or 'terms and conditions' thing linked on the front page of the instance that users can read. You could put GDPR info there. Would that fit the bill?

**Comment by boerge30** [comment]
Definitely! Thanks :)

**Comment by tsmethurst** [comment]
Whoops
