### ISSUE TITLE
[bug] Minor margin, size, and border radius issues on profiles

### ISSUE THREAD

**Issue by foreverxml** [superseriousbusiness/gotosocial#712]
### Describe the bug with a clear and concise description of what the bug is.

The frontend profiles have some minor graphical bugs present on them. Namely, wrongly-sized header images (see below):

![Wrongly sized header image of owl@u8.is](https://user-images.githubusercontent.com/52264162/179310758-257710ff-4188-48b4-8069-11c79ec3cd3f.png)

That can be fixed by adding the following CSS:
```css
.profile .headerimage {
    width: 100%;
    overflow: hidden;
 -o-object-fit: cover;
    object-fit: cover;
}
```
However, there is also a wrongful spacing between the images and the border of their box (see top circle in figure) and rounding issues as well (see bottom circle):

![photo of the two issues above](https://user-images.githubusercontent.com/52264162/179311519-52b78c41-6044-428c-aafd-2a7a40ef0a20.png)

The one on the profile picture can be fixed by applying the border to the image itself, but I haven't found a fix for the header image one.

### What's your GoToSocial Version?

v0.3.7

### Anything else we need to know?

No, but please reach out if you have any further questions :D

**Comment by tsmethurst** [comment]
Thank you!! I think we fixed some of these on main already, but some not, so I'll check :)

**Comment by tsmethurst** [comment]
whoops

**Comment by tsmethurst** [comment]
Right, I double checked with this same level of zoom and indeed we've got the header image fitting pretty nicely now (see image) cuz of some recent changes by me and f0x:

![Screenshot from 2022-07-17 10-06-45](https://user-images.githubusercontent.com/31960611/179389654-6ade3749-3b83-4ecf-8eaf-0ab7525a0595.png)

But yes, some of the rounding on the edges is still off, so I'll make sure to fix that up before we do another release :)
