### ISSUE TITLE
Support migrations for new versions

### ISSUE THREAD

**Issue by decentral1se** [superseriousbusiness/gotosocial#72]
When new commits roll out and they require database migrations, it would be nice to have some way to automatically run those migrations on the deployment side when deploying the new binary version. I use the Docker deployment myself, so having it there would be handy too. For now, having the commands to run in `psql` is fine ofc.

(Also discussed in the matrix room and wanted to help keep track of this one too :+1:)

**Comment by tsmethurst** [comment]
Closed by #297
