### ISSUE TITLE
[feature] Add links to frontend pages

### ISSUE THREAD

**Issue by martijndeb** [superseriousbusiness/gotosocial#729]
### Is your feature request related to a problem ?

I've extended GoToSocial with [some pages for my friends](https://github.com/sexybiggetje/gotosocial-oncaffeine) to help them get around (and I plan to do some more things). I would like to link them from at least the homepage. This currently requires me to patch the index template on every release.

### Describe the solution you'd like.

I would love to have a list of links in the config file that work as key value for the link title and page.
My files are served from another folder, so I don't actually require them to be served (the webserver takes care of that).
Since I'd like to also include another subdomain in the list, I would both need absolute and relative paths. It can be very simple :-).

### Describe alternatives you've considered.

NONE

### Additional context.

I currently patch in a simple section with 3 links; which looks like the following.
![Screenshot 2022-07-23 153213](https://user-images.githubusercontent.com/60222/180607247-76c794cb-6597-46c3-8fb0-8b7db0a7731e.png)

**Comment by tsmethurst** [comment]
Gonna close this now since it's possible to add a list of links using the short description :)
