### ISSUE TITLE
[feature] Make fields for OIDC username/display name etc configurable

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#763]
Right now we just use the `Name` field of the OIDC claim for username. We should make it possible for instance admins to configure which claim field(s) should map to which User fields.

This will require adding some new config options in the `internal/config` package (and updating cli tests), fleshing out the `Claims` struct in `internal/oidc` to add more standard OIDC fields, and also updating the `parseUserFromClaims` function in `internal/api/client/auth/callback.go` to map using the configured fields rather than hardcoded ones.

To avoid breaking any existing deployments, the config should still use Name as the default Username mapping.

To support all this, we should write some decent OIDC documentation!

Handy document explaining different claims + scopes etc: https://developer.okta.com/blog/2017/07/25/oidc-primer-part-1

**Comment by theSuess** [comment]
I really like the gitea approach: On first registration prompt the user for a desired username/displayname but prefill it with claims from the token.

This also offers an easy fallback regarding #309

**Comment by tsmethurst** [comment]
closed by https://github.com/superseriousbusiness/gotosocial/pull/961
