### ISSUE TITLE
[feature] Show link to unsupported media rather than dropping it completely

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#765]
Right now we totally drop unsupported media from statuses (videos for instance) instead of processing them, so the user gets presented with a status that doesn't appear to have any media attached to it at all.

Often, though, the text of a status pertains to the media attached to it. Example: a video of a cat with the status text 'she's cute'. In GtS this would just look like a status that says 'she's cute' with no other context. This is confusing!

Instead of doing this, we should provide a link in the timelined status to the original URL. We should investigate how Mastodon does this so that we can ensure that clients using GtS will also be able to handle this.

This isn't just an interim measure until we implement video support: it'll be useful in future as well for other file types that GtS might never support.

**Comment by tsmethurst** [comment]
![Screenshot from 2022-09-08 18-19-41](https://user-images.githubusercontent.com/31960611/189174339-019d5b4b-a834-4c6d-a8b7-af49b99bfda7.png)

for future reference, this is how mastodon serves unknown attachments via the api ^

**Comment by Follpvosten** [comment]
I can only say that this would be really nice. I've been seeing empty posts where people just uploaded a video and that was also really confusing until now (when I tried to search the issues). Makes sense that support for some stuff just isn't implemented yet, and would be great to know about it as a user.

**Comment by tsmethurst** [comment]
Closed by https://github.com/superseriousbusiness/gotosocial/pull/2331
