### ISSUE TITLE
[bug] Unhelpful error message when trying to upload a profile picture that is too large

### ISSUE THREAD

**Issue by DysphoricUnicorn** [superseriousbusiness/gotosocial#771]
### Describe the bug with a clear and concise description of what the bug is.

When trying to upload a profile picture that is too large, the server will respond with a default NGINX 413 error page.  
Since that page is not valid JSON, the error description shown only displays `Unexpected token '<', "<html> <h"... is not valid JSON`.

### What's your GoToSocial Version?

v0.4.0-rc2

### GoToSocial Arch

Kubernetes (Docker image running with containerd)

### What happened?

A non helpful error message was shown after I tried to upload a large image as my profile picture. (The image was in 16:9 aspect ratio and 1920x1080 resolution) 

### What you expected to happen?

Best case would if a cropping tool could pop up but I know that this is a ton of work.  
In either case, a 413 status code should be handled and a specific error message should be shown.

### How to reproduce it?

Try to upload a very large profile picture using the user settings

**Comment by tsmethurst** [comment]
Ah thanks for opening this :) This is via the user panel right? Will add some fallback behavior for when the response can't be parsed as JSON.

As a workaround, you perhaps saw this already, but we added the line `client_max_body_size 40M;` to the nginx config here: https://docs.gotosocial.org/en/latest/installation_guide/nginx/#set-up-nginx

**Comment by DysphoricUnicorn** [comment]
Thanks for the quick response ^^

Yes, I was using the user panel, I didn't try any third party clients for profile editing so far

**Comment by tsmethurst** [comment]
Alrighty, will put it on my to-do list :)
