### ISSUE TITLE
[bug] mastodon-twitter-poster doesn't seem to work

### ISSUE THREAD

**Issue by blackle** [superseriousbusiness/gotosocial#790]
### Describe the bug with a clear and concise description of what the bug is.

Connecting https://github.com/renatolond/mastodon-twitter-poster to a gotosocial account seems to work, but is unable to crosspost anything to twitter

### What's your GoToSocial Version?

v0.4.0

### GoToSocial Arch

amd64 binary

### What happened?

Connected mastodon-twitter-poster to my gotosocial account using oauth. Changed mastodon-twitter-poster settings to cross-post mastodon to twitter. made a public post on gotosocial. post wasn't cross-posted

### What you expected to happen?

Posts are cross-posted to twitter

### How to reproduce it?

Connect mastodon-twitter-poster to my gotosocial account using oauth.
Chang mastodon-twitter-poster settings to cross-post mastodon to twitter.
made a public post on gotosocial

**Comment by tsmethurst** [comment]
Did you see any errors on GtS when doing this? And, if you host the crossposter, did you see any errors there? 

It might also be worth trying it again since https://github.com/superseriousbusiness/gotosocial/commit/4e13408fd48105d591c3f0f716641f1ef928817c was merged

**Comment by blackle** [comment]
crossposter seems to work now!
