### ISSUE TITLE
[feature] Allow admins to upload / delete custom emojis via admin panel

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#797]
The admin section of the settings panel needs a subsection for emojis.

Here, admins should be able to:

- [x] View custom emojis present on the instance
- [x] (`GET /api/v1/admin/custom_emojis[?filter=local]`, returns an array of emojis like from `/api/v1/custom_emojis` but including domain, date uploaded, last updated, id, etc).
- [x] Upload a new custom emoji, with a shortcode and category (`POST /api/v1/admin/custom_emojis`) -- ideally, admins can drag and drop an emoji file into a box and see how it'll actually look when rendered on the instance, but this is probably FIDDLY so basic implementation of selecting a file + uploading it is fine to start with.
- [ ] Delete a custom emoji, either local or remote (`DELETE /api/v1/admin/custom_emojis/{id}`)
- [ ] Use `PUT` or `PATCH`? to `/api/v1/admin/custom_emojis/{id}`:
  - [ ] Modify a local custom emoji -- set a new image for it, put it in a different category, etc
  - [ ] Disable/suspend a remote custom emoji
  - [ ] Copy a remote emoji to local

**Comment by tsmethurst** [comment]
Gonna work on this one now: https://github.com/superseriousbusiness/gotosocial/issues/821

And then work on the PATCH endpoint mentioned above :)

**Comment by xplosionmind** [comment]
When visiting `https://gts.superseriousbusiness.org/settings/admin/custom-emoji` I get this.

```
An error occured, please report this on the [GoToSocial issue tracker](https://github.com/superseriousbusiness/gotosocial/issues) or [Matrix support room](https://matrix.to/#/#gotosocial-help:superseriousbusiness.org).
Include the details below:

TypeError: t is undefined

[112]</module.exports/r<@https://gts.superseriousbusiness.org/assets/dist/settings.js:2831:1567
useMemo@https://gts.superseriousbusiness.org/assets/dist/settings.js:2268:70076
[75]</exports.useMemo@https://gts.superseriousbusiness.org/assets/dist/settings.js:1785:6231
[112]</module.exports@https://gts.superseriousbusiness.org/assets/dist/settings.js:2831:1548
Xh@https://gts.superseriousbusiness.org/assets/dist/settings.js:2268:63826
Wk@https://gts.superseriousbusiness.org/assets/dist/settings.js:2268:120234
Vk@https://gts.superseriousbusiness.org/assets/dist/settings.js:2268:111701
Uk@https://gts.superseriousbusiness.org/assets/dist/settings.js:2268:111632
Jk@https://gts.superseriousbusiness.org/assets/dist/settings.js:2268:111499
Ok@https://gts.superseriousbusiness.org/assets/dist/settings.js:2268:107940
Fk@https://gts.superseriousbusiness.org/assets/dist/settings.js:2268:108744
jg@https://gts.superseriousbusiness.org/assets/dist/settings.js:2268:47683
[38]</Ek/<@https://gts.superseriousbusiness.org/assets/dist/settings.js:2268:106280
```
