### ISSUE TITLE
[bug] Content sizing covering complete width on UXP-based web browsers such as Pale Moon

### ISSUE THREAD

**Issue by EchedeyLR** [superseriousbusiness/gotosocial#800]
### Describe the bug with a clear and concise description of what the bug is.

The content size, specifically the width, of the front page as far as I could test, is covering the whole web browser window.

This happens just to UXP-based web browsers, and I think that is due to a bad setting in the `grid-template-columns` setting a value of `auto min(92%, 90ch) auto`, for which `min` function is not available there.

### What's your GoToSocial Version?

0.4.0

### GoToSocial Arch

x86_64 (amd64) Binary

### What happened?

The content size, specifically the width, of the front page is covering the whole web browser window.

I attach a screenshot for it:
![Vis4Valentine_Social_-_GoToSocial_2022-09-02_21-26-14](https://user-images.githubusercontent.com/56733813/188231973-cbec5f7e-7617-4659-b14a-ef952104de85.png)

### What you expected to happen?

Content size being seeing with a proportionate width according to the web browser window.

### How to reproduce it?

Load any front page of any GoToSocial instance in version 0.4.0 with an UXP-based web browser.

### Anything else we need to know?

As written before, the issue is the `min` function in `grid-temlate-columns` and more information of widely supported things are at [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns).

**Comment by EchedeyLR** [comment]
After some tweaking, `auto minmax(auto, 90ch) auto` could make the trick.

**Comment by illfygli** [comment]
Would it be an option to add support for `min()` to Pale Moon?
So that other websites work better too.

**Comment by EchedeyLR** [comment]
Not sure how ahead is in their queue, since Web Components is a task on it too and is a big thing but generally, yes, they should with time, sooner if it is part of a standard.

Anyways, the example I wrote fixes the issue for Pale Moon (and keep it working for other web browsers) using already supported features.

**Comment by tsmethurst** [comment]
Thanks for investigating this! Will try to get a fix in soon :)

**Comment by EchedeyLR** [comment]
Thanks to you for this incredible software. :3
