### ISSUE TITLE
[feature] admin status in Account response

### ISSUE THREAD

**Issue by f0x52** [superseriousbusiness/gotosocial#814]
for clients to tell if the user that logged in is admin or not, and can perform admin actions. Mastodon API does not seem to have an equivalent anywhere, but uses the term `role` for this I think?

Could be returned in `api/v1/verify_credentials` and `/api/v1/accounts/{id}`
```json
{
  "acct": "some_user@example.org",
  "role": "admin",
  ...
}
```

**Comment by f0x52** [comment]
It would also be useful in `/api/v1/accounts/{id}` responses, so clients can show roles too (open mastodon issue from 2018 https://github.com/mastodon/mastodon/issues/7108#issuecomment-395953636)

**Comment by tsmethurst** [comment]
I had a look around!

Mastodon user roles are defined here: https://github.com/mastodon/mastodon/blob/main/app/models/user_role.rb

And they're serialized to the api via the admin view of accounts: https://github.com/mastodon/mastodon/blob/main/app/serializers/rest/admin/account_serializer.rb#L23-L25 and verify_credentials: https://github.com/mastodon/mastodon/blob/main/app/serializers/rest/credential_account_serializer.rb#L21-L23

It looks like Mastodon returns an object there representing the user role and the various permissions and flags that user role allows, but I think we can keep this simple and just return `"admin"` if the user is an admin, and either `null` or `"user"` or something if they're not.

And yeah indeed we should add that to the /api/v1/accounts/{id} representation as well, agree with you there.

**Comment by tsmethurst** [comment]
Aha! It's serialized like this: https://github.com/mastodon/mastodon/blob/main/app/serializers/rest/role_serializer.rb

> it has `id` (arbitrary string, but numeric in practice), `name`, `permissions` (it's a large integer in string representation, it's actually a bitfield of individual permissions), `color` (hex code), `highlighted` a boolean which does… something (i think it's to display the thing at all on public pages)

Thanks @ClearlyClaire !
