### ISSUE TITLE
[feature] `image-rendering: pixelated` switch on images in frontend

### ISSUE THREAD

**Issue by autumnull** [superseriousbusiness/gotosocial#817]
### Is your feature request related to a problem ?

- Pixel Art!! But it scales really bad :(
- Photos!! But they look really bad with [`image-rendering: pixelated`](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering) set in the CSS :(

### Describe the solution you'd like.

What if there was a switch so u could toggle a class with the `image-rendering: pixelated` CSS property??

### Describe alternatives you've considered.

NONE

### Additional context.

![pixel-art of a kunekune pig](https://user-images.githubusercontent.com/86073772/189526503-d680317f-6ed1-4ba7-ba4c-94e08c62300e.png)

Then u could see things like this beautiful hog at full-lightbox size!

**Comment by tsmethurst** [comment]
Hmm you mean on the web ui? (also, cute hog)

**Comment by autumnull** [comment]
yep on the web ui

**Comment by tsmethurst** [comment]
ah, can you link to an example of it looking shitty? i don't think i have any examples to hand

**Comment by autumnull** [comment]
https://social.tranarchy.fish/@microfag/statuses/01GCP60QQ4JDF1EKH6E0288GS1

**Comment by tsmethurst** [comment]
Ahh thanks. Right yeah, that preview image looks real bad indeed. I'll see if we can fiddle with it some :)

**Comment by autumnull** [comment]
yeh on the one hand there's the thumbnail-generation making the thumbnail look weird but u'd probably have to add an option in the media-upload api to make that not look deep-fried with interpolation/compression.

but i think it would b cool if u could scale up tiny images in the lightbox somehow or something

**Comment by EchedeyLR** [comment]
Advice that `crisp-edges` was the only supported option for the `image-rendering` property until Firefox 92 and that Chromium-based web browsers don't support `crips-edges`. 

I would suggest adding both for web compatibility.

**Comment by tsmethurst** [comment]
I'm gonna close this now because we're probably not gonna do it as it's quite niche *BUT* you can at least now use custom CSS for your profile to set `image-rendering: pixelated` if you wanna :) So for example it could be useful to set it on accounts that just post lots of pixel art.
