### ISSUE TITLE
[bug] Login on iOS app tooot not possible

### ISSUE THREAD

**Issue by 42gb** [superseriousbusiness/gotosocial#825]
### Describe the bug with a clear and concise description of what the bug is.

Login unsuccessful with iOS app tooot (https://apps.apple.com/us/app/tooot/id1549772269)

### What's your GoToSocial Version?

0.5.0-rc1

### What happened?

Account was not added after login

### What you expected to happen?

GTS account should be useable in tooot.

### How to reproduce it?

- Add new account in tooot
- GTS login shows up as usual
- User enters credentials
- It looks like login was successful
- User gets forwarded to app. 

Overview of all accounts is shown. GTS account is not listed here. User is not able to use GTS via tooot. 

### Anything else we need to know?

(I also tested other iOS apps. No problems with Metatext and Toot!)

**Comment by tsmethurst** [comment]
Thanks for opening this!

**Comment by xmflsct** [comment]
Happy to help test if the API is compatible with Mastodon's.

**Comment by mirabilos** [comment]
Is there an iPhone äpp recommended to work with this?

**Comment by worldofgeese** [comment]
Together with @mirabilos I am also interested. Right now the README doesn't have an iOS client app suggestion. Pinafore is a webapp but what most users will want to reach for is a "real" app especially given Apple's hostility toward webapps.

**Comment by mirabilos** [comment]
Tao dixit:

>Together with @mirabilos I am also interested. Right now the README
>doesn't have an iOS client app suggestion. Pinafore is a webapp but

Metatext seems to work reasonably well (haven’t used it much though)
and is even OSS.

bye,
//mirabilos
-- 
  "Using Lynx is like wearing a really good pair of shades: cuts out
   the glare and harmful UV (ultra-vanity), and you feel so-o-o COOL."
                                         -- Henry Nelson, March 1999

**Comment by hrkfdn** [comment]
Can confirm this for the Android app as well.

**Comment by cimm** [comment]
On iOS I tried Metatext, tooot, Mastoot and Mastodon for iPhone and iPad with GoToSocial 0.5.2 git-c31f219. I am using Apache as a reverse proxy and the LetsEncrypt certs are handled by Apache, not GtS.

Metatext seems to work best. I can login and post toots. The "Messages" section in Metatext gives a 404 error and using the "Explore" function to find other fediverse accounts works sometimes. Even if it finds the account I want to follow the list with toots is empty. So far I can only use it to post, not to follow others.

The other iOS apps I tried: tooot, Mastoot and Mastodon detect the login and open the in app GtS login page but silently fail after authenticating. I can't get past the login screen.

With Pinafore I have the same success rate as Metatext. Loggin and posting toots works but when I search for an account on another server I get the avatar and banner but no toots.

Maybe I misunderstand how federation is supposed to work.

**Comment by xmflsct** [comment]
Added support of GoToSocial, will be released soon.

**Comment by daenney** [comment]
I think we can close this now based on https://github.com/tooot-app/app/commit/a3b5a132c59aeaeec1d6cb7eaf0252bb5e3b0dbd? Based on the tags it's been fixed since 4.8.0 and 4.8.7 is available in the app store currently.

**Comment by tsmethurst** [comment]
Thanks!
