### ISSUE TITLE
[bug] Admin panel: new instance block has wrong date+time initially

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#870]
This is fixed when refreshing the page. Example of wrong value:

![image](https://user-images.githubusercontent.com/31960611/193303265-6008a1a5-85a0-4539-ba39-2bd512b23f1b.png)

**Comment by f0x52** [comment]
This is actually an API issue, POST /api/v1/admin/domain_blocks returns `created_at: 0001-01-01T00:00:00.000Z`. (which then gets parsed and displayed in the frontend)

**Comment by tsmethurst** [comment]
Aha thanks @f0x52 !
