### ISSUE TITLE
[bug] Can't create poll with pinafore / try to extract ints from string parameters

### ISSUE THREAD

**Issue by noerw** [superseriousbusiness/gotosocial#898]
### Describe the bug with a clear and concise description of what the bug is.

Creating a poll in pinafore 2.2.1 fails with a HTTP 400 response: `"Bad Request: json: cannot unmarshal string into Go struct field PollRequest.poll.expires_in of type int"`.
What pinafore sends is a string: `"expires_in": "86400"`.

I don't know about the spec,but I guess it's arguable that pinafore sends a bogus request. Maybe GtS could try to parse requests like these. Feel free to close this if you consider this out of scope.

### What's your GoToSocial Version?

0.5.2 git-c31f219

**Comment by tsmethurst** [comment]
Heya! Polls aren't implemented yet. They're on the [roadmap](https://github.com/superseriousbusiness/gotosocial/blob/main/ROADMAP.md) for the beginning of next year. We'll sort out the parsing issues etc when we do the implementation, so I'm gonna close this issue for now :)
