### ISSUE TITLE
[bug] `media-description-min-chars` config not enforced at toot time

### ISSUE THREAD

**Issue by noerw** [superseriousbusiness/gotosocial#899]
### Describe the bug with a clear and concise description of what the bug is.

It seems #369 broke the `media-description-min-chars` config var, as I was able to post a toot with an image, without entering a image description.

### What's your GoToSocial Version?

0.5.2 git-c31f219

### What you expected to happen?

It shouldn't be possible to toot without an image description if `media-description-min-chars: 1` is configured.

→ the `POST /toot` endpoint (pardon, idk what its URL actually is) should enforce the `media-description-min-chars` config on all referenced media items.

### How to reproduce it?

- run GtS with `media-description-min-chars: 5` in config.
- log in with pinafore 2.2.1
- upload image
- toot
- observe a successful toot without image description

### Anything else we need to know?

Previous disussion in #338

**Comment by tsmethurst** [comment]
Thanks for opening this! I'll investigate!
