### ISSUE TITLE
[bug] admin account create does not check for email unicity

### ISSUE THREAD

**Issue by flo-dhalluin** [superseriousbusiness/gotosocial#903]
### Describe the bug with a clear and concise description of what the bug is.

CLI account creation does not check for email unicity

### What's your GoToSocial Version?

v0.5.2

### GoToSocial Arch

amd63

### Browser version

N/A

### What happened?

Created two users with the same email with CLI does not issue any warnings, can't login with either passwords it seems

### What you expected to happen?

second time you create a user with an existing email would loudly fail ? 

### How to reproduce it?

Using the CLI tool 

```
./gotosocial --config-path ...  admin accounts create --username admin --email john@doe.com  
./gotosocial --config-path ...  admin accounts create --username john --email john@doe.com
```

**Comment by tsmethurst** [comment]
Thanks, will check this one out!

**Comment by igalic** [comment]
for next time, maybe use
```
./gotosocial --config-path ...  admin accounts create --username admin --email john+admin@doe.com  
./gotosocial --config-path ...  admin accounts create --username john --email john@doe.com
```
