### ISSUE TITLE
[bug] I miss my language for posting

### ISSUE THREAD

**Issue by xmgz** [superseriousbusiness/gotosocial#906]
### Describe the bug with a clear and concise description of what the bug is.

when user is logged and visits `https://gotosocial.domain.tld/user` page, they can set what **language wants to use for posting**

![gts_lang_selc](https://user-images.githubusercontent.com/704948/195251180-aebb0562-88aa-4b66-a51e-532a15593522.png)

my language (galego) is not listed there, so please add it to the drop down menu :smiley: 

ISO639 language code is `gl`, _galician_ (in english)

I don't know where did you get that list, but is incomplete though

### What's your GoToSocial Version?

GoToSocial 0.5.2 git-c31f219

### Browser version

any

### What happened?

can't set my language for posting so post are not signaled as _galician_

### What you expected to happen?

my language listed in the dropdown menu to be selected **AND post marked as galician**

### How to reproduce it?

go to your user page and try to select galician language

### Anything else we need to know?

I appreciate your work and many thanks for it. Remember I volunteered for translating user/admin interface to spanish and galician  when development reaches that point.

Thank you

**Comment by tsmethurst** [comment]
Thank you! We will add it :)

> Remember I volunteered for translating user/admin interface to spanish and galician when development reaches that point.

:heart:
