### ISSUE TITLE
[bug] Posts with a Date in the Future will always show at the top of the federated Timeline

### ISSUE THREAD

**Issue by 0hlov3** [superseriousbusiness/gotosocial#914]
### Describe the bug with a clear and concise description of what the bug is.

This is a known bug, we are opening this bug report to find out how how to deal with this phenomenon exactly.

Maybe it's a matter of updating the local + federated timeline queries to not return any posts above a certain ID (the current ulid plus I don't know, ten minutes?).

### What's your GoToSocial Version?

v0.5.2

### GoToSocial Arch

amd64 docker

### Browser version

Safari

**Comment by tsmethurst** [comment]
Thanks! :)
