### ISSUE TITLE
[bug] Can't unfollow a user who has blocked you

### ISSUE THREAD

**Issue by tinywombat765** [superseriousbusiness/gotosocial#920]
### Describe the bug with a clear and concise description of what the bug is.

When trying to unfollow a user who has blocked you, you get an error instead of unfollowing them.

### What's your GoToSocial Version?

0.5.2

### GoToSocial Arch

amd64

**Comment by tsmethurst** [comment]
I think this is related to https://github.com/superseriousbusiness/gotosocial/issues/1334
