### ISSUE TITLE
[bug] First lookup of a remote account doesn't work, second one does

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#929]
I've seen this in pinafore a few times. When looking up an account your instance doesn't know about yet, the first search returns 0 results, but the second search (literally just clicking the button again immediately) returns the expected account. Argh?

**Comment by xmgz** [comment]
yes, it also happens when searching for single post (using full URL).

**Comment by tsmethurst** [comment]
Seems to have been resolved by https://github.com/superseriousbusiness/gotosocial/pull/1082 :)
