### ISSUE TITLE
[bug] postgres - bun_migrations table is already locked

### ISSUE THREAD

**Issue by dashall** [superseriousbusiness/gotosocial#930]
### Describe the bug with a clear and concise description of what the bug is.

Hello,

the gotosocial instance im running started falling flat in the ground.

Table locked error. 

gotosocial log:
`
timestamp="28/10/2022 14:41:18.286" func=bundb.pgConn level=INFO msg="connected to POSTGRES database"
2022/10/28 14:41:18 error executing command: error creating dbservice: db migration error: migrate: migrations table is already locked (ERROR: duplicate key value violates unique constraint "bun_migration_locks_table_name_key" (SQLSTATE 23505))
`

postgres server log:
`
2022-10-28 14:31:03.969 GMT [220312] ERROR:  duplicate key value violates unique constraint "bun_migration_locks_table_name_key"
2022-10-28 14:31:03.969 GMT [220312] DETAIL:  Key (table_name)=(bun_migrations) already exists.
2022-10-28 14:31:03.969 GMT [220312] STATEMENT:  INSERT INTO bun_migration_locks ("id", "table_name") VALUES (DEFAULT, 'bun_migrations') RETURNING "id"
`

### What's your GoToSocial Version?

0.5.2

### GoToSocial Arch

k8s / docker container

### What happened?

the instance is running for a month now.

today it stopped working because of the table lock.

### What you expected to happen?

table lock gets cleared if its old or the locking party is not existent anymore

### How to reproduce it?

currently the error persists - so i can create a cleaned db dump and send it over.

### Anything else we need to know?

if a db dump is usedful then please notify me soon. 
im fine with having the instance not working for some days but not long term.

**Comment by tsmethurst** [comment]
Heya, this sounds like your instance was interrupted in the middle of migrating or starting up. You should be able to get it unstuck by just deleting the migration lock from the db :) can't remember the exact syntax for the delete off the top of my head but it's something like delete * from bun_migration_locks; Hope that helps!

**Comment by dashall** [comment]
hello @tsmethurst,

truncating bun_migration_locks didnt help and dropping the bun_migration_locks table create another error.

most likley because bun doesnt handle interrupted migrations well and led to this state.

> When a migration fails, Bun still marks the migration as applied so you can rollback the partially applied migration to cleanup the database and try to run the migration again.
https://bun.uptrace.dev/guide/migrations.html#migration-status

anyhow seems like i can setup all from fresh im not up to fiddling in the whole migration to get it repaired.

will leave the bug open since - yeah its a deal breaker.


[#](https://bun.uptrace.dev/guide/migrations.html#migration-groups-and-rollbacks)
