### ISSUE TITLE
[bug] Can't save contact email

### ISSUE THREAD

**Issue by Bauke** [superseriousbusiness/gotosocial#931]
Changing the "contact email" in the admin control panel doesn't seem to save it to the database. The HTTP PATCH and changing other things from the form does work, just not contact email. I've tried other emails like `test@example.org` to see if it was some email validation issue but that also didn't work.

The form data:

```
... other parts omitted
-----------------------------418406927832868131751473918085
Content-Disposition: form-data; name="contact_username"

bauke
-----------------------------418406927832868131751473918085
Content-Disposition: form-data; name="email"

me@bauke.xyz
-----------------------------418406927832868131751473918085--
```

The database columns:

```
gotosocial=# select contact_email,contact_account_username,contact_account_id from instances;
 contact_email | contact_account_username |     contact_account_id     
---------------+--------------------------+----------------------------
               |                          | 01PSSD5S77SQV4ZS4Y8FN0H4QJ
```

* Version: 0.5.2
* Arch: amd64 Docker
* Image: `superseriousbusiness/gotosocial:0.5.2`

**Comment by tsmethurst** [comment]
Thanks for opening, will investigate :)

**Comment by hakamadare** [comment]
i also see this behavior.

version 0.5.2 git-c31f219.
