### ISSUE TITLE
[bug] Pinafore disagrees with toot length when non-ASCII characters are used

### ISSUE THREAD

**Issue by autumnull** [superseriousbusiness/gotosocial#946]
### Describe the bug with a clear and concise description of what the bug is.

Pinafore disagrees with toot length when non-ASCII characters are used

### What's your GoToSocial Version?

v0.5.2

### GoToSocial Arch

armv7 Binary

### Browser version

Firefox 106.0.2 (64-bit)

### What happened?

- Tried to make a long toot from Pinafore with these guys in it: ⎾⎿⏀⏁⏂⏃⏄⏅⏆⏇
- Pinafore says "this toot is a reasonable and fine length, you have several characters to spare!"
- Hit toot button
- Error! 400!
- GoToSocial says I was over the limit!!
- Sad, have to delete characters from my post :pensive: 

### What you expected to happen?

- Either Pinafore says i'm over the limit, or GoToSocial lets me post it.

### How to reproduce it?

Make a post with lots of unicode in it near the character limit.

### Anything else we need to know?

This is probably because GoToSocial is using bytes to measure toot length, and pinafore is using unicode chars. Just a hunch.

**Comment by tsmethurst** [comment]
Ah, thanks! Indeed we just use len(someStringVar)

**Comment by NyaaaWhatsUpDoc** [comment]
Instead we need to be using `len([]rune(str))`
