### ISSUE TITLE
[bug] container in kubernetes cluster with backend error

### ISSUE THREAD

**Issue by enzanto** [superseriousbusiness/gotosocial#950]
### Describe the bug with a clear and concise description of what the bug is.

When trying to set up gotosocial in my kubernetes cluster i get "error creating storage backend: bad file descriptor"

### What's your GoToSocial Version?

0.5.2

### GoToSocial Arch

arm64 docker, and amd64 docker

### What happened?

when trying to start up a pod with the gotosocial image i get error. and container crashes.

> `timestamp="03/11/2022 18:15:02.580" func=bundb.sqliteConn level=INFO msg="connected to SQLITE database"
> timestamp="03/11/2022 18:15:02.853" func=bundb.doMigration level=INFO msg="there are no new migrations to run"
> timestamp="03/11/2022 18:15:02.878" func=bundb.(*adminDB).CreateInstanceAccount level=INFO msg="instance account social.nerdiverset.no already exists"
> timestamp="03/11/2022 18:15:02.898" func=bundb.(*adminDB).CreateInstanceInstance level=INFO msg="instance entry already exists"
> timestamp="03/11/2022 18:15:02.898" func=concurrency.NewWorkerPool level=INFO msg="worker.Worker[messages.FromClientAPI] created with workers=16 queue=1600"
> timestamp="03/11/2022 18:15:02.898" func=concurrency.NewWorkerPool level=INFO msg="worker.Worker[messages.FromFederator] created with workers=16 queue=1600"
> 2022/11/03 18:15:03 error executing command: error creating storage backend: error creating storage backend: bad file descriptor`

### How to reproduce it?

happens everytime i try to start up a pod.

### Anything else we need to know?

i have tried the following:

- changing to another storage location for persistant storage
- scheduling the pod to amd64 architecture
- tried with both postgres(logs said it connected to db. but got the same backend error) and sqlite(see logs above)
- tried the 0.5.1 image

Between each try i wipe the persistent storage and delete persistent volume and persistent volume claim in kubernetes.

**Comment by DysphoricUnicorn** [comment]
what storage backend are you using? It works fine for me using rook-ceph (although I'm on AMD64, so that might be another difference)

**Comment by hnrd** [comment]
I have the same error on longhorn CSI storage, when I declare the PVC ReadWriteMany.
gts works fine on ReadWriteOnce storage, although that disables my backup system, so maybe it's not really that fine :laughing:

**Comment by hnrd** [comment]
fwiw my logs look very similar:
[debuglog.txt](https://github.com/superseriousbusiness/gotosocial/files/9944553/debuglog.txt)

**Comment by manfre** [comment]
This issue might be related to the Dockerfile not creating the `/gotosocial/storage` folder. I ran in to a similar issue when testing out running with generic volume mount. I corrected the issue (for my use case) on [an unrelated PR ](https://github.com/superseriousbusiness/gotosocial/pull/977).

**Comment by enzanto** [comment]
i am using NFS storage.

changing to RWonce did not help.
The dockerfile must create the storage folder. as i can see on my NFS server that the sqlite file is there

**Comment by hnrd** [comment]
your rwonce pvc is mounted by NFS, too?

I do not have issues with the storage folder creation either

**Comment by enzanto** [comment]
yes, the rwonce is also NFS.
I've also tried using another computer as NFS host for testing purposes.

**Comment by NyaaaWhatsUpDoc** [comment]
This is a case of the used file-lock syscall not working on NFS mounts. It is a bug I will get to hopefully sometime soon

**Comment by andrewwippler** [comment]
In the meantime, one could fix this issue by modifying the NFS mount options:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gts-pvc
  namespace: web
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: X.X.X.X
    path: "/k8s/gts"
  mountOptions:
    - vers=3
    - tcp
    - local_lock=posix
 ```

**Comment by tsmethurst** [comment]
@NyaaaWhatsUpDoc did we ever fix this one? I can't remember if something else addressed it already.

**Comment by andrewwippler** [comment]
> @NyaaaWhatsUpDoc did we ever fix this one? I can't remember if something else addressed it already.

It was a problem in the 0.9.0 release for me. After configuring the NFS options, the program runs without complications. Even 0.10.0 is running smoothly. 

As an affected user, I would rather see this marked as wontfix so that coding efforts are spent elsewhere.

**Comment by NoraCodes** [comment]
If anyone is looking into this because they're trying to configure GTS on NixOS, you may also want to check on the status of https://github.com/NixOS/nixpkgs/issues/290332 before committing any more time to solving this problem.
