### ISSUE TITLE
Bad Request: scopes must be less than 64 bytes when trying to sign in to brid.gy

### ISSUE THREAD

**Issue by jk-na** [superseriousbusiness/gotosocial#957]
As per https://github.com/snarfed/bridgy/issues/1340 when I try to log in to brid.gy with my GtS account, an error message is returned to the brid.gy start page ```Bad Request: scopes must be less than 64 bytes```

@snarfed investigated and found that the error is coming from my gts server and supplied the scope string in the linked issue: 

```read+read:accounts+read:blocks+read:bookmarks+read:favourites+read:filters+read:follows+read:lists+read:mutes+read:notifications+read:search+read:statuses+write+write:accounts+write:blocks+write:bookmarks+write:favourites+write:filters+write:follows+write:lists+write:media+write:mutes+write:notifications+write:reports+write:statuses+follow+push```

Would it be possible to raise the 64 bytes limit?

**Comment by tsmethurst** [comment]
yep! will do that, two ticks..
