### ISSUE TITLE
[bug] lost+found directory in storage disliked

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#964]
### Describe the bug with a clear and concise description of what the bug is.

    2022/11/05 23:41:45 error executing command: error creating dbservice: db migration error: error creating storage backend: open /opt/GtS/storage/lost+found: permission denied

Probably because I put the storage on an ext4 filesystem of its own, to easier manage quota.

### What's your GoToSocial Version?

gotosocial version 0.5.2 git-c31f219

### GoToSocial Arch

amd64

### Browser version

none

### What happened?

Failed to create initial user.

### What you expected to happen?

Ignores dirents in storage not created by GtS

### How to reproduce it?

Put storage on a fresh ext4 fs

**Comment by NyaaaWhatsUpDoc** [comment]
Oh now this is an interesting one! I'll take a look into this tomorrow :)

**Comment by NyaaaWhatsUpDoc** [comment]
@mirabilos what permissions does that dir have? I'm assuming it is default `root:root 0700`?

It is a little bit of a tricky situation here. For the storage backend, we're actually using a library of my own creating, https://codeberg.org/gruf/go-store, which was _initially_ intended to be a very simple key-value store that stores direct to the filesystem. But with the per-file locks and very simple storage mechanism it turned out to be a good fit for an overall storage backend in gotosocial to prevent race condition weirdness.

The reason this error will be thrown, is that upon open the key-value store will attempt to perform a `clean`, that is it goes through the store directory and removes empty folders. Though typing this out now I'm realising in our particular usecase here this step should be skipped. I love to end up rubber-duck debugging myself :D

**Comment by NyaaaWhatsUpDoc** [comment]
@mirabilos would you be able to see if this fixes your issue? https://github.com/superseriousbusiness/gotosocial/pull/972

**Comment by mirabilos** [comment]
kim dixit:

***@***.*** what permissions does that dir have? I'm assuming it is
***@***.*** `root:root 0700`?

Yes, exactly. It was a freshly created filesystem specifically for
this purpose.

>It is a little bit of a tricky situation here. For the storage backend,
>we're actually using a library of my own creating,

Ah, that means though it’s fixable ☻

>The reason this error will be thrown, is that upon open the key-value
>store will attempt to perform a `clean`, that is it goes through the
>store directory and removes empty folders. ... Though typing this out
>now I'm realising in our particular usecase here this step should be
>skipped. I love to end up rubber-duck debugging myself :D

Maybe not, but skip inaccessible directories, or blacklist lost+found
specifically?

***@***.*** would you be able to see if this fixes your issue?

Sorry, I’m not in a position to build software written in Issue9.

I’ll wait for the next release, run mklost+found(8) after updating
and see whether it occurs again. For now I just deleted this directory;
e2fsck(8) will have to do without, if needed.

I’m wondering whether (and how) to back up the storage directory.
It being a mix of my own content, retweeted content (which from the
GtS PoV is, of course, my own), boosted content (maybe?), and content
downloaded (cached) because others posted it, this has a chance of
exploding backup storage requirements. Maybe I’ll just keep only the
latest backup, maybe two, or something… (the machine I use is already
backed up with restic, but I’m splitting this filesystem deliberately).

bye,
//mirabilos
-- 
Gestern Nacht ist mein IRC-Netzwerk explodiert. Ich hatte nicht damit
gerechnet, darum bin ich blutverschmiert… wer konnte ahnen, daß SIE so
reagier’n… gestern Nacht ist mein IRC-Netzwerk explodiert~~~
	(as of 2021-06-15 The MirOS Project temporarily reconvenes on OFTC)

**Comment by tsmethurst** [comment]
Is this fixed in 0.6.0? :)

**Comment by mirabilos** [comment]
tobi dixit:

>Is this fixed in 0.6.0? :)

Thanks for reminding me to check. Yes, it is (I even tried with
a fresh dummy ext2 on loopback), and after running mklost+found
on the prod fs, things still work.

I did see over 15k dirents though and vaguely recall a 32k limit
in ext2, so maybe splitting them similar to git objects are may
(possibly) be necessary to scale?

But first have a nice yuletide vacation!

bye,
//mirabilos
-- 
[...] if maybe ext3fs wasn't a better pick, or jfs, or maybe reiserfs, oh but
what about xfs, and if only i had waited until reiser4 was ready... in the be-
ginning, there was ffs, and in the middle, there was ffs, and at the end, there
was still ffs, and the sys admins knew it was good. :)  -- Ted Unangst über *fs
