### ISSUE TITLE
[feature] Lists

### ISSUE THREAD

**Issue by zladuric** [superseriousbusiness/gotosocial#968]
### Is your feature request related to a problem ?

I want to be able to assign the people I follow into lists (or alternatively, the people, tags and other "followable" things). Mastodon has [lists](https://docs.joinmastodon.org/methods/timelines/lists/), but gotosocial seems not to.

### Describe the solution you'd like.

The simplest would probably be to just follow the Mastodon API written above, but I can imagine other ways for this feature to work.

Ideally it should let me:

- list, create, review, rename and remove lists
- add people to lists
  - [optional]: regardless of follow status, unlike mastodon (UI) seems to work
- get a list timeline (only posts from items on the list 
- [optional]: add hashtags to lists
- [super stupid and crazily optional, but maybe a future idea]: add custom filter to lists, e.g. only posts written between 7 and 9 am over a cup of coffee but only if their cat feels well
- [possibly doable, probably stupid]: mention list, so it posts to all of their inboxes (e.g. people's inboxes go directly, but e.g. hashtags would just make a public hashtagged post?)

### Describe alternatives you've considered.

It appears that there's a /lists endpoint on my instance (essentially a 0.5.0 built on my own), and it returns an empty array. But -X POSTing to that endpoint returns a 404.

The docs site does not mention lists (that I could find).

### Additional context.

This is not an urgent request, but I noticed it is missing, so I thought I kick off the discussion and keep it on the radar (or find out that this was considered and discarded). Feel free to close this issue, convert it to a placeholder, edit it or whatever.

**Comment by tsmethurst** [comment]
Heya! It's currently on the roadmap for the beginning of next year :) https://github.com/superseriousbusiness/gotosocial/blob/main/ROADMAP.md#q1-2023

But good to have an issue open for it too, so we can discuss implementation here :+1:
