### ISSUE TITLE
[feature] Option to redirect instance home page to profile page (for single-user instances)

### ISSUE THREAD

**Issue by da2x** [superseriousbusiness/gotosocial#975]
### Is your feature request related to a problem ?

The front page is useless in a single-user set-up, and I’d like an option to redirect visitors directly to my profile instead.

### Describe the solution you'd like.

An option to enable redirecting the front page (/) to a profile (/@me).

### Describe alternatives you've considered.

Configuring Apache or another intermediary proxy server to match `^/$` and redirect it to the desired profile. However, I have no other use for an intermediary proxy server at this time; and I don’t know if this will break any features or service discovery. So, I’d appreciate this being a proper feature instead. It should be a common desire among single-user instance users.

**Comment by NyaaaWhatsUpDoc** [comment]
this is actually already developed and awaiting release 😄

**Comment by manfre** [comment]
The environment variable `GTS_LANDING_PAGE_USER=me`  would redirect to `/@me`. Another related/useful config is `GTS_ACCOUNT_DOMAIN` for when you're running in a sub-domain, but want your identity to use the parent domain.

**Comment by xplosionmind** [comment]
Hi, sorry for the dumb question, but where and how can I change environment variables?
