### ISSUE TITLE
[bug] Profile meta fields don’t persists

### ISSUE THREAD

**Issue by da2x** [superseriousbusiness/gotosocial#979]
### Describe the bug with a clear and concise description of what the bug is.

I can add metadata key–value fields (often used to add links to profiles) using the UIs in the Tusky and Mastodon apps for Android. The request is accepted by the server, but the fields don’

### What's your GoToSocial Version?

0.5.2 git-c31f219

### GoToSocial Arch

arm64 Binary

### Browser version

Tusky 19, Mastodon.apk 1.1.3

### What happened?

I can save the meta fields from the clients, but they don’t appear on the profile or profile editing screen in compatible clients. I can’t find them in the database either.

### What you expected to happen?

The profile meta fields should persist and be displayed in compatible clients.

### How to reproduce it?

1. Set up GoToSocial.
2. Login from the Tusky or Mastodon apps.
3. Edit your profile, and add a meta key–value pair to your profile.
4. Save the changes.

### Anything else we need to know?

I’m grateful that your project exists and provides a lighter weight alternative to Mastodon.

**Comment by tsmethurst** [comment]
This is normal, it's just not implemented yet :)

**Comment by tsmethurst** [comment]
Will be closed when we do https://github.com/superseriousbusiness/gotosocial/issues/1256
