### ISSUE TITLE
[bug] Support create on article type

### ISSUE THREAD

**Issue by agjohnson** [superseriousbusiness/gotosocial#998]
### Describe the bug with a clear and concise description of what the bug is.

When publishing a multiple paragraph post from a writefreely instance, gotosocial emits a 400 Bad Request with the follow error details:

```
Bad Request: activityCreate: one or more errors while processing activity: received an object on a Create that we couldn't handle: Article
```

There is nothing posted to my inbox in this case, but on Mastodon, the activity is in my inbox.

I haven't touched the code here yet, but saw mention of Article object types scanning really quick. I suspect I'm incorrect and this could be considered a feature request instead though.

### What's your GoToSocial Version?

0.5.1-SNAPSHOT git-ee6a0a1

### GoToSocial Arch

Docker, amd64

### Browser version

Firefox 103.0.1 (64-bit)

### What happened?

I published a post on a writefreely instance which contained two large paragraphs. The post did not end up in my inbox on my gotosocial instance, but did show up in my inbox on a Mastodon account.

When I publish a short post in writefreely, this post *does* show up in my inbox on both instances however.

### What you expected to happen?

I expected a truncated post to be in my inbox with a link to the article.

**Comment by agjohnson** [comment]
My golang is crusty at best, so I'm not much use at patching this, but let me know if I can help with more info/testing here!

**Comment by tsmethurst** [comment]
This has been closed in a recent PR (I can't remember which one off the top of my head), but we should support creation of Article types now.
